### ISSUE TITLE
[Packaging Request] Linux binaries in 'AppImage' format

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1748]
*Issue migrated from trac ticket # 1748*

**component:** packaging | **priority:** major

#### 2018-01-19 18:29:54: pdfkungfoo created the issue

___
> I would like to use the latest+greatest Xpra version on Debian Linux (Stretch) and openSUSE Tumbleweed.
> 
> However, on Debian it is version 0.17.6 only which I can obtain through the official repository. For Tumbleweed, I cannot find xpra at all!
> 
> An very user-friendly option would be a Linux binary packaged as an "AppImage". If you never heard of that: you can compare this to a .dmg package for macOS, with the difference that:
> 
> - where the DMG requires (a very simple) installation process, the AppImage does not need "installation" at all (only setting the executable bit) and
> - where the installed .dmg expands into an "*.app" directory, an AppImage remains a compressed SquashFS file system packaged into a single file even during execution time (when it is automatically FUSE-mounted to a temporary mount point and run via simple embedded "AppRun" helper binary).
> 
> AppImages implement the elegant *"One App == One File"* paradigm. They have the following properties:
> 
> - do not need root privileges to get them working;
> - do not need a package management system to get them "installed";
> - do not need any pre-requisite "platform" or package manager to work;
> - one and the same AppImage can work on multiple Linux distributions released in the last 3-4 years;
> - AppImages work from any location (even thumbdrives or remotely mounted SMB/Samba, SSHFS, NFS or other shares);
> - AppImages can be automatically upgraded to the newest version via a (zsync-powered) binary delta download mechanism if the AppImage packagers embed a suitable "updateinfo" string into the package).
> 
> AppImages are relatively simple to package with the help of the AppImageKit tools provided on GitHub here: [AppImageKit on GitHub](https://github.com/AppImage/AppImageKit) and [linuxdeployqt on GitHub](https://github.com/probonopd/linuxdeployqt).
> 
> I'm sure the AppImageKit developers hanging around in IRC will be happy to help should you be interested to implement this: [#AppImage channel on Freenode](https://webchat.freenode.net/?channels=appimage).
>

**Comment by totaam** [comment]
Apart from the important points raised above, the best summary of why this is unlikely to happen is [Flatpak Is Not the Future](https://ludocode.com/blog/flatpak-is-not-the-future)

**Comment by brechtm** [comment]
Related: I tried building Xpra using spack, but [got stuck at the pycairo dependency](https://github.com/spack/spack/discussions/35416).
