### ISSUE TITLE
Continuous Spamming of Network Quality Issues

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1855]
*Issue migrated from trac ticket # 1855*

**component:** client | **priority:** major | **resolution:** fixed

#### 2018-05-28 13:34:46: stdedos created the issue

___
> Windows 10 (1803/17134.48) (connecting wirelessly @ 240 Mbit/s) connecting to Ubuntu 16.04.3 (Ethernet, 1 Gbit/s)
> ```
> Xpra gtk2 client version 2.3-19246 64-bit
>  running on Microsoft Windows 10
> GStreamer version 1.14.0 for Python 2.7.15 64-bit
>  desktop size is 1600x900 with 1 screen:
>   2\WinSta-Default (423x238 mm - DPI: 96x96) workarea: 1600x860
>     DISPLAY1 (310x174 mm - DPI: 131x131)
>  downscaled by 75%, virtual screen size: 2133x1200
>   2\WinSta-Default (423x238 mm - DPI: 128x128) workarea: 2133x1147
>     DISPLAY1 (310x174 mm - DPI: 174x175)
>  keyboard settings: layout=us
> enabled remote logging
> Xpra shadow server version 2.3-19255 64-bit
>  running on Linux Ubuntu 16.04 xenial
> setting scaling to 67%:
> sending updated screen size to server: 2402x1351 with 1 screens
>   2\WinSta-Default (423x238 mm - DPI: 144x144) workarea: 2402x1291
>     DISPLAY1 (310x174 mm - DPI: 196x197)
> ```
> 
> After some time, I keep getting "Network Performance Issue", "Your connection is struggling to keep up".
> 
> It doesn't matter if I press "Lower bandwidth limit" or "Cancel". I've tried both, it keeps coming up. I've tried to change the settings to the tray icon (Speed / Quality), but nothing happens. *However, I feel that it's possible that tray icon is not listening to me i.e. it does not apply my options.*
> 
> Trying to WinSCP a 1GB file I get a speed ~7 - 22 MB/s, so, I wouldn't say that actual network speed is problematic

**Comment by weberjn** [comment]
Problem still there with xpra v4.2-r0, FreeBSD 13.0-RELEASE-p3. Very frequent bandwidth warnings, both on wifi and ethernet.
The XPRA_ACK_TOLERANCE=1000 workaround solves the problem for me.

**Comment by totaam** [comment]
@weberjn is there anything specific that triggers it?
Any useful info when running with `-d bandwidth`?

Please try with 4.2.1

**Comment by weberjn** [comment]
@totaam I append the log. This was current HTML5 Client in Chrome W10, ethernet connection to xpra on local FreeBSD. 
Go to welt.de and surf a couple of articles.
[100.log](https://github.com/Xpra-org/xpra/files/6872789/100.log)

Cannot try 4.2.1, yet, I use what I get from pkg. I am good with XPRA_ACK_TOLERANCE=1000
