### ISSUE TITLE
packaging for mingw64 / MSYS2

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1883]
*Issue migrated from trac ticket # 1883*

**component:** packaging | **priority:** major | **resolution:** fixed

#### 2018-06-21 08:52:01: antoine created the issue

___
> We should be able to submit this as a package to MSYS2: [https://github.com/msys2/msys2/wiki/Creating-Packages].

**Comment by Biswa96** [comment]
New source tarballs in xpra.org/src do not contain xpra/platform/win32/setappid{.cpp, .h} files.

**Comment by totaam** [comment]
@Biswa96 thanks for the heads up.
Fixed by the commit above, these will be included in future releases.
