### ISSUE TITLE
hidpi awareness for macos

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#1933]
See [Is HiDPI possible?](https://github.com/JAremko/docker-x11-bridge/issues/4)

See also [Automatically scale windows?](https://bugs.freedesktop.org/show_bug.cgi?id=93315) - similar problem for wayland vs x11 

[Optimizing for High Resolution](https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html#//apple_ref/doc/uid/TP40012302-CH7-SW1)

**Comment by mbac** [comment]
> #### 2020-09-30 11:45:37: hawski commented
> > I scaled 2x render_size in init from xpra/client/gl/gl_window_backing_base.py Then it looks good on single display. I will check later how it works with backingScaleFactor, but it's good enough for me now.
> > I have massive lag on local network, but it is unrelated to my changes as far as I see, because the same lag is noticeable with –opengl=no.

Hi,

Could you explain exactly what is meant by “scaling 2x render_size”? I’d like to try this workaround…

**Comment by totaam** [comment]
@mbac hawski never replied and isn't subscribed to this ticket.
He never shared his tiny change and I don't have the hardware to validate any changes I could make.

**Comment by hadrianw** [comment]
Oh, hello. I'm here. I manually edited /Applications/Xpra.app//Contents/Resources/lib/python3.8/xpra/client/gl/gl_window_backing_base.py

```
--- /Applications/Xpra.app/Contents/Resources/lib/python3.8/xpra/client/gl/gl_window_backing_base.py
+++ /Applications/Xpra.app/Contents/Resources/lib/python3.8/xpra/client/gl/gl_window_backing_base.py	2020-09-29 13:27:52.000000000 +0200
@@ -325,7 +325,7 @@
     def init(self, ww : int, wh : int, bw : int, bh : int):
         #re-init gl projection with new dimensions
         #(see gl_init)
-        self.render_size = ww, wh
+        self.render_size = ww * 2, wh * 2
         if self.size!=(bw, bh):
             self.gl_setup = False
             oldw, oldh = self.size
```

I still use this workaround and did not work further on improving the change.

**Comment by totaam** [comment]
This change will upscale the window, but this will not take advantage of the extra pixel density available.
For that to work, we would need to also upscale the screen dimensions sent to the server - but not the DPI!
Then, I believe that instead of doubling the `render_size`, the client should halve the window size.
I need to find a way to test this.

**Comment by hadrianw** [comment]
I had quite a dirty Xpra.app after my debugging. I diffed python sources against Xpra 4.0.4 source and forgot to mention that the previous patch is also crucial for it to work. So overall:

1. I spawn Xpra like that: xpra shadow --printing=no --opengl=yes --desktop-scaling=2/3 --swap-keys=no ssh:hadrian@karton.local:0

Without my changes I get this:

<img width="1440" alt="Screenshot 2021-06-07 at 17 37 55" src="https://user-images.githubusercontent.com/154291/121049028-a10f2900-c7b7-11eb-8be1-fb3a69ed738e.png">

3. Then I modify things with this patch (I don't know if it is clean, but changes are small enough to do this manually):

```
--- xpra-4.0.4/xpra/client/gl/gl_window_backing_base.py	2020-05-10 19:00:53.000000000 +0200
+++ /Applications/Xpra.app/Contents/Resources/lib/python3.8/xpra/client/gl/gl_window_backing_base.py	2021-06-07 17:46:33.000000000 +0200
@@ -325,7 +325,7 @@
     def init(self, ww : int, wh : int, bw : int, bh : int):
         #re-init gl projection with new dimensions
         #(see gl_init)
-        self.render_size = ww, wh
+        self.render_size = ww * 2, wh * 2
         if self.size!=(bw, bh):
             self.gl_setup = False
             oldw, oldh = self.size
--- xpra-4.0.4/xpra/platform/darwin/gl_context.py	2020-05-10 19:00:55.000000000 +0200
+++ /Applications/Xpra.app/Contents/Resources/lib/python3.8/xpra/platform/darwin/gl_context.py	2021-06-07 17:38:23.000000000 +0200
@@ -150,6 +150,7 @@
         if not self.window_context:
             self.nsview_ptr = nsview_ptr
             nsview = objc.objc_object(c_void_p=nsview_ptr)
+            nsview.setWantsBestResolutionOpenGLSurface_(True)
             log("get_paint_context(%s) nsview(%#x)=%s", gdk_window, nsview_ptr, nsview)
             if self.alpha and enable_transparency:
                 self.gl_context.setValues_forParameter_([0], NSOpenGLCPSurfaceOpacity)
```

4. I spawn it the same as in point 1. That's the result:

<img width="1440" alt="Screenshot 2021-06-07 at 17 38 38" src="https://user-images.githubusercontent.com/154291/121050478-e4b66280-c7b8-11eb-884d-fd96d65bb15e.png">

> Then, I believe that instead of doubling the render_size, the client should halve the window size.
I need to find a way to test this.

Tell me what to modify and I'll check. I lost my way around the code.

**Comment by totaam** [comment]
Ah, now I see!
You're downscaling the server side screen by using `--desktop-scaling=2/3` and that's why your change actually does work! It can only work if the server is sending a higher resolution than that of the client's window.

And starting with xpra 4.2 servers, this won't work any more because the server will downscale the image to save bandwidth  - since it is not aware that the client really will make use of the extra pixels, the details are in #2052.
The commit above now allows you to switch off this feature with `XPRA_DOWNSCALE=0`. (server-side switch)

> Tell me what to modify and I'll check. I lost my way around the code

Well, for your use-case, there isn't a lot more needed because the window has a fixed size and there is no DPI synchronization to do in shadow mode.
(obviously, the code would need to be cleaned up a bit to get the real scaling values)

The difficulty is to make it work for seamless mode. Simply using the extra pixels by default would make all remote windows shrink by 50%, making them hard to read.
Increasing the DPI accordingly doesn't work very well as the application support is spotty at best. (and most applications need to be started after the new DPI is applied or they don't take it into account)
Many applications would still look too small. Others would be a mishmash of small and large widgets.
The best way forward may be to expose this scaling factor to the server side so that it can decide what to do. For example: using the value when making any scaling adjustments, like disabling the automatic downscaling that was added in 4.2.

**Comment by jaeyeun97** [comment]
Any updates on this? I'm also getting 36x31 dpi downscaling when I access my linux Xpra server from a MacOS client.

**Comment by totaam** [comment]
@jaeyeun97 I think that the warning you are talking about has nothing to do with hidpi awareness, see https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md

**Comment by vkz** [comment]
Hi all. Not exactly clear how to get that magical HIDPI on the Mac. Text looks rugged and far from crisp or even decent. 

Could someone post a step by step solution? Way I understood it from previous conversation:
- you start server side with `--desktop-scaling=2/3`
- apply patch to `xpra/client/gl/gl_window_backing_base.py`
- apply patch to `xpra/platform/darwin/gl_context.py`
But then @totaam mentions it won't work past 4.2 without `XPRA_DOWNSCALE=0`, which if I read Python code correctly means setting shell env variable.

Or am I missing some recent option or flag or setting that I can use to avoid the above dance?
Thank you

**Comment by totaam** [comment]
@vkz : 
* this only works for `xpra shadow`
* `--desktop-scaling=2/3` is a client side switch
* `XPRA_DOWNSCALE=0` is a server side switch

There has been no progress on this.
To make this work properly, I would need hardware to test and time to implement.

**Comment by vkz** [comment]
ah, I see. So, to clarify, as of now there is no way to get HIDPI on Mac OSX clients? 
Not even talking retina here. I've been trying it on the external Samsung U32'' which can do 3840x2160 (but I use scaled to look like 1920x1080 else its too tiny).

Is this specific to XPRA implementation? As in, there's a chance one could get crisper image going with X server + Xquartz client. Of course we'd be missing on all the nice things XPRA gives us like clipboard sharing and persistent sessions etc.

**Comment by totaam** [comment]
> So, to clarify, as of now there is no way to get HIDPI on Mac OSX clients?

Only with `xpra shadow` and steps above.

> Is this specific to XPRA implementation?

Yes.

> As in, there's a chance one could get crisper image going with X server + Xquartz client

Perhaps, I have no idea.

**Comment by vkz** [comment]
ok, I feel stupid but it only just occurred to me that HIDPI you speak of probably refers to Mac Retina displays which I believe >220ppi, which is not what I'm talking about. My Mac indeed has retina, but I'm running XPRA client on the external 4K display 3840 x 2160 which at 32inch diagonal translates to something like 142ppi. If I made a mistake and butted in the wrong convo, I apologies. Should I move my questions into a separate issue?

**Comment by totaam** [comment]
> Should I move my questions into a separate issue?

Probably, it doesn't hurt to open a new issue with your details in it. Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
See https://github.com/Xpra-org/xpra/issues/4017#issuecomment-1757407309

**Comment by totaam** [comment]
Perhaps we can deal with this as part of #2467
Some links:
* [wantsBestResolutionOpenGLSurface](https://developer.apple.com/documentation/appkit/nsview/1414938-wantsbestresolutionopenglsurface)
* [PyOpenGL on a Macbook retina display](https://stackoverflow.com/questions/14784317/)

**Comment by totaam** [comment]
Is this still an issue, I would have thought that 854f012ac91137b96591a82087719d9e1463eb97 fixed this.

**Comment by totaam** [comment]
Probably solved by https://github.com/Xpra-org/xpra/issues/4167#issuecomment-2219530807

**Comment by ShadowJonathan** [comment]
Can confirm this has fixed my (direct) issues, i'll have to use the desktop client more to see if there are any more bugs, but thank you for fixing this :)
