### ISSUE TITLE
intellij pop-ups appear in the wrong place sometimes

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2008]
*Issue migrated from trac ticket # 2008*

**component:** java | **priority:** minor

#### 2018-10-25 11:17:45: facboy created the issue

___
> xpra occasionally lose track of where Intellij's pop-ups are supposed to appear. eg you right-click and the pop-up appears way over on the right of the screen instead of under the mouse.  Resizing the window seems to fix it for a while.
> 
> I am running two monitors on the client if that makes a difference, and I have multiple intellij windows (different projects) open.

**Comment by stdedos** [comment]
It sounds like a duplicate of one of my tickets (I'll link if I find it)

**Comment by totaam** [comment]
I'm not sure if this is going to fix the popups, but the fix above ensures that the window is in the same place it was before when re-attaching to the same session.
