### ISSUE TITLE
xpra shadow raises "Error parsing xdg menu data"

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2174]
*Issue migrated from trac ticket # 2174*

**component:** server | **priority:** minor | **resolution:** invalid

#### 2019-02-25 08:27:28: stdedos created the issue

___
> It feels related to #2153, but no idea if it is. Search returns nothing.
> 
> 
> ```
> 2019-02-25 10:21:05,810 xpra GTK2 shadow version 2.5-21828 64-bit
> 2019-02-25 10:21:05,810  running with pid 1055 on Linux Ubuntu 16.04 xenial
> ```

**Comment by totaam** [comment]
Some OSes don't set things up correctly: [problem getting application data from DE](https://lists.devloop.org.uk/pipermail/shifter-users/2022-October/002946.html)
We already try various magic values that might help make it load the menus without errors:
https://github.com/Xpra-org/xpra/blob/b1454da8599e455c69c7200f886849a4a6c0b6b7/xpra/platform/xposix/menu_helper.py#L379-L382

**Comment by brainchild0** [comment]
What component, functionality, operation, or so on, should be included in the OS for the menu to appear correctly?

I have not yet understood how all the pieces of this problem fit together, and am simply wondering, if I imagine myself as the OS provider, what change I would have to make to the OS for the relevant support to be provided.

**Comment by brainchild0** [comment]
> We already try various magic values that might help make it load the menus without errors

Is there any reason for not at least picking *some*  file name rather than none? At the moment, I have *no* menu available. Surely, there are sensible changes that are unlikely to degrade the situation further, right?

**Comment by brainchild0** [comment]
Ultimately, it not the server receiving the request for the Xpra session that ought to determine the desktop environment, but in my view, the client, which is where the end user would be situated. Is it sensible to approach the question of choosing a desktop environment as a user preference, rather than one imposed by the remote site?

**Comment by totaam** [comment]
> What component, functionality, operation, or so on, should be included in the OS for the menu to appear correctly?

The ability to use the library, out of the box, without relying on the `XDG_MENU_PREFIX` environment variable being set to a specific value.

> Is there any reason for not at least picking some file name rather than none?

That's exactly what we try to do, see the comment just above: https://github.com/Xpra-org/xpra/issues/2174#issuecomment-1292012681
We try `gnome-`, etc..

> At the moment, I have no menu available. 
> Surely, there are sensible changes that are unlikely to degrade the situation further, right?

I literally have no idea what these "sensible" changes would be.
We can keep adding strings to our guess list of values to try when the defaults don't work out of the box.
Feel free to provide the prefix that does work on your specific system setup.

> Is it sensible to approach the question of choosing a desktop environment as a user preference, rather than one imposed by the remote site?

No. The html5 client, MS Windows and MacOS desktops don't have the concept of a desktop environment.
The server needs to be able to use the `xdg` library without making any assumptions about what the client may or may not have in terms of DE.

**Comment by brainchild0** [comment]
> > What component, functionality, operation, or so on, should be included in the OS for the menu to appear correctly?
> 
> The ability to use the library, out of the box, without relying on the `XDG_MENU_PREFIX` environment variable being set to a specific value.

Yes, but from the standpoint of asking the question, such an answer is circular. What I am seeking  to understand is  what actual  component must be inserted into the distribution's file tree, or what must be changed in an existing file or utility, that would bring about such a functional  change.


> That's exactly what we try to do, see the comment just above: [#2174 (comment)](https://github.com/Xpra-org/xpra/issues/2174#issuecomment-1292012681) We try `gnome-`, etc..

> 
> I literally have no idea what these "sensible" changes would be. We can keep adding strings to our guess list of values to try when the defaults don't work out of the box. Feel free to provide the prefix that does work on your specific system setup.

Not quite.  I intended to suggest  literally *any* file, whether or not blessed by a prescribed list of prefixes.

(That is to say nothing of the observation that Xfce4 is conspicuously absent from the list. If it were given, then connections to my server would not experience  the reported problem.) 


> No. The html5 client, MS Windows and MacOS desktops don't have the concept of a desktop environment. The server needs to be able to use the `xdg` library without making any assumptions about what the client may or may not have in terms of DE.

Again, not quite what I meant. I was not suggesting that the   choice of desktop environment for the server   should try match the one used on the client, any more than I would suggest that the password given  for server login must match the local password for the same user. I was simply suggesting  that  which desktop environment  to prefer for the remote host, among those available,    might be a matter of preference, by the user invoking the session from the client.

**Comment by totaam** [comment]
> such an answer is circular

No comment.
> What I am seeking to understand is what actual component must be inserted into the distribution's file tree

Perhaps you should ask your distribution / `python-xdg` / desktop environment instead as this is not an xpra problem.
You can clearly see this by running the command from a clean environment (ie: `ssh` session) on your system:
```shell
python -c "from xdg.Menu import parse;parse()"
```
> Not quite.
> (..)

Again, if your distribution wants to fix things in a different / better way, go right ahead.

> I was simply suggesting...

This would be "nice" but does literally nothing to solve the bug discussed here.

I am going to lock this issue because it is meant as a quick reference on the source of this common problem and is quickly devolving into bike shedding.
