### ISSUE TITLE
Theming is weird in 2.5 on Fedora 30 MATE

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2298]
*Issue migrated from trac ticket # 2298*

**component:** core | **priority:** major | **resolution:** needinfo

#### 2019-05-17 04:49:44: turkstra created the issue

___
> When running xpra 2.5 on Fedora 30 (or Fedora 29) with MATE, the theming of the captive application(s) is various degrees of weird.
> 
> For some things, like Firefox, it seems to just be the scrollbar. For others like mate-terminal and especially Evolution (I didn't include screenshots for Evolution for privacy reasons, but I could provide them if it would help), other parts of the UI are off. I've included screenshots of mate-terminal and firefox in and outside of xpra. As you can see, the tabs are gray. This kind of weirdness makes interacting with Evolution particularly difficult, as it is hard to tell which "buttons" are being selected.
> 
> On Fedora 29, I can downgrade back to xpra 2.4 and everything goes back to normal.
> ```
> $ rpm -qa | grep xpra
> xpra-2.5.0-1.fc30.x86_64
> ```
> ```
> $ xpra start :100 --start-child=mate-terminal
> Entering daemon mode; any further errors will be reported to:
>   /run/user/1000/xpra/:100.log
> ```
> ```
> $ xpra attach :100
> 2019-05-16 23:14:25,127 Xpra GTK3 client version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit
> 2019-05-16 23:14:25,128  running on Linux Fedora 30 Thirty
> 2019-05-16 23:14:25,129  window manager is 'Metacity (Marco)'
> 2019-05-16 23:14:26,425 GStreamer version 1.16.0 for Python 3.7.3 64-bit
> 2019-05-16 23:14:26,616  keyboard settings: rules=evdev, model=microsoft4000, layout=us
> 2019-05-16 23:14:26,619  desktop size is 5120x1600 with 1 screen:
> 2019-05-16 23:14:26,619   :0.0 (1355x423 mm - DPI: 95x96) workarea: 5120x1550 at 0x25
> 2019-05-16 23:14:26,619     DP-4 2560x1600 at 2560x0 (641x401 mm - DPI: 101x101)
> 2019-05-16 23:14:26,619     DP-6 2560x1600 (641x401 mm - DPI: 101x101)
> 2019-05-16 23:14:35,006 enabled fast mmap transfers using 256MB shared memory area
> 2019-05-16 23:14:35,006 enabled remote logging
> 2019-05-16 23:14:35,006 Xpra GTK3 X11 server version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit
> 2019-05-16 23:14:35,007  running on Linux Fedora 30 Thirty
> 2019-05-16 23:14:35,012 Attached to :100
> 2019-05-16 23:14:35,012  (press Control-C to detach)
> 
> 2019-05-16 23:14:35,128 server does not support xi input devices
> 2019-05-16 23:14:35,128  server uses: xtest
> ```
> 
> Server log:
> ```
> [31m2019-05-16 23:14:22,231 Error: cannot enable SSH socket upgrades:[0m
> [31m2019-05-16 23:14:22,231  No module named 'paramiko'[0m
> 2019-05-16 23:14:22,233 cannot access python uinput module:[0m
> 2019-05-16 23:14:22,233  No module named 'uinput'[0m
> 
> X.Org X Server 1.20.4
> X Protocol Version 11, Revision 0
> Build Operating System:  4.20.13-200.fc29.x86_64 
> Current Operating System: Linux endor.turkeyland.net 5.0.16-300.fc30.x86_64 #1 SMP Tue May 14 19:33:09 UTC 2019 x86_64
> Kernel command line: BOOT_IMAGE=(hd2,gpt6)/vmlinuz-5.0.16-300.fc30.x86_64 root=/dev/mapper/endor-root ro rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 rd.lvm.lv=endor/root rd.luks.uuid=luks-12e16eea-2303-4115-a58b-af4c5f2210c0 rd.lvm.lv=endor/swap resume=/dev/mapper/endor-swap nomodeset rhgb quiet
> Build Date: 29 March 2019  05:04:12AM
> Build ID: xorg-x11-server 1.20.4-3.fc30 
> Current version of pixman: 0.38.0
> 	Before reporting problems, check http://wiki.x.org
> 	to make sure that you have the latest version.
> Markers: (--) probed, (**) from config file, (==) default setting,
> 	(++) from command line, (!!) notice, (II) informational,
> 	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
> (++) Log file: "/run/user/1000/xpra/Xorg.:100.log", Time: Thu May 16 23:14:22 2019
> (++) Using config file: "/etc/xpra/xorg.conf"
> (==) Using system config directory "/usr/share/X11/xorg.conf.d"
> 2019-05-16 23:14:22,836 created unix domain socket: /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:14:22,836 cannot create group socket '/run/xpra/endor.turkeyland.net-100'[0m
> 2019-05-16 23:14:22,836  [Errno 13] Permission denied[0m
> 2019-05-16 23:14:22,837  user 'turkstra' is a member of groups: wheel, sshusers[0m
> 2019-05-16 23:14:22,837   add 'xpra' group membership to enable group socket sharing[0m
> 2019-05-16 23:14:22,837   permissions on directory /run/xpra: 0o775[0m
> 2019-05-16 23:14:22,837   ownership root:xpra[0m
> 2019-05-16 23:14:22,949 pointer device emulation using XTest[0m
> [33m2019-05-16 23:14:22,949 Warning: the 'start-child' option is used,[0m
> [33m2019-05-16 23:14:22,949  but 'exit-with-children' is not enabled,[0m
> [33m2019-05-16 23:14:22,949  use 'start' instead[0m
> 2019-05-16 23:14:23,028 serving html content from: /usr/share/xpra/www[0m
> 2019-05-16 23:14:24,012  OpenGL is supported on display ':100'[0m
> 2019-05-16 23:14:24,012  using 'llvmpipe (LLVM 8.0, 256 bits)' renderer[0m
> 2019-05-16 23:14:24,031 D-Bus notification forwarding is available[0m
> [33m2019-05-16 23:14:24,159 Warning: webcam forwarding is disabled[0m
> [33m2019-05-16 23:14:24,159  the virtual video directory '/sys/devices/virtual/video4linux' was not found[0m
> [33m2019-05-16 23:14:24,160  make sure that the 'v4l2loopback' kernel module is installed and loaded[0m
> 2019-05-16 23:14:24,160 found 0 virtual video devices for webcam forwarding[0m
> 
> (Xpra:5658): Gtk-CRITICAL **: 23:14:24.186: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
> [33m2019-05-16 23:14:24,191 Warning: failed to load the mdns publisher[0m
> [33m2019-05-16 23:14:24,191  No module named 'avahi'[0m
> [33m2019-05-16 23:14:24,191  either install the 'python-avahi' module[0m
> [33m2019-05-16 23:14:24,191  or use the 'mdns=no' option[0m
> 2019-05-16 23:14:24,191 xpra GTK3 X11 version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit[0m
> 2019-05-16 23:14:24,191  uid=1000 (turkstra), gid=1000 (turkstra)[0m
> 2019-05-16 23:14:24,191  running with pid 5658 on Linux Fedora 30 Thirty[0m
> 2019-05-16 23:14:24,192  connected to X11 display :100 with 24 bit colors[0m
> 
> -* (Xpra:5658): WARNING **: 23:14:24.197: AT-SPI: Could not obtain desktop path or name
> 
> 
> -* (Xpra:5658): WARNING **: 23:14:24.206: atk-bridge: GetRegisteredEvents returned message with unknown signature
> 
> -* (Xpra:5658): WARNING **: 23:14:24.206: atk-bridge: get_device_events_reply: unknown signature
> 
> -* (Xpra:5658): WARNING **: 23:14:24.206: atk-bridge: get_device_events_reply: unknown signature
> 2019-05-16 23:14:24,246 xpra is ready.[0m
> 2019-05-16 23:14:26,929 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:14:26,935 Handshake complete; enabling connection[0m
> 2019-05-16 23:14:26,983  mmap is enabled using 256MB area in /run/user/1000/xpra/xpra.8q2onpk2.mmap[0m
> 2019-05-16 23:14:26,985 Python/GTK3 Linux Fedora 30 Thirty x11 client version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit[0m
> 2019-05-16 23:14:26,985  connected from 'endor.turkeyland.net' as 'turkstra' - 'Jeff Turkstra'[0m
> 2019-05-16 23:14:26,988 setting key repeat rate from client: 500ms delay / 33ms interval[0m
> 2019-05-16 23:14:26,989 setting keymap: [0m
> 2019-05-16 23:14:27,009 setting keyboard layout to 'us'[0m
> 2019-05-16 23:14:27,055 waiting for video encoders initialization[0m
> 2019-05-16 23:14:27,587 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:14:34,952 printer forwarding enabled using postscript and pdf[0m
> 2019-05-16 23:14:34,959 started command 'mate-terminal' with pid 6395[0m
> 2019-05-16 23:14:34,960 15.6GB of system memory[0m
> 2019-05-16 23:14:34,961  client root window size is 5120x1600 with 1 display:[0m
> 2019-05-16 23:14:34,961   :0.0 (1355x423 mm - DPI: 95x96) workarea: 5120x1550 at 0x25[0m
> 2019-05-16 23:14:34,962     DP-4 2560x1600 at 2560x0 (641x401 mm - DPI: 101x101)[0m
> 2019-05-16 23:14:34,962     DP-6 2560x1600 (641x401 mm - DPI: 101x101)[0m
> 2019-05-16 23:14:34,991 server virtual display now set to 5280x1920 (best match for 5120x1600)[0m
> 
> -* (mate-terminal:6395): WARNING **: 23:14:34.999: AT-SPI: Could not obtain desktop path or name
> 
> 2019-05-16 23:14:35,007 client @09.878 Xpra GTK3 X11 server version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit[0m
> 2019-05-16 23:14:35,008 client @09.878  running on Linux Fedora 30 Thirty[0m
> [33m2019-05-16 23:14:35,009 DPI set to 62 x 45 (wanted 96 x 96)[0m
> [33m2019-05-16 23:14:35,009  you may experience scaling problems, such as huge or small fonts, etc[0m
> [33m2019-05-16 23:14:35,009  to fix this issue, try the dpi switch, or use a patched Xorg dummy driver[0m
> 2019-05-16 23:14:35,014 client @09.884 Attached to :100[0m
> 2019-05-16 23:14:35,014 client @09.884  (press Control-C to detach)[0m
> 
> -* (mate-terminal:6395): WARNING **: 23:14:35.096: atk-bridge: GetRegisteredEvents returned message with unknown signature
> 
> -* (mate-terminal:6395): WARNING **: 23:14:35.096: atk-bridge: get_device_events_reply: unknown signature
> 
> -* (mate-terminal:6395): WARNING **: 23:14:35.096: atk-bridge: get_device_events_reply: unknown signature
> 2019-05-16 23:14:35,130 client @09.999 server does not support xi input devices[0m
> 2019-05-16 23:14:35,130 client @10.000  server uses: xtest[0m
> [33m2019-05-16 23:14:35,148 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:14:35,148 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:14:35,149 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:14:35,149 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:15:56,465 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:15:56,465 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:15:58,083 Warning: limited clipboard support for CLIPBOARD[0m
> [33m2019-05-16 23:15:58,083  g-invoke-error-quark: Class GtkInvisible doesn't implement selection_get (1)[0m
> [33m2019-05-16 23:16:07,233 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:07,233 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:07,236 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:07,236 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,547 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,547 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,558 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,558 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,601 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,601 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,622 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,622 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,679 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,679 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:09,682 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:09,682 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:16:13,235 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:16:13,236 client does not support any csc modes with vp9[0m
> /usr/lib64/python3.7/site-packages/gi/overrides/Gtk.py:1630: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
>   return _Gtk_main(*args, **kwargs)
> 2019-05-16 23:20:00,845 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:20:00,879 processed structured info request from unix-domain socket:/run/user/1000/xpra/endor.turkeyland.net-100 in 31ms[0m
> 2019-05-16 23:20:01,529 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:24:39,998 client @14.868 got signal SIGINT[0m
> 2019-05-16 23:24:39,999 client @14.869 exiting[0m
> 2019-05-16 23:24:39,999 client has requested disconnection: exit on signal SIGINT[0m
> 2019-05-16 23:24:39,999 Disconnecting client Protocol(unix-domain socket:/run/user/1000/xpra/endor.turkeyland.net-100):[0m
> 2019-05-16 23:24:40,000  client request[0m
> 2019-05-16 23:24:40,012 xpra client 1 disconnected.[0m
> 2019-05-16 23:24:43,308 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> 2019-05-16 23:24:43,313 Handshake complete; enabling connection[0m
> 2019-05-16 23:24:43,317  mmap is enabled using 256MB area in /run/user/1000/xpra/xpra.0wwn37ij.mmap[0m
> 2019-05-16 23:24:43,318 Python/GTK3 Linux Fedora 30 Thirty x11 client version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit[0m
> 2019-05-16 23:24:43,318  connected from 'endor.turkeyland.net' as 'turkstra' - 'Jeff Turkstra'[0m
> 2019-05-16 23:24:43,319 setting key repeat rate from client: 500ms delay / 33ms interval[0m
> 2019-05-16 23:24:43,321 keyboard mapping already configured (skipped)[0m
> 2019-05-16 23:24:43,321  client root window size is 5120x1600 with 1 display:[0m
> 2019-05-16 23:24:43,321   :0.0 (1355x423 mm - DPI: 95x96) workarea: 5120x1550 at 0x25[0m
> 2019-05-16 23:24:43,321     DP-4 2560x1600 at 2560x0 (641x401 mm - DPI: 101x101)[0m
> 2019-05-16 23:24:43,321     DP-6 2560x1600 (641x401 mm - DPI: 101x101)[0m
> 2019-05-16 23:24:43,322 best resolution matching 5120x1600 is unchanged: 5280x1920[0m
> 2019-05-16 23:24:43,350 client @01.410 Xpra GTK3 X11 server version 2.5-[r22144](../commit/627709277f9777781b327a09ee13fac236a42684) 64-bit[0m
> 2019-05-16 23:24:43,350 client @01.411  running on Linux Fedora 30 Thirty[0m
> 2019-05-16 23:24:43,355 client @01.414 Attached to :100[0m
> 2019-05-16 23:24:43,355 client @01.415  (press Control-C to detach)[0m
> [33m2019-05-16 23:24:43,414 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:24:43,414 client does not support any csc modes with vp9[0m
> [33m2019-05-16 23:24:43,419 client does not support any csc modes with vp8[0m
> [33m2019-05-16 23:24:43,419 client does not support any csc modes with vp9[0m
> 2019-05-16 23:24:43,460 client @01.521 server does not support xi input devices[0m
> 2019-05-16 23:24:43,461 client @01.522  server uses: xtest[0m
> 2019-05-16 23:24:43,974 New unix-domain connection received on /run/user/1000/xpra/endor.turkeyland.net-100[0m
> ```

**Comment by palves** [comment]
Hi!

I see similar issues as the OP.  In my case, I use KDE as environment.  When I launch a remote app via plan ssh, the app launches with wrong fonts, widgets, etc., if XDG_CURRENT_DESKTOP is not set to "KDE".  So to fix that, I added XDG_CURRENT_DESKTOP to AcceptEnv in /etc/ssh/sshd_config, and have "SendEnv XDG_CURRENT_DESKTOP" in my ~/.ssh/config.  Again, that fixes e.g., "ssh myserver konsole".

For Xpra, however, the ssh env settings alone do not work, because for some reason Xpra always overrides XDG_CURRENT_DESKTOP with XDG_CURRENT_DESKTOP=Xpra, and again, I get the undesired theming.

In the OP's logs diff above, we see:

 -XDG_CURRENT_DESKTOP=MATE
 +XDG_CURRENT_DESKTOP=Xpra

so that may well explain the difference for them too.

So is there a way to make Xpra not force XDG_CURRENT_DESKTOP=Xpra?  Where is that coming from?

**Comment by palves** [comment]
BTW, my workaround is to explicitly pass the env var on the started command via --start, like:

  $ xpra start --dpi=96 --ssh="ssh -x" ssh://myserver --start='sh -c "XDG_CURRENT_DESKTOP=KDE konsole"'

I need "--dpi=96" too, for some reason, and --ssh to force openssh, as the builtin ssh client doesn't grok my config.

**Comment by palves** [comment]
And now that I've looked at the code, I saw that XDG_CURRENT_DESKTOP comes from the wm-name setting.

So putting this in ~/.config/xpra/xpra.conf on the server makes ```xpra start ssh://myserver --start=konsole``` work correctly for me (and putting MATE there would probably fix it for the OP):

```
# So that remote apps use the right theme/fonts.
wm-name = KDE

# Use a fixed DPI:
dpi = 96

# The built-in client doesn't grok my ~/.ssh/config properly.
ssh = ssh -x
```

**Comment by totaam** [comment]
The `wm-name` option was / is needed for some type of applications that make the wrong assumptions: #705

Perhaps we could default to `auto` and forward the option when using remote ssh start.
The problem with this is that it affects a number of things, not just the theming. This could well cause further problems. (ie: loading of xdg menus, etc)

> I need `--dpi=96` too, for some reason

@palves My guess is that you're on Debian or Ubuntu, which don't have Xdummy support amongst many other broken OS features.

> The built-in client doesn't grok my `~/.ssh/config` properly

Newer versions of `paramiko` handle this better.
What is the specific problem?
