### ISSUE TITLE
xpra-shadow new borders and window size miscalculations

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2455]
*Issue migrated from trac ticket # 2455*

**component:** client | **priority:** critical

#### 2019-10-19 10:43:20: stdedos created the issue

___
> After changing to the "new window styles" (between [r24005](../commit/389239a9abfaf8a90cc15a53d9bb024f1502e5ba) and 24195), I noticed that the shadow works "a bit differently"
> 
> Please see attached images.
> 
> 1. Image may not be fully initialized
> [[Image(Xpra_cmd_2019-10-19_12-25-26.png)]]
> 2. Viewport calculation is wrong 
> 3. On fullsize, viewport is correct, but other monitors "seep in"
> [[Image(Xpra_cmd_2019-10-19_12-28-34-1.png)]]
> [[Image(Xpra_cmd_2019-10-19_12-30-04-2.png)]]
> 
> I am not complaining so much about (3), but, if client could scale shadow window to perfectly fit the client's available viewport for maximized windows (i.e. window + the Start bar), then this would bring unnecessary drawing outside of the screen.
> 
> I don't know if client would be able to do that with Shadow windows (i.e. make the scaling fill pixel-perfectly the whole screen), but it would be a nice feature (reported in #2458).

**Comment by stdedos** [comment]
Let's close this one in favor of https://github.com/Xpra-org/xpra/issues/3140?
