### ISSUE TITLE
No module named 'comtypes.gen.stdole'

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2573]
*Issue migrated from trac ticket # 2573*

**component:** client | **priority:** trivial

#### 2020-02-03 12:26:41: stdedos created the issue

___
> Resurrecting #1899:
> 
> ```
> "Xpra-Python3-x86_64_4.0-[r24952](../commit/6a233f08f3d9bea8e142cb91840fbbaecc393908)\xpra_cmd" shadow ssh://user@ip/0  --opengl=no --desktop-scaling=0.75 --min-speed=70 --webcam=no --speaker=off --microphone=off --pulseaudio=no --exit-with-client=no
> 
> 2020-02-03 14:07:25,294 Xpra GTK3 client version 4.0-[r24952](../commit/6a233f08f3d9bea8e142cb91840fbbaecc393908) 64-bit
> 2020-02-03 14:07:25,294  running on Microsoft Windows 10
> 2020-02-03 14:07:26,075 GStreamer version 1.16.2 for Python 3.8.0 64-bit
> 2020-02-03 14:07:26,653 Connected (version 2.0, client OpenSSH_7.2p2)
> 2020-02-03 14:07:26,731 SSH password authentication failed:
> 2020-02-03 14:07:26,731  Bad authentication type; allowed types: ['publickey', 'password']
> please enter the SSH password for user@ip:
> 2020-02-03 14:07:41,465 Authentication (password) failed.
> 2020-02-03 14:07:41,465 SSH password authentication failed:
> 2020-02-03 14:07:41,465  Authentication failed.
> please enter the SSH password for user@ip:
> 2020-02-03 14:07:54,011 Authentication (password) successful!
> 2020-02-03 14:07:55,699 Error: failed to query network interface:
> 2020-02-03 14:07:55,699  No module named 'comtypes.gen.stdole'
> 2020-02-03 14:07:55,730  keyboard settings: layout=us
> ```
>

**Comment by stdedos** [comment]
I don't think I have seen this happening ever since; and now Xenial is EOL (maybe a main user of v3?).

I guess this should be closeable too. (You have anyway marked this as wontfix)

**Comment by totaam** [comment]
Both the network query code `Network_info.exe` and the webcam tool `Webcam_info.exe` run without spitting out comtypes errors. Yay.
