### ISSUE TITLE
LibreOffice Calc: The brush cursor is not rendered

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2623]
*Issue migrated from trac ticket # 2623*

**component:** client | **priority:** minor | **resolution:** needinfo

#### 2020-03-05 19:59:52: stdedos created the issue

___
> Server: Xenial / 3.0.6-[r25174](../commit/86fdb78c7bf461e68008d62bac8a4bf54dd5f12c)
> Client: Xpra-Python3-x86_64_4.0-[r25519](../commit/f9057e6fd70fff31eb2e9744132cafd5db367ff6)
> 
> In LibreOffice Calc, when using the "Copy Format" functionality, the cursor changes to the brush cursor.
> 
> Via xpra, that does not happen.
> 
> Please fix it if possible (no error message appears on the screen)

**Comment by stdedos** [comment]
Checking with the current latest version, it does not seem that xpra has any issue with it.

It's just that LibreOffice decided that the "paint brush" is a euphemism for "small and indiscernible fluorescent marker" cursor icon ...

**Comment by totaam** [comment]
FYI: as well as `-d cursor`, you can always use `XPRA_SAVE_CURSORS=1` on both client and server to save the cursor to png every time it changes.

There is a workaround for MS Windows specifically which can affect the cursor size: we use the size `GetSystemMetrics(win32con.SM_CXCURSOR)` x `GetSystemMetrics(win32con.SM_CYCURSOR)` and paste / scale the real cursor as needed to achieve the size required by the OS: _The width / height of a cursor, in pixels. The system cannot create cursors of other sizes._
So it is possible that this code is buggy or has problems with specific cursor geometries.

**Comment by stdedos** [comment]
Thank you for the debugging comments 😀

However, I have verified that the cursors on the xpra screen, and my other Ubuntu laptop look exactly the same (for the same app/setup). Of course I don't know if that was the same case back then; however, it doesn't seem to matter anymore. I know I was clearly expecting a paint brush, and not seeing made me first question the middleware, not "the source".

**Comment by stdedos** [comment]
Oh, and the image just for the sake of completeness
![Xpra_cmd_2021-04-12_14-37-52](https://user-images.githubusercontent.com/133706/116722717-6c08fd00-a9e7-11eb-94d0-88f711ce3a19.png)

(via xpra-rendering)
