### ISSUE TITLE
Moving a maximized window to a smaller monitor via WinKey+Shift+LeftArrow does not fit it on destination

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2643]
#### 2020-03-13 14:55:58: stdedos created the issue

Moving maximized LibreOffice to the adjacent big monitor (via WinKey+Shift+LeftArrow) does not fit the screen with the maximized window.

Window "pretends" to be maximized, and left in a non-standard place in the new monitor.

You need to manually window it and then maximize it again.

**Comment by totaam** [comment]
@stdedos: can you try doing the same thing with any "regular" window you want from the native `xpra toolbox`?
My guess is that the problem is the same as #3122 - something in GTK is preventing this from working.

**Comment by stdedos** [comment]
I'll check this tomorrow - hopefully there is a window that maximizes 😀

**Comment by stdedos** [comment]
Window States window does the job.

... and, it exhibits the same behavior as other windows.
The only mitigating fact is that, when un-maximized, its entirety is on the new monitor; a subsequent maximization solves the issue. "Other" windows end up too big and/or not clearly placed on the next monitor - which requires manual intervention to associate them where they need to be.
Other fact is that it does not exhibit #3122; click-drag-maximize works fine.

**Comment by totaam** [comment]
Closing as another Debian-only issue. 
Using properly virtualized monitors via Xdummy likely fixes this.
