### ISSUE TITLE
Question multi-user html5

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2644]
*Issue migrated from trac ticket # 2644*

**component:** html5 | **priority:** major | **resolution:** fixed

#### 2020-03-13 21:31:03: peter0914 created the issue

___
> I have the following use case:
> 
> - Multiple users (clients) shall be able to run a specific program P on a remote server
> * Each user gets its own instance of P (so P is started multiple times on the server)
> * The users connect via web-browser (html5) with their username and password
> 
> At the moment I solved it by creating separate linux user accounts and launching multiple instances of xpra-html5 under each of these accounts on different display and tcp (wss) ports. However I wonder if there is a better option, because I have some stability problems with the X-servers and maybe I am using xpra the wrong way.
> 
> 
> My questions are:
> 1. Is my current solution the preferred one in this situation?
> 2. Might the xpra proxy be useful to me?
> 3. How could multiple user logins/passwords be handled by a single xpra instance?
> 
> 
> PS: Im using the latest ppa version. Also I could not find a proper type for this ticket, please change it to something else.

**Comment by Yas-LM** [comment]
hello, i have the same probleme, how do you solve it ?
