### ISSUE TITLE
Detecting or setting up MIT-SHM

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2647]
*Issue migrated from trac ticket # 2647*

**component:** server | **priority:** critical | **resolution:** needinfo

#### 2020-03-16 09:01:06: mviereck created the issue

___
> Coming from #2610
> 
> 
> >> I found no way to allow memory sharing for MIT-SHM only. Docker only allows to share the entire IPC namespace/shared memory for all applications (Docker option --ipc=host).
> 
> 
> 
> > That's a real shame!
> > As per ​Understanding the Linux Virtual Memory Manager: The filesystem comes in two variations called shm and tmpfs. They both share core functionality and mainly differ in what they are used for. shm is for use by the kernel for creating file backings for anonymous pages and for backing regions created by shmget().
> > We need shmget for xshm, so mounting a tmpfs may not be enough. I have not tried it.
> 
> So far I did not even found a hint where to look for MIT-SHM in the system.I would assume that `lsipc -m` should show it, but it does not.
> If you can give me some hints where to look for the memory area or maybe even providing one to Xvfb and/or Xdummy, I might find a solution how to share it with a Docker container.
> 
> Ideally it would have a representation in the file system like e.g. `/dev/shm/MIT-SHM.X20`. It is easy to share files with a Docker container.

**Comment by mviereck** [comment]
I just want to note that your suggestions helped me again several years later. Thank you!

**Comment by totaam** [comment]
@mviereck FYI we have easier diagnostics for xshm issues now too, ie for display `:0`:
```shell
xpra xshm :0
```
Will exit with a return code 0 when it succeeds.
You can get more debugging details with `xpra xshm :100 -d all`.
