### ISSUE TITLE
AltGr on german keyboard does not work on windows client

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2648]
*Issue migrated from trac ticket # 2648*

**component:** keyboard | **priority:** major | **resolution:** fixed

#### 2020-03-16 11:13:29: leo_b created the issue

___
> When connecting from a Win10 client to a Centos 7 server, **AltGr** key combinations on a german keyboard don't work. Attaching to the same session from a linux client works fine.
> 
> Pressing **AltGr** yields `ISO_Level3_Shift` down and up events on the linux client but on windows additional `Meta_R` events are shown. Short pressing and releasing **AltGr** produces:
> 
>   down ISO_Level3_Shift 
>   up ISO_Level3_Shift 
>   down Meta_R
>   up Meta_R
>   down ISO_Level3_Shift
> 
> Log output on Windows:
> ```
> 2020-03-16 10:39:16,677 keyboard layout code 0x407
> 2020-03-16 10:39:16,677 identified as 'German' : de
> [...]
> 2020-03-16 10:39:21,591 Authentication (password) successful!
> 2020-03-16 10:39:22,158  keyboard settings: layout=de
> ```
> 
> Log output on linux:
> ```
> 2020-03-16 10:32:40,812  keyboard settings: rules=evdev, model=pc105, layout=at
> ```
> 
> The issue is also present when using `--no-keyboard-sync`.
> 
> I attached the client log produced with
> `xpra attach  ssh://user@host/ -d keyboard`
> ... when pressing **AltGr** + **q** which should produce "@" but actually only results in a "q".
> 
> Examples of other important **AltGr** keys that don't work:
> **AltGr** + **+** = ~
> **AltGr** + **<** = |
>

**Comment by totaam** [comment]
Extracted from the attachments (now deleted):
```
$ setxkbmap -query
	rules:      evdev
	model:      pc105
	layout:     de
```
```
$ setxkbmap -print
	xkb_keymap {
	        xkb_keycodes  { include "evdev+aliases(qwertz)" };
	        xkb_types     { include "complete"      };
	        xkb_compat    { include "complete"      };
	        xkb_symbols   { include "pc+de+inet(evdev)"     };
	        xkb_geometry  { include "pc(pc105)"     };
	};
```

Which one is the correct layout? 'at' or 'de'?
* `identified as 'German' : de`
* `keyboard settings: rules=evdev, model=pc105, layout=at`

**Comment by ebecheto** [comment]
For some reasons, in my Xpra client (or server, dunno) the tild character is disabled from AltGr+2 (french keyboard), but it is available from the right-mouse key closed to Fn on my keyboard. Cheap workaround.

**Comment by totaam** [comment]
@ebecheto this ticket is closed, please use a new issue and include more details as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
