### ISSUE TITLE
PyCharm Search Everywhere "window" cannot be moved around

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2675]
*Issue migrated from trac ticket # 2675*

**component:** client | **priority:** major

#### 2020-03-24 08:54:15: stdedos created the issue

___
> ```
> "Xpra-Python3-x86_64_4.0-25747\xpra_cmd" attach ssh://user@ip/20 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @hostname@/@server-display@"
> 
> 2020-03-24 10:17:38,093 Warning: OpenGL probe failed: timeout
> 2020-03-24 10:17:38,835 Xpra GTK3 client version 4.0-25747 64-bit
> 2020-03-24 10:17:38,838  running on Microsoft Windows 10
> 2020-03-24 10:17:38,981 Warning: failed to import opencv:
> 2020-03-24 10:17:38,983  No module named 'cv2'
> 2020-03-24 10:17:38,983  webcam forwarding is disabled
> 2020-03-24 10:17:40,611 GStreamer version 1.16.2 for Python 3.8.2 64-bit
> 2020-03-24 10:17:41,155 keyboard layout code 0x409
> 2020-03-24 10:17:41,156 identified as 'United States - English' : us
> 2020-03-24 10:17:42,013  keyboard settings: layout=us
> 2020-03-24 10:17:42,018  desktop size is 1600x900 with 1 screen:
> 2020-03-24 10:17:42,019   Default (423x238 mm - DPI: 96x96) workarea: 1600x860
> 2020-03-24 10:17:42,019     Generic PnP Monitor (309x174 mm - DPI: 131x131)
> 2020-03-24 10:17:46,701 enabled remote logging
> 2020-03-24 10:17:46,704 Xpra GTK3 X11 server version 3.0.8-[r25722](../commit/84a5a81aa1fb41a3dac3b4c78d92b54b13278a5c) 64-bit
> 2020-03-24 10:17:46,709  running on Linux Ubuntu 16.04 xenial
> 2020-03-24 10:17:46,727 Attached to ip:22
> 2020-03-24 10:17:46,731  (press Control-C to detach)
> 
> 
> (xpra_cmd:2904): Pango-WARNING **: 10:17:47.423: couldn't load font "Bitstream Vera Sans Not-Rotated 14.662109375", falling back to "Sans Not-Rotated 14.662109375", expect ugly output.
> 2020-03-24 10:17:47,984 sound output using 'opus' audio codec
> 2020-03-24 10:17:48,460 UI thread is now blocked
> 2020-03-24 10:17:48,509 UI thread is running again, resuming
> 2020-03-24 10:18:03,899 Warning: static gravity is not handled
> 2020-03-24 10:18:49,271 Warning: failed to set clipboard data
> 2020-03-24 10:18:49,276  OpenClipboard: too many failed attempts, giving up
> ```
> 
> In PyCharm EAP:
> 
> - Press `Shift Shift` (press `Shift`, release, press `Shift`)
> * Try to move that window *anywhere*
> 
> The window is "somewhat" following the cursor, but it's jumpy.
> 
> (All JetBrains tools "share" underlying code, so it doesn't really matter which one you use)

**Comment by stdedos** [comment]
(still valid for v4.x)

**Comment by totaam** [comment]
Duplicate of #1941.
