### ISSUE TITLE
Right click ends up on the screen edge

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2697]
*Issue migrated from trac ticket # 2697*

**component:** client | **priority:** major

#### 2020-04-01 14:25:04: stdedos created the issue

___
> In some cases (I assume custom right-click menus) I see this for windows on my WQHD monitor:
> 
> [[Image(xpra_right-click_ends-up-on-the-screen-edge.png)]]
> 
> Unfortunately, I don't have more info data than these:
> 
> ```
> "Xpra-Python3-x86_64_4.0-[r25894](../commit/19b846eb99133c0526c58dc6390a01873d52acdf)\xpra_cmd" attach ssh://user@ip/20 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @hostname@/@server-display@" --opengl=no
> 
> 2020-04-01 16:20:57,638 Xpra GTK3 client version 4.0-[r25894](../commit/19b846eb99133c0526c58dc6390a01873d52acdf) 64-bit
> 2020-04-01 16:20:57,640  running on Microsoft Windows 10
> 2020-04-01 16:20:57,713 Warning: failed to import opencv:
> 2020-04-01 16:20:57,714  No module named 'cv2'
> 2020-04-01 16:20:57,714  webcam forwarding is disabled
> 2020-04-01 16:20:58,418 GStreamer version 1.16.2 for Python 3.8.2 64-bit
> 2020-04-01 16:20:58,696 keyboard layout code 0x409
> 2020-04-01 16:20:58,697 identified as 'United States - English' : us
> 2020-04-01 16:20:59,053  keyboard settings: layout=us
> 2020-04-01 16:20:59,056  desktop size is 4160x1440 with 1 screen:
> 2020-04-01 16:20:59,056   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
> 2020-04-01 16:20:59,056     Generic PnP Monitor 1600x900 (309x174 mm - DPI: 131x131) workarea: 1600x860
> 2020-04-01 16:20:59,056     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400
> 
> Xenial server $ xpra --version
> xpra v3.0.8-25767
> ```
> 
> Since #2642's spam is toooo damn high

**Comment by stdedos** [comment]
Right click ends up on the screen edge > Right click / File menus end up unrelated to their "parent" (mouse click, menu toolbar)

**Comment by stdedos** [comment]
I was about to start a "Jetbrains hover tooltips appear unrelated to mouse cursor" ticket, but it seems that all of the issues presented here (except https://github.com/Xpra-org/xpra/issues/2697#issuecomment-765540994, https://github.com/Xpra-org/xpra/issues/2697#issuecomment-765540996) are somewhat related to each other.

"Jetbrains hover tooltips appear unrelated to mouse cursor", for example, on static analysis errors (in this case, from the provided Shellcheck extension).

For the familiar monitor setup, 1336x..⊥2560x.. (merged like so: ⊥), Jetbrains App maximized on the big monitor, a tooltip at the ~20% of monitor's width, ends up fully to the right.
However, if I move the App to left and hover again, the tooltip ends up where it's supposed to.
... and then, if I move the App back to the big monitor, the tooltip (again) ends up where it's supposed to.

Might be some issue with re-attaching? 😕 

_Might be also related to: https://github.com/Xpra-org/xpra/issues/2703_

**Comment by stdedos** [comment]
> Can you try with a patched Xdummy?

Do you mean this patch?
https://github.com/Xpra-org/xpra/commit/871e8c71f779f1a31e68f622b7031fb936ed7256

To make sure I understand, if I use Xvfb, I automatically use Xdummy?

**Comment by totaam** [comment]
> Do you mean this patch? 871e8c7

Yes.

> To make sure I understand, if I use Xvfb, I automatically use Xdummy?

No.
You would need to change to use [Xdummy](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md) by setting the `xvfb` option in your `/etc/xpra/xpra.conf/ config file.

**Comment by totaam** [comment]
One year ago, I'm going to assume that xpra 4.4 or later with dummy 0.4.0 or later fixes this issue.
