### ISSUE TITLE
text mode rendering may become stale

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2708]
*Issue migrated from trac ticket # 2708*

**component:** client | **priority:** minor

#### 2020-04-03 13:46:16: stdedos created the issue

___
> For example, if I use multi-caret selection in Sublime Text too quickly (select a text that exists multiple times on the document, press Ctrl+D repeatedly), doing it too fast might end up showing one of the scrolling frames, but the last frame will end up being stale for the text editing area *except* for part of the blinking cursor.
> 
> The workaround is to "wiggle" the scroll position with the mouse - but then that means I need to context switch between the keyboard and the mouse.
> 
> The other way, to click with the mouse or do some modification with the keyboard, while valid workarounds, do not fit said user scenario.

**Comment by stdedos** [comment]
Still visible on high-churn operations, but does not appear to be as severe as it was on v3, prior to the code changes that had been done

**Comment by totaam** [comment]
Is this still a problem with v4?

**Comment by stdedos** [comment]
No, and I think the work on done on https://github.com/Xpra-org/xpra/issues/3167 (and the conclusions at https://github.com/Xpra-org/xpra/issues/3167#issuecomment-879788218) seem to somehow make this disappear  completely
