### ISSUE TITLE
Add a window showing all shortcuts

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2779]
*Issue migrated from trac ticket # 2779*

**component:** client | **priority:** minor | **resolution:** fixed

#### 2020-05-27 09:40:50: stdedos created the issue

___
> *From #2762#comment:20* 
> 
> > > Ctrl+Shift+F5 does not seem to work 😕
> > > Which `ShortcutKey`? `Cmd` / `Ctrl`?
> > `--shortcut-modifiers=auto` should be using `Meta+Shift` on mswindows.
> > You can change it, ie: `--shortcut-modifiers=Control+Shift`.
> 
> btw, are all the available shortcuts collected/listed somewhere?
> 
> If not, would you add something along those lines:
> [[Image(/raw-attachment/ticket/2762/xpra-example-shortcuts.png)]]
> 
> (my mockup is not perfect, but I hope it conveys the idea)
> 
> You can assign `prefix+?` to it (the `/?` key, not necessarily the `?` if it is harder to map because of "Shift" weirdness), and a tray-list-entry

**Comment by stdedos** [comment]
Is `show_shortcuts` assigned a shortcut itself by default?

Should it? In the event of https://github.com/Xpra-org/xpra/issues/3586, and man-page not including the default shortcuts (not that I am saying it should), "it would've been helpful" to have a way to trigger `show_shortcuts` from a live instance

If the above is agreeable, then maybe add _that keyboard shortcut_ also:
* to the man-page, and/or
* https://github.com/Xpra-org/xpra/blob/master/docs/FAQ.md, and/or
* the wiki

**Comment by totaam** [comment]
> it would've been helpful" to have a way to trigger show_shortcuts from a live instance

Done, the `F6` shortcut will bring up this window and the `F7` one will bring up the documentation in a browser window.

You can get to the documentation with `xpra docs`. (bar small fix above)

(no MS Windows builds yet..)
