### ISSUE TITLE
'Alt' keyboard shortcuts seem to not to be forwarded to the server correctly

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2831]
*Issue migrated from trac ticket # 2831*

**component:** client | **priority:** major

#### 2020-07-08 08:49:42: stdedos created the issue

___
> Ctrl+Shift+D, Ctrl+C works.
> Ctrl+Alt+Y, Ctrl+Shift+Alt+C don't work:
> 
> [[Image(GTK_Keyboard_Test_2020-07-08_10-37-54.png)]]
> 
> 
> ```
> "Xpra-Python3_4.0.2-26623\xpra_cmd" attach ssh://user@ip/2 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @@/@server-display@" --opengl=no --bandwidth-limit=6Mbps
> 
> 2020-07-08 10:21:21,525 Xpra GTK3 client version 4.0.2-26623 32-bit
> 2020-07-08 10:21:21,527  running on Microsoft Windows 10
> 2020-07-08 10:21:22,419 GStreamer version 1.16.2 for Python 3.8.3 32-bit
> 2020-07-08 10:21:22,925 keyboard layout code 0x409
> 2020-07-08 10:21:22,925 identified as 'United States - English' : us
> 2020-07-08 10:21:23,257  keyboard settings: layout=us
> 2020-07-08 10:21:23,260  desktop size is 4160x1440 with 1 screen:
> 2020-07-08 10:21:23,261   Default (1100x380 mm - DPI: 96x96) workarea: 4160x1400
> 2020-07-08 10:21:23,261     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 131x131) workarea: 1600x860
> 2020-07-08 10:21:23,261     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400
> 2020-07-08 10:21:28,266 enabled remote logging
> 2020-07-08 10:21:28,268 Xpra GTK3 X11 server version 3.0.10-26630 64-bit
> 2020-07-08 10:21:28,268  running on Linux Ubuntu 16.04 xenial
> 2020-07-08 10:21:28,273 Attached to ip:22
> 2020-07-08 10:21:28,274  (press Control-C to detach)
> 
> ```
> 
> 
> Attaching small server logs.
> 
> `xkbprint -label name $DISPLAY`: empty
> Missing #2830

**Comment by stdedos** [comment]
No longer an issue: verified with now-latest v4.1.x

**Comment by nightshiba** [comment]
FYI: I had the same issue for a long time (Xpra X11 seamless server version 4.3.1-r0 64-bit, Python/GTK3 Linux Arch rolling n/a x11 client version 4.2.3-r3 64-bit), but it happened only after some time. So then I've noticed "[Errno 19] Failed to open the uinput device: No such device" in the server's log, and after enabling `uinput` module the issue is gone. (And it's still reproducible if I disable autoloading of `uinput`). I hope it can help someone.

**Comment by totaam** [comment]
> after enabling `uinput` module the issue is gone

You're lucky, `uinput` is very rarely used.

---

GTK3 updates may impact `Alt` / `AltGr` keyboard mapping: https://github.com/Xpra-org/xpra/issues/3463#issuecomment-1041546056
