### ISSUE TITLE
Xpra stop crashes X Display :0

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2834]
*Issue migrated from trac ticket # 2834*

**component:** server | **priority:** major | **resolution:** fixed

#### 2020-07-08 17:59:00: brady created the issue

___
> If I start an xpra session using `xpra start :100`, and then run the command `xpra stop`, xpra will not only stop the xpra session, but will also kill my original x session running on DISPLAY :0. It did not kill the applications that were running on that X Server either.
> 
> This rather annoyingly caused a situation in which a program running on X Display :0 was able to capture my keystrokes that I entered into a tty to try to recover my session.
> 
> Xpra version: `xpra v4.0.2-26625`
> OS: Ubuntu 18.04 amd64
> Desktop Environment: KDE Plasma 5

**Comment by basilgello** [comment]
@totaam

> Let's hope new Debian versions… 

No room for false hopes. I had to revert this commit to make Xorg not deallocate a tty.

**Comment by totaam** [comment]
Reverted in 873060b9ee903d6ed5571cb25ba3df26737fd1cf.

Seeing that a huge number of bugs are being resolved by switching to xrandr Xdummy (#56), the only recommendation I can make is to **avoid Debian with xpra**.

**Comment by totaam** [comment]
Checked again and in 2024, the Debian version of `Xorg` is still butchered and unusable as non-root!
https://github.com/Xpra-org/xpra/wiki/Distribution-Packages#specific-distributions

**Comment by felipecrs** [comment]
> Checked again and in 2024, the Debian version of `Xorg` is still butchered and unusable as non-root! [Wiki: Distribution Packages (specific distributions)](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages#specific-distributions)

Is there some easy way to check? Some specific binary with suid bit?

**Comment by felipecrs** [comment]
No suid bit here, in case that's the binary (Debian 13).

```console
$ stat /usr/bin/Xorg
  File: /usr/bin/Xorg
  Size: 274             Blocks: 8          IO Block: 4096   regular file
Device: 0,292   Inode: 6856730     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-08-22 03:33:46.550588963 +0000
Modify: 2025-06-20 07:47:20.000000000 +0000
Change: 2025-08-22 03:31:41.841512524 +0000
 Birth: 2025-08-22 03:31:41.734511602 +0000
```

**Comment by felipecrs** [comment]
Is this the proof that it's still broken?

<img width="1469" height="1132" alt="Image" src="https://github.com/user-attachments/assets/155ae953-fe05-402a-b1cb-b3da1aca1ab0" />

https://github.com/user-attachments/assets/855eaf2b-e6f3-428e-90b1-200e31bdcc04

**Comment by felipecrs** [comment]
I guess so, but in my case this issue is acceptable. Here's why:

1. I run `xpra start --daemon=no --xvfb=Xdummy` as my main container `CMD`. If `xpra` exits, the whole container will exit.
2. I use `s6-overlay` (running as root) as PID 1 of the container, so that when `xpra` exits, `s6-overlay` will take the container down together with any processes within it, even if the processes are spawned by root.

**Comment by totaam** [comment]
> Is this the proof that it's still broken?

No.
AFAIK, this only affects multiuser systems,  potentially requiring a real desktop session which may get taken down when you stop the xpra session.
