### ISSUE TITLE
Seamless JetBrains apps do not gain focus

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2852]
*Issue migrated from trac ticket # 2852*

**component:** client | **priority:** major

#### 2020-07-23 13:14:42: stdedos created the issue

___
> Opposite of #2723
> 
> ```
> "Xpra-Python3-x86_64_4.1-[r27002](../commit/541311ebdeb9b885dee854ce94f3767340a6bc61)\xpra_cmd" attach ssh://user@ip/2 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @@/@server-display@" --headerbar=off --opengl=no --bandwidth-limit=6Mbps
> 
> 2020-07-23 12:56:36,692 Xpra GTK3 client version 4.1-[r27002](../commit/541311ebdeb9b885dee854ce94f3767340a6bc61) 64-bit
> 2020-07-23 12:56:36,696  running on Microsoft Windows 10
> 2020-07-23 12:56:37,914 GStreamer version 1.16.2 for Python 3.8.4 64-bit
> 2020-07-23 12:56:38,670 keyboard layout code 0x409
> 2020-07-23 12:56:38,671 identified as 'United States - English' : us
> 2020-07-23 12:56:38,938  keyboard settings: layout=us
> 2020-07-23 12:56:38,941  desktop size is 4160x1440 with 1 screen:
> 2020-07-23 12:56:38,941   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
> 2020-07-23 12:56:38,941     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 131x131) workarea: 1600x860 at 0x534
> 2020-07-23 12:56:38,942     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
> 2020-07-23 12:56:45,718 enabled remote logging
> 2020-07-23 12:56:45,721 Xpra GTK3 X11 server version 3.0.10-26630 64-bit
> 2020-07-23 12:56:45,723  running on Linux Ubuntu 16.04 xenial
> 2020-07-23 12:56:45,741 Attached to ip:22
> 2020-07-23 12:56:45,746  (press Control-C to detach)
> 
> 
> (xpra_cmd:12568): Pango-WARNING **: 12:56:46.481: couldn't load font "Bitstream Vera Sans Not-Rotated 14.662109375", falling back to "Sans Not-Rotated 14.662109375", expect ugly output.
> 2020-07-23 12:56:47,504 UI thread is now blocked
> 2020-07-23 12:56:47,921 UI thread is running again, resuming
> 2020-07-23 14:07:38,138 server is not responding, drawing spinners over the windows
> 2020-07-23 14:07:39,903 server is OK again
> 2020-07-23 14:48:19,589 enabled debugging for:
> 2020-07-23 14:48:19,596  - Logger(xpra.client.client_window_base, focus)
> 2020-07-23 14:48:19,599  - Logger(xpra.client.mixins.window_manager, focus)
> 2020-07-23 14:48:19,603  - Logger(xpra.client.gtk_base.gtk_client_window_base, focus, grab)
> 2020-07-23 14:48:23,620 focus-out-event for wid=8
> 2020-07-23 14:48:23,623 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x00000000053c6d60 (void at 0x000000001b7a6830)>)
> 2020-07-23 14:48:23,625 ClientWindow(8) focus_change(ClientWindow(8), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:23,625 update_focus(8, False) focused=8, grabbed=None
> 2020-07-23 14:48:23,627 focus-in-event for wid=5063
> 2020-07-23 14:48:23,629 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x00000000053c6d60 (void at 0x000000001b7c4500)>) been_mapped=True
> 2020-07-23 14:48:23,630 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:23,632 update_focus(5063, True) focused=None, grabbed=None
> 2020-07-23 14:48:23,637 send_focus(5063)
> 2020-07-23 14:48:23,639 recheck_focus() wid=8, focused=5063, latest=False
> 2020-07-23 14:48:23,641 recheck_focus() wid=5063, focused=5063, latest=True
> 2020-07-23 14:48:28,367 focus-out-event for wid=5063
> 2020-07-23 14:48:28,385 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x00000000053d3130 (void at 0x000000001b7c45a0)>)
> 2020-07-23 14:48:28,390 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:28,393 update_focus(5063, False) focused=5063, grabbed=None
> 2020-07-23 14:48:28,397 focus-in-event for wid=8
> 2020-07-23 14:48:28,399 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x00000000053d3130 (void at 0x000000001b7a6830)>) been_mapped=True
> 2020-07-23 14:48:28,401 ClientWindow(8) focus_change(ClientWindow(8), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:28,403 update_focus(8, True) focused=None, grabbed=None
> 2020-07-23 14:48:28,405 send_focus(8)
> 2020-07-23 14:48:28,412 recheck_focus() wid=5063, focused=8, latest=False
> 2020-07-23 14:48:28,415 recheck_focus() wid=8, focused=8, latest=True
> 2020-07-23 14:48:29,255 focus-out-event for wid=8
> 2020-07-23 14:48:29,266 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x0000000000787810 (void at 0x000000001b7a6e70)>)
> 2020-07-23 14:48:29,268 ClientWindow(8) focus_change(ClientWindow(8), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:29,271 update_focus(8, False) focused=8, grabbed=None
> 2020-07-23 14:48:29,274 focus-in-event for wid=5063
> 2020-07-23 14:48:29,276 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x00000000007a53b0 (void at 0x000000001b7eeaa0)>) been_mapped=True
> 2020-07-23 14:48:29,278 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:29,280 update_focus(5063, True) focused=None, grabbed=None
> 2020-07-23 14:48:29,282 send_focus(5063)
> 2020-07-23 14:48:29,287 recheck_focus() wid=8, focused=5063, latest=False
> 2020-07-23 14:48:29,291 recheck_focus() wid=5063, focused=5063, latest=True
> 2020-07-23 14:48:30,264 update_focus(0, False) focused=5063, grabbed=None
> 2020-07-23 14:48:30,268 focus-out-event for wid=5063
> 2020-07-23 14:48:30,269 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x00000000007ab400 (void at 0x000000001b7c4500)>)
> 2020-07-23 14:48:30,271 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:30,272 update_focus(5063, False) focused=None, grabbed=None
> 2020-07-23 14:48:30,273 recheck_focus() wid=5063, focused=None, latest=False
> 2020-07-23 14:48:30,288 send_lost_focus() focused=None
> 2020-07-23 14:48:30,290 send_focus(0)
> 2020-07-23 14:48:30,351 focus-in-event for wid=5595
> 2020-07-23 14:48:30,362 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x00000000007ab130 (void at 0x000000001b7eeaa0)>) been_mapped=True
> 2020-07-23 14:48:30,364 ClientWindow(5595) focus_change(ClientWindow(5595), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:30,366 update_focus(5595, True) focused=None, grabbed=None
> 2020-07-23 14:48:30,367 send_focus(5595)
> 2020-07-23 14:48:30,370 recheck_focus() wid=5595, focused=5595, latest=True
> 2020-07-23 14:48:30,850 update_focus(0, False) focused=5595, grabbed=None
> 2020-07-23 14:48:30,864 focus-out-event for wid=5595
> 2020-07-23 14:48:30,868 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x0000000021978c20 (void at 0x000000001b7a6dd0)>)
> 2020-07-23 14:48:30,874 ClientWindow(5595) focus_change(ClientWindow(5595), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:30,877 update_focus(5595, False) focused=None, grabbed=None
> 2020-07-23 14:48:30,881 send_lost_focus() focused=None
> 2020-07-23 14:48:30,886 send_focus(0)
> 2020-07-23 14:48:30,889 recheck_focus() wid=5595, focused=None, latest=False
> 2020-07-23 14:48:30,944 _unfocus() wid=5595, focused=None
> 2020-07-23 14:48:30,949 focus-in-event for wid=5063
> 2020-07-23 14:48:30,952 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x0000000021978c20 (void at 0x000000001b7c4500)>) been_mapped=True
> 2020-07-23 14:48:30,957 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:30,960 update_focus(5063, True) focused=None, grabbed=None
> 2020-07-23 14:48:30,963 send_focus(5063)
> 2020-07-23 14:48:30,966 recheck_focus() wid=5063, focused=5063, latest=True
> 2020-07-23 14:48:34,371 focus-out-event for wid=5063
> 2020-07-23 14:48:34,382 do_xpra_focus_out_event(<Gdk.EventFocus object at 0x0000000000787ae0 (void at 0x000000001b7eeaa0)>)
> 2020-07-23 14:48:34,386 ClientWindow(5063) focus_change(ClientWindow(5063), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=False, _been_mapped=True
> 2020-07-23 14:48:34,389 update_focus(5063, False) focused=5063, grabbed=None
> 2020-07-23 14:48:34,396 focus-in-event for wid=8
> 2020-07-23 14:48:34,399 do_xpra_focus_in_event(<Gdk.EventFocus object at 0x0000000000787ae0 (void at 0x000000001b7a6f10)>) been_mapped=True
> 2020-07-23 14:48:34,401 ClientWindow(8) focus_change(ClientWindow(8), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
> 2020-07-23 14:48:34,403 update_focus(8, True) focused=None, grabbed=None
> 2020-07-23 14:48:34,408 send_focus(8)
> 2020-07-23 14:48:34,411 recheck_focus() wid=5063, focused=8, latest=False
> 2020-07-23 14:48:34,415 recheck_focus() wid=8, focused=8, latest=True
> 2020-07-23 14:48:34,661 _unfocus() wid=5643, focused=8
> 2020-07-23 14:48:38,554 disabled debugging for:
> 2020-07-23 14:48:38,556  - Logger(xpra.client.client_window_base, focus)
> 2020-07-23 14:48:38,558  - Logger(xpra.client.mixins.window_manager, focus)
> 2020-07-23 14:48:38,559  - Logger(xpra.client.gtk_base.gtk_client_window_base, focus, grab)
> ```
> 
> However, I don't know how to trigger that sequence of events.
> 
> I know that I had time to:
> * observe it (LibreOffice to PyCharm, Ctrl+P triggered "Print" instead of ala-Sublime "Go to file ..."),
> * switch to terminal, enable client diagnostics
> * re-trigger it (Triggered "Complete last command" on terminal), and
> * work around it (raise and re-minimize an app).

**Comment by stdedos** [comment]
Nowadays it's worse: Only the "Search Anywhere" facility is taking focus, all other ones (e.g. Find in Path, Go to line) are explicitly not focused, and you need to mouse-click them to give them focus.

"Nominal setup": S:Focal/C:Win10, xpra v4.1.x both, 2 monitors on client.

**Comment by totaam** [comment]
Confirmed. Reproducible on Fedora 34.

ie: the "Go to line" window has the window focus, but not the input focus.
Moving the pointer anywhere over this popup window "fixes" things and the input focus ends up where it should be. So does clicking on the main window.
I think they're using a hidden input window that needs to have the focus.

With `-d focus`, I see nothing unusual:
```
client   5 @12.343 mapped: has-toplevel-focus=False
client   5 @12.344 ClientWindow(63) focus_change(ClientWindow(63), <GParamBoolean 'has-toplevel-focus'>) has-toplevel-focus=True, _been_mapped=True
client   5 @12.345 recheck_focus() wid=7, focused=63, latest=False
process_focus: wid=63
focus wid=63 has_focus=7
focus: giving focus to WindowModel(0x16008cc)
Giving focus to 0x16008cc
 ... using XSetInputFocus
focus: will set modified mask to (b'control', b'mod2') using <bound method InputMixin.make_keymask_match of ClientConnectionMuxer(5 : Protocol(unix-domain socket:/run/user/1000/xpra/localhost.localdomain-10))>
focus wid=63 has_focus=63
```
The focus goes from 7 (the main window) to 63 (the popup dialog).

**Comment by totaam** [comment]
This was a **monster**!
It is yet another bug (we've had hundreds) caused by cython / python3's annoying differentiation between byte strings and character strings - in 99% of cases, we just don't care but python does.
`XGetWMProtocols` returns C `char`s, which end up as byte strings with python3.
So although the list of window protocols contained `WM_TAKE_FOCUS`, we never actually matched it..

I suspect that this is going to fix a number of other tricksy tickets! (and not just #2882)

**Comment by stdedos** [comment]
A monster of +10/-6 🤣🤣🤣🤣🤣

SO NICE that you are getting so much ahead with the leftover issues 😄 
I am preparing a latency issue to report to you next week (27ms-650ms which xpra makes a 500ms-4000ms delay 😝).

**Comment by stdedos** [comment]
idk why I never said that this issue was fixed at-the-time. Because IIRC, it was.

However, this ...
> ie: the "Go to line" window has the window focus, but not the input focus.
> Moving the pointer anywhere over this popup window "fixes" things and the input focus ends up where it should be. So does clicking on the main window.
> I think they're using a hidden input window that needs to have the focus.

came back again "sometime recently" (e.g. last 2 months).

If you could quickly re-verify that with your Fedora?
If it doesn't happen for you, I'll downgrade to test that it was actually verified, and then give you a good...bad range to bisect.

**Comment by totaam** [comment]
> If you could quickly re-verify that with your Fedora?

I have verified this with both a Fedora and win10 clients and there are no focus problems with any windows I could find.
I also tested with 4.2.1-RC, still no problems.

---

I did manage to reproduce some very broken behaviour with sharing enabled and connecting two clients with very different screen geometries simultaneously: one was 3x4K the other just 720p.
It looks like those jetbrains tools do their own window placement and so some of the windows can end up off-screen for one of the clients. We normally compensate for that but that didn't seem to work in this case.

This should not be a problem for most users and your problem is likely different.

**Comment by stdedos** [comment]
There's also https://github.com/Xpra-org/xpra/issues/1941 related to window movement/placement.

**Comment by stdedos** [comment]
> This should not be a problem for most users and your problem is likely different.

Okay; then: let's close this one as fixed (https://github.com/Xpra-org/xpra/issues/2852#issuecomment-875527391) and open a new one? 😕

`-d focus` gives:
```
2021-07-14 10:53:27,470 process_focus: wid=15
2021-07-14 10:53:27,470 focus wid=15 has_focus=7
2021-07-14 10:53:27,470 focus: giving focus to WindowModel(0x1410505)
2021-07-14 10:53:27,470 Giving focus to 0x1410505, input_field=0, FORCE_XSETINPUTFOCUS=True, protocols=['WM_DELETE_WINDOW', 'WM_TAKE_FOCUS']
2021-07-14 10:53:27,470 ... using XSetInputFocus
2021-07-14 10:53:27,470 ... using WM_TAKE_FOCUS
2021-07-14 10:53:27,470 sending WM_TAKE_FOCUS: 0x1410505, X11 timestamp=4067517476
2021-07-14 10:53:27,471 focus: will set modified mask to (b'mod2',) using <bound method InputMixin.make_keymask_match of ClientConnectionMuxer(2 : Protocol(unix-domain socket:/run/user/1000/xpra/u-h-2))>
2021-07-14 10:53:27,647 focus wid=15 has_focus=15
2021-07-14 10:53:27,648 focus wid=15 has_focus=15
2021-07-14 10:53:28,153 focus wid=15 has_focus=15
2021-07-14 10:53:28,289 focus wid=15 has_focus=15
2021-07-14 10:53:28,324 focus wid=15 has_focus=15
2021-07-14 10:53:28,345 focus wid=15 has_focus=15
2021-07-14 10:53:28,425 focus wid=15 has_focus=15
2021-07-14 10:53:28,443 focus wid=15 has_focus=15
2021-07-14 10:53:28,462 focus wid=15 has_focus=15
2021-07-14 10:53:28,570 focus wid=15 has_focus=15
2021-07-14 10:53:28,590 focus wid=15 has_focus=15
2021-07-14 10:53:28,590 focus wid=15 has_focus=15
2021-07-14 10:53:28,670 focus wid=15 has_focus=15
2021-07-14 10:53:28,689 focus wid=15 has_focus=15
2021-07-14 10:53:28,706 focus wid=15 has_focus=15
2021-07-14 10:53:28,788 focus wid=15 has_focus=15
2021-07-14 10:53:28,788 focus wid=15 has_focus=15
2021-07-14 10:53:28,804 focus wid=15 has_focus=15
2021-07-14 10:53:28,872 focus wid=15 has_focus=15
2021-07-14 10:53:28,891 focus wid=15 has_focus=15
2021-07-14 10:53:28,909 focus wid=15 has_focus=15
2021-07-14 10:53:28,975 focus wid=15 has_focus=15
2021-07-14 10:53:28,992 focus wid=15 has_focus=15
2021-07-14 10:53:28,993 focus wid=15 has_focus=15
2021-07-14 10:53:29,067 focus wid=15 has_focus=15
2021-07-14 10:53:29,085 focus wid=15 has_focus=15
2021-07-14 10:53:29,103 focus wid=15 has_focus=15
2021-07-14 10:53:29,146 focus wid=15 has_focus=15
2021-07-14 10:53:29,180 focus wid=15 has_focus=15
2021-07-14 10:53:29,253 focus wid=15 has_focus=15
2021-07-14 10:53:30,682 process_focus: wid=0
2021-07-14 10:53:30,682 focus wid=0 has_focus=15
2021-07-14 10:53:30,682 reset_focus() 15 / WindowModel(0x1410505) had focus (toplevel=WorldWindow(0x2c00009))
2021-07-14 10:53:30,683 reset_x_focus: widget with focus: None
2021-07-14 10:53:30,683 Take Focus -> world window
2021-07-14 10:53:30,683 sending WM_TAKE_FOCUS: 0x2c00009, X11 timestamp=4067520688
2021-07-14 10:53:30,774 process_focus: wid=1
2021-07-14 10:53:30,774 focus wid=1 has_focus=0
```

and I guess you don't see something out of the ordinary here, right?
(and I also see `WM_TAKE_FOCUS` being sent, so I guess nothing)
