### ISSUE TITLE
migrate away from trac and svn

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2967]
They have served us well for over 10 years, but without any meaningful progress, especially with trac still not supporting python3 properly..
It's time to move on.

Options (in no particular order):
* migrate to gitlab using [tracboat](https://github.com/tracboat/tracboat) (itself hosted on github!?) - either hosted at [gitlab.com](https://gitlab.com/) or self-hosted on the current hardware, or even elsewhere
* migrate to github using [trac-to-github](https://github.com/svigerske/trac-to-github)

There are pros and cons for each option:
* amount of work for migrating
* amount of maintenance work
* cost
* accessibility
* making it easier for others to contribute
* maintaining existing documentation links and resources (could keep trac in read-only mode for a while)
* preserving code authors in git history
* ci / cd
* use oauth if self-hosted?

**Comment by stdedos** [comment]
> The repositories and tickets are now available here: ​https://github.com/Xpra-org

🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

Welcome to the other side 😀 
You could've added tags for these ones too!

component: external | priority: major

**Comment by totaam** [comment]
Adding a redirect in each ticket - this will take time to run:

    for i in `seq 4 3008`; do
      python2 -c "from trac.env import Environment;from trac.ticket import Ticket;\
      env = Environment('/var/lib/trac/Xpra/', create=0);\
      tkt = Ticket(env, $i);tkt.save_changes('migration script', comment='this ticket has been moved to: [https://github.com/Xpra-org/xpra/issues/%s]' % \"$i\")";
    done

github seems to do the right thing for tickets that have been moved to  https://github.com/Xpra-org/xpra-html5

**Comment by stdedos** [comment]
I don't know why you splitted the html repo; but yeah - if it works, you should do that.

At least https://xpra.org/trac/ticket/2967 -> https://github.com/Xpra-org/xpra/issues/2967 works

**Comment by totaam** [comment]
LGTM.

Public announcement on the mailing list: [migration to github](https://lists.devloop.org.uk/pipermail/shifter-users/2021-February/002742.html)

**Comment by stdedos** [comment]
After _so many years_ (and more than 2 years of experience in Gitlab) ... I _sort-of_ regret my decision :sweat_smile: 

Github has "less features" than Gitlab - which work better in Github ...
but Github CI is **so far behind** with comparison to Gitlab's.

_After learning to ignore a lot of Gitlab's stuff_ that you don't use, then the CI is **many times over** worth it

I know it's "a little bit too late", but I did want to just leave this here for posterity
