### ISSUE TITLE
python << 3.9

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2972]
*Issue migrated from trac ticket # 2972*

**component:** android | **priority:** major | **resolution:** invalid

#### 2020-12-09 10:04:15: pot created the issue

___
> Is there a reason why the current Xpra build for Debian requires python << 3.9?
> 
> This is blocking Debian testing upgrade

**Comment by tb1** [comment]
Same thing with the groovy repo (and likely others, I haven't checked)

**Comment by totaam** [comment]
> Same thing with the groovy repo

There is no 'groovy' repo.
Ubuntu Groovy has reached end of support in July 2020.

> and likely others, I haven't checked

Not with any supported distribution.
