### ISSUE TITLE
The A-key repeated after changing the Input Source of macOS

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2977]
*Issue migrated from trac ticket # 2977*

**component:** keyboard | **priority:** major

#### 2020-12-11 11:41:27: toshi created the issue

___
> I attach the server from Mac mini (M1, 2020) and entered the A-key in the xterm of the server.  The A-key input get repeated, after I change the Input Source (default is Cmd + Space) of macOS.  The A-key is ignored, after the repeating is interrupted.  If I kill the xpra and then reattach, it will recover.
>

**Comment by SaitouToshihide** [comment]
This patch (shown in #3026) resolve the problem.  So, this ticket can be closed.

(There are other issues with Input Source that need to be improved, but I can't explain the situation well.)
