### ISSUE TITLE
Announce video stream as DLNA/UPnP media source

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2995]
*Issue migrated from trac ticket # 2995*

**component:** network | **priority:** major

#### 2021-01-08 16:54:27: amontero created the issue

___
> Usage scenario:
> Nowadays, all TVs feature DLNA "client" (renderer in DLNA parlance). They can render multimedia streams available in the LAN from any available media server. It is also a standard widely supported by lots of devices and software (Playstation, VLC, Kodi).
> By just announcing the stream to the LAN (via an optional switch), any of these devices could be used as a monitor without any direct (physical) cabling to PC/server.
> I'm still not deep into xpra usage, but think of it as secondary desktop on your TV or to use a headless (no VGA, DVI, HDMI physical cabling) for a desktop. Or just easily exposing a single GUI app output to the LAN.
> 
> Since there is already a media stream, only doing a proper UPnP server LAN broadcast would do, since client devices would just connect to the stream.
> My Python is not that awesome, but with proper guidance I can even take a stab at it.

**Comment by Falc0nreeper** [comment]
Hi.  I trying to test it but there is no /video url.  The XPRA was installed via the official package Ubuntu 22.04 
![image](https://github.com/Xpra-org/xpra/assets/38694458/c49616a1-dace-4c89-8d99-fb8349fff936)

**Comment by Falc0nreeper** [comment]
@totaam Just I want to implement some session recording functionality but I need to know The XPRA codebase and architecture
