### ISSUE TITLE
better network congestion handling

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3001]
Follow up to #2812, see also #2421.

**Comment by stdedos** [comment]
Unfortunately, #2812 was not enough to resolve this issue:

[xpra-2812-server-display-_0.log](https://github.com/Xpra-org/xpra/files/6010009/xpra-2812-server-display-_0.log)
[xpra-2812-client.log](https://github.com/Xpra-org/xpra/files/6010010/xpra-2812-client.log)

I could try to make all of this with a `-d stats`, but I am afraid that the server logs will bloat out of proporsion.

**Comment by totaam** [comment]
Will probably improve things as part of #3337
