### ISSUE TITLE
gtk client: auto reconnect feature

### ISSUE THREAD

**Issue by pillo79** [Xpra-org/xpra#3010]
I'm using Xpra to forward applications from a Linux VM to the Windows host so the applications are seamlessly integrated. However, every time the system is put in standby all sockets are closed, causing a connection error and the Xpra connect window reappears. 

Would it be possible to add an automatic connection retry in case of network errors?

**Comment by totaam** [comment]
This will do for now.

**Comment by totaam** [comment]
Forgot: cff50de835e9392ff30ccb11dcdd645973b079e3.
Related: a5c3d904e42050067c05d791ea63bc9e34656548.

**Comment by JeffFaer** [comment]
Is there any way to turn off this behavior?

I looked through the conf.d directory looking for something but didn't find anything obvious :/

My xpra connection goes through an SSH key that needs 2fa. So when xpra tries to reconnect, I get an annoying popup on my desktop asking me to touch my security key. I'd rather the xpra connection just die until I go around to reestablishing it

**Comment by totaam** [comment]
@JeffFaer
```shell
$ xpra -h | grep recon
    --reconnect=yes|no  Reconnect to the server. Default: yes.
```
