### ISSUE TITLE
[Documentation / Examples / Screenshots] Could this be added as a link or something to the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [Xpra-org/xpra#3016]
Hey xpra devs,

I found this project via gosu ( a C++ and ruby engine).

However, I am not entirely sure what is possible with xpra exactly.

Would it be possible to add a few partial screenshots of what people do with it? This does not
have to be all-inclusive, really just a few screenshots to see in one glance what can be done
with it. Does not have to be listed in the main README per se (although that is also possible
of course); could just be a separate page that keeps a few screenshots. While I am a ruby
guy, I am fine with python examples too and even other languages - I am mostly interested
in "what can be done with xrpa specifically". (If there was a screenshot page already as-is
I may not have seen it; in that case perhaps the section on the README could be made
longer in this regard.) Thank you for reading and potentially considering.

**Comment by totaam** [comment]
We used to have [screenshots on the old wiki](https://xpra.org/trac/wiki/Screenshots).
I guess we could make some new ones for github.

The real difficulty is that the remote forwarded windows are meant to look identical to local applications, so it's not really obvious what to look for on those screenshots.  
I guess we could show some X11 applications forwarded to a MS Windows or MacOS desktop - that's assuming people will recognise that those are X11 applications and not native applications.

**Comment by stdedos** [comment]
These look too ugly to be confused with "normal" Windows apps:
![](https://xpra.org/trac/raw-attachment/wiki/Screenshots/XP-dual-screen.png)
![](https://xpra.org/trac/raw-attachment/wiki/Screenshots/Windows-8.1-UnigineValley.png)

**Comment by totaam** [comment]
@stdedos can you please provide some pretty screenshots?

I know that it's obvious to you and me that those windows are not from native MS Windows applications, but for casual users just browsing the front page, we may need `xpra attach --border=red,5` to make it clearer I think.

**Comment by stdedos** [comment]
That sounds like a plan! I am not close to my setup right now, but I can definitely cook something up :-)

I have some xpra tests to do soon, so hopefully I can do two things at once 😉 

> We used to have screenshots on the old wiki.
> I guess we could make some new ones for github.

However, I wonder: Didn't those screenshots "come with us" to the new site? 😕

**Comment by totaam** [comment]
> However, I wonder: Didn't those screenshots "come with us" to the new site? confused

Every ticket has been migrated, wiki pages were either converted or archived.
https://xpra.org/trac-attachments/
https://xpra.org/screenshots/
That's all I've got right now - probably best to make some new screenshots anyway.
An outdated tray menu running on MS Windows 7 doesn't exactly advertise a modern software!

**Comment by stdedos** [comment]
> An outdated tray menu running on MS Windows 7 doesn't exactly advertise a modern software!

Yes, but I am missing that so much 🤓

![https://xpra.org/screenshots/xpra-session-info.png](https://xpra.org/screenshots/xpra-session-info.png)

In any case, I have started a new page here https://github.com/Xpra-org/xpra/wiki/Usage-Examples
Hopefully, they are "everything they have to be" 🙏 😸
