### ISSUE TITLE
Entire client display flashes white with exotically-shaped window in Autodesk Maya

### ISSUE THREAD

**Issue by dhou-memverge** [Xpra-org/xpra#3017]
Hi,

I'm trying to use Xpra with Autodesk Maya, a graphics and animation software. Autodesk Maya has a feature where a rather exotically-shaped window appears when the user right clicks and holds on the main viewport.

![Screenshot from 2021-02-16 13-12-14](https://user-images.githubusercontent.com/52430611/108122086-a0138980-7058-11eb-809c-f361b0a80b2e.png)

When I launch Maya in Xpra and open this menu, the entire client display becomes white while the menu is up.

I am on Centos 7.8 and am using the xpra from the official xpra repos. You can get a free trial of Autodesk Maya from their website if you want to try it out yourself.

Any help would be appreciated. Thanks!

**Comment by totaam** [comment]
This reminds me of a bug we had with eclipse:
https://github.com/Xpra-org/xpra/issues/2900#issuecomment-765551040

Maybe this solution (using ibus) will work for you here?
Otherwise, please capture `xpra info` exactly when the problem is showing.
Is your client also on CentOS 7.8?


I am afraid that going through hoops to install proprietary applications (registration, licensing, etc) is not a high priority.

**Comment by dhou-memverge** [comment]
I tried `xpra start --input-method=ibus --start-env=QT_IM_MODULE=ibus --start=maya :25` which did not affect the bug.
I also tried `XPRA_USE_PIL=0` and `XPRA_ALPHA=0`, no effect.

`xpra info`:
[xpra_info.txt](https://github.com/Xpra-org/xpra/files/6045360/xpra_info.txt)

My client is also on CentOS 7.8.

The info on the relevant window from the log:
```
windows.11.XShm=True
windows.11.above=False
windows.11.allowed-actions=('_NET_WM_ACTION_CLOSE', '_NET_WM_ACTION_MOVE', '_NET_WM_ACTION_RESIZE', '_NET_WM_ACTION_FULLSCREEN', '_NET_WM_ACTION_MINIMIZE', '_NET_WM_ACTION_SHADE', '_NET_WM_ACTION_STICK', '_NET_WM_ACTION_MAXIMIZE_HORZ', '_NET_WM_ACTION_MAXIMIZE_VERT', '_NET_WM_ACTION_CHANGE_DESKTOP', '_NET_WM_ACTION_ABOVE', '_NET_WM_ACTION_BELOW')
windows.11.below=False
windows.11.bypass-compositor=0
windows.11.class-instance=('maya.bin', 'Maya-2020')
windows.11.client-machine=m
windows.11.command=
windows.11.content-type=
windows.11.depth=32
windows.11.focused=False
windows.11.fullscreen=False
windows.11.geometry=(0, 0, 1920, 1080)
windows.11.grabbed=0
windows.11.has-alpha=True
windows.11.maximized=False
windows.11.opacity=-1
windows.11.override-redirect=True
windows.11.pid=50195
windows.11.shaded=False
windows.11.shown=True
windows.11.size=(1920, 1080)
windows.11.skip-pager=False
windows.11.skip-taskbar=False
windows.11.state=('_NET_WM_STATE_STAYS_ON_TOP',)
windows.11.sticky=False
windows.11.title=Marking Menu
windows.11.tray=False
windows.11.window-type=('_KDEOVERRIDE', 'NORMAL')
windows.11.workspace=65535
windows.11.xid=0x800e6e
```

The menu in question seems to be producing a full-screen window with alpha. It seems that the result is a full-screen window with nothing drawn (or rather, all grayish-white drawn). 

I found this issue from a very long time ago: https://www.xpra.org/trac/ticket/500 . Seems superficially similar.

> I am afraid that going through hoops to install proprietary applications (registration, licensing, etc) is not a high priority.

No problem, fully understand. Let me know if there's more information you need for diagnosing!

**Comment by totaam** [comment]
It would be worth trying this application with more recent server and client versions.

Is there anything in your server log?
Can you attach the output of the command `xpra screenshot screenshot.png` when this window is shown?
