### ISSUE TITLE
Render Windows Without Explicit Attach

### ISSUE THREAD

**Issue by mbalkanloo** [Xpra-org/xpra#3028]
Currently, windows are not rendered until a client "attaches". This means that commands such as `xdotool` have no available windows to operate on until an explicit call to `xpra attach` is made in a terminal session with X11 forwarding. I have tried many variations of `xdotool` commands to try to force rendering but to no avail. To allow rendering without an explicit attach would significantly enhance automation capabilities and I would be enormously grateful for this feature.

Thank you for considering this request and thank you for developing and supporting Xpra.

**Comment by totaam** [comment]
The original discussion on the mailing list is here: [Render Without Attach](https://lists.devloop.org.uk/pipermail/shifter-users/2021-February/002747.html)

OTOH, we just need a new control channel command to trigger `WindowModel.map()`.

**Comment by mbalkanloo** [comment]
Thank you for reviewing this request.

I have found that I am able to achieve the desired result by running `Xvfb` directly.

I simply run the GUI application in an `Xvfb` session, use `xdotool` commands to interact with the interface, and subsequently run `xpra start-desktop` if I need to attach and interact with the GUI manually.

Please feel free to close the request if you like.

**Comment by totaam** [comment]
That was easy, with the commit above you can do (I added `sync-xvfb` to the command be able to see the state of the virtual screen using `scrot` or other screen capture tools):
```
xpra start --start=xterm --sync-xvfb=20 :100
```
Then:
```
WID=1
xpra control :100 map $WID
# the window shows up on the vfb, then:
xpra control :100 unmap $WID
```
The first window to show up will be `1`, you can identify your windows with `xpra info`.
