### ISSUE TITLE
use annotated tags and git describe --tags to generate the version string

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3034]
See https://github.com/Xpra-org/xpra/commit/5286af5814ae911b4d8373e71e5289e0e4c1922d#commitcomment-47546705

**Comment by stdedos** [comment]
I am pulling your response here:

> > unfortunately, no one told you in time that you should've created your version tags as annotated
> 
> IIRC, I didn't do this myself or was given the choice: this was automated in the conversion script.

Well, I am not sure if it's a "de-facto" standard, but IMHO I would've definitely added something like that 😕 

> There may be issues with tools parsing the version string, either from `xpra --version` or from `xpra info`.
> Apart from that, there's no reason why we can't switch to `git describe --tags` for a future release if the version is correctly tagged with an annotated tag, is there?

With `git describe --tags`, your tags don't need to be annotated. I don't really know why is Git requires that on a plain `git describe`, but that's what happens anyway (and https://git-scm.com/book/en/v2/Git-Basics-Tagging here's the lowdown)

**Comment by totaam** [comment]
> ... should be switched to the output of

It's not that simple.
Many users will build from source snapshots, hence why we store `REVISION` in `xpra.src_info` and retrieve it later.

The code in `add_build_info.py` has been updated to use `git describe --long --always --tags`.
(found out the hard way that the extra flags are important)

**Comment by stdedos** [comment]
The `--tags` flag is not important, if you use "annotated tags"? 😕 

https://git-scm.com/book/en/v2/Git-Basics-Tagging#_creating_tags

**Comment by totaam** [comment]
We do use annotated tags!?

**Comment by stdedos** [comment]
Okay - awesome 😄 

I just wanted to make sure that this was the case.
Therefore `--tags` are not needed here:
https://github.com/Xpra-org/xpra/blob/67e79fbbd2090d453da15563cfbd99404b4d0bad/fs/bin/add_build_info.py#L310-L315

I can make a PR/more extensive test later in the day if you'd like.

**Comment by stdedos** [comment]
I don't think it really does - so let's ignore me 😄
