### ISSUE TITLE
"UI thread is now blocked" when using opengl

### ISSUE THREAD

**Issue by aerusso** [Xpra-org/xpra#3035]
Hello,

I am running Debian xpra (`3.0.13+dfsg1-1`), and I'm getting log messages like

```
client   6 @42.106 UI thread is now blocked
client   6 @43.063 UI thread is running again, resuming
```

These fill up the logs (they can be hundreds of megabytes), and do not occur when I use `--opengl=no` on the client.

There are (at least) two situations that trigger these messages

1. Switching to another vt, with any X11 application (e.g. xterm) running.  This (seems to) result in a single blocked/running again pair---corresponding to the switch away from and return to the VT.
2. Allowing X11 DPMS to power down the monitor, with an opengl application (e.g., firefox) running.  Once the screen powers down, I get many pairs of messages with block times upwards of 10 seconds.

I suppose opengl calls block in these situations, and the client is genuinely stalling---but is there maybe a better way to handle this?

**Comment by totaam** [comment]
> but is there maybe a better way to handle this?

I have no idea how we could handle this better: if the program's main loop is not running, we have no control.

**Comment by aerusso** [comment]
First of all---can you reproduce this, or is this some weird quirk of my setup?  Like, should I be figuring out why OpenGL is stalling instead of fighting to patch every X11 (and also wayland? I haven't tested that) application?

Without worrying about implementation details, I can think of a couple ways this could be handled better:

- (a) Don't log this at all---it's complete noise, and there's no reason to track it.  Maybe put some switch that lets you enable and disable client stalls at runtime, since you might need this, but probably not all the time since there's a TON of noise on that channel.
- (b) Detect (or track?) when OpenGL is blocking, and enter some "quiet" mode---tell the xpra server not to send updates and reduce bandwidth/CPU consumption when there are no updates.

Frankly, now that I think about it, 1. (i.e., the behavior when I switch to another VT) is basically desirable behavior: it is just a slightly louder form of (b).

Could we detect on the client side that we're stalling---and send some kind of alive-pings every timeout period to the server that we're OK, suppressing the server logspam?

**Comment by totaam** [comment]
> First of all---can you reproduce this, or is this some weird quirk of my setup?

I will try. Which driver are you using? Which exact Debian version, etc

> Don't log this at all---it's complete noise

No it's not. It's very useful for diagnostics.
If someone complains that the screen updates are sluggish, this tells us exactly why.

> tell the xpra server not to send updates and reduce bandwidth/CPU consumption when there are no updates

We already do that:
https://github.com/Xpra-org/xpra/blob/master/xpra/client/gtk_base/gtk_client_base.py#L209
If we didn't, things would go into a bad state.

> Could we detect on the client side that we're stalling

That's what this is.
> and send some kind of alive-pings every timeout period to the server that we're OK, suppressing the server logspam

Those messages correspond to the `suspend` and `resume` events we generate.

**Comment by aerusso** [comment]
>> First of all---can you reproduce this, or is this some weird quirk of my setup?
>
> I will try. Which driver are you using? Which exact Debian version, etc

This is amdgpu, Debian up-to-date testing, (xpra `3.0.13+dfsg1-1`)

glxinfo:
> Device: Radeon RX 560 Series (POLARIS11, DRM 3.39.0, 5.9.0-5-amd64, LLVM 11.0.1) (0x67ff)

I'm running KDE (kwin_x11 5.20.5).

If this isn't something you can just easily reproduce by switching to another vt and noticing the UI blocked response, I'm inclined to think it's something weird about my drivers and not worth bothering about, especially since:

> Those messages correspond to the suspend and resume events we generate.

Is there any harm in me just setting `XPRA_UI_THREAD_POLLING=30000`? I promise I'll unset it before filing bugs about stuttering graphics!  I don't want to waste effort on something minor like this.

**Comment by totaam** [comment]
> Is there any harm in me just setting XPRA_UI_THREAD_POLLING=30000?

Yes, if the delay is too high (not sure what value that would be) then we won't notice that the UI thread has gone out to lunch fast enough and the server will go into a state where it thinks the network or client are having serious trouble and it may even drop the connection.

**Comment by aerusso** [comment]
I ran into some interesting observations looking at this more closely, but I'd like to nail this down first, if you think the approach is sound.

Notice that the default does not affect the behavior at all.

**Comment by totaam** [comment]
FWIW: OpenGL stops whenever the X11 server is not the active VT:
https://github.com/Xpra-org/xpra/issues/3057#issuecomment-801621815

And so you're lucky that the application doesn't just stop completely.
