### ISSUE TITLE
xpra top: version string displays incorrectly

### ISSUE THREAD

**Issue by shururuun** [Xpra-org/xpra#3041]
On a Debian server with Xpra 4.1, using "xpra top" the version string at the top of the display says (what I assume) the function reference instead of the version string:

"Xpra top <function full_version_str at 0x7fa651d67048>"

**Comment by totaam** [comment]
Oops, didn't notice until now!
Fixed in 22c1c9e3dc075fbc489f6fba7e1392b7eb4c1d48.

This will be included in the next stable update.
