### ISSUE TITLE
VSOCK connectivity issue

### ISSUE THREAD

**Issue by mattsuth** [Xpra-org/xpra#3047]
I'm running XPRA on a VM that I connect to via the VSOCK interface, both the host and guest are Ubuntu 20.04.  After the last release through the XPRA APT repo (package version v.4.1-r28561-1 and the more recent v4.1.1-r28-1) VSOCK connectivity is broken (note: not the main Ubuntu repos, this is the repo on xpra.org for 'focal').  The upgraded client can connect to older XPRA servers, but if the server is upgraded to that version it fails.  There is a python error in the logs when I attempt to connect, shown below.  The error appears to be how "bytestreams.py" is handling the client address, looks like VSOCK hands it an int as an address but it expects an IP address as a string:

```
Exception in thread new-vsock-connection:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 1073, in handle_new_connection
    log_new_connection(conn, socket_info)
  File "/usr/lib/python3/dist-packages/xpra/net/bytestreams.py", line 631, in log_new_connection
    frominfo = pretty_socket(peername)
  File "/usr/lib/python3/dist-packages/xpra/net/bytestreams.py", line 93, in pretty_socket
    if s[0].find(":")>=0:
AttributeError: 'int' object has no attribute 'find'
```
I took a quick look at the code in Github and the line in bytestreams.py that fails appears to be the same in master as in the error above, is there anything I should do to gather more info?

**Comment by totaam** [comment]
Sorry about that.
The commit above should fix this issue. It's tiny so you can apply it by hand to your installation.

Otherwise, I have uploaded beta 4.1.2 and 4.2 packages for Ubuntu Focal to the beta area: https://xpra.org/beta/
