### ISSUE TITLE
OpenGL Probe Error on OSX Big Sur

### ISSUE THREAD

**Issue by skalathoor3** [Xpra-org/xpra#3048]
Xpra crashes during launch with OpenGL error. The popup shows Open GL Acceleration Failure, and Xpra crashes. Crash log as reported by OSX is attached (along with screenshots of error).
[xpra_crashlog.txt](https://github.com/Xpra-org/xpra/files/6097791/xpra_crashlog.txt)
<img width="402" alt="Screen Shot 2021-03-07 at 2 11 38 PM" src="https://user-images.githubusercontent.com/80219700/110251600-3c8dc500-7f4f-11eb-896f-10649f833269.png">
<img width="400" alt="Screen Shot 2021-03-07 at 2 11 15 PM" src="https://user-images.githubusercontent.com/80219700/110251603-3f88b580-7f4f-11eb-888c-b603c0a6045c.png">

**Comment by totaam** [comment]
@skalathoor3 is this a regression in 4.2 beta builds?
Are you seeing this with 4.1.x? (or was this also the case with 4.0.x?)
Have you tried 4.1.1 released yesterday? Does running with `--splash=no` fix things?
Does the client not continue after this probe error?

**Comment by skalathoor3** [comment]
It turns out there was an authentication problem on my server side. Once I set up my server with SSH keys to bypass the password request, I was able to connect successfully.

Both the latest release 4.1.1 and beta 4.2 work, without using --splash=no.

Closing ticket as invalid.
