### ISSUE TITLE
xpra shadow ignores keyboard variant (Dvorak)

### ISSUE THREAD

**Issue by tmo1** [Xpra-org/xpra#3054]
I'm trying out xpra between Debian Sid systems. I have the Dvorak keyboard variant configured (via /etc/default/keyboard) on both client and server. I get the correct Dvorak layout with `xpra start ssh://hostname/ --start=xterm`, but with `xpra shadow ssh://hostname/`, the standard Qwerty variant is used. I tried `xpra shadow ssh://hostname/ --keyboard-layout=us --keyboard-variant=dvorak`, but Qwerty is still used instead of Dvorak.

Note that in all cases xpra reports `keyboard settings: rules=evdev, model=pc105, layout=us` and doesn't mention the variant, but it does use the correct Dvorak variant with `xpra start` but not with `xpra shadow` (at least the way I ran those commands).

**Comment by totaam** [comment]
In seamless and desktop modes the server side keyboard is configured to match your client keyboard exactly: the layout and variant will be preserved. Whereas in shadow mode, we never modify the existing session, so the each keys is translated dynamically.

You may have better luck with `--keyboard-raw=yes`.

**Comment by tmo1** [comment]
Hi,
Thanks - I tried `--keyboard-raw=yes`, but the problem remains. I don't really need `shadow` anyway, so I'll probably just stick with `start` and `start-desktop`.

**Comment by totaam** [comment]
> `TypeError: vstr() missing 1 required positional argument: 'v'`

This has been fixed for quite some time: 6dcc65256a41807e6ea9f90843fb5c15407c28bb.
What outdated version are you running?
Surely you'r not running a version that old?

**Comment by tmo1** [comment]
```
~$ xpra --version
xpra v3.1
```

**Comment by totaam** [comment]
> `xpra v3.1`

And why are you running an outdated version? What distro is this on. On anything but CentoS 7, this is not the version you should be using.

Please try a supported version, and report more details as per:
https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
As per https://github.com/Xpra-org/xpra/issues/3054#issuecomment-955629992, this is probably caused by running an outdated version.
