### ISSUE TITLE
xpra client detected as harmful by windows 10 edge /w defender

### ISSUE THREAD

**Issue by tomuxi** [Xpra-org/xpra#3056]
Both of these
- https://xpra.org/dists/windows/Xpra-Client-Python2-x86_64_3.0.13-r28289.msi
- https://xpra.org/dists/windows/Xpra-Client-Python2-x86_64_Setup_3.0.13-r28289.exe

are doomed by Microsoft Edge 89.0.774.45 on Windows 10 as potentially malicious, prohibiting install.

Is this something to worry about?

**Comment by totaam** [comment]
Probably not, we keep getting false positives from various AV vendors:
* Symantec: #527
* Microsoft: #2781

Does it give you any details about which part it is unhappy about?
Or is their "AI" being facetious again?

**Comment by tomuxi** [comment]
I am not sure, supposedly the Smartscreen functionality is flagging it and I have difficulties of getting any clear judgement data from it. It may be an AI decision...

Anyhow, I reported these as false positives to Microsoft. Hopefully they will agree at some point.
