### ISSUE TITLE
Help: VirtualGL and Xpra in headless enviroment

### ISSUE THREAD

**Issue by svargh** [Xpra-org/xpra#3057]
This issue is to get some help/support  how to configure VirtualGL/XPra in headless enviroment - more VirtualGL I guess.

Xpra Start (from ssh connection):
`xpra start --start=xterm --bind-tcp=0.0.0.0:10000 --html=on --daemon=no`
```
vmuser@vmuser:~$ xpra --version
xpra v4.2
```
```
VirtualGL version is 2.6.80
See also sections below  'Video hardware info' and 'Video hardware info'
```

In my case, VirtualGL acceleration works in xpra, but only when desktop session is visible:
- E.g. Firefox WebGL [Kev3d Waves](http://www.kevs3d.co.uk/dev/shaders/waves5.html) Xpra runs with 60FPS(same as on host), Without acceleration it would be only 1FPS/2FPS.
- Working glmark2 shows  VMWare and GL_VENDOR
![virtualglok](https://user-images.githubusercontent.com/13705625/111437070-f8df4c00-8702-11eb-91b1-df94fe67f437.png)

**Not working: desktop session is not visible**
If the user logs out (only Login screen visible) or switching to console, then acceleration is not working:
- then vglrun hangs until I switch back or log into the desktop session (cannot reproduce currently)
- The following error occur :
```
vmuser@vmuser:~$ vglrun +v glmark2 # user logged out
[VGL] Shared memory segment ID for vglconfig: 98342
[VGL] VirtualGL v2.6.80 64-bit (Build 20210315)
[VGL] Opening connection to 3D X server :0
[VGL] ERROR: Could not open display :0.
```

     

  - Not working - user logged off- login manager visible:

![nok](https://user-images.githubusercontent.com/13705625/111437166-12809380-8703-11eb-8c0e-4b64024ff5f3.png)

  - Not working - user logged off - loginmanager active - switchted to text console:
![nok-console](https://user-images.githubusercontent.com/13705625/111438366-70fa4180-8704-11eb-9c5e-043280718ede.png)

**Not working: Starting Xpra, X11 Desktop session ended (in headless)**
```
root@vmuser:/home/vmuser# service gdm stop
root@vmuser:/home/vmuser# service ssh restart^C
root@vmuser:/home/vmuser# exit
exit
vmuser@vmuser:~$ xpra start --start=xterm --bind-tcp=0.0.0.0:10000 --html=on --daemon=no
2021-03-17 08:08:10,348 created tcp socket '0.0.0.0:10000'
2021-03-17 08:08:11,354 cannot access python uinput module:
2021-03-17 08:08:11,354  No module named 'uinput'
2021-03-17 08:08:12,541 Warning: some of the sockets are in an unknown state:
2021-03-17 08:08:12,541  /home/vmuser/.xpra/vmuser-0
2021-03-17 08:08:12,541  please wait as we allow the socket probing to timeout
2021-03-17 08:08:18,553 created unix domain socket '/run/user/1000/xpra/vmuser-0'
2021-03-17 08:08:18,553 cannot create group socket '/run/xpra/vmuser-0'
2021-03-17 08:08:18,553  [Errno 13] Permission denied
2021-03-17 08:08:18,555 created unix domain socket '/home/vmuser/.xpra/vmuser-0'
2021-03-17 08:08:18,604 pointer device emulation using XTest
2021-03-17 08:08:18,701 serving html content from '/usr/share/xpra/www'
2021-03-17 08:08:18,761 D-Bus notification forwarding is available
2021-03-17 08:08:18,773 pulseaudio server started with pid 6141
2021-03-17 08:08:18,773  private server socket path:
2021-03-17 08:08:18,773  '/run/user/1000/xpra/pulse-0/pulse/native'

(Xpra:6082): Gtk-CRITICAL **: 08:08:18.825: gtk_widget_realize: assertion 'widget->priv->anchored || GTK_IS_INVISIBLE (widget)' failed
2021-03-17 08:08:18,837 Warning: webcam forwarding is disabled
2021-03-17 08:08:18,837  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2021-03-17 08:08:18,837  make sure that the 'v4l2loopback' kernel module is installed and loaded
2021-03-17 08:08:18,837  or use the 'webcam=no' option
2021-03-17 08:08:18,837 found 0 virtual video devices for webcam forwarding
2021-03-17 08:08:19,034 xpra is ready.
2021-03-17 08:08:19,098 GStreamer version 1.16.2 for Python 3.8.5 64-bit
2021-03-17 08:08:27,075 printer forwarding enabled using postscript and pdf
2021-03-17 08:08:27,080 started command 'xterm' with pid 6226
2021-03-17 08:08:27,081 Warning: cannot watch for application menu changes without pyinotify:
2021-03-17 08:08:27,081  No module named 'pyinotify'
2021-03-17 08:08:27,141 vpx: vp9 encoding failed: failed to instantiate vp9 encoder with ABI version 23: Invalid parameter
2021-03-17 08:08:27,398 19.1GB of system memory
2021-03-17 08:08:28,114 OpenGL is supported on display ':0'
2021-03-17 08:08:28,114  using 'llvmpipe (LLVM 11.0.0, 256 bits)' renderer
2021-03-17 08:08:28,132 loaded 72 start menu entries from 9 sub-menus in 1.0 seconds
2021-03-17 08:08:28,438 xpra GTK3 X11 version 4.2 64-bit
2021-03-17 08:08:28,439  uid=1000 (vmuser), gid=1000 (vmuser)
2021-03-17 08:08:28,439  running with pid 6082 on Linux Ubuntu 20.04 focal
2021-03-17 08:08:31,649  connected to X11 display :0 with 24 bit colors

```
Running vglrun against xpra headless without gdm:

```
vmuser@vmuser:~$ vglrun glmark2
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 11.0.0, 256 bits)
    GL_VERSION:    3.1 Mesa 20.2.6
=======================================================
[build] use-vbo=false:X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Serial number of failed request:  44
  Current serial number in output stream:  45
vmuser@vmuser:~$ glmark2
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 11.0.0, 256 bits)
    GL_VERSION:    3.1 Mesa 20.2.6
=======================================================
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
[build] use-vbo=false:^C
vmuser@vmuser:~$ glxinfo | grep Vendor
    Vendor: Mesa/X.org (0xffffffff)
vmuser@vmuser:~$ glxinfo | grep direct
direct rendering: Yes
    GL_AMD_gpu_shader_int64, GL_AMD_multi_draw_indirect, 
    GL_ARB_derivative_control, GL_ARB_direct_state_access, 
    GL_ARB_draw_elements_base_vertex, GL_ARB_draw_indirect, 
    GL_ARB_indirect_parameters, GL_ARB_instanced_arrays, 
    GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multi_draw_indirect, 
    GL_AMD_multi_draw_indirect, GL_AMD_query_buffer_object, 
    GL_ARB_direct_state_access, GL_ARB_draw_buffers, 
    GL_ARB_draw_indirect, GL_ARB_draw_instanced, GL_ARB_enhanced_layouts, 
    GL_ARB_indirect_parameters, GL_ARB_instanced_arrays, 
    GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multi_draw_indirect, 
    GL_EXT_direct_state_access, GL_EXT_draw_buffers2, GL_EXT_draw_instanced, 
vmuser@vmuser:~$ 
```

**How I configured Hardware acceleration**
I applied in the VMWare guest Ubuntu 20.04LTS the following  commands given
in [docker-xpra-html5-gpu-minimal](https://github.com/ffeldhaus/docker-xpra-html5-gpu-minimal)

Installing VirtualGL similar to [this](https://github.com/ffeldhaus/docker-xpra-html5-gpu-minimal/blob/master/Dockerfile) Dockerfile
```
apt install libegl1-mesa libxv1
root@vmuser:/home/vmuser#  VIRTUALGL_VERSION=2.6.80
root@vmuser:/home/vmuser# curl -fsSL -O https://s3.amazonaws.com/virtualgl-pr/dev/linux/virtualgl_${VIRTUALGL_VERSION}_amd64.deb

root@vmuser:/home/vmuser# dpkg -i virtualgl_${VIRTUALGL_VERSION}_amd64.deb
Selecting previously unselected package virtualgl.
(Reading database ... 226808 files and directories currently installed.)
Preparing to unpack virtualgl_2.6.80_amd64.deb ...
Unpacking virtualgl (2.6.80-20210315) ...
Setting up virtualgl (2.6.80-20210315) ...
root@vmuser:/home/vmuser


echo "\nclass-instance:vglrun=video" >> /etc/xpra/content-type/50_class.conf

```

```
root@vmuser:~# cat dri.sh
#!/bin/bash

if [ ! -d "/dev/dri" ];then
    echo "ERROR: Directory /dev/dri does not exists, likely the GPU is not available to container."
    exit 1
fi

# ensure that xpra user is part of vglusers group which must have been set for /dev/dri/card0
DRI_CARD_GROUP_NAME=$(ls -l /dev/dri/card* | head -1 | awk '{print $4}')
DRI_CARD_GID=$(ls -ln /dev/dri/card* | head -1 | awk '{print $4}')
groupadd -f -g $DRI_CARD_GID $DRI_CARD_GROUP_NAME
DRI_RENDER_GROUP_NAME=$(ls -l /dev/dri/render* | head -1 | awk '{print $4}')
DRI_RENDER_GID=$(ls -ln /dev/dri/render* | head -1 | awk '{print $4}')
groupadd -f -g $DRI_RENDER_GID $DRI_RENDER_GROUP_NAME
usermod --groups $DRI_CARD_GID,$DRI_RENDER_GID --append vmuser

# start xpra as xpra user with command specified in dockerfile as CMD or passed as parameter to docker run
#CMD="XPRA_PASSWORD=$XPRA_PASSWORD /usr/bin/xpra start --daemon=no --start-child='$@'"
#runuser -l xpra -c "$CMD"

```

**Video hardware info:**
```
Last login: Wed Mar 17 07:53:19 2021 from 192.168.90.1
vmuser@vmuser:~$ ls -all /dev/dri/card*
crw-rw----+ 1 root video 226, 0 Mar 17 07:52 /dev/dri/card0
vmuser@vmuser:~$ ls -all /dev/dri/render*
crw-rw----+ 1 root render 226, 128 Mar 17 07:52 /dev/dri/renderD128
vmuser@vmuser:~$ groups
vmuser adm cdrom sudo dip video plugdev render lxd
vmuser@vmuser:~$
```

```
vmuser@vmuser:~$ glmark2
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 11.0.0, 256 bits)
    GL_VERSION:    3.1 Mesa 20.2.6
=======================================================
** GLX does not support GLX_EXT_swap_control or GLX_MESA_swap_control!
** Failed to set swap interval. Results may be bounded above by refresh rate.
[build] use-vbo=false:^C
vmuser@vmuser:~$ vglrun glmark2
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     VMware, Inc.
    GL_RENDERER:   SVGA3D; build: RELEASE;  LLVM;
    GL_VERSION:    3.3 (Compatibility Profile) Mesa 20.2.6
=======================================================
[build] use-vbo=false:^C
vmuser@vmuser:~$ 

```

**Comment by totaam** [comment]
> If the user logs out (only Login screen visible) or switching to console, then acceleration is not working:

Are you sure that this is VirtualGL problem?
Can you run any OpenGL application on your physical display after switching to the console? (without stalling for long periods)

**Comment by svargh** [comment]
> 
> 
> > If the user logs out (only Login screen visible) or switching to console, then acceleration is not working:
> 
> Are you sure that this is VirtualGL problem?

I am not so deep into VirtualGL, X11.
But I tried in another VMWare Instance with Xrdp and gdm disabled, only text console on physical display.
There, firefox WebGl and glmark2 do work with VMWare 3d hardware acceleration.

> Can you run any OpenGL application on your physical display after switching to the console? (without stalling for long periods)

Sorry, I hope, I understood your question correctly:
1.  Switching to the console on physical display ( I press Ctrl+F4), then any app for display :0 work
```
  export DISPLAY=:0
  firefox or glmark2
  # Switching back  to session( Ctrl+F1), I see the firefox/glmark2 window using VMWare device
```
2.  Switching to the console ( I press Ctrl+F4) , 
    then typing the following commands in xterm started by a xpra client:
  -  Without vglrun: Apps  run, but slow (Firefox WebGlTest) slow  (Mesa/X.org) 
  - With vglrun: Apps  do not run: 
```
[VGL] Opening connection to 3D X server :0
[VGL] ERROR: Could not open display :0.
```
This  error occur also, when I stop the gdm service

**Comment by svargh** [comment]
Update: Update to 2.

>     2. Switching to the console ( I press Ctrl+Alt+F4) ,
>        then typing the following commands in xterm started by a xpra client:
> 
> 
>     * Without vglrun: Apps  run, but slow (Firefox WebGlTest) slow  (Mesa/X.org)
> 
>     * With vglrun: Apps  do not run:
> 
> 
> ```
> [VGL] Opening connection to 3D X server :0
> [VGL] ERROR: Could not open display :0.
> ```
> 
> This error occur also, when I stop the gdm service.
> 
This this, not an error occurs, but vglrun glmark2 on xterm of xpra client  just hangs forever.
It starts glmark2 hw accelerated until I press Alt F1 on host and login back to the session on physical display.

```

vmuser@vmuser:~$ vglrun +v glmark2
[VGL] Shared memory segment ID for vglconfig: 98352
[VGL] VirtualGL v2.6.80 64-bit (Build 20210315)
[VGL] Opening connection to 3D X server :0
#Waiting forever until login in physical screen
```

**Comment by totaam** [comment]
As per https://github.com/VirtualGL/virtualgl/issues/160#issuecomment-801281233
*However, the 3D X server VT must always be the active VT in order to use hardware-accelerated OpenGL. That is a system limitation, and it has existed for as long as VirtualGL has existed*

**Comment by svargh** [comment]
Thanks  for pointing me to the already same issue in VirtualGL!
Sorry,  i am not familiar with hardware accelerated/X11 stuff and "active VT".
Please excuse my stupid questions...

1) What do you recommend, how to use Xpra hardware accelerated but headless, without Active VT, without physical display (e.g. using in docker or lxc). 


2) Do you have an idea whether instead of using VirtualGL, using "somehow" Xrdp might work out?
In Xrdp there is no "active VT", no login manager, but I saw Firefox webgl, glmark2 working hardware accelerated.
Is the same possible with Xpra?

**Comment by totaam** [comment]
> What do you recommend, how to use Xpra hardware accelerated but headless

AFAIK. It depends on how many users you want to have and what GPU(s) are installed.
If you have more concurrent users than the number of GPUs in the system then you will need to use VirtualGL, so please refer to that project's documentation.
Otherwise, there are headless GPU options.

No idea how Xrdp does it, but I don't see why this could not also be used with xpra. Let us know if you figure it out.

**Comment by svargh** [comment]
> 
> 
> > What do you recommend, how to use Xpra hardware accelerated but headless
> 
> AFAIK. It depends on how many users you want to have and what GPU(s) are installed.
> If you have more concurrent users than the number of GPUs in the system then you will need to use VirtualGL, so please refer to that project's documentation.
> Otherwise, there are headless GPU options.
> 
> No idea how Xrdp does it, but I don't see why this could not also be used with xpra. Let us know if you figure it out.

**Thank you very much  for pointing me to the right direction, it has helped much!**

Just an update:
**Xpra works for me now without active VT by pointing VirtualGl to a running Xorg session from xrdp.**

Actually xrdp is not needed.
But I needed something easy which starts the complex X11 machinery with Accelerated 3D support.

I haven't understood, how docker-xpra-html5-gpu-minimal can work with accelerated Virtualgl without an active VT/Xorg session, when running Firefox WebGl, it was still using the cpu and using vglrun firefox doesn't work...

Anyway, Xpra with Xrdp (using only its X11 session) works fine in VMWare, and works in docker running in VMWare too - sharing VMWare's /dev/dri among all docker containers just works.

Firing several Xpra docker instances sharing all the same GPU is really nice too see.
So now, the stuff is ready to be deployed on a real NVidia RTX 3090!

**Comment by totaam** [comment]
> Actually xrdp is not needed.
> But I needed something easy which starts the complex X11 machinery with Accelerated 3D support.

If I were you, I would figure out the exact command line and config files which are used to start the accelerated X11 server and then use those alone.
Then your dependencies and container image will be a lot slimmer and far less likely to break should the behaviour change.

https://virtualgl.org/Documentation/HeadlessNV
