### ISSUE TITLE
Versions 4.x won't connect on Windows 10

### ISSUE THREAD

**Issue by vrbadev** [Xpra-org/xpra#3058]
I am experiencing problems while trying to connect with SSH->SSH to our university server. It starts connecting, wants me to approve new SSH key and then it prints red text: 'NoneType' object has no attribute 'ioctl'. What can I do about that?
Version 3.0-r24039 works just fine so I can stick with it till this is fixed.

**Comment by totaam** [comment]
@vrbadev I can't be certain, but I believe that the fix above should resolve your problems.
If that's the case, then versions from the 4.0.x branch should also work and only versions 4.1 and later are affected.

**Comment by totaam** [comment]
@vrbadev there are 4.2 builds for MS Windows with this fix here: https://xpra.org/beta/windows/
Does that fix the problem for you?

**Comment by totaam** [comment]
I assume this is now working.
