### ISSUE TITLE
Inconsistent parameter values for switching features on and off

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3061]
xpra uses inconsistent parameter values to switch features off by default (and the user can enable them) or to permanently disable them.

Clipboard:

- `--clipboard=no` disabled it permanently
- `--clipboard-direction=disabled` disables it only by default but allows to enable it

Sound:

- `--speaker=disabled` disables it permanently
- `--speaker=off` disables it by default but allows to enable it.

**Comment by totaam** [comment]
Sorry, but the code evolved to reach this shape and I'm not going to spend time on this.
pull requests will be accepted though.

**Comment by allo-** [comment]
I won't do a pull-request that changes configuration values without anyone having agreed on this before.
The implementation should not be the problem, the decision how to name things consistently is.
