### ISSUE TITLE
macosx Catalina+ "damaged application" workaround 

### ISSUE THREAD

**Issue by area42** [Xpra-org/xpra#3062]
FYI to get around the "damaged application" gatekeeper block you can use

 `sudo xattr -rd com.apple.quarantine /Applications/Xpra.app`

**Comment by area42** [comment]
issue can be closed. just FYI

**Comment by totaam** [comment]
Thanks!

Added to the FAQ and https://github.com/Xpra-org/xpra/wiki/Download
