### ISSUE TITLE
OpenGL Probe Fails on Mac OS (M1, Apple Silicon)

### ISSUE THREAD

**Issue by johncadengo** [Xpra-org/xpra#3063]
When trying to connect to any session, I get a little error at the bottom right of my screen saying "OpenGL Probe Failed"

I tried running the `OpenGL_Check` file, found here: `/Applications/Xpra.app/Contents/Helpers`

Installed it from the releases in Xpra, and also through Brew. Both fail in the same way.

This is the error I get:

```
$ ./OpenGL_check 

(OpenGL-Check:29731): Gtk-CRITICAL **: 11:49:12.038: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

OpenGL errors:
  ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)

(OpenGL-Check:29731): Gdk-WARNING **: 11:49:12.133: losing last reference to undestroyed window
```

Running an M1 Mac Mini.

**Comment by totaam** [comment]
This can safely be ignored.

From now on, we will not show the warning on MacOS. Apple has decided to stop supporting OpenGL and I suspect that this is what is causing the problem. (perhaps the `OpenGL` library is not even installed since we fail to `dlopen` it)

**Comment by johncadengo** [comment]
@totaam question. If there is no OpenGL, is there hardware acceleration supported for xpra on Mac OS? Are there plans to use Metal, for example?

**Comment by totaam** [comment]
@johncadengo Vulkan would be the way to go (via an emulation layer on MacOS): #3064

**Comment by johncadengo** [comment]
@totaam Ok,I see. Thanks for the response. I'll watch that issue.

**Comment by johncadengo** [comment]
@totaam Maybe this isn't a matter of Apple's dropping of OpenGL support. I dug into the issue a bit and found this: https://github.com/PixarAnimationStudios/USD/issues/1372

Which pointed to a fix that was merged into a recent version of Python 3.9, and backported to 3.8 as well: https://github.com/python/cpython/pull/22855

So I wanted to test if my M1 Mac can work with OpenGL, and I updated my Python to the latest version via brew (3.9.2):

```
➜  ~ pip3 install PyOpenGL PyOpenGL_accelerate
Collecting PyOpenGL
  Downloading PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 7.4 MB/s 
Collecting PyOpenGL_accelerate
  Downloading PyOpenGL-accelerate-3.1.5.tar.gz (538 kB)
     |████████████████████████████████| 538 kB 31.4 MB/s 
Building wheels for collected packages: PyOpenGL-accelerate
  Building wheel for PyOpenGL-accelerate (setup.py) ... done
  Created wheel for PyOpenGL-accelerate: filename=PyOpenGL_accelerate-3.1.5-cp39-cp39-macosx_11_0_arm64.whl size=330980 sha256=24d9416effbeac6740126ec1c03be295fd6017d06e9a321146a351e80581da89
  Stored in directory: /Users/johncadengo/Library/Caches/pip/wheels/32/bf/f2/fc5d1e29923dab6c757eca3fe7265b9a5b0c0550a08bc1307f
Successfully built PyOpenGL-accelerate
Installing collected packages: PyOpenGL-accelerate, PyOpenGL
Successfully installed PyOpenGL-3.1.5 PyOpenGL-accelerate-3.1.5
➜  ~ python3                                  
Python 3.9.2 (default, Mar 26 2021, 15:28:17) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenGL import GL
```

I was able to install and import PyOpenGL without an error. Is it possible that by updating the version of Python that's included with Xpra that this issue for me could be solved?

**Comment by totaam** [comment]
> Is it possible that by updating the version of Python that's included with Xpra that this issue for me could be solved?

We're already shipping Python 3.9.2

[This solution](https://stackoverflow.com/a/65599706/428751) monkey patches the `find_library` function and should allow PyOpenGL to load the library again.
@johncadengo can you test this? There's an xpra 4.2 beta build with this change here: https://xpra.org/beta/MacOS/
(bear in mind that if the OpenGL library is still not found, you won't see a notification, just a log message since a39d002b8489528f15c74746d80226d85339bc11)

**Comment by totaam** [comment]
It might be possible to make native builds using [cross platform emulation](https://blogs.blackberry.com/en/2021/05/strong-arming-with-macos-adventures-in-cross-platform-emulation)

**Comment by totaam** [comment]
@johncadengo we now have beta arm64 builds that should be able to run on M1 and later, they require MacOS 12:
https://github.com/Xpra-org/xpra/wiki/Download#-macos
