### ISSUE TITLE
xpra-html5-4.1.1-1.deb for bionic has "any" architecture

### ISSUE THREAD

**Issue by oischinger** [Xpra-org/xpra#3065]
This results in the following error:
`dpkg: error processing archive /tmp/apt-dpkg-install-eUowh5/369-xpra-html5_4.1_amd64.deb (--unpack):
 package architecture (any) does not match system (amd64)`

**Comment by olifre** [comment]
I observe the same issue on Debian Buster since today.

**Comment by totaam** [comment]
Wrong repo, here's the correct ticket: https://github.com/Xpra-org/xpra-html5/issues/37
