### ISSUE TITLE
No documentation for how to use Windows 10 version

### ISSUE THREAD

**Issue by znmeb** [Xpra-org/xpra#3066]
I have been unable to find any documentation on how to use the Windows version of Xpra. I installed the package, but when I try to connect to a server via SSH I get "connection lost". I don't know what's going on, and there's no Help function.

**Comment by totaam** [comment]
Was an xpra session available on the server you tried to connect to?
The [usage](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/README.md) examples should have you covered.
(just replace `xpra` with `xpra_cmd.exe` on MS Windows)

**Comment by znmeb** [comment]
@totaam I managed to get it working with WSL ... but I need something I can hand to a Windows user that says:

1. How to install the Xpra client on Windows.
2. What to type in the boxes.
3. What the "Shadow Server" and "Browse" buttons do.

etc.

I'm working with users that aren't necessarily command-line appreciative. If they have to open a command shell on the Windows machine I'll lose a good percentage of them.

**Comment by totaam** [comment]
> How to install the Xpra client on Windows.

Just run the EXE installer.
https://github.com/Xpra-org/xpra/wiki/Download#-microsoft-windows

> What to type in the boxes.

When you move your pointer over the form input areas, a tooltip should appear which tells you what needs to be typed in.  
The first commit above improves those messages shown.  
Ideally, you could just give your users prepared `.xpra` session files or URLs they can just click on to connect without even having to see the GUI dialog window.

> What the "Shadow Server" and "Browse" buttons do.

There's also a tooltip for those buttons, and the messages were improved in the second commit.  
Do you think there's more we should do?  
The shadow server is [documented here](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Shadow-Server.md).

**Comment by znmeb** [comment]
@totaam I managed to get it working with WSL ... but I need something I can hand to a Windows user that says:

1. How to install the Xpra client on Windows.
2. What to type in the boxes.
3. What the "Shadow Server" and "Browse" buttons do.

etc.

I'm working with users that aren't necessarily command-line appreciative. If they have to open a command shell on the Windows machine I'll lose a good percentage of them.

> 
> 
> > How to install the Xpra client on Windows.
> 
> Just run the EXE installer.
> https://github.com/Xpra-org/xpra/wiki/Download#-microsoft-windows
> 
> > What to type in the boxes.
> 
> When you move your pointer over the form input areas, a tooltip should appear which tells you what needs to be typed in.
> The first commit above improves those messages shown.
> Ideally, you could just give your users prepared `.xpra` session files or URLs they can just click on to connect without even having to see the GUI dialog window.
> 
> > What the "Shadow Server" and "Browse" buttons do.
> 
> There's also a tooltip for those buttons, and the messages were improved in the second commit.
> Do you think there's more we should do?
> The shadow server is [documented here](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Shadow-Server.md).
> 
> Edit: there are beta builds with those minor changes here: [https://xpra.org/beta/windows/]

Thanks! I'll take a look at these later today.

**Comment by totaam** [comment]
> What to type in the boxes.

Perhaps just give them session files already made so they don't have to type anything at all?
You can generate them from the launcher to have an example file, the format is self explanatory.
Add `autoconnect=true` and the launcher will be skipped completely.
