### ISSUE TITLE
Origin change on apt update -- Debina Buster

### ISSUE THREAD

**Issue by cpcn** [Xpra-org/xpra#3069]
On a machine running Debian Buster during normal apt update  I get the below error message:

    Get:6 https://xpra.org buster InRelease [4,081 B]                
    E: Repository 'https://xpra.org buster InRelease' changed its 'Origin' value from 'winswitch.org' to 'xpra.org'
    N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

should the new origin be accepted?

**Comment by totaam** [comment]
Yes: 5dd47a01a3fa3a7f9374319a431a4a5d0f0aac37
