### ISSUE TITLE
xpra upgrade forgets the server image codecs

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3071]
After an "xpra upgrade", the server sends an empty list of picture codecs (At least the info window shows an empty list) and the client uses "auto", probably choosing an raw encoding.

    2021-04-03 03:19:58,445 server does not support png/P encoding and has switched to auto

Xpra 4.1.1 on both sides installed using the debian packages provided by

    deb https://xpra.org/ bullseye main

on the client and

    deb https://xpra.org/ buster main

on the server side.

**Comment by totaam** [comment]
Thanks for the bug report, this had been broken for quite a while.
