### ISSUE TITLE
[run_scaled] Incorrect scaling

### ISSUE THREAD

**Issue by SamLukeYes** [Xpra-org/xpra#3072]
I'm using Arch Linux with GNOME (Wayland). `run_scaled-git` in AUR and `xpra` v4.0.6-3 from [community] repo can provide expected scaling. However, `xpra-git` v4.1.r257.g37b6dc36f-1 doesn't scale the application correctly.

Use the executable `qq` in AUR package `linuxqq` as an example. When running without `run_scaled`, its window looks like this:
![image](https://user-images.githubusercontent.com/12882091/113470199-4b03c980-9486-11eb-91b6-de1fc630a8a3.png)

With `run_scaled qq`, the window appears to be too large:
![image](https://user-images.githubusercontent.com/12882091/113470236-a2099e80-9486-11eb-89b2-4a4a4e0defa8.png)

With `run_scaled --scale=1 qq`, the window size appears to be normal, but the words are too large for the interface:
![image](https://user-images.githubusercontent.com/12882091/113470271-e9902a80-9486-11eb-87bc-0cd3ca53dffb.png)

Curiously, when executing `run_scaled` in Guake, this scaling issue is gone, though the words are greyed out (might be related to the dark theme):
![image](https://user-images.githubusercontent.com/12882091/113470539-f3b32880-9488-11eb-8a15-b5e97f601fab.png)

All the other ways I tried to launching `run_scaled`, including GNOME Terminal, Nautilus Terminal, the terminal in VSCode, and launching through a desktop entry, can reproduce the issue. I also noticed that Xpra starting window is also smaller when `run_scaled` is launched with Guake. ~~The version of `run_scaled` script itself (the original shell script, my own re-write version according to the shell script, or the one comes with the latest Xpra) seems to be unrelated.~~ The tests above were performed with the script provided by the latest Xpra.

 BTW, it would be nice to add input method support to `run_scaled`. Currently, I can't use the input method `fcitx5` in an application scaled by `run_scaled` without editing the script to specify the arguments `--input-method=keep` and `--start=fcitx5`.

**Comment by totaam** [comment]
Does the problem go away if you change `start-child` into `start-child-after-connect` in `run_scaled`?

My guess is that your applications are using the DPI from the vfb (no idea which one is used in arch - xvfb? Xdummy?), which is just the default value until the client actually connects.

**Comment by SamLukeYes** [comment]
> Does the problem go away if you change `start-child` into `start-child-after-connect` in `run_scaled`?

Unfortunately, this doesn't solve the problem.

> Another way of dealing with this is to make your settings permanent - if that's applicable to you:
> 
> ```
> echo "input-method=keep" >> ~/.config/xpra/xpra.conf
> ```

Oh thanks, this works for me.

**Comment by totaam** [comment]
> Unfortunately, this doesn't solve the problem.

Then xpra's xvfb may be misconfigured in ArchLinux.  
It's probably using an unpatched [Xdummy](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md). Switch to `Xvfb` in `/etc/xpra/conf.d/55_server_x11.conf`.

**Comment by SamLukeYes** [comment]
> It's probably using an unpatched [Xdummy](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md).

That's strange. I've been actually using [xf86-video-dummy-xpra-patch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xf86-video-dummy-xpra-patch). Doesn't it apply the patches properly?

> Switch to `Xvfb` in `/etc/xpra/conf.d/55_server_x11.conf`.

This doesn't help either.

----

BTW, I just noticed that the original `run_scaled` script behaves a bit different from the one in this repo. Fonts are rendered in the expected size when using the original shell script, so using that script with `--scale=1` is a workaround.

**Comment by totaam** [comment]
> We can't just add every command line argument to run_scaled unless we add a -- argument that then passes every other command line argument to xpra

And this is exactly what has been added: e6a2c6471ed65c6de153ca9bbe3c63404befa3a4

As for the actual scaling issue, I'm still not sure what I am looking at.
Do you have simple steps so that I can reproduce the problem with a simple open-source app?

**Comment by SamLukeYes** [comment]
> Do you have simple steps so that I can reproduce the problem with a simple open-source app?

Had a try with Qt4 Designer.

Without `run_scaled`:

    $ designer-qt4

![2021-11-06 18-19-42屏幕截图](https://user-images.githubusercontent.com/12882091/140606498-a4eb8fbd-0f41-48ea-9fc3-e6548c1b4d0f.png)

Text is in normal size, but the widgets are too small.

With `run_scaled`:

    $ run_scaled designer-qt4

![2021-11-06 18-24-07屏幕截图](https://user-images.githubusercontent.com/12882091/140606717-9b611796-4694-42af-ae77-bb89a8239529.png)

Both text and widgets are too large for my screen.

    $ run_scaled --scale=1 designer-qt4

![2021-11-06 18-34-18屏幕截图](https://user-images.githubusercontent.com/12882091/140606786-24698479-3131-4fde-ad79-dabbdbc6ef46.png)

Widgets are likely in normal size, but the text is still a little too large.

Formally Guake sets `GDK_BACKEND=x11`, which causes different behavior than other Terminal Emulators. See https://github.com/Guake/guake/issues/1871

    $ export GDK_BACKEND=x11
    $ run_scaled designer-qt4

![2021-11-06 19-04-28屏幕截图](https://user-images.githubusercontent.com/12882091/140607322-7b5d9072-378f-40f0-a2c1-99cbd9543aa2.png)

The text looks better this time. I also noticed that the Xpra window is smaller after setting `GDK_BACKEND=x11`. Not sure whether this is related.

Before setting `GDK_BACKEND`:
![2021-11-06 19-14-25屏幕截图](https://user-images.githubusercontent.com/12882091/140607557-d5c42c58-0c37-4c2f-8f5e-fa6bab864e41.png)

After setting `GDK_BACKEND=x11`:
![2021-11-06 19-12-40屏幕截图](https://user-images.githubusercontent.com/12882091/140607590-62cd2ad4-3345-4215-9739-6d036baaee10.png)

The tests above are done in Wayland session. My current GNOME Shell version is 41.1, Xpra version is 4.2.2.

**Comment by totaam** [comment]
I assume that this is fixed in newer versions.
In particular a patched dummy >= 0.4.1 with xpra v5.
