### ISSUE TITLE
notifications are not shown correctly

### ISSUE THREAD

**Issue by goekce** [Xpra-org/xpra#3074]
I am on Archlinux with i3 window manager and use xpra version 8557ff5cbcdbadcc431cf9fb98be2557f844ad95. The notifications are shown like this:

![image](https://user-images.githubusercontent.com/18174744/113718039-8c95ae00-96ec-11eb-9991-6c455ab94b85.png)
(used `notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information`)

The notification windows cannot be closed and I have to disconnect from xpra. I am using the native xpra client over wss.

I didn't have this problem one month ago and will try to install an older version. Meanwhile has someone an idea what the problem could be?

**Comment by totaam** [comment]
Please post the `-d notify` command output. I don't use `i3`, the way it handles window geometries can be problematic.

**Comment by goekce** [comment]
I noticed that I had no notification manager installed on my local machine. Probably it was removed in last weeks. After installing a notification daemon (`dunst`) the problem is solved. I also tried with 829b9ea64e3bf0cb08cbeab0ce132313043b140c.

 I thought that the notification windows would be rendered by the xpra server – apparently not true. My hypothesis is that my client (i3 to be more specific) tried to draw the notifications as normal windows, so my window was full of tiled notification confetti.

Thank you for the idea totaam, I do not need to debug anymore. Please let me know if you wish more info.
