### ISSUE TITLE
kde apps file open makes app frozen

### ISSUE THREAD

**Issue by kuszinger** [Xpra-org/xpra#3076]
Hello!

Kde apps (cloudcomapare, qgis) gets frozen after file open - it is kde file open dialog, I think.
Dialog opens, file selected, ok pressed. Dialog disappears but app stays frozen.
How could I debug further, check what the problem is?

I don't know if it has any relevance, but both are flatpak distributed apps. flatpak list is at the end.

Thanks: Robert

SERVER: 
```
[kuszi@robert-aspire ~]$ xpra --version
xpra v4.0.6-r28285
[kuszi@robert-aspire ~]$ uname -a
Linux robert-aspire 5.11.6-1-MANJARO #1 SMP PREEMPT Thu Mar 11 19:05:51 UTC 2021 x86_64 GNU/Linux
```

CLIENT:
WIndows 10 4.1.2 client
```
Python 3.8, 64bit
revision 78
commit gb75b0f2c9 from v4.1.x branch
with 0 local changes
built on Win10-Build-VM by Windows 10 Test
2021-04-06 20:32
using Cython 0.29.22
gcc (Rev9, Built by MSYS2 project) 10.2.0

```

```

[kuszi@robert-aspire ~]$ flatpak list
Név                                   Alkalmazásazonosító                      Verzió  Ág     Installation
AnyDesk                               com.anydesk.Anydesk                      6.1.0   stable system
DBeaver Community                     io.dbeaver.DBeaverCommunity              21.0.1  stable system
CloudCompare                          org.cloudcompare.CloudCompare                    stable system
Freedesktop Platform                  org.freedesktop.Platform                 20.08.6 20.08  system
default                               org.freedesktop.Platform.GL.default              20.08  system
nvidia-460-39                         …g.freedesktop.Platform.GL.nvidia-460-39         1.4    system
nvidia-460-56                         …g.freedesktop.Platform.GL.nvidia-460-56         1.4    system
Intel                                 org.freedesktop.Platform.VAAPI.Intel             18.08  system
Intel                                 org.freedesktop.Platform.VAAPI.Intel             20.08  system
html5-codecs                          org.freedesktop.Platform.html5-codecs            18.08  system
openh264                              org.freedesktop.Platform.openh264        2.1.0   2.0    system
GNOME Application Platform version 3… org.gnome.Platform                               3.38   system
Adwaita theme                         org.kde.KStyle.Adwaita                           5.12   system
Adwaita theme                         org.kde.KStyle.Adwaita                           5.15   system
KDE Application Platform              org.kde.Platform                                 5.12   system
KDE Application Platform              org.kde.Platform                                 5.15   system
QGIS asztali alkalmazás               org.qgis.qgis                            3.18.1  stable system

```

**Comment by totaam** [comment]
Can you reproduce this problem with any application available from the standard Fedora repositories?

I assume that you're using seamless mode and that the problem does not occur in desktop mode?

**Comment by kuszinger** [comment]
Wow! Thanks... I've tried desktop mode and yes, both cloudcompare and qgis file dialogs work well... 
I tried with other KDE apps like rkward and kdenlive but all run well.
And even more, after this desktop mode success cloudcompare and qgis both wok in seamless mode (???) - How could it be?

Is there any permanent (config?) change somewhere following a desktop mode?

thanks
Robert

**Comment by totaam** [comment]
> Is there any permanent (config?) change somewhere following a desktop mode?

No. Something in the environment perhaps?
Or the apps themselves?
You did start them from `--start=` or from a child thereof, right?

**Comment by kuszinger** [comment]
--start=xterm

tmux in xterm and then command line (different tmux screens for each):
`flatpak run org.qgis.qgis for example`


BTW in terminal messages there was nothing special in tmux referring to an error...

**I'll make further investigations....**

**Comment by totaam** [comment]
I don't think `tmux` changes anything. But it's worth ruling it out and starting directly from the `xterm` instead.

If the problem only occurs with flatpak applications then that's another data point..

**Comment by kuszinger** [comment]
I'll try to find a repo packaged KDE app and reproduce... and start directly with --start= and/or from xterm.

**Comment by totaam** [comment]
> Kde apps (cloudcomapare, qgis) gets frozen after file open - it is kde file open dialog, I think.

Tested with qgis on Fedora 34, connected from a win10 client with the latest 4.3 beta and I am not seeing any problems.
