### ISSUE TITLE
xpra does not pick up the correct menu applications / snap applications 

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3083]
I did:

```bash
sudo apt-get purge libreoffice-core libreoffice-core-nogui --autoremove
sudo snap install libreoffice
```

and I have even restarted since I've done these commands.

However, xpra has not picked up the snap menu options (they are in start menu)
![image](https://user-images.githubusercontent.com/133706/114201302-b6eea200-995e-11eb-9491-0b44c7990aee.png)

and, instead, has found one "LibreOffice" option in "Office", which gives:
```
    214 2021-04-09 09:59:17,891 started command 'libreoffice' with pid 284573
    215 /usr/bin/libreoffice: 191: exec: /usr/lib/libreoffice/program/oosplash: not found
    216 2021-04-09 09:59:17,896 child 'LibreOffice' with pid 284573 has terminated
```

**Comment by totaam** [comment]
What xpra displays in the start menu is extracted using [pyxdg](https://freedesktop.org/wiki/Software/pyxdg/).
The [menu loader](https://github.com/Xpra-org/xpra/blob/master/xpra/platform/xposix/xdg_helper.py) does include a number of ugly workarounds for various pyxdg "features".
The data we retrieve is all-or-nothing by calling the `Menu.parse` function.

You can see the data by calling the script directly:
```
python3 xpra/platform/xposix/xdg_helper.py
```

**Comment by stdedos** [comment]
```
   1273     - LibreOffice
   1274       - Categories                : Office, X-Red-Hat-Base, X-SuSE-Core-Office, X-MandrivaLinux-Office-Other
   1275       - Comment                   : The office productivity suite compatible to the open and standardized ODF document format. Supported by The Document Foundation.
   1276       - Exec                      : libreoffice %U
   1277       - GenericName               : Office
   1278       - Hidden                    : False
   1279       - Icon                      : libreoffice-startcenter
   1280       - IconData                  : 926 bytes
   1281       - IconType                  : png
   1282       - MimeTypes                 : application/vnd.openofficeorg.extension, x-scheme-handler/vnd.libreoffice.cmis
   1283       - Name                      : LibreOffice
   1284       - NoDisplay                 : False
   1285       - NotShowIn                 : GNOME
   1286       - OnlyShowIn                : []
   1287       - Path                      : 
   1288       - StartupNotify             : True
   1289       - StartupWMClass            : libreoffice-startcenter
   1290       - Terminal                  : False
   1291       - TryExec                   : 
   1292       - Type                      : Application
   1293       - URL                       : 
   1294       - VersionString             : 1.0
   1295       - command                   : libreoffice %U
   1296     - LibreOffice 7.1
   1297       - Categories                : Office, X-Red-Hat-Base, X-SuSE-Core-Office, X-MandrivaLinux-Office-Other
   1298       - Comment                   : The office productivity suite compatible to the open and standardized ODF document format. Supported by The Document Foundation.
   1299       - Exec                      : env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/libreoffice_libreoffice.desktop /snap/bin/libreoffice %U
   1300       - GenericName               : Office
   1301       - Hidden                    : False
   1302       - Icon                      : /snap/libreoffice/208/usr/share/icons/hicolor/256x256/apps/libreoffice7.1-startcenter.png
   1303       - IconData                  : 3898 bytes
   1304       - IconType                  : png
   1305       - MimeTypes                 : application/vnd.openofficeorg.extension, x-scheme-handler/vnd.libreoffice.cmis
   1306       - Name                      : LibreOffice 7.1
   1307       - NoDisplay                 : False
   1308       - NotShowIn                 : []
   1309       - OnlyShowIn                : []
   1310       - Path                      : 
   1311       - StartupNotify             : True
   1312       - StartupWMClass            : libreoffice-startcenter
   1313       - Terminal                  : False
   1314       - TryExec                   : 
   1315       - Type                      : Application
   1316       - URL                       : 
   1317       - VersionString             : 1.0
   1318       - command                   : env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/libreoffice_libreoffice.desktop /snap/bin/libreoffice %U
```

I removed more LibreOffice packages, and the first entry (which was valid after all) disappeared.

Let's see next time what the output will be.

**Comment by stdedos** [comment]
Log out (gdk crash ...) and login fixed the situation

**Comment by totaam** [comment]
Took another look at that menu loading code and added some tweaks above.
The menu should be reloaded automatically now on Debian / Ubuntu, even for flatpak / snap applications - even if `XDG_DATA_DIRS` is unset.

**Comment by stdedos** [comment]
... and now I managed to replicate it again 😂.

```
python3 xpra/platform/xposix/xdg_helper.py | grep -i libre
```

returns nothing; `office` returns only the Office subcategory

**Comment by totaam** [comment]
> ... and now I managed to replicate it again

So... what's the cause? Is it a pyxdg bug?
Where does the libreoffice `.desktop` file live?
Is it somewhere found in `$XDG_CONFIG_DIRS`?
If loading fails, we try unsetting it.
Then we also try various values for `XDG_MENU_PREFIX` to try to find one that does load.

**Comment by stdedos** [comment]
> Where does the libreoffice `.desktop` file live?
```
/snap/libreoffice/21[38]
/usr/share/app-install/desktop # idk if that's from snaps, but the `Exec=` directive works when manually called
/var/lib/snapd/desktop/applications
```

> Is it somewhere found in `$XDG_CONFIG_DIRS`?

No such `$XDG_CONFIG_DIRS` in my bash env

> `XDG_MENU_PREFIX`

No such `XDG_MENU_PREFIX` either

**Comment by totaam** [comment]
`XDG_CONFIG_DIRS`, as per [basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
_If `$XDG_CONFIG_DIRS` is either not set or empty, a value equal to /etc/xdg should be used._
FYI: If we can't load the menus with the current value, we try unsetting it. (not applicable to your setup)

`XDG_MENU_PREFIX`, as per [menu spec](https://developer.gnome.org/menu-spec/):
_`$XDG_CONFIG_DIRS/menus/${XDG_MENU_PREFIX}applications.menu` This file contains the XML definition of the main application menu layout_
We try the following prefix values: unchanged, empty, `gnome-` and `kde-`.

**Comment by stdedos** [comment]
```console
u@h:/etc/xdg/menus$ locate '*.menu'
Running:
locate '*.menu'
/etc/xdg/menus/gnome-applications.menu
/etc/xdg/menus/unity-lens-applications.menu
/etc/xdg/menus/unitycc.menu
/usr/share/app-install/desktop/applications.menu
/usr/share/menu/google-chrome.menu
/usr/share/menu/vivaldi.menu
/home/u/.config/menus/applications-merged/user-chrome-apps.menu
/home/u/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu
u@h:/etc/xdg/menus$ locate '*.menu' | xargs grep -Trin libre
Running:
locate '*.menu'
u@h:/etc/xdg/menus$ locate '*.menu' | xargs grep -Trin termin
Running:
locate '*.menu'
/etc/xdg/menus/gnome-applications.menu:    47:	      <Filename>org.gnome.Terminal.desktop</Filename>
/etc/xdg/menus/gnome-applications.menu:   302:	      <Filename>org.gnome.Terminal.desktop</Filename>
/etc/xdg/menus/gnome-applications.menu:   433:	      <Filename>org.gnome.Terminal.desktop</Filename>
u@h:/etc/xdg/menus$ 
```

I guess I need to dig where on earth are the .menu files for the snap applications 😠

**Comment by stdedos** [comment]
Unfortunately, neither my Bionic laptop (one who gets more regular maintenance, reboots etc) seems to have any .menu files listing LibreOffice.

Instead, it seems that there are a lot of files in
`/var/lib/snapd/desktop/applications/` (e.g. `/var/lib/snapd/desktop/applications/libreoffice_calc.desktop`)

Maybe these are the ones loaded somehow? 😕

**Comment by totaam** [comment]
Logging in to a desktop session on Ubuntu 18.04, I see:
```
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```
This comes from `/etc/profile.d/apps-bin-path.sh`

Adding `--source=/etc/profile` should fix this. (at least the value of `$XDG_DATA_DIRS`)
*BUT* there may be other issues with loading the full `profile` script, it may interfere or cause bugs / crashes. So we may want to source the snap script specifically.

@stdedos does that fix things?

**Comment by stdedos** [comment]
I laser-focused on the `/etc/profile.d/apps-bin-path.sh`; and that fixes things.

Apart from
```
2021-05-27 09:22:44,629 Error: cannot find file '%s' to source
```
😛 

(no adjacent errors)

**Comment by totaam** [comment]
On the subject of snap: #3740
