### ISSUE TITLE
Quality rendering issues

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3085]
Since Focal, `xpra top` now shows constantly what the server is doing quality/speed/network wise.
AWESOME! Now, if I ever see any qual....

![Xpra_cmd_2021-04-09_09-57-56](https://user-images.githubusercontent.com/133706/114203968-544ad580-9961-11eb-9b56-b13577fe110f.png)
![Xpra_cmd_2021-04-09_10-33-22](https://user-images.githubusercontent.com/133706/114204124-7fcdc000-9961-11eb-8f10-8cb525b5bd4a.png)
![Xpra_cmd_2021-04-09_10-45-35](https://user-images.githubusercontent.com/133706/114204151-865c3780-9961-11eb-8b76-bc9844faf41d.png) (Here's the xterm we talked about 😉 https://github.com/Xpra-org/xpra/issues/3077#issuecomment-816561108)
![Xpra_cmd_2021-04-09_10-46-25](https://user-images.githubusercontent.com/133706/114204157-8825fb00-9961-11eb-8e98-66f1e735a018.png)
!!!

This reminds me of https://github.com/Xpra-org/xpra/issues/3042#issuecomment-815501496. You can _clearly_ see (pun intended), that the quality on the last one is 99% percent!

I could constantly trigger this by maximizing the terminal on the screen.
I think I was also able to clear it up by switching to another window; after I took the screenshot, the windows were crispy (I think I have mentioned this in another quality-related ticket, but I cannot find right now).

PS: I just saw that in all of the screenshots, I have been using the 4.1.2 version, and not the latest and greatest 😕
![Xpra_cmd_2021-04-09_10-30-46](https://user-images.githubusercontent.com/133706/114207774-6d558580-9965-11eb-837f-8760c544d370.png)
_PPS: revision 2 😛_

I think I triggered it in 4.2 too; but for some reason, I didn't take more screenshots 😕 
I can try again on Monday.

**Comment by totaam** [comment]
> I could constantly trigger this by maximizing the terminal on the screen.

Doesn't trigger it for me (as usual!). But I believe that I have seen this bug with a plain xterm on my local development system.  
When I looked at the `-d compress` log, the screen updates were using `h264`!
This should not happen:
* `xterm` should be mapped to text mode and never use a video encoder
* video mode should require a high framerate to trigger


> PPS: revision 2 stuck_out_tongue

Yeah. That's annoying as it starts counting from the last tag, which is not what I wanted.  
And then if I build the release packages before I create the tag (as I am used to) then the builds after the tag will have the same version but a lower "revision" number!

**Comment by stdedos** [comment]
> And then if I build the release packages before I create the tag (as I am used to) then the builds after the tag will have the same version but a lower "revision" number!

"I am not at my best time" to talk coding-related stuff; however, the way I had seen the coding around the revision be, I thought it was perfect to keep counting upwards, correctly (minus the "magic number" you introduced). 

"I don't understand how could this happen"

**Comment by stdedos** [comment]
> Doesn't trigger it for me (as usual!). 

Can you keep around permanently that environment you debugged that "enterprise guy's" vpn-in-vpn issue? The one that the batch delay in shadow wasn't compensating quickly enough? 

"Maybe" you'll need to debug my issues in that environment 😕 
(I realize what hassle this could be in the long run, apologies in advance 😕)

**Comment by totaam** [comment]
Summary for my own reference, so I know what to look for: I've seen a plain `xterm` use low quality `h264` with a local connection shortly after connecting!
There are so many reasons why this is wrong:
* we don't use video for text applications
* we should not use video unless the framerate is high
* video should still trigger auto-refresh
etc

**Comment by totaam** [comment]
I really cannot reproduce this any more.
What's frustrating is that I really wanted to, so I:
* went back to the version from 3 weeks ago
* tweaked the list of encodings and the server code to trigger `h264` more easily
* ignored the `text` mapping
* used a 500ms link
* lowered the quality setting

And things looked better than I could have expected. When the screen updates did use `h264`, the lossless refresh fixed things shortly after.

**Comment by stdedos** [comment]
😕

I guess `xpra top` is fixed now. I'll start using this method of diagnosing again.
It's a bit sad that I have to have 2 things open right now to keep diagnosing my connection (`xpra top`, ping plotter)
