### ISSUE TITLE
xdg-open file is too large

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3090]
```console
$ xdg-open .rvm.txz
server returned error code 127
  file '/home/u/.rvm.txz' is too large: 198MB (limit is 100MB)
```

Okay so ... can you just let me run it server-side? 😛

**Comment by totaam** [comment]
> Okay so ... can you just let me run it server-side? stuck_out_tongue

Just use the "real" `xdg-open` instead of our wrapper:
```
/usr/bin/xdg-open .rvm.txz
```

**Comment by stdedos** [comment]
I know 😝 

But it took me a while to figure out how to find that path
