### ISSUE TITLE
JetBrains Toolbox is not showing up

### ISSUE THREAD

**Issue by mtthsbrr** [Xpra-org/xpra#3095]
I use the JetBrains Toolbox for installing and managing their IDEs. Sadly it does not show up when clicking "Start" -> "Programming" -> "JetBrains Toolbox". I tried it with a comparable tool to Xpra and there it's working fine.

Server:
`xpra v4.1.3 on Ubuntu Focal on WSL2 on Win 10 20H2`

Client:
`Xpra-Python3-x86_64_4.1.3-r1`

Client Start Command:
```shell
xpra start ssh://USERNAME@HOSTNAME/ --start-child=xterm
```

**Comment by totaam** [comment]
I downloaded the jetbrains toolbox from https://www.jetbrains.com/toolbox-app/download/download-thanks.html?platform=linux, untarred it and then I ran it from an xterm in the xpra session. It took a few seconds to show up, but here it is:
![jetbrains-toolbox](https://user-images.githubusercontent.com/1049737/115730991-f7174100-a3b0-11eb-8319-41084b3c142f.png)


Same versions you are using:
* Windows client is 4.1.3, nothing interesting in the `Xpra_cmd.exe` output.
* Ubuntu server is running 4.1.3-r1, again nothing in the logs.

Perhaps there's something different in your configuration. Have you tried disabling opengl in the client?
Anything of interest in the log file or client output?

**Comment by mtthsbrr** [comment]
Hi @totaam. Interesting...yes I can reproduce it working the way you described but when I install it following this guide https://www.jetbrains.com/help/idea/installation-guide.html#toolbox and then try to open it from the Xpra Start menu, the app does not seem to start. So I guess it has something to do with the config in the corresponding .desktop file in /usr/share/applications then?

![image](https://user-images.githubusercontent.com/49281986/115839892-645fbc00-a41b-11eb-9742-14bb5030a862.png)

**Comment by totaam** [comment]
> So I guess it has something to do with the config in the corresponding .desktop file in /usr/share/applications then?

Probably. Or it could be something in the environment it doesn't like (though that's unlikely).
Please take a look at your server log, it should show you what command it's using to run the toolbox, and it will also log a message when it terminates.

You can also try running commands manually in the server context (without having to restart your server every time), ie for `DISPLAY=:2` :
```shell
xpra control :2 start xterm
```

**Comment by mtthsbrr** [comment]
>Please take a look at your server log, it should show you what command it's using to run the toolbox, and it will also log a message when it terminates.

You were right - it shows an error:

`2021-04-29 08:45:08,581 started command '/home/m/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox' with pid 13103
open dir error: No such file or directory
2021-04-29 08:45:08,585 child 'JetBrains Toolbox' with pid 13103 has terminated`

The directory is definitely existing so it might be some permission issue when running it from a .desktop file? Any help would be appreciated. 🙏 
![image](https://user-images.githubusercontent.com/49281986/116513377-c7dd6400-a8c9-11eb-8bd1-3ae9b103cb7d.png)

**Comment by totaam** [comment]
> `open dir error: No such file or directory`

That's odd. Can you try starting an xterm from xpra then running that same command from the xterm:
```shell
ls -la /home/m/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
/home/m/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox
```
The error message should be the same as the one found in the server log.
Then you just have to figure out what it means.
My guess is that the `jetbrains-toolbox` is failing to open some directory.
You could `strace` the process to find out which one it is.

Apart from some small tweaks to the environment, there isn't anything that should cause an application to behave differently when running in an xpra session.

There is a difference if you start your sessions via the proxy server (`--start-via-proxy=yes`) as this enables systemd `ReadWritePaths=/run/xpra /tmp`, `ProtectSystem=strict` and `ProtectControlGroups=true` - and this severely restricts what applications are allowed to do.
But I assume that this is not the case here - correct me if I'm wrong.

**Comment by stdedos** [comment]
FYI, to start the toolbox "properly", it was necessary to do
`$ (cd ~/.config/autostart && GIT_OPTIONAL_LOCKS=0 DISPLAY="${DISPLAY}" gtk-launch jetbrains-toolbox)`

I don't know how up-to-date this behavior/method is used; however, when I needed to inject `GIT_OPTIONAL_LOCKS=0` (on descendants), it was necessary to execute it like that, and not "just" as `/home/m/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox`.

Also; jetbrains-toolbox does some dumb `fuse.jetbrains-toolbox` mounting on `/tmp/.mount_jetbraXXXXXXX`, whose reason/necessity/"ability-to-happen" I don't know.

**Comment by totaam** [comment]
Works-for-me.
