### ISSUE TITLE
Debian package build fails in Ubuntu Hirsute container on Ubuntu Hirsute ARM64 host

### ISSUE THREAD

**Issue by nikitalita** [Xpra-org/xpra#3097]
Log: [xpra-log1.log](https://github.com/Xpra-org/xpra/files/6375777/xpra-log1.log)

Most relevant bits:
```
Traceback (most recent call last):
  File "/src/xpra-4.2/setup.py", line 2109, in <module>
    assert nvcc_versions, "cannot find nvcc compiler!"
AssertionError: cannot find nvcc compiler!
make[1]: *** [debian/rules:21: override_dh_auto_build] Error 1
make[1]: Leaving directory '/src/xpra-4.2'
make: *** [debian/rules:15: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
ls: cannot access '../xpra*deb': No such file or directory
mv: cannot stat '../xpra*deb': No such file or directory
mv: cannot stat '../xpra*changes': No such file or directory
/src
ls: cannot access 'pkgs/xpra-html5-*': No such file or directory
b30871d5db3ef3ac1b572390a38ade674a104139aec608f5366efe0a44d60351
```

Putting `apt-get install nvidia-cuda-toolkit libffmpeg-nvenc-dev -y` in the `build-deps.sh` script right after `apt-get dist-upgrade -y` fixes this, but pulls in a large number of dependencies. I'm not sure what the minimal install packages would be.

**Comment by totaam** [comment]
> .. in the `build-deps.sh` script...

I assume that you mean `build_debs.sh`?

Do you really have nvenc and nvjpeg enabled on ARM? Does that even work?

If so, then yes, I am afraid that you will need to download all the extra stuff.
If not, then we need to remove this line from the setup script on ARM:
```shell
buildah copy $IMAGE_NAME "./nvenc-deb.pc" "/usr/lib/pkgconfig/nvenc.pc"
```
Then the xpra build scripts won't try to build `nvenc`.
`nvjpeg` (#2984) should not be enabled by default unless you've installed the `nvjpeg` pkgconfig file somehow.

**Comment by nikitalita** [comment]
I don't know if it works or not; I had assumed that maybe tegra boards would support that? I don't know, I just ran the commands to set up the container and that's how it set it up.

**Comment by totaam** [comment]
We now only enable `nvenc` and `nvjpeg` on `x86_64` arch.
You may want to remove the `nvenc.pc` and `cuda.pc` from your images - or regenerate them.

It is still possible to enable them by setting the environment variable `NVIDIA_CODECS=1` when running the `setup_build_containers.sh` script.

**Comment by nikitalita** [comment]
Doing some further research, it does appear that Tegra boards have support for NVENC, although current support is apparently preliminary: https://lwn.net/Articles/846135/
