### ISSUE TITLE
Xpra, Xfce and weird theme, icons

### ISSUE THREAD

**Issue by kden416** [Xpra-org/xpra#3102]
When i start tigervnc server, i get normal xfce session, but when:

> xpra start-desktop --start=startxfce4

i get this weird desktop:
![2021-04-29_19-27](https://user-images.githubusercontent.com/1554073/116585378-005c5c80-a921-11eb-84a5-c2b8b7a2b8d4.png)

this is with VNC (normal desktop):
![2021-04-29_19-30](https://user-images.githubusercontent.com/1554073/116585810-6d6ff200-a921-11eb-992b-71402f5ee146.png)

if i start
> xpra shadow

for VNC session, desktop looks fine, like in VNC viewer

**Comment by totaam** [comment]
My guess is that some environment variables differ, causing xfce to use a different theme / settings.
You should be able to figure out which one by using `--start=xterm` and starting `startxfce4` from there repeatedly after tweaking the environment until you find the variable that affects the way it looks.
You could also ask the xfce developers.

Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
In particular: what distro, xpra version, DPI settings, etc.

**Comment by totaam** [comment]
> remote server xpra version 3.0.9 and ubuntu 20.10

That's well out of date.

**Comment by totaam** [comment]
>>> remote server xpra version 3.0.9 and ubuntu 20.10

>> That's well out of date.

> behavior same.

What does that mean?
Same as what?
Are you using the official xpra packages?
Like I said before, please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

> xpra do something wrong when starts session

Very unlikely.
Like I said in the very first comment, you should compare the environment until you find the difference.

Another way to verify if it really is xpra that is changing something is to start xfce on a display that has never even seen an xpra server:
* start a vfb: `Xvfb :100`
* start xfce on that vfb: `DISPLAY=:100 startxfce4`
* take a screenshot of this vfb (ie: `DISPLAY=:100 scrot`), or start an xpra server against it: `xpra start :100 --attach=yes`

**Comment by kden416** [comment]
> > > > remote server xpra version 3.0.9 and ubuntu 20.10
> 
> > > That's well out of date.
> 
> > behavior same.
> 
> What does that mean?
> Same as what?
> Are you using the official xpra packages?
> Like I said before, please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

ubuntu server version and manjaro laptop version different, but behavior same

> > xpra do something wrong when starts session
> 
> Very unlikely.
> Like I said in the very first comment, you should compare the environment until you find the difference.
> 
> Another way to verify if it really is xpra that is changing something is to start xfce on a display that has never even seen an xpra server:
> 
>     * start a vfb: `Xvfb :100`
> 
>     * start xfce on that vfb: `DISPLAY=:100 startxfce4`
> 
>     * take a screenshot of this vfb (ie: `DISPLAY=:100 scrot`), or start an xpra server against it: `xpra start :100 --attach=yes`

Screenshot by scrot, desktop looks like in VNC
![2021-04-30-235354_1280x1024_scrot](https://user-images.githubusercontent.com/1554073/116758023-f79a8200-aa17-11eb-9614-44b5c9d949a9.png)

how i said, error occurs not only with Xfce4 session , but gnome-session on another PC can't change themes of shell, apps and icons too. (within xpra)

**Comment by totaam** [comment]
> Screenshot by scrot, desktop looks like in VNC

Then try running xpra with `--xsettings=no`.
My guess is that your client OS has this theme set through xsettings and xpra is synchronizing it with the server.

**Comment by kden416** [comment]
It  works! Thank you for your help.
