### ISSUE TITLE
centos 7 build?

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3103]
wondering if there's any hope for official current (release or beta) builds for centos 7, since c7 will be with us for a long time to come (EOL In 2024).

i cloned the repo and attempted a straightforward build. there is no python3-opengl in c7, rather there is still PyOpenGL which is python2, so no OpenGL support in xpra. not a problem to me personally, i use VirtualGL heavily, typically starting my xpra world with "--start-child='vglrun mate-terminal'".

bigger problem was that FORMAT_RGB30 seems to be unsupported (import failure). the attached diff is what it took to shave this option out of existence and force 24 as default. naturally, i don't expect this patch to be applied, it's simply demonstrative of what it took for me in c7 to get what i wanted.

last glitch is that the session info fails to display graphs, dropping a stack trace that complains:
AttributeError: module 'cairo' has no attribute 'Format'
not familiar with that, but not a deep concern to me.

anyhow, just hoping. i've got it running ok now, i'd just prefer to have *.rpm.

[centos7.diff.gz](https://github.com/Xpra-org/xpra/files/6401379/centos7.diff.gz)

**Comment by totaam** [comment]
Please see:
https://github.com/Xpra-org/xpra/wiki/Platforms

Packages for CentOS 7 are available in the [repository](https://github.com/Xpra-org/xpra/wiki/Download#-linux). Those are built from the 3.x branch which is the last branch supporting python 2.x
