### ISSUE TITLE
xpra-html5 application menu empty (Debian10)

### ISSUE THREAD

**Issue by olifre** [Xpra-org/xpra#3108]
This is probably a user error, but since I am out of ideas, I'm reporting here:
Connecting to a running xpra 4.1.2 server with an 4.1.2 client, the epplication menu is completely empty. 

Trying the helper directly shows:
```
$ python3  /usr/lib/python3/dist-packages/xpra/platform/xposix/xdg_helper.py
2021-05-03 23:26:24,014 loaded 6 start menu entries from 1 sub-menus in 0.5 seconds
* Applications
  - Comment                       : 
  - Entries
  - GenericName                   : 
  - Icon                          : debian-applications
  - Name                          : Applications
  - Path                          : Applications
```
This is a rather minimal Debian 10 container, with `xpra`, some editors, an `xterm` and other basic needs installed. 
I also added `menu-xdg` and `hicolor-icon-theme` but to no avail. 

I can confirm `/var/lib/menu-xdg` appears to be filled:
```
...
/var/lib/menu-xdg/desktop-directories/menu-xdg/debian-applications-shells.directory
/var/lib/menu-xdg/desktop-directories/menu-xdg/debian-applications-system-hardware.directory
/var/lib/menu-xdg/desktop-directories/menu-xdg/debian-applications-programming.directory
/var/lib/menu-xdg/menus
/var/lib/menu-xdg/menus/debian-menu.menu
/var/lib/menu-xdg/applications
/var/lib/menu-xdg/applications/menu-xdg
/var/lib/menu-xdg/applications/menu-xdg/X-Debian-Applications-Science-Mathematics-bc.desktop
/var/lib/menu-xdg/applications/menu-xdg/X-Debian-Applications-System-Monitoring-top.desktop
...
```

Am I missing a package / preparatory step to make the application menu work? 
Also. please feel free to redirect me to the `pyxdg` developers if this turns out to be an issue there.

**Comment by totaam** [comment]
Try the loader class from 8d42d28c9578f3f1a38eed4bf66ed71e5282ab29 which adds extra debug logging:
```shell
XPRA_XDG_LOAD_GLOB=0 XPRA_ALL_DEBUG=1 python3 ./xpra/platform/xposix/xdg_helper.py 
```
It's possible that the sub-menu is not visible, or perhaps the entries are not in a sub-menu.

**Comment by olifre** [comment]
Thanks for adding this debugging! 
It looks rather "empty":
```
$ XPRA_XDG_LOAD_GLOB=0 XPRA_ALL_DEBUG=1 python3 ./xpra/platform/xposix/xdg_helper.py
2021-05-04 10:14:54,883 parsing xdg menu data for prefix None
2021-05-04 10:14:54,901 parsing xdg menu data for prefix None
2021-05-04 10:14:54,916 Debian.getEntries()=(<xdg.Menu.Menu object at 0x2b72e7980470>,)
2021-05-04 10:14:54,916 Name=Applications (<class 'str'>)
2021-05-04 10:14:54,916 GenericName= (<class 'str'>)
2021-05-04 10:14:54,916 Comment= (<class 'str'>)
2021-05-04 10:14:54,916 Path=Applications (<class 'str'>)
2021-05-04 10:14:54,916 Icon=debian-applications (<class 'str'>)
2021-05-04 10:14:54,916 properties(Applications)={'Name': 'Applications', 'GenericName': '', 'Comment': '', 'Path': 'Applications', 'Icon': 'debian-applications'}
2021-05-04 10:14:55,021 loaded 6 start menu entries from 1 sub-menus in 0.1 seconds

application menu:
* Applications
  - Comment                       : 
  - Entries
  - GenericName                   : 
  - Icon                          : debian-applications
  - Name                          : Applications
  - Path                          : Applications
no session menu data found
```

Checking manually, I see some menu objects:
```
$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from xdg.Menu import parse, Menu
>>> print(list(tuple(parse().getEntries())[0].getEntries()))
[<xdg.Menu.Menu object at 0x2b80b7d34f28>, <xdg.Menu.Menu object at 0x2b80b7d34f60>, <xdg.Menu.Menu object at 0x2b80b7d34fd0>, <xdg.Menu.Menu object at 0x2b80b7d4a0b8>, <xdg.Menu.Menu object at 0x2b80b7d4a160>, <xdg.Menu.Menu object at 0x2b80b7d4a208>]
```

**Comment by totaam** [comment]
Please re-open if you have more details using the latest code.
My guess is that the first menu we find has very little in it.
The env vars that matter here are `XDG_CONFIG_DIRS` and `XDG_MENU_PREFIX`. Both are tweaked by the loader script to try to find valid menu data.

**Comment by olifre** [comment]
@totaam It sadly still looks mostly the same with most recent code:
```
XPRA_XDG_LOAD_GLOB=0 XPRA_ALL_DEBUG=1 python3 ./xpra/platform/xposix/xdg_helper.py 
2021-05-17 19:47:52,357 parsing xdg menu data for prefix None with XDG_CONFIG_DIRS=None
2021-05-17 19:47:52,361 Debian.getEntries()=(<xdg.Menu.Menu object at 0x7ff0116af048>,)
2021-05-17 19:47:52,361 Name=Applications (<class 'str'>)
2021-05-17 19:47:52,361 GenericName= (<class 'str'>)
2021-05-17 19:47:52,361 Comment= (<class 'str'>)
2021-05-17 19:47:52,361 Path=Applications (<class 'str'>)
2021-05-17 19:47:52,361 Icon=debian-applications (<class 'str'>)
2021-05-17 19:47:52,361 properties(Applications)={'Name': 'Applications', 'GenericName': '', 'Comment': '', 'Path': 'Applications', 'Icon': 'debian-applications'}
2021-05-17 19:47:52,385 loaded 6 start menu entries from 1 sub-menus in 0.0 seconds

application menu:
* Applications
  - Comment                       : 
  - Entries
  - GenericName                   : 
  - Icon                          : debian-applications
  - Name                          : Applications
  - Path                          : Applications
no session menu data found
```
i.e. the only obvious difference is that the debug output now shows that `XDG_CONFIG_DIRS` is unset. 

Trying `XDG_CONFIG_DIRS=/etc/xdg` does not change this. Trying to manually go through the files, I find:
`/etc/xdg/menus/debian-menu.menu`
which contains directories, e.g.:
```<Menu>
<AppDir>/var/lib/menu-xdg/applications</AppDir>
<DirectoryDir>/var/lib/menu-xdg/desktop-directories/menu-xdg</DirectoryDir>
<Name>Debian</Name>
<Directory>debian.directory</Directory>
<Include>
<Category>X-Debian</Category>
</Include>
<Menu>
<Name>Applications</Name>
<Directory>debian-applications.directory</Directory>
<Include>
<Category>X-Debian-Applications</Category>
</Include>
...
```
Checking further, I find:
`/var/lib/menu-xdg/desktop-directories/menu-xdg/debian-applications.directory`
which contains:
```
[Desktop Entry]
Type=Directory
Encoding=UTF-8
Name=Applications
```
and then the related actual `.desktop` files in  `/var/lib/menu-xdg/applications/menu-xdg/`:
```
...
X-Debian-Applications-Programming-tclsh8.6.desktop
X-Debian-Applications-Science-Mathematics-bc.desktop
X-Debian-Applications-Shells-bash.desktop
...
```

I would expect these to be found according to the `<DirectoryDir>` tag in `/etc/xdg/menus/debian-menu.menu`. 
I'm sure I'm missing something, but I don't see it...

**Comment by iDmple** [comment]
Following because I have this issue as well.

**Comment by totaam** [comment]
Perhaps the solution here will help: https://github.com/Xpra-org/xpra/issues/3083#issuecomment-849318431

**Comment by olifre** [comment]
I tried with `--source=/etc/profile` and it did not change things for me. The file `/etc/profile.d/apps-bin-path.sh` mentioned in the other report is exclusively present on systems using `snapd`. Menus from apackages installed by `apt` or `dpkg` should be unrelated (and on Debian or most other non-Ubuntu distributions, `snapd` does not exist).

**Comment by totaam** [comment]
@olifre can you share a `DockerFile` I can use for testing?

**Comment by olifre** [comment]
@totaam I did use a different container runtime in my tests, but I could also create a `DockerFile` — however, the only things I did upon `debian:10` pulled straight from DockerHub were:
```
apt-get update
apt-get -y dist-upgrade
wget -q https://xpra.org/gpg.asc -O- | apt-key add - 
wget -q https://xpra.org/repos/buster/xpra.list -O /etc/apt/sources.list.d/xpra.list
apt-get update
apt-get -y install      xpra \
                        xpra-html5 \
                        websockify \
                        menu-xdg \
                        hicolor-icon-theme
```
So that is essentially the `DockerFile` when using Debian 10 as base. Does these list of commands also work for you?

**Comment by totaam** [comment]
FYI: `websockify` has not been needed for a very long time: #2121

To be able to install xpra:
```
apt-get install -y wget gnupg2
```

So, I'm using [buildah](https://buildah.io/).
I can reproduce the problem now. Let me play with it.

**Comment by olifre** [comment]
> FYI: `websockify` has not been needed for a very long time: #2121

Thanks!


> To be able to install xpra: [...]

Indeed, sorry — I think I installed these manually in a writable overlay on top of the container, so I forgot them :-(. 

>  I can reproduce the problem now. Let me play with it.

Thanks! :+1:

**Comment by totaam** [comment]
Damn. So this is using a single top level `Applications` menu with many submenus and it goes deep:
```
# python3 -c "from xdg.Menu import parse;submenus=parse().Entries[0].Submenus;print(submenus[2].Entries[0].Entries)"
[menu-xdg-X-Debian-Applications-System-Administration-editres.desktop, menu-xdg-X-Debian-Applications-System-Administration-xfontsel.desktop, menu-xdg-X-Debian-Applications-System-Administration-xkill.desktop]
```
This doesn't play well at all with how we normally export the menus.  
So the fix above is **quite ugly** but it seems to work for me.  
It works by raising the sub-menus if there's only a single top-level menu and flattening any deeper sub-menus.


The menu loader has gained some new knobs you can play with:
* `XPRA_XDG_EXPORT_TERMINAL_APPLICATIONS=0` because we don't want to expose applications that require a terminal to run as the client doesn't know how to deal with that (yet? meh)
* `XPRA_XDG_EXPORT_SELF=0` because we don't want to show xpra in the menus we export: running xpra nested is usually a bad idea and minimal installations don't want to show those menu entries
* `XPRA_MENU_LOAD_APPLICATIONS=`sys.prefix`/share/applications` to load

@olifre please close if this works for you.
