### ISSUE TITLE
Area graying out when moving the cursor over it

### ISSUE THREAD

**Issue by Giraut** [Xpra-org/xpra#3114]
ello,

EDIT: I should have dug a bit deeper before opening this. `--input-method=ibus `cures it, as per https://github.com/Xpra-org/xpra/issues/2900

I'm trying to use a tool called [SoftConsole](https://www.microsemi.com/product-directory/design-tools/4879-softconsole), which is an Eclipse development IDE, over Xpra. It works, but the code pane keeps graying out when I move the cursor over it: it grays out for an instant and then displays correctly again when I stop moving the cursor, or it can stay grayed out for several seconds.

I have a feeling it's because the tool tries to draw floating popups over the code (that shows variable, function declarations and such) and does it in a dumb way - maybe redrawing the entire pane constantly all the time even when there's no popup to show or something like that.

![softconsole_over_xpra-display_ok_cursor_not_moving](https://user-images.githubusercontent.com/37288252/117527717-b9ccc900-afd6-11eb-9582-6d1f91eca605.png)
![softconsole_over_xpra-display_grayed_out_after_cursor_move1](https://user-images.githubusercontent.com/37288252/117527715-b8030580-afd6-11eb-9996-260c12c64b40.png)
![softconsole_over_xpra-display_grayed_out_after_cursor_move2](https://user-images.githubusercontent.com/37288252/117527716-b9343280-afd6-11eb-8537-418ac3f78a2f.png)

Anything I can try to work around this issue? I've played around with just about all the server, X11 and GL options I can think of but it's not improving it.

I'm using Xpra v4.1.3

By the way, great work on Xpra. I've seen this project around for years, but for some reason only got around to trying it now. It's great! The default documentation blurb that describes the basic xterm example really sells it short.

**Comment by totaam** [comment]
> `--input-method=ibus` cures it

The plan was to try to switch to ibus by default for 4.2: #2359
But it's too late now so it isn't going to happen. Maybe the following release.

> The default documentation blurb that describes the basic xterm example really sells it short

I would love to improve it, but I'm not sure how to do this without scaring away newbie users. Feel free to suggest anything.
