### ISSUE TITLE
Suggestion: timeout before closing the server with exit-with-children=yes

### ISSUE THREAD

**Issue by Giraut** [Xpra-org/xpra#3115]
When the exit-with-children parameter is set to yet, the server quits after the last client quits. I suggest a timeout parameter to wait for a few seconds before terminating the server.

The rationale is this: some utilities insist on displaying a splash screen. The splash screen appears, then it disappears, then the main UI opens. With exit-with-children=yes, the Xpra server terminates when the splash screen disappears.

Of course, it's always possible to run an xterm or some other X client on the side to keep the server running for the short time between the moment the splash screen disappears and the moment the main UI appears, but a grace period before terminating the server would be more elegant.

**Comment by totaam** [comment]
> .. a grace period before terminating the server would be more elegant

This will not help.
If the process has terminated then the server will exit anyway, delaying that by a few seconds won't make a difference.
Xpra does not track process groups only the process you launch.
