### ISSUE TITLE
support session descriptors

### ISSUE THREAD

**Issue by brainchild0** [Xpra-org/xpra#3117]
Currently, invocation of  Xpra can be tedious, even for a seasoned user of   command-line  applications. Notably, specifications from among a large set of options must be entered through the command invocation, leaving custom scripts the only means of automation. 

Proposed is adoption of some method of defining session descriptors, one per file, that can be referenced instead of the list of switches needed to resolve the options set.

Such an enhancement would also facilitate integration with a graphical session launcher and manager, which would be a useful enhancement to the overall system.

**Comment by totaam** [comment]
You can already specify your options in `.xpra` session files, is that not enough?

There is already a graphical session launcher, try the new one from 4.2 (beta channel).

**Comment by brainchild0** [comment]
I am sorry, I did not notice these topics in the documentation. Would you mind pointing to the location where they are discussed?

**Comment by totaam** [comment]
> Would you mind pointing to the location where they are discussed?

They're not in the documentation IIRC - and maybe we should fix that. (the man page for `xpra_launcher` is missing)
To get started easily, just run `xpra_launcher` and save your session file from there.

**Comment by brainchild0** [comment]
Do I understand that the launcher is currently a hidden feature under development?

There are a  variety of use cases for administrating a thin client, and supporting this range through  the launcher would be useful to anyone seeking to build any of these kinds of deployments.



Support for session files (`.xpra`) is definitely helpful, as would be documentation. It seems that a further objective might be integration of   sessions and the launcher, for example, support for building session definitions graphically.

For reference, at the moment, I am unable to connect to my server using the launcher. Due to apparent incompatibilities in OpenSSH and the Python 3 client, I am able  to open a Xpra session only by forcing the client to use the system `ssh` executable (OpenSSH), and  I have not found this behavior supported in the launcher.

**Comment by totaam** [comment]
> Do I understand that the launcher is currently a hidden feature under development?

The launcher is not hidden, just very badly documented.
The code was written back in 2009, and it shows.

> .. support for building session definitions graphically.

This is planned, by re-using the same GUI elements added for the new `xpra start-gui` subcommand: #3119

> Due to apparent incompatibilities in OpenSSH and the Python 3 client

Please create a ticket for this.

> and I have not found this behavior supported in the launcher

Do you mean that you can't set the `ssh` option using the launcher configuration files?

**Comment by brainchild0** [comment]
> Do you mean that you can't set the `ssh` option using the launcher configuration files?

I can't set it in the graphical launcher. I haven't tried configuration files, because I don't know how to write one.

**Comment by totaam** [comment]
> I haven't tried configuration files, because I don't know how to write one.

You can just save one from the launcher and edit it.
The key-values are exactly the same as xpra's configuration file (`/etc/xpra/conf.d`) and those are exactly the same as the command line options (`man xpra`) - minus the `--` prefix.

FYI: it will be improved in #3119

**Comment by brainchild0** [comment]
Overall, the relationship among the various system components is extremely difficult for a new user to ascertain  based on  available documentation. I would recommend outlining the structure and design of the entire system in user documentation, unless such documentation is available already that I simply failed to discover.
