### ISSUE TITLE
xpra bloats latency

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3121]
![d3tr_2021-05-10_12-10-03](https://user-images.githubusercontent.com/133706/117636396-6cdd2400-b189-11eb-8616-cd41eccde49e.png)

Legend goes:
- thick red: average
- thin read: min/max
- medium blue: average +/- std. dev.

Magical piece of software: https://www.majorgeeks.com/files/details/3d_traceroute.html

htop load avg: 0./0./0.

**Comment by totaam** [comment]
What's the z-axis? Time?
It looks like the bandwidth got maxed out?
12 seconds to reply to ping packets at one point! (both ways)

If the 3d-traceroute graph corresponds to the same timeframe then it never saw a latency anywhere as high as that?
`ping` packets are queued with every other packet, so it is possible that a much bigger screen update is just hogging all the bandwidth.
(the `ping`s are at the application level, not network level)

I guess you could see in what order they're coming in with `XPRA_LOG_PACKET_TYPE=1`.

**Comment by stdedos** [comment]
> What's the z-axis? Time?

Yes. However, the 3d graph keeps limited samples; the most complete log is in the 2d subgraphs.

> It looks like the bandwidth got maxed out?

Where do you see that?

> If the 3d-traceroute graph corresponds to the same timeframe then it never saw a latency anywhere as high as that?

Longer time; server is one of the `xpra upgrade/recover` servers - the app is running as soon as I got it.

> I guess you could see in what order they're coming in with `XPRA_LOG_PACKET_TYPE=1`.

I'll try ... Server or client? Am I going to be chocked on output? 😛

**Comment by totaam** [comment]
> Where do you see that?

When the latency goes to 12 seconds, the primary suspect would be lack of bandwidth.

> I'll try ... Server or client?

Both preferably.
Then you can see if the ping packets are getting backed up by something else.

> Am I going to be chocked on output?

Every packet received will be logged, but only the packet type, so just one line of text.

**Comment by stdedos** [comment]
> If the 3d-traceroute graph corresponds to the same timeframe then it never saw a latency anywhere as high as that?
> `ping` packets are queued with every other packet, so it is possible that a much bigger screen update is just hogging all the bandwidth.
> (the `ping`s are at the application level, not network level)

While it makes sense for your protocol (I guess), that is seriously distorting the reality of what "ping" means.
I guess someone could've thought about that; however, it took me ~2 years before I realized that - by finding a program that can do what needs to be done in this case.

Would you consider comparable functionality? Ping packets that do not adhere to the packet queue? (And/or parsing
network-level pings?)

**Comment by totaam** [comment]
> While it makes sense for your protocol (I guess), that is seriously distorting the reality of what "ping" means.

I disagree. It is a ping that works at the application layer rather than pure IP / ICMP layer.

> Would you consider comparable functionality? Ping packets that do not adhere to the packet queue?

That would be nearly impossible to implement. There is no framing for TCP chunks and if there's a 32MB packet being sent then the ping will have to wait its turn.

> (And/or parsing network-level pings?)

That would require special privileges.

**Comment by stdedos** [comment]
"Just" running a pure ICMP-ping and printing the metric side-by-side the Application-level ping would require special privileges? 😕 

Did I fail to communicate something? and/or Did I fail to understand the complexity?

**Comment by totaam** [comment]
[python non-privileged ICMP](https://stackoverflow.com/questions/1189389/python-non-privileged-icmp): _The ping program is installed setuid root. This allows any user to use the program, and still be able to open a raw socket_

**Comment by stdedos** [comment]
Oh fun

> The ping program is installed setuid root. This allows any user to use the program, and still be able to open a raw socket.
>
> After it opens the raw socket, it typically drops root privs.

I've been doing it so many years, **not realising** that ping has setuid root set 😂😂😂😂😂😂

**Comment by open-trade** [comment]
try out https://github.com/rustdesk/rustdesk, it is a new open-source remote desktop software

**Comment by totaam** [comment]
I think it is best to close this one and follow up in https://github.com/Xpra-org/xpra/issues/3167#issuecomment-877138717 - my guess is that a hardware encoder is stalling, which is causing this application latency.
