### ISSUE TITLE
maximized windows do not like being click-drag-moved to a new monitor

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3122]
C: Win10 / S:Focal

Repro with:

- 2 monitors
- Maximize X on one monitor
- Click-drag-move from the title bar to the top of the other monitor (in Windows that will maximize the window on the monitor that the title bar was "pushed" to the top)

Expected:
Window is moved to the other monitor and remains maximized

Actual:
Window remains on the original monitor

**Comment by totaam** [comment]
Well, that was a waste of time: every single test window from the `xpra toolbox` has the same behaviour.
So this is a GTK bug and seeing how little they care about MS Windows support, not one that is likely to be fixed anytime soon.

(so I am closing this ticket)

**Comment by stdedos** [comment]
Can you at least link the things you found for the sake of completeness? 😕
Sad to know that I cannot do something to pressure them.

What's the expected workflow then, in light of these events?
Un-maximize, move to adjacent monitor, maximize?
