### ISSUE TITLE
undecorate window causes a pointer offset on win10

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3128]
1. Takes too much time to load for "such a basic window" (>1sec)
2. "decorate" broken:
	1. press "undecorate", then
	4. press "decorate", then
	5. press "decorate" again

😀

**Comment by totaam** [comment]
> Takes too much time to load for "such a basic window" (>1sec)

It's probably loading the X11 bindings or something. It's a test tool.

> "decorate" broken:...

On what client OS? Natively or via xpra?
What am expecting to see or not see?

**Comment by stdedos** [comment]
Natively, xpra on win10.

"undecorate" removes the decorations, "decorate" jiggles it up/left (theoretically it re-decorated it and the window was moved to the original x,y I guess), "decorate" again makes the window full-screen

**Comment by totaam** [comment]
This is a GTK bug.

**Comment by stdedos** [comment]
😂😂😂😂😂😂 Damn.

Which bug?

**Comment by totaam** [comment]
> Which bug?

No idea. But this toolbox example you are running is plain GTK, there is no xpra code in it.
```python
    def decorate():
        window.set_decorated(True)
    def undecorate():
        window.set_decorated(False)
    add_buttons("decorate", decorate, "undecorate", undecorate)
```

**Comment by stdedos** [comment]
Aaah, so that's how you came to the conclusion that it's a GTK bug 😅
