### ISSUE TITLE
Sessions are not being resumed / re-connected

### ISSUE THREAD

**Issue by lm-sig** [Xpra-org/xpra#3130]
In the past (Xpra 3.x, 4.0.x) I could disconnect from a Xpra session in the HTML5 client and then re-connect to the same session.

Testing 4.1.2 I can no longer reconnect to an existing session. The session is still running (ps shows Xorg running, apps running) when I disconnect. A new Xorg, etc. are started when I try to reconnect.

The HTML5 client does have the "Re-connect automatically to the session" checkbox checked.

Xpra 4.1.2 from the xpra.org official repository:
xpra-4.1.2-10.r78.el8.x86_64
xpra-html5-4.1.2-1.noarch

Server OS: RHEL 8.4
Client Browser: Firefox 78.10.0esr

**Comment by totaam** [comment]
I get a constant stream of SELinux errors which makes it very hard to debug anything, even with `setenforce 0`.

At least with the latest 4.2 beta builds, the proxy does work if you run it by hand:
```
xpra proxy --bind-tcp=0.0.0.0:10000,auth=sys --no-daemon
```
So the problem is elsewhere.

**Comment by basilgello** [comment]
I faced the same problem but my commits fixing this and other issues will be tagged soon. Check master branch and PR section for the relevant technical information.﻿

**Comment by lm-sig** [comment]
Will the @basilgello fixes make it into the 4.2 branch? Will we see a new 4.2+ release soon?

**Comment by basilgello** [comment]
@totaam :)

**Comment by totaam** [comment]
I believe the fixes you are referring to are in all the supported branches, which have all had releases (stable for 3.0 and 3.1, and beta for master) except for 4.2
I was going to release 4.2.1 earlier this week but then I fell ill. Should happen in the next few days instead.

**Comment by basilgello** [comment]
> then I fell ill

Stay safe & get well soon! :)
