### ISSUE TITLE
Can't enforce SSL

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3141]
Hi,

I successfully activated ssl with
`xpra start :80 --bind-tcp=0.0.0.0:8080 --html=on --no-daemon --start="xhost +" --ssl-cert=/etc/xpra/ssl-cert.pem`

but I don't manage to enforce SSL, the connections that don't use it are still allowed.

I've tried variations with `--ssl` modes and replacing `--bind-tcp` by `--bind-ssl` without success. Most of the time I get this error:
`ERR_INVALID_HTTP_RESPONSE` on the browser.

Can you please let me how to proceed?

Thanks!

**Comment by totaam** [comment]
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs.

At the very least:
* versions
* URL used
* browser
* OS
> `--start="xhost +"`

Why is that present?

**Comment by iDmple** [comment]
Sorry about that.

Versions:
- xpra                  4.2-r0-1   
- xpra-html5       4.2-r1-1 
Browser:
- Chrome Version 90.0.4430.93 (Official Build) (x86_64)
OS:
- Host: Ubuntu 20.04
- Client: Mac OS 10.15.7 
URL:
- I'm not sure what you mean.

Regarding xhost, I need this to be able to connect clients from other hosts on DISPLAY :80.

Thanks for your help regarding this issue.

**Comment by totaam** [comment]
Bad news is that this is a bug, now fixed.

Good news is that there are workaounds you can use right away:
* `--bind-wss=0.0.0.0:8080` - the downside is that you won't be able to connect with a regular xpra client in `ssl` mode, only in `wss` mode
* `--bind-ssl=0.0.0.0:8080,wss=auto` (or even `wss=yes` but then you might as well use `--bind-wss`)

**Comment by iDmple** [comment]
Okay, this works perfectly! Thank you, you're awesome!

Is there actually a way to prevent regular clients from connecting and only allow the browser?

**Comment by totaam** [comment]
> Is there actually a way to prevent regular clients from connecting and only allow the browser?

No. The html5 client and the regular clients use the same protocol.
As far as the server is concerned they are (almost) indistinguishable - at least a the protocol layer.

**Comment by iDmple** [comment]
Ok thanks for your answer!
