### ISSUE TITLE
Wrong index used

### ISSUE THREAD

**Issue by XmiliaH** [Xpra-org/xpra#3147]
It seems to me that the wrong index is used in https://github.com/Xpra-org/xpra/blob/c3d5ed33dd789287c5f0599aca389c3ae01ba294/xpra/client/mixins/window_manager.py#L1056-L1057 The index 4 already contains the width and it seems that it should be index 6 instead. As is used when the packet is generated at https://github.com/Xpra-org/xpra/blob/1c9ab018abcae952b677bd000e7cd77b0824362e/xpra/server/source/windows_mixin.py#L450

**Comment by totaam** [comment]
Looks like you're right.
I think the code was cut&pasted from `_process_window_resized`.
