### ISSUE TITLE
Xpra crashes at server start

### ISSUE THREAD

**Issue by andymcraae1** [Xpra-org/xpra#3151]
Hi I have xpra installed on Ubuntu 2004 and it crashes randomly when I start the server. Is it a know issue?

**Comment by totaam** [comment]
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
Not heard back so it is impossible to fix.
My guess is that the user was running 4.2 and hit the vaapi problems: fb52a4b8e58eaa27df509e2286d16efcd0d93ae6

**Comment by andymcraae1** [comment]
Hello. Actually I answered back that everything was fixed. But I lost my hotspot connection and the mesage wasn't sent. Its fixed. The reason is that I needed to upgrade the xpra package. Thanks
