### ISSUE TITLE
Clicking Load button on Xpra Session Browser results in consistent crash

### ISSUE THREAD

**Issue by cr1901** [Xpra-org/xpra#3154]
## How To Reproduce (for me)
1. Shut down computer running Windows 10.
2. Upgrade RAM from 8GB to 16GB. _I have no idea if this is relevant, but I'm including all the context I can think of._ This only started after the RAM upgrade.
3. Turn on computer running Windows 10.
4. Log in to Windows 10 user account.
5. Press Win+Tab, create a New Desktop if one doesn't exist already.
6. Press Win+Ctrl+Right arrow to switch to new desktop.
7. Open Xpra (Xpra.exe).
8. Click Connect button. This opens Xpra Session Browser (Xpra_Browser.exe).
9. Click Load. Xpra_Browser will hard hang, requiring me to manually kill it.
10. From here on out, clicking Load will consistently crash Xpra. This persisted from upgrading from 4.06 to 4.2, including after restarting my computer again. The image below demonstrates:
     ![image](https://user-images.githubusercontent.com/6418027/120878263-324c8880-c589-11eb-82c5-b1bf401e30a7.png)

## Other Info
1. Xpra version info:
    ![image](https://user-images.githubusercontent.com/6418027/120878252-206ae580-c589-11eb-97c8-65b965f6f6bb.png)
2. Creating a shortcut and clicking it will correctly populate Session Browser and let me start an Xpra session.
    ![image](https://user-images.githubusercontent.com/6418027/120878239-09c48e80-c589-11eb-965a-9d73eea6eb33.png)

**Comment by totaam** [comment]
I have followed these reproduction steps (except for 1-3) and I don't see any problems:
![load-on-desktop2](https://user-images.githubusercontent.com/1049737/120878510-2b546300-c5e7-11eb-80d4-ebdbe5368aeb.png)

**Comment by cr1901** [comment]
So Xpra Session Browser doesn't like something about _my_ particular system. But I can't think of anything that's changed. Is there a debug build or logs I can make Xpra Session Browser dump to help diagnose, or am I gonna have to build from source?

If the latter, this could be a few days...

**Comment by totaam** [comment]
> Is there a debug build or logs I can make Xpra Session Browser dump

```shell
Xpra_cmd.exe -d all launcher
```

**Comment by cr1901** [comment]
Naturally, I can't reproduce this anymore, starting with running `Xpra_cmd.exe -d all launcher` directly. 

I managed to copy/paste the log of that _non crashing_ session into a text file: [xpra_dbg.txt](https://github.com/Xpra-org/xpra/files/6620608/xpra_dbg.txt). I don't know how helpful this'll be, or if it'll include useful information that "reset" the bad state of running the launcher, but might as well include it. I can always reopen later.
