### ISSUE TITLE
paramiko ssh config parser can't parse included ssh config files.

### ISSUE THREAD

**Issue by djerius** [Xpra-org/xpra#3163]
I'm using the ssh  `include` directive in my `.ssh/config` file, which looks like this:

```
Include /usr/local/share/home/ssh/*.conf
Include config.d/*.conf
```

It seems that paramiko doesn't understand it. When trying to connect to a host `macabre` which is defined in a configuration file in my ` .ssh/config.d`

I get (via running `xpra --debug all`

```
2021-06-10 16:16:59,525 parsed user config '/home/dj/.ssh/config'
2021-06-10 16:16:59,526 1 hosts found
2021-06-10 16:16:59,526 got host config for 'macabre': {'include': '/usr/local/share/home/ssh/*.conf', 'hostname': 'macabre'}
```

which doesn't look quite right, and sure enough, later on:
```
xpra.scripts.config.InitException: cannot get  address of('macabre', 22): [Errno -2] Name or service not known
Warning: failed to connect:
 cannot get  address of('macabre', 22): [Errno -2] Name or service not known
```
It all works if I simply set `--ssh=ssh`.

**Comment by totaam** [comment]
Needs upstream to merge this: https://github.com/paramiko/paramiko/pull/872
(3 years in limbo..)
Nothing we can or should do in xpra.
