### ISSUE TITLE
Rendering issues/timeout on r29304 vs r29144

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3167]
_Start from https://github.com/Xpra-org/xpra/issues/3167#issuecomment-865872880 instead_

<sub style="font-size: 0.75em;" markdown="1">
I have upgraded server (Focal/r29304), with client win10/r29129, and right now, clipboard operations seem to make the server hangup when `Ctrl+C` is pressed.

Using r29304 for the client, loads the server, loads the windows, loads the spinner - and then it fails.

Problem is between r29270 and r29304.
</sub>

**Comment by totaam** [comment]
Is this still a problem with the latest build?

I've not seen this _server hangup_. Where do I `Ctrl+C`?

**Comment by stdedos** [comment]
> I've not seen this _server hangup_. Where do I `Ctrl+C`?

Not anything specific that I've tried - I just tried to copy stuff from gnome-terminal, sublime text, etc etc ...

I'll check on Monday

**Comment by stdedos** [comment]
Seems like a one-off. I'll keep it mind.

Sounds like related to network issues and https://github.com/Xpra-org/xpra/issues/3086 (which has, again, resurfaced 😕)

**Comment by stdedos** [comment]
... However, "recent updates" (I'd say after r29129), seem to have made the server a bit more unstable.

I am flooded with server wait requests (but not timeout), even with this performance:
![Xpra_cmd_2021-06-22_13-36-46](https://user-images.githubusercontent.com/133706/122910738-389b7c80-d35f-11eb-9f5d-fc24c146bfa0.png)

I am deliberately avoiding posting in https://github.com/Xpra-org/xpra/issues/3121, since I cannot commit time in doing `XPRA_LOG_PACKET_TYPE=1` and going through the output.

**Comment by stdedos** [comment]
_For clarity I don't know/think if that's related to copy-paste operations in general, or "somehow poor handling of something" in server code_

**Comment by stdedos** [comment]
I am thinking that the handling of very big maximized windows "has gotten worse".

Removing the bandwidth limitation works better, making some larger windows smaller helps even more.
However, the (short) bw bursts are no more than ~14 Mbps, so, I'm wondering how is it possible to be a network issue.

**Comment by totaam** [comment]
Please define *very big*.
A single update to a 4K window will use roughly 24bit*3840*2160=140Mbps uncompressed.
Even with a good lossless compression ratio of 10:1, your bandwidth budget will be gone with a single refresh.

There has been no updates to the screen updates logic for some time, nothing at all since the 4.2 release.
Perhaps the list of codecs enabled has changed.
You could always enable paint color debugging with `XPRA_PAINT_BOX=1` and see if the type of encoding has changed.
https://github.com/Xpra-org/xpra/blob/469ca94b6ea13a51c2624c5bb54b6c09651d3d86/xpra/client/paint_colors.py#L8-L24

**Comment by stdedos** [comment]
They are at the size of 2.5K, yes.

The quality at some time seems tanked; however, the text editor (Sublime) does not seem to have degraded quality or pixelization - it just is refresh or isn't (and that leads to timeout).


I guess I'll have to manually check the pre/post paint color 😕
How I hate downgrades, especially with the `upgrade` sequence damaged ....

**Comment by totaam** [comment]
> however, the text editor (Sublime) does not seem to have degraded

I believe that we have a class mapping to `text` for it now, so it should never use lossy compression.
The downside of lossless screen updates is that they use up *a lot* more bandwidth.

**Comment by totaam** [comment]
Regarding screen updates, nothing has changed in 4.3, but #2359 is known to affect text editors. (ie: eclipse and probably others)
Try `--input-method=xim` to see if it helps.

**Comment by stdedos** [comment]
> Try `--input-method=xim` to see if it helps.

Does not help.

Downgrading the server to r29144, however, works. My quick guess is that the scroll encoding is somehow "supplanted" (for a lack of a better translation of my original feeling) by other encoding(s) (webp?).

Most of the affected windows (Sublime Text/Merge, Jetbrains etc) looked like this:
![Xpra_pre-downgrade_cmd_2021-06-28_10-37-27](https://user-images.githubusercontent.com/133706/123599284-1b066100-d7fe-11eb-906f-46cd81bef0db.png)

Whereas downgrading, even from the get-go, windows are rendered like this with r29144:
![Xpra_downgraded_cmd_2021-06-28_10-41-13](https://user-images.githubusercontent.com/133706/123599291-1cd02480-d7fe-11eb-9099-ba57223acc5e.png)

Note that scroll was not disabled: Server:
```
$ xpra info :2 | grep scroll
client.1.encodings=('h264', 'vp9', 'vp8', 'mpeg4', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale')
client.1.encodings.core=('h264', 'vp9', 'vp8', 'mpeg4', 'png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll')
client.1.window.1.encoding.scrolling.enabled=True
client.1.window.1.encoding.scrolling.min-percent=50
client.1.window.1.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.1.total_frames.scroll=5
client.1.window.1.total_pixels.scroll=17149440
client.1.window.3.encoding.scrolling.enabled=True
client.1.window.3.encoding.scrolling.min-percent=50
client.1.window.3.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.4.encoding.scrolling.enabled=True
client.1.window.4.encoding.scrolling.min-percent=50
client.1.window.4.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.4.total_frames.scroll=1
client.1.window.4.total_pixels.scroll=377468
client.1.window.5.encoding.scrolling.enabled=True
client.1.window.5.encoding.scrolling.min-percent=50
client.1.window.5.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.7.encoding.scrolling.enabled=True
client.1.window.7.encoding.scrolling.min-percent=50
client.1.window.7.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.12.encoding.scrolling.enabled=True
client.1.window.12.encoding.scrolling.min-percent=50
client.1.window.12.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.13.encoding.scrolling.enabled=True
client.1.window.13.encoding.scrolling.min-percent=50
client.1.window.13.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.104.encoding.scrolling.enabled=True
client.1.window.104.encoding.scrolling.min-percent=50
client.1.window.104.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.215.encoding.scrolling.enabled=True
client.1.window.215.encoding.scrolling.min-percent=50
client.1.window.215.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.218.encoding.scrolling.enabled=True
client.1.window.218.encoding.scrolling.min-percent=50
client.1.window.218.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.302.encoding.scrolling.enabled=True
client.1.window.302.encoding.scrolling.min-percent=50
client.1.window.302.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
client.1.window.440.encoding.scrolling.enabled=True
client.1.window.440.encoding.scrolling.min-percent=50
client.1.window.440.encodings.non-video=('png', 'png/P', 'png/L', 'webp', 'rgb24', 'rgb32', 'jpeg', 'scroll')
encodings=('rgb', 'scroll', 'h264', 'vp8', 'vp9', 'h264+mp4', 'mpeg4+mp4', 'mpeg1', 'mpeg2', 'png', 'png/L', 'png/P', 'jpeg', 'webp', 'grayscale')
encodings.allowed=('h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'h265', 'mpeg1', 'mpeg2', 'scroll', 'grayscale')
encodings.core=('rgb24', 'rgb32', 'scroll', 'h264', 'vp8', 'vp9', 'h264+mp4', 'mpeg4+mp4', 'mpeg1', 'mpeg2', 'png', 'png/L', 'png/P', 'jpeg', 'webp')
encodings.with_lossless_mode=('scroll', 'webp', 'h264')
encodings.with_quality=('scroll', 'h264', 'vp8', 'vp9', 'jpeg', 'webp')
encodings.with_speed=('webp', 'vp8', 'h264', 'vp9', 'png/L', 'png', 'scroll', 'rgb', 'png/P')
```
Client:
```
"Xpra-Python3-x86_64_4.3-r29325\xpra_cmd" attach ssh://user@ip/2 --ssh="plink -ssh -agent" --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --opengl=no

XPRA_CLIPBOARD_REMOTE_TIMEOUT=5000
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.3-r29325

2021-06-28 10:38:51,857 Xpra GTK3 client version 4.3-r29325 (g84b6a9831) 64-bit
2021-06-28 10:38:51,862  running on Microsoft Windows 10
2021-06-28 10:38:54,655 GStreamer version 1.18.4 for Python 3.8.9 64-bit
2021-06-28 10:38:55,381 created named pipe 'Xpra\9004'
2021-06-28 10:38:55,790 keyboard layout code 0x409
2021-06-28 10:38:55,926 identified as 'United States - English' : us
2021-06-28 10:38:56,631  keyboard settings: layout=us
2021-06-28 10:38:56,733  desktop size is 4160x1440 with 1 screen:
2021-06-28 10:38:56,769   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-06-28 10:38:56,772     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 132x131) workarea: 1600x860 at 0x534
2021-06-28 10:38:56,773     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-06-28 10:38:56,793 Warning: cannot query ICC profiles:
2021-06-28 10:38:56,801  cannot import name 'ImageWin' from 'PIL' (Xpra-Python3-x86_64_4.3-r29325\lib\PIL\__init__.pyc)
2021-06-28 10:39:00,584 enabled remote logging
2021-06-28 10:39:00,588 Xpra X11 seamless server version 4.3-r29144 64-bit
2021-06-28 10:39:00,590  running on Linux Ubuntu 20.04 focal
2021-06-28 10:39:00,628 Attached to 172.16.0.0:22
2021-06-28 10:39:00,635  (press Control-C to detach)


(xpra_cmd:9004): Pango-WARNING **: 10:39:01.475: couldn't load font "DejaVu Serif Not-Rotated 59.796875", falling back to "Sans Not-Rotated 59.796875", expect ugly output.

(xpra_cmd:9004): Pango-WARNING **: 10:39:01.890: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.

(xpra_cmd:9004): Pango-WARNING **: 10:39:01.933: couldn't load font "Bitstream Vera Sans Not-Rotated 14.662109375", falling back to "Sans Not-Rotated 14.662109375", expect ugly output.
2021-06-28 10:39:03,434 UI thread is now blocked
2021-06-28 10:39:04,437 running, 10 windows, 1 tray
2021-06-28 10:39:04,678 UI thread is running again, resuming
2021-06-28 10:39:04,760 Warning: static gravity is not handled
2021-06-28 10:39:30,108 toggling debug on backing gtk3.CairoBacking(ImageSurface(2560, 1377) : size=(2560, 1377), render_size=(2560, 1377)) for window 5
```

PS: Server signature
```
2021-06-28 10:39:00,588 Xpra X11 seamless server version 4.3-r29144 64-bit
```
might be of more help to you if it also contained the git-describe hash

**Comment by totaam** [comment]
Your first screenshot looks identical to the top of the second one.  Both using webp for the window's menu bar. What am I meant to be seeing here?

Since there were no changes to the screen update handling, perhaps it's a problem with the builds enabling different codecs (fixes or dependency changes in the build environment). Or the bug fix to the webp encoder somehow causes it.

You could try running with just `--encodings=jpeg,rgb,png --video-encoders=vpx --csc-modules=libyuv`.
This would seriously limit the codecs and tell us if it's a codec issue or not.
(comparing both versions with those same restricted settings)

**Comment by stdedos** [comment]
> Your first screenshot looks identical to the top of the second one. Both using webp for the window's menu bar. What am I meant to be seeing here?

The first one is missing the full-frame part, but there was no other color to render (and redaction was a little unnecessary and therefore boring). The second one, however, has all of these:
![image](https://user-images.githubusercontent.com/133706/123749939-a5ae9500-d8be-11eb-8cad-63ad0648dafb.png)
... which I thought there were somehow scrolling encoding (i.e. which avoided a burst of webp full-frame refresh).

But I guess they are
```python
    "rgb24"     : "orange",
    "rgb32"     : "red",
    "webp"      : "pink",
    "vp9"       : "lavender",
```

**Comment by totaam** [comment]
> The second one, however, has all of these:

Second one? That's a completely different one. What is it?

> But I guess they are

Yellow is `png`.

**Comment by stdedos** [comment]
> > The second one, however, has all of these:
> 
> Second one? That's a completely different one. What is it?

The second _image_.

> > But I guess they are
> 
> Yellow is `png`.

I used the yellow as a highlighting means (an alternative would be to draw about 5 arrows pointing at the lines, but that would be too much time I guess)

**Comment by totaam** [comment]
> The second image.

Now I am utterly confused. I was asking what this image is:
https://github.com/Xpra-org/xpra/issues/3167#issuecomment-870291479
How it was obtained, with which version and settings. Is this when things are "bad"?

> I used the yellow as a highlighting means

Wait. So you edited the picture and added yellow (which is normally `png`). No wonder I am getting confused.
I don't think I can make sense of it now.
As per https://github.com/Xpra-org/xpra/issues/3167#issuecomment-869764384, I would compare versions with limited codecs to try to narrow it down.

**Comment by stdedos** [comment]
> How it was obtained, with which version and settings.

Right after re-connecting with the downgraded client. Things are good and stable here.

> Is this when things are "bad"?
No, this is where things are good.
The bad things, are on the small picture (the newer client), where the rendering is just a pink outline (webp) constantly.

> As per [#3167 (comment)](https://github.com/Xpra-org/xpra/issues/3167#issuecomment-869764384), I would compare versions with limited codecs to try to narrow it down.

I am currently running the old client with the provided arguments. I do see ugly refreshes from time to time (8bit color, blurry textures and text) temporarily, but absolutely no issues with connectivity or latency so far.

I'll upgrade the server tomorrow, and re-run.

**Comment by totaam** [comment]
> I'll upgrade the server tomorrow, and re-run.

Cool. Thanks.
Make sure to try with `--encodings=jpeg,rgb,png --video-encoders=vpx --csc-modules=libyuv` to see if that helps.

**Comment by stdedos** [comment]
Tons and tons of 
```
 181561 2021-06-30 11:12:37,661 using non-video fallback encoding
 181562 2021-06-30 11:20:51,998 Error: no video pipeline options found for BGRX 24-bit at 2163x1284
 181563 2021-06-30 11:20:51,998 Error: failed to setup a video pipeline for auto encoding with source format BGRX
 181564 2021-06-30 11:20:51,999  all encoders: 
 181565 2021-06-30 11:20:51,999  supported CSC modes: 
 181566 2021-06-30 11:20:51,999  supported encoders: 
 181567 2021-06-30 11:20:51,999  encoders CSC modes: 
```

these. I guess this is "your" doing?

**Comment by stdedos** [comment]
I honestly don't see any difference, for the mentioned versions, for the specific command-line flags you requested, with regards to my issue. However, for both versions, the connectivity stabilized a lot. Further pointing to that fact is that, there were numerous crappy renderings for a miniscule-to-small amount of time visible, only to then be rendered at maximum quality a few moments later.

If anything, this combination makes xpra act **exactly** the way I want it!
Do I have bandwidth to send full quality? **FIRE AWAY @4K**.
Do I have problems temporarily? Latency/Bandwidth/WhatNot? **Immediately** render the crappiest possible version (8bit color or less, grained etc), and follow up with nicer updates "when there's time".

That helps so much for the session to feel interactive at all times - something that's very high on my wish-list, and secondarily good quality. I don't like my text editor granulated with 8bit color, but I'll trade this anytime for the feeling that, when I press something, the command is received and executed, and I "kinda" see its results.

**Comment by totaam** [comment]
> I honestly don't see any difference, for the mentioned versions, for the specific command-line flags you requested, with regards to my issue.

Good. So there must be a problem when more codecs are enabled, rather than the server logic itself.
Perhaps one of them takes way too long. OTOH, it could well be `--video-encoders=ffmpeg` since it now has `vaapi` hardware acceleration support and whenever interacting with hardware, things can get tangled up.  
You could try re-adding them one by one until the problem manifests itself again.

> If anything, this combination makes xpra act exactly the way I want it!

That's the way it is supposed to work, the way it should always be!

> Immediately render the crappiest possible version (8bit color or less, grained etc), and follow up with nicer updates "when there's time".

The only tricky thing there is deciding if it's worth the small extra bandwidth of the lossy update. Also, if the area is updated regularly, the lossless refresh may never get a chance to fire and the picture will remain blurry.

**Comment by stdedos** [comment]
> > If anything, this combination makes xpra act exactly the way I want it!
> 
> That's the way it is supposed to work, the way it should always be!
 
I've never seen xpra work so quickly, so "flawlessly" in a sense. Of course, the difference now is very striking - from a very losslessly no-delay rendering, to a very varied but a responsive one. Hence, maybe that's the reason I am noticing it. 

> > Immediately render the crappiest possible version (8bit color or less, grained etc), and follow up with nicer updates "when there's time".
> 
> The only tricky thing there is deciding if it's worth the small extra bandwidth of the lossy update. 

If the update takes more than 2RTT, or more than 200ms (that's not visible on the network level), I am very willing to sacrifice bandwidth (and quality) to get my responsiveness back. 

> Also, if the area is updated regularly, the lossless refresh may never get a chance to fire and the picture will remain blurry.

This has never happened so far - I've never gone more than eg 3 seconds without having my screen clean up to an acceptable level at least.

**Comment by totaam** [comment]
> I've never seen xpra work so quickly, so "flawlessly" in a sense.

If it turns out that these settings you are using make things work better, then we should figure out which ones make it worse and fix them. (perhaps one of the video codecs introduces unacceptable delays)

FYI: new beta builds have finally been uploaded - now that #3190 vanished on its own.

**Comment by stdedos** [comment]
> Perhaps one of them takes way too long. OTOH, it could well be `--video-encoders=ffmpeg` since it now has `vaapi` hardware acceleration support and whenever interacting with hardware, things can get tangled up.

Is this a client or a server option? To add e.g. vpx should I re-attach or re-upgrade? (or both?)

**Comment by totaam** [comment]
> Is this a client or a server option?

Server.
An upgrade should do the trick. Nothing should be needed client-side, apart from the obvious re-attach since that's still not automatic.

**Comment by stdedos** [comment]
Aha. Well.... surprise 😕 

I did all of that using _client-side_ options

**Comment by stdedos** [comment]
Also, no error checking: I used to connect with `--encodings=jprg,rgb,png --video-encoders=vpx --csc-modules=libyuv` (jprg)

**Comment by stdedos** [comment]
Note-to-self: `--video-encoders=all,-ffmpeg,-nvenc` works as well just fine (if needed)

**Comment by stdedos** [comment]
a. I think that, even though the `--encodings=jprg,rgb,png --video-encoders=all,-ffmpeg --csc-modules=libyuv` should've been server-side options, using them in `attach` is "good enough": ffmpeg stops crying about that video pipeline "patches welcome" server-side
b. Removing `--encodings=jprg,rgb,png --csc-modules=libyuv` causes the high bw issues / "inability" to quickly shape quality to the available bw/latency.

What's next?

**Comment by totaam** [comment]
> `--encodings=jprg,rgb,png`

I assume that you've typed `jpeg` correctly in your command line, and wrong only here in this ticket?

> Removing `--encodings=jprg,rgb,png --csc-modules=libyuv` causes the high bw issues / "inability" to quickly shape quality to the available bw/latency.

That's actually excellent news: it means that we can very quickly identify which codec is causing the problem.

Just re-add them one by one until things go wrong again.
I would start by re-adding all encodings (removing the whole `--encodings` switch) and  / or the whole `--csc-modules=all` to see which way to "bisect". Is it an encoding issue or a video codec issue.
My guess is that one of the video encoders is way too slow. `--csc-modules=libyuv` is much more limited in what formats it can handle - especially with the non-opengl renderer, which doesn't handle csc either (whereas the opengl one does).

**Comment by totaam** [comment]
The obvious suspect is vaapi: it now requires kernel v5 or later to be enabled in master (55be7e7eed5cae8a271f77266fcb0f112e33a645)

So many problems that it was disabled by default in v4.2.1: fb52a4b8e58eaa27df509e2286d16efcd0d93ae6

**Comment by totaam** [comment]
FYI found another huge bug that may have affected latency: #3201

**Comment by stdedos** [comment]
😂 I should've waited a little bit before I updated the server today

**Comment by stdedos** [comment]
Activating `swscale` gave couple of spinners, but not consistently.
Activating `cython` immediately after `swscale`s timeouts, gave spinners immediately upon "real" use.

**Comment by stdedos** [comment]
`--csc-modules=help --csc-modules=libyuv` does not trigger the help text, instead it connects normally

**Comment by stdedos** [comment]
> Activating `swscale` gave couple of spinners, but not consistently.
> Activating `cython` immediately after `swscale`s timeouts, gave spinners immediately upon "real" use.

I think these flags also lead in faulty rendering like https://github.com/Xpra-org/xpra/issues/3042

**Comment by totaam** [comment]
Is this still an issue with the latest builds?

**Comment by stdedos** [comment]
I don't think I have removed the aforementioned flags since this ticket's creation, so, I cannot tell for sure 😕 

There are also the "technical issues", such as:

* > `--csc-modules=help --csc-modules=libyuv` does not trigger the help text, instead it connects normally
* > > `--encodings=jprg,rgb,png`
  > 
  > I assume that you've typed `jpeg` correctly in your command line, and wrong only here in this ticket?

I don't/won't have an environment like the one I had for quite some time, so, it's up to you if you'd prefer to close it as fixed.

**Comment by totaam** [comment]
As of the commit above + e2c978cec2f5c021f4b84db1877eeaa784be85e7 (wrong ticket tagged in commit..):
```shell
$ xpra start --csc-modules=help --csc-modules=libyuv --no-daemon
the following csc modules may be available: swscale, cython, libyuv
```
```shell
$ xpra start --encodings=red,rgb,blue --no-daemon
invalid encodings specified: red, blue
```
