### ISSUE TITLE
no login after user screen is locked 

### ISSUE THREAD

**Issue by unicorn667** [Xpra-org/xpra#3178]
Hello,

I have the same issue on RHEL8 and Debian 10. 

After the session is locked from the desktop, no unlock is possible. Any idea of this issue?

Best Regards

Tomcat

Version on Debian  2.4.3

Debian 10 error 
`Jun 23 09:57:47 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Characters.BackgroundService'
Jun 23 09:57:47 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Terminal'
Jun 23 09:57:47 debian org.gnome.Chara[9177]: JS WARNING: [resource:///org/gnome/Characters/BackgroundService/js/searchProvider.js 50]: Strin
g.toUpperCase is deprecated; use String.prototype.toUpperCase instead
Jun 23 09:57:48 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Activating service name='org.freedesktop.secrets' requested by ':1.67'
(uid=1000 pid=9182 comm="/usr/bin/seahorse --gapplication-service ")
Jun 23 09:57:48 debian org.freedesktop.secrets[6618]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
Jun 23 09:57:48 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Contacts.SearchProvider'
Jun 23 09:57:48 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Documents'
Jun 23 09:57:48 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Nautilus'
Jun 23 09:57:48 debian dbus-daemon[6618]: [session uid=1000 pid=6616] Successfully activated service 'org.gnome.Calendar'
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:48 debian gnome-clocks[9186]: g_variant_new_string: assertion 'string != NULL' failed
Jun 23 09:57:49 debian PackageKit: resolve transaction /37_eedbdbba from uid 1000 finished with cancelled after 811ms
Jun 23 09:57:49 debian gnome-software[7060]: internal error: failed, but no error code: cancelled
Jun 23 09:57:49 debian PackageKit: resolve transaction /38_bdaacdac from uid 1000 finished with success after 227ms
Jun 23 09:57:51 debian org.gnome.Terminal.desktop[6792]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
Jun 23 09:57:51 debian org.gnome.Terminal.desktop[6792]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
Jun 23 09:57:51 debian org.gnome.Terminal.desktop[6792]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
Jun 23 09:58:13 debian seahorse[9182]: gkr-backend.vala:94: couldn't connect to secret service: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached
`

RHEL 8 Error Log with xpra v4.2-r0 

`
journal[289465]: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.20 was not provided by any .service files
`

**Comment by totaam** [comment]
@unicorn667 please specify the command lines you are using.

Are you using `shadow` or `start-desktop`?

> Version on Debian 2.4.3

This version was EOLed years ago: https://github.com/Xpra-org/xpra/wiki/Versions

**Comment by totaam** [comment]
Probably caused by using an out of date version.

**Comment by georgedorn** [comment]
I just had this happen to me on xubuntu 22.04, with xpra v3.1.  It's not EOL yet.

Weirdly, it never happened to me before, until I upgraded the machine I connect to with it; it started sending much more of the desktop (xpanel, etc) to the client.  While localhost was locked, key and mouse movement ended up in a terminal window (also on localhost).  I ssh'd into the machine from another one and killed Xpra, and the sent keys were sent correctly to the lock screen again.

I'll try upgrading to 4.4.x and see if it still happens, given I seem to have a rare setup where it happens.

**Comment by totaam** [comment]
> with xpra v3.1. It's not EOL yet.

It is. Don't use it.
That said, the problems you describe may well be caused by using `uinput` and / or Debian in general.
Please try with a better distro.

**Comment by georgedorn** [comment]
I mean, I don't disagree that Ubuntu is awful, but that's a huge portion of the linux userbase.

Anyway, I had a similar issue with 4.4 (target machine grabbing keys from the client machine while client machine was locked).  Resolved by ripping out the window manager and session manager and leaving just Xorg on the target machine.  Probably not a viable solution for most who run into this.

Future searchers who end up here:  try disabling the screensaver / lock timeout on the target machine.

**Comment by totaam** [comment]
> I mean, I don't disagree that Ubuntu is awful, but that's a huge portion of the linux userbase.

I said Debian, but this applies to Ubuntu too.

> Probably not a viable solution for most who run into this.

Right. Like I said, don't use Debian, the problem comes from there - it's not even an Ubuntu thing.
https://github.com/Xpra-org/xpra/issues/2834#issuecomment-1179500636
