### ISSUE TITLE
xdg-open `error processing control command: 'ClientConnectionMuxer' object has no attribute 'file_transfer'`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3179]
Small issue I bumped onto today:

```
$ xdg-open ~/index.html 
server returned error code 127
 error processing control command: 'ClientConnectionMuxer' object has no attribute 'file_transfer'
```

Which is weird, since it's happening after the server upgrade. However, the server was in need on `recover` (and it's not the same as the `upgrade` one)

**Comment by totaam** [comment]
Without the full backtrace from the server log, I can't be 100% certain, but I am fairly confident that the fix above is the correct one for this bug.
(you must have had a `top` client running?)

**Comment by stdedos** [comment]
> (you must have had a `top` client running?)

Yes I do. Constantly 😛

**Comment by stdedos** [comment]
> Without the full backtrace from the server log, I can't be 100% certain, but I am fairly confident that the fix above is the correct one for this bug.

I can try to dig this up for you on Monday.

**Comment by stdedos** [comment]
```
    131 2021-06-30 09:03:14,745 screen used by 2 clients:
    132 2021-06-30 09:03:14,745 * eedb92ace05de166b941da2f38da1a4a734d8e3e: unknown
    133 2021-06-30 09:03:14,746 * 484e1798d8e5cfd8b5095ee96c48ae753bf9e9d5: 4160x1440
```

and

```python
2021-06-30 10:33:46,372 error processing control command 'send-file'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/server_core.py", line 692, in process_control_command
    v = command.run(*args[1:])
  File "/usr/lib/python3/dist-packages/xpra/server/control_command.py", line 68, in run
    return super().run(*args)
  File "/usr/lib/python3/dist-packages/xpra/server/control_command.py", line 33, in run
    return self.do_run(*args)
  File "/usr/lib/python3/dist-packages/xpra/server/mixins/server_base_controlcommands.py", line 296, in control_command_send_file
    return self.do_control_file_command("send file", client_uuids, filename, "file_transfer", (False, openit))
  File "/usr/lib/python3/dist-packages/xpra/server/mixins/server_base_controlcommands.py", line 338, in do_control_file_command
    if not getattr(ss, source_flag_name):
AttributeError: 'ClientConnectionMuxer' object has no attribute 'file_transfer'
2021-06-30 10:33:53,651 client   3 @49.121 downloaded 516 bytes to temporary file:
2021-06-30 10:33:53,721 client   3 @49.149  '\Downloads\printers.conf'
```

However, the file was downloaded successfully.

**Comment by totaam** [comment]
> `    if not getattr(ss, source_flag_name):`

That's definitely an older version of the code, which now looks like this:
https://github.com/Xpra-org/xpra/blob/41cd6689e69f0c7535ebf47712c3f7ad7d58218b/xpra/server/mixins/server_base_controlcommands.py#L338

> `screen used by 2 clients`
Should be fixed in b4975dd017bb10e5003c99ddbabdb5cc5dfcdc15

**Comment by stdedos** [comment]
> That's definitely an older version of the code

I am absolutely certain that I did apt-get, *and* xpra upgrade... 

Dammit, I'll check more thoroughly again.

**Comment by totaam** [comment]
> Dammit, I'll check more thoroughly again.

I'll be pushing new builds in a couple of hours.

**Comment by stdedos** [comment]
> Have you forgotten to build the Focal beta? I still don't see anything.

**Comment by totaam** [comment]
> Have you forgotten to build the Focal beta? I still don't see anything.

Trying to fix #3187 first.

**Comment by stdedos** [comment]
Verified as fixed

**Comment by stdedos** [comment]
However, "do you really need that" as a warning?

```
    507 2021-07-05 10:10:23,595 Warning: cannot send file 'requirements.txt'
    508 2021-07-05 10:10:23,595  client ClientConnectionMuxer(2 : Protocol(unix-domain socket:/run/user/1000/xpra/u-h-2)) does not support this feature
    509 2021-07-05 10:10:24,762 client   1 @18.168 downloaded 20 bytes to temporary file:
    510 2021-07-05 10:10:24,821 client   1 @18.174  'requirements.txt'
    511 2021-07-05 10:10:26,608 client   1 @19.977 unknown string message: 0xc2a2 / 0x0 / 0x0
```

Maybe just `if client == xpra.client.TOP: return`?

**Comment by totaam** [comment]
> Maybe just `if client == xpra.client.TOP: return`?

Good idea: a0e04c991fe5b8edfee398fb347e4652aef461a3
