### ISSUE TITLE
proxy: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by goekce** [Xpra-org/xpra#3181]
Using 3004e3d, could be related to #912

After one week, on a server with multiple users I have about 70 sessions open. After that the proxy does not accept new connections anymore:

```
Error sending '/usr/share/xpra/www/css/icon.css':
Error: cannot accept new connection:
 [Errno 24] Too many open files
 [Errno 24] Too many open file
```
open file descriptors:
```
ls -al /proc/8592/fd | wc -l
1025
```

- Is this a bug or normal behavior?
  - if this is not a leak, is it possible to increase this limit?
- is it possible to shutdown idle servers (similar to idle-culler service in Jupyterhub)?

**Comment by basilgello** [comment]
It might be a file descriptor soft limit hit: https://www.linuxtechi.com/set-ulimit-file-descriptors-limit-linux-servers/

And unused TCP connections are cleared by timeout by Linux kernel.

**Comment by totaam** [comment]
> Is this a bug or normal behavior?

Could be either.
Can you give us the list of open file descriptors?
`ls -l /proc/$SERVERPID/fd`

> is it possible to shutdown idle servers

See `idle-timeout` with `exit-with-client` and `server-idle-timeout`.

**Comment by goekce** [comment]
> Could be either.
> Can you give us the list of open file descriptors?
> `ls -l /proc/$SERVERPID/fd`

Currently I have 153 descriptors:
<details><summary>details</summary>
<pre><code>
dr-x------ 2 root root  0 Jun 27 09:44 .
dr-xr-xr-x 9 root root  0 Jun 27 09:44 ..
lr-x------ 1 root root 64 Jun 27 09:44 0 -> /dev/null
lrwx------ 1 root root 64 Jun 27 09:44 1 -> 'socket:[5977913]'
lrwx------ 1 root root 64 Jun 27 09:44 10 -> 'socket:[5990799]'
l-wx------ 1 root root 64 Jun 28 18:41 100 -> 'pipe:[6297055]'
lr-x------ 1 root root 64 Jun 28 18:41 101 -> 'pipe:[6274346]'
l-wx------ 1 root root 64 Jun 28 18:41 102 -> 'pipe:[6297853]'
lr-x------ 1 root root 64 Jun 28 18:41 103 -> 'pipe:[6255121]'
lr-x------ 1 root root 64 Jun 28 18:41 104 -> 'pipe:[6294881]'
lr-x------ 1 root root 64 Jun 28 18:41 105 -> 'pipe:[6284131]'
l-wx------ 1 root root 64 Jun 28 18:41 106 -> 'pipe:[6284131]'
l-wx------ 1 root root 64 Jun 28 18:41 107 -> 'pipe:[6294882]'
l-wx------ 1 root root 64 Jun 28 18:41 108 -> 'pipe:[6255121]'
lr-x------ 1 root root 64 Jun 28 18:41 109 -> 'pipe:[6284132]'
lr-x------ 1 root root 64 Jun 27 09:44 11 -> 'pipe:[5984739]'
lr-x------ 1 root root 64 Jun 28 18:41 110 -> 'pipe:[6302773]'
l-wx------ 1 root root 64 Jun 28 18:41 111 -> 'pipe:[6302773]'
l-wx------ 1 root root 64 Jun 28 18:41 112 -> 'pipe:[6274347]'
l-wx------ 1 root root 64 Jun 28 18:41 113 -> 'pipe:[6284133]'
lr-x------ 1 root root 64 Jun 28 18:41 114 -> 'pipe:[6302774]'
lr-x------ 1 root root 64 Jun 28 18:41 115 -> 'pipe:[6320383]'
l-wx------ 1 root root 64 Jun 28 18:41 116 -> 'pipe:[6320383]'
l-wx------ 1 root root 64 Jun 28 18:41 117 -> 'pipe:[6302775]'
lr-x------ 1 root root 64 Jun 28 18:41 118 -> 'pipe:[6320384]'
lr-x------ 1 root root 64 Jun 28 18:41 119 -> 'pipe:[6346926]'
l-wx------ 1 root root 64 Jun 27 09:44 12 -> 'pipe:[5984739]'
l-wx------ 1 root root 64 Jun 28 18:41 120 -> 'pipe:[6346926]'
l-wx------ 1 root root 64 Jun 28 18:41 121 -> 'pipe:[6320385]'
lr-x------ 1 root root 64 Jun 28 18:41 122 -> 'pipe:[6346927]'
lr-x------ 1 root root 64 Jun 28 18:41 123 -> 'pipe:[6326701]'
lr-x------ 1 root root 64 Jun 28 18:41 124 -> 'pipe:[6390658]'
l-wx------ 1 root root 64 Jun 28 18:41 125 -> 'pipe:[6390658]'
lr-x------ 1 root root 64 Jun 28 18:41 126 -> 'pipe:[6326699]'
l-wx------ 1 root root 64 Jun 28 18:41 127 -> 'pipe:[6326699]'
l-wx------ 1 root root 64 Jun 28 18:41 128 -> 'pipe:[6346928]'
l-wx------ 1 root root 64 Jun 28 18:41 129 -> 'pipe:[6326702]'
lr-x------ 1 root root 64 Jun 28 18:41 130 -> 'pipe:[6390659]'
lr-x------ 1 root root 64 Jun 28 18:41 131 -> 'pipe:[6405278]'
l-wx------ 1 root root 64 Jun 28 18:41 132 -> 'pipe:[6405278]'
l-wx------ 1 root root 64 Jun 28 18:41 133 -> 'pipe:[6390660]'
lr-x------ 1 root root 64 Jun 28 18:41 134 -> 'pipe:[6363038]'
lr-x------ 1 root root 64 Jun 28 18:41 135 -> 'pipe:[6405279]'
lr-x------ 1 root root 64 Jun 28 18:41 136 -> 'pipe:[6402562]'
l-wx------ 1 root root 64 Jun 28 18:41 137 -> 'pipe:[6402562]'
l-wx------ 1 root root 64 Jun 28 18:41 138 -> 'pipe:[6405280]'
lr-x------ 1 root root 64 Jun 28 18:41 139 -> 'pipe:[6402563]'
lr-x------ 1 root root 64 Jun 28 18:41 140 -> 'pipe:[6375466]'
l-wx------ 1 root root 64 Jun 28 18:41 141 -> 'pipe:[6375466]'
lr-x------ 1 root root 64 Jun 28 18:41 142 -> 'pipe:[6402675]'
l-wx------ 1 root root 64 Jun 28 18:41 143 -> 'pipe:[6402675]'
l-wx------ 1 root root 64 Jun 28 18:41 144 -> 'pipe:[6402564]'
l-wx------ 1 root root 64 Jun 28 18:41 145 -> 'pipe:[6363039]'
lr-x------ 1 root root 64 Jun 28 18:41 146 -> 'pipe:[6402676]'
l-wx------ 1 root root 64 Jun 28 18:41 149 -> 'pipe:[6402677]'
lr-x------ 1 root root 64 Jun 28 18:41 15 -> 'pipe:[6113372]'
lr-x------ 1 root root 64 Jun 28 18:41 156 -> 'pipe:[6473195]'
l-wx------ 1 root root 64 Jun 28 18:41 16 -> 'pipe:[6113372]'
lr-x------ 1 root root 64 Jun 28 18:41 160 -> 'pipe:[6468940]'
l-wx------ 1 root root 64 Jun 28 18:41 161 -> 'pipe:[6468940]'
l-wx------ 1 root root 64 Jun 28 18:41 165 -> 'pipe:[6473196]'
lr-x------ 1 root root 64 Jun 28 18:41 17 -> 'pipe:[6113373]'
lr-x------ 1 root root 64 Jun 28 18:41 18 -> 'pipe:[6082252]'
lr-x------ 1 root root 64 Jun 28 18:41 19 -> 'pipe:[6116398]'
lrwx------ 1 root root 64 Jun 27 09:44 2 -> 'socket:[5977913]'
lrwx------ 1 root root 64 Jun 28 18:41 20 -> 'socket:[6040007]'
l-wx------ 1 root root 64 Jun 28 18:41 21 -> 'pipe:[6116398]'
l-wx------ 1 root root 64 Jun 28 18:41 22 -> 'pipe:[6113374]'
lr-x------ 1 root root 64 Jun 28 18:41 23 -> 'pipe:[6110662]'
l-wx------ 1 root root 64 Jun 28 18:41 24 -> 'pipe:[6082252]'
lr-x------ 1 root root 64 Jun 28 18:41 25 -> 'pipe:[6117352]'
lr-x------ 1 root root 64 Jun 28 18:41 26 -> 'pipe:[6088338]'
l-wx------ 1 root root 64 Jun 28 18:41 27 -> 'pipe:[6117352]'
l-wx------ 1 root root 64 Jun 28 18:41 28 -> 'pipe:[6110663]'
lr-x------ 1 root root 64 Jun 28 18:41 29 -> 'pipe:[6117353]'
lrwx------ 1 root root 64 Jun 27 09:44 3 -> 'socket:[5977910]'
lr-x------ 1 root root 64 Jun 28 18:41 30 -> 'pipe:[6127701]'
l-wx------ 1 root root 64 Jun 28 18:41 31 -> 'pipe:[6127701]'
l-wx------ 1 root root 64 Jun 28 18:41 32 -> 'pipe:[6117354]'
l-wx------ 1 root root 64 Jun 28 18:41 33 -> 'pipe:[6088339]'
lr-x------ 1 root root 64 Jun 28 18:41 34 -> 'pipe:[6127702]'
lr-x------ 1 root root 64 Jun 28 18:41 35 -> 'pipe:[6131921]'
l-wx------ 1 root root 64 Jun 28 18:41 36 -> 'pipe:[6131921]'
l-wx------ 1 root root 64 Jun 28 18:41 37 -> 'pipe:[6127703]'
lr-x------ 1 root root 64 Jun 28 18:41 38 -> 'pipe:[6131922]'
lr-x------ 1 root root 64 Jun 28 18:41 39 -> 'pipe:[6130098]'
lrwx------ 1 root root 64 Jun 27 09:44 4 -> 'socket:[5990787]'
l-wx------ 1 root root 64 Jun 28 18:41 40 -> 'pipe:[6130098]'
l-wx------ 1 root root 64 Jun 28 18:41 41 -> 'pipe:[6131923]'
lr-x------ 1 root root 64 Jun 28 18:41 42 -> 'pipe:[6128202]'
lr-x------ 1 root root 64 Jun 28 18:41 43 -> 'pipe:[6135188]'
l-wx------ 1 root root 64 Jun 28 18:41 44 -> 'pipe:[6135188]'
l-wx------ 1 root root 64 Jun 28 18:41 45 -> 'pipe:[6128203]'
lr-x------ 1 root root 64 Jun 28 18:41 46 -> 'pipe:[6135189]'
lr-x------ 1 root root 64 Jun 28 18:41 47 -> 'pipe:[6147141]'
l-wx------ 1 root root 64 Jun 28 18:41 48 -> 'pipe:[6147141]'
l-wx------ 1 root root 64 Jun 28 18:41 49 -> 'pipe:[6135190]'
lrwx------ 1 root root 64 Jun 27 09:44 5 -> 'anon_inode:[eventfd]'
lr-x------ 1 root root 64 Jun 28 18:41 50 -> 'pipe:[6147142]'
lr-x------ 1 root root 64 Jun 28 18:41 51 -> 'pipe:[6130502]'
l-wx------ 1 root root 64 Jun 28 18:41 52 -> 'pipe:[6130502]'
l-wx------ 1 root root 64 Jun 28 18:41 53 -> 'pipe:[6147143]'
lr-x------ 1 root root 64 Jun 28 18:41 54 -> 'pipe:[6137147]'
lr-x------ 1 root root 64 Jun 28 18:41 55 -> 'pipe:[6150260]'
l-wx------ 1 root root 64 Jun 28 18:41 56 -> 'pipe:[6150260]'
l-wx------ 1 root root 64 Jun 28 18:41 57 -> 'pipe:[6137148]'
lr-x------ 1 root root 64 Jun 28 18:41 58 -> 'pipe:[6150261]'
lr-x------ 1 root root 64 Jun 28 18:41 59 -> 'pipe:[6138823]'
lrwx------ 1 root root 64 Jun 27 09:44 6 -> 'socket:[6023930]'
l-wx------ 1 root root 64 Jun 28 18:41 60 -> 'pipe:[6138823]'
l-wx------ 1 root root 64 Jun 28 18:41 61 -> 'pipe:[6150262]'
lr-x------ 1 root root 64 Jun 28 18:41 62 -> 'pipe:[6138824]'
lr-x------ 1 root root 64 Jun 28 18:41 63 -> 'pipe:[6156026]'
l-wx------ 1 root root 64 Jun 28 18:41 64 -> 'pipe:[6156026]'
l-wx------ 1 root root 64 Jun 28 18:41 65 -> 'pipe:[6138825]'
lr-x------ 1 root root 64 Jun 28 18:41 66 -> 'pipe:[6156027]'
lr-x------ 1 root root 64 Jun 28 18:41 67 -> 'pipe:[6156531]'
l-wx------ 1 root root 64 Jun 28 18:41 68 -> 'pipe:[6156531]'
l-wx------ 1 root root 64 Jun 28 18:41 69 -> 'pipe:[6156028]'
lrwx------ 1 root root 64 Jun 27 09:44 7 -> 'anon_inode:[eventfd]'
lr-x------ 1 root root 64 Jun 28 18:41 70 -> 'pipe:[6150558]'
lr-x------ 1 root root 64 Jun 28 18:41 71 -> 'pipe:[6164640]'
l-wx------ 1 root root 64 Jun 28 18:41 72 -> 'pipe:[6164640]'
l-wx------ 1 root root 64 Jun 28 18:41 73 -> 'pipe:[6150559]'
lr-x------ 1 root root 64 Jun 28 18:41 74 -> 'pipe:[6164641]'
lr-x------ 1 root root 64 Jun 28 18:41 75 -> 'pipe:[6151101]'
l-wx------ 1 root root 64 Jun 28 18:41 76 -> 'pipe:[6151101]'
l-wx------ 1 root root 64 Jun 28 18:41 77 -> 'pipe:[6164642]'
lr-x------ 1 root root 64 Jun 28 18:41 78 -> 'pipe:[6151102]'
lr-x------ 1 root root 64 Jun 28 18:41 79 -> 'pipe:[6191969]'
lr-x------ 1 root root 64 Jun 27 09:44 8 -> anon_inode:inotify
l-wx------ 1 root root 64 Jun 28 18:41 80 -> 'pipe:[6191969]'
l-wx------ 1 root root 64 Jun 28 18:41 81 -> 'pipe:[6151103]'
lr-x------ 1 root root 64 Jun 28 18:41 82 -> 'pipe:[6198997]'
lr-x------ 1 root root 64 Jun 28 18:41 83 -> 'pipe:[6222563]'
lr-x------ 1 root root 64 Jun 28 18:41 84 -> 'pipe:[6174960]'
l-wx------ 1 root root 64 Jun 28 18:41 85 -> 'pipe:[6222563]'
lr-x------ 1 root root 64 Jun 28 18:41 86 -> 'pipe:[6174959]'
l-wx------ 1 root root 64 Jun 28 18:41 87 -> 'pipe:[6174959]'
l-wx------ 1 root root 64 Jun 28 18:41 88 -> 'pipe:[6198998]'
lr-x------ 1 root root 64 Jun 28 18:41 89 -> 'pipe:[6224773]'
lrwx------ 1 root root 64 Jun 27 09:44 9 -> 'socket:[5990798]'
lr-x------ 1 root root 64 Jun 28 18:41 90 -> 'pipe:[6297814]'
l-wx------ 1 root root 64 Jun 28 18:41 91 -> 'pipe:[6297814]'
l-wx------ 1 root root 64 Jun 28 18:41 92 -> 'pipe:[6174961]'
l-wx------ 1 root root 64 Jun 28 18:41 93 -> 'pipe:[6224774]'
lr-x------ 1 root root 64 Jun 28 18:41 94 -> 'pipe:[6297815]'
lr-x------ 1 root root 64 Jun 28 18:41 95 -> 'pipe:[6297851]'
l-wx------ 1 root root 64 Jun 28 18:41 96 -> 'pipe:[6297851]'
l-wx------ 1 root root 64 Jun 28 18:41 97 -> 'pipe:[6297816]'
lr-x------ 1 root root 64 Jun 28 18:41 98 -> 'pipe:[6297852]'
lr-x------ 1 root root 64 Jun 28 18:41 99 -> 'pipe:[6297055]'
</code></pre>
</details>

Is this helpful or do you need an `ls` after the error?

> See `idle-timeout` with `exit-with-client` and `server-idle-timeout`.

Thanks, I will set this later after we resolved the fd issue.

**Comment by totaam** [comment]
> Currently I have 153 descriptors:

I believe that those pipes are likely to be proxy instances that the proxy process uses to communicate with proxy connection sub-processes.

Please specify more details as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
In particular, the command lines used and whether you are using encrypted connections or just plain TCP / unix domain.
How many xpra processes are running when you run out of file descriptors?

**Comment by goekce** [comment]
> Please specify more details as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
> In particular, the command lines used and whether you are using encrypted connections or just plain TCP / unix domain.

- I use the default systemd file for the proxy with `TCP_AUTH=pam`, and `AUTH=pam`
- connections are encrypted via `wss`
- using `Xdummy` with DPI patch

> How many xpra processes are running when you run out of file descriptors?

Unfortunately the courses ended and the server does not have many users anymore. So I could not reproduce the issue :(

Feel free to close the issue @totaam. I can reopen it if I can reproduce it again.

**Comment by totaam** [comment]
IIRC, there was another bug report similar to this one which was fixed by running the latest version.
