### ISSUE TITLE
Where is EnvironmentOptions document page?

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra#3184]
I used to check the document here before: https://xpra.org/trac/wiki/Usage/EnvironmentOptions
Now, this webpage is forwarded to github, but I cann't find it on github. It just disappeared.

> We have moved
> This wiki has been moved to ​https://github.com/Xpra-org/xpra/blob/master/docs/README.md and ​https://github.com/Xpra-org/xpra/wiki

**Comment by totaam** [comment]
This page has not been migrated as it was completely out of date and keeping such a page up to date would be far too much work.
