### ISSUE TITLE
Problems in installing xpra in Ubuntu 20.04

### ISSUE THREAD

**Issue by jaeukk** [Xpra-org/xpra#3188]
Hi,

I am a ubuntu 20.04 user and trying to install xpra.
At first, I tried the casual "apt-get (aptitude) install" command to install xpra, but it doesn't work because of some uninstallable dependencies; see the message at the end of this post.

So, I tried to build xpra from source, after installing all pre-required dependencies mentioned in https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md
However, the compilation failed with the following message:
```
xpra/x11/bindings/randr_bindings.c:682:10: fatal error: X11/extensions/randr.h: No such file or directory
 #include "X11/extensions/randr.h"
```
However, `randr.h` DOES exist in `/usr/include/X11/extensions/` directory.

How can I resolve any of these problems?

-------------------------------------
aptitude install message:
-------------------------------------
```
The following packages have unmet dependencies:
 xpra : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
        Depends: libavcodec57 (>= 7:3.4.8) which is a virtual package and is not provided by any available package
 or
                 libavcodec-extra57 (>= 7:3.4.8) which is a virtual package and is not provided by any available package

        Depends: libavformat57 (>= 7:3.4.8) which is a virtual package and is not provided by any available package

        Depends: libavutil55 (>= 7:3.4.8) which is a virtual package and is not provided by any available package

        Depends: libswscale4 (>= 7:3.4.8) which is a virtual package and is not provided by any available package

        Depends: libvpx5 (>= 1.6.0) which is a virtual package and is not provided by any available package

        Depends: libx264-152 which is a virtual package and is not provided by any available package
```

**Comment by totaam** [comment]
> `xpra : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed`

Your xpra repository is misconfigured. Perhaps you're using the one for an earlier Ubuntu version and not focal.
Grabbing the latest version available at time of writing (4.2-r0):
```
dpkg -I xpra_*_amd64.deb | grep Depends
 Depends: python3 (<< 3.9), python3 (>= 3.8~), ...
```
(I've trimmed the output)

As for building from source, I suspect a similar user error.
A misconfigured python3 interpreter or path.
