### ISSUE TITLE
xpra top clients load Menu data?

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3189]
Apart from the monstrous size of the logs (81MB for 40 minutes of execution), and the lack of diagnostics for the `gnome-keyring-daemon --start` (https://github.com/Xpra-org/xpra/issues/3109#issuecomment-872049423), the logs uncovered also this:

```
...
   1523 top client version 4.3-r29319 64-bit
   1524  connected from ' ' as ' ' - ' '
   1525 exec_on_connect_commands() start=[], start_child=[]
   1526 properties(Unity)={'Type': 'Application', 'VersionString': '', 'Name': 'Unity', 'GenericName': '', 'NoDisplay': False, 'Comment': 'This session logs you into Unity', 'Icon': '', 'Hidden': False, 'OnlyShowIn': [], 'NotShowIn': [], 'Exec': '/usr/libexec/run-systemd-session u>
....
```

**Comment by totaam** [comment]
Are you sure this isn't just a timing coincidence?
The menus are not loaded from this code path. I added this to double check:
```
diff --git a/xpra/platform/xposix/xdg_helper.py b/xpra/platform/xposix/xdg_helper.py
index f18ff481e..173c1f3f7 100755
--- a/xpra/platform/xposix/xdg_helper.py
+++ b/xpra/platform/xposix/xdg_helper.py
@@ -198,6 +198,10 @@ def remove_icons(menu_data):
 load_lock = Lock()
 xdg_menu_data = None
 def load_xdg_menu_data(force_reload=False, wait_for_lock=True):
+    try:
+        raise Exception("hello")
+    except:
+        log.error("load_xdg_menu_data", exc_info=True)
     global xdg_menu_data
     if not wait_for_lock and load_lock.locked():
         return xdg_menu_data
```

**Comment by totaam** [comment]
`xpra top` queries `xpra info` which does include the start menu data.

But, this shouldn't be a problem since the menu data is only loaded once.

**Comment by totaam** [comment]
The menu data will only actually be loaded from this code path if you run `xpra top` immediately after starting the server. And usually, it won't actually be loaded from this thread - it will just wait for the initialization thread to finish doing it.

So this isn't a bug.

**Comment by stdedos** [comment]
Okay - good to know.

I failed to mention that - even though I am not sure of the timings you mentioned, the logs are taken with `xpra recover :2 -d exec`, and the `xpra top` client was attached to `:2` before `xpra upgrade` / `xpra recover` (so the `xpra top` client "did something" (kept poking the open servers?).

So these are extended diagnostics.
