### ISSUE TITLE
Ubuntu buildbot failures

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3190]
No idea what's going on, trying to install the build dependencies fails, repeatedly:
```
...
Get:241 http://archive.ubuntu.com/ubuntu bionic/main amd64 python3-magic all 2:0.4.15-1 [9280 B]
Fetched 74.0 MB in 1min 50s (674 kB/s)
Unable to correct missing packages.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-144.148_amd64.deb  404  Not Found [IP: 91.189.88.142 80]
E: Aborting install.
```

So I can't post any new builds.

**Comment by totaam** [comment]
It is working today.
It must have been a transient problem with the mirrors.

---

The bigger issue is that this can happen again and this makes the buildbot unreliable.

**Comment by stdedos** [comment]
> The bigger issue is that this can happen again and this makes the buildbot unreliable.

I know you will not be a fun of it - but how about you clone those packages to your mirror as well?
Or _the bare minimum_ of them.
