### ISSUE TITLE
notifications errors sending svg icons

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3192]
I also digged this up after the upgrade to r29386

```
    389 2021-07-05 10:05:13,072 Error processing notification:
    390 2021-07-05 10:05:13,072  cannot identify image file '~/.local/share/JetBrains/Toolbox/toolbox.svg'
```

**Comment by totaam** [comment]
Transferred because this is not a repository build issue.

The first commit is a bug fix, the next two just try harder to find an icon to use, converting svg to png if that's what we have to do.

**Comment by stdedos** [comment]
> Transferred because this is not a repository build issue.

Oh ooops 😂 Sorry about that!
