### ISSUE TITLE
Visual corruption

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3194]
From https://github.com/Xpra-org/xpra/issues/3187:

> > So, no visual corruption, right?
>
> None that I've seen, no. (I have seen some visual corruption recently, but nothing related to this ticket)

The visual corruption I've seen is this one:
![Xpra_cmd_2021-06-18_14-35-51 - xpra v4 3-r29304 (gc2ba637da)](https://user-images.githubusercontent.com/133706/124804391-ea8f9700-df62-11eb-835b-31234ef31143.png)

Mostly on the shadow, but "a time or two" in the seamless client as well.

If it helps somehow, the corruption looks a green duplicate of the original, with the same top,left corner anchor (0,0) and zoomed in (at the range of 800% - 1600%+)

Server: xpra v4.3-r29304 (c2ba637da)

**Comment by totaam** [comment]
This looks exactly like what I was seeing before f55b6575743882efb61fe394c4d70bf973d21c9d.
(and sure enough c2ba637dabbfba96e91dab4bbe2bf43365e3a3f7 is right between the faulty commit and the fix)
