### ISSUE TITLE
preserve all options when reconnecting

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3207]
Split from #3010.
The way we `parse_display_name` doesn't make it easy to preserve all the options that may be found in the connection string.
As it is now, proxy attributes and anything found after the display part of the URI will be lost when reconnecting.

**Comment by totaam** [comment]
This may also help with ugly hacks like this one: 6c57572a6d6c5b6a2e9e621fbc351eefd41afaa8

**Comment by totaam** [comment]
Done and fixed a re-connection bug.
Tested using:
```shell
xpra start ssh://localhost/?testparam=42 --start=xterm -d ssh
```
Then killing the `_proxy_start` process. The re-connect command line becomes:
```
xpra attach ssh://localhost/2?testparam=42 -d ssh
```
* the display `:2` was added since we knew what display had been allocated,
* `testparam` and `-d ssh` were preserved
* `--start=xterm` was removed

**Comment by Martin-Buchholz** [comment]
> Done and fixed a re-connection bug.

I was trying to debug the same re-connection problem.  Eventually git blame led me to this issue, fixed just days before!  Thanks!
