### ISSUE TITLE
xpra shadow after remote reboot

### ISSUE THREAD

**Issue by thomas725** [Xpra-org/xpra#3210]
I know from https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Shadow-Server.md that 

> On most platforms, the display being shadowed must be active: not locked or turned off.

I was just wondering, is there anything I can do to fix that on my machine, without switching to one of the unknown platforms which are not part of that "most platforms" group? (Besides maybe configuring the server to auto-login on boot, I don't want to make it THAT insecure....)

My server is running xpra v4.2.1-r0 on Linux Mint 20.2.
My client xpra v4.3-r29404 (g116cfdb17) on Manjaro Linux.

Starting directly from client using `xpra -d ssh shadow ssh://server` ends with
```
2021-07-19 15:02:27,551 connection timed out
2021-07-19 15:02:27,563 SSH EOF on stderr of run-xpra
```
When starting on server first to attach client later:
```
xpra --daemon=no shadow
Invalid MIT-MAGIC-COOKIE-1 key (repeated 68023 times with no spaces / new lines in between)
2021-07-19 15:07:12,498 Error: failed to connect to display :0
2021-07-19 15:07:12,499  could not connect to X server on display ':0' after 3 seconds
```

**Comment by totaam** [comment]
Often, `:0` is owned by the display manager which runs as root.
So you can use root to see it: `xpra shadow ssh://root@server/0`

I don't think that there are any other options, sorry.

**Comment by thomas725** [comment]
Running as root doesn't seem to make it work either..
```
root@server:~# xpra --daemon=no shadow :0

Warning: running as root

Warning: running as root
failed to initialize Gtk, no display?
2021-07-19 16:33:08,598 Error: failed to connect to display :0
2021-07-19 16:33:08,598  could not connect to X server on display ':0' after 3 seconds
```

**Comment by totaam** [comment]
> Running as root doesn't seem to make it work either..
> ..
> `failed to initialize Gtk, no display?`

That's probably because the display manager uses a private `XAUTHORITY` file.
Xpra version 4.3 will re-add an `xauth` entry when that's the case, to re-gain access.
Try the beta builds, it should work.

**Comment by thomas725** [comment]
Okey so by using https://xpra.org/repos/focal/xpra-beta.list I upgraded my server to xpra v4.3-r29499 (g27a2d4a97)
My client is on xpra v4.3-r29404 (g116cfdb17) installed through AUR package "xpra-git"

Starting on server for later attachment now looks like this:
```
# xpra --daemon=no shadow :0

Warning: running as root
2021-07-25 09:37:34,057 cannot access python uinput module:
2021-07-25 09:37:34,057  No module named 'uinput'
No protocol specified [[repeated 79.069 times]]
2021-07-25 09:37:37,057 Error: failed to connect to display :0
2021-07-25 09:37:37,058  could not connect to X server on display ':0' after 3 seconds
```

The output when starting directly from client hasn't changed.

**Comment by totaam** [comment]
Sorry for misleading you.
I've just tried all current releases of Fedora, Ubuntu and Debian and they're all using `gdm-wayland` or some other wayland based display manager. I'm not even sure they have a protocol for shadowing the login screen.
Wayland support is in #387

**Comment by thomas725** [comment]
Okey. No problem. From what my htop is telling me, it seems my Linux Mint 20.2 installation is running lightdm:
![image](https://user-images.githubusercontent.com/68635351/126938658-9d9d436c-95b7-4b00-96da-6c5b9384c40e.png)

So at the moment it's not possible, did I understand you correctly? What display managers are supported to shadow the login screen on a fresh boot?

If I login and lock the screen, shadowing does work fine.

**Comment by totaam** [comment]
> So at the moment it's not possible, did I understand you correctly?

Not with wayland based login managers. No.

> What display managers are supported to shadow the login screen on a fresh boot?

Anything X11 based. Some of the login managers can be configured to use X11.

> If I login and lock the screen, shadowing does work fine.

This means you logged in to an X11 session.

**Comment by thomas725** [comment]
Just to make sure I understood the issue correctly:

Most current Linux desktop distributions use a Wayland based login manager, and xpra's Wayland support has not yet progressed far enough, that it could support shadowing such Wayland based login managers. Correct?

**Comment by totaam** [comment]
Correct.
