### ISSUE TITLE
Xpra assumes all Linuxes have `which` installed, resulting in errors when its not

### ISSUE THREAD

**Issue by miojonka** [Xpra-org/xpra#3216]
Xpra currently checks for its own binary when connecting to a server by using `which xpra`. But it does not verify that the program `which` is actually installed (probably because many distributions make part of their base install). 

This causes several problems:
- not every distribution has `which` installed (it is not part of Archlinux base)
- when `which` is not installed, xpra claims that `Xpra is not installed` instead upon connecting
- `which` is not a proper way to find the path to a binary - `command -v` is. (POSIX)

https://github.com/Xpra-org/xpra/pull/3215 should fix this.

**Comment by totaam** [comment]
Out of curiosity, which OS are you running on?
`which` is installed on every distribution that I have used for testing.
Please see https://github.com/Xpra-org/xpra/pull/3215/files#r674875670

**Comment by miojonka** [comment]
I'm running Archlinux (archlinux.org) which does not have `which` installed in it's base package.
