### ISSUE TITLE
Forwarding click events of window title bar

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra#3226]
For an application with popup menu, typically when one click or drag the window title bar, the popup menu should close. But I found it's not the case for the html5 client. Maybe because we didn't forward the clicking event to remote application. 

Similarly, if we have the pop up menu open and now we drag the window, the popup menu should close, maybe we should also send a click event when one drag the window?

<img width="701" alt="Screen Shot 2021-07-28 at 3 25 32 PM" src="https://user-images.githubusercontent.com/478667/127330117-90e260c2-8a0a-4d9e-91cf-68069c5473b7.png">

**Comment by totaam** [comment]
There is no `transient-for` attribute, which is why it wasn't shown.
It doesn't respond to `WM_DELETE_WINDOW` messages. (tested using control commands added in fc03be817f8a442fd7f57f49ebdc19575937867d)

So I'm not going to spend any more time on this.
You may have better luck running with a more up to date openjdk version.

**Comment by oeway** [comment]
@totaam It's a bit unfortunate to see that it cannot be fixed, but I understand. Nevertheless, do you think we can have application-specific fix by hacking the html client? E.g. trigger close window whenever someone clicked in the title bar? If yes, could you please provide some hint.

**Comment by totaam** [comment]
> E.g. trigger close window whenever someone clicked in the title bar?

No, as per my comment above, the application does not respond to `WM_DELETE_WINDOW`.
But your initial suggestion seems to work:
https://github.com/Xpra-org/xpra-html5/commit/92b03d9cfbd2655a004055f0871c5197cc2e3479

And perhaps we should do the same in the python client.
The danger is that the click will land on another window. Perhaps we should change the focus to the root window before sending the fake click.

@oeway does that work for you?

**Comment by oeway** [comment]
Hey, just tried it, dragging can close the menu now, however, if I click in the title bar it doesn't. Maybe we should also do that same when one click in the title bar?

**Comment by totaam** [comment]
> Maybe we should also do that same when one click in the title bar?

I really hope this doesn't cause regressions somewhere else:
https://github.com/Xpra-org/xpra-html5/commit/3f73f769a2ae057a3bcbc1fd1876427393a01caf

Please close this ticket if that works for you.

**Comment by oeway** [comment]
It works! Thanks!
