### ISSUE TITLE
Provide a conda package

### ISSUE THREAD

**Issue by oeway** [Xpra-org/xpra#3231]
Is it possible to make xpra conda package? E.g. provide it via conda-forge. It looks like most of the dependent packages are already available in  conda, do you any obvious obstacles?

**Comment by totaam** [comment]
It might be possible but packaging is **hard** and this would not work on MS Windows or MacOS.
As for Linux, I very much doubt that you can achieve the same level of OS integration that you can get from native packages.

**Comment by taranu** [comment]
FYI, @erykoff kindly provided a Linux conda-forge recipe at https://github.com/conda-forge/xpra-feedstock, although he is having some problems upgrading from 3.3.4 to 3.4.1 (something similar to #3360, it seems).

**Comment by totaam** [comment]
Without details, it's impossible for me to help.
Had a quick look at the recipe and there is at least one mistake in there: `x265` should not be used: it is normally disabled by default unless explicitly enabled.
Also, `conda` doesn't seem to have _recommends_ vs _suggests_ vs straight dependencies so the list of dependencies is always going to be arbitrary.

**Comment by erykoff** [comment]
As for this particular problem, it was just that I needed to explicitly include the centos7 system libraries, so that's fine.  Re: x265, are you saying that this isn't being used at all (unless I were to change a flag or something somewhere?).  If so, I can remove it.
