### ISSUE TITLE
OpenGL without GPU

### ISSUE THREAD

**Issue by rvvincelli** [Xpra-org/xpra#3235]
Hi!

First of all thanks a lot for this project, it gave a second life to my venerand linux box and the idea of a screen for X is really cool.

My GPU died today unfortunately, and I've deactivated it at boot time by following [this](https://apple.stackexchange.com/questions/166876/macbook-pro-how-to-disable-discrete-gpu-permanently-from-efi) wonderful walkthrough.

I'm on macOS Catalina, `Darwin sanctuspetrus-3.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64 x86_64`. Cutting out the discrete card like that comes with a few drawbacks, even the _About this Mac_ menu will cause a freeze.

And if I give my usual command `xpra start ssh://???@???/ --start-child=xterm --start-child=xterm` it freezes too, I have to add an explicit `--opengl=no`. It might be obvious or just out of xpra's reach but I mention this just to be sure.

Thanks again,

**Comment by totaam** [comment]
Please post the output of `Xpra opengl` so we can blacklist this particular driver / version.
I use the software opengl renderer regularly without issues.

**Comment by rvvincelli** [comment]
Hi @totaam , thanks for your prompt answer. I am sure it is not an issue with the OpenGL support because I've always used it myself, and it is not a driver issue either. This just happens because I've disabled the discrete GPU following the steps linked above, so it is not a standard setup so to say. Since it does not ring any bell and there're more important issues, I'll close it.

**Comment by totaam** [comment]
With the `xpra opengl` output, we may be able to detect the specific combination that causes the problem.

**Comment by rvvincelli** [comment]
Eliciting the behavior for the log means crashing the mac and starting the PRAM reset keys dance. I might have some time to try it out in the coming days but I cannot promise you so :/ Thanks,

**Comment by totaam** [comment]
Wow. That's a proper crash then!
Perhaps `xpra opengl` won't actually trigger it.

This should be reported to Apple too - no user space application should be able to have that effect.
