### ISSUE TITLE
Can't run start command on Windows

### ISSUE THREAD

**Issue by ZvonimirMatic** [Xpra-org/xpra#3236]
I installed xpra on Windows and tried to run `xpra start --start=notepad --bind-tcp=0.0.0.0:10000`. I got the following error:

```
xpra initialization error:
 start is not supported by this local installation
```

The same error appears when I try to just run `xpra start`. I tried installing xpra with EXE installer, MSI installer and I also tried just downloading ZIP file, but every method results in same error. I tried installing xpra by cloning the repository and running setup.py, but I get an error related to MinGW (MINGW_PREFIX). I haven't tried running this on another OS.

**Comment by ZvonimirMatic** [comment]
@totaam Oh, I didn't see that anywhere. I am trying to run a Windows desktop application in the web browser. The idea was to do it using xpra similar to this (but without docker):
https://youtu.be/a5bDdN082No

Obviously the xpra start runs inside linux docker image in this example so it works. Do you think it is possible to do something similar to run Windows application?

**Comment by totaam** [comment]
On MS Windows, your options are much more limited. Microsoft is not sharing the secret sauce that would allow us to implement the feature.

You can run xpra in shadow mode and then access the whole desktop through your browser.
