### ISSUE TITLE
Screen crash

### ISSUE THREAD

**Issue by crwagn** [Xpra-org/xpra#3238]
As soon as I open Xpra on my desktop, I get the usual screen asking what type I am trying to open. However, after selecting Shadow or opening the options menu of start session, I have about 30 seconds before my GPU fans ramp up, and my screens go rainbow static. If I wait a moment, my mouse returns to visible, but no amount of playing around returns the screen. If I change to a terminal environment, restart the desktop environment, try to Alt+F4 the program, nothing fixes the screen. It seems the computer still works, as I can move the mouse, and see the screen flicker if I do a desktop environment reset, but it never comes back until I reset or power cycle the computer.

I never saw this happen on my laptop with xpra. nor ever on my desktop before now.

OS: Manjaro Linux, Kernel 5.13.11, Cinnamon DE, AMDGPU drivers

Hardware: AMD 1950X Threadripper, 64GB DDR4, MSI Radeon RX580 8GB, 2x 1080p60 monitors

Laptop has an Intel CPU and nVidia GPU, if that helps. Usually running one screen.

It is very reproducible. No limit on how long the computer has been running nor other tasks running.

Thanks for the software, I hope to get it running and tested for regular usage soon!

**Comment by totaam** [comment]
There's something wrong with your GPU drivers. Try `--opengl=no`.
If that doesn't help, please try running xpra from the command line with `-d all` and post the last few dozen lines from the output.

**Comment by crwagn** [comment]
Hey @totaam, thanks for the help, but the --opengl=no didn't work, as soon as the gui launches I have about 30 seconds before things go nuclear. 

I ended up saving the output of your second command to a file so that it was sendable after the freeze. Also to note, during the freezes and after restarts the fan on the gpu kicks on, which never normally happens (one of the no spin style gpus).

Here is the output from the -d all command
[log.txt](https://github.com/Xpra-org/xpra/files/7024782/log.txt)

**Comment by totaam** [comment]
You just launched `xpra start-gui`, I meant starting whatever command you use xpra for.
Like `xpra attach` or `xpra start`.
BTW, which xpra version is this?

**Comment by totaam** [comment]
> .. after selecting Shadow

So that would be: `xpra shadow -d all`

**Comment by crwagn** [comment]
Xpra 4.2-1 is what the repo says.

And I just hit the icon in the menu originally, and the crash happens from the gui launch, I dont get to/have to do anything before the visual crash happens. I have started shadow session, and started into the start menu of the gui to start xpra, but the crash happens before I can set anything up. So there is no specific way running xpra that causes it, it's usually not even running beyond the gui start when the crash happens.

For additional testing, I launched the xpra start and it happened about 15 seconds later. Do you want me to run the -d all with that start as well?

**Comment by totaam** [comment]
> Xpra 4.2-1 is what the repo says.

That's two full releases behind...

> For additional testing, I launched the xpra start and it happened about 15 seconds later.
> Do you want me to run the -d all with that start as well?

Yes please, try:
```
xpra start --no-daemon --start=xterm --splash=no >& log
```
And we'll see what the last few hundred messages are in that log.
(try with and without the splash option)

**Comment by crwagn** [comment]
I cannot save anything from the output. 

But, it says a log is being saved, then tells me shadow is running, then the system does the rainbow pixel vomit all over the screens stopping me from doing anything but moving a mouse around on the broken screens, I cannot seemingly interact with anything. 

It seems to stop all memory processes though, because it doesnt finish saving any of the processes going. So it doesnt fill the file, nor allow me to find the log it said would be made.

**Comment by crwagn** [comment]
Okay, with --splash=no

[log.txt](https://github.com/Xpra-org/xpra/files/7024829/log.txt)

**Comment by totaam** [comment]
> Okay, with --splash=no

Did it still crash? If so, please add `-d all`.

> then the system does the rainbow pixel vomit all over the screens stopping me from doing anything

Again, that's not something an application should be able to do.
It points to a kernel or GPU bug, not an xpra bug.

Since you're running an outdated version, perhaps this will help:
```
XPRA_VAAPI=0 xpra start --video-encoders=none
```
(or you can try with `shadow` instead of `start`)

**Comment by crwagn** [comment]
Okay, without  --splash=no
[log.txt](https://github.com/Xpra-org/xpra/files/7024833/log.txt)


> Did it still crash? If so, please add `-d all`.

Yes it did.
 
> Again, that's not something an application should be able to do.
> It points to a kernel or GPU bug, not an xpra bug.

I agree, just figured it must be a crazy segfault, since nothing but the mouse works afterward
 
> Since you're running an outdated version, perhaps this will help:
> 
> ```
> XPRA_VAAPI=0 xpra start --video-encoders=none
> ```

I'll give that a shot too. Or just pull from the github and see if it still happens on a more recent version...

**Comment by crwagn** [comment]
Here is the -d all added log. going to get the git version now and see if I have the same issues.
[log.txt](https://github.com/Xpra-org/xpra/files/7024846/log.txt)

Thanks for all the help so far!

**Comment by crwagn** [comment]
So, even with the up to date git version, I am having the same issue.

**Comment by totaam** [comment]
Ah! The last entry in your log sample is `load_icon_from_file`, so this problem could just be the same as #3142.
Can you try starting your server with `--start-new-commands=no` or apply 01a1cd12d551f5cfb80d274a2dad74f8ca932a2f and run with:
```
XPRA_SVG_TO_PNG=0 xpra start --start=xterm --no-daemon >& log
```

**Comment by totaam** [comment]
Oh, and BTW, you're not running master in that log sample, you're running 4.2 which has this known bug.
Si I will probably close this ticket as invalid. I'm pretty sure the problem does not occur with master.

**Comment by totaam** [comment]
Not heard back.
