### ISSUE TITLE
find_libfakeXinerama find_lib fallback is broken

### ISSUE THREAD

**Issue by chewi** [Xpra-org/xpra#3239]
`find_libfakeXinerama` calls `find_lib` if the ldconfig-based method does not work. However, it literally looks for a file called `fakeXinerama` rather than `libfakeXinerama.so`, which is obviously wrong.

**Comment by totaam** [comment]
FWIW: doesn't the ctypes variant find the library on your system?
```
from ctypes.util import find_library
find_library("fakeXinerama")
```

This was made worse by the fact that the `ldconfig` variant had a bug.
Note: this code should only be used when building from source. Packages should ship with the correct value in the on-disk config.

**Comment by chewi** [comment]
It would but Gentoo has been patching out most of `find_libfakeXinerama` to jump straight to the fallback. I'm about to package libfakeXinerama now but we previously weren't. It was therefore falling through to the `ldconfig` call and this was triggering our build sandbox that prevents writes outside the build area. This shouldn't have happened with the `-p` argument but, as you've just found, that wasn't being passed properly. Thanks for fixing our problem without even realising it!

**Comment by totaam** [comment]
> It would but Gentoo has been patching out...

The number of times downstream distros do questionable things without ever consulting with us is staggering.

**Comment by chewi** [comment]
Heh, don't look at me, I wasn't maintaining it at that time. It feels like finding this path shouldn't be as hard as it is.

**Comment by totaam** [comment]
> Heh, don't look at me..

I wasn't, sorry. Just a general comment.

> It feels like finding this path shouldn't be as hard as it is.

Indeed, that's why we only do it once at build time is possible.
