### ISSUE TITLE
Clarity on local sessions in Mac OS

### ISSUE THREAD

**Issue by hoopahmadness** [Xpra-org/xpra#3240]
I've installed xpra on a Mac and on Linux, with the hope of running some apps from my Mac remotely on my linux machine. However, I've gotten this output when trying to start a session remotely:

"this xpra installation does not support starting local servers"

and when using the xpra GUI directly on the mac I see a tooltip saying "Cannot start local desktop or seamless sessions on Mac OS X"

I don't see anything in documentation about this limitation, nor have I been able to find anyone talking about it after searching around online. Therefore I can't help but wonder if I'm missing something. I find it hard to believe that such a large limitation would be summed up in a tooltip.

**Comment by totaam** [comment]
Sorry, seamless sessions are not available on MacOS as they require X11 applications.

**Comment by hoopahmadness** [comment]
Thank you. That was my fear :( Otherwise the software is really cool!  Wish I could make use of it.
