### ISSUE TITLE
Chromebook Chrome OS browser fails to connect to session

### ISSUE THREAD

**Issue by pfortier** [Xpra-org/xpra#3241]
I can connect from the chrome browser of a linux laptop (xubuntu) but I cannot connect using the chrome browser in a chromebook (uses chrome os).

The following works from a xubuntu laptop connecting to myserver with xpra.
[terminal] ssh -L 8003:localhost:5901 me@myserver
[terminal] xpra start --bind-tcp=0.0.0.0:5901 --html=on --start-child=xterm
[chrome browser] localhost:8003

**Comment by totaam** [comment]
Are you sure the port is open?
Does the server log show a connection attempt?
What is the error in your chrome browser?

FYI: this may be the wrong repository if the bug is in the html5 client.

**Comment by pfortier** [comment]
RE: Are you sure the port is open? 
1. On the server I run "xpra start --bind-tcp=0.0.0.0:5901 --html=on --start-child=xterm" and leave it running
2. I can connect from the chrome browser of a linux laptop (xubuntu) and see xterm and the applications menus by using
  [terminal] ssh -L 8003:localhost:5901 me@myserver
  [browser] localhost:8003 
3. then I close this browser and open up my chromebook and make the same connection but there's no xterm and no menu items

RE: Does the server log show a connection attempt? I didn't check
What is the error in your chrome browser? There's no error mentioned.

It works on chrome in xubuntu but not on chrome in chromeOS (chromebook). I would guess it's a chromebook issue.

Thanks
P.S. I will just use the xubuntu laptop.

**Comment by totaam** [comment]
Check your server log, chances are there will be an error in there.
I don't have a chromebook so the chances of this bug getting fixed are slim.

**Comment by s15y** [comment]
This is not strictly a chromeos issue, but apparently a ERR_UNSAFE_PORT issue that could arise on other platforms.
See also https://bugs.chromium.org/p/chromium/issues/detail?id=246595

A workaround can be to launch the server on a "safe" port (tested with 443), but this has the drawback of needing admin rights to use below-1024 port, and --min-port option.
Could not find how to use --explicitly-allowed-ports for chrome on chromeos.
There are probably better workarounds.

It is not clear if ERR_UNSAFE_PORT comes from a global chromeos configuration or if it is specific to the browser (chromeos support many browsers through android and linux/crostini).

**Comment by s15y** [comment]
> There are probably better workarounds.

It seems only some ports are restricted:
https://source.chromium.org/chromium/chromium/src/+/main:net/base/port_util.cc;l=56

Tested ok with 7000 (was not working previously with 6000).

Not sure why this could not work on 5901, though because this is not in  kRestrictedPorts.

**Comment by totaam** [comment]
Thanks for the investigation.
So I am closing this issue because there is nothing xpra can do here.
This is a chrome os "feature".
