### ISSUE TITLE
Slash keyboard / (SHIFT + 7) mapped to Question Mark (?).

### ISSUE THREAD

**Issue by TommasoBendinelli** [Xpra-org/xpra#3253]
Hi, 
Keyboard mapping is wrong for a multiple keys. Most important / is remapped to ?
I am running xpra with:
`xpra start ssh://tommaso@T7144 --start=xterm`

**Comment by totaam** [comment]
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
Not heard back.
