### ISSUE TITLE
Any window without title bar can't move and resize

### ISSUE THREAD

**Issue by julee** [Xpra-org/xpra#3269]
Any linux application, start with xpra client on Windows, cannot move and resize.
Such as almost all gnome3 applications : Files, Text Editor ...

![image](https://user-images.githubusercontent.com/1493342/133719670-79ada0b0-a6d5-4288-893e-92cdb50a0104.png)

version info:
![image](https://user-images.githubusercontent.com/1493342/133719765-895650d4-d4db-49c3-b961-8fc28c5a500f.png)

**Comment by totaam** [comment]
Please use a supported version on the server, 3.0.6 is too old and buggy.

If you can reproduce the bug with a supported version, you can re-open this issue.

**Comment by julee** [comment]
> Please use a supported version on the server, 3.0.6 is too old and buggy.
> 
> If you can reproduce the bug with a supported version, you can re-open this issue.

Yeah, after upgrade to 4.2.2, no this bug now.
Thanks.
