### ISSUE TITLE
`Error: clipboard request for 'PRIMARY' (no proxy, ignored)` on middle-click with client `r30012` / `r30040` against `r29944` server

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3273]
When upgrading client from `r30012` to `r30040`, with server at `r29944`/`r30040` (Ubuntu 20.04, https://github.com/Xpra-org/xpra/issues/3267#issuecomment-922777828), I noticed that middle-click from/to server (no need to involve the client's environment), instead of doing the expected action, instead gives: 

```
Error: clipboard request for 'PRIMARY' (no proxy, ignored)
```
continuously, and without copy/pasting the selection.

**Comment by totaam** [comment]
I believe this bug is not new as I have seen it before. It never caused any problems though.
And it may be that simply re-setting the selection makes it go away.

MS Windows clients - which is what I believe you are using - do not synchronize the `PRIMARY` selection at all (unless specifically requested) and therefore no packets should ever be sent to the client.

**Comment by totaam** [comment]
Dang. I saw the bug just now, it was easily reproducible so I decided to test / fix some other bug first.
Now that I am back to this one, I cannot reproduce it any more at all!
Do you have specific steps that would help?

**Comment by stdedos** [comment]
Nothing specific 😕

However, due to the circumstances of #3274, everything was tried on new/empty servers too.
No much happy news though: The server was at `r30040` (_but might require `r29944` for some reason_), and client at `r30012` or `r30040` (or maybe `r29944`)

Command line was:
```
"Xpra-Python3-x86_64_4.3-r30012\xpra_cmd" start ssh://usr-linux@1.1.1.1/5 --ssh="plink -ssh -agent" -d ssh --title="@title@ on @@/@server-display@" --modal-windows=no --headerbar=off --use-display=yes --input-method=xim --csc-modules=libyuv --start=gnome-terminal
```
(it's a little mocked - YMMV).

Start the `gnome-terminal`, and find some text to middle-click-copy.

**Comment by totaam** [comment]
The best I could come up with is the commit above.
We try harder not to make the server side claim clipboard selections that we don't handle. (only one clipboard selection at a time on MS Windows) - this should help in preventing the clipboard from getting wedged.
I just wished I was still able to reproduce the problem, then I could have verified that this fixes things.

**Comment by stdedos** [comment]
Why not promote logs to info? 
We could continue debugging if that happens to come up again. 

My workstation is a bit thrashed at the moment - expect silence from testing 😕

**Comment by totaam** [comment]
> Why not promote logs to info?

If I did that every time there's an unsolved issue... we would never be able to see anything!

**Comment by totaam** [comment]
Is this still an issue with post f36cff6 builds?

**Comment by stdedos** [comment]
I think I have updated/used xpra since "Tue, 21 Sep 2021 18:03:44 +0700", and therefore I'll hazard a guess saying that it's fixed
