### ISSUE TITLE
Different information between server and client

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3278]
From/To the same Client/Server (Ubuntu 20.04.3), the information provided is slightly different:
![Screenshot from 2021-09-22 20-07-57](https://user-images.githubusercontent.com/133706/134467687-a185abd8-9254-4327-99ff-5f488d2a3b04.png)

Also: is it possible / does it make sense e.g. for the server to be OpenGL-accelerated, but the client to not be?
Does it work?

If so - how can I see, from the client, whether the Server is OpenGL-accelerated or not?
_Especially_ when the client is not.

**Comment by totaam** [comment]
> Also: is it possible / does it make sense e.g. for the server to be OpenGL-accelerated, but the client to not be?

The two things are completely independent and unrelated:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/OpenGL.md
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Client-OpenGL.md

Summary:
* the server opengl may be used by X11 applications to render things
* the client opengl is used to paint the screen faster

> If so - how can I see, from the client, whether the Server is OpenGL-accelerated or not?

Session info is a good place to start.
Or you can run tools like `glxinfo`.

**Comment by stdedos** [comment]
From your previous commit, there also seems to be missing GStreamer, pygst, and Cairo version has a different representation. 

> Session info is a good place to start.

I meant - where exactly? 

"I have been in a situation" where the OpenGL was reported as disabled server-side, but I could not verify it client-side. 

On the Features tab, there is a big fat checkbox saying "Client OpenGL: - disabled by configuration".

**Comment by totaam** [comment]
> From your previous commit, there also seems to be missing GStreamer, pygst

I'm not seeing this problem here, could be a packaging issue. I will check it.

> and Cairo version has a different representation.

That's fixed by c5ef1bd7ce56eb145bca57c6d76115f428b0292c

> "I have been in a situation" where the OpenGL was reported as disabled server-side

Reported where?
> but I could not verify it client-side.

It may or may not show up correctly in session info. If it doesn't, it could still be enabled server side anyway.
ie: you can always run `vglrun glxgears` to get accelerated opengl, and the xpra server has no way of knowing about it.

> On the Features tab, there is a big fat checkbox saying "Client OpenGL: - disabled by configuration".

Don't you disable opengl because of an Intel GPU?
Or perhaps it is blacklisted? In any case, the client's `-d opengl` should tell all.

**Comment by stdedos** [comment]
> > "I have been in a situation" where the OpenGL was reported as disabled server-side
> 
> Reported where?

I didn't report it, as it involved VMWare, and also sometimes I start the client with `xpra start --opengl=no`, which I think forwards `--opengl=no` to server too. [1]
(I might have tried mitigations, like `xpra upgrade` without `--opengl=no` from the server-side, but to no avail)

> > On the Features tab, there is a big fat checkbox saying "Client OpenGL: - disabled by configuration".
> 
> Don't you disable opengl because of an Intel GPU?

Indeed - but I don't want that necessarily to mean that server does not have OpenGL if it can sustain it (I am aware of [1], and _that_ is my fault if it is indeed the case)

**Comment by totaam** [comment]
> I might have tried mitigations, like xpra upgrade without --opengl=no from the server-side, but to no avail

The new and improved `upgrade` subcommand reloads the previous server configuration and will apply any previous command line switches unless specifically overriden. So `xpra upgrade --opengl=yes` should do what you want and re-enable the `opengl` flag it if it had been disabled by your `xpra start` command line.

Just be aware that this only affects whether or not the xpra server will probe the opengl characteristics of the vfb it connects to. (it just runs `xpra opengl` in a subcommand)
It doesn't actually enable anything.

> I don't want that necessarily to mean that server does not have OpenGL if it can sustain it

As per above, this only affects xpra's probing of opengl, not opengl support itself, which doesn't depend on anything in xpra.

**Comment by stdedos** [comment]
> It doesn't actually enable anything.

In other words ... xpra will always be OpenGL-accelerated if possible? 😕

**Comment by totaam** [comment]
> In other words ... xpra will always be OpenGL-accelerated if possible?

On the server, no.
There is nothing in xpra that uses OpenGL server-side.

Only the client can use OpenGL to render screen updates faster.

**Comment by stdedos** [comment]
Ah - so if _something_ demands OpenGL, it cannot happen inside an xpra display

**Comment by totaam** [comment]
> Ah - so if something demands OpenGL, it cannot happen inside an xpra display

It can, as per:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/OpenGL.md

**Comment by stdedos** [comment]
> > by trying to access `DISPLAY=:0` for some reason
> 
> AFAIK, that's the default display it tries to get an OpenGL context from. If you want to use a different one then you have to specify it.

I did from `gnome-terminal`: `DISPLAY=:2 vglrun env DISPLAY=:2 glxgears` (inside `DISPLAY :2`)
No dice 😕 

But anyway maybe it's me

**Comment by totaam** [comment]
> But anyway maybe it's me

I think it is.

> `DISPLAY=:2 vglrun env DISPLAY=:2 glxgears`

This just looks wrong.
Why are you specifying `DISPLAY` twice? Isn't this already running from `$DISPLAY`? If not, why not?
And why aren't you specifying the accelerated display that `vglrun` should be connecting to?
ie something like this from a session running on `:2`:
```shell
vglrun -d :1 glxgears
```

**Comment by stdedos** [comment]
> > But anyway maybe it's me
> 
> I think it is.
> 
> > `DISPLAY=:2 vglrun env DISPLAY=:2 glxgears`
> 
> This just looks wrong. Why are you specifying `DISPLAY` twice? Isn't this already running from `$DISPLAY`? If not, why not? [...]

Because:

```
$ vglrun glxgears
Invalid MIT-MAGIC-COOKIE-1 key[VGL] ERROR: Could not open display :0.

And I thought the solution was to "force-identify" `DISPLAY`

> And why aren't you specifying the accelerated display that `vglrun` should be connecting to? ie something like this from a session running on `:2`:
> 
> ```shell
> vglrun -d :1 glxgears
> ```

🤯 because I didn't know I had to
```
$ vglrun -d :1 glxgears
7 frames in 5.0 seconds =  1.397 FPS
5 frames in 5.0 seconds =  1.000 FPS
6 frames in 6.0 seconds =  1.000 FPS
[VGL] ERROR: in readback--
[VGL]    269: Window has been deleted by window manager
```
At least it "renders" 😛 

Thank you 🙂
