### ISSUE TITLE
Apparently harmless messages at reconnection about Network Tools icon

### ISSUE THREAD

**Issue by fpoto** [Xpra-org/xpra#3279]
[bug.zip](https://github.com/Xpra-org/xpra/files/7217705/bug.zip)
Description: 
On the client side, at every reconnection I see:
```
2021-09-23 12:28:44,122 Error: failed to load icon data for 'Network Tools':
2021-09-23 12:28:44,123  rsvg-error-quark: XML parse error: error code=99 (3) in (null):10:72: xmlns:sodipodi: 'http://inkscape.sourceforge.net/DTD/s odipodi-0.dtd' is not a valid URI
 (0)
2021-09-23 12:28:44,123  data=b'<?xml version="1.0" encoding="UTF-8" standalon ..  z "\n       id="rect3988" />\n  </g>\n</svg>\n'
2021-09-23 12:28:44,123 Error: failed to load icon data for Network Tools
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/menu_helper.py", line 118, in get_appimage
    img = open_only(icondata)
  File "/usr/lib/python3/dist-packages/xpra/codecs/pillow/decoder.py", line 72, in open_only
    raise Exception("invalid data: %s, not recognized as %s, header: %s" % (
Exception: invalid data: unknown, not recognized as png, jpeg, webp, header: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822207374616e64616c6f6e653d226e6f223f3e0a3c212d2d2043726561
2021-09-23 12:28:44,124  data=b'<?xml version="1.0" encoding="UTF-8" standalon ..  z "\n       id="rect3988" />\n  </g>\n</svg>\n'
```
I can provide any additional info on request

**Comment by basilgello** [comment]
I think we'll need the actual XML / SVG file. Probably ther is an extra whitespace in `http://inkscape.sourceforge.net/DTD/s odipodi-0.dtd`

Apart from that, should bug.zip consist sensitive stuff like hostname, username, user full name and full ENV block in `System.txt` @totaam ?

**Comment by basilgello** [comment]
Also since it is Debian bookworm and it is Inkscape icon causing the issue, fyi @mapreri

**Comment by totaam** [comment]
Here is the full stacktrace from the bug report zip file:
```
loaded 24 start menu entries from 4 sub-menus in 49.4 seconds
client   1 @02.792 Error: failed to load icon data for 'Network Tools':
client   1 @02.792  rsvg-error-quark: XML parse error: error code=99 (3) in (null):10:72: xmlns:sodipodi: 'http://inkscape.sourceforge.net/DTD/s odipodi-0.dtd' is not a valid URI
client   1 @02.792  (0)
client   1 @02.793  data=b'<?xml version="1.0" encoding="UTF-8" standalon ..  z "\n       id="rect3988" />\n  </g>\n</svg>\n'
client   1 @02.793 Error: failed to load icon data for Network Tools
client   1 @02.793   File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/menu_helper.py", line 118, in get_appimage
client   1 @02.793     img = open_only(icondata)
client   1 @02.793   File "/usr/lib/python3/dist-packages/xpra/codecs/pillow/decoder.py", line 72, in open_only
client   1 @02.793     raise Exception("invalid data: %s, not recognized as %s, header: %s" % (
client   1 @02.793 Exception: invalid data: unknown, not recognized as png, jpeg, webp, header: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822207374616e64616c6f6e653d226e
6f223f3e0a3c212d2d2043726561
client   1 @02.797  data=b'<?xml version="1.0" encoding="UTF-8" standalon ..  z "\n       id="rect3988" />\n  </g>\n</svg>\n'
```
So, rsvg fails to load the application icon and then we try again with pillow and it also fails with a slightly different error message.
It is an icon from `inkscape` and this is not the first time that we have hit problems with it:
https://github.com/Xpra-org/xpra/issues/2978#issuecomment-765553664
The commit above re-uses the same regular expression to detect broken inkscape icons and tries again after patching the XML.
@fpoto does that work for you?

Servers may convert svg icons to png before sending, but not on Debian: https://github.com/Xpra-org/xpra/issues/3268#issuecomment-919955633

---

BTW:
> `loaded 24 start menu entries from 4 sub-menus in 49.4 seconds`

That's very very slow!
You can make your server startup much more quickly with either `--start-new-commands=no` or `--env=XPRA_XDG_LOAD_GLOB=0`.

**Comment by fpoto** [comment]
Sorry, I am quite busy these days. I can try things out, but I need step-by-step instructions. I tried to understand what should work for me but I could not... If I need to modify a file, I can do that, but I should know which file and how.

**Comment by fpoto** [comment]
> It is an icon from `inkscape` and this is not the first time that we have hit problems with it:
> [#2978 (comment)](https://github.com/Xpra-org/xpra/issues/2978#issuecomment-765553664)
> The commit above re-uses the same regular expression to detect broken inkscape icons and tries again after patching the XML.
> @fpoto does that work for you?

Sorry, I am quite busy these days. I can try things out, but I need step-by-step instructions. I tried to understand what should work for me but I could not... If I need to modify a file, I can do that, but I should know which file and how.

**Comment by fpoto** [comment]
> > `loaded 24 start menu entries from 4 sub-menus in 49.4 seconds`
> 
> That's very very slow!
> You can make your server startup much more quickly with either `--start-new-commands=no` or `-- env=XPRA_XDG_LOAD_GLOB=0`.

Mh, thanks, but I in fact ask the server to start a command, so the first one is not possible. What does the second one do?

**Comment by basilgello** [comment]
> If I need to modify a file, I can do that, but I should know which file and how.

Easy! As root:

```
wget https://raw.githubusercontent.com/Xpra-org/xpra/master/xpra/client/gtk_base/menu_helper.py -O /usr/lib/python3/dist-packages/xpra/client/gtk_base/menu_helper.py
```

and start your servers again.

**Comment by fpoto** [comment]
> `wget https://raw.githubusercontent.com/Xpra-org/xpra/master/xpra/client/gtk_base/menu_helper.py -O /usr/lib/python3/dist-packages/xpra/client/gtk_base/menu_helper.py`

Ok, patched on both the server and client, restarted, the error is there no more. Thanks

**Comment by basilgello** [comment]
This is rsvg file parser error. It needs to be debugged separately. But do the actual icons get displayed?

**Comment by totaam** [comment]
> Mh, thanks, but I in fact ask the server to start a command, so the first one is not possible.

It is. It only prevents **new** commands from being started in this session from the client's start command tray menu **later**.
This does not affect any of the `--start=` command line options.

> What does the second one do?

It turns off the _"try harder"_ version of the icon loading code, which uses large wildcard globs to try to locate a valid icon for all the start menu categories and commands. It is particularly costly on spinning disks, less so on SSDs.
This is usually responsible of over 90% of the startup delay cost.

> and I do not understand why ever Inkscape is involved...

I believe that's because the problematic icon was created or saved using inkscape.

> Where should I look to check for missing or bad icons?

Based on your server log:
> `failed to load icon data for 'Network Tools':`

My guess is that this is the "Network Tools" start menu category.

---

I'm closing this ticket because the warnings are gone.

**Comment by fpoto** [comment]
Wow.  I had never noticed the Start tray menu...

I understand why it can cause startup delays, thanks.  I now see that
several icons in the menu are missing, among them the Network Tools one.

I did some quick tests.

- I shut sown the Xpra server and kill the X server
- I use the same script as above, without any of the options you suggested
- Startup time is ~8s until the message "audio playback using 'opus' audio codec"
- I shut down the Xpra server
I get these messages:

2021-09-24 08:34:09,867 SSH EOF on stderr of run-xpra
2021-09-24 08:34:09,874 removing unix domain socket '/run/user/1000/xpra/clients/pot-759161'
2021-09-24 08:34:09,875 audio playback stopping
2021-09-24 08:34:09,876 trying to re-connect to the notification service
2021-09-24 08:34:09,948 Error processing notification:
2021-09-24 08:34:09,948  org.freedesktop.DBus.Error.ServiceUnknown: The name :1.2590 was not provided by any .service files
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1680: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
2021-09-24 08:34:09,952 Connection lost
  
- I restart the server, still using the script above
- Startup time is ~6s
- ~10s later I see the message "Error: failed to load icon data for 'Network Tools'"

- I disconnect from the server
- I reconnect, still using the script above
- Startup time is ~3s
- I immediately see the error message about the icon

So, in practice, the delay while creating the menu entries is invisible
to me, as it happens in the background after my windows have been shown.
The only effect is that the Start menu is not populated for a while
after the server is first launched.

Thank you for your work on Xpra!

-- 
Francesco Potortì (ricercatore)        Voice:  +39.050.621.3058
ISTI - Area della ricerca CNR          Mobile: +39.348.8283.107
via G. Moruzzi 1, I-56124 Pisa         Skype:  wnlabisti
(gate 20, 1st floor, room C71)         Web:    http://fly.isti.cnr.it
