### ISSUE TITLE
yet another install glitch

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3280]
```
Package xpra-html5-4.5.1-1.r1046.el8.noarch.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

```

**Comment by totaam** [comment]
Thanks for the heads up. I've signed them and pushed to the repo.

You may need to `dnf clean packages` before `dnf update`.

Sorry, I still don't know why this happens occasionally... otherwise I would fix it!
