### ISSUE TITLE
Add direct mention of the presence or absence of NAT Passthrough

### ISSUE THREAD

**Issue by Korb** [Xpra-org/xpra#3282]
I suggest adding an indication to [the main site](https://xpra.org/) and to [the wiki](https://github.com/Xpra-org/xpra/wiki), is it possible with this application to connect two computers located in different local networks, without VPN and port forwarding on routers?

**Comment by totaam** [comment]
I'm sorry but if we have to list every feature that is not present, it will take forever.
Feel free to submit a PR though.
