### ISSUE TITLE
Connection dropping when system busy

### ISSUE THREAD

**Issue by fpoto** [Xpra-org/xpra#3285]
I typically keep both an Xpra and a Screen connection open from home to office. Often at night the xpra client disconnects, (ping timoeut) while the screen connection stays up. Finally I investigated and discovered that often the btrfs check process that I call at night backup time eats up a scary amount of memory and triggers the oom_killer several times. While it does not kill Xpra (going after skypeforlinux instead), I strongly suspect that it almost freezes the system for some time, so xpra's ping timeout expires.

I see that I could easily increase the timeout, but maybe something better should be done. If for example the timeout handler detects a high load average it could just wait some more time.
I see that there are some logging facilities embedded into the source, but I could not easily sort them out:
 - the man page mentions "all" as an argument to --debug but does not explain what are the other filters available, nor could I find hints in the source
 - the man page mentions that the server uses ~/.xpra for its log files, but says nothing about the client
 - I understand that the client can send its logs to the server, but that would be useless in this case because network connection is unstable or absent

So: can I have the client log something locally?

**Comment by totaam** [comment]
> I see that I could easily increase the timeout, but maybe something better should be done.
> If for example the timeout handler detects a high load average it could just wait some more time

I think that this is a better solution: #3010

> .. but does not explain what are the other filters available ..

We have a whole documentation page dedicated to logging:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Logging.md
And this is shipped with the Linux packages, usually under `/usr/share/doc/xpra`.
I have also added some more information to the man page: e463cf3ff4570aac64929ccee8a6ab46ef49f897

> but says nothing about the client

It depends on how you run the client.
Most subcommands, including `xpra attach` simply write to `stdout`. You can redirect it to a file.

**Comment by fpoto** [comment]
Thanks. I quickly looked at the patch and some comments on the related patches (so I probably missed something, sorry), and as far as I understand, reconnections are done with the same (as default) 60s timeout. I have some suggestions for arguments to --reconnect.
- Maybe add a limit on reconnections, expressed either as time or number of retries, max >0, default Inf
- Maybe add a factor for reconnecting at exponentially increasing timeout lenght, factor >=1, default 1

**Comment by totaam** [comment]
Yes, having more control and increasing the timeout would make sense.
I'm not sure we will have to time to get that in before the release though.

I'm closing this ticket because I don't see any other actions to take here.
Feel free to create a new ticket for the reconnection configuration options, or even better: a PR.
