### ISSUE TITLE
[consult] would like to know the method you use to build / package this program for distribution

### ISSUE THREAD

**Issue by mo-han** [Xpra-org/xpra#3287]
xpra is a greate tool i discovered recently and helped me a lot (although there are some bugs or defects but that's another topic)
i enjoy using it, and also love its folder structure in my "Program Files" (using the windows version), that almost all depending libs are put into the "lib" folder.

how you guys achieve this? i'm a python hobbist, and use a tool called pyinstaller to build / package for release. pyinstaller is good but the output folder structure is not as tidy as xpra is.
could you share you method? i see there is some "packaging" scripts in the source code and took a glance inside it, i saw `cx_freeze` in the code. is cx_freeze the tool xpra used? is all the settings and procedure included inside those packaging scripts? any other import steps to follow to get the same level as xpra?

thank you in advance.

**Comment by totaam** [comment]
https://github.com/Xpra-org/xpra/blob/master/packaging/MSWindows/MINGW_BUILD.sh
