### ISSUE TITLE
xpra r30063 (dd6aa88a9) fails on xdg-open `http://url`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3290]
xpra r30063 (dd6aa88a9) fails on xdg-open `http://url` · Issue #3290 · Xpra-org/xpra

The only error message is:
```
Error: unknown datatype 'url'
```

slots again?

**Comment by totaam** [comment]
This was yet another instance of #3229

Should all be fixed as of r60098.

**Comment by stdedos** [comment]
And I've just installed r30095
Damn 😛

**Comment by stdedos** [comment]
I have verified the "#3290 make URI text selectable" commit, but the `Error: unknown datatype 'url'` is a server issue that requires a server build (latest I can get is r30063).

I don't have to always do formal verification ofc on every issue (that's so trivial), but just as an FYI 🙂
