### ISSUE TITLE
clarify meaning of options for start versus attach

### ISSUE THREAD

**Issue by brainchild0** [Xpra-org/xpra#3298]
Currently the documentation leaves ambiguous how options may independently affect *start* versus *attach* operations. I have generally assumed that most options apply to _start_ operations, and are ignored for *resume* operations, being immutable throughout the session.

However, I would suggest better documentation on this subject, as well as warnings or errors in cases of invocation with options that are not appropriate or meaningful for the chosen operation.

(I have been using version 3.0.6-r25177 on a Linux Mint client.)

**Comment by brainchild0** [comment]
> `man xpra` is divided into sections which list at the top `Options for attach` or `Options for start, start-desktop, upgrade and attach`, etc..

Yes, it's true, but there is still some lack of clarity, especially for certain items under _General options_.  For example, consider `--clipboard` or `--pulseaudio`. 

The following questions are unresolved:

1. In what sense are these options "general"? Do they apply to all operations, or do they apply to the main application in some way independent of any operations, such as *start* or *attach*. One assumes, at minimum, they apply to _start_ operations by determining the attributes of the new session, though an explanation would be helpful.
2. Then, if these options determine the attributes of a new session, do they also apply to *attach*? If so,  is the effect to mutate the attributes of an existing session?
3. If the effect is to mutate the existing session, what is the effect if the session is started with an option overriding a default value, and then the session is resumed without the option being given explicitly? Is the attribute preserved from  the session as originally created, or is it mutated to the default value?

Resolving a correct invocation, for some desired effect, even for very ordinary use, requires some understanding of these distinctions, which I believe are not given in the documentation.

**Comment by totaam** [comment]
> Do they apply to all operations

They apply to all subcommands where they are relevant. ie: `clipboard` and many other options are not relevant to `xpra screenshot` or `xpra list`.

> if these options determine the attributes of a new session, do they also apply to attach

The clipboard option specifically states: _If disabled on the server, no clients will be able to use clipboard synchronization at all_

> If the effect is to mutate the existing session

It is not.

> which I believe are not given in the documentation

Please provide specific examples of what is unclear to you. ie: `clipboard` seems quite clear.

**Comment by brainchild0** [comment]
Perhaps `--clipboard`  should be placed under a section called *Options for start*, or one similarly named by the the subcommands to which it applies. Based on your explanation, and the document structure of placing option descriptions under a section named by the subcommands to which the option applies, I would suggest that *General options* is a confusing location the description of `--clipboard`, and likewise for any other option currently in the same section that applies only to specific subcommands.

I believe the question of whether clipboard support is available on the server, and how such availability affects the client, is a separate issue from the immediate one of options applying differently to various subcommands.


The questions I have asked, I believe, are not easy, perhaps not possible, to infer from the documentation in its current state. They are the examples, at least to start, of what is unclear to me. At minimum, I would suggest that some revisions to the document structure would make it less confusing.




Finally, if options such as `--clipboard`  have no effect for subcommands such as *attach*, perhaps the application should print a warning for such combinations.
