### ISSUE TITLE
Make overlay icon configurable

### ISSUE THREAD

**Issue by DataGhost** [Xpra-org/xpra#3301]
I am running multiple VMs / workspaces and accessing them through Xpra. I am using ```--tray-icon=/some/icon/file``` on client launch to distinguish the different Xpra sessions in the tray so I start the correct process on the correct machine. However, this icon is not applied as overlay in the individual process windows, they all have the default Xpra icon superimposed. It'd be nice to use a different icon there as well, configurable on the command line as the tray icon is now. That way I can easily distinguish which machine processes with otherwise identical window icons are running on. 

I have tried ```window-icon``` on both client and server to no avail. Looking into the current code, it's defined at: https://github.com/Xpra-org/xpra/blob/3ffd5de1e95738a61a6ce7c49582eb17224110dd/xpra/client/mixins/window_manager.py#L218 where it says the "xpra" icon is applied, always. It looks like it should be relatively straightforward to fetch ```icon_filename``` from the environment if the proper variable is set, and fall back to the default icon otherwise.

**Comment by DataGhost** [comment]
I knew I was forgetting something writing this ticket but couldn't put my finger on it. I'm on Windows (and using forward slashes just in case, sorry, habit), so looking at the PNG handling code below it I think it might cause a problem with the ICO file format requirement for the tray icon. Also because of this, I can't easily modify the code and run it, at least not until later today.

**Comment by totaam** [comment]
> I'm on Windows

There's a new beta build (r30216) here: https://xpra.org/beta/windows/

There are no `WMCLASS` problems on MS Windows, so the latest builds should do what you requested.

**Comment by DataGhost** [comment]
Ah, nice. Yes it's working for me too. Thanks!
