### ISSUE TITLE
Question: Is it possible to start a dock application in seamless mode?

### ISSUE THREAD

**Issue by ogzs** [Xpra-org/xpra#3304]
Hi, I'm able to run a desktop environment with `start-desktop`, works great!
But I would prefer to run it in seamless mode, with one window for the dock (for example, `plank`) or a task-bar, so that any program that I open would run in its own window in the same session.

When I do `start --start=plank` , it messes the local desktop background and doesn't show the dock. I guess it needs to interact with the local desktop environment.

I would even be ok with a small desktop env in a small window, but configured so that applications open in other local windows, and not inside the desktop window.

Did anybody manage to do something like that?

**Comment by ogzs** [comment]
> What you want is to just run the dock in xpra.

Exactly!
Is there a way to do that?

**Comment by totaam** [comment]
> Is there a way to do that?

`xpra start --start=somedockapplication`

ie: `xfce4-panel` and many other options.
