### ISSUE TITLE
Password for tcp connections is ignored (regression)

### ISSUE THREAD

**Issue by DataGhost** [Xpra-org/xpra#3307]
Introduced recently in commit 070baba428f3c2286db9fc461b83f73c5e628f56.
Specifying the password as tcp://:password@host:port presents a password prompt. This is because the password is not propagated out through ```opts```  (good thing there was a warning there):
https://github.com/Xpra-org/xpra/blob/d447c73b151efd118199a6ad3f021531d6980a52/xpra/scripts/main.py#L1187-L1190

When parsing: https://github.com/Xpra-org/xpra/blob/d447c73b151efd118199a6ad3f021531d6980a52/xpra/scripts/parsing.py#L593
for tcp and some other protocols, ```_parse_host_string``` is called which in turn calls ```parse_username_and_password```. For some other protocols, ```_parse_username_and_password``` is used instead, which also updates ```opts```. This last step is thus missing for tcp, ssl, ws, wss, vnc and I believe ssh as well, so ```opts.username``` and ```opts.password``` will remain empty and subsequently overwrite ```app.username``` and ```app.password``` in main.py with empty values.

Adding the two assignments to ```opts``` from ```def _parse_username_and_password``` https://github.com/Xpra-org/xpra/blob/d447c73b151efd118199a6ad3f021531d6980a52/xpra/scripts/parsing.py#L474-L475 
to ```def _parse_host_string``` right before the call to ```_set_password``` fixes the problem for me. Might not be the most beautiful solution though but the code flow put me off a little.

The documentation is also a bit strange here, the manpage lists only the username as an option for tcp://, no :password https://github.com/Xpra-org/xpra/blob/d447c73b151efd118199a6ad3f021531d6980a52/fs/share/man/man1/xpra.1#L100
while the tcp example in https://github.com/Xpra-org/xpra/blob/d447c73b151efd118199a6ad3f021531d6980a52/docs/Usage/Authentication.md#L103
shows that it should be accepted.

Repro:
```xpra start --bind-tcp=0.0.0.0:10000,auth=password:value=something```
```xpra attach tcp://:something@127.0.0.1:10000```
Password is requested, instead of expected successful connection without prompt.

**Comment by totaam** [comment]
Wow. I am impressed that you managed to read through that awful code without having your head explode!
I must apologize for letting the code get this bad over the years.. it has evolved in ways that weren't planned.
(we can probably make it simpler by dropping some of the backwards compatible syntax - unfortunately people still use it)

Do the commits above resolve this issue?

**Comment by DataGhost** [comment]
I didn't want to say too much about it, I think we've all been there, especially in long-living projects. The code looked pretty "evolved" indeed.
Anyway I just did a pull and the above patches seem to have resolved the issue for my test case.
