### ISSUE TITLE
Wishlist: shadowing only the display space corresponding to an external monitor

### ISSUE THREAD

**Issue by callegar** [Xpra-org/xpra#3320]
I would like to shadow only one part of a display, namely the one corresponding to an external monitor.

It is my understanding that the shadow operation mode shadows a full display. Namely if you have an external monitor attached, that is placed, e.g. right of your standard screen via xrandr, xpra will shadow the full display area (namely the one extending from your standard screen to the right to include also the area corresponding to your external monitor).

Would it be possible to introduce switches to shadow only the area corresponding to the external monitor — or if switches to achieve this goal already exist to better document them, maybe with an example?

This would be extra-useful. Specifically, it would let you attach a "virtual display adapter" to the external (HDMI/DP) port of a computer (see https://www.amazon.com/s?k=virtual+display+adapter) to pretend that there is an external monitor attached and make your desktop environment and applications use it. Then it would let you virtualize this monitor over xpra to some other place (e.g. inside a web-browser in a tablet). In other words it would let you do the same thing that can be done with deskreen (https://deskreen.com/), but most likely with the better efficiency and flexibility of xpra in terms of encodings, etc.

**Comment by totaam** [comment]
With the commits above, we now support this feature with MS Windows shadow servers and using a more user friendly syntax:
* just as before, this will shadow all monitors of the display specified:  
`xpra shadow :1`
* we can now disable _window-per-monitor_ mode more easily with:  
`xpra shadow :1,multi-window=no`
* we can shadow a specific output:  
`xpra shadow :1,DP-1`
Or more explicitly with:  
`xpra shadow :1,plug=DP-1`
* to limit the size:  
`xpra shadow :1,1920x1080`
* size and location:  
`xpra shadow :1,1920x1080@1280x0`
or more explicitly:
`xpra shadow :1,geometry=1920x1080@1280x0`
* this can also be used to specify multiple areas:  
`xpra shadow :1,1920x1080@1280x0,1280x600@0x400`

---

On MS Windows and MacOS, the display name (`:1` in the examples above) is not used but it is still required. Use: `xpra shadow Main,options..`

---

To get the list of output names (ie: `DP-1` in the examples above), look at the client's command line output (`Xpra_cmd.exe` on MS Windows) or run with an invalid value: `xpra shadow Main,help`.

This feature is available in beta builds 4.3-r30301 and later.

**Comment by totaam** [comment]
This information has been added to the man page: a0e0b5ec4a55240c2a6a45825b27d65cc483fcc6

**Comment by normanr** [comment]
There seems to be a way to add a virtual output with evdi (https://unix.stackexchange.com/a/585078). I have not yet tested it.

**Comment by totaam** [comment]
@normanr please see #3390 and comment there.
