### ISSUE TITLE
connection failed: unsupported operand type(s) for +

### ISSUE THREAD

**Issue by MartinSchoenstedt** [Xpra-org/xpra#3332]
Hello, 

Running Xpra 4.3-r29365 (g2b480aafb) 64-bit on Windows 10, connecting fails with the following error:

> xpra initialization error: connection failed: unsupported operand type(s) for +: NoneType and int

However, in the log file on my Windows machine the last writen line is "Connected" and no error is mentioned.

Any ideas for what could cause this error?

**Comment by totaam** [comment]
@MartinSchoenstedt what connection string are you using?
Or are you using the launcher GUI?
In which case: what settings are you using?

You can usually get more details by running `Xpra_cmd.exe` instead of the launcher directly.

**Comment by MartinSchoenstedt** [comment]
> @MartinSchoenstedt what connection string are you using? Or are you using the launcher GUI? In which case: what settings are you using?

I used
`C:\"Program Files"\Xpra\Xpra.exe start ssh://user@ip-address:22 --input-method=ibus --start-env=GTK_IM_MODULE=ibus --start lxterminal` 
the same command has worked before. For settings I only configured a fixed value for desktop-scaling, everything else I left unchanged

> You can usually get more details by running `Xpra_cmd.exe` instead of the launcher directly.
I will try this now

**Comment by totaam** [comment]
The same command works for me here going from win10 to Fedora 34.
Can you try adding `--debug ssh` to your command line?

**Comment by MartinSchoenstedt** [comment]
I can't reproduce the bug anymore. Although I have not changed anything, suddenly the connection works again. If the problem occurs again I will try to debug it.
Thanks for your hints

**Comment by MartinSchoenstedt** [comment]
So I was able to reproduce the bug again, when I add the `--debug ssh` option, the connection is established, but when I remove that option again the bug occurs again

**Comment by totaam** [comment]
> `2021-11-01 10:37:01,815 Connected (version 2.0, client OpenSSH_7.6p1) xpra initialization error: connection failed: unsupported operand type(s) for +: 'NoneType' and 'int'`

So your client successfully connected to the server and opened the ssh session.
What is the xpra version on the server?

**Comment by MartinSchoenstedt** [comment]
The server is running xpra v4.3-r30283 (g76fc65878)

**Comment by totaam** [comment]
> The server is running xpra v4.3-r30283 (g76fc65878)

Which distribution?

**Comment by MartinSchoenstedt** [comment]
Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-161-generic x86_64)

**Comment by totaam** [comment]
> Ubuntu 18.04.6 LTS

9e10e1521db7c1a2e6eb8a08a3260eb0a5eab67c may be the fix you need.
You can try applying it by hand on the server or updating to r30325 or later from the beta channel. (just uploaded)

**Comment by MartinSchoenstedt** [comment]
Updating to the mentioned release on client and server fixed the problem
