### ISSUE TITLE
keycloak authentication module

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3334]
Probably using https://github.com/marcospereirampj/python-keycloak

First hurdle is the keycloak server setup, which is done manually using a UI rather than scripting.
Then we have to choose how deeply to integrate. Do we want to use `get_sessions()`?
The documentation is quite limited too.

**Comment by iDmple** [comment]
I'm highly interesting in this feature.

**Comment by totaam** [comment]
@iDmple you can help by narrowing down the requirements and providing simple setup instructions so that I can setup a test environment.

**Comment by iDmple** [comment]
I will have to focus on the auth of our platform soon, and will report my findings to you.

**Comment by iDmple** [comment]
I'm ready to start the work on this. Which tag / branch should I integrate this on?

**Comment by totaam** [comment]
> I saw there is no dev branch, so probably master.

Correct.

**Comment by totaam** [comment]
See also #4915
