### ISSUE TITLE
Finnish keyboard layout is not detected without --keyboard-layout=fi (client on Windows 11/server on WSL 2/Ubuntu 20.04)

### ISSUE THREAD

**Issue by aki-k** [Xpra-org/xpra#3338]
Client: Windows version: 4.2.3 rev 3
Server: Ubuntu version: 4.2.3-r12

Finnish keyboard layout is not detected without --keyboard-layout=fi. It somehow defaults to 'us'.

I'll upload 4 log files taken with -d keyboard from both client sessions and server sessions.

[client_log_without_keyboard_layout.txt](https://github.com/Xpra-org/xpra/files/7459958/client_log_without_keyboard_layout.txt)

[server_log_without_keyboard_layout.txt](https://github.com/Xpra-org/xpra/files/7459960/server_log_without_keyboard_layout.txt)

[client_log_with_keyboard_layout.txt](https://github.com/Xpra-org/xpra/files/7459957/client_log_with_keyboard_layout.txt)

[server_log_with_keyboard_layout.txt](https://github.com/Xpra-org/xpra/files/7459959/server_log_with_keyboard_layout.txt)

**Comment by totaam** [comment]
Could be similar to #2560 ?

TILs: without:
```
 GetKeyboardLayoutList()=0x40b0409, 0x40b0809
 found keyboard layout 'us' / 0x409 with variants=[], code 'USA' for kbid=1033 (0x40b0409)
 found keyboard layout 'gb' / 0x809 with variants=['extd', 'intl', 'dvorak', 'dvorakukp', 'mac', 'mac_intl', 'colemak'], code 'ENG' for kbid=2057 (0x40b0809)
 GetKeyboardLayout(0)=0x40b0409
 found keyboard layout 'us' / 0x409 with variants=[], code 'USA' for kbid=1033 (0x40b0409)
 get_layout_spec() GetKeyboardLayoutName()=0000040B
 sublang(0x40b)=0x1
 get_layout_spec() WIN32_KEYBOARDS[0x40b]=('fi', 'Finnish')
 get_layout_spec() WIN32_KEYBOARDS[0x40b]=('fi', 'Finnish')
 get_layout_spec() WIN32_KEYBOARDS[0xb]=None
 keyboard layout code 0x409
 identified as 'Finnish' : us
 win32.Keyboard.get_layout_spec()=('us', ['us', 'gb'], None, [], '')
 get_layout_spec()=('fi', ['fi', 'us', 'gb'], None, [], None)
```
vs with:
```
 GetKeyboardLayoutList()=0x40b0409, 0x40b0809
 found keyboard layout 'us' / 0x409 with variants=[], code 'USA' for kbid=1033 (0x40b0409)
 found keyboard layout 'gb' / 0x809 with variants=['extd', 'intl', 'dvorak', 'dvorakukp', 'mac', 'mac_intl', 'colemak'], code 'ENG' for kbid=2057 (0x40b0809)
 GetKeyboardLayout(0)=0x40b0409
 found keyboard layout 'us' / 0x409 with variants=[], code 'USA' for kbid=1033 (0x40b0409)
 get_layout_spec() GetKeyboardLayoutName()=0000040B
 sublang(0x40b)=0x1
 get_layout_spec() WIN32_KEYBOARDS[0x40b]=('fi', 'Finnish')
 get_layout_spec() WIN32_KEYBOARDS[0x40b]=('fi', 'Finnish')
 get_layout_spec() WIN32_KEYBOARDS[0xb]=None
 keyboard layout code 0x409
 identified as 'Finnish' : us
 win32.Keyboard.get_layout_spec()=('us', ['us', 'gb'], None, [], '')
 get_layout_spec()=('us', ['us', 'gb'], None, [], None)
```
The only difference is that we override the value returned in `get_layout_spec`.

We find the correct Finnish layout: ```get_layout_spec() GetKeyboardLayoutName()=0000040B``` with ```sublang(0x40b)=0x1``` but somehow this gets mapped to `us`: `identified as 'Finnish' : us` !?

**Comment by totaam** [comment]
So, I think that the fixes above should do what we want.

We use [GetKeyboardLayoutName](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutnamea) before trying [GetKeyboardLayout](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayout).
The former returns a 32-bit number... formatted as a string! Yuk.

From your log sample, `GetKeyboardLayoutName()=0000040B` should then give you a `Finnish` aka `fi` keyboard layout.
Hopefully this won't cause regressions for other keyboard layouts..

@aki-k Does the latest beta build work for you? (4.3-r30331 or later)
https://xpra.org/beta/windows/

**Comment by aki-k** [comment]
@totaam Yes that fixed it.

**Comment by aki-k** [comment]
These are the logs from my attempt to use r30333 and not use --keyboard-layout=fi.
There are many keys that don't produce any chars on screen.

from server: [%3A100.log](https://github.com/Xpra-org/xpra/files/7468368/3A100.log)

from client: [Xpra.log](https://github.com/Xpra-org/xpra/files/7468377/Xpra.log)

**Comment by totaam** [comment]
@aki-k is this a regression between r30331 and r30333?

From your client log, this looks correct:
```
GetKeyboardLayoutList()=0x40b0409, 0x40b0809
get_layout_spec() GetKeyboardLayoutName()=0000040B
(..)
get_layout_spec()=('fi', ['fi', 'gb', 'us'], None, [], None)
```
`0x040b` is `fi`, `0x0409` is `us` and `0x0809` is `gb`.

The only difference that I see with the debug output your posted when using `--keyboard-layout=fi` is that `gb` now comes before `us`, you had:
```
 get_layout_spec()=('fi', ['fi', 'us', 'gb'], None, [], None)
```
Surely that's not enough to cause keys to go missing!?

**Comment by aki-k** [comment]
This is output on the server side into :100.log when I press ö and nothing shows on the screen. This only happens first time after rebooting Windows 11.

[xpra-odiaresis.txt](https://github.com/Xpra-org/xpra/files/7468800/xpra-odiaresis.txt)

**Comment by totaam** [comment]
From this log sample, TIL:
```
process_key_action(['key-action', 1, b'0xffffff', True, (), 16777215, b'', 192, 0]) server keycode=-1, group=0
```
Which corresponds to: `window id, key name, pressed state, modifiers, keyval, key string, client_keycode, group`
This means that we don't have the key name or the key string - probably due to the `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 0: unexpected end of data` you had reported elsewhere.
And therefore the server is unable to find a keycode matching so little information.

I very much doubt that this is something that has changed between the two revisions above (and even if it does, this is going to be caused by a GI / GTK library update) so this belongs in a different ticket.

**Comment by totaam** [comment]
Setting: `XPRA_WIN32_LANGCHANGE=0` seems to help and stops the stream of keyboard messages.
Is win11 triggering too many `LANGCHANGE` messages?

**Comment by totaam** [comment]
If you're still having problems with win11, the `-d events` log output should show the `LANGCHANGE` events - perhaps we need to disable it on win11.
