### ISSUE TITLE
Untrusted Certificate

### ISSUE THREAD

**Issue by tmanok** [Xpra-org/xpra#3339]
Hello,

I'm running Linux Mint 20 and I've noticed that the xpra.org repository no longer works due to an expired certificate. 

The sources.list.d/additional-repositories.list file contains: `deb https://xpra.org/ bionic main`, this appears to still be supported (https://xpra.org/repos/bionic/xpra.list).

```
Err:19 https://xpra.org bionic Release                          
Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 78.129.163.65 443]
```

The following command was issued to attempt a resolution:

`wget -q https://xpra.org/gpg.asc -O- | sudo apt-key add -`
However, the problem persists.

Thanks, please let me know what mistake I may have made or resolve the issue with the repository.

Tmanok

**Comment by totaam** [comment]
https://github.com/Xpra-org/xpra/issues/3323#issuecomment-951587226
