### ISSUE TITLE
relocatable RPMs?

### ISSUE THREAD

**Issue by scottven** [Xpra-org/xpra#3341]
Would it be possible to rebuild the RPMs to support relocation?  I don't have root on my compute farm and would like to install into my home directory.

**Comment by totaam** [comment]
You already can, just install the RPMs into a prefix then adjust:
* `PATH` and `LD_LIBRARY_PATH`
* set `XPRA_INSTALL_PREFIX=/your/prefix` or you can also switch to `Xvfb` which is easier (in `/etc/xpra/conf.d/55_server_x11.conf`)
