### ISSUE TITLE
xpra agent for osx - ssh start support

### ISSUE THREAD

**Issue by megheaiulian** [Xpra-org/xpra#3343]
When using `xpra shadow ssh:$MACIP` ($MACIP is a Big Sur OS) I get this error:
```
SSH: 'Error: shadow may not start,'
SSH: " the launch agent file '/System/Library/LaunchAgents/org.xpra.Agent.plist' seems to be missing:[Errno 2] No such file or directory: '/System/Library/LaunchAgents/org.xpra.Agent.plist'."
```
Had a look at #1169 and it seems the LaunchAgent is missing from `/System/Library/LaunchAgents/` because of SIP.
To make it work the installer should place that plist instead in `/Library/LaunchAgents` which should be writable. 
See also:  https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html.

**Comment by totaam** [comment]
I haven't tried it yet, but there's a new beta build with the change you suggested above: https://xpra.org/beta/MacOS/

**Comment by megheaiulian** [comment]
Thank you! That fixed the issue.
