### ISSUE TITLE
mystery of the missing byte

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3346]
Connecting the html5 client through a proxy server causes the first byte to go missing!?

Tested with both master and the v3.1.x branch:
```
/usr/bin/xpra start --start=xterm --bind-tcp=0.0.0.0:12000 :10 --daemon=no
/usr/bin/xpra proxy --bind-tcp=0.0.0.0:10000 --tcp-auth=allow -d proxy --daemon=no
```
Connecting the python client works:
```
xpra attach tcp://foo:bar@192.168.0.10:10000/
```
But connecting with the html5 client causes a strange error where the proxy sends the hello packet to the backend server after connecting and the first byte is chopped off somewhere:
```
started proxy instance pid 45179
 for client ws socket: 127.0.0.1:10000 <- 127.0.0.1:32974
 and server unix-domain socket:  <- /run/user/1000/xpra/10/socket
(..)
queueing server packet: hello (queue size=0)
sending to server: hello (queue size=0)
Protocol(unix-domain socket:  <- /run/user/1000/xpra/10/socket) \
    wrote 5001000000001917c28568656c6c6f3c8776657273696f6e85342e...
process_server_packet: gibberish
```
The server sees:
```
New unix-domain connection received
 on '/run/user/1000/xpra/10/socket'
read: 01000000001917c28568656c6c6f3c8776657273696f6e85342e..
Disconnecting client /run/user/1000/xpra/10/socket:
 invalid packet header byte: 0x01000000001917c2 read buffer=b'\x01\x00\x00\x00\x00\x19\x17\xc2\x85hello<\x87 .. \x03\xe8\x85proxyC\x94encoding.proxy.videoD\x7f' (6430 bytes)
```
The packet data is clearly exactly the same, just missing the first byte (`0x50` aka `P`).

**Comment by basilgello** [comment]
I do use proxy constantly and I dont see such issue @totaam . Is it manifested when v3.1.x HTML5 client connects to master proxy or?

**Comment by basilgello** [comment]
Missing byte in `socket` is strange, but I spent 2w figuring out missing bytes in amd64 <--> x32 fakeroot: https://salsa.debian.org/clint/fakeroot/-/merge_requests/7

**Comment by totaam** [comment]
Also reproduced with a Debian Bullseye and Debian Buster VM but not with a Fedora 34 VM running the same version!? There's something funky going on.

The "good" news is that I can reproduce the problem more easily with the python client and `xpra attach ws://127.0.0.1:10000` which is a lot faster and easier to deal with than a browser process!

I think this is caused by some incompatible changes during the 4.3 release cycle (very likely to be `rencodeplus`): updating to the latest version seems to have fixed things for some test VMs - but not all!

I will need to re-test when mixing 4.2.x and 4.3.x
(I also saw some problems with the html5 client..)

**Comment by totaam** [comment]
Not made much progress on this, it looks like a random "corruption" of some sort, I'm now hitting something very similar at random without using a proxy:
```
Error: received an invalid packet
 received uninterpretable nonsense: "invalid packet header byte: 0x0000000000000000 read buffer=b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x .. GRX\\x87quality>d\\x8bwindow-size\\xc2?\\x01,?\\x01,' (7772 bytes)"
 packet no 122 data:  .. Zirgb_format
                                                             BGRXquality>dwindow-sizeÂ?,?,
```

**Comment by basilgello** [comment]
I cant see it on Debian testing, soooo… Can you try my Debian build?)

**Comment by jdstroy** [comment]
I'm on Debian AArch64 and I see it all the time when connecting over SSH+Unix sockets.  Doesn't reproduce over TCP/IP, nor does it reproduce if I use socat as a proxy (listening on TCP and connecting to the Unix socket).

**Comment by totaam** [comment]
The real problem was that the "pre-read" data from unix domain sockets was not being re-injected. (using `__slots__` would have prevented that, but protocol is too big)
