### ISSUE TITLE
HTML5 Client on arm64

### ISSUE THREAD

**Issue by nakkaya** [Xpra-org/xpra#3350]
On `arm64` `Ubuntu`  `xpra-html5` package is missing using `xpra.org` repository. I seem to remember on another issue, it has been mentioned that this package is no arch however `apt-get install xpra xpra-html5` fails on arm64 but not on `amd64`.

**Comment by totaam** [comment]
What specific distribution?
arm64 support will be included in the 4.3 release, until then it is in the beta repository for some distributions only:
https://github.com/Xpra-org/xpra/issues/3291#issuecomment-932866664

**Comment by nakkaya** [comment]
Then my bad. I was using `Ubuntu 20.04` but with non beta repository. Following #3291 I assumed it was available for the current release also. I'll switch to beta repository.

**Comment by nakkaya** [comment]
Following the release of `4.3`. I tried rebuilding my docker image [1]  for `arm64`.  On `arm64`  `xpra-html5` package seems to be missing. Running `apt-cache policy xpra` returns 4.3 as candidate to install but `apt-cache policy xpra-html5` show no package available.

[1] https://github.com/nakkaya/emacsd/blob/master/Dockerfile#L107

**Comment by totaam** [comment]
Until a new version of the `xpra-html5` client is released, please use the beta area which does have one.
`xpra` and `xpra-html5` are now separate projects.
