### ISSUE TITLE
ubuntu focal repo cert verify problem

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3364]
I have a new Ubuntu (Focal) system at work. I'm not yet too familiar with Ubuntu habits, but followed the [directions](https://github.com/Xpra-org/xpra/wiki/Download#-linux) for setting up beta. Unfortunately, `apt update` is unhappy with the result:
```
Ign:7 https://xpra.org/beta focal InRelease                                                                                 
[ ... ]
Err:9 https://xpra.org/beta focal Release  
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 78.129.163.65 443]
[ ... ]
E: The repository 'https://xpra.org/beta focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by totaam** [comment]
This is bogus and caused by an Ubuntu bug: #3339

**Comment by karlkleinpaste** [comment]
Then I suggest that `sudo apt install ca-certificates` be added to the instructions.

**Comment by totaam** [comment]
Good idea, done: https://github.com/Xpra-org/xpra/wiki/Download/_compare/5333409659eeb7b1584d9bffbf5a86f40fed1315
