### ISSUE TITLE
spng decoder

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3373]
Fedora has `libspng` in Fedora 34.

Unfortunately, the header file does not have the encode functions, only decode.

**Comment by totaam** [comment]
Done.
Unfortunately, there is no `spng` package in Debian or in MSYS2.
We could add it to jhbuild for MacOS.

**Comment by randy408** [comment]
> Done. Unfortunately, there is no `spng` package in Debian or in MSYS2. We could add it to jhbuild for MacOS.

FYI it is expected to ship in Debian Bookworm: https://packages.debian.org/search?suite=bookworm&searchon=names&keywords=libspng
