### ISSUE TITLE
quic transport

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3376]
[QUIC](https://en.wikipedia.org/wiki/QUIC) could easily replace the old UDP transport.
There are frameworks and APIs that wrap QUIC with easy to use callbacks, like https://github.com/aiortc/aioquic [documentation](https://aioquic.readthedocs.io/en/latest/)
(see also https://github.com/MagicStack/uvloop)
We would get HTTP/3 and encryption almost for free and a reliable event based framework for managing connection state.

[Examples](https://github.com/aiortc/aioquic/tree/main/examples) include an [http3 server](https://github.com/aiortc/aioquic/blob/main/examples/http3_server.py) and clients, etc..

The re-send / packet-drop callbacks could easily re-use the techniques that were used for UDP (#639) which was removed in 2022238ababa40382d2b8d6b019fb2d757ec9955.

---

Worth noting that _aioquic requires Python 3.7 or better, and the OpenSSL development headers_ so this won't be available on RHEL 8.

**Comment by totaam** [comment]
`aioquic` is not available in Fedora and the number of dependencies required to run the http3 server example is a little bit ridiculous: `python3-wsproto`, `python3-httpbin`, `python3-asgiref`, `python3-starlette` and `python3-aiofiles`.
Not counting all the dependencies that each one of these packages brings...

**Comment by totaam** [comment]
It gets worse since we also need to run the GTK main loop.
There are various ways of doing this:
* [asyncio-glib](https://github.com/jhenstridge/asyncio-glib/)
* [gbulb](https://github.com/beeware/gbulb)
And perhaps soon in pygobject directly: [Implement asyncio event loop based on glib](https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/189)

Next, creating `asyncio` sockets requires using a specific API: [asyncio.loop.create_datagram_endpoint](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_datagram_endpoint) / [loop.create_connection](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection), which means that socket sharing is going to be more difficult to implement.

This may help in bridging with the rest of the code:
* [trio](https://github.com/python-trio/trio) : _a friendly Python library for async concurrency and I/O_
* [greenback](https://github.com/oremanj/greenback) : _allows you to call back into async code from a syntactically synchronous function_

**Comment by TijZwa** [comment]
I've done some testing with Aioquic. Basically I've just glued asyncio with aioquic to the existing codebase. 
The main issue is starting a new main loop inside a thread, inside the existing GTK loop.
Also the list of dependencies is way too big (starlette and what not).

The source of aioquic seems pretty neat. I think the best way forward is to use this code as an example to implement our own low-level implementation of a http/3 quic server.

https://github.com/aiortc/aioquic/tree/main/src/aioquic

**Comment by totaam** [comment]
> as an example to implement our own low-level implementation of a http/3 quic server

Yes!
This part of the library looks really clean and, at first glance, without too many dependencies, only things like https://github.com/aiortc/pylsqpack
Gio supports UDP so there is no reason why we can't use the GTK main loop for handling packet events.

**Comment by totaam** [comment]
We need an asyncio event loop:
https://github.com/aiortc/aioquic/blob/444be09157aed3c81881d18647484165dd07139c/src/aioquic/asyncio/server.py#L202

The patches for pygobject are still languishing as a PR and [asyncio-glib](https://github.com/jhenstridge/asyncio-glib/) is unmaintained.

And [gbulb](https://github.com/beeware/gbulb) has had no update since earlier this year.

Then there's also [glibcoro](https://github.com/ldo/glibcoro): _glibcoro makes the `GLib` / `GTK`
event loop compatible with Python’s `asyncio`_

Meanwhile, this answer: https://stackoverflow.com/a/26719999/428751 suggests running the aio part in a separate thread. Downside is: _One does need to be careful, however, to use thread-safe functions to communicate between the GUI (main) thread and the asyncio thread. This means using loop.call_soon_threadsafe or asyncio.run_coroutine_threadsafe to submit things to asyncio from GTK, and GLib.idle_add to submit things to GTK from asyncio._

Decisions!

**Comment by totaam** [comment]
As of the commit above, I can connect via `quic` using a self signed cert:
```shell
xpra start --bind-quic=localhost:20000 --start=xterm :100 \
    --ssl-cert=./cert.pem --ssl-key=./key.pem
```
```shell
xpra attach quic://localhost:20000/ --ssl-server-verify-mode=none
```

**Comment by totaam** [comment]
As per [QUIC Throughput and Fairness over Dual Connectivity](https://www.sciencedirect.com/science/article/pii/S1389128622004650):
* _QUIC’s throughput is found to be similar to that of TCP in general cases, provided that the UDP receive buffer (when using aioquic) has been increased to a similar size as the corresponding TCP buffer_
* _With aioquic, the QUIC throughput is considerably lower if the UDP receive buffer remains at default values for Linux, as PDCP introduces packet bursts, causing packet drops due to full buffers. This occurs especially often in asymmetric link scenarios with high throughput. With the increased use of QUIC, we emphasize the importance of studying and optimizing the resources provided by the kernel to QUIC._

So running a quic server may require tweaking the kernel parameters:
```shell
sysctl -w net.core.rmem_max=26214400
sysctl -w net.core.rmem_default=26214400
```

**Comment by totaam** [comment]
Some notes on audio: do we want to use datagrams and [rtpjitterbuffer](https://gstreamer.freedesktop.org/documentation/rtpmanager/rtpjitterbuffer.html?gi-language=c)?
See [How to make rtpjitterbuffer work on a stream without timestamps?](https://stackoverflow.com/questions/39565204/)

**Comment by totaam** [comment]
Looks like [asyncio integration with support to await Gio async functions](https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/189) is going to be merged!
But we'll have to keep the threaded implementation around until all the supported distros ship with the new pygobject... which could take many years.

**Comment by totaam** [comment]
Looks like `asyncio` will be integrated with `pygobject` `Gio` soon: [asyncio integration with support to await Gio async functions](https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/189) so we will be able to drop the ugly [asyncio_thread](https://github.com/Xpra-org/xpra/blob/c1b032d8b6cde01434ae2ee074c9fcd22e4c12f0/xpra/net/quic/asyncio_thread.py) workaround in the future.

**Comment by totaam** [comment]
WebTransport can now be used with the html5 client:
https://github.com/Xpra-org/xpra-html5/issues/143#issuecomment-2198058969
(it would be nice to also support a `xpra attach webtransport://host:port/` mode for the Python client.
