### ISSUE TITLE
Clipping area for mouse event after connecting by HTML5 client

### ISSUE THREAD

**Issue by belonesox** [Xpra-org/xpra#3379]
I've observed a geometric clipping of mouse events on HTML5 connections.
For a 1920×1080 monitor, if the mouse event was larger than about 1790×800, its coordinates were clipped.

The easiest way to see this is with a logging application such as xournal or xournalpp.

This ( https://vimeo.com/99375768, 3minute) video demonstrates the following demos:
* Running the server with the local GTK client and the xournalpp application
```
xpra start ssh://b6981b2b16284bb6bfba79653f09d507@scp-007.0x1.tv/100 --start=xournalpp --bind-tcp=0.0.0.0:10000 --html=/usr/share/xpra/www/ --sharing=yes --microphone=off --terminate-children=yes --speaker=disabled --bell=no --clipboard=yes --notifications=no --av-sync=no --tray=no --mousewheel=on   --daemon=no 
```
[log-from-starting-session.txt](https://github.com/Xpra-org/xpra/files/7655078/log-from-starting-session.txt)

* The GTK version of xournalpp starts and works without any clipping.
* Attaching the HTML5 client (tested all modern browsers, FF, Chrome, Edge… — same problem)
  * In the HTML5 client there is a clipping of mouse events
* Once HTML5 client is connected, clipping occurs in GTK client as well.

So, I think this problem is beyond the scope of the xpra-html5 project.

I tested xpra==4.1.3 (standard RPM from Fedora Core 34), and last v4.2.3 — the problem still persists.

**To Reproduce**

Install on server any applications, to demo mouse clipping event — xournal, xournalpp, inkscape, etc. Actually, any application can be used, even ``xev``, but drawing apps are better to demo the issue. 
 
1. server command
```
/usr/bin/xpra start :100 --start=xournalpp --bind-tcp=0.0.0.0:10000 --html=/usr/share/xpra/www/ --sharing=yes --daemon=no  --cursors=yes 
```
2. Connect by any browser to choosen port (10000)

3.  Try to draw something to bottom right corner.

 - Server OS: «Fedora release 34 (Thirty Four)»
 - Client OS: «Fedora release 34 (Thirty Four)»
 - Server Version 34
 - Client Version 34

4. Server Logs attached…
[:101.log](https://github.com/Xpra-org/xpra/files/7655075/101.log)
[Xorg.:101.log](https://github.com/Xpra-org/xpra/files/7655076/Xorg.101.log)

**Comment by totaam** [comment]
> Once HTML5 client is connected, clipping occurs in GTK client as well.

So if I understand this correctly, there may actually be two bugs here:
* clipping with the html5 client, which means we're not detecting the correct window size for your browser - or choosing the wrong resolution on the server
* the virtual screen ends up being resized to the smallest of the two clients connected - it should use the biggest

You're not using the dummy driver from the xpra.org repositories:
```
DPI set to 32 x 18 (wanted 96 x 96)
 you may experience scaling problems, such as huge or small fonts, etc
 to fix this issue, try the dpi switch, or use a patched Xorg dummy driver
```
Please try the one from the official repos to see if it makes any difference.
Switching to `Xvfb` in `/etc/xpra/conf.d/55_server_x11.conf` may also help.

Your logs have lots of extra debugging enabled so it's not easy to follow.
Your GTK client seems to be:
```
client root window size is 3840x1200 with 1 display:
  :1.0 (1016x318 mm - DPI: 96x96) workarea: 3840x1048 at 0x152
     HJW DVI-I-0 1920x1080 at 0x120 (509x286 mm) workarea: 1920x1048 at 0x152
     DEL DP-1 1920x1200 at 1920x0 (519x324 mm - DPI: 94x94) workarea: 1920x1200 at 1920x0
```
The html5 client:
```
HTML5 Linux Chrome client version 4.5.2-r1087
client root window size is 640x624 with 1 display:
  HTML (169x165 mm - DPI: 96x96)
     Canvas
```
620x624 is very small, but perhaps your browser window was this small.

And here's at least one of the bugs - with both clients connected it does:
```
server virtual display now set to 576x432 (best match for 640x624)
```
It should have used a resolution bigger than the one from the browser.

---

BTW, your html5 client is failing to decode `h264` frames so you may want to turn `video` off on html5 client connect page.

**Comment by belonesox** [comment]
> Switching to Xvfb in /etc/xpra/conf.d/55_server_x11.conf may also help.

I tried to run server with and without «--xvfb="/usr/bin/Xvfb +extension Composite"», no difference. 

> your html5 client is failing to decode h264 frames 

May be I broke something when experimenting with different pip versions of xpra… Not important now.

>Your logs have lots of extra debugging enabled so it's not easy to follow.

Actually, I wish you to reproduce the issue, simplest way. 
I can provide you direct root access to some playground server on the internet where this issue reproduced, or prepare VirtualBox OVA… 

Can some of that help?

**Comment by totaam** [comment]
> I can provide you ..

The one thing that I really need is time.

**Comment by totaam** [comment]
@belonesox please try ef3e43b0e7934939b9ca94bdc2528520f4023f28

**Comment by totaam** [comment]
I'm quite confident that this issue is not present in the official xpra.org repositories - please use those.
Especially now that we have dynamic resolutions with the dummy driver: #56
