### ISSUE TITLE
SSH Shadow geometry

### ISSUE THREAD

**Issue by JohelEGP** [Xpra-org/xpra#3384]
Greetings.

Thank you for this great software.

As a follow up of #3320, running `xpra shadow ssh:server:port:display,geometry-option` does not handle geometry options just like local displays.

It'd like to use geometry options with a server through SSH.

Since geometry options are part of the `CONNECTIONSTRING`, it seems they have no place in config files. I did try setting a `geometry=500x300` option, to no avail.

Thanks for your attention.

**Comment by totaam** [comment]
First of all, the syntax you are using is well out of date, please use this form with the commit above - which works-for-me(tm):
```shell
xpra shadow ssh://server:sshport//:DISPLAY,geometry=1024x640@0x0
```
Which at least stands a chance of getting parsed correctly in the future.

The geometry options are part of the display string, which got overloaded over time.. so the fix above is really quite ugly.
Unfortunately there is no way to make this backwards compatible either, as the client cannot know in advance if the server supports the new syntax.
The whole thing is likely to change as we may need a more generic solution for #3476.
(so this may break again before the 4.4 release)

**Comment by JohelEGP** [comment]
Thank you. Now it works with:
```
xpra shadow ssh://server:sshport//DISPLAY?geometry=1024x640@0x0
```
So without `:` before DISPLAY, and with a `?` instead of `,` before `geometry`.
