### ISSUE TITLE
Connection that works on ubuntu doesn't work on macos

### ISSUE THREAD

**Issue by da0ist** [Xpra-org/xpra#3385]
**Describe the bug**
Connection that works on ubuntu doesn't work on macos

**To Reproduce**
1. server command: none
2. client command: 
Ubuntu: `xpra start-desktop --start=xterm ssh://ubuntu@xxx.xxx.xxx.xxx/`
macOS: `/Applications/Xpra.app/Contents/MacOS/Xpra start-desktop --start=xterm ssh://ubuntu@xxx.xxx.xxx.xxx`
SSH Authentication on `xxx.xxx.xxx.xxx` failed

3. specific action to trigger the bug

**System Information:**
 - Server OS: Ubuntu 20.04.3 LTS
 - Linux Client OS: Ubuntu 20.04.3 LTS
 - macOS Client OS: Big Sur
 - Xpra Server Version: v3.0.6-r25177
 - Linux Xpra Client Version: v3.0.6-r25177
 - macOS Xpra Client Version: v4.2.3-r0

**Additional context**
I even enabled password authentication on the server, but still get authentication failed. I can ssh fine from the terminal.

**Comment by da0ist** [comment]
Also happens with brew installed xpra version: v4.2.3-r0

**Comment by totaam** [comment]
Your xpra server version is not supported: https://github.com/Xpra-org/xpra/wiki/Versions

My guess is that this is a known regression in 4.2.3, please try downgrading to 4.2.2 or using the latest beta builds.

**Comment by totaam** [comment]
Not heard back. I assume this was the problem.
