### ISSUE TITLE
Run `systemd-inhibit` for xpra connections

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3386]
**Is your feature request related to a problem? Please describe.**
I would like to have frictionless experience when working between two computers one Windows (client) and one Ubuntu (server).
The server, coincidentally, is a laptop. Since I am not using its display, it makes little sense to keep its monitor open.

However, that triggers the "default" lid-button action (i.e. sleep).

`systemd` has `systemd-inhibit`, which can mask out such events. "Technically", the command started takes a lock-mask on the wanted events (so it should've been `systemd-inhibit --what=handle-lid-switch xpra [...] 1d`), but it can be easily mocked with a `--start-child` process that gets reaped at server-exit. (However, I am not sure if the `--start-child` are "exactly as I think they are", or if they are reverse i.e. xpra-server gets stopped when all `--start-child`s are dead).

**Describe the solution you'd like**
I would like to be able to run a command , that gets reaped when the server is shut down.
Except ofc `kill -9`, or explicit command that avoids teardowns (however, in this case, it should tell me which children will be orphaned)

"For extra points": there might be network connectivity issues. If the server exits immediately at a ~30sec connectivity timeout, I'd like for the `systemd-inhibit` command to live on server for an extra timeout (e.g. 5 minutes).
If the xpra server dies, and takes `systemd-inhibit` with it while the lid is already closed, the system automatically "receives" the signal - resulting in the "closed lid" actions. Instead, I'd like to run a `--start-on-last-client-exit='systemd-inhibit --what=handle-lid-switch sleep 5m'` command that MAY NOT hang the server necessarily (e.g. I am worried if I'll be able to re-connect to an almost-dead server; "`--use-display=auto`-like" or not).

**Describe alternatives you've considered**

```
    103 2021-12-14 22:16:14,274 started command 'systemd-inhibit --what=handle-lid-switch sleep 1d' with pid 281228
    104 [0m0;1;31mFailed to inhibit: Access denied
```

**Additional context**

**Comment by totaam** [comment]
Any idea about the `Failed to inhibit: Access denied`?
This idea won't get very far if we don't have the permissions to use it.

All `--start` commands are only terminated with the server if you also specify `--terminate-children`.
The server is terminated if all `--start-[.*]child=` commands exit and `--exit-with-children` is specified.

**Comment by stdedos** [comment]
> Any idea about the `Failed to inhibit: Access denied`? This idea won't get very far if we don't have the permissions to use it.

No 😕 I can run the command, even without `sudo` at my terminal, and it works (i.e. terminal runs `sleep`).
I won't pretend that `systemd` is something "small" though - who knows what "might be different" for my terminal vs xpra

> All `--start` commands are only terminated with the server if you also specify `--terminate-children`.

That sounds promising for this specific case

> The server is terminated if all `--start-[.*]child=` commands exit and `--exit-with-children` is specified.

Yeah - it was in reverse as I imagined

**Comment by totaam** [comment]
It's not quite clear to me where xpra should be dealing with this beyond what is already available via the "terminate" options.
Whilst playing with `systemd-inhibit` I did find that it was useful to wait for the vfb to terminate before running a command so the commit above makes it easier to do that:
```shell
xpra xwait;dosomething
```
One minor caveat is that the exit code of `xwait` is never zero, despite the fact that the command terminated correctly.
(dealing with X11 error handling was hard enough as it was)

Is this enough to close this ticket?

**Comment by totaam** [comment]
The brotli fallback has been removed: dc788a8a38a75b85edc61a86315f16657ff38d87
So this particular error should be impossible to hit again.

As for the original request, `xpra xwait` should make it easier to run commands at the right time.
