### ISSUE TITLE
New instance of "Warning: failed to setup video pipeline"

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3387]
**Describe the bug**
<pre>     <b>50</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">949</font><font color="#DCDFE4"> Warning: failed to setup video pipeline (</font><font color="#E5C07B">44</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), None, </font><font color="#E5C07B">0</font><font color="#DCDFE4">, </font><font color="#E5C07B">0</font><font color="#DCDFE4">, None, </font><font color="#98C379">&apos;BGRX&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(BGRX to jpeg))</font>
     <b>51</b> <font color="#DCDFE4">Traceback (most recent call last):</font>
     <b>52</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1656</font><font color="#DCDFE4">, in setup_pipeline</font>
     <b>53</b> <font color="#DCDFE4">    if self.setup_pipeline_option(width, height, src_format, *option):</font>
     <b>54</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1743</font><font color="#DCDFE4">, in setup_pipeline_option</font>
     <b>55</b> <font color="#DCDFE4">    ve.init_context(encoder_spec.encoding, enc_width, enc_height, enc_in_format, options)</font>
     <b>56</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;xpra/codecs/jpeg/encoder.pyx&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">172</font><font color="#DCDFE4">, in xpra.codecs.jpeg.encoder.Encoder.init_context</font>
     <b>57</b> <font color="#DCDFE4">TypeError: init_context() takes exactly </font><font color="#E5C07B">10</font><font color="#DCDFE4"> positional arguments (</font><font color="#E5C07B">5</font><font color="#DCDFE4"> given)</font>
     <b>58</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">968</font><font color="#DCDFE4"> Warning: failed to setup video pipeline (</font><font color="#E5C07B">34</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, swscale(BGRX to RGBX), </font><font color="#98C379">&apos;RGBX&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(RGBX to jpeg))</font>
     <b>59</b> <font color="#DCDFE4">Traceback (most recent call last):</font>
     <b>60</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1656</font><font color="#DCDFE4">, in setup_pipeline</font>
     <b>61</b> <font color="#DCDFE4">    if self.setup_pipeline_option(width, height, src_format, *option):</font>
     <b>62</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1743</font><font color="#DCDFE4">, in setup_pipeline_option</font>
     <b>63</b> <font color="#DCDFE4">    ve.init_context(encoder_spec.encoding, enc_width, enc_height, enc_in_format, options)</font>
     <b>64</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;xpra/codecs/jpeg/encoder.pyx&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">172</font><font color="#DCDFE4">, in xpra.codecs.jpeg.encoder.Encoder.init_context</font>
     <b>65</b> <font color="#DCDFE4">TypeError: init_context() takes exactly </font><font color="#E5C07B">10</font><font color="#DCDFE4"> positional arguments (</font><font color="#E5C07B">5</font><font color="#DCDFE4"> given)</font>
     <b>66</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">969</font><font color="#DCDFE4"> Warning: failed to setup video pipeline (</font><font color="#E5C07B">24</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, swscale(BGRX to YUV420P), </font><font color="#98C379">&apos;YUV420P&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(YUV420P to jpeg))</font>
     <b>67</b> <font color="#DCDFE4">Traceback (most recent call last):</font>
     <b>68</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1656</font><font color="#DCDFE4">, in setup_pipeline</font>
     <b>69</b> <font color="#DCDFE4">    if self.setup_pipeline_option(width, height, src_format, *option):</font>
     <b>70</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1743</font><font color="#DCDFE4">, in setup_pipeline_option</font>
     <b>71</b> <font color="#DCDFE4">    ve.init_context(encoder_spec.encoding, enc_width, enc_height, enc_in_format, options)</font>
     <b>72</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;xpra/codecs/jpeg/encoder.pyx&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">172</font><font color="#DCDFE4">, in xpra.codecs.jpeg.encoder.Encoder.init_context</font>
     <b>73</b> <font color="#DCDFE4">TypeError: init_context() takes exactly </font><font color="#E5C07B">10</font><font color="#DCDFE4"> positional arguments (</font><font color="#E5C07B">5</font><font color="#DCDFE4"> given)</font>
     <b>74</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">970</font><font color="#DCDFE4"> Warning: failed to setup video pipeline (</font><font color="#E5C07B">23</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, cython(BGRX to YUV420P), </font><font color="#98C379">&apos;YUV420P&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(YUV420P to jpeg))</font>
     <b>75</b> <font color="#DCDFE4">Traceback (most recent call last):</font>
     <b>76</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1656</font><font color="#DCDFE4">, in setup_pipeline</font>
     <b>77</b> <font color="#DCDFE4">    if self.setup_pipeline_option(width, height, src_format, *option):</font>
     <b>78</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;/usr/lib/python3/dist-packages/xpra/server/window/window_video_source.py&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">1743</font><font color="#DCDFE4">, in setup_pipeline_option</font>
     <b>79</b> <font color="#DCDFE4">    ve.init_context(encoder_spec.encoding, enc_width, enc_height, enc_in_format, options)</font>
     <b>80</b> <font color="#DCDFE4">  File </font><font color="#98C379">&quot;xpra/codecs/jpeg/encoder.pyx&quot;</font><font color="#DCDFE4">, line </font><font color="#E5C07B">172</font><font color="#DCDFE4">, in xpra.codecs.jpeg.encoder.Encoder.init_context</font>
     <b>81</b> <font color="#DCDFE4">TypeError: init_context() takes exactly </font><font color="#E5C07B">10</font><font color="#DCDFE4"> positional arguments (</font><font color="#E5C07B">5</font><font color="#DCDFE4"> given)</font>
     <b>82</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">970</font><font color="#DCDFE4"> Error: failed to setup a video pipeline for BGRX at 1920x1080</font>
     <b>83</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">970</font><font color="#DCDFE4">  tried the following options</font>
     <b>84</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  (</font><font color="#E5C07B">44</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), None, </font><font color="#E5C07B">0</font><font color="#DCDFE4">, </font><font color="#E5C07B">0</font><font color="#DCDFE4">, None, </font><font color="#98C379">&apos;BGRX&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(BGRX to jpeg))</font>
     <b>85</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  (</font><font color="#E5C07B">34</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, swscale(BGRX to RGBX), </font><font color="#98C379">&apos;RGBX&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(RGBX to jpeg))</font>
     <b>86</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  (</font><font color="#E5C07B">24</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, swscale(BGRX to YUV420P), </font><font color="#98C379">&apos;YUV420P&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(YUV420P to jpeg))</font>
     <b>87</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  (</font><font color="#E5C07B">23</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, cython(BGRX to YUV420P), </font><font color="#98C379">&apos;YUV420P&apos;</font><font color="#DCDFE4">, (</font><font color="#E5C07B">1</font><font color="#DCDFE4">, </font><font color="#E5C07B">1</font><font color="#DCDFE4">), </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">, jpeg(YUV420P to jpeg))</font>
     <b>88</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4"> Error: failed to setup a video pipeline for auto encoding with source format BGRX</font>
     <b>89</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  all encoders: </font>
     <b>90</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  supported CSC modes: </font>
     <b>91</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  supported encoders: </font>
     <b>92</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">971</font><font color="#DCDFE4">  encoders CSC modes: </font>
     <b>93</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">972</font><font color="#DCDFE4"> Warning: using non-video fallback encoding</font>
     <b>94</b> <font color="#E5C07B">2021-12-14</font><font color="#DCDFE4"> </font><font color="#E5C07B">22:16:07</font><font color="#DCDFE4">,</font><font color="#E5C07B">972</font><font color="#DCDFE4">  for XShmImageWrapper(BGRX: </font><font color="#E5C07B">0</font><font color="#DCDFE4">, </font><font color="#E5C07B">0</font><font color="#DCDFE4">, </font><font color="#E5C07B">1920</font><font color="#DCDFE4">, </font><font color="#E5C07B">1080</font><font color="#DCDFE4">) of window </font><font color="#E5C07B">1</font>
</pre>

**To Reproduce**
1. ```
	Server: Ubuntu 20.04.3 LTS / 4.3-r30655 (1e8a46dce)
	/usr/bin/xpra
	shadow
	:0
	--title=@title@ on @@/@server-display@
	--ssh=plink -ssh -agent
	--desktop-scaling=1.25
	--speaker=off
	--exit-with-client=yes
	--splash=no
	--video-encoders=
	--csc-modules=
	--video-decoders=
	--start-child=systemd-inhibit --what=handle-lid-switch sleep 1d
	--env=XPRA_PROXY_START_UUID=c86bb1b029e1460b87788017b337c98d
	--daemon=yes
	--systemd-run=no
	```
2. `"Xpra-Python3-x86_64_4.3-r30655\xpra_cmd" shadow ssh://user@ip/0 --ssh="plink -ssh -agent" --modal-windows=no --desktop-scaling=1.25 --headerbar=off --title="@title@ on @@/@server-display@" --start-child="systemd-inhibit --what=handle-lid-switch sleep 1d" --microphone=off --speaker=off --webcam=no --pulseaudio=no`

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Add any other context about the problem here.
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Oops. Thanks for the ticket! (fix above)
