### ISSUE TITLE
Xvfb-for-Xpra-S* process remaining after disconnection

### ISSUE THREAD

**Issue by mo-han** [Xpra-org/xpra#3395]
**Describe the bug**
after disconnected from client side, desktop related process also stopped on server side, but the `Xvfb-for-Xpra-S*` process still be there:
![图片](https://user-images.githubusercontent.com/9916948/147207043-e68ec5ee-25e6-4f90-b09f-91ad71546269.png)

**To Reproduce**
1. server command (nothing really, just let the xpra service running)
2. client command `xpra.cmd start-desktop ssh://***@*** --exit-with-client --start=***`

**System Information (please complete the following information):**
 - Server OS: Ubuntu 18.04
 - Client OS: Windows 10 LTSB 2016
 - Xpra Server Version v4.2.3-r7
 - Xpra Client Version v4.2.2-r0

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
I am unable to reproduce this bug with the current version (4.3 at time of writing).
How do you terminate the session? I have tried control-c in the windows terminal, and a more regular exit from the system tray.

Note: you may encounter some blurriness instead with 4.3, apply b18d947d1fa8b72a02b29a2daa3332c9611c3632 for that bug, use the beta builds or wait for 4.3.1.

**Comment by mo-han** [comment]
@totaam 
i usually close the remote desktop window, sometimes ctrl-c or tray menu exit.
actually i just encountered "blur issue", since several hours ago, even with my 4.2.2 version.
i'm still trying to figure out the cause / workaround.
