### ISSUE TITLE
xpra "overwrites" existing display number if abstract sockets are disabled

### ISSUE THREAD

**Issue by tomjaguarpaw** [Xpra-org/xpra#3396]
**Describe the bug**

Suppose display 0, attached to a real, physical display devices, is configured to start without an abstract socket (`-nolisten local`). Then if xpra server is started without giving a display number it "overwrites" the existing display filesystem socket and deletes when it closes.

**To Reproduce**

1. Start an X11 server with `startx -- :0 -nolisten local`
2. Start `xpra` with

  ```
  xpra start --attach --exit-with-children --daemon=no --exit-with-client --start-child=xterm
  ```

Then xpra seemingly tries to choose display number 0, despite a display numbered 0 already existing. It fails to launch the client xterm and eventually dies. When it dies it deletes `/tmp/.X11-unix/X0` that does not belong to it!

This does not happen if abstract sockets are enabled (i.e. `-nolisten local` is omitted).

**System Information**

 - OS: Debian Bullseye
 - Xpra Version: xpra v4.4-r30763 (g1cdd8d54f)

(server and client are same machine)

**Comment by tomjaguarpaw** [comment]
In fact the same bug appears with merely `xpra start --daemon=no` (and I guess without the `--daemon=no`, but I didn't try it). Somehow xpra is deciding to use display 0 despite it already being taken.

**Comment by totaam** [comment]
I don't think that this is an xpra bug.
We rely on `Xvfb -displayfd` to choose the display and if this command chooses a display it should not be using then the bug belongs in `Xvfb`.
Also, xpra does not remove the socket itself, `Xvfb` does.
