### ISSUE TITLE
Connect to socket?

### ISSUE THREAD

**Issue by Peter2121** [Xpra-org/xpra#3400]
I use the option `--bind=/var/run/user/1001/xpra/server/1` starting the xpra session in a container (FreeBSD jail). The directory `/var/run/user/1001/xpra/server/` is mapped to the same path on the host, so the socket open by xpra is available on my host as `/var/run/user/1001/xpra/server/1`. How can I attach xpra of the host to this socket? I don't see any option to use **the** socket to attach xpra as client.

**Comment by totaam** [comment]
```shell
xpra attach socket:///var/run/user/1001/xpra/server/1
```
