### ISSUE TITLE
Another received uninterpretable nonsense

### ISSUE THREAD

**Issue by vkz** [Xpra-org/xpra#3403]
**Describe the bug**
I ran into #3402 and installed your fresh beta 4.3.1-r24 for MacOS. Connecting to remote Linux box running Xpra 4.3. I'm always confused who's server and who's client here. So, I'll just go with Mac and Linux. Seriously, which one is Server here?

**To Reproduce**
Mac: `xpra start ssh://user@remote.local/ --start-child=emacs`

After successful authentication (which by the way demands password even when pubkey is in authorized_keys on the remote):
```
2021-12-27 21:02:38,053  SSH: "Warning: cannot load cython bencode module: No module named 'xpra.net.bencode.cython_bencode'"
2021-12-27 21:02:38,086 Error: failed to connect
2021-12-27 21:02:38,086  received uninterpretable nonsense: 'invalid packet header byte: 0x496e76616c696420'
2021-12-27 21:02:38,086  b"Invalid subcommand '_proxy_start'\nUsage:\n\t. ..  'man xpra' or 'xpra --help' for more details\n" (977 bytes)
2021-12-27 21:02:38,086  packet no 0 data: Invalid subcommand '_proxy_start'\nUsage:\n	.xpra- .. see 'man xpra' or 'xpra --help' for more details
```

**System Information (please complete the following information):**
 - Mac 11.6.2 Big Sur
 - Linux 5.14.20
 - Xpra beta 4.3.1-r24 for MacOS
 - Xpra 4.3-r0 on Linux built from https://xpra.org/src/xpra-4.3.tar.gz

**Additional context**
Is this similar to #3349 or something new? 
Could it be this failed attempt to load bencode that's causing this?
This warning from SSH looks to be coming from the remote, since when I attempt to `xpra start :100 --start=emacs` on that Linux box so I can attach from Mac I see this warning. Sadly, I also get `start is not supported by this local installation` - 4.2 allowed that just fine.

**Comment by totaam** [comment]
> Seriously, which one is Server here?

The server exports the virtual screen or window(s), the client displays them.

> Xpra 4.3-r0 on Linux built from ..
> Sadly, I also get start is not supported by this local installation - 4.2 allowed that just fine

Your build is incomplete and is missing at the very least the server component as well as the bencode module, probably much more.
Make sure that all the required dependencies are installed.

**Comment by vkz** [comment]
This was on `GNU Guix` reproduced and reported upstream, confirmed the problem and fixed by rolling to older version. They don't know how to fix it, yet. Good to close.
