### ISSUE TITLE
/bin/bash is hardcoded in server_util.py

### ISSUE THREAD

**Issue by arrowd** [Xpra-org/xpra#3407]
This line has hardcoded "/usr/bash" string: https://github.com/Xpra-org/xpra/blob/master/xpra/server/server_util.py#L88

Bash can be installed in various places, for instance on FreeBSD it is installed to `/usr/local/bin/bash`. Maybe it is possible to use `/bin/sh` instead?

**Comment by totaam** [comment]
It is used for this:
```shell
/bin/bash -c somecommand 1>&2 && someothercommand 
```
Would this file descriptor redirection also work with a plain posix `sh` shell?

**Comment by arrowd** [comment]
> Would this file descriptor redirection also work with a plain posix sh shell?

It seems so, according to FreeBSD man page. It also works at run-time. I didn't test Linux, though.

**Comment by totaam** [comment]
@arrowd how about the commit above? Does that work for you on FreeBSD?

**Comment by arrowd** [comment]
> @arrowd how about the commit above? Does that work for you on FreeBSD?

Works with both `bash` and `sh`. Thanks for the fix!
