### ISSUE TITLE
ssh rsa key not accepted

### ISSUE THREAD

**Issue by kavol** [Xpra-org/xpra#3409]
**Describe the bug**
Trying to connect to a server, my id_rsa is rejected.

**To Reproduce**
1. server command: xpra start :100
2. client command: xpra attach ssh/username@example.org/100

**System Information (please complete the following information):**
 - Server OS: Gentoo Base System release 2.7
 - Client OS: Fedora release 35 (Thirty Five)
 - Xpra Server Version x11-wm/xpra-4.2:0
 - Xpra Client Version xpra-4.2.2-1.fc35.x86_64

**Additional context**
I believe the problem is that xpra tries to use MD5 which is deprecated.

this is how xpra fails:
```
2022-01-04 11:23:15,774 trying public key authentication using ['/home/kvolny/.ssh/id_rsa']
2022-01-04 11:23:15,775 trying '/home/kvolny/.ssh/id_rsa'
2022-01-04 11:23:15,775 trying to load as RSA
2022-01-04 11:23:15,779 loaded RSA private key from '/home/kvolny/.ssh/id_rsa'
2022-01-04 11:23:15,779 auth_publickey using /home/kvolny/.ssh/id_rsa as RSA: MD5:8f:45:58:ed:09:fb:60:d5:6c:71:db:4a:e5:50:a0:5f
2022-01-04 11:23:15,808 Authentication (publickey) failed.
2022-01-04 11:23:15,808 key '/home/kvolny/.ssh/id_rsa' rejected
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/xpra/net/ssh.py", line 642, in auth_publickey
    transport.auth_publickey(username, key)
  File "/usr/lib/python3.10/site-packages/paramiko/transport.py", line 1580, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/lib/python3.10/site-packages/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

and this is how ssh client succeeds:
```
debug1: Next authentication method: publickey
debug1: Offering public key: /home/kvolny/.ssh/id_rsa RSA SHA256:+g8WzIYzBKINju0QNsdxmu+3bsaZKOuETv33pF+hxS8 explicit
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/kvolny/.ssh/id_rsa RSA SHA256:+g8WzIYzBKINju0QNsdxmu+3bsaZKOuETv33pF+hxS8 explicit
debug3: sign_and_send_pubkey: RSA SHA256:+g8WzIYzBKINju0QNsdxmu+3bsaZKOuETv33pF+hxS8
debug3: sign_and_send_pubkey: signing using rsa-sha2-256 SHA256:+g8WzIYzBKINju0QNsdxmu+3bsaZKOuETv33pF+hxS8
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Enabling compression at level 6.
Authenticated to example.org ([xx.xx.xx.xx]:yy) using "publickey".
```

**Comment by totaam** [comment]
> I believe the problem is that xpra tries to use MD5 which is deprecated.

That's down to paramiko, no xpra itself.
It could be #2307, though the version of paramiko in Fedora should be recent enough.
You may be able to get more detailed information from your server's sshd log.

In the meantime, you can just switch back to openssh with `xpra attach --ssh='ssh -x'`

FYI: the xpra 4.2 branch is EOL.

**Comment by kavol** [comment]
> That's down to paramiko, no xpra itself. It could be #2307, though the version of paramiko in Fedora should be recent enough.

well, I don't think so

the other report mentions "invalid key" which is not the case here

the package version is `python3-paramiko-2.7.2-6.fc35.noarch`

> You may be able to get more detailed information from your server's sshd log.

not much ... the unsuccessful attempt is logged as:

`userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
`

while the successful reads:

`Accepted publickey for kavol from xx.xx.xx.xx port yy ssh2: RSA SHA256:+g8WzIYzBKINju0QNsdxmu+3bsaZKOuETv33pF+hxS8`

> In the meantime, you can just switch back to openssh with `xpra attach --ssh='ssh -x'`

or just enter the password :-)

> FYI: the xpra 4.2 branch is EOL.

that's the most recent stable version in both distros ... looking into git, it seems that xpra/net/ssh.py hasn't changed in this part

**Comment by totaam** [comment]
> `userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`

https://github.com/paramiko/paramiko/issues/1734

> that's the most recent stable version in both distros

Yes, known issue:
https://github.com/Xpra-org/xpra/wiki/Distribution-Packages

**Comment by kavol** [comment]
> > `userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`
> 
> [paramiko/paramiko#1734](https://github.com/paramiko/paramiko/issues/1734)

well, [paramiko#1643](https://github.com/paramiko/paramiko/pull/1643) in fact :-)

updating to 2.9.1 solves the issue - thanks and sorry for the noise 'cause at a quick glance, md5 usage in ssh.py looked like the thing
