### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jetamie** [Xpra-org/xpra#3412]
When I execute the following command:
`python3 ./setup.py install  --rpath=/usr/lib64/xpra --pkg-config-path=/usr/lib64/xpra/pkgconfig`
The following error occurs:
![image](https://user-images.githubusercontent.com/46777058/148176537-343c5020-34e7-4a41-b5d8-92c6cb112e42.png)

**Comment by jetamie** [comment]
Source code version: 4.3.1

**Comment by totaam** [comment]
Please don't use screenshots for text!

You also have not specified your distribution or any other details about the steps you followed...

My guess is that this is an old distribution, or one with old turbojpeg headers.
