### ISSUE TITLE
video_subregion.supported is False

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3413]
**Describe the bug**
Video regions are not detected. If I open a website with a video playing, the entire screen is updated. Even the static content.
With `xpra info` I see:
```
client.window.2.video_subregion.auto-refresh-delay=500
client.window.2.video_subregion.counter=0
client.window.2.video_subregion.detection=True
client.window.2.video_subregion.enabled=True
client.window.2.video_subregion.supported=False
client.window.2.video_subregion.video-mode=False
```
**To Reproduce**
1. Start a server with RGB, Png and Webp enabled
2. Run xpra info | grep subregion

**System Information (please complete the following information):**
 - Server OS: Fedora 32
 - Client OS: Electron HTML5 on Windows
 - Xpra Server Version v4.4-r30790
 - Xpra Client Version 4.5.2

**Additional context**
I'm running in docker

**Comment by TijZwa** [comment]
Thanks! Seems to work for me too.

With only rgb+png+webp enabled I get an error, which makes sense.

`2022-01-06 16:25:14,243 Error: no video pipeline options found for BGRA 32-bit at 1889x631
2022-01-06 16:25:14,243 Error: failed to setup a video pipeline for auto encoding with source format BGRA
2022-01-06 16:25:14,243  all encoders:
2022-01-06 16:25:14,243  supported CSC modes:
2022-01-06 16:25:14,243  supported encoders:
2022-01-06 16:25:14,243  encoders CSC modes:`

**Comment by totaam** [comment]
The latest commit is a more correct fix for this issue.

---

> `Error: failed to setup a video pipeline for auto encoding with source format BGRA`

I'll have to check this one.
First, assuming that you were running a browser as a test application, it should have received the opaque-region and switched to `BGRX`.
And even if it didn't, it should probably skip video warnings when there are no video encodings available.

So I am keeping this ticket open for further investigations.

**Comment by totaam** [comment]
@TijZwa Please see https://github.com/Xpra-org/xpra/issues/3410#issuecomment-1008743601
We need to understand why we're wasting time using `BGRA` instead of `BGRX`.

**Comment by TijZwa** [comment]
Thanks! I will look into this.
To make the bug clear: I'm using only RGB+webp+png fixed on 70% as this seems to be the best way to get a great performance with almost no visible compression on the frames, which is perfect for VDI purposes.

But, when watching a video in the browser (on the Xpra server side) the whole page is re-drawn with each video frame being played. I would expect to only receive an webp-image of the video and leave the static parts of the webpage alone. Is this correct? Or does it not work that way for non-video encoders?

**Comment by totaam** [comment]
> I would expect to only receive an webp-image of the video and leave the static parts of the webpage alone

That should usually be the case when the video region is correctly detected, and when it doesn't cover almost all the page.
But you've also disabled all video encodings, even `jpeg`..

Also be aware that browsers often repaint things that don't look like they need repainting.
You can see the repaint events with `-d damage`.
