### ISSUE TITLE
Constrain mouse inside shadow window

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3415]
**Is your feature request related to a problem? Please describe.**
Somewhat related to https://github.com/Xpra-org/xpra/issues/3388, I'd like to be able to constrain the mouse pointer within the Shadow window.

Again related to https://github.com/Xpra-org/xpra/issues/3388, it could be released on a specific shortcut - VM software have already figured this out

**Comment by totaam** [comment]
[Gdk.pointer_grab](https://lazka.github.io/pgi-docs/Gdk-3.0/functions.html#Gdk.pointer_grab) used to do this in GTK2 (pygtk):
```python
import pygtk
pygtk.require("2.0")
import gobject, gtk

def release_me():
    gtk.main_quit()
    return True

def on_destroy(widget):
    gtk.main_quit()

def on_enter(widget, event):
    if event.type == gtk.gdk.ENTER_NOTIFY:
        cursor = gtk.gdk.Cursor(gtk.gdk.PIRATE)     # Pirates!!
        gtk.gdk.pointer_grab(widget.window, False, gtk.gdk.POINTER_MOTION_MASK,
                             widget.window, cursor, long(event.time))
        gobject.timeout_add(15000, release_me)
    else:
        # leaving: won't happen
        gtk.gdk.pointer_ungrab(long(event.time))
    return False

def on_move(widget, event):
    print "move to:", event.x, event.y

def main():
    w = gtk.Window()
    w.set_title("Grabby")

    w.connect('destroy', on_destroy)
    w.connect('enter-notify-event', on_enter)
    w.connect('motion-notify-event', on_move)

    w.show_all()

    gtk.main()

    gdk.pointer_ungrab(long(event.time))

if __name__ == '__main__':
    main()
```

But this doesn't work with GTK3 anymore.

This looks like one of those things that Wayland just could not do (protocol only added in ~2019) and so perhaps they decided that it was X11 that was broken by supporting it. A bit like: [..on wayland host](https://bugzilla.redhat.com/show_bug.cgi?id=1285378#c18) _These semantics don't adapt really well to any other windowing system than X11_ - because MS Windows and MacOS either don't exist or don't matter.

If it means that we have to implement the pointer grab ourselves, so be it.
On MS Windows, that's using [ClipCursor](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clipcursor)
There's bound to be corner cases where we need to release the pointer confinement early: monitor added or removed, etc.

**Comment by totaam** [comment]
Actually, I just remembered that we already have this `ClipCursor` workaround: https://github.com/Xpra-org/xpra/issues/1229#issuecomment-765461491 - f0301e1ab3d3ad3b49b234510809852628dce31b.

But I've just tried it and it doesn't seem to confine the pointer, only trap focus / input.
`-d grab` doesn't show anything useful so I have no idea why it stopped working.
Tested using `--key-shortcut=Shift+F2:toggle_pointer_grab` on MS Windows 10.

**Comment by totaam** [comment]
Minimal reproducer
```python3
#!/usr/bin/env python3

import gi
from xpra.util import AdHocStruct
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
from xpra.platform.win32.gui import pointer_grab

w = Gtk.Window(type=Gtk.WindowType.TOPLEVEL)
w._client = AdHocStruct()
w.show()
GLib.timeout_add(1000, pointer_grab, w)
Gtk.main()
```

**Comment by totaam** [comment]
Just found an old note in #1229 : _virtualbox's mouse integration interferes with pointer grabs, turn it off for testing_
So perhaps everything still works and I'm just testing it wrong!

@stdedos please try `toggle_pointer_grab`.

**Comment by stdedos** [comment]
It works as expected.

However ... at least, you should auto-disengage it on Alt+Tab.
Try it: `enable_pointer_grab`, verify confinement, Alt+Tab, Alt+Tab back, verify confinement: FAIL.
Then, it's not enough to just `toggle_pointer_grab` once (i.e. re-enable it); instead, you have to do `toggle_pointer_grab` twice (once to disable it, once to re-enable it).

... Which will also MAY be more complicated to judge if you need to auto-`disengage_pointer_grab`, if you implement https://github.com/Xpra-org/xpra/issues/3388 (then Alt+Tab is directed to the server, instead of client interpreting it).

**Comment by totaam** [comment]
> Try it: ..

I just don't have any hardware available that runs MS Windows native so I can't try it!
(but I'll take your word for it)

> instead, you have to do `toggle_pointer_grab` twice

The first commit above should fix that (totally untested), the second one is not strictly needed.

We track and manage keyboard grabs and pointer grabs separately and I'm not sure that makes any sense but I don't have to courage to change it, especially if I can't test the only platform that actually honours it properly.

**Comment by stdedos** [comment]
Again, take the VM example (Virtualbox):

"Simple keys" can just pass on as-is. If you'd like to grab the mouse (because I like the constraint), I can. If I need to capture the keyboard (#3388 eg for Alt+Tab), I can

**Comment by totaam** [comment]
@stdedos is the double-grab issue fixed? Can we close this ticket?

**Comment by stdedos** [comment]
Yes, it's all good now! Thanks 😄
