### ISSUE TITLE
`xpra keyboard-test` is not/no longer a subcommand

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3416]
**Describe the bug**

https://github.com/Xpra-org/xpra/blob/master/docs/Features/Keyboard.md#reporting-bugs
> * try the keyboard debugging tool which can be launched using xpra keyboard-test or from the xpra toolbox
```console
➜  ~  xpra --version
xpra v4.4-r30771 (g636b0b8d8)
➜  ~ xpra keyboard-test
Invalid subcommand 'keyboard-test'
Usage:
	xpra 
	xpra start [DISPLAY]
	xpra start-desktop [DISPLAY]
	xpra upgrade [DISPLAY]
	xpra upgrade-desktop [DISPLAY]
	xpra recover [DISPLAY]
	xpra shadow [DISPLAY]
	xpra attach [DISPLAY]
	xpra detach [DISPLAY]
	xpra info [DISPLAY]
	xpra id [DISPLAY]
	xpra version [DISPLAY]
	xpra stop [DISPLAY]
	xpra exit [DISPLAY]
	xpra clean [DISPLAY1] [DISPLAY2]..
	xpra clean-sockets [DISPLAY]
	xpra clean-displays [DISPLAY]
	xpra screenshot filename [DISPLAY]
	xpra control DISPLAY command [arg1] [arg2]..
	xpra print DISPLAY filename
	xpra shell [DISPLAY]
	xpra showconfig
	xpra list
	xpra list-sessions
	xpra list-windows
	xpra sessions
	xpra launcher
	xpra gui
	xpra start-gui
	xpra bug-report
	xpra toolbox
	xpra displays
	xpra docs
	xpra html5
	xpra autostart
	xpra encoding
	xpra path-info
	xpra list-mdns
	xpra mdns-gui

see 'man xpra' or 'xpra --help' for more details
```

**To Reproduce**

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
904187ca281fa446a928f7f0317807a5d8542c0d

**Comment by stdedos** [comment]
btw, do you mind me asking _why_ did you choose to remove them?
and/or why not move them under `xpra toolbox` instead? 😕

**Comment by totaam** [comment]
> btw, do you mind me asking why did you choose to remove them?

Because someone complained that some subcommands were undocumented and I don't have the time to document them.

> and/or why not move them under xpra toolbox instead?

It should be there.

**Comment by stdedos** [comment]
> > btw, do you mind me asking why did you choose to remove them?
> 
> Because someone complained that some subcommands were undocumented and I don't have the time to document them.

I hope that it wasn't me 😅🤣 

> 
> > and/or why not move them under xpra toolbox instead?
> 
> It should be there.

Good to know 🙂
