### ISSUE TITLE
`clipboard_core.py:506`: `UnicodeEncodeError`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3418]
**Describe the bug**
Found the following stacktrace:
```py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_core.py", line 506, in process_clipboard_packet
    handler(packet)
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_core.py", line 475, in _process_clipboard_contents
    self._clipboard_got_contents(request_id, dtype, dformat, raw_data)
  File "/usr/lib/python3/dist-packages/xpra/clipboard/clipboard_timeout_helper.py", line 120, in _clipboard_got_contents
    proxy.got_contents(target, dtype, dformat, data)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/clipboard.py", line 498, in got_contents
    self.set_selection_response(requestor, actual_target, prop, dtype, dformat, data, time)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/clipboard.py", line 468, in set_selection_response
    data = strtobytes(data)
  File "/usr/lib/python3/dist-packages/xpra/os_util.py", line 115, in strtobytes
    return str(x).encode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u279c' in position 0: ordinal not in range(256)
```

in the middle of trying to reproduce https://github.com/Xpra-org/xpra/issues/3417

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Comment by totaam** [comment]
It's not entirely clear where the boundary should be but I think that the commit above is correct.
(this is a server side fix)

**Comment by stdedos** [comment]
It was an one-off for me, so we can close this for now, if you want

**Comment by totaam** [comment]
I've re-checked.
It is correct: we assume that all strings are `utf8`.
`ASCII` is sent as `bytes` because we don't want it converted.

**Comment by shatokhinvlad** [comment]
This commit corrupts clipboard for the such setup:

Ubuntu 20.04
server: `xpra` version `4.3.2-r0-1`
client: `xpra-html5` version `4.5.2-r1107-1`

There is no problem with previous version of xpra:
server: `xpra` version `4.3.1-r0-1`
client: `xpra-html5` version `4.5.2-r1107-1`

Problem description:
Pasted text looks like that:
Ð¢Ñ�Ñ�Ð±Ð° Ð¿Ñ�Ð¾Ñ�Ñ�Ð»Ñ�Ð½Ð°


So, when we reverted changes in `clipboard_core.py`, it works like a charm again

**Comment by totaam** [comment]
@shatokhinvlad I believe that the two commits above should allow both the html5 client and MS Windows clients to work, even if they're running an older version that sends `utf8` data encoded as a string.
