### ISSUE TITLE
xpra-html5 cannot connect to the xpra server in macOS and IOS

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra#3422]
## Describe
`xpra-html5` cannot connect to the xpra server in macOS and IOS clients, Because the `Content-Security-Policy` has not been set in `xpra/net/http_handler.py`.
The default `Content-Security-Policy` value is
```
script-src 'self' 'unsafe-inline' ;
font-src 'self' ;
object-src 'none';
child-src 'none';
worker-src 'self';
frame-ancestors 'none';
form-action 'self';
block-all-mixed-content;
disown-opener;
reflected-xss block;
referrer no-referrer
```
safari and chrome will block the `new Worker('js/lib/wsworker_check.js')` request in macOS and IOS if `child-src` is set to `none`.

Add 
```
self.extra_headers["Content-Security-Policy"] = "script-src 'self' 'unsafe-inline' ; font-src 'self' ; object-src 'none' ; child-src * ; worker-src 'self' ; frame-ancestors 'none' ; form-action 'self' ; block-all-mixed-content; disown-opener; reflected-xss block; referrer no-referrer;"
```
to `/xpra/net/http_handler.py` will fix this bug, but not security.

## To Reproduce
Start a xpra server with `tcp-bind` and connect using iPhone or MacBook.

## System Information
 - Server OS: ubuntu 20.04
 - Client OS: macOS or IOS
 - Xpra Server Version 4.3
 - Xpra Client Version 5.0

**Comment by totaam** [comment]
The CSP is meant to be set by
https://github.com/Xpra-org/xpra/blob/master/fs/etc/xpra/http-headers/10_content_security_policy.txt

But perhaps the MacOS builds fail to locate it at runtime?
Is this what you mean?

**Comment by Vssblt** [comment]
Sorry, I misunderstood. 
I didn't know the `10_content_security_policy.txt` can custom configuration. I misunderstood that this setup requires settings by code.

The default CSP does not allow macOS and IOS to connect to the server.

**Comment by totaam** [comment]
@Vssblt what changes do I need to make to this file to make it work by default?
MacOS users should be hitting the same issue when connecting to Linux servers since those use the same config file but I haven't heard any complaints.
Perhaps it isn't installed correctly on MacOS?

**Comment by Vssblt** [comment]
**Another CSP bug in the chrome by default CSP settings.**

[click for the video](https://vssblt.com/1.webm)

**error:**
```
Unrecognized Content-Security-Policy directive 'disown-opener'.
Unrecognized Content-Security-Policy directive 'reflected-xss'.
Unrecognized Content-Security-Policy directive 'referrer'.
```

**google solution:**

![图片](https://user-images.githubusercontent.com/35415088/149297157-e0faa69a-1a96-4c88-8369-d71d1bc46dd1.png)

**Comment by Vssblt** [comment]
> **Another CSP bug in the chrome by default CSP settings.**
> 
> [click for the video](https://vssblt.com/1.webm)
> 
> **error:**
> 
> ```
> Unrecognized Content-Security-Policy directive 'disown-opener'.
> Unrecognized Content-Security-Policy directive 'reflected-xss'.
> Unrecognized Content-Security-Policy directive 'referrer'.
> ```
> 
> **google solution:**
> 
> ![图片](https://user-images.githubusercontent.com/35415088/149297157-e0faa69a-1a96-4c88-8369-d71d1bc46dd1.png)

Client OS: Ubuntu 20.04


I'm guessing the bug on MacOS and IOS is also due to the browser version.

**Comment by Vssblt** [comment]
CSP errors in macOS safari:

![782_1642066012_hd](https://user-images.githubusercontent.com/35415088/149303063-57cf10ad-5556-46a4-827e-5b1326ce7aef.jpeg)

safari version: 15.0 (16612.1.29.41.4, 16612)

**Comment by Vssblt** [comment]
This works in both chrome and safari.
```
Content-Security-Policy: script-src 'self' 'unsafe-inline' ; font-src 'self' ; object-src 'none' ; child-src * ; frame-ancestors 'none'; form-action 'self' ; block-all-mixed-content;
```

**Comment by totaam** [comment]
Please use links, not images.
Here it is: [Unrecognized content security policy directives: disown-opener, reflected-xss, referrer](https://stackoverflow.com/questions/50575265/)

What a royal pain.
The commit above replaces the directives that have been renamed.
https://github.com/Xpra-org/xpra-html5/commit/4f8a95057048989fae12e9389b00095dd84da06d converts `disown-opener` to individual link attributes. (which seems completely backwards to me)

As for `child-src`, the problem is that Safari doesn't understand `worker-src` which should take precedence... So the next commit loosens the policy for Safari.

I think this should do it.
@Vssblt can you confirm?

**Comment by Vssblt** [comment]
I tested CSP settings on Linux chrome and it throw out an error.
 ```
The Content-Security-Policy directive name 'Referrer-Policy:' contains one or more invalid characters. Only ASCII alphanumeric characters or dashes '-' are allowed in directive names.
```
I think `Referrer-Policy` is a separate header, rather than a part of CSP.
`Referrer-Policy: no-referrer` should be on the next line of `Content-Security-Policy` and remove the semicolon.

like this:
```
Content-Security-Policy: script-src 'self' 'unsafe-inline' ; font-src 'self' ; object-src 'none' ; child-src 'self' ; worker-src 'self' ; frame-ancestors 'none' ; form-action 'self' ; block-all-mixed-content; 
Referrer-Policy: no-referrer
```

**Comment by totaam** [comment]
@Vssblt I believe the commit above does this.
FYI: if this is not correct, you can just edit the file at https://github.com/Xpra-org/xpra/blob/master/fs/etc/xpra/http-headers/10_content_security_policy.txt and this will create a PR.
