### ISSUE TITLE
xpra on OpenBSD - steps to get there

### ISSUE THREAD

**Issue by vkz** [Xpra-org/xpra#3429]
NB: these are late-night notes, just to get the ball rolling. Will see tom if need to improve and update.

**Describe the bug**
Not "stop the show" stuff but a couple of corner cases spotted while getting xpra to serve OpenBSD. I understand it isn't one of the supported platforms, but it does come up in commits and looks like maintainers do build for it every now and again. Here's what I did to get it to work. And corner cases spotted, questions that came up.

**To Reproduce**
Lets try to get some of those deps.
```
doas pkg_add glib2
doas pkg_add 'gtk+3'
doas pkg_add py3-opengl                     
doas pkg_add py3-rencode
doas pkg_add py3-lz4 
doas pkg_add py3-cryptography
doas pkg_add py3-zeroconf
doas pkg_add py3-dbus
doas pkg_add py3-netifaces
doas pkg_add py3-paramiko
doas pkg_add py3-Pillow
doas pkg_add x264
doas pkg_add libvpx
doas pkg_add libwebp
doas pkg_add py3-cython
doas pkg_add py3-cairo
doas pkg_add py3-gobject3
doas pkg_add pandoc
```

Appears we need `gcc` to build. So, first problem is actually finding it on OpenBSD - looks like a bug on their side.
```
pkg_info -Q gcc
# will show you what's available
doas pkg_add 'gcc-11.2.0p0'

# package installs cleanly, but `which gcc` won't find it. For some ungodly reason it installs it as something like:
/usr/local/bin/x86_64-unknown-openbsd7.0-gcc-11.2.0
```
Here's our first `xpra` (or its dependency) issue: you can't just willy-nilly `ln -s` to e.g. `~/bin/gcc`, someone hardcodes gcc path to `/usr/local/bin/gcc` or one of the known PATHs instead of trying `gcc` and relying that it is found on your PATH. So:
```
ln -s /usr/local/bin/x86_64-unknown-openbsd7.0-gcc-11.2.0 /usr/local/bin/gcc
```

Finally, lets install it xpra:
```
git clone https://github.com/Xpra-org/xpra
cd xpra
CC=gcc doas bash -c 'python3 ./setup.py install --prefix=/usr/local --record=files.txt'
```
couple of issues that I ran into. that `CC=gcc` is important. I believe `setup.py` sets `CC` correctly, but someone down the line ignores it simply invokes system `cc` which on OpenBSD defaults to `clang` which errors out on some code.

Don't do `--prefix=/usr`. If you do, python3 won't be able to find `xpra` modules, which you can fix by exporting `PYTHONPATH=/usr/lib/python3.8/site-packages` or so you think. I was unfortunate enough to walk right into that problem and then discovered another xpra corner case. When your client connects to the server, `xpra` will simply rely on `sys.path` and completely ignore `PYTHONPATH` that's correctly set in your `~/.bashrc`. Just go with `--prefix=/usr/local` and it'll work.

Finally, `emacs` on the remote pops up. Bit slow and mid-session xpra on the client reports network is congested or slow and offers to limit bandwidth etc. Not sure why seeing how I'm connecting to a VM running in QEMU - network is simulated locally.

So, finally. Would like to improve networking and maybe see if picture quality / drivers maybe improved. I think server-side reported no *dummy* driver or smth, other warnings.

Would maintainers chime in if they have experience building on OpenBSD and getting good results?

**System Information (please complete the following information):**
 - Server OS: OpenBSD 7.0
 - Client OS: Mac OSX Big Sur 11.6.2
 - Xpra Server Version xpra v4.4-r30834 (gaa8f907e1)
 - Xpra Client Version xpra v4.3.1-r24

**Additional context**
This is

**Comment by totaam** [comment]
> but someone down the line ignores it simply invokes system cc which on OpenBSD defaults to clang which errors out on some code.

It would be good to know where, we could fix that.
Also, building with clang should work. I've just rebuilt everything in master with it.
That said, you're right `CC=gcc` should be honoured everywhere and mixing `gcc` and `clang` in the same build is not recommended.

> When your client connects to the server, xpra will simply rely on `sys.path` and completely ignore `PYTHONPATH` that's correctly set in your `~/.bashrc`

How so?

> Finally, emacs on the remote pops up. Bit slow...

The way emacs repaints the screen is very broken.

> client reports network is congested

Could be CPU or network performance issue.

> I think server-side reported no dummy driver or smth, other warnings.

Xdummy is not essential. Can you post the other warnings?

> Would maintainers chime in if they have experience building on OpenBSD and getting good results?

I haven't tried it in years.  
It used to work OK but it was always quite slow compared to Linux and I can't remember why. Perhaps X11 is missing the `XShm` extension?

**Comment by totaam** [comment]
Not head back so impossible to improve OpenBSD support.
