### ISSUE TITLE
Nonsense of forward-xdg-open when start-desktop

### ISSUE THREAD

**Issue by dantefff** [Xpra-org/xpra#3433]
**Describe the bug**
When we open a full desktop with start-desktop there is little sense on making the xdg-open interception so start-desktop should make forward-xdg-open=no the default forward-xdg-open option

**To Reproduce**
- Open the server and client with the all-in-one command  
    `xpra start-desktop --start-child=fluxbox`
- In a terminal in the server type:
    `xdg-opwn any-file.html`

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Client OS: Ubuntu Focal
 - Xpra Server Version v3.0.13-r28292
 - Xpra Client Version 4.3.1

**Additional context**

**Comment by totaam** [comment]
@dantefff the commit above does what you want.

Thanks for the bug report!

**Comment by dantefff** [comment]
Wow! That's responsiveness!!! Thanks you very much @totaam !!
