### ISSUE TITLE
xpra version from client won't use client connections

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3434]
**Describe the bug**
`xpra version` requires a server. Specifying a local client session fails to put the named session to use. Asking for version of a legitimate remote client with ssh syntax doesn't identify which local connection it's using.

How do I learn which local client is connected to which remote server?

**To Reproduce**
1. Any server startup(s)
2. Any client connection(s)
3. `xpra version` in several variations, both right and wrong. Why isn't the local list of sessions usable to reach the indicated server?
```
$ xpra version
xpra initialization error:
 cannot find any live servers to connect to
$ xpra list
Found the following xpra sessions:
/run/user/5271/xpra/clients:
	LIVE session at :1483882
	LIVE session at :1483883
	LIVE session at :1484900
	LIVE session at :1798877
	LIVE session at :1973468
	LIVE session at :1976098
	LIVE session at :53409
	LIVE session at :54018
	LIVE session at :71932
$ xpra version :53409
server socket for display :53409 not found
 waiting up to 20 seconds
Warning: failed to connect:
 cannot find live server for display :53409
$ xpra version ssh://major/73
Connected (version 2.0, client OpenSSH_8.7)
Authentication (publickey) successful!
4.4-r30818 (gc7abc26db)
SSH EOF on stderr of run-xpra
```

**System Information (please complete the following information):**
F35 + 4.4-10.r30839 at both ends.

**Comment by totaam** [comment]
Client sockets were added much later and many commands do not make sense for these sockets and so the commands exclude client sockets when locating targets.

`xpra version` is an exception and needs to be added, until then you can point to the full path:
```shell
xpra version /run/user/$UID/xpra/clients/$HOSTNAME-$CLIENTPID
```

> How do I learn which local client is connected to which remote server?

`xpra version` won't help you with that.
I think that the information should be included in `xpra info` however.

**Comment by totaam** [comment]
Fix is in the commit above, the following subcommands will search the `client-socket-dirs` for sockets to connect to: `info`, `id`, `connect-test`, `control`, `version`, `detach`, `show-menu`, `show-about`, `show-session-info`

**Comment by totaam** [comment]
And... this caused problems: when I run `xpra info` with a single server running, it finds both the client and the server and refuses to choose one... The commit above fixes that.
