### ISSUE TITLE
PolicyKit integration

### ISSUE THREAD

**Issue by brainchild0** [Xpra-org/xpra#3436]
Presently, when the menu is used to launch an application that invokes a request to PolicyKit, such that normally a prompt would appear for a user password, the application is effectively not launched and no password prompt is given.

As a workaround, it is necessary to launch a terminal, then launch the application through `sudo`. If the application is launched from a terminal without `sudo`, an error returns, such as "Error executing command as another user: No authentication agent found."

Proposed is providing a graphical password prompt, rendered by the local software, for gaining authorization for the privileged operation.

**Comment by totaam** [comment]
Use `--start-via-proxy=yes` to get a proper session registered with `logind`.
This will call `pam` and should get `PolicyKit` to prompt on the correct display.

If you find any useful documentation on what `PolicyKit` does and how, please add it here.

**Comment by brainchild0** [comment]
Is there a reason why this value is not the default?

**Comment by totaam** [comment]
> Is there a reason why this value is not the default?

It used to be but there were too many problems with distributions messing up the service or changing pam configs, etc.
