### ISSUE TITLE
"Favorites", "recents", and search features in application menu

### ISSUE THREAD

**Issue by brainchild0** [Xpra-org/xpra#3437]
Many   launchers running on local desktop environments supply convenience features for  choosing applications.

A few examples include allowing the user to choose applications through the following means:

1. From a list of favorite applications,  provided with greater accessibility than the items in the full menu system  for  installed applications.
2. As above,  but from an automatically-generated list based on recent usage.
3.  By searching based on text prompt. This feature is different than running a command, instead selecting an application by matching an input string to the application name (which may be different from the command name).

Proposed is adding the three features to the    menu in Xpra.

**Comment by totaam** [comment]
Please provide a PR.
