### ISSUE TITLE
Not able to frame Xpra in another browser window anymore

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3442]
Hi,

We always used to be able to frame the Xpra window in another browser window, but since the 1 to 3 weeks (unsure exactly when due to the holidays) it stopped working and we get this error in the console:
`Refused to frame 'xxx' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

I don't know if it's related to #3422 ?

I noticed that if I remove `frame-ancestors 'none'` from `10_content_security_policy.txt`, it works. This is strange since this isn't a recent addition.

This happens on Chrome executed from a Mac. Xpra is version 4.5.2 ran on ubuntu 20.04, official Xpra .deb package.

**Comment by totaam** [comment]
That's working as intended, if you need to embed the client then you will need to loosen the CSP.

**Comment by iDmple** [comment]
Fair enough, just unsure why it previously worked then!
