### ISSUE TITLE
It is possible to limit the frame rate?

### ISSUE THREAD

**Issue by Vssblt** [Xpra-org/xpra#3443]
It is possible to limit the frame rate?
Drop some frames to reduce bandwidth and CPU usage.

**Comment by totaam** [comment]
Use a lower `speed` or `min-speed`, that should do it.
Otherwise, you could try the commit above:
```shell
xpra attach --env=XPRA_VREFRESH=10 ...
```
This should limit the refresh rate to 10 fps.

**Comment by totaam** [comment]
This is superseded by #3600.
