### ISSUE TITLE
Invalid self-signature on user ID for PGP key

### ISSUE THREAD

**Issue by ritzmann** [Xpra-org/xpra#3446]
**Describe the bug**

I am trying to import the PGP key for the Debian Bullseye repository but GnuPG 2.2.27 insists that the user ID is not properly signed:

```
$ gpg --verbose --no-default-keyring --keyring=~/xpra.gpg --recv-keys F18AD6BB
gpg: data source: https://162.213.33.9:443
gpg: armor header: Version: Hockeypuck ~unreleased
gpg: armor header: Comment: Hostname:
gpg: key 0x18ADB31CF18AD6BB: number of dropped non-self-signatures: 5
gpg: pub  dsa1024/0x18ADB31CF18AD6BB 2007-04-18  Antoine Martin <antoine@nagafix.co.uk>
gpg: Note: signatures using the SHA1 algorithm are rejected
gpg: key 0x18ADB31CF18AD6BB: 15 bad signatures
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB: skipped user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: skipped user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: skipped subkey
gpg: key 0x18ADB31CF18AD6BB: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

I was using `hkps://keyserver.ubuntu.com` as keyserver.

A manual download of the key from https://xpra.org/gpg.asc yields the same issue when imported:

```
$ gpg --verbose --no-default-keyring --keyring=~/xpra.gpg --import ./gpg.asc
gpg: pub  dsa1024/0x18ADB31CF18AD6BB 2007-04-18  Antoine Martin <antoine@nagafix.co.uk>
gpg: Note: signatures using the SHA1 algorithm are rejected
gpg: key 0x18ADB31CF18AD6BB: 2 signatures not checked due to missing keys
gpg: key 0x18ADB31CF18AD6BB: 7 bad signatures
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB: invalid self-signature on user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: invalid subkey binding
gpg: key 0x18ADB31CF18AD6BB: skipped user ID "Antoine Martin <antoine@nagafix.co.uk>"
gpg: key 0x18ADB31CF18AD6BB: skipped user ID "[jpeg image of size 4992]"
gpg: key 0x18ADB31CF18AD6BB/0x00D777F76E23E963: skipped subkey
gpg: key 0x18ADB31CF18AD6BB: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

**To Reproduce**

see above

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Client OS: n/a
 - Xpra Server Version 4.3.1
 - Xpra Client Version n/a

**Additional context**

**Comment by totaam** [comment]
Is there a specific reason why you're doing things this way instead of following https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions ?
This works OK:
```shell
wget -q https://xpra.org/gpg.asc -O- | sudo apt-key add -
```

My guess is that the problem comes from `signatures using the SHA1 algorithm are rejected`.
The big problem is that it doesn't look like we can have two signatures for the same key? (and why not?!)
Changing the key is not an option as there are very many systems out there relying on the existing one.

**Comment by ritzmann** [comment]
```
$ man apt-key
...
Use of apt-key is deprecated
...
apt-key(8) will last be available in Debian 11 and Ubuntu 22.04.
...
```

I believe you are on the right track with these SHA-1 signatures. There might be a way out of that because it looks to me like there are at least 15 signatures but you must remove the obsolete/insecure SHA-1 signatures. At least this is how I understand [Fixing old SHA1-infested OpenPGP keys](https://blog.bmarwell.de/en/fixing-old-sha1-infested-openpgp-keys/). I also checked the German article that is referenced and it is vital not to skip the expiration step because that forces gpg to generate new secure signatures. The expiration value is not important and can be changed back again to the original value.

**Comment by ritzmann** [comment]
```
$ man apt-key
...
Use of apt-key is deprecated
...
apt-key(8) will last be available in Debian 11 and Ubuntu 22.04.
...
```

I believe you are on the right track with these SHA-1 signatures. There might be a way out of that because it looks to me like there are at least 15 signatures but you must remove the obsolete/insecure SHA-1 signatures. At least this is how I understand [Fixing old SHA1-infested OpenPGP keys](https://blog.bmarwell.de/en/fixing-old-sha1-infested-openpgp-keys/). I also checked the German article that is referenced and it is vital not to skip the expiration step because that forces gpg to generate new secure signatures. The expiration value is not important and can be changed back again to the original value.

**Comment by totaam** [comment]
Done. Thanks for the details!

Until the key propagates through the pgp network. Re-importing the key fixes things:
```shell
wget -q https://xpra.org/gpg.asc -O- | sudo apt-key add -
```
(yes, `apt-key` is deprecated - adding `signed-by` to the repositories is going to take a big chunk of time that I don't have right now)

**Comment by ritzmann** [comment]
Excellent, thanks, I just tried without `apt-key` and it works when you convert the key to the expected format:
```
$ curl -O https://xpra.org/gpg.asc
$ gpg --no-default-keyring --keyring=./xpra-v1.gpg --import ./gpg.asc
$ gpg --no-default-keyring --keyring=./xpra-v1.gpg --export > xpra.gpg
$ sudo mv xpra.gpg /etc/apt/trusted.gpg.d/
```

**Comment by totaam** [comment]
And, as I had feared, this is causing pain: #3499

**Comment by totaam** [comment]
What a mess. To try to avoid breaking too many existing installations and instructions, I have now reverted part of the changes in this ticket:
https://xpra.org/gpg.asc points to the older version of the key again. Details here:
https://github.com/Xpra-org/xpra/issues/3499#issuecomment-1077136429
And updated the download instructions:
https://github.com/Xpra-org/xpra/wiki/Download/62889d4845e76f4dc6356c79ce74f43654c7145f

**Comment by totaam** [comment]
See also #2968 and #1830
