### ISSUE TITLE
Missing code signature in MacOS downloads 4.3.2

### ISSUE THREAD

**Issue by suschizu** [Xpra-org/xpra#3451]
**Describe the bug**
I received a warning that the code signature has changed in version 4.3.2 (so is missing in this case)
`EXPECTED Antoine Martin (N3UFHUL6R9) but FOUND xpra.org `

**To Reproduce**
codesign -dvv [path_to_app]
output: `[…]/Xpra.dmg: code object is not signed at all`

**System Information (please complete the following information):**
MacOS version 4.3.2 downloads:
https://xpra.org/dists/MacOS/x86_64/Xpra.dmg
and
https://xpra.org/dists/osx/x86_64/Xpra.pkg

**Comment by totaam** [comment]
Thanks for the report, this should be fixed in: cbbc4af76e85c35ff57f7e7b6f35536a257f506b.
At least, this is what I see during the build:
```
File size: 59987352 bytes, Checksum: CRC32 $57BFE519
Sectors processed: 1048656, 447409 compressed
Speed: 41.0Mbytes/sec
Savings: 88.8%
created: /Users/macos/xpra/packaging/MacOS/image/Xpra-Python3-x86_64-4.4-r30898.dmg
Signing with key 'xpra.org'
image/Xpra-Python3-x86_64-4.4-r30898.dmg: signed  []
Copying Xpra-Python3-x86_64-4.4-r30898.dmg to the desktop
Size of disk image:  58M	image/Xpra-Python3-x86_64-4.4-r30898.dmg
```
Unlike the PKG, which cannot be signed without paying Apple (!) https://github.com/Xpra-org/xpra/issues/3340#issuecomment-964781418

You can find a beta 4.4 build with this change here: https://xpra.org/beta/MacOS/

FYI: the links you have posted are identical, `osx` is a symlink for `MacOS`.

**Comment by totaam** [comment]
@suschizu I assume this worked for you.

**Comment by suschizu** [comment]
yes - thank you - sorry for the late reply!

**Comment by andlabs** [comment]
I'm seeing a different issue: while the *app bundle* is signed, the *individual binaries within* (under Contents/Resources/bin) aren't. We deploy a [app binary allowlisting service](https://github.com/google/santa) that checks each individual binary for codesigning, and it doesn't like the current Xpra setup as a result. Can the app bundle codesigning key be used for codesigning the constituent binaries?

I can also make this a separate issue if desired.

**Comment by totaam** [comment]
> while the app bundle is signed, the individual binaries within aren't

@andlabs this is a separate issue.

> I think it's only feebased when you publish inside the App Store - but not 100% sure about this

Sadly, no. You have to pay a fee to skip the scary warnings. Extortion comes to mind.

**Comment by andlabs** [comment]
Thanks; split into #3765
