### ISSUE TITLE
Hardware acceleration with virgl

### ISSUE THREAD

**Issue by mviereck** [Xpra-org/xpra#3452]
Currently I run some tests with [virgl](https://gitlab.freedesktop.org/virgl/virglrenderer) that allows sort of hardware acceleration for Xvfb. (Not to confuse with `virtualgl`).

It seems to work with xpra, just don't expect too much. I just want to tell you of this possibility. Maybe this is of interest for you.

My setup on debian:
 - Install `virgl-server`
 - Run `virgl_test_server` (X clients need access to socket `/tmp/.virgl_test`)
 - Set environment variables for X clients `export LIBGL_ALWAYS_SOFTWARE=1 GALLIUM_DRIVER=virpipe`
 - Run xpra with e.g. `glxgears`.

On the good side:
 - It seems to work, CPU usage of glxgears is rather low.
 - Indeed it uses the GPU. (checked)

On the bad side:
 - CPU usage of `virgl_test_server` is high.
 - Acceleration is not as good as one could expect.

----------
The fps of glxgears is high (as it is with a regular Xvfb setup). If it could be set to the framerate of the monitor (normally about 60 fps), the CPU usage could be ok. 
Do you know a way to set the fps for MESA GALLIUM drivers in general (independent from virgl)?

**Comment by totaam** [comment]
> If it could be set to the framerate of the monitor (normally about 60 fps), the CPU usage could be ok

> Do you know a way to set the fps for MESA GALLIUM drivers in general (independent from virgl)?

I really don't know how to do that but I would be very interested in finding out!
(ideally something that can be updated at runtime as clients with different displays come and go)

**Comment by totaam** [comment]
Closing as I don't think there are any actions to take in xpra.
