### ISSUE TITLE
nvidia driver 510 troubles

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3456]
**Describe the bug**
Just installed driver 510 from rpmfusion on several servers. Two xpra problems:
[1] opengl probe failure.
![screenshot7](https://user-images.githubusercontent.com/7548920/152661178-435422d0-57f7-4f95-b36d-61f692abe918.png)

[2] repetitious whining on mouse entry/exit to some windows:
```
2022-02-05 17:31:58,238 [ph]	Error: failed to create csc instance <class 'xpra.codecs.csc_swscale.colorspace_converter.ColorspaceConverter'>
2022-02-05 17:31:58,238 [ph]	 for GBRP to BGRX: 'int' object is not iterable
```

**To Reproduce**
any server and client startups
on client attach, both of these occur. the 1st occurs once, the other is ongoing on entry/exit of mouse from some windows.

**System Information (please complete the following information):**
 f35 and 4.4-10.r30897 all around.

**Comment by totaam** [comment]
The `probe crash` is probably because you haven't rebooted yet or because there's a driver conflict.

For the `failed to create csc instance`, can you get the `-d video` stacktrace please?

**Comment by karlkleinpaste** [comment]
Ignore the entire report. Apologies, you're right, I hadn't rebooted the client, and after doing that, both conditions are no longer seen.
