### ISSUE TITLE
ModuleNotFoundError: No module named 'xpra'

### ISSUE THREAD

**Issue by holongate** [Xpra-org/xpra#3460]
**Describe the bug**
Each time an xpra command is issued, the following error is raised:
Traceback (most recent call last):
  File "/usr/bin/xpra", line 5, in <module>
    from xpra.platform import init, set_default_name
ModuleNotFoundError: No module named 'xpra'

**To Reproduce**
1. server command
any xpra start variant
2. client command
xpra gui or any xpra start variant
3. specific action to trigger the bug

**System Information (please complete the following information):**
 - Server OS: Kubuntu 20.04.LTS
 - Client OS: Kubuntu 21.10
 - Xpra Server Version v4.3.2-r0
 - Xpra Client Version v4.3.2-r0

**Additional context**
The xpra server/client communication seems to work as expected... so not sure if this is a managed error or not.
I use Kubuntu if that matter, so the win manager is Kwin.

**Comment by neilsimp1** [comment]
I was experiencing this recently on Arch Linux ARM: https://archlinuxarm.org/forum/viewtopic.php?f=9&t=15871&p=68901#p68901

A recent python update has fixed this error, but my xpra sessions are being created in an UNKNOWN state and so I cannot connect applications to it.

**Comment by holongate** [comment]
I think I found something interesting:
On one machine I uninstalled xpra then just did 'apt install xpra' instead of adding the key/repo as per the xpra docs and it's now ok.
On the other, I deactivated the conda env before running xpra and it seems to be ok.
I guess there is some subtle differences when installing from the ubuntu repo and the xpra one that generates some conflicts in one case but not the other...

**Comment by totaam** [comment]
```
ModuleNotFoundError: No module named 'xpra'
```
This means that xpra is not installed.
Please double check your installation steps.

**Comment by holongate** [comment]
@totaam As per thee traceback, xpra was installed following this site documentation, the /usr/bin/xpra client just not found its libraries.
However, even with this error, 'xpra start' seemed to work, which led to my hypothesis about some interactions with my Python setup.

**Comment by totaam** [comment]
> However, even with this error, 'xpra start' seemed to work

The `/usr/bin/xpra` script used to try both python3 and python2.
Perhaps you have an old version installed.
The correct script no longer does:
https://github.com/Xpra-org/xpra/blob/7193c400c05ef82228e67b1d6ab0c078e2364296/fs/bin/xpra#L1-L10
