### ISSUE TITLE
Flickering/Laggy Window When Using Atom Over Xpra

### ISSUE THREAD

**Issue by cr1901** [Xpra-org/xpra#3461]
**Describe the bug**
While using Atom over Xpra on Windows 10, after enough scrolling, text-highlighting, or window-resizing, Xpra will begin to update the Atom window several times going between old and current states before settling on the new/correct window state. This lag/spurious updating makes Atom unusable over Xpra. 

I have provided a video of the behavior [here](http://gopher.wdj-consulting.com:70/store/xpra-one-click-release.mkv) (I don't have a good way to convert from MKV, so a link will have to do for now). In the video, I left-click the mouse, highlight some text, and then release the mouse _exactly once_. The selected text then flickers/goes between selected/unselected states multiple times before the text is unselected.

**To Reproduce**
1. server command: `PYTHONPATH=/home/william/Projects/remote/xpra/install/lib/python3.8/site-packages ./xpra/install/bin/xpra start --daemon=no :100`
2. client command: `./Xpra-Launcher /c/Users/William/LivingRoom.xpra`, and then click `Connect`.
3. Run `atom &` from `xterm`. Resize the window from minimized to maximized a few times, while some text is selected. Flickering will start to occur as demonstrated in the video.

**System Information:**
 - Server OS: `Linux xubuntu-dtrain 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Client OS: `Microsoft Windows [Version 10.0.19044.1526]`
 - Xpra Server Version: `xpra X11 seamless version 4.4-r28477 (g5ceb23424) 64-bit` (**The commit shown is wrong, even after doing a clean build**- it's actually `4d904a3c31`).
 - Xpra Client Version: `4.4-r30952 (g4d904a3c3)`

**Additional context**
* Issue was bisected to start occurring on this commit: https://github.com/Xpra-org/xpra/commit/3d8fe70ae2ade01f49186b98266dfc4931f34cc4
* Based on `--env=XPRA_SAVE_TO_FILE=1`, the server does not exhibit flickering (i.e. the server is _not_ repeatedly sending old and new screen states), and the problem is client-side. I could not get meaningful output (zero-sized `vp9` files) from running `--env=XPRA_SAVE_TO_FILE=1` on the client.
* **Workaround**: The flickering does _not_ occur if I start `xpra` with `./Xpra attach ssh://william@192.168.1.168`. _Only_ when I start the client through `Xpra-Launcher` does the flickering occur.
* Client `xpra.conf`:
   ```
   ssh=C:\msys64\usr\bin\ssh.exe
   encoding=png
   opengl=no
   ```

* Server `xpra.conf`
   ```
   start-child = xterm -geometry 150x43 -fg grey -bg black
   start = xrdb -merge ~/.Xresources
   # start = atom
   exit-with-children = yes
   ```
* [Example client `xpra info`](http://gopher.wdj-consulting.com:70/paste/launcher-info.txt)
* [Example server `xpra info`](http://gopher.wdj-consulting.com:70/paste/server-info.txt)

**Comment by totaam** [comment]
Could be related to #3410

**Comment by totaam** [comment]
Please try removing `encoding=png` and `opengl=no`.
Does either help?

**Comment by cr1901** [comment]
I am able to duplicate the problem with the following:
* ```
  # encoding=png
  opengl=no
  ```

When `# opengl=no` is commented out, regardless of `encoding` setting, I get a different type of display problem that's probably not relevant to my current issue:
![Xpra-Launcher_9mnLf4Cwcd](https://user-images.githubusercontent.com/6418027/154832522-6dd2dc19-6719-49e7-9df0-037d02a921d0.png)

![image](https://user-images.githubusercontent.com/6418027/154832603-4bb7494e-4c08-4630-aa8f-b49550ba3abd.png)

**Comment by totaam** [comment]
What am I looking at?
What should I be seeing instead?
Is your initial issue occurring with `opengl=no`?

**Comment by cr1901** [comment]
## `opengl=yes`
>What am I looking at?

Faded colors in the Atom window, along with some of the Atom window just not being rendered at all and showing the layer behing the Window (my desktop) instead.

>What should I be seeing instead?

Colors should not be faded and the Atom window should not have transparent sections where the layer beneath the Atom window is visible.

**I do not believe this is related to my initial issue, I just posted an image for future reference**

## `opengl=no`
>Is your initial issue occurring with opengl=no?

Yes.

**Comment by totaam** [comment]
Forgot to mention that you can run the client with `XPRA_PAINT_BOX=1 xpra attach ..` to see which encodings are causing problems.
A screenshot with those colors would help:
https://github.com/Xpra-org/xpra/blob/bfd528f22f4b8ff11f9912c17d0fe3e7cdcddd0f/xpra/client/paint_colors.py#L8-L26

**Comment by cr1901** [comment]
After a hardware failure are replacement with a new disk, I cannot duplicate this issue anymore. I am closing, and will reopen if I can duplicate the symptoms.

On this current machine, settings are now:

```
ssh=C:\msys64\usr\bin\ssh.exe
opengl=no
```

(i.e. no more `encoding=png`. But I _could_ dup with `encoding=png` commented out on the old machine anyway, so I don't think it matters).

**Comment by totaam** [comment]
FYI: `ssh=C:\msys64\usr\bin\ssh.exe` only works if the host is already known and the authentication uses keys as xpra is unable to run openssh with access to the terminal for prompts on MS Windows.
