### ISSUE TITLE
xpra control toggle_readonly ?

### ISSUE THREAD

**Issue by open-contracts** [Xpra-org/xpra#3466]
I'd love to be able to activate the --readonly flag from the server at runtime, disabling all client input for a given session for some period, and afterwards re-enabling it again. Is this already possible via the xpra control channel?

**Comment by totaam** [comment]
Done in the trivial commit above, example:
```shell
xpra control :100 readonly true
```

**Comment by open-contracts** [comment]
thanks a lot <3
