### ISSUE TITLE
Unable to get the server and client side using xpra

### ISSUE THREAD

**Issue by bishnoi29nitin** [Xpra-org/xpra#3472]
**Describe the bug**
I was trying to use xpra for the first time but facing some issues, not able to start the session.

I am using the xpra version - xpra v3.1.2-r25. when I run the xpra command on the server it does start the xpra session and gives xpra initialization error. On the server side I am trying to create a proxy server so that manys user can get connected to the server.

Below mentioned details are log file for the command - xpra start --ssl-cert=/usr/share/xpra/www/xpra-ssl.cert --ssl=on --start="/opt/ohpc/pub/intel_2018/vtune_amplifier_2018.3.0.558279/bin64/amplxe-gui /scratch_ib/nitin/ParaDE/visualizer/PI_Calculation-OpenMPwithMPI/r000hs.ssl-hn"

022-02-07 22:45:55,763 cannot access python uinput module:^[[0m
2022-02-07 22:45:55,763  No module named uinput^[[0m
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running

X.Org X Server 1.20.4
X Protocol Version 11, Revision 0
Build Operating System:  3.10.0-957.1.3.el7.x86_64
Current Operating System: Linux ssl-hn 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-862.14.4.el7.x86_64 root=UUID=1d198f74-6a8f-41be-bc5f-8c4bfdd9e0ed ro crashkernel=auto rhgb quiet LANG=en_US.UTF-8
Build Date: 04 January 2022  05:44:44PM
Build ID: xorg-x11-server 1.20.4-17.el7_9
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/run/user/1020/xpra/Xorg.S200200.log", Time: Mon Feb  7 22:45:55 2022
(++) Using config file: "/etc/xpra/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/bin/Xorg: symbol lookup error: /usr/lib64/xorg/modules/input/mouse_drv.so: undefined symbol: xf86GetOS
xpra initialization error:
 xpra_Xdummy: did not provide a display number using displayfd

And the below details is for the command Start xpra proxy server, command - sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5905 --ssl-cert=/usr/share/xpra/www/xpra-ssl.cert --ssl=on

﻿2022-02-07 23:18:47,352 created wss socket '0.0.0.0:5905'^[[0m
^[[33m2022-02-07 23:18:47,370 Warning: some of the sockets are in an unknown state:^[[0m
^[[33m2022-02-07 23:18:47,370  /root/.xpra/ssl-hn-100^[[0m
^[[33m2022-02-07 23:18:47,371  please wait as we allow the socket probing to timeout^[[0m
2022-02-07 23:18:53,404 created unix domain socket '/run/user/0/xpra/ssl-hn-100'^[[0m
2022-02-07 23:18:53,405 created unix domain socket '/run/xpra/ssl-hn-100'^[[0m
2022-02-07 23:18:53,405 created unix domain socket '/root/.xpra/ssl-hn-100'^[[0m
^[[33m2022-02-07 23:18:53,405 Warning: missing sound module^[[0m
^[[33m2022-02-07 23:18:53,436 Warning: zlib is the only compressor enabled^[[0m
^[[33m2022-02-07 23:18:53,436  install and enable lz4 support for better performance^[[0m
2022-02-07 23:18:53,441 serving html content from '/usr/share/xpra/www'^[[0m
2022-02-07 23:18:53,490 xpra is ready.^[[0m
2022-02-07 23:18:53,490 xpra proxy version 3.1.2-r25 64-bit^[[0m
2022-02-07 23:18:53,491  uid=0 (root), gid=0 (root)^[[0m
2022-02-07 23:18:53,491  running with pid 173768 on Linux CentOS 7.5.1804 Core^[[0m

**To Reproduce**
1. server command - Start xpra proxy server, command - sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5905  --ssl-cert=/usr/share/xpra/www/xpra-ssl.cert --ssl=on
2. To start the visualizer command which is want to display using xpra on the web appilcation. 
xpra start --ssl-cert=/usr/share/xpra/www/xpra-ssl.cert --ssl=on --start="/opt/ohpc/pub/intel_2018/vtune_amplifier_2018.3.0.558279/bin64/amplxe-gui /scratch_ib/nitin/ParaDE/visualizer/PI_Calculation-OpenMPwithMPI/r000hs.ssl-hn"
2. client command - Start xpra-html5-client server using “npm run serve”
3. specific action to trigger the bug

**System Information (please complete the following information):**
 - Server OS: Centos 7
 - Client OS: Centos 7
 - Xpra Server Version v3.1.2-r25
 - Xpra Client Version xpra v4.0
 - 
**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
You're using the wrong version of CentOS 7:
> `/bin/Xorg: symbol lookup error: /usr/lib64/xorg/modules/input/mouse_drv.so: undefined symbol: xf86GetOS`

Solutions:
* ensure your CentOS is up to date - 7.9 is the current version
* use the repository path matching your CentOS version (7.6 or whatever)
* switch to `Xvfb` in `/etc/xpra/conf.d/55_server_x11.conf`
