### ISSUE TITLE
Can't change encoding on the fly via tray icon

### ISSUE THREAD

**Issue by nentibusarchitectura** [Xpra-org/xpra#3474]
**Describe the bug**
When I change the picture encoding for example to PNG 8 bit to save bandwith nothing happens and I can observe this error in the server logs:

Feb 22 10:22:44 server xpra[144252]: Traceback (most recent call last):
Feb 22 10:22:44 server xpra[144252]:   File "/usr/lib/python3/dist-packages/xpra/server/server_base.py", line 896, in call_handler
Feb 22 10:22:44 server xpra[144252]:     handler(proto, packet)
Feb 22 10:22:44 server xpra[144252]:   File "/usr/lib/python3/dist-packages/xpra/server/mixins/encoding_server.py", line 196, in _process_encoding
Feb 22 10:22:44 server xpra[144252]:     encoding = packet[1].decode("latin1")
Feb 22 10:22:44 server xpra[144252]: AttributeError: 'str' object has no attribute 'decode'

**To Reproduce**
Connect to xpra server, change encoding via xpra tray icon picture->encoding->(any encoding)

Server command:

```
/usr/bin/xpra start :100 \
--start-after-connect="/usr/bin/xfce4-terminal" \
--start-via-proxy=no \
--start-new-commands=yes \
--no-pulseaudio \
--no-microphone \
--no-speaker \
--no-daemon \
--webcam=no \
--opengl=no \
--systemd-run=no \
--env=XPRA_VAAPI=0 \
```

Client command:

```
xpra attach ssh:username@server1:100 --border=orange,1 \
                                             --encoding=rgb \
                                             --compress=9 \
                                             --no-microphone \
                                             --no-speaker \
                                             --no-cursors \
                                             --ssh='ssh -p 2222' \
                                             --desktop-scaling=off \
                                             --opengl=no \
                                             --headerbar=yes \
                                             --env=XPRA_CLIPBOARD_IMAGE_STAMP=0 \
                                             --env=XPRA_MIN_CLIPBOARD_COMPRESS_SIZE=2097152"
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.4 LTS
 - Client OS: Ubuntu 20.04.4 LTS
 - Xpra Server Version: 4.3.2r0
 - Xpra Client Version: 4.3.2r0

**Comment by totaam** [comment]
Already fixed in 437cc5af81f5acf1cc00efc8ab2ac2061e2454f2
