### ISSUE TITLE
"FakeClient has no attr wheel_smooth"

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3477]
**Describe the bug**
Attaching to an existing xpra server gives me this diagnostic:
![screenshot3](https://user-images.githubusercontent.com/7548920/156040340-3ae27325-a02f-4f63-b01e-2ce75a70fc4a.png)

**To Reproduce**
1. xpra start ssh://u20/73 --start-child=vterm --attach=no
2. xpra attach ssh://u20/73 --border=turquoise,1
3. get notification.

**System Information (please complete the following information):**
 - Server: ( f35 | centos8 | u20.04 ) + 4.4-r31013 (g4e0fec250) (ubuntu) or 4.4-r31034 (gfd9f7c27f) ( f35 | centos8 )
 - Client: f35 + 4.4-r31034 (gfd9f7c27f)

**Comment by totaam** [comment]
Oops - thanks for the report.
(commit above fixes that)
