### ISSUE TITLE
"server requested 'xor' digest, cowardly refusing to use it without encryption" when using ssh with Windows server Linux client

### ISSUE THREAD

**Issue by bdklahn** [Xpra-org/xpra#3482]
I did find a reference to one of these messages in an old Track thread: wasn't helpful here.

It looks like I can connect to the served remote lan ip, locally. It asks for the (I assume ssh) password, which apparently is my Windows login password (Ah . . . but maybe that "Connect" isn't using ssh url I see in the connection's dropdown menu)

So does the Windows 64 package not understand "[. . .authentication can be skipped . . .](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md)", when using ssh? I.e., it's serving an ssh url. It's receiving a connection from an ssh client. So it should be able to easily know there's encryption, right? I guess that is paramiko implementing the ssh server stuff?
On the Linux client . . .
```bash
2022-03-06 11:57:54,155 Connected (version 2.0, client paramiko_2.8.0)
2022-03-06 11:57:54,246 Authentication (none) successful!
```
There I'm just passing in the username and password with the ssh url on the CLI, just for testing.

There doesn't appear to be a way to set the `-d auth`, or whatever on the Windows server, via the Windows Xpra GUI (WinSwitch???).

I did the "Shadow" one, because that seems to be the only interface designed to start the local server, for remote access. The "Start" interface seemed to only enable starting localhost for local access, or starting a remote Xpra server, for attaching to.

Also . . . I didn't see a(n obvious) way to shutdown a server. And when I close the GUI program, the previous server processes are still there after I re-start it. That design seems to encourage orphan processes.

Maybe I just couldn't find the right place/way. It was hard to see some things with the GUI. It looks like it hasn't been updated to work with current Windows versions, on the common high-res screens (icon widgets very small, rendered widgets very large).

But those last things, of course, are separate issues.

**Comment by totaam** [comment]
> It looks like I can connect to the served remote lan ip, locally. It asks for the (I assume ssh) password, which apparently is my Windows login password

Correct. The default authentication module for shadow servers is `sys` which is an alias for the `win32` authentication module and uses the system password.
You are free to configure a different authentication module if you wish.

> So does the Windows 64 package not understand "[. . .authentication can be skipped . . .](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md)", when using ssh?

Correct. As per that link: _by default the unix domain sockets used by ssh do not use authentication_
There are no unix domain sockets on MS Windows and no system provided ssh server (not usually anyway).

> So it should be able to easily know there's encryption, right?

Yes, `ssh` sockets should match this test:
https://github.com/Xpra-org/xpra/blob/6d05d5fc851aa953d4d355389da7d0ce167eb7a6/xpra/net/protocol.py#L216-L217

> I guess that is paramiko implementing the ssh server stuff?

Yes. It provides the scaffolding for it.
The authentication proper is still handled by the xpra server itself, which is why you can use any authentication module with it.

> There doesn't appear to be a way to set the -d auth, or whatever on the Windows server, via the Windows Xpra GUI 

Try:
`xpra_cmd.exe shadow -d ssh`

> (WinSwitch???).

Not winswitch, which is now abandonware.

> The "Start" interface seemed to only enable starting localhost for local access, or starting a remote Xpra server, for attaching to.

`Start` should also work and is not just for localhost - it creates the default xpra socket (on port 14500) which supports many different protocols, including `ssh`.

> Also . . . I didn't see a(n obvious) way to shutdown a server.

The systray menu on the server has this option. So does the systray menu on the client once connected.

> It looks like it hasn't been updated to work with current Windows versions, on the common high-res screens (icon widgets very small, rendered widgets very large).

Can you post a screenshot?

**Comment by bdklahn** [comment]
Thanks for the response.

> Try: `xpra_cmd.exe shadow -d ssh`
> 
```
>xpra_cmd.exe shadow -d ssh
'xpra_cmd.exe' is not recognized as an internal or external command,
operable program or batch file.
```
So maybe the installer doesn't put it in the path, or something?

> `Start` should also work and is not just for localhost - it creates the default xpra socket (on port 14500) which supports many different protocols, including `ssh`.

> 
> The systray menu on the server has this option. So does the systray menu on the client once connected.

I don't see Xpra in the/a systray, on this Windows 10.0.19043 Build 19043 system. Only Xpra, Xpra Session, and Xpra Session Browser windows (can be open).


> 
> Can you post a screenshot?

One of the screenshots should show the Start > Shadow Session > Local System option doesn't seem to be able to set things like -d ssh. But I guess, maybe, checking "exit with client" might be one way of shutting down the server(?).
![Screenshot 2022-03-07 204653](https://user-images.githubusercontent.com/920400/157152678-68063d00-d415-4f93-bd26-5049e006817f.png)
![Screenshot 2022-03-07 204818](https://user-images.githubusercontent.com/920400/157152707-2fc533c6-6ae1-458b-8ba2-79801533c1b3.png)
![Screenshot 2022-03-07 205001](https://user-images.githubusercontent.com/920400/157152712-2f2dd16a-1f8f-4732-b1db-f439910c9702.png)

**Comment by totaam** [comment]
> So maybe the installer doesn't put it in the path, or something?

No. Xpra is normally installed in `C:\Program Files\Xpra`.

> Wait . . . does -d work in windows?

It does.
> It's been a while, but I would have thought that to be /d or something.

That's just a convention on MS Windows.
Xpra uses the same command line syntax and options on all platforms.

> Am I supposed to be using Powershell?

No.
> (or the Ubuntu subsystem???)

No.

> I don't see Xpra in the/a systray, on this Windows 10.0.19043 Build 19043 system. Only Xpra, Xpra Session, and Xpra Session Browser windows (can be open).

Those are system menu entries.
I am talking about the system tray which shows up once xpra is running:
https://github.com/Xpra-org/xpra/blob/master/docs/Features/System-Tray.md
Here's an old screenshot on Ubuntu:
![Ubuntu-TrayMenu](https://user-images.githubusercontent.com/1049737/157159841-8e38b08b-8bee-489a-a91f-5cbfa92633df.png)

> One of the screenshots should show the Start > Shadow Session > Local System option doesn't seem to be able to set things like -d ssh.

No, you have to use the command line for that.
> But I guess, maybe, checking "exit with client" might be one way of shutting down the server(?).

Yes, that's one way.

**Comment by totaam** [comment]
The only remaining issue is now tracked in #3514.
