### ISSUE TITLE
update Debian install instructions, apt-key deprecated, new source format

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra#3485]
You might want to update the Debian / Ubuntu installation instructions on https://github.com/Xpra-org/xpra/wiki/Download#-linux

1. apt-key is deprecated
2. There is a new, IMHO more readable format for apt repository files

Instead of adding keys with apt-key, one should add non-armored gpg keys in a file in folder `/usr/share/keyrings/`. For this I changed your key with

    gpg --dearmor gpg.asc

and moved the resulting file to `/usr/share/keyrings/xpra.gpg`.

The new source format then allows to specify, which key should be used to sign packages of which repository. The new format used the file extension `.sources`. So in `/etc/apt/sources.list.d/xpra.sources` I put:

```
Types: deb
URIs: https://xpra.org/
Suites: bullseye
Components: main
Signed-By: /usr/share/keyrings/xpra.gpg
```

For more details:

- https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html
- https://wiki.debian.org/DebianRepository/UseThirdParty

Thank you!

**Comment by totaam** [comment]
Since the current instructions still work, this is unlikely to be worked on just yet.

**Comment by totaam** [comment]
See also #3446

**Comment by adamhotep** [comment]
Run this command:

```bash
sudo wget -O "/usr/share/keyrings/antoine-martin.gpg" https://xpra.org/gpg-2022.asc
```

Then download the appropriate repository file from the [Download § for Debian based disributions](https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions) table and modify it to include that signing key as an option:

Like this:
```
deb [signed-by=/usr/share/keyrings/antoine-martin.gpg] https://xpra.org/ bookworm main
```

If there's already an options section, it's space-delimited (see [my notes](https://askubuntu.com/a/1396167/260416 "What is the format of the Ubuntu sources.list file?")):
```
deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/antoine-martin.gpg] https://xpra.org/beta/ hirsute main
```

I chose to use Antoine's name for the key since it identifies itself as his personal key. You may prefer to call it `xpra.gpg`. 

To update the docs, just update the files and the code block with my command.

**Comment by totaam** [comment]
@adamhotep thanks, do you happen to know which distributions support this format and which don't? (from both Ubuntu and Debian)

**Comment by adamhotep** [comment]
Ubuntu and Debian develop APT together and coordinate releases to reduce this confusion, especially for the apt-key deprecation given [its security concerns](https://unix.stackexchange.com/a/582853/87770 "How to add a third-party repo and key in Debian?").

See also [apt-key Is Deprecated](https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html), which notes that this applies to "Debian, Ubuntu, Linux Mint, Pop!_OS, etc."

**Comment by totaam** [comment]
Users have criticised the download page for DEB package as being too complicated.
And these latest changes have just made things a little bit worse as we now have two different ways of importing the keys and no easy way to make it clear which one users should use... oh well.

**Comment by ehfd** [comment]
> Instead of adding keys with apt-key, one should add non-armored gpg keys in a file in folder /usr/share/keyrings/.

This is apparently unnecessary. Just use the armored key from `https://xpra.org/gpg.asc`.
