### ISSUE TITLE
gvfs_open, gnome_open contain Bashisms

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra#3489]
The Debian tool lintian complains, that the shell scripts gvfs-open and gnome-open contain BASH-specific functionality but declare a generic shebang (/bin/sh):

```
#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec $DIR/xdg-open "$@"
```

These two scripts apparently don't do anything else but to redirect their call to xdg-open in the same folder. Additionally, these scripts only get installed on Linux and FreeBSD according to setup.py. Both platforms (not sure on BSD) support symlinks. Would you mind replacing gnome-open and gvfs-open with relative symlinks to xdg-open?

**Comment by totaam** [comment]
I can't remember why it was done this way, perhaps they did look different originally.
