### ISSUE TITLE
xpra_udev_product_version is in /usr/bin but has no manpage

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra#3491]
The script xpra_udev_product_version gets installed to /usr/bin but has no manpage. Apparently this scripts should never be called directly by a user anyways but only by udev.

Would you be OK to merge a PR to setup.py and the udev files to move xpra_udev_product_version to /usr/lib/xpra?

**Comment by totaam** [comment]
Sure, please make sure to update all references to it.
This should go into `/usr/libexec/xpra/` on Fedora / RHEL.

I don't see any reason not to move `xpra_signal_listener` together with it.
