### ISSUE TITLE
libexec dir should also be used for Debian based distributions

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra#3493]
I compared xpra's Debian package with my own attempt to update the Debian package to 4.3.2 and found these lintian overrides in xpra's package:

```
executable-in-usr-lib usr/lib/cups/backend/xpraforwarder
executable-in-usr-lib usr/lib/xpra/auth_dialog
executable-in-usr-lib usr/lib/xpra/gnome-open
executable-in-usr-lib usr/lib/xpra/gvfs-open
executable-in-usr-lib usr/lib/xpra/xdg-open
```

These overrides were [added June 2021](https://github.com/Xpra-org/xpra/commit/2c9341105f8ede934f7d235453fb6fc4c9cb759f). However the [lintian tag explanation](https://lintian.debian.org/tags/executable-in-usr-lib) (today) says that it is actually preferred to move executables to libexec instead of lib. So the following logic in `setup.py` is now obsolete if I assume that the else branch is only for Debian based distributions:

    if is_Fedora() or is_CentOS() or is_RedHat() or FREEBSD:
        libexec = "libexec"
    else:
        libexec = "lib"

Do you accept a PR to install these files to libexec for all posix distros?

**Comment by totaam** [comment]
Let's do it!

**Comment by totaam** [comment]
@thkoch2001 I also moved the signal watcher and cleaned up the code - see above

**Comment by totaam** [comment]
This also broke MacOS and MS Windows builds..

**Comment by totaam** [comment]
Also broke some overrides in:
https://github.com/Xpra-org/xpra/blob/master/packaging/debian/xpra/xpra.lintian-overrides
(commit above fixes that)
