### ISSUE TITLE
Please release 4.3.3

### ISSUE THREAD

**Issue by thkoch2001** [Xpra-org/xpra#3498]
In case that releasing is not too much work, I'd be thankful if you could cut a release including the recent PRs I sent. Then I could remove all the patches from the Debian package.

I see that you have had frequent releases in the past but none since January.

Thank you!

**Comment by totaam** [comment]
The current PRs are in master which will become 4.4

There are still quite a few features that I am working on before being able to cut this release - and a lot more testing.
