### ISSUE TITLE
'FakeClient' object has no attribute 'find_window'

### ISSUE THREAD

**Issue by sbradnick** [Xpra-org/xpra#3500]
**Describe the bug**
Looking @ [#3477](https://github.com/Xpra-org/xpra/issues/3477), I'm wondering if this is a similar oops or there's something wrong on my end.

**To Reproduce**
1. xpra start ssh://\<user\>@\<host\> --start=evolution

**System Information (please complete the following information):**
 - Server OS: openSUSE Tumbleweed 20220322, aarch64
 - Client OS: openSUSE Tumbleweed 20220322, x86_64
 - Xpra Server Version ==> latest git
 - Xpra Client Version ==> latest git

**Additional context**
Didn't have this issue w/ 4.3.2 official release, but upon updating to latest git it popped up ~ everything seems to work fine aside from it seeming like openGL isn't happy at startup.

**Comment by totaam** [comment]
You're totally right, I messed up (again) and it is exactly the same problem as #3477 : I forgot to update the opengl probe code path (opengl was broken on my machine again by an nvidia driver update... so I didn't notice).
Ideally, this would be a clean interface and the update would be done automagically..

The fix tagged the wrong ticket: 7f8ca92ba5c19209b9dab32c6f7cef3a2537fc0b

**Comment by sbradnick** [comment]
Working great now, thank you so much for such a fast turnaround!
