### ISSUE TITLE
Use Pypi 'distro' module for Linux distribution detection?

### ISSUE THREAD

**Issue by bdklahn** [Xpra-org/xpra#3501]
[https://pypi.org/project/distro/](https://pypi.org/project/distro/)

Not critical or necessary. But if, say, a new OpenSUSE package maintainer wanted to create a PR to, say, add is_OpenSUSE . . .
to the utilities, to make this a "cleaner" (???) situation for [Open Build Service](https://openbuildservice.org/) regular updating, would that create a conflict/issue with any backwards-compatible code, or something?

Probably  the code here handled the OS dist detection during the "transition" of Python's stdlib functionality for that. But now, I guess, the recent 'distro' module is the recommended way (and looks like it is planning to also handle non-Linux, as well).

A new guy is testing/prototyping an updated OBS package build, and we/they are discussing such things in a [bug](https://bugzilla.opensuse.org/show_bug.cgi?id=1195873)'s comments.

**Comment by totaam** [comment]
I don't have a login for that bug tracker.
> `the build runs "git describe --long --always --tags":`

Only if the `./xpra/src_info.py` is not populated already.
And it is populated with the pypi releases since those are generated using `python ./setup.py sdist` but not with the archives from github which are generated by github...

As for `lsb_release -a` shenanigans, I'm totally cool adding a `is_openSUSE()` function.
And even using https://pypi.org/project/distro/ - as long as this does not become a new hard dependency but an optional one.

**Comment by sbradnick** [comment]
I have absolutely _no issue_ with how things are now and wouldn't want to complicate anything for (already working) multi-distro detection. Using something like `import distro` would be 'neat', but if `lsb_release -a` parsing already works it just isn't "openSUSE" aware, seems easier (famous last words) to make that happen.

Also fine with how the About section is populated w/ info from git ; just seems most of the automation tools around OBS (on SUSE's side) willfully strip out `.git/*` when building tarballs. Nothing is *wrong*, just want things to work automagically & harmoniously :-D

@totaam Does it make more sense for you to do the `is_openSUSE()` stuff vs. one of us potentially guessing and submitting a PR? It seemed straightforward, but I don't want to waste anyone's time :P ...

**Comment by totaam** [comment]
> just seems most of the automation tools around OBS (on SUSE's side) willfully strip out .git/* when building tarballs.

As long as you use the pypi tarballs, you should not need `.git` since the `xpra/src_info.py` should have the information already recorded.

I can easily add `is_openSUSE` (I guess!) but I have no idea where it would be used.
Do you have an existing patch that uses it?

**Comment by sbradnick** [comment]
OBS generally likes a reproducible setup via GitHub. I'm not suggesting it's not possible or that someone else isn't using pypi tarball source. I've even used SUSE documentation to generate python packages off pypi.org.

Maybe in that case, it'd make more sense for it to be a python module vs. built from github source ~ but as it stands now, it's pulled down from GitHub and I don't necessarily want to throw that away and pivot in that direction. I also like the idea of maintaining it via git so it can be more agile - at least for Tumbleweed.

Here's the latest diff I have, and the things we're making adjustments for:

```diff
--- xpra-v4.3.git20220324.785a44e79/setup.py.orig	2022-03-24 12:07:49.434707163 -0400
+++ xpra-v4.3.git20220324.785a44e79/setup.py	2022-03-24 12:11:13.710523552 -0400
@@ -1538,7 +1538,7 @@
             add_data_files("libexec/xpra/", ["fs/libexec/xpra/%s" % x for x in libexec_scripts])
     if data_ENABLED:
         man_path = "share/man"
-        icons_dir = "icons"
+        icons_dir = "pixmaps"
         if OPENBSD or FREEBSD:
             man_path = "man"
             icons_dir = "pixmaps"
@@ -1634,7 +1634,7 @@
             if pam_ENABLED:
                 copytodir("fs/etc/pam.d/xpra", "/etc/pam.d")
 
-            systemd_dir = "/lib/systemd/system"
+            systemd_dir = "__UNITDIR__"
             if service_ENABLED:
                 #Linux init service:
                 subs = {}
@@ -1642,15 +1642,15 @@
                     cdir = "/etc/sysconfig"
                 elif is_Debian() or is_Ubuntu():
                     cdir = "/etc/default"
-                elif os.path.exists("/etc/sysconfig"):
-                    cdir = "/etc/sysconfig"
                 else:
-                    cdir = "/etc/default"
-                copytodir("fs/etc/sysconfig/xpra", cdir)
+                    cdir = "__FILLUPDIR__"
+                shutil.copy("fs/etc/sysconfig/xpra", "fs/etc/sysconfig/sysconfig.xpra")
+                os.chmod("fs/etc/sysconfig/sysconfig.xpra", 0o644)
+                copytodir("fs/etc/sysconfig/sysconfig.xpra", cdir)
                 if cdir!="/etc/sysconfig":
                     #also replace the reference to it in the service file below
                     subs[b"/etc/sysconfig"] = cdir.encode()
-                if os.path.exists("/bin/systemctl"):
+                if os.path.exists("/usr/bin/systemctl"):
                     if sd_listen_ENABLED:
                         copytodir("fs/lib/systemd/system/xpra.service", systemd_dir,
                                   subs=subs)
@@ -1766,7 +1766,6 @@
 toggle_modules(WIN32, "xpra/scripts/win32_service")
 
 if data_ENABLED:
-    add_data_files(share_xpra,                      ["README.md", "COPYING"])
     add_data_files(share_xpra,                      ["fs/share/xpra/bell.wav"])
     if LINUX:
         add_data_files(share_xpra,                  ["fs/share/xpra/autostart.desktop"])
```

`__UNITDIR__` & `__FILLUPDIR__` are parsed out at some point to be replaced as the .spec builds packages - this is the info that was passed along to me (thanks Luigi!):

```shell
  sed -e 's|__FILLUPDIR__|%{_fillupdir}|' \
      -e 's|__UNITDIR__|%{_unitdir}|'

The macros (can) have different values in Leap and TW.
```

**Comment by totaam** [comment]
@bdklahn please see the commit above - it should be equivalent to the patch is now in master.

**Comment by sbradnick** [comment]
This is great, thanks so much for it! I was able to have my branch in OBS build _without_ the patch after ensuring 2 `BuildRequires:` were present ==> `lsb-release` (for `lsb_release -a`) & `openSUSE-release` (for `/etc/os-release`) [thankfully lsb_release complains when `/etc/os-release` is missing].

**Comment by totaam** [comment]
See also #3597
