### ISSUE TITLE
Windows do not get keyboard focus in some cases

### ISSUE THREAD

**Issue by Vftdan** [Xpra-org/xpra#3506]
**Describe the bug**
Jetbrains IDEs do not start reacting to keyboard input (& do not show text cursor) when their window is focused, until they are clicked with mouse.
Dmenu & rofi only receive keyboard input when there are no windows on the current workspace (and sometimes also require mouse click), when there are windows they get the typed text instead. (Normally dmenu & rofi grab the keyboard.)

**To Reproduce**
1. server command: `xpra start :11 --start='tmux new -Ads xpra-11' --xsettings=yes`
2. client command: `xpra attach`
3. specific action to trigger the bug: open some windows on the current desktop, attach to xpra session, attach to tmux session, run `dmenu_run` or `rofi -show drun` — menu is shown, but input is sent to regular non-xpra windows
4. specific action to trigger the bug: open Jetbrains IDE inside xpra session (in my case `WebStorm2021.3`, with IdeaVIM plugin), type some text into it, switch to non-xpra window, switch back — IDE does not react to keyboard

**System Information (please complete the following information):**
 - Server OS: Linux Mint 19 Tara x86_64
 - Client OS: Linux Mint 19 Tara x86_64
 - Xpra Server Version 4.1.3
 - Xpra Client Version 4.1.3

**Additional context**
Keyboard layout: [xkbcomp](https://github.com/Vftdan/dotfiles/blob/master/extra/xkb/my)
Input method: `uim-xim`
Window manager: `bspwm`
Hotkey manager: `sxhkd`

**Comment by totaam** [comment]
Your xpra versions are well out of date.
Please try again with a supported version: https://github.com/Xpra-org/xpra/wiki/Versions
