### ISSUE TITLE
Connection refused from local tty, works over remote ssh

### ISSUE THREAD

**Issue by jrichardson97** [Xpra-org/xpra#3508]
I've been trying to setup xpra for remoting into a work computer. My idea was to setup my .xinitrc to launch i3wm as an xpra session and be able to connect from tty locally or over ssh with a Windows 10 laptop remotely. 

I launched the xpra session with `xpra start-desktop :20 start=i3 resize-display=1920x1080` and am able to connect from my laptop with `Xpra_cmd.exe attach ssh://user@ip/20` which works fine. When I try to login from a different tty on my work computer though I get the following error:
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
failed to initialize Gtk, no display?
```

Does this have something to do with xorg.conf? My laptop only has a single monitor but I have a custom xorg.conf from my work monitors (3 monitors configured with NVIDIA). Not sure how to debug this otherwise. Ideally, I'd be able to adapt the display based on which computer is connected too (ie, only have one i3wm workspace when connected with laptop but have 3 when connected with desktop).

**Comment by jrichardson97** [comment]
Sorry - I see now. I've reformatted my post below.

Workstation: Ubuntu 20.04, i3wm, no display manager, gnome polkit, xpra 4.3.2-r0, 3 monitors 
Laptop: Windows 10, xpra 4.3.2-r0, single monitor

Goal: Run window manager (i3wm with some extras) with xpra start-desktop on Workstation. Attach to xpra session locally from Workstation and display 3 i3wm workspaces (one on each monitor). Attach to xpra session from Laptop via ssh and display 1 i3wm workspace (on single laptop monitor). Ultimately just trying to setup the ability to work remotely and be able to attach to the same xpra session either from Workstation or Laptop. 

Commands run:
1) On Workstation (additional config shown below): "xpra start-desktop :20"
2) Attach from Laptop: "Xpra_cmd.exe attach ssh://user@host/20"
3) Attach from Workstation: "xpra attach :20"

Issue: 
Commands 1 and 2 work well and I can see the i3wm workspace running on Workstation from Laptop. I then get this error when trying to attach from Workstation shell after login on tty:
"
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
failed to initialize Gtk, no display?
"
Command 3 works however when I use startx with ~/.xinitrc just containing "exec i3" from tty then attach from xterm once the x server loads up. So I guess my main issue is how do you configure an xpra desktop session with a windows manager so it can be attached to locally and displayed on the monitors connected to Workstation as well as attached remotely from Laptop?

Additional files:
- xpra info output: [xpra_info.txt](https://github.com/Xpra-org/xpra/files/8382954/xpra_info.txt)
- xpra showconfig output: [xpra_showconfig.txt](https://github.com/Xpra-org/xpra/files/8382973/xpra_showconfig.txt)

**Comment by totaam** [comment]
> Goal: Run window manager (i3wm with some extras) with xpra start-desktop on Workstation.
> Attach to xpra session locally from Workstation and display 3 i3wm workspaces (one on each monitor)

Each `xpra start-desktop` session will have a single virtual display, so you may not be able to map this to your 3 displays.

> Attach to xpra session from Laptop via ssh and display 1 i3wm workspace (on single laptop monitor)

Unless this i3wm workspace lives in a window, you won't be able to separate it from the other 2 living in the same xpra virtual display.

> I then get this error when trying to attach from Workstation shell after login on tty

Are you trying to run `xpra attach` from a plain tty?
xpra needs to access a display to show the windows it forwards. You need to be running an X11 server (or wayland).

> So I guess my main issue is how do you configure an xpra desktop session with a windows manager so it can be attached to locally and displayed on the monitors connected to Workstation as well as attached remotely from Laptop?

My guess is that you would be better off running the workstation as you normally would, then just shadow one display from the laptop:
https://github.com/Xpra-org/xpra/issues/3320
(`shadow` is not as fast as desktop mode, but it should be usable)

**Comment by jrichardson97** [comment]
Hmm I will do some more testing with shadow to see if it works well enough for me. I tried it initially but had issues configuring it. 

From #3320, how would the options such as `xpra shadow :1,multi-window=no` be added when connecting over ssh `xpra shadow ssh://HOST/DISPLAY`?

Also, are there recommended settings for optimizing performance over a VPN? I have full admin access so I can bind to TCP or anything else like that.

**Comment by totaam** [comment]
Only use shadow for the laptop, not from the workstation itself which can run a native X11 desktop.
```shell
xpra shadow ssh://HOST/:1,multi-window=no
```

> Also, are there recommended settings for optimizing performance over a VPN?

TCP mode may work better as the VPN may be able to detect TCP flush / cork - depending on how well it is integrated with the OS.
It may also help to set the forwarded port to _low latency_, but not always: if bandwidth is scarce then this will be counterproductive.
