### ISSUE TITLE
deque mutated during iteration

### ISSUE THREAD

**Issue by normanr** [Xpra-org/xpra#3509]
**Describe the bug**
xpra crashed. The last entry in the log was:
```
Error: cannot add information from <class 'xpra.server.source.windows_mixin.WindowsMixin'>:
 deque mutated during iteration
```
There was no log entry for merge_dicts, so no exc_info sorry.

**To Reproduce**
1. couldn't reproduce, happened during startup of Chrome (but I've started Chrome fine many times before too).

**System Information (please complete the following information):**
 - Server OS: Debian testing
 - Client OS: Debian testing
 - Xpra Server Version 4.3.1-r0 (4.3.2-r0 was installed, but the running xpra was not yet upgraded)
 - Xpra Client Version 4.3.2-r0

**Additional context**
Sorry I can't be of more help in reproducing.

**Comment by normanr** [comment]
ack.

`encoding_totals` in `WindowPerformanceStatistics` is a dict, so not the cause of _this_ error.

I wonder if https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/window/batch_config.py#L114 and https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/window/batch_config.py#L121 are not atomic. At  https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/window/window_stats.py#L285 tuple is called on the deque directly, where as in the prior places it's accessing the item while iterating (which might cause the access to be non-atomic).

Other similar places:
https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/source/source_stats.py#L259
https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/source/source_stats.py#L262

and a non-`get_info` codepath:
https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/server/source/clipboard_connection.py#L109

and I'm not sure if these `join` calls end up being atomic in CPython or not:
https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/gtk_common/gtk_view_clipboard.py#L234
https://github.com/Xpra-org/xpra/blob/1e2764c0feddbe15b70954099220383e145e957c/xpra/gtk_common/gtk_view_keyboard.py#L153

**Comment by totaam** [comment]
Thanks for the review.
I've addressed some of those in the commit above.
I believe the last two are already safe as all data access is done from the UI thread.

---

Ideally, we would come up with a `deque` wrapper or alternative implementation that just avoids all this unnecessary copying: in pretty much all cases, we just don't care if the callers (ie: `get_info`) use slightly out-of-date data but we do care about the extra cost of locking / copying.

**Comment by totaam** [comment]
I'm going to optimistically close this ticket early and we can just re-open it if the error pops up again. Hopefully not.
