### ISSUE TITLE
xpra attach IP:DISPLAY fails

### ISSUE THREAD

**Issue by mviereck** [Xpra-org/xpra#3513]
I use xpra to attach to an already running X server.
If I use a display number with an IP address, the `xpra start --use-display` command succeeds, but the `xpra attach` command fails with:
```
xpra initialization error:
 unknown format for display name: 172.20.0.4:123
```
xpra v4.3.2-r0 on debian bullseye.

This is no important use case for me, just stumbled about this.

**Comment by totaam** [comment]
`172.20.0.4:123` is not a valid display name, never has been.

**Comment by mviereck** [comment]
> 172.20.0.4:123 is not a valid display name, never has been.

Of course it is valid. X can be accessed over IP/TCP if option `-listen tcp` is enabled.

**Comment by totaam** [comment]
So this is not an xpra display name, please specify your exact command lines.

**Comment by mviereck** [comment]
Example for IP access:
```
Xephyr :2 -listen tcp
DISPLAY=127.0.0.1:2 xterm
```
```
xpra start 127.0.0.1:2 --use-display
xpra attach 127.0.0.1:2
```

**Comment by totaam** [comment]
Local display numbers should start with `:`:
```shell
xpra attach :127.0.0.1:2
```

---

I'm sure you know that running X11 over TCP is a bad-idea(tm).

Also `--use-display=auto` has been the default for a while now, you don't need to specify it.

**Comment by mviereck** [comment]
> Local displays should start with ::

Indeed, that works. However, imho xpra should recognize the regular valid IP:DISPLAY notation.

> I'm sure you know that running X11 over TCP is a bad-idea(tm).

Yes. There are few special cases where I need it. (Some container setups cannot share a unix socket, e.g. those running in a virtual machine.)

> Also --use-display=auto has been the default for a while now, you don't need to specify it.

Good to know, thank you! I will keep it for now to support old xpra versions, too.
