### ISSUE TITLE
GTK widgets are too large on high resolution MS Windows displays

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3514]
See https://github.com/Xpra-org/xpra/issues/3482#issuecomment-1061336439
ie:
![157152678-68063d00-d415-4f93-bd26-5049e006817f](https://user-images.githubusercontent.com/1049737/161431578-864dc16e-553e-4f6a-b8bc-a4c66d2ff178.png)

**Comment by totaam** [comment]
@bdklahn does this still happen with the beta builds and the patched dummy driver version 0.4.0?

**Comment by bdklahn** [comment]
@totaam I don't know . . . Is this the latest beta?


[Xpra_Setup.exe](https://xpra.org/beta/windows/Xpra_Setup.exe)	2022-04-17 12:59	105M


![Capture](https://user-images.githubusercontent.com/920400/165659317-adce561a-5627-4ae6-a5b4-eaca314a0545.PNG)

**Comment by totaam** [comment]
Oops, that's now fixed. Sorry about that.
In any case, newer builds are unlikely to fix this since the server is not involved, right? You're just running `Xpra_cmd` and getting this gui?

**Comment by bdklahn** [comment]
I just tried again with 4.4

https://xpra.org/beta/windows/Xpra-x86_64_Setup.exe

2022-05-03 12:41 110M
![Xpra4 4](https://user-images.githubusercontent.com/920400/166747729-e73ebb7c-2f16-433c-ad89-61334059f098.PNG)
![AboutXpraCapture](https://user-images.githubusercontent.com/920400/166748086-f9f2d074-85c7-4c87-8912-5c0d01797a13.PNG)

**Comment by totaam** [comment]
According to [GDK-Win32/4.0: Enable HiDPI support for Windows](https://anzwix.com/a/GTK/GDKWin3240EnableHiDPISupportForWindows), the support for HiDPI displays is only available in GTK4.
And since we're unlikely to ever port to GTK4 #1977 (too much Waylandization and levelling down)

We explicitly disable `GDK_SCALING` to ensure that GTK gives us the actual window dimensions. I tried allowing us to override this environment variable, but since it only supports whole integers, I can only use it to make things bigger, not smaller.

And there are no plans to support fractional scaling beyond fonts: https://gitlab.gnome.org/GNOME/gtk/-/issues/4345#note_1344625
[HiDPI Fractional_scaling](https://wiki.archlinux.org/title/HiDPI#Fractional_scaling) is documented for Wayland / Xorg, but using gsettings. No idea how to do the same on MS Windows.
[Support fractional scaling on windows](https://gitlab.gnome.org/GNOME/gtk/-/issues/1036) would seem to indicate that `GDK_WIN32_DISABLE_HIDPI=1` may help?
(we may need to _disable_ HiDPI support in GTK because we force enable DPI awareness: #697)
@bdklahn does this make any difference?
```shell
set GDK_WIN32_DISABLE_HIDPI=1
Xpra_cmd gui
```

**Comment by totaam** [comment]
As per the commit above, beta 5.0 builds r32110 and later will have `GDK_WIN32_DISABLE_HIDPI=1` by default.
@bdklahn does that make things better or worse?

**Comment by totaam** [comment]
Doh! I was still running with the env var set manually, which you can also do:
```shell
set GDK_WIN32_DISABLE_HIDPI=1
xpra_cmd attach ...
```
(the commit above fixes that - new builds will arrive shortly)

**Comment by totaam** [comment]
@bdklahn did that help?

**Comment by totaam** [comment]
Not heard back.

**Comment by totaam** [comment]
@bdklahn the commit above and #3943 may help with this.
Please try 6.0-r35043 or later.

**Comment by totaam** [comment]
FWIW: the icons in the header bar are no longer switched as of 391ae4d0e37cbac2b5a38ac0d2b44d5490bc856b.

As for the buttons, they're big but everything is when setting "200% scaling" - so I'm not sure what the problem is / was.
![image](https://github.com/Xpra-org/xpra/assets/1049737/0b1c3df4-9309-44e7-b026-66c2f17c5e0f)

**Comment by totaam** [comment]
FWIW, this may have been resolved or at least improved by https://github.com/Xpra-org/xpra/pull/4444

Any builds newer than 6.3-r37057 should be using the correct MS Windows manifest file.
