### ISSUE TITLE
Ubuntu GPG - Repository is not signed error

### ISSUE THREAD

**Issue by nakkaya** [Xpra-org/xpra#3520]
I have a Ubuntu based docker image [1]  that uses instructions from the download page [2]. 

    RUN wget -q https://xpra.org/gpg.asc -O- | apt-key add - && \
             add-apt-repository "deb https://xpra.org/beta/ $DISTRO main" && \
             apt-get update && \
             apt-get install python3-rencode xpra xpra-html5 -y --no-install-recommends`

Today I had to rebuild the container but build failed due to repository is not signed error.

[1] https://github.com/nakkaya/emacsd
[2] https://github.com/Xpra-org/xpra/wiki/Download

**Comment by totaam** [comment]
The download instructions have been updated, see: https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions

The gory details of why this was necessary are in #3446

**Comment by nakkaya** [comment]
Forgot to mention I tried those as well with the same result on Ubuntu LTS 20.04

**Comment by totaam** [comment]
OK, I must have forgotten to sign today's beta builds. Try again now.
