### ISSUE TITLE
Sluggish response after long time connected

### ISSUE THREAD

**Issue by AJStone** [Xpra-org/xpra#3521]
Client and server both running xpra v4.3.2-r0 under Ubuntu 18.04.
Connection command:
```
xpra start ssh/whirligig --start="gnome-terminal --window-with-profile=Blue" &> ~/xpra.log &
```
but subsequently disconnected and reconnected using xpra detach/attach or possibly attach following client restart.

After the session has been running on the server for a long time the response becomes increasingly sluggish. After even a brief pause, the response to a single keystroke may take many seconds, but then response is fairly normal for a while.

Results of xpra info on server for a normal well-behaved session and an intermittently sluggish one:
[xpra_normal.txt](https://github.com/Xpra-org/xpra/files/8496340/xpra_normal.txt)
[xpra_sluggish.txt](https://github.com/Xpra-org/xpra/files/8496343/xpra_sluggish.txt)

xpra complains that the connection is struggling to keep up, but the ping average response time is 25 ms and the line download/upload speeds are 100mbps and 9 mbps.

**Comment by totaam** [comment]
> the response to a single keystroke may take many seconds, but then response is fairly normal for a while

I can't think of anything that would ever cause the server to delay screen updates by more than a second.
Is it possible that the process has been swapped out?
Can you run with `-d compress`?
Are there any warnings in your server log?

From the sluggish log::
> `client.connection.client.ping_latency.avg=50`
> `client.connection.client.ping_latency.max=280`
> `client.connection.server.ping_latency.avg=47`
> `client.connection.server.ping_latency.max=209`

280 ms maximum latency isn't very high.

> `client.batch.delay.avg=46`
> `client.batch.delay.max=62`

And as a result, the server never delays things by more than 62ms.

```
client.window.1.total_frames.jpeg=67
client.window.1.total_frames.jpega=108
client.window.1.total_frames.png=6
client.window.1.total_frames.rgb24=54
client.window.1.total_frames.rgb32=5534
client.window.1.total_frames.scroll=107
client.window.1.total_frames.webp=1949
```
That's a lot of `rgb32`, but not necessarily a problem for a terminal app.

> xpra complains that the connection is struggling to keep up, but the ping average response time is 25 ms and the line download/upload speeds are 100mbps and 9 mbps.

Please post the server log when running with `-d bandwidth`.

**Comment by AJStone** [comment]
[xpra_server.log](https://github.com/Xpra-org/xpra/files/9100599/xpra_server.log)

This is the server log for session started with xpra start ssh/whirligig  -d bandwidth -d compress ...
Response was starting to get sluggish but not as bad as it has been sometimes.

**Comment by totaam** [comment]
From that log:
* client resolution is 1920x1080
* server and client (x11) are running 4.3.4
* started command `gnome-terminal --window-with-profile=Blue` at `11:21:03`
* there are nother windows - what else was running?
* not a single bandwidth warning
* lots of small `rgb` screen updates (likely when typing in the terminal) with the `webp` used for larger areas and very few `scroll` packets - quality is 100% and speed is low (high compression)
* totals:
  * 25495 `webp`
  * 8500 `rgb32`
  * 18918 `rgb24`
  * 396 `jpeg`
  * 665 `jpega`
  * 34 `vp9` almost all for window 71

Near the end of the log, the quality is still very high (99% - 100%) and the speed is a little bit lower (as low as 4-5).
But even with such a low speed setting, most screen updates take less than 5ms, only a few take up to 50-60ms and most of these are lossless auto-refresh so hardly noticeable. The low speed means that the screen updates are well compressed (<10% of original size) and therefore not using much bandwidth.

Have you tried raising the `min-speed`? Maybe something like: `--min-speed=50`.
I don't think that this is the problem, but worth a try.

---

My best guess at this point is that it is something external to xpra that is causing the network packets to become throttled.

---

BTW, found these in your client output:
```
2022-07-07 11:21:05,089 client   1 @09.267 Error: failed to load icon data for 'gxmms2':
2022-07-07 11:21:05,094 client   1 @09.267  gdk-pixbuf-error-quark: Unrecognised image file format (3)
```
Would you mind locating the file that causes this and attaching it here?
It's very likely to be another broken SVG file (#3455) and we may need yet-another workaround to load it without errors.
