### ISSUE TITLE
Multibyte characters don't paste from remote Mac client

### ISSUE THREAD

**Issue by SaitouToshihide** [Xpra-org/xpra#3522]
Multibyte characters don't paste from remote Mac client.
It was able to paste up to version 4.2.3 r0 client.
The server version is 4.3_1.

Server OS: FreeBSD 13.0
Client OS: Mac 12.3.1

Xpra Server Version 4.3_1
Xpra Client Version 4.3-

**Comment by totaam** [comment]
Those versions are out of date.

Since this is a clipboard issue, please post the `-d clipboard` log, or at least the sequence of characters that shows the problem.

Is the problem in one direction only or both?

**Comment by SaitouToshihide** [comment]
The problem no longer appears while uninstalling and installing.
I have tried several combinations but they do not reproduce.
I am sorry.


Server (FreeBSD)

  % sudo pkg uninstall xpra
  % sudo pkg install xpra

  or

  % tar zxf xpra-4.3.2.tar.gz
  % cd xpra-4.3.2
  % sudo python3 ./setup.py install --with-server --without-printing --without-strict

  % xpra --version
  xpra v4.3.2-runknown

  % xpra start :12


Client (Mac)

  used Xpra.dmg, 
   Xpra-Python3-x86_64-4.2-r0.dmg, 
   Xpra-Python3-x86_64-4.2.3-r0.dmg, 
   Xpra-Python3-x86_64-4.3-r12.dmg, 
   Xpra-Python3-x86_64-4.3-r13.dmg, 
   Xpra-Python3-x86_64-4.3.1-r0.dmg.
