### ISSUE TITLE
official xpra package for debian sid stuck on python << 3.10

### ISSUE THREAD

**Issue by dovf** [Xpra-org/xpra#3525]
Hi!

More of a question than a bug report: does xpra really require python < 3.10? AFAICT, I'm on the latest official xpra package for debian sid (4.3.2-r0-1), and the deb itself seems to require python << 3.10 (and my problem is that at this point it's holding me back from upgrading my system to python 3.10). But I don't see this requirement in the sources of the package, so I wasn't sure what the actual status is..? Does xpra currently really require python < 3.10? If so, why? If not, any ideas why the package thinks it does?

Thanks!

**Comment by totaam** [comment]
That's automatic from the debian build tools because the Cython extensions are ABI version specific.

I've built new beta packages very recently so those should use whatever version of python is currently in sid.

Make sure to use the beta channel for sid which is not a stable distribution.

**Comment by dovf** [comment]
Thanks!
I switched to the beta channel for sid and it is no longer preventing upgrade to python 3.10 .

**Comment by adamhotep** [comment]
I tried this last night and found that bookworm beta didn't yet support python3 3.10.4. It does now, thanks.
