### ISSUE TITLE
high CPU usage on spinner

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#353]
*Issue migrated from trac ticket # 353*

**component:** client | **priority:** minor | **resolution:** fixed

#### 2013-06-05 17:47:49: onlyjob created the issue

___
> Forwarding as reported in http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=711181
> 
> "spinners consume a lot of CPU time unnecessarily".
> 
> My laptop is usually connected to at least two xpra servers. If the
> network connection is bad I frequently see xpra drawing spinners over
> all windows. This is a good indicator but I think it uses bit too much
> CPU time causing my laptop fan to accelerate when the 3G connection
> drops:
> ```
> Tasks: 154 total,   3 running, 150 sleeping,   0 stopped,   1 zombie
> Cpu(s): 34.1%us,  0.7%sy,  0.0%ni, 65.2%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
> Mem:   5867296k total,  2151144k used,  3716152k free,   270956k buffers
> Swap: 11460604k total,    50704k used, 11409900k free,  1002416k cached
> 
>   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                 
>  1548 root      20   0  220m 114m  11m R   62  2.0 190:29.15 Xorg                    
>  9286 lindi     20   0  795m  79m  16m S    4  1.4   7:49.61 xpra                    
>  9265 lindi     20   0  938m  72m  17m S    3  1.3  15:25.61 xpra
> ```

**Comment by chapmanjacobd** [comment]
In case others come here by Googling "xpra disable spinner" it seems like this works well:

    env XPRA_SHOW_SPINNER_WINDOW_TYPES='' xpra ...

imho much less distracting on spotty connections--just don't forget you've disabled it ;-) (but the log is verbose enough to remind you: "server is not responding, drawing spinners over the windows")
