### ISSUE TITLE
Windows ARM support?

### ISSUE THREAD

**Issue by seflerZ** [Xpra-org/xpra#3532]
Could you provide binary exe package for Windows on ARM, or can I compile it by myself with intstructions?

**Comment by totaam** [comment]
It looks like it may be possible to run emulated now: [Run Win11 on ARM in QEMU](https://gist.github.com/Vogtinator/293c4f90c5e92838f7e72610725905fd): _When following this guide on a host not capable of native arm64 KVM..._

ISOs download: [Download Windows 11 Disk Image (ISO) for Arm-based PCs](https://www.microsoft.com/en-us/software-download/windows11arm64)

**Comment by totaam** [comment]
@seflerZ moved to #3941

**Comment by totaam** [comment]
The [download page](https://github.com/Xpra-org/xpra/wiki/Download) now includes `arm64` builds for MS Windows.
