### ISSUE TITLE
Xpra xdg-open doesn't convert URL-encoded filenames

### ISSUE THREAD

**Issue by mikiab** [Xpra-org/xpra#3535]
This issue arises when you try to send a file with a space `%20` in its name using the `file:///` scheme, such as:

`xdg-open 'file:///home/mike/Documents/My%20Doc.pdf'`

which returns:

```
server returned error code 127
  file '/home/mike/Documents/My%20Doc.pdf' does not exist
```

I use Xpra 3.0.13 provided by Debian 11, but i think the problem is still present in the latest Xpra version, looking into the current source code:
https://github.com/Xpra-org/xpra/blob/cf94cf486e71597563af19fcccdbb90f8b2365a0/fs/libexec/xpra/xdg-open#L64

The issue is gone passing `filename` to `urllib.parse.unquote`.

**Comment by totaam** [comment]
@mikiab you mean like the commit above?
If so, can I close this ticket?

**Comment by mikiab** [comment]
> @mikiab you mean like the commit above? If so, can I close this ticket?

I think you should decode only if `proto=="file"`, because `open-url` accepts an URL which needs to be encoded.

**Comment by totaam** [comment]
@mikiab Ah, right! How about now?

**Comment by mikiab** [comment]
> @mikiab Ah, right! How about now?

It's ok now.
