### ISSUE TITLE
ModuleNotFoundError: No module named 'xpra.rectangle'

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3536]
**Describe the bug**
xpra cannot display the Firefox bookmark popup anymore with the error:

````
2022-05-04 22:42:47,958 failed to instantiate <class 'xpra.client.gtk3.client_window.ClientWindow'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/window_manager.py", line 777, in make_new_window
    window = cwc(self, group_leader_window, watcher_pid, wid,
  File "/usr/lib/python3/dist-packages/xpra/client/client_window_base.py", line 87, in __init__
    self.setup_window(bw, bh)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 632, in setup_window
    self.window_offset = self.calculate_window_offset(x, y, w, h)
  File "/usr/lib/python3/dist-packages/xpra/client/gtk_base/gtk_client_window_base.py", line 714, in calculate_window_offset
    from xpra.rectangle import rectangle #@UnresolvedImport
ModuleNotFoundError: No module named 'xpra.rectangle'
````

**To Reproduce**
Run xpra v4.3.3-r0 on the server and xpra v4.3.2-r0 on the client, then click the star icon in the Firefox URL-Bar

**System Information (please complete the following information):**
 - Server OS: Debian Bullseye
 - Client OS: Debian Bookworm
 - Xpra Server Version 4.3.3
 - Xpra Client Version 4.3.2

**Comment by allo-** [comment]
I see that it works with python3.9. So it seems to be an incompatiblity with python 3.10 in Debian bookworm.

**Comment by totaam** [comment]
Debian bookworm is not a stable released version so this is not meant to work.
Use the beta repositories for such distributions.

**Comment by allo-** [comment]
Oh, I didn't know there is a separate Beta Repo.

But I get an error there, that the Release file is not signed:

> E: The repository 'https://xpra.org/beta bullseye Release' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by allo-** [comment]
Thanks, the beta repo works for bookworm. For bullseye, the Release file is not signed for some reason.

**Comment by totaam** [comment]
> For bullseye, the Release file is not signed for some reason.

Are you sure?
What is the error message you are seeing?
Probably just: https://github.com/Xpra-org/xpra/issues/3499#issuecomment-1077136429

**Comment by allo-** [comment]
> E: The repository 'https://xpra.org/beta bullseye Release' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by allo-** [comment]
Bookworm has a PGP signature in https://xpra.org/beta/bookworm/InRelease and Bullseye does not have a `InRelease` file at all, but only an unsigned `Release` file.

**Comment by totaam** [comment]
Oh, you're right!
(Fixed)

**Comment by allo-** [comment]
That's what I call a fast reaction! Thanks!
