### ISSUE TITLE
Installation of x264-xpra fails on CentOS7 (RPM not signed)

### ISSUE THREAD

**Issue by olifre** [Xpra-org/xpra#3540]
**Describe the bug**
Installation fails:
```
wget -O /etc/yum.repos.d/xpra.repo https://xpra.org/repos/CentOS/xpra.repo
yum -y install  xpra \
                xpra-html5
[...]
Package x264-xpra-20211215-1.el7.x86_64.rpm is not signed
```

**To Reproduce**
see above

**System Information (please complete the following information):**
 - OS: CentOS7

**Additional context**
Can also be checked without installation:
```
wget https://xpra.org/dists/CentOS/7/x86_64/x264-xpra-20211215-1.el7.x86_64.rpm
rpm -qpi x264-xpra-20211215-1.el7.x86_64.rpm | grep Signature
Signature   : (none)
```

Interestingly, the modification time on:
https://xpra.org/dists/CentOS/7/x86_64/
shows 2022-01-25 for the given file, but it only started failing 1-2 days ago for me.

**Comment by totaam** [comment]
Probably caused by #3485 / #3446 : the endless Debian changes to signing and GPG keys.
I have just re-signed every single package and re-generated all the repodata.
Can you try again?

I wished I could say this won't happen again.. but I can't.

**Comment by olifre** [comment]
Indeed, I can confirm it's working again now. Many thanks for the fast reaction, as usual!

**Comment by totaam** [comment]
The missing signatures are due to gpg agent timeouts: https://github.com/Xpra-org/xpra/issues/3674#issuecomment-1640422672
