### ISSUE TITLE
Mouse click doesn't work under shadow mode

### ISSUE THREAD

**Issue by fweng322** [Xpra-org/xpra#3542]
**Describe the bug**
Xpra starts with shadow mode to shadow existing display (:0).  Then connect with browser to show the desktop.  The cursor could move but mouse clicking does not work at all.

Under start-desktop mode the mouse click works.

**To Reproduce**
1. server command: `xpra shadow --use-display=yes :0 --bind-tcp=0.0.0.0:33445`
2. client: using browser (Firefox 91, Chrome 101) to connect to http://<myip>:33445
3. mouse clicking does not work

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04
 - Client OS: Debian testing
 - Xpra Server Version 4.3.3
 - Xpra Client Version  HTML5 5.0-r1276-1

**Additional context**
Here is how I tested:
* I installed a ubuntu 20.04 in a virtual machine (VirtualBox), with screen size set to 1600x900.  
* Starting xpra with `xpra start-desktop --use-display=yes :0 --bind-tcp=0.0.0.0:33445` would not make the screen of this vm blank and I could control the display with browser without problem, no matter clicking, dragging, typing with keyboard, they all were okay.
* Starting xpra with `xpra shadow --use-display=yes :0 --bind-tcp=0.0.0.0:33445` I could see the display, but mouse clicking did not work at all.  Keyboard could input if I got the focus of a window.

**Comment by fweng322** [comment]
With debug message I saw that the mouse click event was sent, but not worked.

```
2022-05-18 08:45:12,768 client   2 mouse pointermove: [object PointerEvent]
2022-05-18 08:45:12,959 client   2 mouse pointerout: [object PointerEvent]
2022-05-18 08:45:13,698 client   2 mouse click: 1 true 471 498
2022-05-18 08:45:13,830 client   2 mouse click: 1 false 471 498
2022-05-18 08:45:14,901 client   2 mouse click: 1 true 471 498
2022-05-18 08:45:15,009 client   2 mouse click: 1 false 471 498
2022-05-18 08:45:29,709 client   2 mouse pointermove: [object PointerEvent]
2022-05-18 08:45:29,726 client   2 mouse pointermove: [object PointerEvent]
```

**Comment by Korynkai** [comment]
I am experiencing this issue as well, however I discovered that pounding on my touchpad or, for whatever reason, using my touchscreen seem to work to some extent, albeit this is still erroneous input... Likely some messages aren't being transmitted/received correctly, or are being filtered somehow, I assume?

**Comment by totaam** [comment]
Testing with:
* Ubuntu 20.04 running in VirtualBox
* default desktop environment
* recent versions of xpra (4.4.1 and 5.0 beta)
I am unable to reproduce any problems at all and the `-d mouse` server log shows the expected `xtest_fake_motion` and `xtest_fake_button` calls.

My guess is that your problems can come from one of these:
* using unusual / different environment
* having `python3-uinput` installed and enabled
* not having a window manager running in the shadow session?

Please provide steps to reproduce this bug and / or the problems shown in the server log.

**Comment by totaam** [comment]
Not heard back.

**Comment by MrElectronics** [comment]
This problem appeared to me today on a fresh vagrant box ubuntu 20.04 running gnome shell. 

I have been playing around with the code a bit and when I changed the following line [here](https://github.com/Xpra-org/xpra/blob/c18dc072f654fa4babc23ccf43534d3fc6f1c88c/xpra/server/shadow/gtk_shadow_server_base.py#L309) to simply return the opointer variable it started working:
```
    def _adjust_pointer(self, proto, device_id, wid:int, opointer) -> Optional[List]:
        window = self._id_to_window.get(wid)
        if not window:
            self.suspend_cursor(proto)
            return opointer
```

**Comment by totaam** [comment]
@fweng322 / @MrElectronics / @Korynkai  does the trivial change in the commit above help?

What type of client are you using? What version?
The pointer data should always have a valid window id, but I guess it's possible for it to go missing.

**Comment by MrElectronics** [comment]
Thanks a ton @totaam for your quick reply. Concerning your question, my apologies for not adding this information: 
- OS: Ubuntu 20.04.6 LTS
- Client html5 - version 5.0.5-r27-1 (debian package - beta repo)
- xpra - version 5.0.5-r27-1 (debian package - beta repo)
- Window Manager: gnome-shell version 3.36.9-0ubuntu0.20.04.3

I tried your commit. This one only partially works - when I click outside of a window it throws a stack trace along with the error message which seems to be happening [here](https://github.com/Xpra-org/xpra/blob/c18dc072f654fa4babc23ccf43534d3fc6f1c88c/xpra/server/shadow/gtk_shadow_server_base.py#L312):
AtributeError: "NoneType" object has no attribute "get_geometry"

However the revised code block (see below) seems to work properly:
```
[...]
    from xpra.x11 import shadow_x11_server
[...]
    def _adjust_pointer(self, proto, device_id, wid:int, opointer) -> Optional[List]:
        window = self._id_to_window.get(wid)
        if wid == 0 and not window and isinstance(self._id_to_window.get(1), shadow_x11_server.X11ShadowModel):
            wid = 1
            window = self._id_to_window.get(wid)
        if not window:
            self.suspend_cursor(proto)
            return None
        pointer = super()._adjust_pointer(proto, device_id, wid, opointer)
[...]
```
If I understood correctly, if there is not at least one window inside the id-to-window dict, the cursor position recalculation does not work properly. However, at least in the case of gnome shell there seems to be the main canvas sitting inside the aforementioned dict with id 1 that should to the trick. In using this clicks on the main canvas are not lost and cursor position recalc seems to work properly as well.

**Comment by totaam** [comment]
> Client html5 - version 5.0.5-r27-1 (debian package - beta repo)

No such version exists.
Are you using the html5 client or the python client?
>  it throws a stack trace

Please always include the full details.
> or the desktop handlers like the tray icon

Tray icons do have a window id, the tray docking area itself does not have one but then the clicks should not go through to the server in that case.

> However the revised code block (see below) seems to work properly:

This change is not correct.
Please try the new commit just above: 77a210014ac016946510a4d6c083a97e2d6cec9d

**Comment by fweng322** [comment]
> @fweng322 / @MrElectronics / @Korynkai does the trivial change in the commit above help?
> 
> What type of client are you using? What version? The pointer data should always have a valid window id, but I guess it's possible for it to go missing.

Sorry.  I reported this issue 1.5 year ago because at that time we were trying some remote desktop solutions, and since it was a problem that couldn't be solved we moved on to another solution (eventually we used NoVNC.)  So I'm not following this one anymore.  But it's good if this issue can be solved.

**Comment by totaam** [comment]
@MrElectronics sorry about that, I will get around to test these commits - I promise.
The latest one **should** be correct at last.

@fweng322 no worries. I'm pretty sure that it was working, even in the last year and a half, but perhaps not on Debian Testing.
