### ISSUE TITLE
' "_FORTIFY_SOURCE" redefined ' build error

### ISSUE THREAD

**Issue by sbradnick** [Xpra-org/xpra#3545]
Does anyone have any insight into how (maybe through Cython) `-D_FORTIFY_SOURCE=2` makes its way into a source build of xpra?

SUSE has, by my limited understanding at this point, switched to a universal `-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3` setting for CFLAGS.

Now I'm seeing a previously successful source (and even most current git pull) build failing with the following:
```
[   35s] running build_ext
[   35s] building 'xpra.buffers.membuf' extension
[   35s] creating build/temp.linux-x86_64-3.8
[   35s] creating build/temp.linux-x86_64-3.8/xpra
[   35s] creating build/temp.linux-x86_64-3.8/xpra/buffers
[   35s] gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -Ixpra/buffers -I/usr/include/python3.8 -c xpra/buffers/memalign.c -o build/temp.linux-x86_64-3.8/xpra/buffers/memalign.o -O3 -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -DOPENSSL_LOAD_CONF -fwrapv -fno-semantic-interposition -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -g -Wall -Werror -fPIC -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g
[   35s] <command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
[   35s] <command-line>: note: this is the location of the previous definition
[   35s] cc1: all warnings being treated as errors
[   35s] error: command 'gcc' failed with exit status 1
```
It seems that files like these are generated after the build is started and now there's a conflict:
```
abuild@tumbleweed-xfce:~>  grep FORTIFY_SOURCE ./rpmbuild/BUILD/xpra-4.4+git20220519.9be098cc7/xpra/buffers/xxh.c
            "-D_FORTIFY_SOURCE=2",
            "-D_FORTIFY_SOURCE=2",
            "-D_FORTIFY_SOURCE=2",
            "-U_FORTIFY_SOURCE",
            "-D_FORTIFY_SOURCE=3",
abuild@tumbleweed-xfce:~>  head ./rpmbuild/BUILD/xpra-4.4+git20220519.9be098cc7/xpra/buffers/xxh.c
/* Generated by Cython 0.29.28 */

/* BEGIN: Cython Metadata
{
    "distutils": {
        "depends": [
            "xpra/buffers/xxhash.h"
        ],
        "extra_compile_args": [
            "-O3",
abuild@tumbleweed-xfce:~>
```

I'm attaching the full build log in case it's of value. Is there a way to disable how files are created during build time which reference `-D_FORTIFY_SOURCE=2`?

[xpra_build.log](https://github.com/Xpra-org/xpra/files/8744872/xpra_build.log)

**Comment by totaam** [comment]
Since the `membuf` module does not use a `pkgconfig` file, the only places that can modify the compiler options are the `CFLAGS` sysconfig:
https://github.com/Xpra-org/xpra/blob/9be098cc7cd79b642eec03e09570b9a77b346fe4/setup.py#L692-L698

Perhaps suse should be added to the list of distros that do patch distutils?

And the environment variable `CFLAGS`:
https://github.com/Xpra-org/xpra/blob/9be098cc7cd79b642eec03e09570b9a77b346fe4/setup.py#L773

**Comment by sbradnick** [comment]
I added `or is_openSUSE()` to the end of line 694 and it worked as usual :+1: ; the line where it failed previously certainly doesn't appear to have duplicated parameters on it, but I'm certainly not well versed in these specifics.

Is `or is_openSUSE()` something you can add (as you did for us earlier) or would you like a PR? Either way, thank you so much for addressing it so quickly and I'll be sure to dig into setup.py if something else comes up during a build and there are other `is_<a distro>()` defined around it.

**Comment by totaam** [comment]
See also #3597
