### ISSUE TITLE
On Windows, xpra client does not connect using ssh key.

### ISSUE THREAD

**Issue by xihh87** [Xpra-org/xpra#3547]
**Describe the bug**
On Windows, xpra client does not connect to ssh xpra available only with ssh key.

**To Reproduce**
1. Configure sshd to nonstandard port and to only use ssh key auth.
1. Configure `~/.ssh/config` to use a specific Port, User and IdentityFile to connect to server. (Test that this configuration works from PowerShell.)
1. Server command: `xpra start --clipboard-direction=both --clipboard=yes --desktop-scaling=auto --mdns=no --printing=no --pulseaudio=no --sharing=yes --webcam=no`
4. Client comand:
    -  `xpra attach --debug --ssh='ssh' ssh://user@alias:port/display` # works on linux and osx.
    -  `xpra attach --debug --ssh='ssh -i /path/to/key' ssh://user@alias:port/display`
    -  `ssh -fN server`
        `xpra attach --debug --ssh='ssh' ssh://user@alias:port/display`
6. The server asks for passwords and dies (or just dies), it does not provide additional information on the bug. Could not find the logs to further diagnose.

**System Information (please complete the following information):**
 - Server OS: [Arch Linux]
 - Client OS: [Windows 10, Windows 11]
 - Xpra Server Version [xpra-4.2.3-4]
 - Xpra Client Version [xpra-4.2.3]

**Additional context**

- The server does not accept passwords, only public key auth.
- The client can connect to the server using ssh from PowerShell.

**Comment by totaam** [comment]
Not heard back.
