### ISSUE TITLE
xpra insists on starting the entire desktop

### ISSUE THREAD

**Issue by gdkrmr** [Xpra-org/xpra#3548]
I have a new remote machine with Xubuntu 22.04 and when I want to access it through xpra I always get the following error in a window on the local machine:

> Xsession: unable to launch "true" X session --- "true" not found; falling back to default session.

If I press "okay" in that window, the entire Xfce desktop of the remote machine launches. This does not happen on other machines running Xubuntu 20.04.

**Comment by totaam** [comment]
Are you using the official packages from xpra.org?
And if so, what version?
My guess is that you need to remove `--source=/etc/profile` from your configuration.

**Comment by gdkrmr** [comment]
I am using the official versions from the repos on the local machine it is Manjaro (xpra v4.2.3-r3) and the remote Ubuntu 22.4 machine (xpra v3.1)

```
me@remote$ xpra showconfig | grep source
pulseaudio-configure-commands           = 'pactl set-default-sink Xpra-Speaker', 'pactl set-default-source Xpra-Microphone.monitor'
sound-source                   = ''
source                         = 
source-start                   = 
```

**Comment by totaam** [comment]
Those are not official versions in any shape or form.
Please see https://github.com/Xpra-org/xpra/wiki/Versions, https://github.com/Xpra-org/xpra/wiki/Distribution-Packages and https://github.com/Xpra-org/xpra/wiki/Distribution-Packages-Ubuntu

**Comment by gdkrmr** [comment]
you were right, I installed xpra from your repository and it seems to work now. Thanks for the hint and the links, I wasn't aware that Ubuntu is doing it's own thing.
