### ISSUE TITLE
Integration/embedding xpra into Flask/Django app

### ISSUE THREAD

**Issue by nmz787-intel** [Xpra-org/xpra#3549]
**Is your feature request related to a problem? Please describe.**
I have a Flask app that is performing automation with SSH to linux via paramiko. I want to now be able to display programs using X11 forwarding to the web client. It seems embedding xpra into my server, to perform the x11 to websocket translation would be useful, as well as using the HTML xpra client.

**Describe the solution you'd like**
a howto or tutorial or example

**Describe alternatives you've considered**
I was searching for X11 server in JavaScript when I found this project

**Comment by totaam** [comment]
It's not clear what "your server" is or does, so I can't comment on where the embedding should take place.
Embedding the `xpra-html5` client is fairly easy and that's one aspect that is being improved.
The xpra server is not usually embedded, just executed.

**Comment by nmz787-intel** [comment]
my server is a Python Flask webserver. I already have this doing SSH to remote linux machines, to run commands, get the output, return to the webpage the user views. Since I see xpra server is coded in Python, it seems feasible to use xpra as a Python library, to attach my [SSH forwarded X11 connection](https://docs.paramiko.org/en/stable/api/channel.html#paramiko.channel.Channel.request_x11), and then use the `xpra-html5` client to connect to the websocket that presumably would be exposed through my Flask app but handled by the Xpra library/backend.

**Comment by totaam** [comment]
Xpra does not use SSH X11 forwarding at all.
I guess you could start an xpra server then somehow connect your html5 client to the paramiko channel. I have no idea how you would do that though.
Running "xpra _proxy :DISPLAYNO` on the server gives you a stdin / stdout channel that any xpra client can talk to.

**Comment by totaam** [comment]
> I guess I thought xpra was a proxy between X11 and WebSockets

It can be.

> Since I cannot run xpra on the remote SSH servers

That's going to be a major hinderance.

> connect the SSH X11 forwarding to xpra which then sends it on to HTML5

Running xpra whilst connected to an X11 server running over ssh is a bad idea.
Performance would be very poor.

And it's still not clear to me where this xpra server would run.

> I can't tell if you're saying I can open xpra without a specific graphical process

I don't understand what you mean.

> I'm not sure what "any xpra client" means, are there others besides the HTML5 client?

Yes the xpra packages come with a server and client.

**Comment by nmz787-intel** [comment]
> > I guess I thought xpra was a proxy between X11 and WebSockets
> 
> It can be.

Can you give some keywords to help me localize where in the code I should start digging?

> > connect the SSH X11 forwarding to xpra which then sends it on to HTML5
> 
> Running xpra whilst connected to an X11 server running over ssh is a bad idea. Performance would be very poor.

I thought python-xpra would be the x11 server. I assumed python-xpra acts as a X11 server, to "convert" X11 protocol into something else (xpra-protocol??), which is then easily communicated with html5-xpra.

> And it's still not clear to me where this xpra server would run.

in my use case there are 3 machines.
(linux machine where I want to run a GUI program) ----SSH connection -- (linux machine running in CloudFoundry hosting VM, running X11 proxy) ---HTTP/ajax/WebSocket connection(s) --- (end-user with web-browser, which wants to see and interact with GUI program running on)

**Comment by totaam** [comment]
> Can you give some keywords to help me localize where in the code I should start digging?

It's not clear what you want to look into.
The websockets code is trivial:
https://github.com/Xpra-org/xpra/tree/master/xpra/net/websockets
The rest is not.

> I thought python-xpra would be the x11 server

No. I'm assuming you are talking about the RPM packaging?
There is a `python-xpra-server` and `python-xpra-client`.

> to "convert" X11 protocol into something else (xpra-protocol??), which is then easily communicated with html5-xpra

That's one way to look at it.
The X11 server code lives here:
https://github.com/Xpra-org/xpra/blob/master/xpra/x11/server.py
And extends the more generic server classes:
https://github.com/Xpra-org/xpra/tree/master/xpra/server
The protocol is here:
https://github.com/Xpra-org/xpra/blob/master/xpra/net/protocol.py

> in my use case there are 3 machines.

Like I said, using ssh forwarding with xpra is usually a terrible idea.
You get all the disadvantages and almost none of the benefits.
