### ISSUE TITLE
http upgrades are not enabled

### ISSUE THREAD

**Issue by Booabi** [Xpra-org/xpra#3550]
**Xpra Log:**
Error: tcp connection failed:
packet from 172.18.0.7:21346
received on 0.0.0.0:8911
this packet looks like a 'http' packet
http upgrades are not enabled

**Web response:**
Server Error
Error code 400.
Message: this port does not support HTTP requests.
Error code explanation: 400 = Bad request syntax or unsupported method.

**Command Used:** XPRA_ACK_TOLERANCE=1000 xpra start --start=xterm --min-quality=100 --bind-tcp=0.0.0.0:8911

Hi, I am new to Xpra and I am trying to hit the xpra from web using https://mydomain.com  which is pointing to 0.0.0.0:8911
Please assist me on this

**Comment by totaam** [comment]
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

What version, distro, etc
