### ISSUE TITLE
Xpra doesn't utilize VAAPI codec

### ISSUE THREAD

**Issue by interj** [Xpra-org/xpra#3556]
**Describe the bug**
Xpra detects h264 vaapi encoder but doesn't utilize it. I had to exclude h265 codec from vaapi detection, because it completely breaks vaapi context when accessed apparently.

**To Reproduce**
1. XPRA_VAAPI=1 XPRA_VAAPI_ENCODINGS=h264 XPRA_LIBAV_TRACE=1 xpra start  --bind-tcp=192.168.9.10:14500
2. "C:\Program Files\Xpra\Xpra.exe" start --exit-with-client=False --exit-with-children=True --start-child=konsole --attach=True --splash=True tcp://interj@192.168.9.10:14500
3. playing a video in the browser causes high cpu load, `intel_gpu_top` reports no load on a graphic card

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Client OS: Windows 10
 - Xpra Server Version `xpra v4.3.3-r31317 (g0af32cf59)`
 - Xpra Client Version `xpra 4.3.3 commit g337d861d2 from v4.3.x branch`

**Additional context**

Card has the needed capabilities:
```
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.2.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP
```

H264 vaapi codec is found:
`2022-06-17 13:37:36,914 found 1 vaapi codecs: h264`

Xpra uses x264 codec but no gpu load is present:
```
xpra info | grep "encoder="
warning: invalid compressor(s) specified: lzo
client.connection.encoder=rencode
client.window.4.encoding.pipeline_option.1.encoder=x264
client.window.4.encoding.pipeline_option.2.encoder=x265
client.window.4.encoding.pipeline_option.encoder=x264
logging.filters.Codec.encoder=All encoders
```

This log appears once:
```
2022-06-17 13:38:38,792 Warning: using non-video fallback encoding
2022-06-17 13:38:38,792  for XShmImageWrapper(BGRA: 4, 58, 1057, 510) of window 2
```

This log repeats every minute or so:
```
2022-06-17 13:38:39,894 Error: no video pipeline options found for BGRA 32-bit at 1062x405
2022-06-17 13:38:39,895 Error: failed to setup a video pipeline for auto encoding with source format BGRA
2022-06-17 13:38:39,895  all encoders: 
2022-06-17 13:38:39,895  supported CSC modes: 
2022-06-17 13:38:39,895  supported encoders: 
2022-06-17 13:38:39,895  encoders CSC modes: 
```

**Comment by totaam** [comment]
> If I try to use `hevc_vaapi` codec instead it blows up:
> (..)
> And apparently even checking the hevc capabilities causes vaapi context to catastrophically break in `libav`

It's not surprising.
A common interface to multiple hardware backends is hard to implement safely.
That's why we gave up on enabling it by default: too many combinations breaking in unpredictable ways that aren't going to be testable or reproducible.

> I just can't get xpra to choose it as a preferred encoder:

That's a different issue.
In order to avoid recycling many hardware contexts in a short period of time (which can cause real problems - including lockups, also because it can cause the screen updates to stutter as hardware takes longer to initialize), hardware encoders are defined as having a higher _setup-cost_ value, which means that other software encoders will be used initially until the server is confident that the stream is here to stay.
You can view which video encoding pipelines are being considered at runtime using:
```shell
xpra info | grep pipeline_option
```
You can force the hardware encoder by simply turning off the software encoders. (but I would not recommend it)

> Maybe disabling `hevc_vaapi` detection in `init_vaapi` altogether would alleviate some of these bugs, like it did for me.

Done, see commit above.

> I can see it when running konsole (KDE terminal), it might utilize alpha channel.

It does. That's the one then, this should never be using a video encoder, no matter how quickly the window is updating because it should be detected as a `text` application.

**Comment by interj** [comment]
So, apparently `h264_vaapi` encoder isn't considered at all
```
xpra info :2 | grep pipeline_option
warning: invalid compressor(s) specified: lzo
client.window.2.encoding.pipeline_option.1.encoder=x264
client.window.2.encoding.pipeline_option.1.format=YUV420P
client.window.2.encoding.pipeline_option.1.score=54
...
client.window.2.encoding.pipeline_option.2.encoder=x265
client.window.2.encoding.pipeline_option.2.format=YUV420P
client.window.2.encoding.pipeline_option.2.score=45
...
client.window.2.encoding.pipeline_option.encoder=x264
client.window.2.encoding.pipeline_option.format=BGRX
client.window.2.encoding.pipeline_option.score=61
```

In the last log mentioning `h264_vaapi` looks like the codec was closed after a failed conversion from `YUV420P` to `NV12`? Not sure if that's what `ImageWrapper(NV12:(0, 0, 64, 32, 32)` is supposed to do.
```
2022-06-19 15:37:23,534 avcodec_receive_packet(..)=0
2022-06-19 15:37:23,534 avcodec_receive_packet returned 0xc bytes of data, flags: 
2022-06-19 15:37:23,534 compress_image(ImageWrapper(NV12:(0, 0, 64, 32, 32):None), None) avcodec_receive_packet avpacket=0x7f3beab7b480
2022-06-19 15:37:23,534 avcodec_receive_packet(..)=-11
2022-06-19 15:37:23,534 ffmpeg avcodec_receive_packet EAGAIN
2022-06-19 15:37:23,534 compress_image(ImageWrapper(NV12:(0, 0, 64, 32, 32):None))    12 bytes (1 buffers) for h264 with client options: {'csc': 'YUV420P', 'frame': 1}
2022-06-19 15:37:23,534 <module 'xpra.codecs.enc_ffmpeg.encoder' from '/home/interj/.local/lib/python3.9/site-packages/xpra/codecs/enc_ffmpeg/encoder.cpython-39-x86_64-linux-gnu.so'>: h264 / NV12 / YUV420P passed
2022-06-19 15:37:23,534 enc_ffmpeg.Encoder({'version': (58, 134, 100), 'encoding': 'h264', 'formats': ['NV12'], 'type': 'ffmpeg', 'frames': 2, 'width': 64, 'height': 32, 'video-codec': b'h264_vaapi', 'video-description': b'H.264/AVC (VAAPI)', 'src_format': 'NV12', 'encoder_width': 64, 'encoder_height': 32}).clean_encoder()
2022-06-19 15:37:23,534 clean_encoder() freeing AVFrame: 0x7f3be00c4ac0
2022-06-19 15:37:23,534 clean_encoder() freeing AVCodecContext: 0x7f3be020ccc0
2022-06-19 15:37:23,534 libav: 'Freed output buffer 0'
2022-06-19 15:37:23,536 clean_encoder() done
2022-06-19 15:37:23,536 enc_ffmpeg.Encoder(*closed*).clean_encoder()
2022-06-19 15:37:23,536 clean_encoder() freeing AVCodecContext: 0x0
2022-06-19 15:37:23,536 clean_encoder() done
2022-06-19 15:37:23,536 xpra.codecs.enc_ffmpeg.encoder: cleanup_module=<built-in function cleanup_module>
2022-06-19 15:37:23,536 enc_ffmpeg.cleanup_module()
```

> It does. That's the one then, this should never be using a video encoder, no matter how quickly the window is updating because it should be detected as a `text` application.

Looks like it is doing that properly then, because `xpra info :7 | grep pipeline_option` (:7 has only the konsole open) outputs nothing and I can see `webp` being utilized, but the  `Error: failed to setup a video pipeline for auto encoding with source format BGRA` log is still appearing every 10 seconds or so.

**Comment by totaam** [comment]
> `client.window.2.encoding.pipeline_option.2.encoder=x265`

Huh. Why is `x265` even available? It should not be, it is not enabled by default and is not enabled in any of the official xpra builds.

> but the `Error: failed to setup a video pipeline for auto encoding with source format BGRA` log is still appearing every 10 seconds or so.

It must be for a different window.

**Comment by interj** [comment]
> Huh. Why is `x265` even available? It should not be, it is not enabled by default and is not enabled in any of the official xpra builds.

No idea. Probably having libx265 installed was enough for setup.py to include it, but I still didn't enable it in runtime or anywhere else.

> It must be for a different window.

No other window in that session and the resolution roughly matches: `client.window.2.dimensions=(1557, 1159)` matches the `Error: no video pipeline options found for BGRA 32-bit at 1533x1065` without borders. The resolution in the log changed after I resized `konsole` window too. And the log appears reliably when I hover on the tab, it produces a little popup with the tab title - it spawns correctly in the client, but still causes the error log to appear.

**Comment by interj** [comment]
> And the log appears reliably when I hover on the tab

... or not. It appeared when I caused the first pop-up to spawn, but not for the subsequent ones.

**Comment by interj** [comment]
va api is a gift that keeps on giving. I managed to get it to work after removing `libx265-dev` (x265 codec was activating automatically in the setup if the lib was present), fiddling with build environment and rerunning `setup.py`, but now xpra is leaking memory when utilizing the `h264_vaapi`. Anyway, I will close this one since I can't reproduce it anymore.
