### ISSUE TITLE
Installation fails on CentOS 7

### ISSUE THREAD

**Issue by olifre** [Xpra-org/xpra#3563]
**Describe the bug**
```
$ yum -y install  xpra xpra-html5
...
--> Finished Dependency Resolution
Error: Package: python2-xpra-3.1.2-10.30245xpra1.el7.x86_64 (xpra)
           Requires: libvpx.so.6()(64bit)
           Available: libvpx-xpra-1.9.0-1.el7.x86_64 (xpra)
               libvpx.so.6()(64bit)
           Available: libvpx-xpra-1.9.0-1.el7_9.x86_64 (xpra)
               libvpx.so.6()(64bit)
           Installing: libvpx-xpra-1.11.0-1.el7.x86_64 (xpra)
              ~libvpx.so.7()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**To Reproduce**
```
wget -O /etc/yum.repos.d/xpra.repo https://xpra.org/repos/CentOS/xpra.repo
yum -y install  xpra xpra-html5
```

**System Information (please complete the following information):**
- `CentOS Linux release 7.9.2009 (Core)`

**Additional context**
I am not fully sure I understand the error message correctly, but I asusme the problem is that `python2-xpra` is not built against the latest version of `libvpx-xpra` available in the repositories (and `yum` does not seem to select an older version of `libvpx-xpra` in that case, but bail out).

**Comment by totaam** [comment]
Sorry about that.
The new `libvpx` came from the 4.3.4 release, but there are no new `xpra` or `xpra-html5` packages for CentOS 7, so I should have waited until 3.1.3 was released to include the new `libvpx` packages in the repo.

I've nuked them from the `repodata` now - should work, untested.

**Comment by olifre** [comment]
Thanks, indeed that fixes it (have to force `yum` to refresh metadata e.g. by using `yum clean all` first) :+1: . 

I'm still a bit astonisched `yum` was not clever enough to just ignore the newer `libvpx` in dependency resolution (as it clearly listed the older `libvpx` versions as alternatives), but that's not something `xpra` can do anything about. 

Thanks!
