### ISSUE TITLE
Artifacts https://www.xpra.org/beta/windows/?C=M&O=D&P=*r31*.zip* are missing verification identifiers

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3585]

**Comment by totaam** [comment]
Ah. `setuptools` broke for the [umpteenth time](https://stackoverflow.com/questions/7446187/), which broke the signing / symlinking scripts and I didn't notice (TBH, I think I saw it and decided to hope it would fix itself all on its own..):
```python
Traceback (most recent call last):
  File "./sign-osxwin32-images.py", line 226, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```
I've changed the script to not use the `setuptools` trainwreck.

Should be OK now.

**Comment by stdedos** [comment]
_Note to myself: "eventually" write packaging tests to not allow @totaam publish whatever he wants 😛_
