### ISSUE TITLE
Beta server revision is `M`, build date is last year

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3588]
![image](https://user-images.githubusercontent.com/133706/180067000-cf381c3c-487e-45ea-9b5f-908953e751d8.png)

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.3 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Comment by totaam** [comment]
Confirmed!
```shell
wget https://xpra.org/beta/focal/main/binary-amd64/xpra_4.4-r31612-1_amd64.deb
ar x xpra_4.4-r31612-1_amd64.deb
tar -Jxf data.tar.xz 
grep DATE usr/lib/python3/dist-packages/xpra/build_info.py 
BUILD_DATE='2021-12-22'
```

**Comment by totaam** [comment]
Heisenbug alert: running the build scripts by hand I get the correct date!?
And why was it using this specific date?

**Comment by totaam** [comment]
This seems to be fixed.
My Ubuntu 20.04 VM is showing a 4.4 build with the date `2022-08-05`.
