### ISSUE TITLE
Typo in variable name on branch v4.3.x

### ISSUE THREAD

**Issue by lschilli** [Xpra-org/xpra#3606]
https://github.com/Xpra-org/xpra/blob/df4632534a5b2b7b2d59eca967e9dd70b83ee4c5/xpra/client/ui_client_base.py#L471

There is a typo I believe: bitsstr vs. bitstr.

**Comment by totaam** [comment]
Thanks!
This was caused by e400032cd1be07710ed21dbf37caa87dfae37387 - which I had applied by hand. Oops.
