### ISSUE TITLE
Clipboard no longer works

### ISSUE THREAD

**Issue by sbradnick** [Xpra-org/xpra#3607]
**Describe the bug**
Clipboard "Both directions" no longer working with dcb5278 (or c8f68c6)

**To Reproduce**
1. `xpra start --start=xterm --bind-tcp=<some ip>:10000`
2. `xpra attach tcp://<some ip>:10000`
3. Using the menu, "Clipboard" is greyed out and copy/paste doesn't function

**System Information (please complete the following information):**
- Server OS: openSUSE Tumbleweed
- Client OS: openSUSE Tumbleweed
- Xpra Server Version: git dcb5278
- Xpra Client Version: git dcb5278

**Additional context**
- I have success with cc03f57 & c52d8ac; haven't tried past that since going to dcb5278
  - df36fcc certainly seems to be where it breaks
- I assume it's still set to work out-of-the-box, but if there's some flag I'm missing or you think a `-d clipboard` would be useful, I'm happy to provide it.

**Comment by totaam** [comment]
Sorry about that!
The commit above fixes things.
