### ISSUE TITLE
Xpra attach fails with "all SSH remote proxy commands have failed" for non-POSIX remote shell

### ISSUE THREAD

**Issue by eblanton** [Xpra-org/xpra#3610]
**Describe the bug**
Xpra fails to attach to a remote server under some circumstances if the user's shell on the remote server is not a POSIX shell.  (Sometimes it seems to work, but for users for whom it does not work, it reliably does not work.)

The reported error is "all SSH remote proxy commands have failed - is xpra installed on the remote host?"

Changing the user shell to `/bin/bash` with `chsh` fixes the problem, so far reliably.

**To Reproduce**
1. Set a remote server's login shell to /bin/tcsh
2. Start the remote server with (use an appropriate session) `xpra start-desktop --start=xfce4-session :100`
3. Attach to the server using the Xpra GUI interface, via ssh.

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.5 LTS
 - Client OS: macOS (Apple Silicon); may affect other platforms, but that's our user base
 - Xpra Server Version 4.3.4-r0
 - Xpra Client Version 4.3.4-r0 _and_ 4.4-r31681 beta .pkg from xpra.org

**Additional context**
We have about seventy or so users attaching Xpra to remote servers, _mostly_ using Apple Silicon clients.  User shells are a mix of bash and tcsh.  Only _some_ tcsh users experience this problem, and I do not know what sets them apart (the accounts are all new, should be nearly identical creations from an identical `/etc/skel`); possibly something on the client side, but we cannot identify it.  I have been unable to reproduce the problem on my own account, even when switching to tcsh.  The specific magic sauce is elusive, but non-POSIX remote shell appears to be the ultimate culprit.

**Comment by totaam** [comment]
Please run the client with `-d ssh` and post the output.
I believe you don't need a MacOS client specifically to test this.
The command line used by the SSH shell should be the same no matter the OS.

We have had problems with `tcsh` before, but that has been fixed. Perhaps it broke again.

**Comment by eblanton** [comment]
As I recall, -d ssh said nothing particularly enlightening, but I'm getting this third-party from students.  I will find a student who had this problem, revert to tcsh, and try to reproduce with debugging enabled.  It may take a couple of days.

**Comment by eblanton** [comment]
(My current suspicion is that xpra expects the login shell to be silent, and that their login shell is NOT.  I have not been able to verify this, due to schedules.)

**Comment by totaam** [comment]
> .. their login shell is NOT

@eblanton that would make sense. Xpra expects data packets on stdin / stdout.
A workaround for that would be possible, but it would be a bit fuzzy and non-trivial.

**Comment by eblanton** [comment]
Certainly a login shell should print nothing when invoked non-interactively (assuming xpra invokes ssh non-interactively, which is the default when running a remote command); however, the usual workaround for this is to use a start token of some kind that is unlikely to appear in the login preamble.

**Comment by totaam** [comment]
> assuming xpra invokes ssh non-interactively

I believe that this is correct. My understanding is that we only get an interactive shell by calling [invoke_shell](https://github.com/paramiko/paramiko/blob/0f3beefa5618ca46ea880eca696dca488fcc2bb6/paramiko/client.py#L526)

> the usual workaround for this is to use a start token

Yes, and the token we already have should be safe since it contains a null byte.
However, that's no guarantee.. Users do funny things sometimes.

**Comment by totaam** [comment]
TIL:
```
exec_command('command -v xpra')=1
exec_command out=''
exec_command err='command: Command not found.\n'
```
According to #3215, _Using `command -v` is `POSIX` compliant (`which` is not)_

**Comment by totaam** [comment]
8db6d4620f0d6d9746079f0e2786873ac5bb0622 helps a little bit with your specific issue of a non-POSIX shell not having the `command` command installed.

But there was still a problem parsing the output of `command -v` or `which` when I add echo statements to my `.bashrc`:
```
exec_command('which xpra')=0
exec_command out='hello\n'
exec_command err='OK\n'
```
429f3bebd12b30ad3ea66f1b89d9a4254a87bda4 deals with this by only using at the last line of output, which should be from `command -v` or `which`.
Works-for-me(tm).

**Comment by eblanton** [comment]
I have confirmed that the beta Xpra-Python3-x86_64-4.4-r31896.pkg for macOS does indeed solve this problem for my users.  Thank you!

**Comment by totaam** [comment]
FWIW: `rsync` fails to connect over `ssh` when stdout is polluted in this way.

**Comment by eblanton** [comment]
NB that it turned out that it was _not_ output pollution, it was `xpra` expecting `which`, which `csh` does not provide (as resolved above).
