### ISSUE TITLE
Include original byte-size in lz4 compressed packets

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3612]
**Is your feature request related to a problem? Please describe.**
Not really. When decompressing LZ4, we dont know how big the uncompressed data would be, so we need to allocate a fairly big buffer to fit the data. After decompressing, we need to copy the data (or shrink the  output buffer or create a mem. view)
It would be nicer to know the decompressed data size and allocate exactly the right size buffer.

**Describe the solution you'd like**
Length of the uncompressed data as part of the packet header?

**Comment by totaam** [comment]
We're out of space in the packet header which uses a fixed size, but we should be able to add this as an option in the metadata for pixel packets.
Another option would be to define a new `lz4-plus` flag (similar to what was done for `rencodeplus`) and then add the new size header to the `lz4` binary blob.
