### ISSUE TITLE
Custom shortcut keys delayed on server

### ISSUE THREAD

**Issue by angus73** [Xpra-org/xpra#3613]
I have a minor but annoying problem, on a xpra server: when xpra is active on the server, all my custom keyboard shortcuts (customized in the Gnome Settings panel) don't trigger immediately but after 25 seconds. Stopping xpra by using the command "xpra stop" does not solve the problem by itself; the only way I found to solve it is by running "xpra stop" + restarting the whole Gnome session. I wonder if there is at least a workaround to have the shortcuts running correctly without restarting Gnome.

**To Reproduce**
1. server command
2. `ps aux |grep xpra` (with no clients connected) returns:
```
angus    209333  0.0  1.6 1705692 539760 ?      Sl   set06   0:35 /usr/bin/python3 -s /usr/bin/xpra start :666 --splash=no --env=XPRA_FORCE_XSETINPUTFOCUS=1 --env=XPRA_PROXY_START_UUID=92a9d9bb743044f8a1b75e9b0e4376cd --daemon=yes --systemd-run=no
angus    209390  0.0  0.6 565076 222324 ?       Ssl  set06   0:07 /usr/libexec/Xorg-for-Xpra-:666 -noreset -novtswitch -nolisten tcp +extension GLX +extension RANDR +extension RENDER -auth /home/angus/.Xauthority -logfile /run/user/1000/xpra/666/Xorg.:666.log -configdir /run/user/1000/xpra/xorg.conf.d/209333 -config /usr/local/etc/xpra/xorg.conf -depth 24 :666
```
3. client command
The problem is present with no connected clients; is it needed to report here the previous client commands issued since the server had been started?

4. specific action to trigger the bug
Press a customized shortcut key on the keyboard (e.g. ctrl+alt+T, which I customized in order to open a terminal window)

**System Information (please complete the following information):**
 - Server OS: Fedora 36
 - Client OS: Ubuntu 18.04
 - Xpra Server Version: xpra-4.3.4-1.fc36.x86_64
 - Xpra Client Version: xpra/bionic,bionic 4.0.6-r28351-1 i386

**Comment by totaam** [comment]
Some notes and questions:
* why do you use `XPRA_FORCE_XSETINPUTFOCUS=1`?
* `Xpra Client Version 4.0.6-r28351-1 i386` is not a supported version
* I see `XPRA_PROXY_START_UUID` so this means that the session was started through the system wide proxy, is that correct? If so, have you tried without?
* please include the initial commands used to start the server, ie: `xpra start --start=xterm`
* please include the server log
* do you have `python-uinput` installed?

**Comment by totaam** [comment]
Not heard back, I assume this is a problem in older versions.

**Comment by angus73** [comment]
Hi totaam, thank you for your reply, sorry if I reply just now but I couldn't do it before.

> Some notes and questions:
> 
>     * why do you use `XPRA_FORCE_XSETINPUTFOCUS=1`?
I found it as a workaround to have the keyboard running in a xpra session which calls a windows  application on the server through wine. May I try without it and see if the delay disappears?

> 
>     * `Xpra Client Version 4.0.6-r28351-1 i386` is not a supported version
Now on the client, maybe after an update, I see 
$ xpra --version
xpra v4.3.4-r0

I can try again and let you know

> 
>     * I see `XPRA_PROXY_START_UUID` so this means that the session was started through the system wide proxy, is that correct? If so, have you tried without?
Sorry for my poor knowledge, but I don't know what the system wide proxy is, so it would be great if you tell me, and how to try without

> 
>     * please include the initial commands used to start the server, ie: `xpra start --start=xterm`
the server is started by just

xpra start --env=XPRA_FORCE_XSETINPUTFOCUS=1 ssh://mybox.mydomain.com/666

and after that I use
xpra attach ssh://mybox.mydomain.com/666 --start=xterm
xpra attach ssh://mybox.mydomain.com/666 --start=firefox
...and others

> 
>     * please include the server log
Sorry, I just can't find any log in the server, can you help me to find it?
The server's /etc/xpra/xpra.conf is empty (all lines begin with #) and there isn't any ~/.xpra directory. In /run there isn't any <uid> directory (where <uid> can be either the user name or user numeric id in the system). There is a /run/xpra directory, but it's empty.

> 
>     * do you have `python-uinput` installed?
on the server (Fedora): no;
on the client (Ubuntu): it seems there isn't any available package whose name matches the name python-ui*
(where) do I have to install it?

Many thanks,
Angus

**Comment by totaam** [comment]
> > why do you use `XPRA_FORCE_XSETINPUTFOCUS=1`?
> >
> I found it as a workaround to have the keyboard running in a xpra session which calls a windows application on the server through wine.
> 
It would be best to fix the server to not require this workaround. Did you create a ticket for this issue?

> `xpra v4.3.4-r0`
> I can try again and let you know
> 
FYI: latest is now 4.4-r0

> > I see `XPRA_PROXY_START_UUID` so this means that the session was started through the system wide proxy, is that correct? If so, have you tried without?
> >
> Sorry for my poor knowledge, but I don't know what the system wide proxy is, so it would be great if you tell me, and how to try without
> 
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Service.md
It shouldn't make any difference, but you can add `--start-via-proxy=no` to your command line to be sure.

> Sorry, I just can't find any log in the server, can you help me to find it?

When you start the server, it should tell you.
On Fedora this usually ends up in `/run/user/$UID/xpra/$DISPLAY/server.log`.
ie: for me with display `:10` and uid `1000`: /run/user/1000/xpra/10/server.log`

> > do you have `python-uinput` installed?
> > on the server (Fedora): no;

OK. Just checking.
> on the client (Ubuntu): it seems there isn't any available package whose name matches the name python-ui*
> (where) do I have to install it?

Don't!
It does more harm than good and it isn't used by the client anyway.

**Comment by angus73** [comment]
This problem doesn't happen any more  after cleaning old configuration files and upgrading to v5.0-r0. Thank you.
