### ISSUE TITLE
Xpra running applications are all in a single Xpra dock icon on Ubuntu Jammy (22.04)

### ISSUE THREAD

**Issue by ogzs** [Xpra-org/xpra#3614]
Hi,

Before (in Ubuntu 20.04), when I was running applications through Xpra, they were correctly assygned by the Ubuntu dock to the right dock icon (for example, Firefox in xpra was displayed as an instance of Firefox applicatin in the dock). That was just perfect.

Now, since I upgraded to Ubuntu 22.04, all the application windows that are running through Xpra are grouped in a single Xpra application icon, and I have to click on it to see the actual application windows.

I didn't change the way I use Xpra (xpra start ...). And I'm using the stable release from the xpra.org repo.
Is there something I can do to help debugging this ?

Thanks!
Olivier Godart

**Comment by ogzs** [comment]
Versions: both the server and the client are running Xpra 4.3.4 on Ubuntu 22.04
Server: Xpra X11 seamless server version 4.3.4-r0 64-bit
Client: Xpra GTK3 X11 client version 4.3.4-r0 64-bit

**Comment by totaam** [comment]
I believe that this is a gnome "feature" where they don't let us specify which icon we want for each window or dock, or which grouping to use...
I am afraid that there isn't much we can do about this.
Perhaps try a different desktop environment?

**Comment by ogzs** [comment]
Thanks,
I'm trying to figure out which of the changes between Gnome 3.36 and Gnome 3.42 is responsible of that behavior.
Do you know the name of the component I should look at ? (which library or program does that feature?)

**Comment by ogzs** [comment]
Indeed, it's related to Wayland. I tried with Xorg, and I've got almost the normal behavior (except that the icons are all mixed up : "notepad" in the "files" app icon, firefox in the keepass app icon,... but I will retry and see if it's not just a temporary issue)

**Comment by totaam** [comment]
Not much we can do about this..

**Comment by totaam** [comment]
> Actually the problem is the same with Wayland deactivated.

There's not much we can do, really.
We call [Gtk.Window.set_icon](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Window.html#Gtk.Window.set_icon) which states: _On others, the icon is not used at all, so your mileage may vary_

This used to work just fine for years, but now desktop environment are breaking things.
