### ISSUE TITLE
macOS merge all windows undone after switching between desktops

### ISSUE THREAD

**Issue by aayushm10001** [Xpra-org/xpra#3615]
When multiple xpra windows are opened in macOS and merge all windows is selected, switching between multiple desktops causes the windows to un-merge.

In the terminal used to launch xpra client, the following message is seen:
2022-09-09 20:13:03,240 system is suspending
2022-09-09 20:13:06,945 system resumed, was suspended for 3

1. Launch xpra client on macOS
2. Open multiple forwarded windows
3. With xpra open, select menu bar -> windows -> merge all windows
4. Switch to a different macOS desktop
5. Switch back to macOS desktop with xpra window open

**System Information (please complete the following information):**
 - Server OS: Debian GNU/Linux 12
 - Client OS: macOS Monterey v12.5.1
 - Xpra Server Version 4.3.3-r0
 - Xpra Client Version 3.1

Thanks!

**Comment by totaam** [comment]
Please try again with a supported version, the 3.x branches are being EOLed.
I have no idea what merging windows does and how it interacts with GTK. Perhaps the bug belongs there instead.

**Comment by totaam** [comment]
Is the "merge" the same as the "grouping as tabs" mentioned in #3723?

**Comment by totaam** [comment]
Not heard back.
