### ISSUE TITLE
Installing shadow server startup as Window service -- how? where to learn how?

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3617]
I couldn't decide whether to class this as a bug or not.

I need `xpra shadow` to run as a service as the machine boots. Alternatively, I'd be happy if I could access the machine via cygwin sshd, already running as a service, and start `xpra shadow` that way. In essence, any means of auto- or remote-starting the shadow server without being physically in front of the machine, so that I can get control of the console after reboot.

I web-searched for such things, and I seem to have gotten close in finding #1527, but as God is my witness, I cannot tell what the final result of all that is. The bug here, if one can call it that, is that there is no documentation which says, "...and _**this**_ is how you set up the shadow server as a Windows service: step 1, step 2, step 3." I see a lot of references to `sc` (that's a new one on me, thanx) but ultimately the several things I've tried have all gone nowhere.

**To Reproduce**
1. Try to find documentation on setting up shadow server Windows service.

**System Information (please complete the following information):**
 - Latest all around: 4.4._yesterday_ on Fedora, and on WIndows, the current [main web page reference] installer .exe, 4.3.whatever.

**Comment by totaam** [comment]
> but as God is my witness, I cannot tell what the final result of all that is

Haha! Same here.
As far as I am aware, this is not possible as it is.
If someone finds the correct and accurate documentation or code to implement this feature, I will gladly implement it.
