### ISSUE TITLE
The xpra client can send a wrong username to the server causing a false log entry in ssh connections

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3627]
**Describe the bug**
The xpra client is able to send a different username to the xpra server than using for login with SSH. The main issue is, that the xpra server will log the login to be from the wrong user.

**To Reproduce**
Suppose you're `bob`, having an account `bob@serverhostname` to access an xpra server and want the log to show that `alice` logged in.

1. Start the server on `serverhostname` with: `xpra start :10`
2. Create a local user `alice` (Or find where the client determines the local hostname and patch the client)
3. Attach to the server from local user `alice` with `xpra attach --ssh=/usr/bin/ssh ssh:serverhostname` (As local user `alice`)
4. Have a `.ssh/config` with the content

```
Host serverhostname
User bob
```

And the credentials to connect to `bob@serverhostname`.

Now the xpra client sees the connection string `ssh:serverhostname` and guesses the username and transmits `alice` to the server, while the `/usr/bin/ssh` binary reads the file `.ssh/config` and logs in as `bob` accordingly.

The log then contains 

```
New unix-domain connection received (...) as 'alice' even when the remote host does not have a user alice.
```

Note that the difference in local and remote usernames is how I found the bug. The real problem is, that the server trusts the client to transmit the username it claims to have used to login instead of reading the effective remote username from the ssh shell after login.

**System Information (please complete the following information):**
 - Server OS: Debian stable
 - Client OS: Debian testing
 - Xpra Server Version v4.3.4-r0
 - Xpra Client Version v4.4-r31841

**Additional context**
- The user `alice` does not even have to exist on the server. The client seems to just send a username (which it seems to guess from using the local one if you use `ssh:serverhostname`) and the server logs it.
- You can send the correct username by connecting to `ssh:bob@serverhostname`. The probably both overrides the username send by `/usr/bin/ssh` (with the same as in the config) and prevents xpra from guessing the remote username by using the local username.
- Because the username in `ssh:alice@serverhostname` is used for ssh login, you cannot use this connection string to send the wrong username. You possibly could by using a `ssh` that ignores the `user@` part.

**Impact**
Server:
Probably mostly a wrong log entry making it harder to audit unauthorized access.

I do not know much about xpra's other authentication methods and if they can be used in addition to a ssh login, but probably sending a false username won't allow any further authentication without knowing the credentials for the user.

Client:
Even when trying to prevent the client from sending data about the local maschine (see #3582), the client can send surprisingly the local username when logging in with a different remote username. This way the server logs data about the client that it should not have.

**Comment by totaam** [comment]
Sorry, but unless I get a very well tested PR with unit tests and very thorough platform testing, this ticket isn't going to go anywhere.

The username is used for authentication and is not trusted. The ability of the client to specify whichever username it wants is a feature, not a bug.
