### ISSUE TITLE
Deprecated usage of old channel layout

### ISSUE THREAD

**Issue by Avimitin** [Xpra-org/xpra#3629]
**Describe the bug**

Xpra default let gcc treat all warning as errors. However ffmpeg has deprecated the `channels` field in `AvCodecContext`: https://github.com/FFmpeg/FFmpeg/commit/548aeb93834b8425c86d1ce60fddc1d41805724d. So when we compile xpra, the compile process will fail for this line https://github.com/Xpra-org/xpra/blob/master/xpra/codecs/enc_ffmpeg/encoder.pyx#L1529.

**To Reproduce**

`python setup.py build`

**System Information (please complete the following information):**
 - Build host OS: Arch Linux 5.19.2
- ffmpeg version: 5.1.2

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by Avimitin** [comment]
Seems fixed in https://github.com/Xpra-org/xpra/commit/3fc230dbdd78f564a01774c4b355cee4ad08cdb6. Closed.

**Comment by totaam** [comment]
FWIW: when this happens, use `./setup.py build --without-strict`
