### ISSUE TITLE
windows shadow server goes *blind*

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3632]
Seriously, I just can't seem to let it go.

r32011 on Windows
r32009 on F35

`xpra shadow ssh://winhost`
Play around a while. Do random things. Everything works.
Get distracted. Leave the room. Go do something else for a little while.
Come back. Move mouse. Open window. Move window.
xpra client screen does not change.
With the physical machine behind my shoulder, I can turn around and see that I'm having the expected effects on it: Mouse and keyboard are live, machine responds to them.
But the xpra client window on F35 machine is showing no updates: It's gone blind, not deaf.
Windows machine hears, but I cannot see.

Fortunately, simply closing and re-connecting makes it all sweetness and light again.

I *think* it's related to simple idle time, how long I was away before it went blind. I've done it several times, and it's not a long time, maybe 10min or so.

What `-d` switch would be useful to learn what's happening?

**Comment by totaam** [comment]
Damn. `-d win32` might be too verbose but it is likely to include the event.
I think that we can't capture the screen when the screensaver is on, perhaps it gets wedged when that happens.

**Comment by totaam** [comment]
Then it must be some kind of leak.. oh joy.
Maybe it runs out of GDI resources and can no longer capture the screen.
If that is the case, the server log should have some errors in it.

**Comment by karlkleinpaste** [comment]
Brief update: It's not screensaver, and it's not idle time. It can sometimes go blind right in the middle of use.
I'll get to proper `-d win32` logging soon.
Also, I have another glitch that was discovered only with Windows→Windows connection, but I'll file it as a separate bug.

**Comment by karlkleinpaste** [comment]
[xpra.log](https://github.com/Xpra-org/xpra/files/9693394/xpra.log)
5.5min log of `xpra shadow ssh://winhost -d win32`
Sorry to upload the whole thing, but lacking any real info as to cause, maybe blindness is an effect that began some time before it was visible. Blindness occurred 10-15sec before the end of this log. As soon as I noticed, I moved to close the session, taking a few seconds to mouse over to the go-away X in the window corner.
I wasn't doing anything special. I had TM open, and was mousing over Performance pane selections.

**Comment by totaam** [comment]
There's nothing left in that log once I remove the network read / write bits with `egrep -v "pipe_write|pipe_read|WriteFile|ReadFile|WaitForSingleObject" ./xpra.log`
Can you launch the shadow server in advance rather than using the all-in-one ssh command?
(I would have expected more messages)

**Comment by karlkleinpaste** [comment]
I upgraded to r32075, just to be current. And now the blindness does not occur at all. I've experimented with it in connections lasting anywhere from 2 minutes to half an hour, and I haven't seen the blindness again.

What might have changed between r32011 and r32075 that would have had an effect here?

In any event, since the bug is no longer appearing, closing this. If I find it happening again, I'll re-open.

**Comment by totaam** [comment]
There were virtually no changes between those two revisions, at least no changes that would have any impact on MS Windows shadow servers.
I guess that it is possible, though unlikely, that a system update (GTK or other) would have a more profound impact.
