### ISSUE TITLE
Windows Defender reports xpra as Win32/Spursint.F!cl trojan and blocks installation

### ISSUE THREAD

**Issue by gdevenyi** [Xpra-org/xpra#3639]
**Describe the bug**
Windows defender blocks the installer and reports it as Win32/Spursint.F!cl

**To Reproduce**
1. download https://xpra.org/dists/windows/Xpra-x86_64_Setup.exe
2. attempt to run

**System Information (please complete the following information):**
 - Server OS: NA
 - Client OS: Windows 11
 - Xpra Server Version NA
 - Xpra Client Version latest

**Comment by totaam** [comment]
This happens fairly regularly: #2781, #2088, #3056

This is usually solved by updating the anti-virus database.
