### ISSUE TITLE
Xpra v4.4-r0 is hang on Windows 10 WSL2

### ISSUE THREAD

**Issue by firejox** [Xpra-org/xpra#3649]
**Describe the bug**
Xpra v4.4-r0 hangs on Windows 10 WSL2 but Xpra v4.3.4-r0 does not.

**To Reproduce**

WSL side :

```
xpra start --bind-tcp=0.0.0.0:10000 --start-child=xterm --exit-with-children-yes --daemon=no --pulseaudio=no --notification=no --bell=no --speaker=diabled --microphone=disabled :10
```
Windows side:

```
"C:\Program Files\Xpra\Xpra_cmd.exe" attach "tcp://0.0.0.0:10000"
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04 Windows 10 WSL2
 - Client OS: Windows 10 Home 21H2
 - Xpra Server Version v4.4-r0
 - Xpra Client Version v4.4-r0

**Additional context**
The client side produce this error.
```
2022-10-13 14:36:40,762 Xpra GTK3 client version 4.4-r0 64-bit
2022-10-13 14:36:40,774  running on Microsoft Windows 10
2022-10-13 14:36:42,900 GStreamer loaded
2022-10-13 14:36:43,065 created named pipe 'Xpra\67544'
2022-10-13 14:36:43,156 keyboard layout 'United States - English' : 'us' (0x409)
failed to connect to 0.0.0.0:10000, retrying for 20 seconds
Warning: failed to connect:
 failed to connect to tcp socket 0.0.0.0:10000
```

The server side produce 
```
Warning: XDG_RUNTIME_DIR is not defined
 and '/run/user/1000' does not exist
 using '/tmp'
2022-10-13 14:35:18,131 created tcp socket '0.0.0.0:10000'
2022-10-13 14:35:18,178 no uinput module (not usually needed)
2022-10-13 14:35:18,231 pointer device emulation using XTest
2022-10-13 14:35:18,271 serving html content from '/usr/share/xpra/www'
2022-10-13 14:35:18,271 wrote pid 1581 to '/tmp/xpra/10/server.pid'
2022-10-13 14:35:18,295 Warning: failed to create socket directory '/run/user/1000/xpra'
2022-10-13 14:35:18,295  [Errno 13] Permission denied: '/run/user/1000'
2022-10-13 14:35:18,296 Warning: failed to create socket directory '/run/xpra'
2022-10-13 14:35:18,296  [Errno 13] Permission denied: '/run/xpra'
2022-10-13 14:35:18,296 Warning: socket directory '/tmp/xpra/10'
2022-10-13 14:35:18,296  expected permissions 700 but found 750
2022-10-13 14:35:18,296 Warning: some of the sockets are in an unknown state:
2022-10-13 14:35:18,296  /home/firejox/.xpra/DESKTOP-2BCQGK7-10
2022-10-13 14:35:18,297  /tmp/xpra/10/socket
2022-10-13 14:35:18,297  please wait as we allow the socket probing to timeout
2022-10-13 14:35:24,308 Warning: cannot create socket '/run/user/1000/xpra/DESKTOP-2BCQGK7-10':
2022-10-13 14:35:24,308  [Errno 2] No such file or directory
2022-10-13 14:35:24,308  ($XDG_RUNTIME_DIR has not been created?)
2022-10-13 14:35:24,308 cannot create group socket '/run/xpra/DESKTOP-2BCQGK7-10'
2022-10-13 14:35:24,309  [Errno 2] No such file or directory
2022-10-13 14:35:24,309  /run/xpra does not exist
2022-10-13 14:35:24,310 created unix domain socket '/home/firejox/.xpra/DESKTOP-2BCQGK7-10'
2022-10-13 14:35:24,310 created unix domain socket '/tmp/xpra/10/socket'
2022-10-13 14:35:24,311 xvfb pid=1464
2022-10-13 14:35:24,443 watching for applications menu changes in:
2022-10-13 14:35:24,443  '/usr/share/applications'
2022-10-13 14:35:24,444  '/var/lib/snapd/desktop/applications'
2022-10-13 14:35:24,470 Warning: webcam forwarding is disabled
2022-10-13 14:35:24,470  the virtual video directory '/sys/devices/virtual/video4linux' was not found
2022-10-13 14:35:24,470  make sure that the 'v4l2loopback' kernel module is installed and loaded
2022-10-13 14:35:24,470  or use the 'webcam=no' option
2022-10-13 14:35:24,470 found 0 virtual video devices for webcam forwarding
2022-10-13 14:35:24,490 Warning: lpinfo command failed and returned 1
2022-10-13 14:35:24,491  command used: '/usr/sbin/lpinfo --make-and-model Generic PDF Printer -m'
2022-10-13 14:35:24,497 Warning: lpinfo command failed and returned 1
2022-10-13 14:35:24,500  command used: '/usr/sbin/lpinfo --make-and-model Generic PostScript Printer -m'
2022-10-13 14:35:24,506 printer forwarding enabled using pdf
2022-10-13 14:35:24,509 started command `xterm` with pid 1611
```

If I downgrade the version of Xpra of WSL2, the issue will be resolve.

**Comment by totaam** [comment]
> `"C:\Program Files\Xpra\Xpra_cmd.exe" attach "tcp://0.0.0.0:10000"`

This is not a valid command line, `0.0.0.0` is not a valid address.
Are you sure that you are using the correct addresses?

**Comment by firejox** [comment]
> > `"C:\Program Files\Xpra\Xpra_cmd.exe" attach "tcp://0.0.0.0:10000"`
> 
> This is not a valid command line, `0.0.0.0` is not a valid address. Are you sure that you are using the correct addresses?

I have tried several  addresses I knew but still get the same result.

> 
> Can you run `xpra info` from the WSL2 side?
> Can you run `xpra info tcp://127.0.0.1:10000/` from the WSL2 side?

The `xpra info` on WSL2 side shows
```
Warning: XDG_RUNTIME_DIR is not defined
 and '/run/user/1000' does not exist
 using '/tmp'
xpra initialization error:
 cannot find any live servers to connect to
```

And the `xpra info tcp://127.0.0.1:10000/` shows
```
Warning: XDG_RUNTIME_DIR is not defined
 and '/run/user/1000' does not exist
 using '/tmp'
failed to connect to 127.0.0.1:10000, retrying for 20 seconds
Warning: failed to connect:
 failed to connect to tcp socket 127.0.0.1:10000
```

**Comment by totaam** [comment]
> `failed to connect to tcp socket 127.0.0.1:10000`

Then maybe the xpra server is not listening on the socket you specified with `bind-tcp`.
What about: `lsof -i -n -P`

**Comment by firejox** [comment]
> > `failed to connect to tcp socket 127.0.0.1:10000`
> 
> Then maybe the xpra server is not listening on the socket you specified with `bind-tcp`. What about: `lsof -i -n -P`

`lsof -i -n -P` shows
```
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
/usr/bin/ 3081 firejox    8u  IPv4 110539      0t0  UDP *:5353
/usr/bin/ 3081 firejox    9u  IPv4 110541      0t0  UDP *:5353
```

**Comment by totaam** [comment]
> `lsof -i -n -P` shows...

Then the xpra server is not listening on the tcp socket.
Are you sure that it is still running?

**Comment by firejox** [comment]
Sure, it is still running.

![image](https://user-images.githubusercontent.com/6823999/195537446-7c643b13-9592-484b-847e-384488cbffdd.png)

**Comment by totaam** [comment]
> `created unix domain socket '/tmp/xpra/10/socket'`

Then `xpra info socket:///tmp/xpra/10/socket` should work.
If it doesn't then there's something fundamentally wrong with your server OS.

**Comment by totaam** [comment]
The UI thread is busy handling a clipboard ownership change, another one is in the mDNS publisher, another one loading desktop menus.
Another very suspicious backtrace is the one that ends up loading `numpy` and `pycuda`. If that's the problematic one, simply removing `pycuda` might "fix" it.

Can you try running the server with `--no-clipboard --no-mdns --no-printing --start-new-commands=no --video-encoders=none --encodings=rgb`?

**Comment by firejox** [comment]
Ok, now I can see the xterm. Thank you :relaxed:
I start server with 
```
 xpra start --bind-tcp=0.0.0.0:14500 --start-child=xterm --exit-with-children=yes --daemon=no --pulseaudio=no --notifications=no --bell=no --speaker=disabled --microphone=disabled --no-clipboard --no-mdns --no-printing --start-new-commands=no --video-encoders=none --encodings=rgb :10 
``` 
and it works.

Then I remove the `pycuda` and run with
```
 xpra start --bind-tcp=0.0.0.0:14500 --start-child=xterm --exit-with-children=yes --daemon=no --pulseaudio=no --notifications=no --bell=no --speaker=disabled --microphone=disabled --no-clipboard --no-mdns --no-printing --start-new-commands=no :10
```
```
xpra start --bind-tcp=0.0.0.0:14500 --start-child=xterm --exit-with-children=yes --daemon=no --pulseaudio=no --notifications=no --bell=no --speaker=disabled --microphone=disabled :10
```
They work, too.

**Comment by totaam** [comment]
If the problem comes from pycuda, then you should be able to reproduce the hang with just:
```
python3 -c "from pycuda import driver;driver.init()"
```

**Comment by firejox** [comment]
Got it. I have now removed pycuda because I didn't feel any responsive issue in my use without nv codes. Though xpra will complain about the import error about pycuda, I think it's fine and the cuda issue need Microsoft to resolve.  Finally, thank you for the great tool and I will close the issue.

**Comment by totaam** [comment]
@firejox did you try the command from the comment above (https://github.com/Xpra-org/xpra/issues/3649#issuecomment-1278547746) with `pycuda` installed?
This would confirm that the bug is with `pycuda` on WSL2.

Do you have an NVidia GPU in this system?

The commit above will now block the import of `pycuda` on WSL, please confirm if that is the right thing to do.

**Comment by firejox** [comment]
> @firejox did you try the command from the comment above ([#3649 (comment)](https://github.com/Xpra-org/xpra/issues/3649#issuecomment-1278547746)) with `pycuda` installed? This would confirm that the bug is with `pycuda` on WSL2.

Yes, I am sure the bug coming from the `pycuda`. After upgrading `pycuda` to the newest version, it will not hang. Xpra is still unable to use `nvenc`.

> Do you have an NVidia GPU in this system?

Yes, it seem to support partial features in my WSL2 system.

> The commit above will now block the import of `pycuda` on WSL, please confirm if that is the right thing to do.
 
AFAIK, there are many features enabled on Windows 11 compared to Windows 10, the nv codec support is inconsistent in WSL2. Hence, I think block the import of `pycuda` will be better.

**Comment by totaam** [comment]
> Yes, I am sure the bug coming from the `pycuda`

As per the comments above, please post the output of
```
python3 -c "from pycuda import driver;driver.init()"
```
Does this also hang?

> After upgrading pycuda to the newest version, it will not hang

How did you update it?
You mean that the `pycuda` package in Ubuntu is what's causing problems?
Was it `pycuda-2018.1.1-4build2` ?

> I think block the import of pycuda will be better.

Maybe other distros don't have this issue and don't ship completely out of date versions of `pycuda`, they should not be penalized.

**Comment by firejox** [comment]
> As per the comments above, please post the output of
> ```
> python3 -c "from pycuda import driver;driver.init()"
> ```
> 
> Does this also hang?

It is normal exit now. Both old and new package have no output and then exit for `python3 -c "from pycuda import driver;driver.init()"`. The old package would cause xpra hang, but the new package would not.  

> How did you update it? You mean that the `pycuda` package in Ubuntu is what's causing problems? Was it `pycuda-2018.1.1-4build2` ?

I Installed newest package to pycuda-2022.1 via pip instead of apt package.
Yes, `pycuda-2018.1.1-4build2` cause the problem.

> > I think block the import of pycuda will be better.
> 
> Maybe other distros don't have this issue and don't ship completely out of date versions of `pycuda`, they should not be penalized.

Sorry, that' not what I meant. I think it is general compatibility problem. Maybe old `pycuda` work well in old system with old cuda lib and old driver,  but it may not work well in new system. In WSL, or in other container system (i.e. docker), the host system could affect the container system then cause the compatibility problem. If you update the host driver, then it is possible to influence container app.

**Comment by totaam** [comment]
> Both old and new package have no output and then exit for..

That's odd because this command is the same that xpra runs:
https://github.com/Xpra-org/xpra/blob/4da5b3bfc99182c2bfe83cc56df073c4db564283/xpra/codecs/nvidia/cuda_context.py#L28

> If you update the host driver, then it is possible to influence container app.

I would expect the CUDA interface to be more robust than that, no matter what host version is installed.
Perhaps it is timing out trying to enumerate the GPU devices.

Do you have the `xpra start -d cuda` output for old and / or new pycuda versions?

**Comment by firejox** [comment]
> Do you have the `xpra start -d cuda` output for old and / or new pycuda versions?

Sure, here it is.

old version: [old.txt](https://github.com/Xpra-org/xpra/files/9800026/old.txt)
new version: [new.txt](https://github.com/Xpra-org/xpra/files/9800027/new.txt)
