### ISSUE TITLE
split codecs into a separate package

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3651]
When using xpra locally on the same (virtual) host using `mmap` or `vsock`, none of the codecs should be used and they end up consuming memory, disk space and sometimes causing bugs too (ie WSL2 #3649).
Somewhat related to #3592

**Comment by totaam** [comment]
Already done: See also #2344
* make `python3-pillow` sort of optional: 268b700a480590bc7cf1aa1a0a60762ba52a9988 - c0f834608d236f01dcb8dd60255f18fd60a0aa78 - f5426a00d11a9b4a62fb5023800d7621ed5bac11, still used in some places, but it should now be possible to run the client and server without having it installed: da8b805d86747ef09dff3f8c6f2ee54a6493bc98, 48e4dd2ab2444d80c4afc626114e184f45d99041, 03c4059da46582d1974d7dab14a1eaca1bfee7ed. Avoid scary warnings: ca5b4d89b8a87405b49a1ef73e986e251018c76f
* re-arrange `codecs` module layout: fa3e6ed7a02c4a5e8aef95102431c423df25c689
* split into `xpra-codecs` package: fd342985d940224571c62b8024ef84fcc09e2ca2* move nvidia bits together: 0f55524dcc786bfae1ac3e369f5859e56a544501 and into a separate RPM package: b2cbd4ca08be5f1ca7b6563eedcaa409f0994507

**Comment by totaam** [comment]
Here is the new list of RPM names generated (excluding `debuginfo` and `debugsource packages):
```
xpra-5.0-10.fc36.x86_64.rpm
xpra-audio-5.0-10.fc36.x86_64.rpm
xpra-client-5.0-10.fc36.x86_64.rpm
xpra-codecs-5.0-10.fc36.x86_64.rpm
xpra-codecs-nvidia-5.0-10.fc36.x86_64.rpm
xpra-common-5.0-10.fc36.x86_64.rpm
xpra-server-5.0-10.fc36.x86_64.rpm
```
And for DEBs:
```
xpra_5.0-1_amd64.deb
xpra-audio_5.0-1_amd64.deb
xpra-codecs_5.0-1_amd64.deb
xpra-codecs-nvidia_5.0-1_amd64.deb
```

**Comment by totaam** [comment]
One downside of this change is that following the Debian build instructions at https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md now fails unless you have cuda installed whereas this used to produce a build without the codecs.
No easy way around this AFAIK.

See also https://github.com/Xpra-org/repo-build-scripts/issues/7

**Comment by iDmple** [comment]
> One downside of this change is that following the Debian build instructions at https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md now fails unless you have cuda installed whereas this used to produce a build without the codecs. No easy way around this AFAIK.

After some investigation, the only problem is this line, because without what's needed for CUDA, it's missing:
https://github.com/Xpra-org/xpra/blob/afcee5be3e0215f03ed17c75cf83a527d768ddfc/packaging/debian/xpra/xpra-codecs-nvidia.files#L1

If it's commented out, the build is a success.

Would it be possible to have an empty file always there for if CUDA isn't installed?

**Comment by totaam** [comment]
We now have a `xpra-codecs-extras` for the `ffmpeg` codecs, and the client has been split into `xpra-client` and `xpra-client-gtk3`: #3797
