### ISSUE TITLE
Windows Defender reporting virus in Xpra-x86_64_Setup.exe

### ISSUE THREAD

**Issue by TristanJamesBall** [Xpra-org/xpra#3655]
Just a heads up that the file https://xpra.org/dists/windows/Xpra-x86_64_Setup.exe was blocked as a trojan

It's listing it as "Trojan:Win32/Spursint.F!cl"

![VirusReport](https://user-images.githubusercontent.com/49751776/195995126-94783734-46a8-45bd-95bc-09ce98d99e7f.png)

**Comment by totaam** [comment]
This happens every few days and is a false positive.
Same as #3639 and many many other tickets.
