### ISSUE TITLE
Documentation still references trac, and no mention of --splash-no seen

### ISSUE THREAD

**Issue by BillyCroan** [Xpra-org/xpra#3668]
The manpage at https://github.com/Xpra-org/xpra/blob/master/fs/share/man/man1/xpra.1 contains two errors:
It does not mention --splash=no as an option to xpra to supress the splash screen
It references trac:
> REPORTING BUGS
> Send any questions or bugs reports to https://xpra.org/trac/
Do you encourage patches on things like this via git?

**Comment by BillyCroan** [comment]
[#3669](https://github.com/Xpra-org/xpra/pull/3669)

**Comment by totaam** [comment]
The commit updates the outdated trac link, the man page issue is tracked in #3669.
