### ISSUE TITLE
Installation of XPRA on CentOS 8 systems fails (`libyuv` is not signed)

### ISSUE THREAD

**Issue by olifre** [Xpra-org/xpra#3674]
**Describe the bug**
Package installation fails, since `libyuv` is regarded as "not signed". 

**To Reproduce**
```
wget -O /etc/yum.repos.d/xpra.repo https://xpra.org/repos/CentOS/xpra.repo
yum -y install xpra
...
Package libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
```

**System Information (please complete the following information):**
 - OS: CentOS Stream release 8

**Additional context**
The issue started to appear a few hours ago.

**Comment by totaam** [comment]
Very likely to have been caused by https://github.com/Xpra-org/repo-build-scripts/issues/5#issuecomment-1291827723

That's odd because:
```shell
# rpm -qpi dists/almalinux/8/x86_64/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm  | grep Signature
warning: dists/almalinux/8/x86_64/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID f18ad6bb: NOKEY
Signature   : DSA/SHA1, Sun Oct  2 10:06:17 2022, Key ID 18adb31cf18ad6bb
```
I have force deleted the signature on this RPM and then re-signed it, the package file ended up being identical.
So the signature must be correct?
What is going on here?

Can you try clearing your cache?

**Comment by olifre** [comment]
That's very strange indeed... Sadly, clearing the cache (`yum clean all`) and also removing the downloaded packages did not change anything. 

I will investigate further after a good night's sleep by checking checksums of the downloaded packages.

**Comment by olifre** [comment]
Here's what I find:
```
$ md5sum /var/cache/dnf/xpra-9be4230523696207/packages/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm
4c500f9890fa04f2efdd66c6a30687c6  /var/cache/dnf/xpra-9be4230523696207/packages/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm

$ rpm -qpi /var/cache/dnf/xpra-9be4230523696207/packages/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm | grep Signature
Signature   : (none)

$ wget https://xpra.org/dists/CentOS/8/x86_64/libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm
$ md5sum libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm 
4c500f9890fa04f2efdd66c6a30687c6  libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm
```
Am I correct that the changed layout to adapt to the increased fragmentation of RedHat and its rebuilds is right now only "live" for beta releases, and not yet for https://xpra.org/repos/ ?

Checking https://xpra.org/repos/CentOS/xpra.repo still seems to redirect to `CentOS` exclusively, so when installing using the repo file, I am likely using `dists/CentOS/8`.

**Comment by totaam** [comment]
My bad, you're using the `CentOS` repo, not the `RedHat` one... I'll update the download documentation for that.

`CentOS/8` is now pointing to `CentOS/stream8`.

That repo symlink change happened around the same time and led me astray, I don't think that was the cause.
The missing signature is exactly where you first said it was and I have now force-added it.

**Comment by olifre** [comment]
@totaam Many thanks! No worries, with all this RedHat fragmentation, it's easy to end up checking the wrong repository. 

Sadly, It's not fully ok yet, now the metadata is out of sync:
```
[MIRROR] libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 849f58e0e3126a9fc46be200cdda6d28c760225ac80a6ae5ed16a41cb77c0169(sha256)  Expected: 59103b7d501a562fdc200e2ce883ef95efb56c7f9b0002b2667f6dd61d40309d(sha256) 
...
[FAILED] libyuv-0-0.1832.20220629git6900494.1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                                                                                                      
```

**Comment by totaam** [comment]
> now the metadata is out of sync:

Sorry, that was really sloppy on my part.
