### ISSUE TITLE
Attach to UNIX socket.

### ISSUE THREAD

**Issue by lockywolf** [Xpra-org/xpra#3686]
**Is your feature request related to a problem? Please describe.**
The documentation says how a server can create a listening socket of various types, including tcp, and unix sockets, but does not tell how a client can `attach` to a unix socket. 

**Describe the solution you'd like**

Implement a "unix://" or a "path://" socket to use with `xpra attach`.
The way I am doing it is `ssh -oLocalForward='/tmp/sock.sock /tmp/sock.sock'`. I do not want to use a tcp socket in order to not to occupy ports when UNIX sockets can do the job, because I don't want to fix socket numbers used for different machines, and because I am using `autossh`  for persistent ssh connections.

Or maybe the option is already there, I just haven't managed to find it?

**Describe alternatives you've considered**

1. Fixed tcp port numbers for different machines. Works, but is a little crutchy.
2. Using tmux as ` xpra attach ssh://address --start=tmux`, but this does not work for some reason. There is no `tmux` process running.

**Comment by totaam** [comment]
This is already possible:
```
xpra attach ///some/path/to/socket
```
or even:
```
xpra attach socket:///some/path/to/socket
```
