### ISSUE TITLE
xpra seamless mode is supported in windows?

### ISSUE THREAD

**Issue by chaklasiyanikunj** [Xpra-org/xpra#3689]
I tried to achieve this using the below [documentation](https://github.com/Xpra-org/xpra/tree/master/docs/Usage).

I downloaded Xpra using [this](http://xpra.org/dists/windows/Xpra-x86_64_Setup.exe) link.
On both (Host and Client Sides) I used Windows 10.

**Host Server Using the below command:**
xpra start :100 --start=xterm
xpra start --start=xterm --bind-tcp=192.168.1.101:14500  //I also tried this command

**Using both commands I got this error.**

"Xpra Installation Error : seamless is not supported on this platform"

![Xpra Installation](https://user-images.githubusercontent.com/39697799/202370654-fbcd7b93-8a45-4e02-96ae-aa38e53d8c5a.PNG)

**Client Using the below command:**
xpra attach ssh://Admin@192.168.1.101/100

**Is seamless mode supported for Windows?**
Anyone any idea about this? or share any good documentation for windows.
I found all documentation available for Linux only.  But not see any single documentation in windows.

**Comment by totaam** [comment]
It is not supported on MS Windows and MacOS, this has been added to the documentation: 3d2a77dc0b9805ea2d059ada116f810f674e5dd3

**Comment by hadogenes** [comment]
@totaam how about this method?
https://forum.level1techs.com/t/how-to-seamlessly-run-windows-10-apps-in-a-vm-in-linux/170417

**Comment by totaam** [comment]
@hadogenes I've tried repeatedly over the last ~10 years and never got it working properly / reliably.
