### ISSUE TITLE
In pixman_set_extents

### ISSUE THREAD

**Issue by Simba98** [Xpra-org/xpra#3691]
**Describe the bug**
The log prints 
*** BUG ***
In pixman_set_extents: The expression region->extents.x1 < region->extents.x2 was false
Set a breakpoint on '_pixman_log_error' to debug

**To Reproduce**
1. Server `xpra start :123 --bind-tcp=127.0.0.1:12345,auth=file:filename=[password] --bind=/tmp/.xpra --start=gnome-terminal`
2. client `xpra attach tcp:localhost:12345 --password-file=~/.ssh/xpra --speaker=no --dpi=384 --desktop-scaling=2`
3. specific action to trigger the bug: NA

**System Information (please complete the following information):**
 - Server OS: `CentOS Kernel 3.10.0-1160.76.1.el7.x86_64`
 - Client OS: `Windows 10`
 - Xpra Server Version `xpra v4.4.2-r0M`
 - Xpra Client Version `xpra v4.4.2-r0`

**Additional context**
Running GNOME

**Comment by totaam** [comment]
> `CentOS Kernel 3.10.0-1160.76.1.el7.x86_64`

CentOS 7.x is not officially supported in versions newer than 3.x
You must have built from source? How?
Since no supported distribution is seeing this problem, the cause is likely in your environment and / or library versions. This issue will not be worked on. Sorry.

**Comment by Simba98** [comment]
> > `CentOS Kernel 3.10.0-1160.76.1.el7.x86_64`
> 
> CentOS 7.x is not officially supported in versions newer than 3.x You must have built from source? How? Since no supported distribution is seeing this problem, the cause is likely in your environment and / or library versions. This issue will not be worked on. Sorry.

Really? I installed it via Miniconda. Sorry for missing it.
