### ISSUE TITLE
Session locking not working as expected

### ISSUE THREAD

**Issue by calderonth** [Xpra-org/xpra#3694]
**Describe the bug**
I cannot get the session lock to behave as documented.

**To Reproduce**
1. `xpra start :100 --lock=yes --sharing=no --speaker=no --microphone=no --printing=no --webcam=no --mdns=no --start=xterm`
2. `xpra attach --lock=yes --sharing=no --speaker=no --microphone=no --printing=no --ssh=ssh ssh:remote-host:100`
3. start another client in the shell with identical parameter, session gets taken over

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04 LTS
 - Client OS: Debian 11
 - Xpra Server Version `4.4.2-r0-1`
 - Xpra Client Version `4.4.2-r0-1`

**Additional context**
It is my understanding from the documentation that using `--lock=yes` should prevent the session from being taken over by a subsequent connection.
Note that `--sharing=no` is also set on both server/client.

**Comment by totaam** [comment]
This works for me.
My guess is that you are connecting your second client from the exact same machine and therefore the server sees this as the same request and allows it. (useful for when your client dies without closing the connection for example).

You can simulate having a different client unique ID with:
```shell
XPRA_USER_UUID=whatever xpra attach ...
```

**Comment by calderonth** [comment]
Haaaa yes I am connecting from the same client indeed.
Thanks for explaining this.
Does that mean that the UUID generation is deterministic on a given machine?

**Comment by totaam** [comment]
https://github.com/Xpra-org/xpra/blob/d8bfc21ed29fadd9351d2272f4a9c4baef74440b/xpra/os_util.py#L276-295
