### ISSUE TITLE
Key based auth with paramiko on Windows not working

### ISSUE THREAD

**Issue by aneesh2312** [Xpra-org/xpra#3695]
**Describe the bug**
I am using paramiko client for SSH, along with key based authentication on Windows. I am using the XPRA_SSH_DEFAULT_KEYFILES environment variable. Xpra is not parsing the environment variable correctly as it uses ":" as the separator by default, which is not the case for Windows.

**To Reproduce**
1. xpra start on server side.
2. Set XPRA_SSH_DEFAULT_KEYFILES environment variable on client side.
3. xpra_cmd attach ssh:ubuntu@<host> --ssh=paramiko:auth=key

**System Information (please complete the following information):**
 - Server OS: Linux (Ubuntu)
 - Client OS: Windows 10
 - Xpra Server Version: 4.4.3
 - Xpra Client Version: 4.4.3

**Comment by totaam** [comment]
I don't want to risk breaking another use case, so I only merged the part the uses `pathsep`.
As per my previous comment, trying to load from `.ssh` should be (almost) free.
