### ISSUE TITLE
Focus problems

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3699]
**Describe the bug**
Since quite some time, xpra has problems with the input focus. When a Firefox window is unminimized (but not focussed and maybe not even visible) all typed text ends up in Firefox until the window is minimized. It seems to be mostly Firefox, which steals the input focus.

A bit shorter, there are also problems with maximized windows. When two windows are maximized on the same screen, trying to do something in the front window flickers the window behind it into the front. Strangely, clicking the title bar seems to bring the background window to the front, but not always redraws the full window. Trying to work in the window again is only possible when the other window is minimized or at least no longer maximized.

I didn't report before, because I have a hard time to really find what may be causing it and don't know what to describe except for the description above, but maybe you know some debugging steps to find out what might be causing it. It also is a regression from older versions.

**System Information (please complete the following information):**
 - Server OS: Debian stable
 - Client OS: Debian testing
 - Xpra Server Version: 4.4.3-r0-1
 - Xpra Client Version: 5.0-r32356-1 

**Additional context**
I see similar issues with a client system with Debian stable and the latest stable client versions (e.g. 4.4.3 right now), but as it has another desktop setup I am not sure if all effects are the same.

**Comment by totaam** [comment]
Try running both the client and server with `-d focus`.

**Comment by allo-** [comment]
Just adding here as the issue is aging and I haven't provided feedback yet: I still have the problems, but I currently find debugging complicated (I am not sure what to look for in the debug output) and it is hard to reproduce the same effects or even get a consistent description of the problem(s) as it may be a combination of different issues.

xpra is installed from your (testing) repos and I am using KDE Plasma with KWin (X11) and two monitors and focus follows the mouse (but does not raise windows).

I am just dumping some things about the problem, so I know what to add later or to test if it is resolved. I will give more feedback as I have time and better ways to reproduce things or get an idea what may be the problem.

One of the issues is that I sometimes need to minimize other windows to have the keyboard focus in the focussed window (It may be especially Firefox, which keeps the input focus). Another problem is sometimes windows opening behind other windows, but the problematic part is that raising them often leads to the problem that they do not stay in front when the focus is moved if I don't use the always-on-top function of KWin.

**Comment by totaam** [comment]
"focus-follows-mouse" is a non-standard setting that almost never gets tested...

@allo- some problems may go away if you use a separate xpra session for each forwarded application.

**Comment by totaam** [comment]
Some major focus issues were fixed recently: #3883

Please re-open if you have more details.

**Comment by totaam** [comment]
Some major focus issues were fixed recently: #3883

Please re-open if you have more details.
