### ISSUE TITLE
Failed to start xpra server on Debian stretch

### ISSUE THREAD

**Issue by anvandaren** [Xpra-org/xpra#3700]
**Describe the bug**
Xpra server xpra v3.1.3-r0 does not launch on Debian stretch. It complains about python version. The xpra version was upgraded to the latest from the xpra Debian Stretch repository.

We have used xpra on this server before extensively, but not the last years. 

**To Reproduce**
On the Debian stretch do:
```
$ xpra start :9677 --start=xterm
using systemd-run to wrap 'start' server command
'systemd-run' '--description' 'xpra-start' '--scope' '--user' 'python3' '/usr/bin/xpra' 'start' ':9677' '--start=xterm' '--systemd-run=no'
Running scope as unit: run-rae8cdc1f4d134c7593476980495e5006.scope
xpra for python 3.7 is not installed
 retrying with python2
xpra for python 2.7 is not installed
```

**System Information (please complete the following information):**
 - Server OS: Debian Stretch 9.13
 - Xpra Server Version xpra v3.1.3-r0

**Comment by totaam** [comment]
Debian Stretch ships with Python 3.5.3 and not 3.7 so you must have tweaked your installation.
I am quite confident that Debian Stretch installations do work properly.
In any case, the 3.x branches are being EOLed and you should move to a supported version.

**Comment by anvandaren** [comment]
@totaam is there any way to install a more recent version of xpra on Debian Stretch? 
We have the following in the sources.list:
`deb https://xpra.org/ stretch main`

**Comment by totaam** [comment]
There are many ways you can do this, with various levels of difficulty, but the best thing to do is to upgrade your OS to a newer release.
(and preferably also drop Debian which is really not a good platform for running xpra)
