### ISSUE TITLE
Does xpra fits my need to have a framebuffer which works together with my nvidia GPU configured as PRIME RENDER OFFLOAD ?

### ISSUE THREAD

**Issue by Marietto2008** [Xpra-org/xpra#3718]
Hello xpra users and developers,

I have two monitors right now. The first one is new,AOC 32 inches and I use it for FreeBSD. The second screen is 25 years old,it’s a SAMSUNG SYNCMASTER that I don’t want to use because it's not working well. I have 3 GPUS on my PC :

1) nvidia geforce GTX 1060 used for FreeBSD and configured as default on the BIOS / my PC boots using it /

2) Intel GPU integrated with the mobo

3) nvidia RTX 2080 ti. I want to use only the AOC monitor to use FreeBSD.

When I boot any bhyve (a hypervisor for BSD) / linux Vm I don’t want to use the Samsung monitor. I want to be able to use the desktop UI in Linux within a window with a framebuffer and at the same time I want to render my projects using the RTX 2080 ti in Linux,using the technology PRIME RENDER OFFLOAD,so without attaching any monitor to the VM. I’ve already installed the CUDA toolkit inside the Linux VM and it works well,BUT only if the RTX 2080 ti is attached to a physical monitor. At the moment the configuration that I’m trying to achieve is more comfortable for me than using two monitors. I need the framebuffer because without it,I can’t use Linux at all,since I can’t watch what happens when I move my mouse and keyboard,that’s because I can use one only monitor. The Samsung monitor is not working well. I think it’s dying. So I want :

    1. use one monitor connected to the first nvidia gpu (geforce 1060) and this monitor should display what happens on the host and even on the guest os (within the Linux desktop environment) and at the same time I would like to use the 2080 ti for rendering porpoises

    2. bound the 1060 to the host bsd : yes

    3. displaying the host’s graphical desktop and the graphical desktop of the linux - bhyve virtual machines at the same time,running the latter within a window smaller than the host screen resolution

    4. running a linux vm : yes

    5. with a passed-through second nvidia : yes,with the 2080 ti used for rendering

    6. with its output redirected to the host’s display : yes. I think that this can be done with a framebuffer. I always use the framebuffer created with vnc,but if at the same time I make the pass thru of the rtx 2080 ti I’m forced to use a secondary monitor,but I don’t want to do this.

I’m not sure if the intel gpu can act as a framebuffer instead of the fbdev driver used by vnc or if there is a way to use a framebuffer (fbdev or any other,I don’t care) together with the 2080 ti,WITHOUT using a secondary monitor.

Virtualgl can allow me to display what happens inside the linux vm and at the same time can I render my 3D projects using the 2080 ti ? The downsides of using virtual gl is the performance loss that I don't want. Not even sure if it will work under FreeBSD because I suspect that virtualgl can't run under FreeBSD.

I've created a thread on the nvidia forum,that you can read entirely going here :

https://forums.developer.nvidia.com/t/im-failing-trying-to-configure-the-framebuffer-as-default-graphic-adapter-and-the-nvidia-geforce-rtx-2080-ti-as-prime-render-offload/236365/37

The verdict of the nvidia developer has been something like this :

You can only use VirtualGL or rather bumblebee. This needs to be installed on the Linux VM. It will spawn a second Xserver on the nVidia gpu (that you won’t see) and then copy the output to the Xserver on the virtual graphics. Downsides: limited to OpenGL, performance loss. This won’t work with just one monitor, the limiting factor will always be the missing prime functions of the virtual gpu’s drm driver. I think it’s more fruitful to check if someone has some patches for it in the works.

At this point I've thought about Xpra. More or less I've understood what it is. But I'm not sure if it can solve my issue,I don't know if it allows me to do what I want. I suppose that what I need is a framebuffer that has the 3d acceleration with a low level of latencies that I can use within the Linux VM and the host os,which can act as an extension of the Linux graphical environment and that connects it to the graphical environment that I run on FreeBSD and that allows me to render my 3d projects using my RTX 2080 ti as PRIME RENDER OFFLOAD ? Is xpra exactly something like that or am I missing something ? thanks.

**Comment by totaam** [comment]
> The downsides of using virtual gl is the performance loss that I don't want.
> Not even sure if it will work under FreeBSD because I suspect that virtualgl can't run under FreeBSD

You should check that first.
What sort of workload would make the virtualgl cost significant enough to dismiss this option?
https://www.freshports.org/x11/virtualgl

> Is xpra exactly something like that or am I missing something ?

To be honest, I'm not sure I understand your use case properly...
xpra can do many things, with performance in mind and a GTX 2xxx, I am tempted to say that anything is possible.
Just try to use vsock or ivshmem for virtual machine transfers if you can.
It should be easy to get going and figure out what performance you can get out of it.

**Comment by Marietto2008** [comment]
I want to enjoy myself with stable diffusion. The os I'm running is FreeBSD,but I can also use Linux,using the bhyve hypervisor. Generix says that VirtualGL works only with OpenGL but I don't know if stable diffusion can use the OpenGL acceleration. My main gpu is RTX 2080 ti,not GTX 2xxx.

**Comment by totaam** [comment]
Moved to https://github.com/orgs/Xpra-org/discussions/3720

**Comment by Marietto2008** [comment]
I'm still waiting a further reply to this comment :

https://github.com/Xpra-org/xpra/issues/3718#issuecomment-1364681191

please consider my doubts not cleared...
