### ISSUE TITLE
crash when firefox spawns a popup window, sometimes

### ISSUE THREAD

**Issue by AGI-chandler** [Xpra-org/xpra#3719]
**Describe the bug**
xpra crashes when firefox opens a pop-up window, sometimes.  My specific use case is accessing our server's IPMI website and launching the iKVM to gain console access.  (I've learned the serial port can do something similar and I'm working with the manufacturer to get that setup, then wouldn't even need to involve firefox or xpra.)

The error shown at the end of the `server.log` is: `Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Managed to allocate after flush. (t=440.544) [GFX1-]: Managed to allocate after flush.`  Only thing Google found was [here](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/153) and [downstream here](https://bugs.gentoo.org/832986) but it only matches the first part of the error.  It's from 10 months ago, and was fixed and merged (can't tell in what version).  It affected libX11-1.7.3 but my system has libx11-6 2:1.8.1-2.

There was also an unexpected crash at the end of `xpra info` output, attached below, seems to be related to "Em Dash" character, not sure where that is coming from...

**To Reproduce**
1. Server command: N/A
2. Client command: `xpra start ssh://user@host/10 --start=firefox`
3. After launching firefox, it seems every 2nd or 3rd time I launch the iKVM (which opens in a pop-up window), the crash will occur.  I understand this may be difficult to reproduce since it involves an internal website only I can access.

Maybe it can be triggered by a generic popup?  Tried https://www.dummysoftware.com/popupdummy_testpage.html
oh success!!  When I try the `Right-click and select "Open in New Window" to allow a new window` link it triggers xpra crash.  On client side I see:
```
[...]
2022-12-25 00:09:26,346 Connection lost
2022-12-25 00:09:26,354 removing unix domain socket '/run/user/1000/xpra/clients/client-2994764'
Segmentation fault
```
Nothing in the server.log at the time of the crash.

On the client, syslog has:
```
xpra[2994764]: segfault at 10404120222 ip 00007f90bdeda325 sp 00007ffc04512e68 error 4 in libgobject-2.0.so.0.7500.0[7f90bdeb0000+32000]
Code: 74 53 48 8b 38 48 81 ff fc 03 00 00 76 4f 48 83 e7 fc 48 81 fe fc 03 00 00 77 72 48 c1 ee 02 48 8d 05 7f 50 02 00 48 8b 34 f0 <f6> 47 16 04 74 25 48 85 f6 74 20 48 83 ec 08 45 31 c0 31 c9 ba 01
```

**System Information (please complete the following information):**
 - Server OS: CentOS 8.4.2105
 - Client OS: Debian bookworm/sid/experimental
 - Xpra Server Version xpra-4.4.3-10.el8.x86_64
 - Xpra Client Version 5.0-r32356-1 (also tried with 4.4.3-r0-1)

**Additional context**
 - Changes made to the default configuration, if any. This can be shown with the command: xpra showconfig:
 [xpra showconfig client.txt](https://github.com/Xpra-org/xpra/files/10299457/xpra.showconfig.client.txt) | [xpra showconfig server.txt](https://github.com/Xpra-org/xpra/files/10299462/xpra.showconfig.server.txt)
 - The desktop environment, window manager used:  **GNOME 43.0 (client)**
 - Anything that would make the setup unusual:  number of screens **(2)**, resolution **(1366x768 and 1360x768)**, virtualization software **(no)**, access via another remote desktop tool (VNC, RDP, ..) **(no)**, etc **(nothing else comes to mind)**
 - The server log file, or output if no log file is used:  [server.log](https://github.com/Xpra-org/xpra/files/10299471/server.log) | [client output.txt](https://github.com/Xpra-org/xpra/files/10299475/client.output.txt)
 - xpra info for the session:  [xpra info.txt](https://github.com/Xpra-org/xpra/files/10299522/xpra.info.txt)
 - How the software was installed and what version, in full:  **Both client and server are using what is available in the xpra repositories.**
 - does this happen with all picture encodings?  **Tried h264 and whatever the default is.**
 - does switching off certain features make a difference (ie: sound **(already off in client config)**, opengl **(tried on and off)**, clipboard **(didn't check)**)
 - does re-connecting help?  **Usually**

Best Regards

**Comment by totaam** [comment]
> Client OS: Debian bookworm/sid/experimental

It is quite possible that Debian has broken the ABI of one of the libraries, that's par for the course when running sid.
I'm quite sure that showing popups does not normally crash xpra.
In those cases, turning off all encodings may help: `--encodings=rgb,png` (though performance will suffer)
Please try to reproduce this problem with a stable distribution.

**Comment by AGI-chandler** [comment]
> > Client OS: Debian bookworm/sid/experimental
>
> It is quite possible that Debian has broken the ABI of one of the libraries, that's par for the course when running sid. 

Yes you may be on to something there.  The base OS is `testing/bookworm` though, have been running testing for years without such issues, but do have a few packages from `unstable/sid` and even fewer from `experimental`.  Wouldn't you happen to know that when I searched for `libgobject-2.0.so.0.7500.0`, it happens to be part of `libglib2.0-0 2.75.0-1` from `experimental` 😳😅

glib has its fingers in a lot of places though, and experimental version was installed over a month ago without any issues until now.  Looks like I needed some newer gedit plugins to test out a different bug... Should I report this as a bug in libglib2.0-0 then?  kind of in unknown territory here.

> turning off all encodings may help: `--encodings=rgb,png` (though performance will suffer)

I couldn't get `--encodings=rgb,png` to work but after some reading and fiddling I think you meant try either `--encoding=rgb` or `--encoding=png`?  With either one I still have issues when popups happen, with something crashing/terminating, although there is no segmentation fault or info in the syslog as in my OP.  All I see on client side is "Connection lost" and in server.log:
```
2022-12-25 11:59:01,811 Missing property or wrong property type WM_TRANSIENT_FOR (window)
2022-12-25 11:59:01,812  no such window
```

> Please try to reproduce this problem with a stable distribution.

I don't know if I'll have time or resources to try that, but you're probably right in that popups do not normally cause issues as I'm sure some others would have reported it by now.  Guess I will just deal with it since it's intermittent and will keep on trying to get the Serial-over-LAN configured.

**Actually, as a workaround, setting the firefox preference `browser.link.open_newwindow.restriction` to `0`, which forces popups to open in a new tab, has stopped the crashing!**

**Comment by totaam** [comment]
> Should I report this as a bug in libglib2.0-0 then?

No, first make sure that you can reproduce the problem with a stable version.

> I couldn't get `--encodings=rgb,png` to work

Why not?
> but after some reading and fiddling I think you meant try either `--encoding=rgb` or `--encoding=png`?

No, I did not. `--encodings=rgb,png` should work. If it does not, then something is wrong with your setup.

> `no such window`

This is usually a sign that the window was quickly removed by the application.
This can happen due to focus, pointer or keyboard events.
(or just the application deciding to withdraw it)

**Comment by AGI-chandler** [comment]
> > I couldn't get `--encodings=rgb,png` to work
> 
> Why not?  `--encodings=rgb,png` should work. If it does not, then something is wrong with your setup.

huh... what could it be then?  When I run `xpra start ssh://user@server/10 --encodings=rgb,png --start=firefox` it results in:
```
[...]
invalid encodings specified: p, n, g, , r, b, 2, 4, 3
xpra initialization error:
 failed to identify the new server display!
2022-12-25 22:45:21,513 Error: failed to receive anything, not an xpra server?
2022-12-25 22:45:21,513   could also be the wrong protocol, username, password or port
2022-12-25 22:45:21,514   or the session was not found
2022-12-25 22:45:21,514   or maybe this server does not support 'unknown' compression or 'bencode' packet encoding?
2022-12-25 22:45:21,514 Connection failed
```

It's as if it's parsing the argument as separate characters or something, and where's that `2, 4, 3` coming from??  Tried using `--encodings="rgb","png"` and `--encodings='rgb','png'` and the results were exactly the same...

**Comment by totaam** [comment]
Thanks for pointing that out, `encodings=rgb,png` was broken (fairly recently - I believe) for remote ssh starts.

**Comment by AGI-chandler** [comment]
No problem man thanks for all your help.  Got the Serial-over-LAN working now too.
