### ISSUE TITLE
xpra gui + xpra-toolkit-keyboard warnings 

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3722]
**Describe the bug**

xpra gui + xpra-toolkit-keyboard causes warnings

```
$ xpra
/usr/lib/python3/dist-packages/xpra/client/gtk_base/../../gtk_common/gtk_view_keyboard.py:36: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "homogeneous, spacing" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  vbox = Gtk.VBox(False, 0)
/usr/lib/python3/dist-packages/xpra/client/gtk_base/../../gtk_common/gtk_view_keyboard.py:38: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label("Keyboard State")
/usr/lib/python3/dist-packages/xpra/client/gtk_base/../../gtk_common/gtk_view_keyboard.py:39: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  label.modify_font(Pango.FontDescription("sans 13"))
do_keymap_changed: current keymap
do_keymap_changed: ('us,gr,us', ['us', 'gr', 'us'], '', None, 'grp:alt_shift_toggle')
/usr/lib/python3/dist-packages/xpra/client/gtk_base/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gtk.Widget.get_root_window is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
/usr/lib/python3/dist-packages/xpra/client/gtk_base/../../gtk_common/gtk_view_keyboard.py:95: DeprecationWarning: Gdk.Window.get_pointer is deprecated
  (x, y, current_mask) = self.window.get_root_window().get_pointer()[-3:]
$ xpra --version
xpra v5.0-r32356 (g2a62420e3) beta
```

I guess related to https://github.com/Xpra-org/xpra/issues/2177? 
Posting mostly for issue-tracker-completeness

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.5 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
The commit above fixes a bunch of them, but these two are much more difficult to silence:
> `DeprecationWarning: Gtk.Widget.get_root_window is deprecated`

In some cases, we just need access to the root window.
GTK is trying so hard to make us waylandize everything that they are forgetting that absolute coordinates are a thing in every other OS out there.
I guess we could hack around it in some cases to avoid the ugly warning, but this would probably increase the kloc for no other benefit.
> `DeprecationWarning: Gdk.Window.get_pointer is deprecated`

GTK wants us to:
> Deprecated since version 3.4
> Use [Gdk.Window.get_device_position](https://lazka.github.io/pgi-docs/Gdk-3.0/classes/Window.html#Gdk.Window.get_device_position)() instead.

That's all well and good, but at present we have no need to know which device generated the event since we only have a single virtual `XTest` device server side.

**Comment by totaam** [comment]
FWIW: silence many more (though not the `get_pointer` ones) in c14beb8762330477fa108e124fafbb2fcde8061c + 0e9eadea0373d963a060b4b90b83c810cb707195

**Comment by stdedos** [comment]
_Also reported here: https://github.com/Xpra-org/xpra/issues/3988#issuecomment-1705855975_
