### ISSUE TITLE
Xpra opens windows as tabs

### ISSUE THREAD

**Issue by nimamox** [Xpra-org/xpra#3723]
**Describe the bug**
Not sure if it's a bug or not. But I've searched a lot and I haven't seen anyone (or the documentation) mentioning this. I use Xpra 4.4 on a remote headless Linux server and my local macOS laptop to have the GUIs of the apps running on Docker containers of the Linux server shown on my macOS laptop, even with streaming audio and OpenGL. Everything works perfectly, but there is an issue that's been bothering me a lot. I run Xpra in the seamless mode, and all windows are shown as tabs of a single window on macOS. Then, I need to detach the tab into a new window manually:

![tg_image_1906475866](https://user-images.githubusercontent.com/12006975/210181575-2b402a73-beba-440f-a885-3a3d8b7617d9.jpeg)

If it's not clear, what I want is to have each window opened as a separate window, not a new tab. I already have some application running, and I develop some code that I need to respawn regularly, which would be frustrating as each time I have to switch to that tab (for that window) which also mistakenly inherits the size of the previous window (tab) that is already open. 

As a side, I have found that the binaries released for macOS can not be run due to an issue with the `libcrypto` shipped with Xpra. FYI, I resolve this issue by replacing those files with the libcrypto and libssl installed by Homebrew. So, at least this one is a bug!

**To Reproduce**
1. Server: `xpra start --daemon=yes :9898`
2. Client: `xpra attach ssh:username@ip:9898 --encoding=h264`
3. Action: Opening any [unrelated] applications
4. Effect: All windows are shown as new tabs. Need an option to override this so that any window would be result on a new window on the client.

**System Information (please complete the following information):**
 - Server OS: Headless Ubuntu 22.04.1 LTS (with Ubuntu 20.04 Docker images)
 - Client OS: macOS Ventura 13.0.1
 - Xpra Server Version: v4.4.3-r0
 - Xpra Client Version v4.4-r0

**Comment by totaam** [comment]
I'm going to guess that this is Ventura feature since I have never seen this before.

I've just synced our MacOS build environment with https://github.com/jralls/gtk-osx-build yesterday and there are fixes to GTK, specifically for Ventura - perhaps this will fix things.
I do not have the hardware needed to test this.

**Comment by nimamox** [comment]
You are right. Since I don't have access to a Windows machine or Linux Desktop, to rule out that it's a macOS thing, I had run Xpra client on the Linux server itself which I was accessing through Xpra client (different session) on my macOS, but observed that the tabbing also occurs there! I'd checked the Xpra code and found that while I don't find any code for the tabbing mechanism, there's the very old thread #539 that discusses such mechanism.

Anyways, I just checked on another machine with macOS Monterey (12.5) and apps are not shown as tabs in form of a "merged" window, anymore.

**Comment by nimamox** [comment]
@totaam I was in fact regularly checking your macOS beta releases. I even tried to build Xpra from scratch but I failed. 
Thank you for getting back to this issue. I've updated my Linux server and two macOS systems (one Ventura and the other running the older Monterey versions) to the Xpra v5.0, but the situation has not changed at all. Monterey works as expected but Ventura still has the issue.

On my server Ubuntu 22.04:
```
UBUNTU$ xpra --version
xpra v5.0-r32727 (gf782ffe8f) beta
```

On my client macOS Ventura 13.2:
```
macOS$ xpra --version
xpra v5.0-r32739 (ge0ba9f839) beta
```

Actually, to be thorough, since I run my applications inside docker containers, I modify `/etc/xpra/conf.d/55_server_x11.conf` to
```
xvfb = Xvfb +extension GLX +extension Composite -screen 0 \
    8192x4096x24+32 -listen tcp -noreset -auth $XAUTHORITY \
    -dpi 96x96
```
and add the following line to `/etc/xpra/conf.d/60_server.conf`
```
pulseaudio-configure-commands = pactl load-module module-native-protocol-tcp port=34567 auth-ip-acl=172.17.0.0/16
```
Then, on the server, I run the command below:

```
UBUNTU$ xpra start --daemon=yes --bind-tcp=0.0.0.0:9898 :9898; sleep 2; export DISPLAY=:9898; xhost +
```
and run my docker container (with some redaction):
```
UBUNTU$ sudo docker run --device /dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix --privileged -v $HOME/.Xauthority:/root/.Xauthority -v $HOME/.Xauthority:/home/nima/.Xauthority -e DISPLAY=172.17.0.1:9898 -v $HOME/.ssh:/home/nima/.ssh --rm -it -e PULSE_SERVER=tcp:172.17.0.1:34567 --net=host .....
```
Then, on macOS:
```
macOS$ xpra attach tcp://scisrs1:9898/9898
```


While both my Monterey and Ventura systems run the same Xpra v5.0-r32739, the issue is still only with Ventura:

Ventura:
![Ventura](https://user-images.githubusercontent.com/12006975/220212145-1f614374-6715-426a-8e6c-ae8f7715358c.gif)

Monterey:
![Monterey](https://user-images.githubusercontent.com/12006975/220211954-60a2e85e-afa0-4f26-bb62-6cae8dd556dd.gif)

In the PyQt app I'm writing, I realized that if I set the window size by issuing `QWidget::setFixedSize(w, h)`, then the my app's window will not be grouped with other windows shown by Xpra as tabs, but a new window! So I assume Xpra should be able to forcefully prevent such undesired tabbing!

**Comment by totaam** [comment]
> `UBUNTU$ xpra start --daemon=yes --bind-tcp=0.0.0.0:9898 :9898; sleep 2; export DISPLAY=:9898; xhost +`

Why not just `--start="xhost +"`.
`sleep 2` is not going to be reliable.

As for this bug, this is a MacOS feature, try: System Preferences -> Mission Control -> Then untick "Group windows by application".

More details here: [Use Stage Manager to organize apps and windows on Mac](https://support.apple.com/en-ph/HT213315)

Alternatively, you could start an xpra session for each application which would prevent MacOS from seeing these applications as belonging to the same process and therefore ungroup them.

**Comment by nimamox** [comment]
Thanks for the tip about `xhost`. It makes sense. As for the grouping, sadly, this doesn't seem to be the case. It's disabled by default on Ventura, and enabling that on Monterey doesn't replicate the issue. Thank you for following up on this. It is not a pressing issue and I guess I'm used to it now. Thank you for your hard work.

**Comment by nimamox** [comment]
Accidentally realized that this is fixed by changing the "Prefer tabs when opening documents" option to "Never".

![image](https://github.com/user-attachments/assets/3831bb6a-4a18-45fd-8ef7-6ccc08dce65a)
