### ISSUE TITLE
Incorrect DPI selection dependent on Modes list order in xorg.conf

### ISSUE THREAD

**Issue by cherio** [Xpra-org/xpra#3724]
**Describe the bug**

I'll jump straight to the discovery.

Part 1.

The negotiated upon connection DPI was incorrect until I
1) added my screen resolution `2560x1440` to the `Modes` list in `/etc/xpra/xorg.conf` (it wasn't there in the original file), and
2) placed this new mode to be the 1st in the list

I tried various combinations of host/client settings of DPI, scaling and sizes. It was only when my screen resolution was added to be the very first in the `Modes` list (for the matching `Depth`, which was 24 in my case) did the negotiated DPI was correctly chosen.

Part 2.

Another observation confirms that the server only uses the very 1st mode from the list.

Before I made the change in the `xorg.conf` the 1st mode was `8192x4096` and the DPI was erroneously evaluated as `30x34` instead of the explicitly requested `96x96`. Evidently the formula for the negotiated DPI looks like this

```
CLIENT_DPI / (1ST_MODE_RESOLUTION / CLIENT_RESOLUTION) = USED_DPI
```
e.g.
```
for X: 96 / (8192 / 2560) = 30
for Y: 96 / (4096 / 1440) = 33.75 ~ 34
```

I tested several modes, moving them to the 1st position in the list and my suspicion held true for all of them.

**To Reproduce**

1. server command
```
xpra start :33 \
	--speaker=disabled --microphone=disabled --pulseaudio=no --av-sync=no --webcam=no \
	--input-method=IBus \
	--fake-xinerama=no \
	--start=xfce4-terminal
```

2. client command
```
xpra attach ssh://user@host/33 \
	--speaker=disabled --microphone=disabled --pulseaudio=no --av-sync=no --webcam=no \
	--dpi=96

```
3. specific action to trigger the bug
For instance run
```
git gui
```
although my guess any Tcl/Tk gui application would behave similarly. The fonts and layout look as if magnified.

**Additional context**

Popup warning regarding DPI mismatch:
![xpra-dpi-warning](https://user-images.githubusercontent.com/2200569/210411798-e4e83f0e-bc5c-41b2-b8e9-58dde30fd07f.png)

Censored server log with DPI warnings:
[xpra-server.log](https://github.com/Xpra-org/xpra/files/10338688/xpra-server.log)

**Comment by totaam** [comment]
Please see:
https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

> `Python/GTK3 Linux unknown unknown unknown tty client version 4.3.3-r0 64-bit`

This version is out of date. The OS is unspecified.

---

Your dummy driver version is too old.
You need version 0.4.0 or the dummy dpi patch.

**Comment by cherio** [comment]
> This version is out of date. The OS is unspecified.

I was wrongfully assuming that running Arch ensures up-to-date packages. It is usually the case but evidently not always. I filed an issue with Arch, although I'm not supposed to report out-of-date project as an issue, but I believe it is justified because of the nature of this distribution is to keep packages fresh.

Also I can't really tell why the OS version is not being captured in the log ¯\_(ツ)_/¯. This might be something only you can tell :wink:

```
$ uname -a
Linux hostnamex 6.1.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 31 Dec 2022 17:40:35 +0000 x86_64 GNU/Linux
```

I do not have a dummy driver installed because it is not distributed via standard Arch repos and I am trying to rely on AUR as little as possible. I guess I need to consider making exception in this case.

Appreciate your response.

**Comment by totaam** [comment]
> I do not have a dummy driver installed because it is not distributed via standard Arch repos

That doesn't make sense. You must have it installed since you modified `/etc/xpra/xorg.conf` as a workaround.
This can only have an effect if you are using the dummy driver.
