### ISSUE TITLE
Repo / packaging logistics: Private key + `arch`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3726]
Should https://xpra.org/repos/bionic/xpra-beta.list match e.g. https://xpra.org/repos/bookworm/xpra-beta.list?

Similarly for https://xpra.org/repos/bionic/xpra.list

```deb
deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ] https://xpra.org/ focal main
deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ] https://xpra.org/beta/ focal main
```

**Comment by totaam** [comment]
Ah, they're all wrong!

**Comment by totaam** [comment]
Are you referring to the gpg key location and using a different key for different distros?
That would be: https://github.com/Xpra-org/xpra/issues/3539#issuecomment-1125823769 and https://github.com/Xpra-org/xpra/issues/3485#issuecomment-1106080392

**Comment by stdedos** [comment]
> Edit: Wait. I'm not seeing that.

I only copy-pasted the fixed lines for your convenience. I'm sorry if it looked like I implied "this is how https://xpra.org/repos/bionic/xpra.list looks like" 😓 

> Are you referring to the gpg key location and using a different key for different distros?

I am saying that: `bionic` is the only release not containing `[ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ]`. 

---

... but now I remembered, `bionic` is 18.04, which means ... I cannot test if `[ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ]` is actually valid for `bionic` or not.

**Comment by stdedos** [comment]
It is, however, valid for `focal`, which is also missing `[ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ]`:

```console
$ curl https://xpra.org/repos/focal/xpra.list
deb https://xpra.org/ focal main
$ curl https://xpra.org/repos/focal/xpra-beta.list
deb https://xpra.org/beta/ focal main
```

**Comment by ehfd** [comment]
https://github.com/Xpra-org/xpra/issues/3539
This, I would say, is more painless.

**Comment by ehfd** [comment]
> I am saying that: bionic is the only release not containing [ arch=amd64,arm64 signed-by=/usr/share/keyrings/xpra-2022.gpg ].

This is actually invalid for bionic.

**Comment by ehfd** [comment]
I came back to #3539 because I was having the same issue when I needed uniformity for VS Code installation.

**Comment by stdedos** [comment]
> @stdedos I believe that it isn't present for focal, because it isn't needed there?

Depends on you definition of "needed", I guess. Ofc, I haven't verified "this" against a Canonical-clean Ubuntu Focal ISO, so (My) Milleage Might Vary

**Comment by stdedos** [comment]
> #3539 This, I would say, is more painless. Same template for all recent versions from 18.04 to 22.10 and similar Debian versions.

"More or less painless" idk. Haven't used it ever, don't know how it works: Same-same-old-but-new to me.

`apt-add-repository` creates `.list` files (right now in my Ubuntu Focal at least), so ... I am using them anyway. Might as well have a "sane, secure, up-to-date" version of it.

**Comment by totaam** [comment]
This is superseded by #3539 - right?
