### ISSUE TITLE
Open subwindow  on the main  monitor or where cursor is

### ISSUE THREAD

**Issue by svargh** [Xpra-org/xpra#3730]
**Is your feature request related to a problem? Please describe.**
When starting an application them its window is opened always on the left most monitor.
When docked to Dual/Three 42' monitors, this is not very comfortable.
This also happens  to non remote windows like: Right click on systemtray -> Information -> About Xpra

**Describe the solution you'd like**
Open subwindow  on the main  monitor or where cursor is.
May be it should query from Windows10/11 what the main display is which I have set.

**Describe alternatives you've considered**

**Additional context**
- 13' inch laptop recent Win11 docked to eGPU Nvidia RTX 3090  with 3x42' monitors or 2x42 on WDTB4
- Xpra client: 4.4.3
- -XpraServer: Linux 5.4.0-131-generic 4.4
![image](https://user-images.githubusercontent.com/13705625/211163881-e5b4840d-9c4d-405e-b5f0-fc583cec2c3b.png)

**Comment by totaam** [comment]
Please try again using `Xdummy` which may require you to use a different distribution OS since Debian and Ubuntu seem to be unable to work with it.

**Comment by svargh** [comment]
I see in https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md that it might work in Ubuntu 18.04.
I should try out with Ubuntu20.04, might be, I have luck.
