### ISSUE TITLE
Compile error: ‘NV_ENC_PRESET_DEFAULT_GUID’ is deprecated

### ISSUE THREAD

**Issue by goekce** [Xpra-org/xpra#3733]
**Describe the bug**

I want to use
During build I get:

```
...
xpra/platform/xposix/proc.c:1020: warning: "likely" redefined
 1020 |   #define likely(x)   __builtin_expect(!!(x), 1)
      | 
In file included from /usr/include/proc/readproc.h:13,
                 from xpra/platform/xposix/proc.c:832:
/usr/include/proc/procps.h:54: note: this is the location of the previous definition
   54 | #define likely(x)       __builtin_expect(!!(x),1)
      | 
xpra/platform/xposix/proc.c:1021: warning: "unlikely" redefined
 1021 |   #define unlikely(x) __builtin_expect(!!(x), 0)
      | 
/usr/include/proc/procps.h:55: note: this is the location of the previous definition
   55 | #define unlikely(x)     __builtin_expect(!!(x),0)
      | 
xpra/codecs/nvidia/nvenc/encoder.c: In function ‘__pyx_pymod_exec_encoder’:
xpra/codecs/nvidia/nvenc/encoder.c:52882:3: error: ‘NV_ENC_PRESET_DEFAULT_GUID’ is deprecated: WILL BE REMOVED IN A FUTURE VIDEO CODEC SDK VERSION [-Werror=deprecated-declarations]
52882 |   __pyx_t_2 = __pyx_f_4xpra_6codecs_6nvidia_5nvenc_7encoder_guidstr(NV_ENC_PRESET_DEFAULT_GUID); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 1260, __pyx_L1_error)
      |   ^~~~~~~~~
...
```

**To Reproduce**
- install latest Nvidia capture and encoding SDKs, set pkgconfig paths
- build

**System Information (please complete the following information):**
Archlinux, git version

My goal is to use NVENC. AFAI understand I need also NvFBC. Is this related to Xpra?

Workaround is to disable `strict_ENABLED` flag in `setup.py`.

After compilation xpra cannot load nvenc due to: `AssertionError: failed to load BGRX_to_NV12 for cuda context <pycuda._driver.Context `. But this is probably unrelated to the deprecation.

**Comment by totaam** [comment]
> My goal is to use NVENC.
> AFAI understand I need also NvFBC.

No, these are two separate things.
You only need nvfbc for fast shadow servers.

> `error: ‘NV_ENC_PRESET_DEFAULT_GUID’ is deprecated`
Use:
https://github.com/Xpra-org/repo-build-scripts/blob/main/pkgconfig/nvenc.pc
Which contains `-Wno-error=deprecated-declarations` to avoid the warning causing an error.

> After compilation xpra cannot load nvenc due to: `AssertionError: failed to load BGRX_to_NV12 for cuda context <pycuda._driver.Context>`.

Without the full error message, it's impossible to tell. Run with `-d cuda` for more details.
My guess would be that the server cannot find the file in the expected location, or cannot open it.
Or perhaps the cuda / driver version is incompatible with this file.

> But this is probably unrelated to the deprecation.

Correct.

**Comment by goekce** [comment]
> Run with `-d cuda` for more details.

Ok, I will open a new case after I look into that.


> Which contains `-Wno-error=deprecated-declarations` to avoid the warning causing an error.

Thanks.

**Comment by jhgoebbert** [comment]
Thank you for the hint to the modified `nvenc.pc`.
NVIDIA announced here that the declarations will be removed in Q1/2023 - so quite soon:
https://docs.nvidia.com/video-technologies/video-codec-sdk/deprecation-notices/
