### ISSUE TITLE
Cisco OpenH264

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3734]
We might consider using Cisco's OpenH264 (https://github.com/cisco/openh264) as decoder and encoder.

**Comment by totaam** [comment]
See earlier ticket: #721

**Comment by totaam** [comment]
The commit above adds a decoder.

Unfortunately, there are a some problems with it:
* only supports `YUV420P`
* the decoder owns the buffers, so we're supposed to copy them - that's what ffmpeg does

Not in EPEL yet either: [Please make OpenH264 available for CentOS Stream 9 and RHEL 9 users](https://bugzilla.redhat.com/show_bug.cgi?id=2053295).
And not in Debian, only in Ubuntu Kinetic: https://packages.ubuntu.com/search?keywords=openh264&searchon=names&suite=kinetic&section=all

---

Here are some initial performance numbers with `glxgears` (including copying the YUV data):
```
2023-01-13 21:45:52,896 openh264 decoded    10266 bytes into 300x300 YUV420P in   2ms
2023-01-13 21:46:05,003 openh264 decoded    84033 bytes into 3840x2090 YUV420P in  70ms
```
Using the same source, the `ffmpeg` decoder is much faster: 2ms / 30ms

**Comment by totaam** [comment]
As per 6b635f461053e1213fa33aa7751be04b6ddba8d0, we no longer build this codec by default on RPM distros.

**Comment by totaam** [comment]
Now re-enabled since the problematic (licensing / patents) codecs now have a separate package: 07b91210a01f53fa639d9d714eae32515af2ac87

**Comment by totaam** [comment]
This will do for now, most other encoders should score higher than this one.

**Comment by totaam** [comment]
The `OpenH264` decoder is now the default `h264` decoder in v6 since we removed the ffmpeg codecs in 20bb5f04233dc650022bc67d5904566d1b158af9.

**Comment by totaam** [comment]
Forgot that speed and quality were never fully implemented for the openh264 encoder!
See https://github.com/Xpra-org/xpra/issues/2046#issuecomment-4770964048

**Comment by totaam** [comment]
See also packaging issues in #4626
