### ISSUE TITLE
Question about Windows support

### ISSUE THREAD

**Issue by vmarh** [Xpra-org/xpra#3741]
We've checked your supported platforms outlined in Wiki https://github.com/Xpra-org/xpra/wiki/Platforms and only Windows 10/11 are listed as supported. Our question is, if you also provide support for Windows Servers and if so, which versions since Windows server have corresponding architecture as Windows Servers?

**Comment by totaam** [comment]
It's not really clear to me if you want to run xpra as a client or as a server on a Windows Server OS.
Xpra should run on all Windows Server OS - the same way that it still should work on MS Windows 7... it's just not a supported configuration.
This type of question would be a better fit for https://github.com/Xpra-org/xpra/discussions
