### ISSUE TITLE
compile error of v4.4.3 on raspberry pi

### ISSUE THREAD

**Issue by PeterPablo** [Xpra-org/xpra#3746]
https://github.com/Xpra-org/xpra/blob/67446ab399dd35510a3778bfa91fde9c76a9e83f/setup.py#L2216
will fail, if if nvidia_ENABLED in some lines above evaluates to false, as the variable `CUDA_BIN` is then not initialized
```
Traceback (most recent call last):                                                                                             
  File "./setup.py", line 2216, in <module>                                                                                    
    add_data_files(CUDA_BIN, ["fs/share/xpra/cuda/README.md"])                                                                 
NameError: name 'CUDA_BIN' is not defined                                                                                      
```

Simply commenting this line 2216 makes the compilation process start. It is too early to tell, if it will finish successfully.

**Comment by PeterPablo** [comment]
it seems master branch has this already fixed:
https://github.com/Xpra-org/xpra/commit/9c92e9054a4c976fbc28d5f956fe7fa9fde64b9d

Anyhow, this issue might guide others facing issues to an explanation on the error message (that did not reveal meaningful results in case of me searching..).

**Comment by PeterPablo** [comment]
Thank you for this minimalist feedback on my report.

**Comment by totaam** [comment]
Duplicate of #3693
