### ISSUE TITLE
OpenGL probe error when /usr/local/bin/xpra run, but not when run from build directory

### ISSUE THREAD

**Issue by gitbxf4** [Xpra-org/xpra#3747]
**Describe the bug**
Happens with both 4.4.3 and current git version. When I run xpra that is built on my machine and installed into /usr/local, I get the following error message:

    `Xpra OpenGL Acceleration Failure`
    `probe error: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

When I run the xpra executable in `~/src/xpra-4.4.3/fs/bin/` (after building via `python3 ./setup.py build`). it shows OpenGL working:

    `Validating OpenGL: success (Mesa Intel(R) HD Graphics 4400 (HSW GT2)`

I'm doing this from the client. The server has a new built version of 4.4.3 on it too.

**To Reproduce**
I've done it several times both ways and it happens as described each time.

**System Information (please complete the following information):**
 - Server OS: Debian unstable (up to date)
 - Client OS: Debian unstable (up to date)
 - Xpra Server Version 4.4.3
 - Xpra Client Version 4.4.3

**Additional context**
`python3-opengl` package is installed from Debian repository, as are all the other packages listed on the platform specific instructions for building from source, except opencv, kerberos, and gssapi.

I also looked at `setup.py --help` to see if there was some OpenGL flag, but didn't see anything that looked right.

Thank you!

**Comment by totaam** [comment]
@gitbxf4 I have no idea what causes this.
Can you try running with:
```shell
XPRA_ALL_DEBUG=1 xpra ...
```
Hopefully there will be a more informative backtrace or message we can work with.

**Comment by gitbxf4** [comment]
Thank you @totaam. I've run the above commands, but not seen anything telling or helpful. I'll dig more and follow-up again. (In part, I'm replying here now because I don't know github etiquette and I don't want to appear unappreciative.)

One thing that I did not understand when I initially posted, but now seems even more confusing to me. I am trying to build xpra (both 4.4.3 and git) in my home directory. If I just build the program, but don't install it, it doesn't work at all.

```
me@localhost:~/src/xpra/fs/bin$ ./xpra start ssh://me@remotehost.com --start=xterm
Traceback (most recent call last):
  File "/home/me/src/xpra/fs/bin/./xpra", line 5, in <module>
    from xpra.platform import init, set_default_name
ModuleNotFoundError: No module named 'xpra'
```
When I install it in /usr/local/, the two discrepant openGL messages happen. So, even when I start `~/src/xpra/fs/bin/xpra start  ...` it seems it is really still running the code in `/usr/local/lib/python3.11/dist...`.  Seems even stranger to me, but my familiarity with python is limited.

I'm going to follow-up the thread about python dependency problems in Debian unstable and see if in the meantime I can get a Debian package from xpra/repos working again. Thanks again!

**Comment by totaam** [comment]
> I am trying to build xpra (both 4.4.3 and git) in my home directory.

Then you need to tell `python` where to find the code that you've just installed.
ie: `PYTHONPATH=./path/to/your/local/install ./xpra`

**Comment by totaam** [comment]
I'm closing this because this looks like a packaging / installation issue and mostly harmless one at that.
