### ISSUE TITLE
Match client layout when using monitor mode

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3749]
**Is your feature request related to a problem? Please describe.**
#3524 implements monitor mode. This works great. It would be very cool if the server can match the client's geometry, like Windows Terminal Server does.

**Describe the solution you'd like**
After the clients send it's ["desktop-size"] hello packet; create an XDUMMY display for each client display in a left-to-right order.
Then match the resolution of clients displays. 

**Describe alternatives you've considered**
Using  xrandr commands on the server to match the clients geo.

**Comment by totaam** [comment]
We need a new switch - not sure we should overload the `resize` command line option on the client to make this request.
Together with `--desktop-fullscreen=true`, we should do our best to take over the client's desktop area.

**Comment by totaam** [comment]
There was already some support for this on the client side:
https://github.com/Xpra-org/xpra/blob/90424bb125c8d12060331d20444c4e1c4c3478fa/xpra/client/ui_client_base.py#L551-L560
The commit above triggers now the same server code we already used in seamless mode for mirroring the client's monitor layout.
The key for clients is to specify `desktop-fullscreen = True` in the hello packet.
To configure the virtual monitors, the server will use the new (v4.4) `monitors` hello packet attribute or fallback to the legacy `screen_sizes` one.
@TijZwa can you give it a spin?

**Comment by totaam** [comment]
@TijZwa I assume that this works for you?
