### ISSUE TITLE
[beta] focal repository "is no longer signed"

### ISSUE THREAD

**Issue by zatricky** [Xpra-org/xpra#3762]
**Describe the bug**

    $ sudo apt update
    [... snip ...]
    Reading package lists... Done   
    E: The repository 'https://xpra.org/beta focal Release' is no longer signed.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

**To Reproduce**

Normal update:

    $ sudo apt update

**System Information (please complete the following information):**

 - Server OS: Ubuntu 20.04 (focal)
 - Client OS: n/a
 - Xpra Server Version: n/a
 - Xpra Client Version: n/a

**Additional context**

See #2208 ; maybe the same problem?

**Comment by zatricky** [comment]
Note that I went through the documentation at https://github.com/Xpra-org/xpra/wiki/Download#-for-debian-based-distributions just in case there was a change to how it should be set up.

My original sources file wasn't exactly the same - but after following the process (re-downloading the key, replacing the sources file) the same error still occurs.

**Comment by totaam** [comment]
@zatricky can you just try again?
I've uploaded some new beta builds and my test focal VM updated fine.

**Comment by zatricky** [comment]
Apologies for the delay. I see a different error now and did not realise the original issue was fixed. I will investigate further.

**Comment by zatricky** [comment]
I figured it out ; Updates are working for me again :-) See #3782

**Comment by totaam** [comment]
Sorry about that. The web host had run out of disk space again so some of the files could not be copied... including the signatures as those get re-generated last.
I've made some space, for now, and the updates should be working again.

**Comment by zatricky** [comment]
Tested and working again. Thank you :-)

**Comment by friki67** [comment]
Hello. I'm having this issue in Linux Mint 21, doing apt update:

`E: The repository 'https://xpra.org/beta jammy Release' is not signed.`

**Comment by totaam** [comment]
@friki67 see #3863
