### ISSUE TITLE
Xpra proxy server without authentication

### ISSUE THREAD

**Issue by bishnoi29nitin** [Xpra-org/xpra#3764]
**Describe the bug**
I am trying to make a proxy server which does not require any password to connect to server from the client browser.

Previously I created the proxy server with the command > sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5906 --ssl-cert=/usr/share/xpra/www/xpra-ssl.cert --ssl=on 

This was working fine and I was able to connect multiple clients at a time, but now as per my application need I need to create a proxy server which does not require wss, ssl and certificates to connect i.e not authentication (password).

**To Reproduce**
1.  sudo xpra proxy :100 --ws-auth=none --bind-ws=0.0.0.0:5906 
2. client command>> xpra start --bind-tcp=0.0.0.0:5906 --html=on --start='command to execute'

**System Information (please complete the following information):**
 - Server OS: centos 7
 - Client OS: centos 7
 - Xpra Server Version [e.g. 4.2.3] >> xpra v3.0.12-r27627
 - Xpra Client Version [e.g. 4.3] >> xpra v3.0.12

**Additional context**
Please help with a command using which I will be able to connect to server with multiple clients at a time, as I am able to connect to server with single client at a time but not with multiple access at a time.

**Comment by totaam** [comment]
```shell
sudo xpra proxy :100 --ws-auth=none --bind-ws=0.0.0.0:5906
xpra start --bind-tcp=0.0.0.0:5906 --html=on --start='command to execute'
```
You probably mean:
```shell
xpra start ws://SERVERHOST:5906/
```
And don't use `ws-auth=none`, use `ws-auth=allow`:
```shell
sudo xpra proxy :100 --bind-ws=0.0.0.0:5906,auth=allow
```
YMMV.

> `xpra v3.0.12-r27627`

This is not up to date.

**Comment by bishnoi29nitin** [comment]
Thank you for your quick reply.

With the command (sudo xpra proxy :100 --ws-auth=allow --bind-ws=0.0.0.0:5906), I am able to create the proxy server and if I check the log file, then it  shows as this.

>>
2023-02-20 10:48:40,239 created ws socket '0.0.0.0:5906'^[[0m
^[[33m2023-02-20 10:48:40,257 Warning: failed to create socket directory '/run/user/0/xpra'^[[0m
^[[33m2023-02-20 10:48:40,258  [Errno 2] No such file or directory: '/run/user/0/xpra'^[[0m
^[[33m2023-02-20 10:48:40,258 Warning: some of the sockets are in an unknown state:^[[0m
^[[33m2023-02-20 10:48:40,258  /root/.xpra/ssl-hn-100^[[0m
^[[33m2023-02-20 10:48:40,258  please wait as we allow the socket probing to timeout^[[0m
^[[33m2023-02-20 10:48:46,298 Warning: cannot create socket '/run/user/0/xpra/serverIP-100':^[[0m
^[[33m2023-02-20 10:48:46,298  [Errno 2] No such file or directory^[[0m
^[[33m2023-02-20 10:48:46,298  ($XDG_RUNTIME_DIR has not been created?)^[[0m
2023-02-20 10:48:46,299 created unix domain socket '/run/xpra/serverIP-100'^[[0m
2023-02-20 10:48:46,299 created unix domain socket '/root/.xpra/serverIP-100'^[[0m
^[[33m2023-02-20 10:48:46,299 Warning: missing sound module^[[0m
^[[33m2023-02-20 10:48:46,329 Warning: zlib is the only compressor enabled^[[0m
^[[33m2023-02-20 10:48:46,329  install and enable lz4 support for better performance^[[0m
2023-02-20 10:48:46,334 serving html content from '/usr/share/xpra/www'^[[0m
2023-02-20 10:48:46,373 xpra is ready.^[[0m
2023-02-20 10:48:46,374 xpra proxy version 3.0.12-r27627 64-bit^[[0m
2023-02-20 10:48:46,374  uid=0 (root), gid=0 (root)^[[0m
2023-02-20 10:48:46,374  running with pid 453468 on Linux CentOS 7.5.1804 Core^[[0m

I hope this is correct.

Now I am facing the issue, when I try to connect to this proxy server with the command 

xpra start --bind-tcp=0.0.0.0:5906 --html=on --start=xterm

it gives an error that the port is already in use. Can you please help with the command using which I can connect to the xpra proxy port with multiple user at a time (min 10 users).

I am sorry to such silly questions, but I am new to this and need you help.

**Comment by bishnoi29nitin** [comment]
One more thing, is it possible that both the server and the client can be the same machine?

**Comment by totaam** [comment]
> `sudo xpra ..`

Using `sudo`, you may end up with a mix of environments.
It is best to login as root or use a system service.

> `Warning: zlib is the only compressor enabled`

You should have `lz4` installed, something is not right.

> `xpra proxy version 3.0.12-r27627 64-bit`

This version is out of date.

> `xpra start --bind-tcp=0.0.0.0:5906 --html=on --start=xterm`

That's trying to start a server on the same port you've already started a proxy on.

My guess is that you want something like:
```shell
xpra start tcp://user@SERVERIP:5906/ --start=xterm
```
Preferably with a different user for each one of your sessions as many applications don't work very well when launched multiple times under the same user account.

> One more thing, is it possible that both the server and the client can be the same machine for xpra?

Of course it is. You get extra benefits when you do, like fast `mmap` transfers.
