### ISSUE TITLE
Connect To Xpra in Browser without install on client

### ISSUE THREAD

**Issue by titus-shoats** [Xpra-org/xpra#3766]
Hello, I installed Xpra on a remote machine. I'm interested in using the HTML browser feature to share a desktop app where anyone can view the app in their browser without having to install anything on their machine.  For instance, if I use the following command to share a desktop app in the browser:  xpra start --bind-tcp=0.0.0.0:9875 --html=on --start=vlc 

And  I try to connect using a browser on a different machine I get the following error:

<img width="1205" alt="Screen Shot 2023-02-16 at 2 41 01 PM" src="https://user-images.githubusercontent.com/12973004/219469991-4ff3b526-4e83-43ac-a2f3-48902fe65fa3.png">

Do I need to open port 9875 on the remote machine so anyone can connect?
How do I configure XPRA to have anyone view the app inside their browser without installing anything on their machine? Im sure there has to be a way to configure xpra for this feature? Any advice? Thanks

**Comment by totaam** [comment]
The port needs to be open on the server! How else are you going to be able to connect to it?
If you are still having problems, try `--bind-ws` instead and report more details as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by titus-shoats** [comment]
Exactly, that worked! 
My last question is, is there a way to have each user have a different session? I tried --sharing=no   but my users are still sharing the same sessions and they need to have their own separate sessions

**Comment by totaam** [comment]
> Each user should have a separate browser session

Then you can either pre-launch sessions on the server and give them an individual port each or run the proxy on the public port and use it to connect to these sessions or start new sessions.
See:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Proxy-Server.md
How you decide to configure authentication is up to you. One user account per session is usually the easiest and safest approach.
