### ISSUE TITLE
mirror mouse cursor when sharing

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3767]
Xpra server changes needed for https://github.com/Xpra-org/xpra-html5/issues/229

**Comment by MarkoSchuetz** [comment]
I'm now using xpra v5.0-r32793 (ge735e6a3b) beta and I believe I also have the most recent HTML5 client (in the information it only says 7.0 beta).
When I start e.g. zathura in xpra and then attach to it locally and from a browser on a remote device, I do not see the cursor on the remote move when the mouse on the local machine is moved.

**Comment by totaam** [comment]
@MarkoSchuetz please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs - there is not enough information for me to try to reproduce the issue.
