### ISSUE TITLE
Remove python <<3.11 dependency?

### ISSUE THREAD

**Issue by SkyperTHC** [Xpra-org/xpra#3768]
Hello,

The latest .deb at https://xpra.org/dists/sid/main/binary-amd64/ has a python <<3.11 dependency.

This causes a problem now that python 3.11.1 is widely deployed:
```
(Reading database ... 47492 files and directories currently installed.)
Preparing to unpack xpra_4.4.3-r0-1_amd64.deb ...
Unpacking xpra (4.4.3-r0-1) over (4.4.3-r0-1) ...
dpkg: xpra: dependency problems, but configuring anyway as you requested:
 xpra depends on python3 (<< 3.11); however:
  Version of python3 on system is 3.11.1-3.
```

**Comment by totaam** [comment]
Invalid.
Please see https://github.com/Xpra-org/xpra/issues/3531#issuecomment-1406373850 and use the beta repository for distributions that do not have a stable ABI.
