### ISSUE TITLE
Xpra cannot find "set_screen_size" in start-desktop

### ISSUE THREAD

**Issue by hazeltoh** [Xpra-org/xpra#3773]
**Describe the bug**
Xpra server does not resize window upon client connection. It will only resize window on the first time the client connects. Upon doing `-d geometry`, we can see that it is unable to find the function `self.set_screen_size` in `ScreenDesktopModel`.  Tested the same thing in Xpra beta versions and it also has the same issue.

**To Reproduce**
1. xpra start-desktop :1 --bind-tcp=0.0.0.0:8080 -d geometry
2. Accessing via localhost:8080 using Chrome (110.0.5481.100)
3. Resize chrome window

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS: MacOS Ventura
 - Xpra Server Version: v4.4.3-r0
 - Xpra Client Version: latest

**Additional context**
<img width="1594" alt="Screenshot 2022-12-28 at 3 57 19 PM" src="https://user-images.githubusercontent.com/126546699/221767327-34bb0dbd-c091-4033-babc-c07550d657df.png">

**Comment by totaam** [comment]
I'm pretty sure that this is already fixed: a36eef12a9b897880312a6627a5b9fc90fff33bb and will be included in the 4.4.4 release.
