### ISSUE TITLE
Sound delay during video playback

### ISSUE THREAD

**Issue by 7vk1** [Xpra-org/xpra#3775]
**Describe the bug**

I am using xpra to screen transfer Firefox from an Ubuntu18 desktop server created with VirturalBox.
When playing a video on Youtube, the audio of the video is delayed by about 1 second and the delay increases as time goes on.
When I play the video directly from VirtualBox using the virtual display, there is no delay.

Is there any workaround for this symptom?

**To Reproduce**
1. server command
 ```
 xpra start \:100 --start-child=firefox --bind-tcp=0.0.0.0:10000 --pulseaudio=yes
 ```

2. client command
Connected from xpra client

3. specific action to trigger the bug
Video playback on Youtube

**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x]
   Ubuntu18 Desktop
 - Client OS: [e.g. Windows 10]
     Windows 10
 - Xpra Server Version [e.g. 4.2.3]
    4.3.4-r0
 - Xpra Client Version [e.g. 4.3]
    4.4.3

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
You may be able to find some pointers in #2861, #3234 and other tickets.

**Comment by 7vk1** [comment]
Referring to #2861 and #3234, we have changed the codecs used and XPRA_SOUND_SINK, but the audio delay during video playback has not improved.

The client codecs and execution results are as follows
```
 client.sound.speaker.codecs=('opus','flac','wavpack','wav+lz4','wav','opus+ogg','vorbis+mka','vorbis+ogg','vorbis','mp3','flac+ogg','aac+mpeg4','speex+ogg','opus+mka')
```
- opus 0.5 second delay
- flac 0.5 second delay
- wavpack 0.5 second delay
- wav+lz4 0.5 second delay
- wav 0.5 second delay
- opus+ogg 0.5 second delay
- vorbis+mka No sound
- vorbis+ogg No sound
- vorbis No sound
- mp3 0.5 second delay
- flac+ogg 0.5 second delay
- aac+mpeg4 No sound
- speex+ogg 0.5 second delay
- opus+mka 0.5 second delay

I checked the logs with the -d sound option to see if it could tell us anything, and the following logs were output.
```
[2023-03-08T07:S8:37Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2023-03-08T07:S8:37Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2023-03-08T07:S8:37Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
[2023-03-08T07:S8:37Z ERROR mp4parse] Found 2 nul bytes in "\0\0"
```

Is there anything else I should try?

**Comment by totaam** [comment]
Your original post stated that the delay was 1 second, 0.5 seconds is to be expected.
That's the default value of `XPRA_SOUND_QUEUE_TIME`:
https://github.com/Xpra-org/xpra/blob/996f300b0e85ce73203f25f891e3269e09e3ac15/xpra/sound/sink.py#L49
That's the size of client-side receive buffer.

You can change this environment variable - as well as many others you can find in that file and in the server source - ie `XPRA_SOUND_QUEUE_SOURCE_TIME`:
https://github.com/Xpra-org/xpra/blob/996f300b0e85ce73203f25f891e3269e09e3ac15/xpra/sound/src.py#L35

But that's straying away from the default values and all the testing that went into choosing these values.
Good luck...
