### ISSUE TITLE
[feature request] add possibility to disconnect unshared shared session

### ISSUE THREAD

**Issue by solofoA45** [Xpra-org/xpra#3776]
**Is your feature request related to a problem? Please describe.**

When sharing then unsharing a session with "xpra control set-sharing [yes|no]", the shared session is still connected after having unshared it.
 
**Describe the solution you'd like**

When the session is unshared, it would be useful to be able to disconnect the shared/unshared session to end the collaboration session.

**Describe alternatives you've considered**

No alternative considered. It was discussed that xpra detach could be used with a session uuid to disconnect the session.

**Additional context**

N/A

**Comment by totaam** [comment]
Done in the commit above, this was simple enough that it could be backported to older branches.

**Comment by solofoA45** [comment]
Thanks!
