### ISSUE TITLE
Client to server paste

### ISSUE THREAD

**Issue by carl-alphonce** [Xpra-org/xpra#3784]
**Describe the bug**
While I can cut & paste from server to client, I cannot cut & paste from client to server.

**To Reproduce**
1. On client select text in server, type Ctrl-C
2. On server, type Ctrl-V
3. Nothing is pasted on server side

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)
 - Client OS: macOS Ventura 13.1 (Macbook Pro M1 Pro processor, 32 GB RAM)
 - Xpra Server Version xpra v4.4.3-r0
 - Xpra Client Version: xpra v4.4.3-r1

**Additional context**
I start xpra as follows:
   `xpra start ssh://<user>@<host> --start "xterm -fs 14 -fa DejaVuSansMono" "$@" 2>/dev/null`

**Comment by totaam** [comment]
@AGI-chandler I believe that this error is due to your outdated build. Try a newer beta build.

As for the OP's bug, I'm not sure, having the client and server `-d clipboard` log would help speed things up.

**Comment by AGI-chandler** [comment]
> As for the OP's bug, I'm not sure, having the client and server `-d clipboard` log would help speed things up.

Here are mine, hope it helps
[client.txt](https://github.com/Xpra-org/xpra/files/10921455/client.txt)
[server.txt](https://github.com/Xpra-org/xpra/files/10921456/server.txt)

**Comment by totaam** [comment]
@AGI-chandler please try 996f300b0e85ce73203f25f891e3269e09e3ac15

**Comment by AGI-chandler** [comment]
Hi @totaam many thanks for your swift action on this, my time is limited though and honestly I've never yet had to check out a commit like this... ah I see so it's all in the master branch already, so I'll `git clone` it and attempt to compile it, will let you know how it goes!

**Comment by totaam** [comment]
@AGI-chandler the change is very small, it's much easier to locate `xpra/x11/gtk_x11/clipboard.py` in your existing installation and patch it in place.

**Comment by AGI-chandler** [comment]
@totaam I see, so I just backed up the /usr/lib/python3/dist-packages/xpra/x11/gtk_x11/clipboard.py   on client and server and replaced clipboard.py, it helps!  I could paste 6,648,214 bytes now for example, but there still seems to be issues with larger amounts for example 9,034,938 bytes was too much and seemed to trigger the same issue...

**Comment by totaam** [comment]
@AGI-chandler Was the error in the server log the same?
There is a size limit on clipboard transfers and you may have hit it.

**Comment by totaam** [comment]
@AGI-chandler / @carl-alphonce can I close this ticket?

**Comment by AGI-chandler** [comment]
Things are working fine for me here with v4.4.6, was able to copy & paste 16,775,003 bytes both ways between client & server!
