### ISSUE TITLE
crash of zeroconfig under bullseye

### ISSUE THREAD

**Issue by alexbodn** [Xpra-org/xpra#3785]
**Describe the bug**
there is an unhandled exception in zeroconfig, the version already in debian bullseye.
xpra is the version you provide for bullseye.
to avoid this, i uninstalled the deb and pip installed the contemporary version.
the exception vanished.

**Comment by totaam** [comment]
Please provide the exception and specify the versions that do fix the problem.

**Comment by totaam** [comment]
Please provide the exception

> you may modify the debian dependency for zeroconf or avahi

We support dozens of distro builds with this one file, and I really don't have time to test those changes, so that's unlikely to happen.

**Comment by alexbodn** [comment]
i removed the zeroconf installed by pip
and reinstalled the one in debian bullseye 
and rerun xpra, but the error doesn't show again.
will periodically check the logs.
a big thank!

**Comment by totaam** [comment]
> i removed the zeroconf installed by pip

FWIW: mixing distribution packages with manual pip installations is not a supported configuration.
