### ISSUE TITLE
apt repository at "https://xpra.org" triggers "Failed to fetch ... File has unexpected size (X != Y) Mirror sync in progress? "

### ISSUE THREAD

**Issue by nifr** [Xpra-org/xpra#3788]
**Describe the bug**

Since yesterday the `xpra.org` apt repository seems to have an issue.

After adding the repository any `apt` package list updates fails with:

```
E: Failed to fetch https://xpra.org/dists/bullseye/main/binary-amd64/Packages.gz  
File has unexpected size (60263 != 60153). 
Mirror sync in progress? [IP: x.x.x.x 443]

    Hashes of expected file:
     - Filesize:60153 [weak]
     - SHA512:f3712f5ca476ae86571c8790340730c1c4196db6dd195fa48611351debdfcf74d9747306e697bbfa111ca00ead095d635fb3d979e1c69f340b2954e017fcd193
     - SHA256:11269a3dd52f9eada8a9995ea1a522c4e47e911de0e9ab91a8cd1e77ac454de1
     - SHA1:89c8888bd7534cd1f09c2e266fb0ef8c810195e6 [weak]
     - MD5Sum:f8a696b70cd0cdf15297176b314e9e63 [weak]
    Release file created at: Tue, 27 Dec 2022 15:17:50 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**To Reproduce**

1. Add the xpra apt repository
      ```bash
      curl -sLo- "https://xpra.org/gpg.asc" \
         | gpg --batch --yes --dearmor -o "/etc/apt/keyrings/xpra.gpg"
     
      echo "deb [signed-by=/etc/apt/keyrings/xpra.gpg] https://xpra.org/ bullseye main" \
         | tee "/etc/apt/sources.list.d/xpra.list" 
      ```
    
3. Run`apt-get update`

**System Information (please complete the following information):**
 - Server OS: Debian 11 (bullseye)
 - Xpra Server Version: any
 - Xpra Client Version any

**Additional context**

Could this be related to the `v3.1.4`  [tag](https://github.com/Xpra-org/xpra/tags) / release that was pushed yesterday?

The repository URL https://xpra.org/dists/bullseye/main/binary-amd64/ shows files `Packages.{gz,bz}` were both updated at `2023-03-05 18:58`.

**Comment by totaam** [comment]
Odd, there will be a 3.1.4 release very soon and all the repository files will be re-generated.

**Comment by totaam** [comment]
FYI: 3.1.4 has been officially released: https://lists.devloop.org.uk/pipermail/shifter-users/2023-March/002958.html

And the repositories have been re-generated, I'm not seeing any problems here but perhaps you will need to zap the cached files.

Thanks for the coffee!

**Comment by totaam** [comment]
https://github.com/Xpra-org/xpra/issues/4170#issuecomment-2014260048
