### ISSUE TITLE
invalid encodings specified

### ISSUE THREAD

**Issue by AGI-chandler** [Xpra-org/xpra#3798]
Suit yourself we can start a new report here.&nbsp; The problem isn't some russian repo though you are making a mountain of a molehill there I think, glossing over the real issues and other questions I'm asking trying to get this fixed.&nbsp; Like, which versions of `ffmpeg-xpra` goes with which versions of `xpra`? because only version `ffmpeg-xpra-6.0-1.el8` gets automatically installed even though the missing libraries are in `ffmpeg-xpra-5.1.2-1.el8`.&nbsp; It seems there might be dependency issues with your Centos packages then?&nbsp; so that's one problem to check out.&nbsp; Now I've removed `xpra` and all it's dependencies as well as the russian `compat-ffmpeg5-libs-5.1.2-1.el8`, so we have a clean slate now, where shall we begin?&nbsp; I suppose the latest beta.

So I installed `xpra-5.0-10.r32045.el8` with `ffmpeg-xpra-5.0-1.el8` and tested with a simple `xpra start ssh://localhost/ --start=xterm --encodings=rgb,h264` command that you recommended previously, which throws a red error:
```
 Error importing dec_avcodec2 (avcodec2 decoder)
  libx264.so.163: cannot open shared object file: No such file or directory
```

more dependency problems.&nbsp; So I killed that and tried upgrading `ffmpeg-xpra` to version `5.1.2-1.el8`.&nbsp; Now I get this red error:
```
 Error importing dec_avcodec2 (avcodec2 decoder)
  /usr/lib64/xpra/libavcodec.so.59: undefined symbol: vaSyncBuffer
```
but xpra is able to continue further and then I see:
```
  SSH: 'invalid encodings specified: h, 2, 6, 4, , r, g, b, 3'
[...]
Error: failed to receive anything, not an xpra server?
  could also be the wrong protocol, username, password or port
  or the session was not found
Connection failed
```

I try upgrading `ffmpeg-xpra` to version `6.0-1.el8` and now I get these red errors:
```
Error importing csc_swscale (swscale colorspace conversion)
 libswscale.so.6: cannot open shared object file: No such file or directory
Error importing dec_avcodec2 (avcodec2 decoder)
 libavcodec.so.59: cannot open shared object file: No such file or directory
```
(These were the original errors I was seeing that cause me to find russian `compat-ffmpeg5-libs-5.1.2-1.el8`).

So I've removed all xpra and dependencies again and will move on to `xpra-4.4.3-10.el8` now, which installs `ffmpeg-xpra-6.0-1.el8` again and throws the same red errors as before with `xpra start`.&nbsp; I'll now downgrade `ffmpeg-xpra` to `4.4.1-3.el8` and try that, no luck, still same red errors about `libswscale` and `libavcodec`.&nbsp; Seems `ffmpeg-xpra-5.1.2-1.el8` is the version with those libraries. but still getting this error:
```
Error importing dec_avcodec2 (avcodec2 decoder)
 /usr/lib64/xpra/libavcodec.so.59: undefined symbol: vaSyncBuffer
```

I guess next would be to try with `xpra-4.3.3-10.r31234.el8` but now it's time to sleep, will continue later.

Best Regards

**Comment by totaam** [comment]
> So I installed `xpra-5.0-10.r32045.el8` with `ffmpeg-xpra-5.0-1.el8`

How?
At time of writing, following the [RPM installation instructions](https://github.com/Xpra-org/xpra/wiki/Download#-for-rpm-distributions) should get you `5.0-r32879`, which is much more recent and includes the fix for the encoding strings.
It does have other issues though - looks like CentOS broke Xdummy..
That's par for the course with beta repositories though.

**Comment by AGI-chandler** [comment]
Idk man I have been using Xpra for a long time maybe the repo needed to be reinstalled?  It looks like there were packages from both xpra and xpra-beta repos installed so i wiped everything out including the repos and cleaned the yum database.  Trying again with just stable repo.  It's installed `xpra-4.4.3-10.el8` and `ffmpeg-xpra-5.1.2-1.el8` now with dependencies.

Running `xpra start ssh://localhost/ --start=xterm  --encodings=rgb,h264` and it's still not working, but at least not getting any lib errors like originally:
```
  SSH: 'invalid encodings specified: h, 2, 6, 4, , r, g, b, 3'
[...]
Error: failed to receive anything, not an xpra server?
  could also be the wrong protocol, username, password or port
  or the session was not found
Connection failed
```

Oh my gosh dude it's your example command! (ok plus a combination of previous stable/beta incompatibilities)
but xterm loads right up now without ` --encodings=rgb,h264` option! 😂
What's more? the log file shows: `ignored invalid default encoding option: h264`
but then later on says: 
```
using h264 as primary encoding, also available:
  vp9, vp8, png, png/P, png/L, webp, rgb24, rgb32, jpeg, jpega, mpeg1, mpeg2, scroll
```
huh? 😂

For the real test, on my workstation, `xpra` is upgraded to `5.0-r32879-1` but `xpra-codecs` stayed at the previous version `5.0-r32850-1`, is that ok?  I could not install xpra-codecs 5.0-r32879-1 because: `xpra-codecs : Depends: libspng but it is not installable`.
There's no deb package `libspng` that i could find, is that a typo?  Did you mean `libspng0`?
With this setup, I still get:
```
invalid encodings specified: h, 2, 6, 4, , v, p, 9, 8, m, e, g, +, w, b, n, a, i, f, r, 3, j, 5, 1, s, c, o, l, y
Error: displayfd failed
 did not provide a display number using displayfd
xpra initialization error:
 failed to identify the new server display!
Error: failed to receive anything, not an xpra server?
  could also be the wrong protocol, username, password or port
  or the session was not found
Connection failed
```

Tried downgrading `xpra` back to `5.0-r32850-1` and get the same error.
Tried adding `--encodings=rgb,h264` option and the same thing happens except it just says `invalid encodings specified: h, 2, 6, 4, , r, g, b, 3`

Uninstalled `xpra` and `xpra-codecs`, trying stable version `4.4.4-r0-1` and .... finally a working combination! for this job at least until next time.

**Comment by totaam** [comment]
> It's installed xpra-4.4.3-10.el8

How?
The latest for the `almalinux` repo - which you should be using if you're on CentOS - is 4.4.4

> Oh my gosh dude it's your example command!

What example command?

> xterm loads right up now without  --encodings=rgb,h264 option! joy

You should almost never use the `--encodings` option.

> I could not install `xpra-codecs 5.0-r32879-1` because: `xpra-codecs : Depends: libspng but it is not installable`

Wait, so now this isn't about CentOS 8 but about some Debian install?
a955dc576627a1a0bcf5c8e6d3ab2a73278b1e56 fixes the `libspng0` packaging issue.

> trying stable version 4.4.4-r0-1 and .... finally a working combination! for this job at least until next time

Beta should work, I certainly don't see any issue with the `--encodings=` option here.
But stable is probably better for you.

**Comment by AGI-chandler** [comment]
> How? The latest for the `almalinux` repo - which you should be using if you're on CentOS - is 4.4.4

I mean I was just following the instructions from https://github.com/Xpra-org/xpra/wiki/Download#-linux which I see have recently been updated.  The new repo indeed has upgraded xpra and dependencies to 4.4.4-10.r32879.el8.

> What example command?

The one you used [over here](https://github.com/Xpra-org/xpra/commit/bcc1c94c140bdafc6af5106fd3d48cd6ea040eab#commitcomment-103721098)

> You should almost never use the `--encodings` option.

I don't, but was just testing following your lead.
 
> Wait, so now this isn't about CentOS 8 but about some Debian install? [a955dc5](https://github.com/Xpra-org/xpra/commit/a955dc576627a1a0bcf5c8e6d3ab2a73278b1e56) fixes the `libspng0` packaging issue.

Yes I'll typically run xpra from my workstation running Debian and initiate a connection to various other computers running Debian or CentOS.  I was testing on CentOS localhost first like you suggested.
