### ISSUE TITLE
start failure - "only console users allowed"

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3811]
Fedora 37. Just installed 5.0-10.r32985.
Start locally with `xpra start :73 --attach=no --start-child=xterm`
Terminal output:
```
using systemd-run to wrap 'seamless' server command
Running scope as unit: run-rc94f0cea8ce24c83a0efd9e3d05f5b77.scope
Entering daemon mode; any further errors will be reported to:
  '/run/user/5271/xpra/73/server.log.new'
vfb failed to start, exiting
```

/run/user/5271/xpra/73/server.log shows you're trying to start Xorg itself rather than, say, Xdummy:
```
2023-03-29 14:37:12,832 no uinput module (not usually needed)
/usr/libexec/Xorg.wrap: Only console users are allowed to run the X server
2023-03-29 14:37:12,850 
2023-03-29 14:37:12,850 Xvfb command has terminated! xpra cannot continue
2023-03-29 14:37:12,850  if the display is already running, try a different one,
2023-03-29 14:37:12,850  or use the --use-display flag
2023-03-29 14:37:12,850  full command: Xorg -noreset -novtswitch -nolisten tcp +extension GLX  +extension RANDR +extension RENDER -auth $XAUTHORITY  -logfile ${XPRA_SESSION_DIR}/Xorg.log  -configdir "${XPRA_SESSION_DIR}/xorg.conf.d/$PID"  -config "${XORG_CONFIG_PREFIX}/etc/xpra/xorg.conf"
2023-03-29 14:37:12,850 
```
Compare vs what's running in another F37 machine's pre-upgrade environment:
`/usr/libexec/Xorg -noreset -novtswitch -nolisten tcp +extension GLX +extension RANDR +extension RENDER -auth /home/karl/.Xauthority -logfile /run/user/5271/xpra/73/Xorg.log -configdir /run/user/5271/xpra/73/xorg.conf.d/246805 -config /etc/xpra/xorg.conf -depth 24 :73`

Showstopper.

**Comment by karlkleinpaste** [comment]
When I manually invoke Xorg using `/usr/libexec/Xorg` (same command line with that one change), I can then `xpra start` as before and it simply adopts the running Xorg, and everything appears to work normally.

**Comment by karlkleinpaste** [comment]
Here's a fun, if somewhat goofy, personal resolution...

Mutter `man Xwrapper.config`, where you will learn that putting this content into that file makes things Just Work.
```
allowed_users = anybody
needs_root_rights = no
```
If you use only the 1st line, Xorg will still fail, on a complaint of logging using elevated privs. Both lines are req'd.

Thus, disaster for myself has been overcome: I can do normal `xpra start` without manually starting Xorg first.

(This hack discovered by doing `strings /usr/libexec/Xorg.wrap | grep / ` and finding the file mentioned.)

**Comment by totaam** [comment]
Caused by bde83581d86b5009795e2e62f513c4e60289fa6b - I thought that all distros could use `/usr/libexec/Xorg` directly now? (will check)

**Comment by totaam** [comment]
The change was correct but a build time dependency was missing (the commit above fixes that) and I obviously did not notice when I tested the RPMs built on my local desktop... because this system does have `/usr/libexec/Xorg` installed!

The quick fix is to edit `/etc/xpra/conf.d/55_server_x11.conf` and add `/usr/libexec` before `Xorg`.
Otherwise, new builds have been uploaded with the fix. (r32991)

**Comment by karlkleinpaste** [comment]
> this system does have `/usr/libexec/Xorg` installed!

Well...sure. So do all my systems. Any system with `xorg-x11-server-Xorg` installed has `/usr/bin/Xorg`, `/usr/libexec/Xorg`, and `/usr/libexec/Xorg.wrap`.

I will upgrade in a bit and try again, without the Xwrapper.config hackery mentioned above.

**Comment by karlkleinpaste** [comment]
r32991 is fine again. thx.
