### ISSUE TITLE
Setting image encoding to PNG 8bpp (colour) does not work.

### ISSUE THREAD

**Issue by nentibusarchitectura** [Xpra-org/xpra#3826]
**Describe the bug**
Setting image encoding to PNG 8bpp (colour) does not work, the images are still 24bit, in the past PNG 8bpp would show the characteristic 256 colour dithering when working and the display will run faster on a weak network link. Now the display (remote windows) remain in 24 bit colour. So PNG 8bpp has no effect other than making all images look like overtly compressed jpg images.

**To Reproduce**
Open browser, google colourful images, set picture encoding to PNG 8bpp, image doesn't change to 8bit 256, it looks like jpg compression.
```
ExecStart=/usr/bin/xpra start :100
--start-after-connect="/usr/bin/xfce4-terminal"
--start-via-proxy=no
--start-new-commands=yes
--no-pulseaudio
--no-microphone
--no-speaker
--no-daemon
--webcam=no
--opengl=no
--systemd-run=no
--env=XPRA_VAAPI=0
```
client command:
```
"xpra attach ssh:@:100 --border=orange,1
--encoding=rgb
--compress=9
--no-microphone
--no-speaker
--no-cursors
--ssh='ssh -p 2222'
--desktop-scaling=off
--opengl=no
--headerbar=yes
--env=XPRA_CLIPBOARD_IMAGE_STAMP=0
```
**System Information (please complete the following information):**

-  Server OS: Ubuntu 20.04.6 LTS
-  Client OS: Ubuntu 20.04.6 LTS
-  Xpra Server Version: 4.4.4-r0-1
-  Xpra Client Version: 4.4.4-r0-1

**Comment by totaam** [comment]
> `--env=XPRA_VAAPI=0`

This is unnecessary as this has been the default for a very long time now.

> `--compress=9`

Bad idea(tm). Don't do that.

> `--opengl=no`

Is there are reason for this one?

---

> Setting image encoding to PNG 8bpp (colour) does not work
> Open browser, google colourful images

The "Bit Depth` tool in `xpra toolbox` would be a more reliable test.

> set picture encoding to PNG 8bpp

How do you set it? Which exact command line argument?

> in the past PNG 8bpp would show the characteristic 256 colour dithering when working and the display will run faster 

Odd. `png/P` is usually no better than `webp`, even with small savings from the downsampling.

> on a weak network link

How weak is it?

**Comment by totaam** [comment]
The commit above will honour `png/P` again but please answer the questions from the earlier comment.

**Comment by nentibusarchitectura** [comment]
> > `--env=XPRA_VAAPI=0`
> 
> This is unnecessary as this has been the default for a very long time now.

Last time I upgraded the computer I use as an xpra server with an Intel integrated the version of XPRA at the time crashed badly if I didn't disable VAAPI, that is from that time, I had no idea that was the default now, will remove it then. :-)
 
> > `--compress=9`

> Bad idea(tm). Don't do that.

Really? I have been using that for years. Sorry, why is it bad have I misunderstood what that setting does? Isn't it supposed to control the level of compression on the lz4/zlib? So my understanding was: less bandwidth more compression... Am I wrong? Can you advise on an appropriate value?

> > `--opengl=no`
> Is there are reason for this one?

Yes, if I don't disable opengl my screen becomes like a flashing disco ball.

> > Setting image encoding to PNG 8bpp (colour) does not work
> > Open browser, google colourful images
> 
> The "Bit Depth`tool in`xpra toolbox` would be a more reliable test.
> 
> > set picture encoding to PNG 8bpp
> 
> How do you set it? Which exact command line argument?

I change the encoding via the tray icon's picture menu, that is what I always have done, I connect by default using Raw and if I'm on a weak link I switch the encoding.

> > in the past PNG 8bpp would show the characteristic 256 colour dithering when working and the display will run faster
> 
> Odd. `png/P` is usually no better than `webp`, even with small savings from the downsampling.

Trust me it used to make a massive difference when I used ADSL 4mbit ADSL, I noticed the PNG/p wasn't working in 8 bit when I had to use tethering on a mobile last week.

> > on a weak network link
> How weak is it?

Tethering on 4G mobile

**Comment by nentibusarchitectura** [comment]
@totaam How do I test these commits you're using for the fixes? Shall I run the beta version from the beta repo or should I build from source?

**Comment by totaam** [comment]
> at the time crashed badly if I didn't disable VAAPI

I remember this quite well.
This commit disabling it is from 2 years ago: fb52a4b8e58eaa27df509e2286d16efcd0d93ae6

> Can you advise on an appropriate value?

`lz4` shouldn't really be used for anything, so this is not a big deal.
But as with most things, it is best to just leave it on default.
Higher values may compress slightly more but this may also take much more CPU time, which causes other problems.
Since your bandwidth is *very* constrained, it *may* still be useful.

> Yes, if I don't disable opengl my screen becomes like a flashing disco ball.

What driver?
Can you post the `xpra opengl` output?
OpenGL used to cause such problems, but lately (~last 4-5 years) it has been very stable.

> Trust me it used to make a massive difference when I used ADSL 4mbit ADSL

Ah, right! That's way lower than what xpra is supposed to work with!
(a single lossless screen update can easily consume over a second of bandwidth budget!)

> Tethering on 4G mobile

What makes this even more difficult to handle is the latency jitters.

> How do I test these commits you're using for the fixes?

You can apply the small changes to your existing installation files - you only need the server updated.

> Shall I run the beta version from the beta repo or should I build from source?

Either will work, there are updated Ubuntu packages in the beta repo now. (r33142 or later)

**Comment by nentibusarchitectura** [comment]
> You can apply the small changes to your existing installation files - you only need the server updated.

Thanks I will try to add the changes to the existing install...

> What makes this even more difficult to handle is the latency jitters.

Tell me about it, but I manage, usually I use tether/slow links on emergencies or while on the road, xpra's convenience of keeping the applications running on the remote box and reconnecting from anywhere is fantastic and it will always be faster than plain X lol.

> xpra opengl

This is the server console:

`
Warning: vendor 'Intel' is greylisted,
 you may want to turn off OpenGL if you encounter bugs
GLU.version=1.3
GLX=1.4
accum-alpha-size=0
accum-blue-size=0
accum-green-size=0
accum-red-size=0
alpha-size=0
aux-buffers=0
blue-size=8
buffer-size=24
depth=24
depth-size=0
direct=True
display_mode=ALPHA, DOUBLE
double-buffered=True
green-size=8
level=0
max-viewport-dims=16384, 16384
opengl=4.6
platform=linux
pyopengl=3.1.0
red-size=8
renderer=Mesa Intel(R) HD Graphics 530 (SKL GT2)
rgba=True
safe=True
shading-language-version=4.60
stencil-size=0
stereo=False
success=True
texture-size-limit=16384
transparency=True
vendor=Intel
zerocopy=False
`

And this is the xpra session as client:

`
GLU.version=1.3
GLX=1.4
accum-alpha-size=0
accum-blue-size=0
accum-green-size=0
accum-red-size=0
alpha-size=0
aux-buffers=0
blue-size=8
buffer-size=24
depth=24
depth-size=0
direct=True
display_mode=ALPHA, DOUBLE
double-buffered=True
green-size=8
level=0
max-viewport-dims=16384, 16384
opengl=4.5
platform=linux
pyopengl=3.1.0
red-size=8
renderer=llvmpipe (LLVM 15.0.7, 256 bits)
rgba=True
safe=True
shading-language-version=4.50
stencil-size=0
stereo=False
success=True
texture-size-limit=16384
transparency=True
vendor=Mesa/X.org
zerocopy=False
`

**Comment by totaam** [comment]
> `renderer=Mesa Intel(R) HD Graphics 530 (SKL GT2)`

That should be fine.
> `pyopengl=3.1.0`

That's probably the cause: Ubuntu 20.04 ships a `pyopengl` version from 2014!
https://pypi.org/project/PyOpenGL/3.1.0/#history
I've now changed it to require 3.1.4 or later: 517f37fa796bdef4391472828fc32e7880c05ba1
So, starting with v5, xpra will not try to enable OpenGL on Ubuntu 20.04

**Comment by nentibusarchitectura** [comment]
> I've now changed it to require 3.1.4 or later: [517f37f](https://github.com/Xpra-org/xpra/commit/517f37fa796bdef4391472828fc32e7880c05ba1)
> So, starting with v5, xpra will not try to enable OpenGL on Ubuntu 20.04

Many thanks for this too.
