### ISSUE TITLE
Xpra 4.4.4 seems to have erratic focus behaviour

### ISSUE THREAD

**Issue by matthewshawgr** [Xpra-org/xpra#3827]
I am using Xpra to run JetBrains Rider remotely, as well as Dolphin (KDE file manager). 

In the past this has worked very well.

I recently upgraded to Xpra 4.4.4 and started noticing what I believe are "focus" related issues. For example:
 - I can be typing in the editor, and the cursor will disappear. I have to click in the editor again to regain focus.
 - I press a keyboard shortcut to search (e.g. Ctrl + F); sometimes the cursor will jump to search input box, other times it will disappear.

I have been trying to determine a consistent way to reproduce, it in the general case, but I cannot. The issue does not seem to occur in a plain text editor. I suspect it is because Rider is always bringing up popups to try and give suggestions, and this. 

To Reproduce:
1. Open a project in a Jetbrains Rider (or likely any Jetbrains product). 
2. Start editing files. Ctrl +F to search. Ctrl + N to search for classes, Ctrl + Alt + N to search for files.
3. You should see that focus at some point does not work as expected. 

System Information:
 - Server OS: Ubuntu Focal 20.04
 - Client OS: Windows 10
 - Xpra Server Version 4.4.4
 - Xpra Client Version 4.4.4

**Comment by totaam** [comment]
Please run both client and server with `-d focus` and post the log samples corresponding to the problems.

**Comment by totaam** [comment]
Was reading through [Re: XInitThreads in library constructor breaks Motif!](https://www.mail-archive.com/xorg-devel@lists.x.org/msg58024.html) and was reminded that: _one such example was using currenttime as opposed to the event timestamp for `XSetInputFocus`_
We do use `CurrentTime`:
https://github.com/Xpra-org/xpra/blob/e25f3ba679136cf4b2ffc35d11cd4d2bf3280ea3/xpra/x11/bindings/window_bindings.pyx#L523
https://github.com/Xpra-org/xpra/blob/368b4e4b4f0d3b2d7d2a02c86ea89111f8644f1e/xpra/x11/gtk_x11/send_wm.py#L20
https://github.com/Xpra-org/xpra/blob/3803f14183e44d0cec197560c86357e234de48ca/xpra/x11/gtk_x11/world_window.py#L171
And when we don't, it's not necessarily the correct time either - just the server time:
https://github.com/Xpra-org/xpra/blob/3803f14183e44d0cec197560c86357e234de48ca/xpra/x11/gtk_x11/world_window.py#L202

**Comment by matthewshawgr** [comment]
Hi, apologies for late reply, I wont be allowed to send logs out of my organisation. Apologise for wasting your time, feel free to close.

**Comment by totaam** [comment]
There are some focus related fixes in xpra v5:
* 90820ad90285dc454460cbe01c71a30fc0b1ea04 : you can run older versions of the xpra server with `XPRA_FORCE_XSETINPUTFOCUS=0` to get the same effect
* 7acc8283a337ac02480e59449a07dabd66146f56: fixes focus issues when windows disappear - this one will also land in xpra 4.4.5
