### ISSUE TITLE
Mouse cursor "hotspot" is always at the bottom left under Mac OS (M1)

### ISSUE THREAD

**Issue by aerusso** [Xpra-org/xpra#3840]
**Describe the bug**
The mouse cursor is unintuitive to use because the "hotspot" of the cursor is located in the bottom left.  The server is running Debian Linux 3.1.3, and connecting from a Linux client (also the same version) does not exhibit this problem.

As an aside, the cursor also sometimes is "stuck" in whatever mode it was right before moving into the xpra client window (often a horizontal or vertical resize cursor).  This seems to be temporarily fixed by disabling and re-enabling the "cursor" xpra client feature. (Though that might have just been because the cursor was able to be brought inside the client window because the menu happened to extend into the client window.)

**To Reproduce**
1. On Debian server: `xpra start-desktop :68 --daemon=no --systemd-run=no --start=startplasma-x11`
2. On Mac OS M1 client:  `xpra attach ssh://$user@$server/$DISPLAY`
3. Move the mouse into the window, and notice where the clicks register relative to the typical hotspot location.

**System Information (please complete the following information):**
 - Server OS: Debian 12
 - Client OS: Mac OS 13.2.1
 - Xpra Server Version 3.1.3
 - Xpra Client Version ?? Hopefully 3.1.3, but whatever is in the download link currently: | Xpra-x86_64.pkg | 2022-10-01 16:10 | 62M | [Xpra-x86_64.pkg](https://xpra.org/dists/MacOS/Xpra-x86_64.pkg)	2022-10-01 16:10 	62M

**Additional context**
My access the Mac client is limited, and I will absolutely be unable to compile anything on it for this task (unfortunately).

**Comment by totaam** [comment]
does this also happen with seamless sessions?
If you disable cursor forwarding, do the clicks land where they should?

3.1.3 is not the current version for Debian 12 - this probably won't fix things, but bug reports against this version will not be investigated
> Xpra Client Version ?? Hopefully 3.1.3, but whatever is in the download link currently

No. You don't want 3.1.3 and the link is definitely not to that ancient version.
The version is shown in the "About" dialog or from the command line with `./Xpra.app/Contents/MacOS/Xpra --version`.
(amongst many other ways.

FYI: I don't have an M1 or M2 system to test with.

**Comment by aerusso** [comment]
Client was 4.4.4, upgrading the server to 3.1.4 resolves the issue. Closing.
