### ISSUE TITLE
Issue with starting a new session on xpra

### ISSUE THREAD

**Issue by bishnoi29nitin** [Xpra-org/xpra#3844]
**Describe the bug**
I have just installed Xpra on linux machine. I was trying to start a session of xpra to check if it work and after the command an error showed up.

```
  1 2023-05-02 17:56:04,133 cannot access python uinput module:^[[0m
  2 2023-05-02 17:56:04,133  No module named uinput^[[0m
  3 xpra initialization error:
  4  failed to execute xvfb command ['Xvfb-for-Xpra-S151786', '-nolisten', 'tcp', '-noreset', '+extension', 'GLX', '+extension', 'Composite', '-auth', '/home/parade/.Xauthority    ', '-screen', '0', '7680x4320x24+32', '-displayfd', '8']: [Errno 9] Bad file descriptor
  5 xpra initialization error:
  6  Xvfb: did not provide a display number using displayfd
```

I have previous contacted you with some error and you have asked me to make changes to the file `/etc/xpra/conf.d/55_server_x11.conf` and remove the comment (#) in front of `xvfb = xvfb` and put comment in front of `xvfb = xdummy`.

which is did but which created more issues for me as before changing this I was able to create new session but there was no display on blue background was there on the browser and also I was not able to stop the session with the command 
`xpra stop`

Os details of the server 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

xpra version details:

`xpra v3.1.4-r3M`

As this is centos 7 so the xpra version installed on it is older version and I have used yum install xpra command for installation.

I am using the same machine as server and client so details for server and client are same.

**To Reproduce**
1. server command `xpra start --bind-tcp=0.0.0.0:5905 --html=on --start=xterm`
2. client command

**System Information (please complete the following information):**
 - Server OS: `[NAME="CentOS Linux" VERSION="7 (Core)"]`
 - Client OS: `[NAME="CentOS Linux" VERSION="7 (Core)"]`
 - Xpra Server Version `xpra v3.1.4-r3M`
 - Xpra Client Version `xpra v3.1.4-r3M`

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
> `Xvfb: did not provide a display number using displayfd`

Your Xvfb is so old that it probably does not support `displayfd`.
Try specifying the display to use:
```
xpra start --bind-tcp=0.0.0.0:5905 --html=on --start=xterm :100
```

> and you have asked me to make changes to the file

Where? Mailing list? Ticket?
Link please.

> I was able to create new session but there was no display on blue background was there on the browser

Those are words, but I don't know what it means. Perhaps a screenshot would help.
is `xterm` installed?

>  I was not able to stop the session with the command `xpra stop`

What was the error?
What was the output?
How about the server log?

**Comment by bishnoi29nitin** [comment]
Thank you for quick reply.

I have changed back to the using **xvfb = xpra_Xdummy** instead of using **xvfb = Xvfb -nolisten tcp -noreset**. With these changes I am able to create a new session with the command 
==>> xpra start --bind-tcp=0.0.0.0:5905 --html=on --start=xterm

and the output on running this command is as:

Entering daemon mode; any further errors will be reported to:
  /run/user/21040/xpra/S65914.log
Actual display used: :2
Actual log file name is now: /run/user/21040/xpra/:2.log

And When I open this on the browser only the blue screen appears nothing else.

For the **xpra stop** command.

xpra stop
Warning: server connection failure:
 server error
 error accepting new connection

this error appears.

Log file for this session == > /run/user/21040/xpra/:2.log

2023-05-03 14:59:36,170 created tcp socket '0.0.0.0:5905'^[[0m
  2 2023-05-03 14:59:36,173 cannot access python uinput module:^[[0m
  3 2023-05-03 14:59:36,173  No module named uinput^[[0m
  4 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
  5 _XSERVTransMakeAllCOTSServerListeners: server already running
  6 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
  7 _XSERVTransMakeAllCOTSServerListeners: server already running
  8 
  9 X.Org X Server 1.20.4
 10 X Protocol Version 11, Revision 0
 11 Build Operating System:  3.10.0-957.1.3.el7.x86_64
 12 Current Operating System: Linux mgmt01 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
 13 Kernel command line: BOOT_IMAGE=/vmlinuz-3.10.0-1160.el7.x86_64 root=/dev/mapper/os_vg-root ro spectre_v2=retpoline rd.lvm.lv=os_vg/root rd.lvm.lv=os_vg/swap rhgb quiet LAN    G=en_IN.UTF-8
 14 Build Date: 01 April 2020  05:04:29AM
 15 Build ID: xorg-x11-server 1.20.4-10.el7
 16 Current version of pixman: 0.34.0
 17     Before reporting problems, check http://wiki.x.org
 18     to make sure that you have the latest version.
 19 Markers: (--) probed, (**) from config file, (==) default setting,
 20     (++) from command line, (!!) notice, (II) informational,
 21     (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
 22 (++) Log file: "/run/user/21040/xpra/Xorg.S65914.log", Time: Wed May  3 14:59:36 2023
 23 (++) Using config file: "/etc/xpra/xorg.conf"
 24 (==) Using system config directory "/usr/share/X11/xorg.conf.d"
 25 2023-05-03 14:59:37,051 created unix domain socket '/run/user/21040/xpra/mgmt01-2'^[[0m
 26 2023-05-03 14:59:37,051 cannot create group socket '/run/xpra/mgmt01-2'^[[0m
 27 2023-05-03 14:59:37,051  [Errno 13] Permission denied^[[0m
 28 2023-05-03 14:59:37,059 created unix domain socket '/home/parade/.xpra/mgmt01-2'^[[0m
 29 ^[[33m2023-05-03 14:59:37,059 Warning: missing sound module^[[0m
 30 2023-05-03 14:59:37,445 pointer device emulation using XTest^[[0m
 31 2023-05-03 14:59:37,477 serving html content from '/usr/share/xpra/www'^[[0m
 32 2023-05-03 14:59:38,472 OpenGL is supported on display ':2'^[[0m
 33 2023-05-03 14:59:38,473  using 'llvmpipe (LLVM 7.0, 256 bits)' renderer^[[0m
 34 2023-05-03 14:59:38,715 D-Bus notification forwarding is available^[[0m
 35 ^[[31m2023-05-03 14:59:38,739 Error: webcam forwarding disabled:^[[0m
 36 ^[[31m2023-05-03 14:59:38,740  'module' object has no attribute 'PILLOW_VERSION'^[[0m
 37 ^[[33m2023-05-03 14:59:38,768 Warning: webcam forwarding is disabled^[[0m
 38 ^[[33m2023-05-03 14:59:38,768  the virtual video directory '/sys/devices/virtual/video4linux' was not found^[[0m
^[[33m2023-05-03 14:59:38,769  make sure that the 'v4l2loopback' kernel module is installed and loaded^[[0m
 40 2023-05-03 14:59:38,769 found 0 virtual video devices for webcam forwarding^[[0m
 41 2023-05-03 14:59:38,983 xpra is ready.^[[0m
 42 2023-05-03 14:59:38,985 xpra GTK2 X11 version 3.1.4-r3M 64-bit^[[0m
 43 2023-05-03 14:59:39,020  uid=21040 (parade), gid=21054 (parade)^[[0m
 44 2023-05-03 14:59:39,020  running with pid 65928 on Linux CentOS Linux 7.9.2009 Core^[[0m
 45 2023-05-03 14:59:39,021  connected to X11 display :2 with 24 bit colors^[[0m
 46 2023-05-03 14:59:43,576 printer forwarding enabled using postscript and pdf^[[0m
 47 2023-05-03 14:59:43,648 started command 'xterm' with pid 66027^[[0m
 48 2023-05-03 14:59:43,739 watching for applications menu changes in:^[[0m
 49 2023-05-03 14:59:43,740  '/usr/local/share/applications'^[[0m
 50 2023-05-03 14:59:43,740  '/usr/share/applications'^[[0m
 51 ^[[33m2023-05-03 14:59:43,741 Warning: cannot load menu data^[[0m
 52 ^[[33m2023-05-03 14:59:43,741  No module named xdg.Menu^[[0m
 53 ^[[33m2023-05-03 14:59:44,042 ffmpeg: vp8+webm encoding failed: could not open vp8+webm encoder context: Invalid argument^[[0m
 54 ^[[33m2023-05-03 14:59:44,082  cannot load enc_pillow (Pillow encoder):
 55 Traceback (most recent call last):
 56   File "/usr/lib64/python2.7/site-packages/xpra/codecs/loader.py", line 37, in codec_import_check
 57     __import__(top_module, {}, {}, [])
 58   File "/usr/lib64/python2.7/site-packages/xpra/codecs/pillow/__init__.py", line 35, in <module>
 59     PIL_VERSION = PIL.PILLOW_VERSION
 60 AttributeError: 'module' object has no attribute 'PILLOW_VERSION'^[[0m
 61 ^[[31m2023-05-03 14:59:44,094 Error importing nvjpeg encoder (enc_nvjpeg)^[[0m
 62 ^[[31m2023-05-03 14:59:44,095  libnvjpeg.so.11: cannot open shared object file: No such file or directory^[[0m
 63 2023-05-03 14:59:44,111 376.6GB of system memory^[[0m
 64 2023-05-03 15:02:24,110 New tcp connection received^[[0m
 65 2023-05-03 15:02:24,110  from '127.0.0.1:53268'^[[0m
 66 2023-05-03 15:02:24,110  on '0.0.0.0:5905'^[[0m
 67 2023-05-03 15:04:50,356 New unix-domain connection received^[[0m
 68 2023-05-03 15:04:50,356  on '/run/user/21040/xpra/mgmt01-2'^[[0m
 69 2023-05-03 15:04:50,359 Handshake complete; enabling connection^[[0m
 70 ^[[31m2023-05-03 15:04:50,427 server error processing new connection from Protocol(unix-domain socket:/run/user/21040/xpra/mgmt01-2): 'module' object has no attribute 'PILL    OW_VERSION'
 71 Traceback (most recent call last):
 72   File "/usr/lib64/python2.7/site-packages/xpra/server/server_core.py", line 1844, in call_hello_oked
 73     self.hello_oked(proto, packet, c, auth_caps)
File "/usr/lib64/python2.7/site-packages/xpra/server/server_base.py", line 362, in hello_oked
 75     cc_class = self.get_client_connection_class(c)
 76   File "/usr/lib64/python2.7/site-packages/xpra/server/server_base.py", line 384, in get_client_connection_class
 77     from xpra.server.source.client_connection import ClientConnection
 78   File "/usr/lib64/python2.7/site-packages/xpra/server/source/client_connection.py", line 31, in <module>
 79     from xpra.server.source.webcam_mixin import WebcamMixin
 80   File "/usr/lib64/python2.7/site-packages/xpra/server/source/webcam_mixin.py", line 10, in <module>
 81     from xpra.codecs.pillow.decoder import HEADERS, open_only
 82   File "/usr/lib64/python2.7/site-packages/xpra/codecs/pillow/__init__.py", line 35, in <module>
 83     PIL_VERSION = PIL.PILLOW_VERSION
 84 AttributeError: 'module' object has no attribute 'PILLOW_VERSION'^[[0m
 85 2023-05-03 15:04:50,430 Disconnecting client /run/user/21040/xpra/mgmt01-2:^[[0m
 86 2023-05-03 15:04:50,430  server error (error accepting new connection)^[[0m
 87 2023-05-03 15:04:51,294 New unix-domain connection received^[[0m
 88 2023-05-03 15:04:51,294  on '/run/user/21040/xpra/mgmt01-2'^[[0m
 89 2023-05-03 15:04:51,296 New unix-domain connection received^[[0m
 90 2023-05-03 15:04:51,296  on '/home/parade/.xpra/mgmt01-2'^[[0m
 91 ^[[31m2023-05-03 15:07:18,054 Error: tcp connection failed:^[[0m
 92 ^[[31m2023-05-03 15:07:18,055  packet from 127.0.0.1:55116^[[0m
 93 ^[[31m2023-05-03 15:07:18,055  received on 0.0.0.0:5905^[[0m
 94 ^[[31m2023-05-03 15:07:18,055  invalid packet header, SSL packet?^[[0m
 95 ^[[31m2023-05-03 15:07:18,085 Error: tcp connection failed:^[[0m
 96 ^[[31m2023-05-03 15:07:18,085  packet from 127.0.0.1:55120^[[0m
 97 ^[[31m2023-05-03 15:07:18,085  received on 0.0.0.0:5905^[[0m
 98 ^[[31m2023-05-03 15:07:18,085  invalid packet header, SSL packet?^[[0m
 99 2023-05-03 15:07:26,320 New tcp connection received^[[0m
100 2023-05-03 15:07:26,321  from '127.0.0.1:55166'^[[0m
101 2023-05-03 15:07:26,321  on '0.0.0.0:5905'^[[0m

Operating system == Linux CentOS Linux 7.9.2009 Core

**Comment by totaam** [comment]
Please learn to use markdown, having to edit your tickets to be able to read them is time consuming.

> I have changed back to the using `xvfb = xpra_Xdummy` instead of using `xvfb = Xvfb -nolisten tcp -noreset`.

Neither of these strings are valid.
Be precise.

> `60 AttributeError: 'module' object has no attribute 'PILLOW_VERSION'`

Make sure that you have `python2-pillow` installed.

> `invalid packet header, SSL packet?`

Your browser is trying to use `https` but your xpra server is not configured for `ssl`.
Tell your browser to use `http` or use the documentation to configure `ssl`.

**Comment by bishnoi29nitin** [comment]
Thank you for quick reply.

`xpra stop`

Error:
Warning: server connection failure:
 server error
 error accepting new connection

What about this error?

**Comment by totaam** [comment]
> Thank you for quick reply.
> 
> `xpra stop`
> 
> Error:
> Warning: server connection failure:
>  server error
>  error accepting new connection
> 
> What about this error?

The cause would be found in your server log

**Comment by bishnoi29nitin** [comment]
I am able to resolve the above mentioned Pillow library of the python and closing of the Xpra session. But still facing some issues.

Command to run xpra --> xpra start --ssl-cert=/path-to-certificate/xpra-ssl.cert --ssl=on --start=xterm

I have also created a proxy server,

command for creating proxy server--> sudo xpra proxy :100 --wss-auth=pam --bind-wss=0.0.0.0:5905 --ssl-cert=/path-to-certificate/xpra-ssl.cert --ssl=on

After running the first command, I am still having only the blue screen is appearing not the xterminal as expected.

the log file is:

 1  2023-06-05 17:42:22,077 cannot access python uinput module:^[[0m
  2 2023-06-05 17:42:22,077  No module named uinput^[[0m
  3 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
  4 _XSERVTransMakeAllCOTSServerListeners: server already running
  5 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
  6 _XSERVTransMakeAllCOTSServerListeners: server already running
  7 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
  8 _XSERVTransMakeAllCOTSServerListeners: server already running
  9 _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
 10 _XSERVTransMakeAllCOTSServerListeners: server already running
 11 2023-06-05 17:42:22,406 created unix domain socket '/run/user/21040/xpra/mgmt01-4'^[[0m
 12 2023-06-05 17:42:22,407 cannot create group socket '/run/xpra/mgmt01-4'^[[0m
 13 2023-06-05 17:42:22,407  [Errno 13] Permission denied^[[0m
 14 2023-06-05 17:42:22,416 created unix domain socket '/home/parade/.xpra/mgmt01-4'^[[0m
 15 ^[[33m2023-06-05 17:42:22,417 Warning: missing sound module^[[0m
 16 2023-06-05 17:42:22,513 pointer device emulation using XTest^[[0m
 17 2023-06-05 17:42:22,534 serving html content from '/usr/share/xpra/www'^[[0m
 18 2023-06-05 17:42:23,435 OpenGL is supported on display ':4'^[[0m
 19 2023-06-05 17:42:23,435  using 'llvmpipe (LLVM 7.0, 256 bits)' renderer^[[0m
 20 2023-06-05 17:42:23,492 D-Bus notification forwarding is available^[[0m
 21 ^[[33m2023-06-05 17:42:23,608 Warning: webcam forwarding is disabled^[[0m
 22 ^[[33m2023-06-05 17:42:23,608  the virtual video directory '/sys/devices/virtual/video4linux' was not found^[[0m
 23 ^[[33m2023-06-05 17:42:23,609  make sure that the 'v4l2loopback' kernel module is installed and loaded^[[0m
 24 2023-06-05 17:42:23,609 found 0 virtual video devices for webcam forwarding^[[0m
 25 2023-06-05 17:42:23,745 xpra is ready.^[[0m
 26 2023-06-05 17:42:23,747 xpra GTK2 X11 version 3.1.4-r3M 64-bit^[[0m
 27 2023-06-05 17:42:23,773  uid=21040 (parade), gid=21054 (parade)^[[0m
 28 2023-06-05 17:42:23,774  running with pid 87192 on Linux CentOS Linux 7.9.2009 Core^[[0m
 29 2023-06-05 17:42:23,774  connected to X11 display :4 with 24 bit colors^[[0m
 30 2023-06-05 17:42:27,287 printer forwarding enabled using postscript and pdf^[[0m
 31 2023-06-05 17:42:27,300 started command 'xterm' with pid 87368^[[0m
 32 2023-06-05 17:42:27,399 watching for applications menu changes in:^[[0m
 33 2023-06-05 17:42:27,400  '/usr/local/share/applications'^[[0m
 34 2023-06-05 17:42:27,400  '/usr/share/applications'^[[0m
 35 ^[[33m2023-06-05 17:42:28,629 ffmpeg: vp8+webm encoding failed: could not open vp8+webm encoder context: Invalid argument^[[0m
 36 ^[[31m2023-06-05 17:42:28,646 Error importing nvjpeg encoder (enc_nvjpeg)^[[0m
 37 ^[[31m2023-06-05 17:42:28,646  libnvjpeg.so.11: cannot open shared object file: No such file or directory^[[0m
 38 2023-06-05 17:42:28,650 376.6GB of system memory^[[0m

Please help me with this. Thank you

**Comment by totaam** [comment]
> I am able to resolve the above mentioned Pillow library of the python and closing of the Xpra session. But still facing some issues.

You haven't explained all the errors that you've hit before or how you resolved them, which is making it more difficult to help you.

> I have also created a proxy server,

How is this relevant to your blue screen issue?
Keep it simple, don't use the proxy until things are working.

> `376.6GB of system memory`

Is this a typo?

Are you connecting using the html5 client?
If so, what version?
Does it work with the python client?

**Comment by bishnoi29nitin** [comment]
Thank you for quick reply.
 
I used the proxy server because you have mentioned that 

> Your browser is trying to use https but your xpra server is not configured for ssl.

> Tell your browser to use http or use the documentation to configure ssl.

But even I have tried with the command --> xpra start --bind-tcp=0.0.0.0:5906 --html=on --start=xterm

the blue screen was still there no terminal was visible.

Below mentioned are the version installed on my system.

python2-pyopengl-3.1.6-1xpra1.el7.x86_64
python2-xpra-3.1.4-10.32991xpra1.el7.x86_64
xpra-3.1.4-10.32991xpra1.el7.x86_64
python2-rencode-1.0.6-11.xpra2.el7.x86_64
ffmpeg-xpra-5.1.2-1.el7.x86_64
xpra-common-server-3.1.4-10.32991xpra1.el7.noarch
xpra-common-3.1.4-10.32991xpra1.el7.noarch
xpra-common-client-3.1.4-10.32991xpra1.el7.noarch
xpra-html5-5.1-1.r3.el7.noarch
pygtkglext-1.1.0-31.xpra2.el7.x86_64
libvpx-xpra-1.11.0-1.el7.x86_64
python2-xpra-client-3.1.4-10.32991xpra1.el7.x86_64
x264-xpra-20220602-1.el7.x86_64
libwebp-xpra-1.2.1-1.el7.x86_64
python2-xpra-server-3.1.4-10.32991xpra1.el7.x86_64

As my os is Operating system == Linux CentOS Linux 7.9.2009 Core, the xpra v3.1.4-r3M version got installed by the command yum install xpra.

I am using one machine which is working for me as server as well as client. sorry but I don't know how to check html5 client or python client. Could you please guide me how to check these things.

**Comment by totaam** [comment]
> I used the proxy server because you have mentioned that
> (..)

Then instead of using a proxy, configure your server to use SSL.
> Command to run xpra --> `xpra start --ssl-cert=/path-to-certificate/xpra-ssl.cert --ssl=on --start=xterm`

That won't do it since you are not defining any tcp or ssl sockets.

> the blue screen was still there no terminal was visible.

How did you connect then? 

> sorry but I don't know how to check html5 client or python client

I mean connect with both of them.
If the problem occurs with both then the problem is likely server side.

> > 376.6GB of system memory
>
> Is this a typo?

Not answered.

Does `xpra info` show the xterm window?
Does `xpra screenshot :$DISPLAY screenshot.png` give you a valid screenshot file?

**Comment by totaam** [comment]
> The memory have something to do with xpra.

Well, a system with 376GB of memory is going to be unusual, when that happens there are going to be other things that are unusual.

> `xpra info | grep xterm`

This should have given you:
```
windows.1.class-instance=('xterm', 'XTerm')
windows.1.command=/usr/bin/xterm
```
So my guess is that `xterm` is not installed properly or that it terminated for some other reason.
Try running it from another terminal: `DISPLAY=:4 xterm`.

> `xpra screenshot :4 screenshot.png`
> (..)

I gave the wrong syntax, try:
```
xpra screenshot screenshot.png :4
```

**Comment by bishnoi29nitin** [comment]
Thank you for replying.

> xpra screenshot screenshot.png :4

```
xpra screenshot screenshot.png :4
screenshot is empty and has not been saved (maybe there are no windows or they are not currently shown)

```

> So my guess is that xterm is not installed properly or that it terminated for some other reason.
Try running it from another terminal: DISPLAY=:4 xterm.

I tried opening the xterm through command line only without xpra, it is working. The terminal opened instantly. 

> xpra info | grep xterm

```
child.command=('xterm',)
child.name=xterm
**commands.command=('xterm',)**
commands.name=xterm
commands.start=('xterm',)
env.TERM=xterm-256color
server.argv=('/usr/bin/xpra', 'start', '--ssl-cert=/usr/share/xpra/www/xpra-ssl.cert', '--ssl=on', '--start=xterm')
session.name=xterm
**windows.1.class-instance=('xterm', 'XTerm')**

```

Shouldn't the bold one be same as the output you have shared.

Question: Does Xpra uses cuda libraries for the GUI?

Thank you.

**Comment by totaam** [comment]
`--start=xterm` and doing `DISPLAY=:VALUE xterm` later should give you the same behaviour.
My guess is that something is messed up with your server environment.

> Question: Does Xpra uses cuda libraries for the GUI?

It depends on the version. 3.x does not.
