### ISSUE TITLE
Expired key for xpra on May 5th 2023

### ISSUE THREAD

**Issue by ccarballido** [Xpra-org/xpra#3847]
**Describe the bug**
The key under [https://xpra.org/gpg.asc ](https://xpra.org/gpg.asc) expired today

**To Reproduce**
![image](https://user-images.githubusercontent.com/83603980/236516144-668eff7b-0403-454a-928d-a3938424fcfd.png)

**System Information (please complete the following information):**
 - Client OS: Ubuntu focal

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Looks like a duplicate of #3846.

Please try again, the symlink now points to the newer key, aka `gpg-2022.asc`.

**Comment by ccarballido** [comment]
It works now.

**Comment by totaam** [comment]
Reference GPG ticket is #3863
