### ISSUE TITLE
Side mouse buttons don't work on Windows

### ISSUE THREAD

**Issue by dgl** [Xpra-org/xpra#3855]
When pressing the side button of a mouse from a Windows client to a Linux server, `xev` reports the button number as 4 or 5, rather than the expected 8 or 9.

```
ButtonPress event, serial 36, synthetic NO, window 0xc00001,
    root 0x50d, subw 0x0, time 166950704, (0,104), root:(618,404),
    state 0x10, button 4, same_screen YES

ButtonRelease event, serial 36, synthetic NO, window 0xc00001,
    root 0x50d, subw 0x0, time 166950840, (0,104), root:(618,404),
    state 0x810, button 4, same_screen YES
```

**To Reproduce**
1. Run a server on Linux (X11), e.g. with xterm, run `xev` inside it, so you can see the output.
2. Run a client on Windows.
3. Click a side mouse button (you obviously need a mouse with side buttons, many Logitech ones for example).

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04.
 - Client OS: Windows 10/11 (both tested)
 - Xpra Server Version: 4.4.4
 - Xpra Client Version: 4.4.4

**Additional context**

Gtk passes these buttons as 4 and 5, per https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/win32/gdkevents-win32.c#L2181-2185 where `WM_XBUTTONDOWN` is the Win32 API for the "X" buttons. Whereas on X11 they are passed as 8 and 9, see https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/x11/gdkdevicemanager-xi2.c#L1635-1639 where button presses 4 to 7 are filtered out and become scroll events.

One interesting side effect of this behaviour is currently if you connect from Xpra on Win32 to a shadow server on Win32, the side buttons act as scroll wheels. I suspect it makes sense to make Xpra in the protocol treat the buttons as 8 and 9 too, then add additional mapping in the win32 shadow server but I haven't looked at that.

I'll open a proposed PR in a moment for fixing the client behaviour.

**Comment by dgl** [comment]
Yes, I think the PR I've opened it will do it.

**Comment by totaam** [comment]
@dgl I've just added the horizontal event hooks here: 6edf88fbe91dc2c77021de49a1afc1273c3f69c8
As was always intended (the function was defined but not actually getting called)
Is this going to interfere? Should I drop it?

**Comment by dgl** [comment]
@totaam Interestingly I can't actually see that code being reached (for me the horizontal scrolling in the client was working already, via GDK_SCROLL_MAP in gtk_client_window_base.py), when are these window hooks expected to apply?

**Comment by totaam** [comment]
Ah, I'll try to find time to play with this.
The [win32 window hooks](https://github.com/Xpra-org/xpra/blob/8a2dc78a2efe8d2f6823aed6de37227f400a9497/xpra/platform/win32/gui.py#L509) are added for all windows here:
https://github.com/Xpra-org/xpra/blob/8a2dc78a2efe8d2f6823aed6de37227f400a9497/xpra/client/gtk_base/gtk_client_window_base.py#L900
