### ISSUE TITLE
GPG key seems to be the wrong one

### ISSUE THREAD

**Issue by rrthomas** [Xpra-org/xpra#3858]
**Describe the bug**
Having downloaded the PGP key block `xpra.asc` file as instructed for Debian-based distros (Ubuntu 22.04 in my case), I get:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://xpra.org jammy InRelease: The following signatures were invalid: EXPKEYSIG 18ADB31CF18AD6BB Antoine Martin <antoine@nagafix.co.uk>
W: Failed to fetch https://xpra.org/dists/jammy/InRelease  The following signatures were invalid: EXPKEYSIG 18ADB31CF18AD6BB Antoine Martin <antoine@nagafix.co.uk>
```

**Additional context**
What is odd is that when I had this problem some weeks ago on another machine, I downloaded the file again and got a newer one (datestamp March 24th 2022). This appears to be the right one, as it contains the key referred to, whereas the file currently available does not.

**Comment by totaam** [comment]
Does this solve things: https://github.com/Xpra-org/xpra/issues/3846#issuecomment-1536559382

**Comment by rrthomas** [comment]
@totaam: thanks, the key seems to have been updated once more; did you do something? What I was trying to explain above is that when I downloaded the key about two weeks ago, I got the same key as now. But when I downloaded it two days ago, I got an older key.

**Comment by rrthomas** [comment]
Ah yes, thanks! So that means that the key has been updated, and this issue can be closed?

**Comment by totaam** [comment]
Different distribution releases require different keys.. so I have tried not to update existing files and change URLs to new ones instead, in the (perhaps foolish) hope that this would not break existing workflows.
