### ISSUE TITLE
'FakeClient' object has no attribute 'has_focus'

### ISSUE THREAD

**Issue by sbradnick** [Xpra-org/xpra#3860]
**Describe the bug**
Don't know if this is similar to #3477 / #3500 but I'm getting the message in the subject.

**To Reproduce**
Server: `xpra start --start=xterm --daemon=no --mdns=no --printing=no --speaker=no --webcam=no --bind-tcp=0.0.0.0:14500 --tcp-auth=u2f -d auth`
Client: `xpra attach tcp://<client dns entry>:14500`

**System Information (please complete the following information):**
 - Server OS: openSUSE Tumbleweed 20230522
 - Client OS: openSUSE Tumbleweed 20230522
 - Xpra Server Version: Using git 370947ed (20230523)
 - Xpra Client Version: Using git 370947ed (20230523)

**Additional context**
Can't seem to right-click on anything; I generally am using Evolution and a terminal and I can't right-click on emails to move them to different folders. This wasn't an issue as of f088bc04 (20230504)

**Comment by totaam** [comment]
The commit above should take care of this, but please always include the full backtrace if there is one.
This is all caused by the churn in #1995 (getting rid of GTK)

**Comment by sbradnick** [comment]
> The commit above should take care of this, but please always include the full backtrace if there is one.
> This is all caused by the churn in https://github.com/Xpra-org/xpra/issues/1995 (getting rid of GTK)

That did fix the error message, but left/right clicking is still behaving oddly. I also get a[nother] icon in my taskbar when I left/right click (in Evolution) that is basically a square; sometimes it has a little white triangle, facing down, sometimes not - depending on if it's a left-click or right-click - almost as if it's some type of toggle. The context menu(s) the left/right click would bring up don't show up.

**Comment by totaam** [comment]
That's all related to the changes in #1995, a fix is coming, just bear with me.

**Comment by sbradnick** [comment]
> That's all related to the changes in https://github.com/Xpra-org/xpra/issues/1995, a fix is coming, just bear with me.

I'm sorry, I completely misread "This is all caused by the churn in #1995 (getting rid of GTK)" as being specific to _that_ 'FakeClient' error message.

Thank you for the quick updates, fixes and dedication.
