### ISSUE TITLE
new gpg project key

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3863]
Seeing how many problems we have with the old expired GPG key: #3846, #3848, #3858, #3861

The best thing to do is probably to start with a brand new project key, instead of using my personal one.

This is going to be a pain, trying to figure out which distributions support what types of keys and subkeys is going to take time too.
(ie: Debian discarding the whole key if there is a `SHA1` signature in it instead of ignoring that signature.. why, oh why)

**Comment by totaam** [comment]
### Type of key

RedHat's [how to sign rpms with GPG](https://access.redhat.com/articles/3359321) documentation is very poor and does not cover the types of keys or the use of subkeys at all: it only says _generate a gpg key pair on the machine_.
The [Debian packaging](https://www.debian.org/doc/manuals/securing-debian-manual/deb-pack-sign.en.html) uses `gpg` directly, so in theory it should be able to handle more (any?) types of key, though they did previously manage to make a mess of things by ignoring keys with SHA1 signatures instead of ignoring the signature! (#3446 - see also #3485)
MS Windows is also done by calling `gpg` directly and MacOS can be ignored since it doesn't use gpg (of course it doesn't): #2388

I wanted to use an `ecc` key with a signing-only subkey, unfortunately RPM only supported `RSA` (and legacy `DSA`) keys until very recently (2021): https://github.com/rpm-software-management/rpm/commit/23770e1a4f28c56a31fe600cae332c77333b60b6
Full list of supported key formats found in the `rpm` source code here:
https://github.com/rpm-software-management/rpm/blob/26d3802390602c6aadc523bfb84426914c8fa050/sign/rpmgensig.c#L157-L165

As for subkeys, [Pitfalls with RPM and GPG](https://technosorcery.net/blog/2010/10/pitfalls-with-rpm-and-gpg/) states that _Your key cannot have any sub-keys_.
Also _You must generate the RPM with a V3 GPG signature (CentOS 5.5 can't verify V4 signatures)_, but since we don't care about CentOS 5, 6 or even 7, can we avoid using this nasty gpg command line that RedHat recommends?
```
%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --verbose --no-armor \
   --passphrase-fd 3 --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}'
```
Is this still relevant in 2023? Who knows. Can we use `sha512`? Not documented either.
[this ticket](https://bugzilla.redhat.com/show_bug.cgi?id=436812#c32) says that _Fixed upstream now (by just ignoring subkeys)_
Can we, or can't we?

Fun read: [It's a cluster of RPM bugs](https://serverfault.com/a/624910/63324): _Not just one bug, or two bugs. A nest of the critters. RPM fails (failed?) to validate signed packages, didn't understand v4 GPG signatures but didn't notice it didn't understand them, didn't understand some key sizes and types but didn't notice it didn't understand that, and also choked on subkeys!_
That doesn't exactly inspire confidence. So, no subkeys then.

### Size of key
Hopefully, all the package validation tools can handle 4096 bits nowadays - that was not always the case!

### Expiry
10 years to avoid having to go through this pain again.

### Result:
Using a `(4) RSA (sign only)`, 4096 bits, 10 year expiry key for `xpra@xpra.org`:
```
pub   rsa4096/0x73254CAD17978FAF 2023-06-10 [SC] [expires: 2033-06-07]
      Key fingerprint = B499 3B57 3231 48E3 7977  E5D8 7325 4CAD 1797 8FAF
uid                              Xpra <xpra@xpra.org>
```
Use the "old" key to sign it with "ultimate trust":
```
gpg -u 0x18ADB31CF18AD6BB   --sign-key "Xpra <xpra@xpra.org>"
```

### Upload to key servers and `xpra.org`:
```shell
gpg --keyserver keyserver.ubuntu.com --send-keys  0x73254CAD17978FAF
gpg --keyserver pgp.mit.edu --send-keys  0x73254CAD17978FAF
```
The key can now be found on these keyservers:
https://keyserver.ubuntu.com/pks/lookup?search=0x73254CAD17978FAF&op=index
https://pgp.mit.edu/pks/lookup?search=0x73254CAD17978FAF&op=index

And now also at this URL:
https://xpra.org/xpra-2023.gpg

### Sign beta repositories
(on a remote host via ssh gpg agent forwarding)
* start the gpg agent pointing at this key:
```shell
gpg-agent --homedir /mnt/USB-GPG-KEY/.gnupg --use-standard-socket --daemon
```
* connect to the remote host with agent forwarding:
(remembering to add `no-autostart` to `gpg.conf`)

### Testing it
(in progress)
* Fedora:
Edit `/etc/yum.repos.d/xpra-beta.repo` to point to the new key.

* Debian Bookworm:
Download the new key and edit `/etc/apt/sources.list.d/xpra-beta.sources` to point to it.

So far, so good.
Next:
* updating the download wiki page
* making new stable releases using the new key

**Comment by totaam** [comment]
The MS Windows installer is now signed using a brand new key, generated as before using `makecert` as per [signing code using signtool](https://stackoverflow.com/a/201277/428751).
```shell
makecert.exe -r -pe -n "CN=Xpra,E=xpra@xpra.org" -ss CA -sr CurrentUser -a sha256 -cy authority -sky signature -sv xpra-ca.pvk xpra-ca.cer
certutil.exe -user -addstore Root xpra-ca.cer
makecert.exe -pe -n "CN=Xpra,E=xpra@xpra.org" -a sha256 -cy end  -sky signature -ic xpra-ca.cer -iv xpra-ca.pvk -sv xpra.pvk xpra.cer
```
And this new signing key expires in 2040:
```
The following certificate was selected:
    Issued to: Xpra
    Issued by: Xpra
    Expires:   Sun Jan 01 06:59:59 2040
    SHA1 hash: C59AEF9FC6E8BC8DA7750908DF653FBA0AFEA614

Done Adding Additional Store
Successfully signed: Xpra-Python3-x86_64_Setup_5.0-r33673.exe

Number of files successfully Signed: 1
Number of warnings: 0
Number of errors: 0
```
And the certificate files are now here:
* CA: [xpra-ca.cer](https://xpra.org/xpra-ca.cer)
* signing: [xpra.cer](https://xpra.org/xpra.cer)
To add this as a "Trusted Publisher":
```shell
certutil.exe -user -addstore Root xpra-ca.cer
```
(I couldn't figure out how to make it trust this CA only for installing software, either from the GUI or the command line)

**Comment by totaam** [comment]
For Debian / Ubuntu distributions using the old `/etc/apt/sources.list.d/xpra-beta.list` source file, use this command to add the new key:
```shell
wget -qO - https://xpra.org/xpra-2023.asc | sudo apt-key add -
```
If using the new `xpra-beta.sources` files, use this command to update the repository specific key:
```shell
sudo wget -O "/usr/share/keyrings/xpra-2023.asc" https://xpra.org/xpra.asc
```

**Comment by John-Ghra** [comment]
This still does not work.

**Comment by markmandel** [comment]
I believe the command should be:

```
sudo wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra-2023.asc
```

But can confirm that this did work for me! Huzzah!

**Comment by SkyperTHC** [comment]
reported in #3861, this is the cut & paste solution (as root):

```sh
bash -c '{ : \
		&& wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra-2023.asc \
		&& wget -O "/etc/apt/sources.list.d/xpra-beta.sources" https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/bookworm/xpra-beta.sources \
		&& apt-get update \
		&& pkg=("xpra" "xpra-html5") \
		&& { [[ $HOSTTYPE != aarch64 ]] && pkg+=("xpra-x11"); true; `### x86_64 only`;  } \
		&& apt-get install -y --no-install-recommends "${pkg[@]}" \
		&& rm -f /var/lib/apt/lists/xpra*; }'
```

**Comment by stdedos** [comment]
I am not sure if one should be "lightly" meddling with the internals of apt-get - _nor if we should recommend it_ 😕

The "average Joe's" way is documented in https://github.com/Xpra-org/xpra/wiki/Download (_I am just now updating it a little bit to match the transient nature of this ticket_)

**Comment by SkyperTHC** [comment]
> I am not sure if one should be "lightly" meddling with the internals of apt-get - _nor if we should recommend it_ 😕
> 
> The "average Joe's" way is documented in https://github.com/Xpra-org/xpra/wiki/Download (_I am just now updating it a little bit to match the transient nature of this ticket_)

The described way on xpra.org wont work on kali (pub key error), see #3861 . The only work-around atm seems to be to use the -beta branch. Would it make sense to describe on the webpage that the default branch is not working and that only the -beta branch works for the time being?

**Comment by totaam** [comment]
I have been on the brink of deploying the new GPG key to all the repos for a while. This will finally include the stable repo since the deployment seems to have gone well. (ignoring "it doesn't work" type of messages which are unactionable)
I will not be re-signing ~100GB of older stable packages (for various reasons, not least of which security implications) - these will be moved to an archive area and eventually to an offline backup.

So, to get there, I still need to:
* release 3.1.5
* release 4.4.6
* release new versions of the html5 client from each supported branch
To do that, I have to first test as many combinations as possible (including 5.0 beta) on as many platforms as possible, with as many browsers as possible.

Each one of these steps can take many days. For a start, doing a full build from a single branch takes multiple days - even on the new hardware VPO has provided - and when things go wrong, and they invariably do, then I have to start again.
I am skipping over all the other daily tasks that aren't going to wait just because people think their problem is more important: renewing hosting, check, renewing SSL certificates, check, backups, check, storm caused power cut, check.. and many many more

---

I'm also keenly aware that a number of other projects / organizations are relying on the xpra repositories. The constant stream of complaints about the GPG key was an eye opener.
Funny that, because when it comes to supporting the project, financially or otherwise, the silence has been deafening.

This is making me seriously re-consider the way this project is managed and in particular, my role in it.
Perhaps now would be a good time to move on.

**Comment by stdedos** [comment]
> This is making me seriously re-consider the way this project is managed and in particular, my role in it.
> Perhaps now would be a good time to move on.

🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 🕯️ 

It could be. If your labor is only appreciated by words, and "projects / organizations" are not willing to step in (but are willing to "cash in") ... maybe you should not torture yourself. 🥲

**Comment by markmandel** [comment]
> This is making me seriously re-consider the way this project is managed and in particular, my role in it.
Perhaps now would be a good time to move on.

Uh. OSS Maintainer burnout sucks. I'm sorry. Just letting you know that I love this project and promote it wherever I go. Please find a maintainable pace for yourself.

From my perspective -- as long as there is a documented way for me to install xpra from the repos, I'm good. I don't care if I have to switch approaches every so often as things change. It's free software, that's the price of doing business.

Also, thanks for jumping on getting these fixes in etc. It really is appreciated.

Also, I don't know if it helps, but is there a way we could push testing down to the community - at least some?

**Comment by totaam** [comment]
It's all live:
https://lists.devloop.org.uk/pipermail/shifter-users/2023-June/002981.html

**Comment by DiagonalArg** [comment]
There are two ways to do this on Ubuntu, and I can confirm both work in 22.04:

```
$ sudo wget -O "/etc/apt/trusted.gpg.d/xpra-2023.gpg" https://xpra.org/xpra-2023.gpg

$ cat /etc/apt/sources.list.d/xpra.list 
deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/xpra-2023.gpg] https://xpra.org/ jammy main
```

```
$ wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra-2023.asc
$ cat /etc/apt/sources.list.d/xpra.list 
deb [arch=amd64] https://xpra.org/ jammy main
```

**Comment by DiagonalArg** [comment]
> managed



> This is making me seriously re-consider the way this project is managed and in particular, my role in it.
> Perhaps now would be a good time to move on.

I'm just an individual occasionally using xpra at home, but if there were an obvious way to do it, I'd buy you a coffee occasionally.  Put it on the xpra.org webpage?  If you've got a budget, you might also put a little thermometer indicating how much you need.

**Comment by DiagonalArg** [comment]
Additionally, I have no interest in linking my identity and interests for Microsoft.
