### ISSUE TITLE
xpra initialization error:  connection failed: 'canonicaldomains'

### ISSUE THREAD

**Issue by monperrus** [Xpra-org/xpra#3868]
**Describe the bug**
cannot start xpra

```
$ xpra start ssh://server/ --start=xterm
2023-05-27 16:48:07,700 Xpra GTK3 X11 client version 4.4.5-r0 64-bit
2023-05-27 16:48:07,807  running on Linux Ubuntu 22.04 jammy
2023-05-27 16:48:07,808  window manager is 'Openbox'
2023-05-27 16:48:08,485 GStreamer version 1.20.3
2023-05-27 16:48:08,513 created unix domain socket '/run/user/1001/xpra/clients/beethoven-74861'
xpra initialization error:
 connection failed: 'canonicaldomains'
```

**To Reproduce**
`xpra start ssh://server/ --start=xterm`

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22 
 - Client OS: Ubuntu 22
 - Xpra Server Version 4.4.5
 - Xpra Client Version 4.4.5

**Comment by totaam** [comment]
`canonicaldomains` is not part of the xpra source code.
Try running with `-d all` to get more details.

**Comment by monperrus** [comment]
fixed it with `--ssh=ssh`

    xpra start ssh://server/ --start=xterm --ssh=ssh

thanks @totaam

**Comment by totaam** [comment]
@monperrus please include the details so that we can fix whatever problem there is with the `paramiko` backend.

**Comment by monperrus** [comment]
The reason is the use of virtual name in `.ssh/config`:

```
Host foobar
   HostName realdnsname
```

In that case, xpra does not like `xpra ssh://foobar`

**Comment by totaam** [comment]
Ubuntu ships with [python3-paramiko 2.9.3](https://packages.ubuntu.com/jammy/python3-paramiko) and it should support `.ssh/config`.

I tested this on Fedora 37 by adding to my `.ssh/config` :
```
Host l
	HostName localhost
```
Then connecting with `xpra attach ssh://l/ worked just fine here.
With `-d ssh`, I see:
```
parsed user config '/home/antoine/.ssh/config'
got host config for 'l': {'controlmaster': 'auto', 'controlpath': '~/.ssh/__tmp-ssh-antoine@localhost:22', 'hostname': 'localhost', 'stricthostkeychecking': 'no', 'userknownhostsfile': '/dev/null'}
```

**Comment by totaam** [comment]
Ubuntu ships with [python3-paramiko 2.9.3](https://packages.ubuntu.com/jammy/python3-paramiko) and it should support `.ssh/config`.

I tested this on Fedora 37 by adding to my `.ssh/config` :
```
Host l
	HostName localhost
```
Then connecting with `xpra attach ssh://l/ worked just fine here.
With `-d ssh`, I see:
```
parsed user config '/home/antoine/.ssh/config'
got host config for 'l': {'controlmaster': 'auto', 'controlpath': '~/.ssh/__tmp-ssh-antoine@localhost:22', 'hostname': 'localhost', 'stricthostkeychecking': 'no', 'userknownhostsfile': '/dev/null'}
```

**Comment by monperrus** [comment]
I also have `[python3-paramiko 2.9.3](https://packages.ubuntu.com/jammy/python3-paramiko)`

with `-d ssh`, I have 

```
2023-05-28 19:29:14,481 parsed user config '/home/martin/.ssh/config'
2023-05-28 19:29:14,481 45 hosts found
```

but no `got host config for 'l'`.

it seems there  is a bug in the ssh config parser

**Comment by totaam** [comment]
> I also have python3-paramiko 2.9.3

I don't. I was stating what is in Ubuntu 22.04
I use Fedora 37 which has paramiko 2.12.0

Since then, I have tried it on Ubuntu 22.04 and it also works fine there.

**Comment by monperrus** [comment]
Made progress. The bug happens when you add `CanonicalizeHostname always` as top level config for all hosts, at the top of `.ssh/config`

**Comment by totaam** [comment]
The full backtrace is:
```
2023-05-29 17:44:48,055 failed to connect
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/scripts/main.py", line 940, in connect_or_fail
    return connect_to(display_desc, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/scripts/main.py", line 1038, in connect_to
    conn = connect_to(display_desc)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/ssh/paramiko_client.py", line 224, in connect_to
    host_config = ssh_lookup(host)
                  ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/ssh/paramiko_client.py", line 207, in ssh_lookup
    return safe_lookup(ssh_config, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/net/ssh/paramiko_client.py", line 161, in safe_lookup
    return config_obj.lookup(host) or {}
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/config.py", line 236, in lookup
    domains = options["canonicaldomains"].split()
              ~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'canonicaldomains'
```
Looks like a bug in paramiko: if `CanonicalizeHostname` is set then `canonicaldomains` must be set.
The commit above will handle this slightly more gracefully, logging a more useful message, but it will still fail.

This patch makes paramiko handle missing `canonicaldomains` without blowing up with a `KeyError`:
```diff
--- a/paramiko/config.py
+++ b/paramiko/config.py
@@ -233,7 +233,7 @@
         if canon and hostname.count(".") <= maxdots:
             # NOTE: OpenSSH manpage does not explicitly state this, but its
             # implementation for CanonicalDomains is 'split on any whitespace'.
-            domains = options["canonicaldomains"].split()
+            domains = options.get("canonicaldomains", "").split()
             hostname = self.canonicalize(hostname, options, domains)
             # Overwrite HostName again here (this is also what OpenSSH does)
             options["hostname"] = hostname
```

**Comment by totaam** [comment]
Sent upstream: https://github.com/paramiko/paramiko/commit/1e5070936aff684852d115a39e5834809d09bc90

**Comment by totaam** [comment]
f171805662d46d115a6d524a8bd2d423041bfd64 simply duplicates the whole paramiko `lookup` method to apply the trivial change ourselves.
At least the ugly warning is gone and `canonicaldomains` should work.

**Comment by totaam** [comment]
Fixup in 61d960072ca637322c94b38967a048ab635a0455 for older versions of paramiko.
