### ISSUE TITLE
xpra ram memory footprint

### ISSUE THREAD

**Issue by monperrus** [Xpra-org/xpra#3869]
**Describe the bug**
xpra is the process that consumes the most ram on my server

```
$ ps aux --sort -rss
ubuntu      4067  4.2 50.4 3332076 2017916 ?     SLl  May27  31:31 /usr/bin/python3 /usr/bin/xpra start --xvfb=Xvfb -screen 0 2000x1000x24+32 -dpi 16 -nolisten tcp -noreset -auth $XAUTHORITY
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22
 - Client OS: Ubuntu 22
 - Xpra Server Version 4.4.5
 - Xpra Client Version 4.4.5

Is that normal? Are there workarounds to reduce the memory footprint?

**Comment by totaam** [comment]
Is this initially or after some time?
This does look excessive. A normal server should use less than 0.5GB with mmap disabled.
RSS includes shared libraries.

Try turning off options, each subsystem you turn off will save some memory.
In particular, `--mmap=no`, all the codecs, etc.

For more information, see #1836, #1838, https://github.com/Xpra-org/xpra/issues/1662#issuecomment-765488913
