### ISSUE TITLE
Update documentation to use the new key

### ISSUE THREAD

**Issue by noamraph** [Xpra-org/xpra#3870]
**Describe the bug**
I encountered the same issue as https://github.com/Xpra-org/xpra/issues/3846#issuecomment-1536559382

According to the comment I linked, Perhaps the copy I copied and pasted should be changed to use the updated link, https://xpra.org/gpg.asc instead of https://xpra.org/xpra.asc.

**Comment by totaam** [comment]
All the documentation and download instructions are going to be updated to use the new key: #3863
