### ISSUE TITLE
Graphics acceleration not working through xpra opengl

### ISSUE THREAD

**Issue by nvaleryRR** [Xpra-org/xpra#3876]
When run on the host the command: 
 ```
user@test:~$ vglrun -d :1 /opt/VirtualGL/bin/glxspheres64
We get a very quickly changing picture and results:
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x10d (8/8/8/0)
Visual ID of window: 0x21
Context is Direct
**OpenGL Renderer: NVIDIA GeForce GT 720/PCIe/SSE2**
159.700289 frames/sec - 178.225522 Mpixels/sec
161.152225 frames/sec - 179.845883 Mpixels/sec
165.579489 frames/sec - 184.786709 Mpixels/sec
```
Then if we run the xpra session on display 0 and run the same test on the session display, we get a much slower picture and very different results.
```
user@test:~$ vglrun -d :0 /opt/VirtualGL/bin/glxspheres64
Polygons in scene: 62464 (61 spheres * 1024 polys/spheres)
GLX FB config ID of window: 0x13c (8/8/8/0)
Visual ID of window: 0x21
Context is Direct
**OpenGL Renderer: llvmpipe (LLVM 15.0.6, 256 bits)**
35.062036 frames/sec - 39.129233 Mpixels/sec
35.838274 frames/sec - 39.995514 Mpixels/sec
36.052739 frames/sec - 40.234856 Mpixels/sec
```
As a result, everything lags and slows down on the client, the speed and quality settings do not improve the situation (they can only make it worse). 
What am I doing wrong? It seems that the reason is in this llvmpipe, but I have not yet found what to do with it...
```
Server OS: Ubuntu 22.04
Client OS: Windows 10
Xpra Server Version 4.4.5-r0-1
Xpra Client Version 4.4.5
```

**Comment by nvaleryRR** [comment]
Apparently I did not correctly describe what is happening.

So - one machine is a host. Run the following command on the host:
xpra start :3 --start-child="vglrun -d :3 /opt/VirtualGL/bin/glxspheres64"

then, on the same host from another terminal window, do:

xpra attach :3

We see that the number of frames per second is very small.
35.062036 frames/sec

if run:
xpra opengl

We see the following errors:
error='FakeClient' object has no attribute 'has_focus'
message='FakeClient' object has no attribute 'has_focus'
success=False

**Comment by totaam** [comment]
Like I said before:
> Your vglrun command line is wrong.

You have to point to an accelerated display, not the same that xpra is running on, which is not accelerated.

> We see that the number of frames per second is very small.

How? Where?
Server side I would assume?

> We see the following errors:

This is completely unrelated to `vglrun`: #3860
It means that unless you specify `--opengl=force` on the client, then opengl won't be used there, which will slow down the performance of the client.
