### ISSUE TITLE
Missing Sec-WebSocket-Key header

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#3877]
Sorry I don't know if this problem concerns xpra or xpra-html5.

I'm on commit c4a31c32e25e96fdf34ac09179a7be5bcaf73909 of xpra and [cd0de67](https://github.com/Xpra-org/xpra-html5/commit/cd0de67cbf9dbb13cf7dfbf2a23945c1c4ea6b10) of xpra-html5 both compiled as debian packages on Ubuntu 20.04.

When I try to access the html5 client with Chrome it fails with this in the logs:
```
2023-05-31 15:46:53,125 Error: cannot handle websocket upgrade:
2023-05-31 15:46:53,125  Missing Sec-WebSocket-Key header
2023-05-31 15:46:53,125 code 403, message failed to handle websocket: Missing Sec-WebSocket-Key header
````

This error wasn't present on commit c65e72fd17cf07534cd6c771696c4b696df65633 of xpra and commit [e7d1a6e](https://github.com/Xpra-org/xpra-html5/commit/e7d1a6efbdc0b7e37d8c0eb3452d6ac662fd604e) of xpra-html5.

Let me know if you need any other info. Thanks for the help.

**Comment by totaam** [comment]
Thanks for pointing that out, the commit above fixes that.

**Comment by iDmple** [comment]
Thank you so much!!!
