### ISSUE TITLE
Client causes high CPU and memory usage in GNOME 44 gnome-shell

### ISSUE THREAD

**Issue by taranu** [Xpra-org/xpra#3880]
**Describe the bug**
Compiled xpra client under GNOME 44 causes high CPU and memory usage (probably a leak) in GNOME 44 gnome-shell

**To Reproduce**
1. Start client with at least one window open and use it for a few minutes.
2. Client system gnome-shell cpu usage grows to 5-10% and memory usage keeps increasing (can be as much as 1GB in a few seconds)

**System Information (please complete the following information):**
 - Server OS: [Fedora 36 Workstation]
 - Client OS: [Fedora 38 Workstation]
 - Xpra Server Version [5.0-r33131 (gd1c801062) beta]
 - Xpra Client Version [5.0-r33131 (gd1c801062) beta]

**Additional context**
This problem does not occur with Fedora 38's packaged xpra v4.4.3, but does occur with self-compiled v4.4.3, v4.4.4, as well as the v4.4.4 provided in conda-forge. I tried compiling within a conda env and using Fedora-provided libraries with the same result.

I tried disabling all GNOME extensions on the client but that made no difference. The gnome-shell memory usage persists after the xpra client is shut down and even after user logout. Performance is sluggish too while the client is running, although I don't know how much of that is xpra itself or GNOME going haywire.

The only suspicious messages I saw in the client log were a few of these (not in v4.4.3, but in 4.4.4 and 5.0 beta):
```
2023-06-02 14:26:47,395 failed to set window metadata to 'typedict({'x11-property': ('_MOTIF_WM_HINTS', '', 0, '')})'
Traceback (most recent call last):
  File "/home/taranu/mambaforge/envs/xpra/lib/python3.11/site-packages/xpra-5.0-py3.11-linux-x86_64.egg/xpra/client/gui/client_window_base.py", line 283, in update_metadata
    self.set_metadata(metadata)
  File "/home/taranu/mambaforge/envs/xpra/lib/python3.11/site-packages/xpra-5.0-py3.11-linux-x86_64.egg/xpra/client/gui/client_window_base.py", line 549, in set_metadata
    self.set_x11_property(*metadata.tupleget("x11-property"))
TypeError: GTKClientWindowBase.set_x11_property() takes from 2 to 4 positional arguments but 5 were given
```
As well as several instances of this message:
```
2023-06-02 14:26:42,399 UI thread is now blocked
2023-06-02 14:26:43,197 UI thread is running again, resuming
```
I'd investigate further but am unsure where else to look.

**Comment by totaam** [comment]
> `failed to set window metadata to..`

Thanks, that's fixed in a6e41eecec300a7d2ffbf36ca785bc6026e8264f

> `Fedora 36 Workstation`

That's been EOLed: https://docs.fedoraproject.org/en-US/releases/eol/

> Client system gnome-shell cpu usage grows to 5-10% and memory usage keeps increasing

5-10% background activity can be explained in a number of ways:
* speaker forwarding - try turning that off
* some applications may update the screen unnecessarily (even if nothing actually changes visually in their window)

Try turning off as many features as you can until you identify the subsystem that has the leak.
ie: `clipboard`, `opengl`, etc..

> This problem does not occur with Fedora 38's packaged xpra v4.4.3

The current version in the repository is 4.4.5

> but does occur with self-compiled v4.4.3, v4.4.4, as well as the v4.4.4 provided in conda-forge

My guess is that a codec is enabled or disabled in one of those builds, and that triggers this behaviour.

> The gnome-shell memory usage persists after the xpra client is shut down and even after user logout

Well that would be a `gnome-shell` bug then.
All the memory that xpra uses will be reclaimed by the OS when the process is terminated.

> UI thread is now blocked

This indicates that the OS is not servicing our GUI thread fast enough - for whatever reason.
A severe lack of memory can cause this problem.

**Comment by taranu** [comment]
> > `Fedora 36 Workstation`
> 
> That's been EOLed: https://docs.fedoraproject.org/en-US/releases/eol/

Indeed. I have since upgraded to 38. I don't think the server was at fault, though.

> > This problem does not occur with Fedora 38's packaged xpra v4.4.3
> 
> The current version in the repository is 4.4.5

4.4.5 was only available in testing at the time, but I installed it and it seems to be fine (as is 4.4.6 which is now in testing).

> > but does occur with self-compiled v4.4.3, v4.4.4, as well as the v4.4.4 provided in conda-forge
> 
> My guess is that a codec is enabled or disabled in one of those builds, and that triggers this behaviour.

That seems likely. The list of codecs enabled between the Fedora versions and compiled 5.0+ is quite different.

> > The gnome-shell memory usage persists after the xpra client is shut down and even after user logout
> 
> Well that would be a `gnome-shell` bug then. All the memory that xpra uses will be reclaimed by the OS when the process is terminated.

That also seems likely, though also rather concerning for gnome-shell. At any rate, I'm not sure if I'll be able to find the culprit anytime soon, but if anyone else runs into the same problem, I hope this issue is helpful.

**Comment by totaam** [comment]
> That seems likely. The list of codecs enabled between the Fedora versions and compiled 5.0+ is quite different.

Most downstream builds are known to enable the wrong codecs: https://github.com/Xpra-org/xpra/wiki/Distribution-Packages
