### ISSUE TITLE
'utf-8' codec can't decode byte 0xd5 in position 931:invalid continuation byte

### ISSUE THREAD

**Issue by foryoung2018** [Xpra-org/xpra#3881]
i use ubuntu, xpra server

window client connect to, produce below error:

'utf-8' codec can't decode byte 0xd5 in position 931:invalid continuation byte

**Comment by totaam** [comment]
You haven't specified what version you are using, what commands, etc...
Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by rsromanovskiy** [comment]
Description: 
'utf-8' codec can't decode byte 0xcd in position 933:invalid continuation byte
position for version 4.4.5 931. for 4.4.6 933
try connect from windows client to linux server. by ssh connect succesful. xpra fail.
on linux locale utf-8. on windows10 chcp 65001 in cmd console before run xpra.exe doesnt effect.
[bugreport.zip](https://github.com/Xpra-org/xpra/files/11849826/bugreport.zip)

**Comment by totaam** [comment]
I have no idea what you mean or how to reproduce this bug.
What command lines?
What applications?
What text?
What is the output from `Xpra_cmd.exe`?

**Comment by rsromanovskiy** [comment]
at server:
@PC-CAD-16-Linux: xpra start --exit-with-children --start-child="/tools/Xilinx/Vivado/2021.2/bin/vivado"
Entering daemon mode; any further errors will be reported to:
  /run/user/1004/xpra/S664179.log
Actual display used: :1
Actual log file name is now: /run/user/1004/xpra/:1.log
xpra start --exit-with-children
@PC-CAD-16-Linux:~$ xpra list
Found the following xpra sessions:
/run/user/1004/xpra:
        LIVE session at :1
/home/rromanovsky/.xpra:
        LIVE session at :1

at client:
Xpra_cmd.exe attach ssh://pc-cad-16-linux/1
Warning: invalid option: 'audio'

2023-07-05 20:03:20,417 Xpra GTK3 client version 4.4.6-r29 64-bit
2023-07-05 20:03:20,461  running on Microsoft Windows 10
2023-07-05 20:03:23,004 xpra main error:
Traceback (most recent call last):
  File "E:/xpra/xpra/scripts/main.py", line 156, in main
  File "E:/xpra/xpra/scripts/main.py", line 465, in run_mode
  File "E:/xpra/xpra/scripts/main.py", line 509, in do_run_mode
  File "E:/xpra/xpra/scripts/main.py", line 1251, in run_client
  File "E:/xpra/xpra/scripts/main.py", line 1416, in get_client_app
  File "E:/xpra/xpra/scripts/main.py", line 1446, in get_client_gui_app
  File "E:/xpra/xpra/scripts/main.py", line 1723, in make_client
  File "E:/xpra/xpra/scripts/main.py", line 1638, in run_opengl_probe
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 933: invalid continuation byte

at server:
@PC-CAD-16-Linux:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

**Comment by totaam** [comment]
Can you please post the output of `Xpra_cmd.exe opengl -d opengl`?

**Comment by totaam** [comment]
We only support Python 3.6+ now, so we can use `universal_newlines=True`, the commit above should fix this problem.

**Comment by rsromanovskiy** [comment]
> Xpra_cmd.exe opengl -d opengl 1>1log.log
Xpra_cmd.exe opengl -d opengl 2>2log.log

[1log.log](https://github.com/Xpra-org/xpra/files/11962124/1log.log)
[2log.log](https://github.com/Xpra-org/xpra/files/11962125/2log.log)

**Comment by totaam** [comment]
This may have something to do with it:
```
Original error was: DLL load failed while importing _multiarray_umath: �� ������ ��������� ������.
```
Though that's on stderr.
The stdout output looks clean:
```
GLU.version=1.2.2.0 Microsoft Corporation
accelerate=3.1.7
display_mode=DOUBLE
max-viewport-dims=16384, 16384
opengl=4.6
platform=win32
pyopengl=3.1.7
renderer=Intel(R) Iris(R) Xe Graphics
safe=True
shading-language-version=4.60 - Build 31.0.101.4255
success=True
texture-size-limit=16384
transparency=True
vendor=Intel
zerocopy=True
```

The fix above should work. You can apply it to your installation by applying the patch in-place, or wait for the next beta builds.
Another way to fix this might be to run with `--opengl=force` or `--opengl=no`.
