### ISSUE TITLE
"xpra sessions" mis-reports display numbers

### ISSUE THREAD

**Issue by karlkleinpaste** [Xpra-org/xpra#3886]
5.0-r33142, RHEL 9.

Display numbers in the session browser are inconsistent. There are 2 sessions shown, :43 and :73, but under the Display column, it shows :73 for both.

There is a 3rd session on :27 (a desktop session), which does not appear in the list at all.

![xpra-sessions](https://github.com/Xpra-org/xpra/assets/7548920/9078c968-94a8-47bb-81e2-37616c2af822)

**Comment by karlkleinpaste** [comment]
As of r34756, this is no longer being seen, either in RHEL 9 or Fedora 39.
Must have been handled by some other work along the way.

**Comment by totaam** [comment]
I can't think of any changes even remotely related to this.
I think the bug is still there, but this will do for now.
