### ISSUE TITLE
5.0 r33655: session browser does not open on Windows

### ISSUE THREAD

**Issue by shururuun** [Xpra-org/xpra#3895]
When you open the session browser from the start menu icon, it automatically fails with an error message.

![Error Message](https://i.imgur.com/2Nz0n1K.png)

**To Reproduce**
1. xpra start :10
2. Start session browser

**System Information (please complete the following information):**
 - Server OS: Debian Bookworm
 - Client OS: Windows 11
 - Xpra Server Version 4.4.5
 - Xpra Client Version 5.0 beta r33655

**Comment by totaam** [comment]
Thanks, fixed in the second commit above.
New beta builds for MS Windows have been released. Please try `5.0-r33665` or later.
