### ISSUE TITLE
installer is faulty

### ISSUE THREAD

**Issue by maghmo1** [Xpra-org/xpra#3897]
**Describe the bug**
Windows Defender and Edge recognize the exe as a virus.
**To Reproduce**
Download from gitbub and official website

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04.2 LTS
 - Client OS: Windows Server 2016 and Windows 10
 - Xpra Server Version xpra v3.1
 - Xpra Client Version ---

**Additional context**
The seems that some certificate chain is missing according to bitdefender and microsoft defender, please take a look into it.

**Comment by totaam** [comment]
There are many other tickets all like this one, all invalid.
You didn't provide any details to act on anyway.

**Comment by maghmo1** [comment]
> There are many other tickets all like this one, all invalid. You didn't provide any details to act on anyway.

what details are you looking for exactly?

**Comment by maghmo1** [comment]
> There are many other tickets all like this one, all invalid. You didn't provide any details to act on anyway.

i dont understand why you label this as invalid, i tested this on a windows 2016 server and 2 windows 10s, the installer is imidiately deleted either by bitdefender or windows defender, as the signature seems to be invalid for whatever microsoft reason there is, now i know i could turn off my antivirus but i thought perhaps someone would be interested that the .exe is not usable on windows.

**Comment by totaam** [comment]
The actual error message would be a start.

But as I said above, just like every other ticket like this one, it will is very likely to be invalid.

Unless you are talking about the gpg signature, in which case this is: #3863 and there's absolutely nothing wrong with the installer, only the gpg key has expired.

**Comment by totaam** [comment]
> The seems that some certificate chain is missing according to bitdefender and microsoft defender,

I'm pretty sure that you got this from a message and not out of thin air.
> there are no error messages as i told you.

Ahem.

Feel free to use the beta builds which use the new gpg key.

This ticket will not be worked on.
