### ISSUE TITLE
Keyboard shortcuts don't work when readonly mode is enabled

### ISSUE THREAD

**Issue by normanr** [Xpra-org/xpra#3899]
**Describe the bug**
Keyboard shortcuts don't work when readonly mode is enabled 

**To Reproduce**
1. `xpra shadow $DISPLAY --readonly`

**System Information (please complete the following information):**
 - Server OS: debian testing
 - Client OS: debian testing
 - Xpra Server Version 4.4.5
 - Xpra Client Version 4.4.5

**Additional context**
Keyboard shortcuts work fine without readonly mode enabled.

**Comment by totaam** [comment]
The commit above should do what you want.
