### ISSUE TITLE
MacOS downloads broken

### ISSUE THREAD

**Issue by suschizu** [Xpra-org/xpra#3900]
**Describe the bug**
the downloads here aren't working:
https://xpra.org/dists/MacOS/x86_64/Xpra.dmg
https://xpra.org/dists/osx/x86_64/Xpra.pkg

 - Client OS: [e.g. MacOS 12]

**Comment by totaam** [comment]
That's fixed, thanks.

FYI: both are the same link.

**Comment by suschizu** [comment]
great thanks for the fast fix!
