### ISSUE TITLE
xpra attach from client with two displays - how to limit max resolution

### ISSUE THREAD

**Issue by diabolusss** [Xpra-org/xpra#3901]
**Describe the bug**
When connecting in seamless mode to a headless xpra server from a client with 2 monitors enabled , xpra server resolution gets updated even with --resize-display=no flag. App resolution is updated accordingly and some apps relocates to extended display.

![xpra_client_extended](https://github.com/Xpra-org/xpra/assets/8426197/7c10bbcb-a2c4-4b88-8cf6-89ae724d7e6d)

**To Reproduce**

0. xpra server (remote) 
 started via command:
```
 xpra start ssh://$XPRA_SSH_CMD/ --ssh="ssh $XPRA_SSH_OPTS" --start=/home/$SSH_USER/autostart.sh
```
which produces process: 
``` 
/usr/bin/xpra seamless --ssh=ssh  -c chacha20-poly1305@openssh.com -o Compression=no --splash=no --env=XPRA_PROXY_START_UUID=#some_hash# --daemon=yes --systemd-run=no --displayfd=4
```

and default x framebuffer subprocess:

```
Xvfb-for-Xpra-S3306 +extension GLX +extension Composite -screen 0 8192x4096x24+32 -nolisten tcp -noreset -auth /home/user/.Xauthority -dpi 96 -displayfd 7
```

1. xpra client (enabled only one display)
```
$ xdpyinfo | grep dimensions  
     dimensions:    1920x1080 pixels (508x286 millimeters)
```

xpra client connection command: 
```
xpra attach ssh://$XPRA_SSH_CMD/$XPRA_DISPLAY_ID --ssh="ssh $XPRA_SSH_OPTS" --enable-pings --speaker=off  --microphone=off --pulseaudio=no --av-sync=no --resize-display=no
```

```
OpenGL_accelerate module loaded
2023-06-22 20:54:39,036 Using accelerated ArrayDatatype
2023-06-22 20:54:39,772 OpenGL enabled with AMD RENOIR (DRM 3.49.0, 6.2.6-arch1-1, LLVM 13.0.1)
2023-06-22 20:54:40,470  desktop size is 1920x1080:
2023-06-22 20:54:40,471   :0.0 (508x286 mm - DPI: 96x96)
2023-06-22 20:54:40,471     SAM HDMI-1       (527x296 mm - DPI: 93x93)
2023-06-22 20:54:43,741 enabled remote logging
2023-06-22 20:54:43,741 Xpra X11 seamless server version 4.4 32-bit
2023-06-22 20:54:43,741  running on unknown
2023-06-22 20:54:43,781 Attached to xpra server at devboxvm:22
```

xpra server (remote) after connection
```
DISPLAY=:0 xdpyinfo | grep dimensions
  dimensions:    1920x1080 pixels (508x286 millimeters)
```

3. xpra client display extended (2 monitors in extended mode):
```
(xpra client)$ xdpyinfo | grep dimensions
  dimensions:    3840x1080 pixels (1016x286 millimeters)
```

xpra server (remote) before connecting
```
DISPLAY=:0 xdpyinfo | grep dimensions
  dimensions:    1920x1080 pixels (508x286 millimeters)
```

xpra client connect (same as before): 
`xpra attach ssh://$XPRA_SSH_CMD/$XPRA_DISPLAY_ID --ssh="ssh $XPRA_SSH_OPTS" --enable-pings --speaker=off  --microphone=off --pulseaudio=no --av-sync=no --resize-display=no`

xpra client connection log:
```
2023-06-22 18:59:31,228 OpenGL_accelerate module loaded
2023-06-22 18:59:31,235 Using accelerated ArrayDatatype
2023-06-22 18:59:31,771 OpenGL enabled with AMD RENOIR (DRM 3.49.0, 6.2.6-arch1-1, LLVM 13.0.1)
2023-06-22 18:59:32,402  desktop size is 3840x1080:
2023-06-22 18:59:32,403   :0.0 (1016x286 mm - DPI: 96x96)
2023-06-22 18:59:32,403     SAM HDMI-1       1920x1080 at    0x0    (527x296 mm - DPI: 93x93) workarea: 1920x1080
2023-06-22 18:59:32,403     NCP eDP-1        1920x1080 at 1920x0    (344x194 mm - DPI: 142x141) workarea: 1920x1080 at 1920x0
2023-06-22 18:59:35,777 enabled remote logging
2023-06-22 18:59:35,777 Xpra X11 seamless server version 4.4 32-bit
2023-06-22 18:59:35,777  running on unknown
2023-06-22 18:59:35,820 Attached to xpra server at devboxvm:22
2023-06-22 18:59:35,820  (press Control-C to detach)
```

xpra server (remote) after connection
```
$ DISPLAY=:0 xdpyinfo | grep dimensions
  dimensions:    3840x1080 pixels (2032x286 millimeters)
```

client process:
` /usr/bin/python .local/bin/xpra attach ssh://devboxvm/0 --ssh=ssh  -c chacha20-poly1305@openssh.com -o Compression=no --enable-pings --speaker=off --microphone=off --pulseaudio=no --av-sync=no --resize-display=no`

**System Information:**
 - Server OS: Ubuntu 20.04.6 LTS
 - Client OS:  Arch Linux
 - Xpra Server Version 4.4
 - Xpra Client Version 4.3.2

**Additional context**
My aim is to limit the xpra client to one screen resolution, regardless of extended mode, i.e.  to 1920x1080.

**Comment by totaam** [comment]
> Xpra Server Version 4.4
> Xpra Client Version 4.3.2

None of these versions are supported.

>  `--enable-pings`

This is the default.

> `--resize-display=no`

This is a server option, it must be specified when starting the server, not when connecting the client.

> `Xvfb-for-Xpra-S3306 +extension GLX +extension Composite -screen 0 8192x4096x24+32 -nolisten tcp -noreset -auth /home/user/.Xauthority -dpi 96 -displayfd 7`

Debian and Ubuntu distributions are handicapped by buggy support for Xdummy, which is why xpra uses `Xvfb`.
`Xvfb` is unable to virtualize multiple monitor.s

> My aim is to limit the xpra client to one screen resolution, regardless of extended mode, i.e. to 1920x1080.

This is not possible.
It is not xpra's responsibility and xpra has little to no control over window placement on the client side.
(and the server-side vfb *must* match the client's)

**Comment by diabolusss** [comment]
Actually, i've found out that switching resolution via randr fixes the problem.
```
$ DISPLAY=:0 xrandr
xrandr: Failed to get size of gamma for output screen
Screen 0: minimum 1 x 1, current 3840 x 1080, maximum 8192 x 4096
screen connected 3840x1080+0+0 0mm x 0mm
   8192x4096      0.00  
   1920x1080@50  50.00  
   3840x1080@50  50.00* 
   5766x1622@50  50.00  
   1920x540@50   50.00  
   7680x2160@50  50.00  

$ DISPLAY=:0 xrandr --output "screen" --mode "1920x1080@50"
xrandr: Failed to get size of gamma for output screen

$ DISPLAY=:0 xrandr
xrandr: Failed to get size of gamma for output screen
Screen 0: minimum 1 x 1, current 1920 x 1080, maximum 8192 x 4096
screen connected 1920x1080+0+0 0mm x 0mm
   8192x4096      0.00  
   1920x1080@50  50.00* 
   3840x1080@50  50.00  
   5766x1622@50  50.00  
   1920x540@50   50.00  
   7680x2160@50  50.00 
```
Then from the client xpra menu run Windows->re-initialize and the issue fixes itself.
