### ISSUE TITLE
"xpra recover" doesn't work after xpra crash: "selection timeout" "the current owner did not exit"

### ISSUE THREAD

**Issue by michalwelnicki** [Xpra-org/xpra#3904]
**Describe the bug**
Recovering xpra after a (server-side) crash does not work on a Rocky Linux 8.8 server.
Xpra on the server crashes occasionally when using a kde3-era application (which is a separate issue).
When trying to recover it by running "xpra recover" I get the following errors:
```
$ tail -n 5 /run/user/1023/xpra/0/server.log
2023-06-23 18:56:23,477 created unix domain socket '/run/user/1023/xpra/0/socket'
2023-06-23 18:56:23,478 xvfb pid=1542
2023-06-23 18:56:23,651 started command `ibus-daemon` with pid 1560114
2023-06-23 18:56:43,619 selection timeout
2023-06-23 18:56:43,619  the current owner did not exit
```
**To Reproduce**
1. start xpra from the client side; I'm using: `XPRA_SCROLL_ENCODING=0 xpra start --ssh=ssh --modal-windows=no --speaker=off ssh://SERVERHOST --start-child=xterm --exit-with-children`; but it happens after an earlier successful `xpra recover`
2. start up a lot of programs, use for several days until xpra server crashes; or just kill -9 the /usr/bin/xpra process on the server
3. ssh to the server and attempt to restart xpra using `xpra recover`
4. xpra starts up for several seconds but eventually dies with `selection timeout` `the current owner did not exit`

**System Information (please complete the following information):**
 - Server OS: Rocky Linux 8.8
 - Client OS: various, usually LinuxMint 21.1
 - Xpra Server Version: xpra v4.4.6-r29
 - Xpra Client Version: xpra v4.4.5-r0

**Additional context**
I can usually get "xpra recover" to work if I go and manually kill off all processes related to ibus: "ibus-daemon", "ibus-dconf", "ibus-extension-gtk3", "ibus-portal", "ibus-x11" etc. I'm not sure which one it is exactly, sometimes just killing "ibus-daemon" works but not always.
These ibus-* processes seem to get restarted by "xpra recover".

**Comment by totaam** [comment]
> `XPRA_SCROLL_ENCODING=0`

Why is this necessary?

> I can usually get "xpra recover" to work if I go and manually kill off all processes related to ibus

Interesting.
We only start one of these, but I guess that it must have spawned some more.

**Comment by totaam** [comment]
Not enough information there to debug. Closing.

> `the current owner did not exit`

This tells me that either the previous xpra server is still running, or maybe another window manager has taken over.
