### ISSUE TITLE
Debian signing key tampered?

### ISSUE THREAD

**Issue by neuhalje** [Xpra-org/xpra#3908]
# Observed Behaviour

The `gpg` signing key under https://xpra.org/gpg.asc has recently changed and differs from the [documented](https://github.com/Xpra-org/xpra/blob/master/docs/FAQ.md#why-do-i-get-a-gpg-signature-warning-when-i-try-to-install) key. This could be a malicious tampering.

## Current Key
As of today (2023-06-27) the key-id is `B4993B57323148E37977E5D873254CAD17978FAF`:

```sh
wget -O - https://xpra.org/gpg.asc  | gpg --import-options show-only --import

pub   rsa4096/0x73254CAD17978FAF 2023-06-10 [SC] [expires: 2033-06-07]
      B4993B57323148E37977E5D873254CAD17978FAF
uid                              Xpra <xpra@xpra.org>
```

## Old & Documented Key

My archive copy looks line this:

```sh
cat docker/xpra.gpg | gpg --import-options show-only --import


pub   dsa1024/0xAD306B2D11BB7837 2006-03-15 [SC] [expired: 2007-03-15]
      E32F3184D959D5E469866EC8AD306B2D11BB7837
uid                              Antoine Martin <antoine@nagafix.co.uk>

gpg: WARNING: No valid encryption subkey left over.
pub   dsa1024/0x18ADB31CF18AD6BB 2007-04-18 [SC] [expires: 2026-03-21]
      C11C0A4DF702EDF6C04F458C18ADB31CF18AD6BB
uid                              Antoine Martin <antoine@nagafix.co.uk>
uid                              [jpeg image of size 4992]
sub   elg2048/0x00D777F76E23E963 2007-04-18 [E] [expires: 2026-03-21]
```

The linked documentation lists `dsa1024/0x18ADB31CF18AD6BB 2007-04-18 [SC] [expires: 2026-03-21]` as correct.

# Expected Behaviour

[documentation](https://github.com/Xpra-org/xpra/blob/master/docs/FAQ.md#why-do-i-get-a-gpg-signature-warning-when-i-try-to-install)  and [key](https://xpra.org/gpg.asc ) are the same

**Comment by totaam** [comment]
See #3863
Which links to:
https://lists.devloop.org.uk/pipermail/shifter-users/2023-June/002981.html
