### ISSUE TITLE
Debian 11, Wayland, xpra v4.4.6-r29: Error: failed to write script file '/run/user/1000/xpra/run-xpra':

### ISSUE THREAD

**Issue by zz0rk** [Xpra-org/xpra#3919]
**Describe the bug**
I attempt to start xpra as a non-administrator:
`$ xpra start :100 --start=vlc`
Xpra fails to start with error provided below.

**To Reproduce**
1. server command: `$ xpra start :100 --start=vlc`
2. client command: N/A
3. specific action to trigger the bug: `$ xpra start :100 --start=vlc`

**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x] debian 11, wayland
 - Client OS: [e.g. Windows 10] debian 11, wayland
 - Xpra Server Version [e.g. 4.2.3] xpra v4.4.6-r29
 - Xpra Client Version [e.g. 4.3] xpra v4.4.6-r29

**Additional context**
**Error**;
```
user$ 2023-07-11 15:10:25,059 Error: failed to write script file '/run/user/1000/xpra/run-xpra':
2023-07-11 15:10:25,060  [Errno 13] Permission denied: '/run/user/1000/xpra/run-xpra'
2023-07-11 15:10:25,061 Error saving session file '/tmp/100/server.env'
2023-07-11 15:10:25,061  [Errno 13] Permission denied: '/tmp/100/server.env'
2023-07-11 15:10:25,061 Error saving session file '/tmp/100/cmdline'
2023-07-11 15:10:25,061  [Errno 13] Permission denied: '/tmp/100/cmdline'
2023-07-11 15:10:25,069 Error saving session file '/tmp/100/config'
2023-07-11 15:10:25,069  [Errno 13] Permission denied: '/tmp/100/config'
xpra initialization error:
cannot open log file '/tmp/100/server.log': [Errno 13] Permission denied: '/tmp/100/server.log'
```

**temp** directory:
```
drwxr-x---  2       1001       1001 4096 Jul 11 11:13 100
```

add user to group **1001**:
```
root:~# usermod -a -G 1001 user
usermod: group '1001' does not exist
```

**Comment by totaam** [comment]
> I attempt to start xpra as a non-administrator:

This should always work. Starting xpra as root is not recommended.

`$XDG_RUNTIME_DIR` should exist and belong to the current user.
Something is messed up on your system and this is not the case.

> `usermod -a -G 1001 user`

This should not be needed.

**Comment by totaam** [comment]
@zz0rk are you logging in via ssh?
What is the value of `$XDG_RUNTIME_DIR`?

**Comment by zz0rk** [comment]
Yes, I am connected via ssh. 
/var/run/user/1000/xpra
drwxr-xr-x  2 user user 120 Jul 11 21:07 tmp

**Comment by totaam** [comment]
That's not `XDG_RUNTIME_DIR`, that's xpra's dir.
Then  why are you getting errors such as this one:
```
2023-07-11 15:10:25,060  [Errno 13] Permission denied: '/run/user/1000/xpra/run-xpra'
```
Does it work from the ssh shell?
```
touch '/run/user/1000/xpra/test'
```

**Comment by zz0rk** [comment]
That's not `XDG_RUNTIME_DIR`, that's xpra's dir. Then why are you getting errors such as this one:

```
2023-07-11 15:10:25,060  [Errno 13] Permission denied: '/run/user/1000/xpra/run-xpra'
```

Does it work from the ssh shell?

```
touch '/run/user/1000/xpra/test'
```
I ssh into the host and execute the command as a non-admin user that's when I get the error messages.
I have since opted to run xpra as a service on my host, so you may close this ticket.
Thank you for your time. : )

**Comment by totaam** [comment]
I am closing as invalid because there is something seriously wrong with your system if `XDG_RUNTIME_DIR` exists but users can't write there.

**Comment by totaam** [comment]
It has just been pointed out that you have `1000` and `1001` in your output.
My guess is that you are using `sudo` or `su` and changing uid, without correctly setting up the environment for the new user.
This will not work for most applications, definitely will cause problems for xpra.
Do not do this.

**Comment by zz0rk** [comment]
No, please see above

root:~# usermod -a -G 1001 user
usermod: group '1001' does not exist

the usermod failed because '1001' does not exist.
There's nothing wrong with my user environment. I've installed this on two Debian boxes which are identical as far as the versioning, etc. concerned. The both show the same behavior.
Plain vanilla install as outlined above.
Thank you
