### ISSUE TITLE
Update doucmentation to reflect correct signing key

### ISSUE THREAD

**Issue by neuhalje** [Xpra-org/xpra#3921]
(result of #3908)

The `gpg` signing key under https://xpra.org/gpg.asc has recently changed and differs from the [documented](https://github.com/Xpra-org/xpra/blob/master/docs/FAQ.md#why-do-i-get-a-gpg-signature-warning-when-i-try-to-install) key. 

## Current Key
As of today (2023-06-27) the key-id is `B4993B57323148E37977E5D873254CAD17978FAF`:

## Old & Documented Key

The linked documentation lists `dsa1024/0x18ADB31CF18AD6BB 2007-04-18 [SC] [expires: 2026-03-21]` as correct.

# Expected Behaviour

[documentation](https://github.com/Xpra-org/xpra/blob/master/docs/FAQ.md#why-do-i-get-a-gpg-signature-warning-when-i-try-to-install)  and [key](https://xpra.org/gpg.asc ) are the same

**Comment by totaam** [comment]
Done: 386efb7ca0f47adb881beed2c23b49503725e769

**Comment by totaam** [comment]
Reference GPG ticket is #3863
