### ISSUE TITLE
type cleanups and refactoring

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3930]
Mostly flagged by #3927, related to #3592.

A lot of the types from the `typing` module are now deprecated, see [PEP 585](https://peps.python.org/pep-0585/):
https://docs.python.org/3/library/typing.html#typing.Tuple

This requires Python 3.9 (not a big problem for v6?)

* `get_info` server method signature mess:
```
xpra/platform/darwin/shadow_server.py:231: error: Signature of "get_info" incompatible with supertype "ServerBase"  [override]
xpra/platform/darwin/shadow_server.py:231: note:      Superclass:
xpra/platform/darwin/shadow_server.py:231: note:          def get_info(self, proto: Any = ..., client_uuids: Any = ...) -> dict[str, Any]
xpra/platform/darwin/shadow_server.py:231: note:      Subclass:
xpra/platform/darwin/shadow_server.py:231: note:          def get_info(self, proto: Any, *_args: Any) -> dict[str, Any]
```
* stricter packet parsing at network boundary, ie:
`xpra/x11/server.py:916: error: Cannot determine type of "wid"  [has-type]`
Could this be [introspected](https://docs.python.org/3/library/inspect.html#inspect.signature) and changed to a positional packet function with default args?
* "client-window-base" missing attributes"
`xpra/client/gui/client_window_base.py:414: error: "ClientWindowBase" has no attribute "set_modal"  [attr-defined]`
* mixins cross domain dependencies:
`xpra/server/mixins/audio.py:216: error: "AudioServer" has no attribute "add_process"  [attr-defined]`
* `SocketProtocol` missing attributes: `authenticators`, `encryption`, ..
* `XpraConfig` class does not have any "real" attributes: convert to introspected hints?
* `_id_to_window`, `readonly`, `ui_driver` and friends
* `Return a value of type "tuple[bool, bool]" instead of "NoneType" or update function "accept_data" type hint`
* `brain-overload`: 164 functions have a cognitive complexity above 30 in sonarqube
* 41 `FIXME`s and 38 `TODO`s
* 9 functions have too many arguments
etc

**Comment by zatricky** [comment]
This seems also to be a problem for `focal` (Ubuntu 22.04) as the latest version of xpra now requires python3.10+ whereas focal ships with python3.8.10.

**Comment by totaam** [comment]
@zatricky thanks for pointing that out, the workaround in d37fecb03d60cef8bbf2e6e12957c89d7ee290d1 should work (not tested yet).
The requirement for Python 3.6+ in v5 is unchanged.

**Comment by zatricky** [comment]
Oops! Yes, 20.04 ... :-|

**Comment by totaam** [comment]
With the switch to Python 3.10+, we can also take advantage of:
* https://docs.python.org/3/library/time.html#time.monotonic_ns
* https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass decorator?
* https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext to replace the dummy context
* https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout to replace out custom context
* https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Network.supernet_of to replace code from `net_util`?
* https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.kill if `terminate` fails?
* https://docs.python.org/3/library/queue.html#queue.SimpleQueue
* https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions "the walrus", incrementally
* https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging
* https://docs.python.org/3/library/stdtypes.html#int.as_integer_ratio for scaling parser?
* https://docs.python.org/3/library/importlib.metadata.html#overview for getting version numbers?
* https://docs.python.org/3/whatsnew/3.8.html#logging force basic config?
* https://docs.python.org/3/library/mmap.html#mmap.mmap.madvise with https://docs.python.org/3/library/mmap.html#mmap.MADV_DONTDUMP for mmap area
* https://docs.python.org/3/library/threading.html#threading.get_native_id expose it?
* https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators
* https://docs.python.org/3/whatsnew/3.9.html#new-string-methods-to-remove-prefixes-and-suffixes
* https://docs.python.org/3/library/sys.html#sys.platlibdir ?
* https://docs.python.org/3/library/typing.html#typing.get_type_hints

**Comment by totaam** [comment]
Remaining items that might be of interest:
* [monotonic_ns](https://docs.python.org/3/library/time.html#time.monotonic_ns) for a lot of performance data (window and source stats)
* [dataclasses](https://docs.python.org/3/library/dataclasses.html#module-dataclasses)
* [contextlib.suppress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress)
* [os.add_dll_directory](https://docs.python.org/3/library/os.html#os.add_dll_directory)
* [os.memfd_create](https://docs.python.org/3/library/os.html#os.memfd_create)
* [shlex.join](https://docs.python.org/3/library/shlex.html#shlex.join) for ssh command?
* [has_dualstack_ipv6](https://docs.python.org/3/library/socket.html#socket.has_dualstack_ipv6)
* [ipaddress](https://docs.python.org/3/library/ipaddress.html#module-ipaddress)
* _The [socket.if_nameindex()](https://docs.python.org/3/library/socket.html#socket.if_nameindex), [socket.if_nametoindex()](https://docs.python.org/3/library/socket.html#socket.if_nametoindex), and [socket.if_indextoname()](https://docs.python.org/3/library/socket.html#socket.if_indextoname) functions have been implemented on Windows_
* [typing.Literal](https://docs.python.org/3/library/typing.html#typing.Literal)
* [math.isclose](https://docs.python.org/3/library/math.html#math.isclose)
* [ConfigParser](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.BOOLEAN_STATES)
* [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run) with `capture_output`
* [set_start_method](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method) with `spawn`? (and pass file descriptors by hand?)

**Comment by totaam** [comment]
Regarding the switch to `monotonic_ns`, here is the type of bug we don't want to re-introduce: 57686777f7fd53ffb74979fdbd3b682c86284236 / #2038
