### ISSUE TITLE
project management changes needed

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3948]
For details, please see the mailing list post: [project management changes needed](https://lists.devloop.org.uk/pipermail/shifter-users/2023-July/002987.html) and the mirror [github discussion](https://github.com/orgs/Xpra-org/discussions/3949).

Tasks:
* archive the [mailing list](https://lists.devloop.org.uk/pipermail/shifter-users/) and switch over to [github discussions](https://github.com/orgs/Xpra-org/discussions),
* move all the package [https://xpra.org/dist/](downloads) to a third party hosting service (TBD),
* redirect [xpra.org](https://xpra.org/) to [github](https://github.com/Xpra-org/xpra),
* finally release [version 5.0](https://github.com/Xpra-org/xpra/tree/v5.x) and a few minor updates after that,
* give commit, release and key privileges to more contributors,
* decommission the hardware currently hosting a lot of these services,
* step down as maintainer

**Comment by ehfd** [comment]
Mirroring from the discussion:

> move all the package https://xpra.org/dist/ to a third party hosting service (TBD)

https://blog.packagecloud.io/packagecloud-loves-oss/

https://help.cloudsmith.io/docs/open-source-hosting-policy

https://cloudrepo.io/pricing.html

Good candidates for the "third party hosting service"

https://www.rabbitmq.com/install-rpm.html

RabbitMQ is a pretty large project, and they receive support from them.

**Comment by totaam** [comment]
> Mirroring from the discussion:

@ehfd Deleted. Let's avoid more duplication.
The discussion is here: https://github.com/orgs/Xpra-org/discussions/3949
