### ISSUE TITLE
Large list of recommended packages for xpra 5.0 in Debian bookworm

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3969]
**Describe the bug**
The upgrade to the Debian bookworm xpra 5.0-r0-1 package would require 7 GB of new packages to be installed. This is probably unreasonable and due to an unfortunate dependencies that could probably be made optional.

**To Reproduce**
Upgrade xpra on Debian bookworm from "4.4.6-r29-1" to "5.0-r0-1"

**System Information (please complete the following information):**
 - Server OS: Debian bookworm

**Additional context**
The new dependencies seem to pull in a lot of nvidia libraries and nvidia development packages, even on systemd that do not have a nvidia card. Maybe some dependencies (probably especially xpra-codecs-nvidia) should be moved from recommends to suggests?

**Comment by totaam** [comment]
Use "no-install-recommends" or remove the `xpra-nvidia-codecs` package.
See #3968
