### ISSUE TITLE
Failed to receive anything if X Server unused

### ISSUE THREAD

**Issue by dunkfan** [Xpra-org/xpra#3970]
I cannot attach to a running xpra server if the server has been started on a system where the standard X server :0 is not active
When Linux is booted on the server with a standard display connected and operational the attach command works, if no display is operational, the client command fails with a "failed to receive anything... Connection lost" error. 

Server: Raspbian 10 buster
Client: Linux Mint 21.2

Server command:
xpra start :100 --start=x-terminal-emulator 

Client command:
xpra attach ssh:user@host

Server 2.4.3 (32 bit) 
Client 3.1

Thanks especially for a workaround idea

**Comment by totaam** [comment]
> Server 2.4.3 (32 bit)
> Client 3.1

Use a supported version, and if that doesn't fix it, a Tier-1 platform:
https://github.com/Xpra-org/xpra/wiki/Platforms
