### ISSUE TITLE
DBUS_SESSION_BUS_ADDRESS not set by xpra 5.0 server

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3976]
**Describe the bug**
When running xpra 5.0 as server, `DBUS_SESSION_BUS_ADDRESS` is not set what causes a lot of problems, for example, with programs communicating with gnome-keyring. When using dbus-launch inside the xpra-session, programs inside the same dbus-launch environment can see each other, but forwarding desktop notifications to the client does not work (probably because it should use another dbus bus).

Downgrading to 4.4 solves the issue, so I think it is a xpra problem, or at least related to a change between xpra 4.4 and 5.0.

**To Reproduce**
1. `xpra start :10`
2. `xpra attach --ssh=/usr/bin/ssh ssh://user@server/10`
3. Open a terminal from the tray menu -> run command and then try `echo $DBUS_SESSION_BUS_ADDRESS` for diagnosing the missing variable. with xpra 4.4 it is set, with 5.0 it is not set.

**System Information (please complete the following information):**
 - Server OS: Debian bookworm
 - Client OS: Debian trixie
 - Xpra Server Version (affected): 5.0-r0-1
 - Xpra Server Version (unaffected): 4.4.6-r29-1
 - Xpra Client Version: 5.0-r32900-1

**Comment by totaam** [comment]
Thanks, looks like the code was broken for years but the bug didn't trigger until now.
The commit above fixes that and will be included in 5.0.1

**Comment by allo-** [comment]
Thanks! I was debugging the issue for hours yesterday and almost gave up when I tried the downgrade, as 5.0 worked correctly after an upgrade command and the bug only triggered after a full restart of xpra.
