### ISSUE TITLE
macOS x86_64 and arm64 versions do not match

### ISSUE THREAD

**Issue by nguyen-phillip** [Xpra-org/xpra#3984]
We are obtaining the macOS x86_64 version for Intel machines from 

https://www.xpra.org/dists/osx/x86_64/Xpra.pkg

which has 

```
$ plutil -p Applications/Xpra.app/Contents/Info.plist | egrep "CFBundle(Short)?Version"
  "CFBundleShortVersionString" => "4.4.6"
  "CFBundleVersion" => "29.0"
```

and the arm64 version for Apple Silicon machines from 

https://www.xpra.org/dists/osx/arm64/Xpra.pkg

which has

```
$ plutil -p Applications/Xpra.app/Contents/Info.plist | egrep "CFBundle(Short)?Version"
  "CFBundleShortVersionString" => "6.0"
  "CFBundleVersion" => "33975.0"
```

Before August 20, the CFBundleShortVersionString for both used to be `4.4.6`.  Now they are different (and the arm64 version seems to be ahead of the stable release). Will these releases eventually be in sync  again? Have you deprecated the x86_64 version?

This has come up because we make Xpra available to a diverse fleet and try to distribute the same version to all devices, so we're currently stuck on version `4.4.6` as that was the last version where both releases matched.

**Comment by totaam** [comment]
The links you are using will change over time as new releases are made. The 6.0 build was an error.
As of today, both links should be pointing to `5.0.1-r0`

Note that I do not have the hardware required for testing these builds, so YMMV and for that reason MacOS builds are now Tier-2:
https://github.com/Xpra-org/xpra/wiki/Platforms

**Comment by nguyen-phillip** [comment]
Understandable and thank you for the quick resolution!
