### ISSUE TITLE
`--start-after-connect=CMD` does not work

### ISSUE THREAD

**Issue by KondorIstvan** [Xpra-org/xpra#3985]
**Describe the bug**
When `--start-after-connect=gnome-terminal` is used at first connection the terminal window should pop up but it does not.

**To Reproduce**
1. Check no Xpra is runnning with `xpra list`
2. `xpra start :12 --start-after-connect=gnome-terminal`
3. Connect with python client
4. Terminal window should pop up

**System Information (please complete the following information):**
 - Server OS: [RHEL 8.7]
 - Client OS: [Windows 10]
 - Xpra Server Version [5.0.1]
 - Xpra Client Version [5.0]

**Additional context**
All other start-commands work as expected, `start`, `start-child`, `start-on-connect` all produce a terminal window.
In the working cases a line like this is printed in the logs:
> Sep 04 12:51:38 myhost xpra[89665]: 2023-09-04 12:51:38,097 started command `/usr/bin/vglrun gnome-terminal` with pid 90387

With `start-after-connect` there is absolutely nothing regarding gnome-terminal in the logs.
Any other command can be used, I also tested xterm, so it's not confined to gnome-terminal.

**Comment by totaam** [comment]
This broke in 13411dba268d4a69c3b151cb9718e3b840af93fa, fixed in the commit above.

This will be included in 5.0.2 - there are no workarounds, sorry.
