### ISSUE TITLE
`conf_dir = os.getcwd()`: `FileNotFoundError: [Errno 2] No such file or directory`

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3997]
**Describe the bug**

```console
u@h /run/user/1000/xpra/1$ xpra list
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 109, in main
    defaults : XpraConfig = make_defaults_struct()
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 1312, in make_defaults_struct
    return do_make_defaults_struct(extras_defaults or {}, extras_types or {}, extras_validation or {},
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 1321, in do_make_defaults_struct
    return dict_to_validated_config(defaults, extras_defaults, extras_types, extras_validation)
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 1324, in dict_to_validated_config
    options = get_defaults().copy()
  File "/usr/lib/python3/dist-packages/xpra/scripts/config.py", line 924, in get_defaults
    conf_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

u@h /run/user/1000/xpra/1$ ls -lah
total 0
```

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.5 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version (see above)
- Xpra Client Version (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
The commit above will now ignore the cwd if it cannot be accessed - for whatever reason.
In your case, this is a temporary session directory - which may be removed or re-created at anytime.

**Comment by KondorIstvan** [comment]
Just in case anybody reads this in the future:
On a headless server sytemd is going to remove the folder `run/usr/100x` after the system bootup is completed and it will only be re-created once the user logs in. To circumvent it, you need to enable lingering for the user with `sudo loginctl enable-linger <username>`
