### ISSUE TITLE
XPRA HTML5 crashes intermittently when using applications

### ISSUE THREAD

**Issue by mint-b** [Xpra-org/xpra#4004]
**Describe the bug**

When using XPRA and launching some applications inside the web browser (Google Earth in this case), sometimes XPRA will randomly crash.

The application that was running will stay opened in the OS and can be viewed in the terminal (ps -ef | grep google), but opening a new XPRA session from the web browser won't bring it back (unlike closing a tab).

**To Reproduce**

1. Launch XPRA Server with Proxy
2. Login with web browser
3. Launch Google Earth
4. File -> Open
5. Close the "Open" window with the top [X] button.
6. XPRA should crash.

Please note that this crash is intermittent, it doesn't always occur, but it occurs regularly enough to be noticeable. 

Logs from /run/user/5000/xpra/server.log

```
(Xpra:3779): Gdk-ERROR **: 16:46:20.856: The program 'Xpra' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 8799 error_code 3 request_code 7 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**System Information (please complete the following information):**

 - Server OS: Rocky Linux 8.8
 - Client OS: Windows 10 [Using Brave, Edge, Chrome browsers]

```
[root@rocky8 ~]# rpm -qa | grep xpra
python3-rencode-1.0.6-11.xpra1.el8.x86_64
xpra-4.4.6-10.r33693.el8.x86_64
xpra-common-server-4.4.6-10.r33693.el8.noarch
xorg-x11-drv-dummy-0.4.1-1.xpra1.el8.x86_64
xpra-common-4.4.6-10.r33693.el8.noarch
python3-xpra-4.4.6-10.r33693.el8.x86_64
xpra-html5-8.1-1.r9.el8.noarch
x264-xpra-20220602-1.el8.x86_64
ffmpeg-xpra-5.1.3-1.el8.x86_64
python3-xpra-server-4.4.6-10.r33693.el8.x86_64
python3-xpra-client-4.4.6-10.r33693.el8.x86_64
xpra-common-client-4.4.6-10.r33693.el8.noarch

```
NOTE: Also happens on the latest version, this is just the one I am using for my tests.

**Additional context**

I also managed to make it crash using Filezilla once, has not happened again for that app... and another application, so I don't think it is an issue exclusive to Google Earth, this is why I suspect that maybe there is some other problem..

**Comment by totaam** [comment]
Likely fixed in v5.

**Comment by mint-b** [comment]
Hi, I was able to test with v5.0.2 and it seems to be resolved in this version.

Thanks,
