### ISSUE TITLE
Can't get xpra started

### ISSUE THREAD

**Issue by AJStone** [Xpra-org/xpra#4009]
I can't get xpra started up in version 5.

I use the command (on the client) which is the same command that has always worked for xpra 4:
```
xpra start ssh/<server> --start="gnome-terminal --profile External" &
```
where `<server>` is a hostname set up in `~/.ssh/config`. There are no xpra sessions running on the server, but this command has always set up a new session on the server and connected to that.

However this now gives:
```
 xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 121, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 455, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 495, in do_run_mode
    return run_remote_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 1996, in run_remote_server
    display_name = args[0]
IndexError: list index out of range
```
Server system: Ubuntu 20.4.6, xpra version 5.0.2-r0, running under anaconda with conda environment that includes python 3.11.5
Client system: same except that the conda environment has python 3.11.4.

It looks as if something basic is set up wrongly on the client. What am I doing wrong?

**Comment by AJStone** [comment]
Markdown has removed some stuff that I enclosed in angle brackets.
The command used was
xpra start ssh/server --start="gnome-terminal --profile External" &
where server is a hostname set up in ~/.ssh/config.

**Comment by totaam** [comment]
Please use the correct syntax, `ssh/` has been deprecated for about a decade.
`xpra start ssh://server/`
