### ISSUE TITLE
x265/encoder.pyx:449:26: undeclared name not builtin: Dict

### ISSUE THREAD

**Issue by sagitter** [Xpra-org/xpra#4010]
Hi all.

**Describe the bug**

x265 encoder is not compiled with `Cython-0.29.33` and `Python-3.11` in Fedora 38:

```
[26/55] Cythonizing xpra/net/bencode/cython_bencode.pyx

Error compiling Cython file:
------------------------------------------------------------
...
        self.time = 0
        self.frames = 0
        self.first_frame_timestamp = 0


    def get_info(self) -> Dict[str,Any]:
                         ^
------------------------------------------------------------

xpra/codecs/x265/encoder.pyx:449:26: undeclared name not builtin: Dict

Error compiling Cython file:
------------------------------------------------------------
...
        self.time = 0
        self.frames = 0
        self.first_frame_timestamp = 0


    def get_info(self) -> Dict[str,Any]:
                                  ^
------------------------------------------------------------

xpra/codecs/x265/encoder.pyx:449:35: undeclared name not builtin: Any
[27/55] Cythonizing xpra/net/brotli/compressor.pyx
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1259, in cythonize_one_helper
    return cythonize_one(*m)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/Cython/Build/Dependencies.py", line 1235, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: xpra/codecs/x265/encoder.pyx
```

**System Information (please complete the following information):**
 - Server OS: Fedora 38
 - xpra- 5.0.2
- Build log:  https://koji.rpmfusion.org/kojifiles/work/tasks/1295/611295/build.log

**Comment by totaam** [comment]
Why would you manually enable a codec that is disabled by default?
It is disabled for a reason.

**Comment by totaam** [comment]
@sagitter oh, and please try to learn from the packaging that we already do here - chances are that there are many other issues that you don't know about.
Preferably without causing our packages to break once again.

**Comment by sergiomb2** [comment]
the real fix here is :
[x265_fix.patch.txt](https://github.com/Xpra-org/xpra/files/12709654/x265_fix.txt)

**Comment by totaam** [comment]
@sergiomb2 No. **Seriously, do NOT enable this codec!**

I've tried making it difficult to enable, I've tried telling people time and time again to not enable it, but I guess the only way to prevent self harm is this: ec12676d68585a926109f1e8d4783f83f4d7768b.

**Comment by sergiomb2** [comment]
Hi, @totaam , ok.
We in Fedora and RPMFusion have to build "non-free" part outside of Fedora, we do a complement package called [xpra-codecs-freeworld](https://koji.rpmfusion.org/koji/packageinfo?packageID=289) 

since x265 is not advised I ask you about openh264 and x264 the other 2 that are in freeworld package , are  openh264 and x264 useful for end users in general ?

**Comment by sagitter** [comment]
> I am well aware of the Fedora way of packaging things as it has caused breakage for users of our repositories in the past.
> Please take a moment to review how we package things, in particular sub-packages and please try not to cause more breakage.

I don't know what's happened in past, me and @sergiomb2 taking care of Xpra Fedora RPMs (and that unofficial one in RPMFusion) now, we obblied to respect the packaging rules of Fedora Project but we also want to follow your recommendations.
Fedora users must understand how to manage external packages/repositories like [yours](https://github.com/Xpra-org/xpra/wiki/Download#sub-packages) regardless if our packages are "broken" or not. The external packages are extraneous to Fedora not the opposite.

We can evaluate the chance to replicate your sub-packages organization with official RPMs of Xpra in Fedora but respecting the Packaging Rules of course; in this case external packages are useless except if they contain proprietary codecs.

**Comment by totaam** [comment]
@sagitter here is a simple example of a commit that was added to v5 packaging to make it easier for users to upgrade / downgrade to / from v6.
These are the sort of changes that can save users major headaches, no matter which repository is "external"

**Comment by sergiomb2** [comment]
@totaam where ?

**Comment by totaam** [comment]
@sergiomb2 oops!
Here's the missing link: 816ff935e7d42736315c9e1fe8296f030a59f012
