### ISSUE TITLE
rsync to xpra.org no longer works

### ISSUE THREAD

**Issue by thetomcorp** [Xpra-org/xpra#4012]
performing an rsync to sync the xpra repos doesn't pull down the latest files. The latest files are from May 25th and getting Xpra Version 4.4.5. I'm looking to synchronize with the Xpra repos to have 5.0 in a local repo.

This has the correct files:
https://www.xpra.org/dists/rockylinux/8/x86_64/

This pulls in older files:
```
rsync -avHS  rsync://xpra.org/dists/rockylinux/
```

**Comment by totaam** [comment]
Fixed.
Note: what you were getting is `vault` which is still available as `rsync://xpra.org/vault/`, at least for now.
