### ISSUE TITLE
v9.0 visual bug of a scaled-down image in the window's top-left corner

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra#4021]
v9.0 shows a visual bug of a scaled-down image in the window's top-left corner.

I know it can compress and show me a scaled-down image (that is upscaled in the client and looks pixelated) - Maybe this upscaling code is broken in v9.0

It may be related to GPU-accelerated codecs (I use NVJPEG).
I am using Xpra 5.0.1 on Ubuntu 22.04.

**Comment by totaam** [comment]
In the end, it was quite obvious.
This looks like this regression was added in the 4.3.x cycle - I'm not quite sure how I didn't hit it. (it's easier with the html5 client, especially now that we prefer nvjpeg)
