### ISSUE TITLE
"true" X session not found - results in an unwanted full desktop session  (and fix)

### ISSUE THREAD

**Issue by RichardNeill** [Xpra-org/xpra#4027]
**Describe the bug**

On recent Ubuntu, (and presumably Debian),  the xsession "/usr/bin/true" isn't available, and the result is that every Xpra instance tries to start a full desktop session. This isn't just slow, but it clogs up my local desktop with taskbars that belong to the remote one. And it nags about failing to create a color-profile.

**To Reproduce**

xpra start ssh://USER@UBUNTU_22.04/ --start=xterm
i.e. where the remote host is Ubuntu 22.04 or above.

**System Information (please complete the following information):**
 - Server OS:  Ubuntu 22.04
 - Client OS:  Ubuntu 22.04
 - Xpra Server Version 3.1
 - Xpra Client Version 3.1

**Root Cause**
https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1983185
(which also explains exactly how it works).

**Temporary fix**

Make the change (on the server) as per:
https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1983185/comments/3
and xpra then works normally again.

**Proper fix**
I suspect that if xpra were to ask for a Session named "/usr/bin/true" rather than merely "true", this problem would be resolved.

As this is likely to be broken for a lot of users for a long time (i.e. anyone on the ubuntu 22.04 and 22.04 LTS releases), I think it would be worth documenting this as an advisory on the homepage. 

Thanks.

**Comment by totaam** [comment]
Xpra 3.1 is not a supported version.
Xpra does not run `Xsession`, this is [one of the many reasons](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages#and-why-you-should-avoid-them) you should not use the packages from Debian or Ubuntu.

**Comment by RichardNeill** [comment]
At least this bug report will be helpful to others trying to find and fix it.

I take your point about some of these downstream packages being problematic, especially when out of date, but which distribution do you recommend instead? (The alternative is the madness of managing individual upstream packages on each system - which we escaped after the Windows 98-era - the aim of a distro is to make this effort happen only once, rather than for every user on every program.)

**Comment by totaam** [comment]
I use Fedora and that has good support for Xdummy, which is essential for proper virtualization of displays.
