### ISSUE TITLE
Using Ubuntu 22.04, the default port 14500 is already in used by the init process.

### ISSUE THREAD

**Issue by kirby33** [Xpra-org/xpra#4032]
Dear developer,
Thanks for this program.
I have a feedback about the default tcp port used by the service xpra.socket.
I get the error message:
    xpra.socket: Failed to create listening socket ([::]:14500): Address already in use

In fact, this port is used by the init process on Ubuntu 22.04

Just change the port 14500 by another (ex. 14600) seems to solve the problem:
I change the port in the file /lib/systemd/system/xpra.socket and everything is OK.

Regards

**Comment by totaam** [comment]
No, it is not used by the init process.

The xpra socket activated systemd service will listen on the default xpra port.
If you don't want to use it, disable it.
