### ISSUE TITLE
'EGLPlatform' object has no attribute 'GLX'

### ISSUE THREAD

**Issue by callegar** [Xpra-org/xpra#4036]
**Describe the bug**

Using xpra 5.0.3 on arch/manjaro linux, with a wayland session I am noticing that the "session info" reports N/A wrt opengl.  Trying to run `xpra opengl` I get:

```
error='EGLPlatform' object has no attribute 'GLX'
message='EGLPlatform' object has no attribute 'GLX'
success=False
```

is this expected? Cannot opengl be used with xwayland?

**To Reproduce**
1. `xpra opengl`

**System Information (please complete the following information):**
 - Server OS: Manjaro linux
 - Client OS: Manjaro linux
 - Xpra Server Version 5.0.3 (built from source, distro ships 4.4.5)
 - Xpra Client Version 5.0.3

**Additional context**

**Comment by totaam** [comment]
No, OpenGL on Wayland would require a rewrite in EGL.

**Comment by callegar** [comment]
Thanks for confirming my expectation.

One question, out of curiosity, in case you have time to respond. Wayland is EGL, but GLX applications appear to be supported in XWayland. Would it be possible to run the xpra client on wayland in X11 mode via XWayland to have it behave as it normally does on X11?

**Comment by callegar** [comment]
I had tried that, but even selecting the X11 backend, `xpra opengl` still fails. Is that normal?

**Comment by totaam** [comment]
@callegar
```shell
$ xpra --version
xpra v5.0.4-r29
$ GDK_BACKEND=x11 xpra opengl | egrep "success|vendor"
success=True
vendor=NVIDIA Corporation
```

**Comment by callegar** [comment]
Great thanks!

**Comment by callegar** [comment]
As a matter of fact:

```
GDK_BACKEND=x11 xpra opengl
```
does not work here. However
```
XDG_SESSION_TYPE=x11 xpra opengl
```
does.  When `XDG_SESSION_TYPE=wayland` and `GDK_BACKEND=x11` the former seems to win, when maybe it should be the other way round (according to the GTK docs the low-level thing should prevail).

Still I wonder: because Xpra is X11 why not always assuming X11 (at least on the server)? Is there any advantage in not doing so?

**Comment by totaam** [comment]
> because Xpra is X11 why not...

Because it isn't.
On a wayland client desktop you can uninstall `xpra-x11`.

**Comment by totaam** [comment]
Server-side: seamless and desktop / monitor modes do require `xpra-x11`, but desktop portal does not. (`shadow`ing wayland sessions).
