### ISSUE TITLE
Html cannot log with credential - no username define

### ISSUE THREAD

**Issue by docop** [Xpra-org/xpra#4045]
Hi
 While i did can connect with html finely to a server running xpra v3.1.3 , i cannot get it to by using password. I do see the connection client page, but i always end up with the : authentication failed. Also, after searching a lot over past issues and doc and wiki.. there is no mention of username.. only password. But on the login screen it clearly a normal : User and Passorwd field.

 If i try :
```shell
xpra start --bind-tcp=0.0.0.0:9876,auth=pam --html=on --start=mousepad

xpra start --bind-tcp=0.0.0.0:9876,auth=pam -d auth --html=on --start=mousepad

xpra start --bind-tcp=0.0.0.0:9876,auth=sys -d auth --html=on --start=mousepad
```

```shell
xpra start \
    --bind-tcp=0.0.0.0:9876,encryption=AES,auth=file:filename=/home/userxyz/password.txt,keyfile=/home/userxyz/key.txt,auth=sys \
    -d auth,crypto --html=on --start=mousepad
```

And even copy a direct example from past issues. All put on the server side.
```shell
PASSWORD=YOURPASSWORD
AES_KEY=0123456789ABCDEF
echo -n $PASSWORD > $HOME/password.txt
echo -n $AES_KEY > $HOME/key.txt
xpra start :10 --socket-dir=$HOME/sdir --bind-tcp=0.0.0.0:10000,encryption=AES,auth=file:filename=$HOME/password.txt,keyfile=$HOME/key.txt -d auth,crypto --html=on --start=xterm --no-daemon
```
with this, still show login but same error.. user needed ??
```shell
xpra start \
    --bind-tcp=0.0.0.0:9876,encryption=AES,auth=file:filename=/home/userxyz/password.txt,keyfile=/home/userxyz/key.txt \
    -d auth,crypto --html=on --start=mousepad
```
How to define the username ?  And i guess the aes key is not supported for html. but removing still give same issues.
Thanks

**Comment by totaam** [comment]
> a server running xpra v3.1.3

This is not a supported version: https://github.com/Xpra-org/xpra/wiki/Versions

> `...auth=file:filename=/home/userxyz/password.txt,keyfile=/home/userxyz/key.txt,auth=sys`

This is wrong, you're specifying `auth` twice.

> but i always end up with the : authentication failed

Use a supported version and it should work.

> there is no mention of username.. only password

Some authentication modules only require a password, others require both.
The html5 client has no way of knowing in advance and offers both.
`auth=sys` will only allow a different username to be specified if running as root or if the `client-username` authentication module option is set.

> And i guess the aes key is not supported for html

It is, but you should really do one thing at a time and get your authentication working before thinking about enabling AES.

> but same error....

Have a look in your server log file, or run your server with `--no-daemon`.
