### ISSUE TITLE
Screen flashing old content

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#4046]
**Describe the bug**
Since the upgrade to v6.0-r34598 (Debian trixie), windows often flash older content and it takes a while until the window consistently shows the current content instead of flashing between old and new content.

I think it is a regression from 6.0-r34524-1. Before the upgrade to v6.0-r34598 I had no problems at all and 6.0-r34524-1 is the latest earlier version I've found in my dpkg.log.
I didn't test in between versions.

**To Reproduce**
1. xpra start :10
2. xpra attach --ssh=/usr/bin/ssh ssh://user@server/10
3. Normal use.

**System Information (please complete the following information):**
 - Server OS: Debian bookworm (stable)
 - Client OS: Debian trixie (testing)
 - Xpra Server Version 5.0.3-r1-1
 - Xpra Client Version v6.0-r34598

**Additional context**
I'd happy to test suggestions or patches.

**Comment by totaam** [comment]
My guess is that you're running a Wayland desktop and therefore had the new OpenGL backend (#2467), there were known regressions but it should be usable now.

The latest at time of writing is r34629. Please try that first.

**Comment by allo-** [comment]
Sorry for not mentioning, but I am using X11. Will try newer versions later.

**Comment by allo-** [comment]
I'm waiting for a Debian package for the newer version, but I can confirm that a downgrade to the older version removes the problem.

**Comment by totaam** [comment]
> Since the upgrade to v6.0-r34598 (Debian trixie)
(..)
> I'm waiting for a Debian package for the newer version

Just refresh?
```shell
$ cd beta;find . -name "xpra_6.0-r34629*deb" -ls
   948103     44 -rw-r--r--   1 antoine  antoine     44040 Nov  1 16:24 ./bookworm/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
   948139     44 -rw-r--r--   1 antoine  antoine     44040 Nov  1 16:35 ./trixie/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
   948341     68 -rw-r--r--   1 antoine  antoine     67112 Nov  1 18:59 ./jammy/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
   948359     44 -rw-r--r--   1 antoine  antoine     44040 Nov  1 19:03 ./lunar/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
   948121     44 -rw-r--r--   1 antoine  antoine     44040 Nov  1 16:31 ./sid/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
   948377     44 -rw-r--r--   1 antoine  antoine     44040 Nov  1 19:08 ./mantic/main/binary-amd64/xpra_6.0-r34629-1_amd64.deb
```
```

**Comment by allo-** [comment]
Yesterday I did not see it, maybe because of the beta repo?
Anyway, today I see 6.0-r34645-1, but in the meantime even 6.0-r34598-1 worked without flickering again.
I have no idea what's the issue, but I close here as long as I can't reproduce anymore.
