### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by LaurentBonnaud** [Xpra-org/xpra#4048]
Hi,

here is the problem:
```
$ python3 ./setup.py install --prefix=/usr
./setup.py install --prefix=/usr
Xpra version 6.0
found Cython version 0.29.36
*******************************************
please switch to Cython 3.x
 version 0 is not supported
*******************************************
```
My system has this Cython version:
```
$ cython -V
Cython version 3.0.5
```

**Comment by totaam** [comment]
> `found Cython version 0.29.36`

You need Cython 3.x

Please refer to your OS installation instructions.
If you installed it manually, then you did it wrong, it you didn't remove the other version.
