### ISSUE TITLE
XPRA server info request can't be turned off

### ISSUE THREAD

**Issue by EmanH** [Xpra-org/xpra#4053]
**Describe the bug**
The XPRA server responds to info-request with a ton of system diagnostics including all environment variables, startup arguments etc. This is a security vulnerability for production use. In the XPRA html5 client (even with floating_menu turned off) it is trivial to execute a info-request and view all the data. 

Is there a flag or something to turn disable info requests?

Also is there anything else that should be locked down? I'm not fully across all xpra functionality, but is it possible to send an XPRA server a message that would get it to execute an arbitrary command?

**Comment by totaam** [comment]
@EmanH please see:
* https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Security.md
* #3582

**Comment by EmanH** [comment]
@totaam ok, fair enough. Thanks for the quick response. Would be great to have some documentation around `XPRA_FULL_INFO`.

**Comment by totaam** [comment]
That ticket **is** the documentation, otherwise you can submit a PR.

**Comment by totaam** [comment]
This was actually implemented in 7417717b837bdb86f22d8caef177a594cebce7ff, see commit message for usage.
