### ISSUE TITLE
Remote window has dead zones for touch on the right + bottom part of the monitor

### ISSUE THREAD

**Issue by mad-ady** [Xpra-org/xpra#4054]
**Describe the bug**
I'm using Xpra 5.0.3 on Windows 10 to connect to Xpra 4.4.4-r0 running on Ubuntu 22.04. The windows desktop has a resolution of 1920x1080. 
Sometimes the window content doesn't register clicks inside at the correct coordinates. For instance, if the window is maximised (a remote Firefox, but happens with other apps as well), when I try to click inside the window past 1500px on the x axis and past 860px on the y axis, the clicks register at 1500 and 860 (are limited by these bounds) (also happens to hover actions). The window renders correctly though.
What's interesting is that the bug happens even when the Xpra client window is not maximized. If I position the smaller window past the above coordinates, I get the same behavior - no clicks past those coordinates. Clicks on the windows title bar work as expected.

**To Reproduce**
1. server command: `XPRA_ACK_TOLERANCE=1000 xpra start :100 --systemd-run=no --start-via-proxy=no`
2. client command: launch xpra and attach via ssh to the remote host on display 100
3. specific action to trigger the bug: nothing in particular

**System Information (please complete the following information):**
 - Server OS: [e.g. Ubuntu 22.04]
 - Client OS: [e.g. Windows 10]
 - Xpra Server Version [e.g. 4.4.4-r0]
 - Xpra Client Version [e.g. 5.0.3]

**Additional context**
Please see "reporting bugs" in the wiki section.

I am willing to debug further if needed. Otherwise, I think I can downgrade the client to match the server, which I expect will solve the issue.
Thanks!

**Comment by totaam** [comment]
> I think I can downgrade the client to match the server, which I expect will solve the issue.

That's very unlikely.

> `connect to Xpra 4.4.4-r0`
4.4.x is not a supported version.

Please try a tier-1 distro.
Debian and Ubuntu have two many issues due to their lack of Xdummy support.

**Comment by mad-ady** [comment]
Thank you for the suggestions. The 4.4.4-r0 was last build from sources, if I remember correctly. Which xpra version do you recommend for the server? Alas, changing the distribution on the server is too much of a challenge :)

P.S. The issue doesn't happen always. I reconnected and now I can click on the edges...

Hmm, this is weirder - the client is on a laptop. I get the issue while the laptop is not docked (it has only its main display). When I connect it to a docking station and effectivelly have 3 displays (not mirrored), the same xpra session starts working (no reconnection is done), and keeps working on any monitor (so far the issue hasn't happened again with multiple screens). 

Each display is 1920x1080, and the laptop screen has scaling set to 125% (in windows), while the physial displays have 100% scaling.
I played some more with the scaling option. When using only the laptop screen, with scaling to 150% and reconnecting to xpra, I still get the issue, but it seems the coordinates of the cutoff are smaller this time (more proeminent issue). 
With scaling set to 100% and only the laptop display, I still get the issue. So - it might not be scaling related, but it was worth a try.

Let me know if you want me to upgrade the server, or collect logs on this combination of client/server.

Thanks for the help!

**Comment by totaam** [comment]
> Which xpra version do you recommend for the server?

The current support version: https://github.com/Xpra-org/xpra/wiki/Versions
At time of writing, that's 5.0.4

> When using only the laptop screen, with scaling to 150% and reconnecting to xpra, I still get the issue, but it seems the coordinates of the cutoff are smaller this time

That's likely to be yet another MS Windows DPI issue, see:
https://github.com/Xpra-org/xpra/blob/master/docs/Features/DPI.md
https://github.com/orgs/Xpra-org/discussions/4062#discussioncomment-7737740

**Comment by totaam** [comment]
Not heard back.
