### ISSUE TITLE
pam module is not POSIX anymore

### ISSUE THREAD

**Issue by arrowd** [Xpra-org/xpra#4057]
The `pam` module is currently enabled by following logic:

```
pam_ENABLED = DEFAULT and (server_ENABLED or proxy_ENABLED) and POSIX and not OSX ...
```

However, it can't be compiled at least on FreeBSD because there is no `libpam_misc` (although we do have `openpam_nullconv()`) and `pam_xauth`. I ended up disabling it on FreeBSD, but maybe the module can be adapted to work on non-Linux OS's too.

**Comment by totaam** [comment]
`and not BSD` should be added here, assuming none of the BSDs have it.
Can you send a PR?

**Comment by arrowd** [comment]
Sure, but I was hoping it'd be possible to adapt the code for FreeBSD.

What does this module do specifically?

**Comment by totaam** [comment]
`pam_ENABLED` will compile this file:
https://github.com/Xpra-org/xpra/blob/master/xpra/server/pam.pyx

Which essentially wraps:
https://github.com/Xpra-org/xpra/blob/816b73087e1a7c7c36c1f1cf0574c47409c64618/xpra/server/pam.pyx#L179
https://github.com/Xpra-org/xpra/blob/816b73087e1a7c7c36c1f1cf0574c47409c64618/xpra/server/pam.pyx#L251
https://github.com/Xpra-org/xpra/blob/816b73087e1a7c7c36c1f1cf0574c47409c64618/xpra/server/pam.pyx#L263
https://github.com/Xpra-org/xpra/blob/816b73087e1a7c7c36c1f1cf0574c47409c64618/xpra/server/pam.pyx#L273

**Comment by arrowd** [comment]
I figured as much, but it doesn't explain how Xpra uses PAM. What features would FreeBSD users lose if I just turn the option off?

**Comment by totaam** [comment]
> I figured as much, but it doesn't explain how Xpra uses PAM

Authentication via pam:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md#server-authentication-modules

And pam login for creating new sessions via the proxy server:
https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Proxy-Server.md
