### ISSUE TITLE
Xpra v5.0.4 about page not working

### ISSUE THREAD

**Issue by Simba98** [Xpra-org/xpra#4061]
**Describe the bug**
Connect to a server and click the About Xpra.
```
Traceback (most recent call last):
  File "E:/xpra/xpra/gtk_common/about.py", line 67, in about
TypeError: second argument must be callable
```

**System Information (please complete the following information):**
 - Client OS: Windows 11 22H2
 - Xpra Client Version v5.0.4

**Additional context**
I used the exe installer to update it from v5.0.3.

**Comment by totaam** [comment]
Ooops, fixed in the commit above. This will be included in 5.0.5
