### ISSUE TITLE
 How can I modify the configuration parameters network.config.socket.timeout=20 and network.config.vsocket.timeout=5 in xpra version 3.1.5?

### ISSUE THREAD

**Issue by junjie0510** [Xpra-org/xpra#4065]
**Is your feature request related to a problem? Please describe.**

xpra 3.1.5
1.  `vim /etc/xpra/xpra.conf`
add
```
network.config.socket.timeout=60
network.config.vsocket.timeout=50
```

```shell
 xpra info
Warning: invalid option: 'network.config.socket.timeout'
Warning: invalid option: 'network.config.vsocket.timeout'
```

2.  `vim /etc/xpra/xpra.conf`
add
```
socket.timeout=60
vsocket.timeout=30
```

```shell
xpra info
Warning: invalid option: 'socket.timeout'
Warning: invalid option: 'vsocket.timeout'
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by junjie0510** [comment]
xpra info | egrep -i "network|latency" | grep timeout

Warning: running as root
network.config.socket.timeout=20
network.config.vsocket.timeout=5
network.system.ipv4.tcp.fin_timeout=60
network.system.ipv4.tcp.thin_linear_timeouts=True

**Comment by totaam** [comment]
https://github.com/Xpra-org/xpra/blob/50d19d99b0f52ec4a1934cc0db6ce60749da98d5/xpra/net/net_util.py#L317-L320
Which comes from:
https://github.com/Xpra-org/xpra/blob/50d19d99b0f52ec4a1934cc0db6ce60749da98d5/xpra/net/bytestreams.py#L37-L38
ie:
`XPRA_VSOCK_TIMEOUT=10`

But generally speaking, changing these options is not recommended. What are you trying to solve?

**Comment by junjie0510** [comment]
@totaam resolve the issue of "server connection lost" caused by network jitter

log
2023-12-06 01:27:56,923 - INFO - util.py:112 : 331248 b'2023-12-06 01:27:56,923 running, 1 window\r\n'
2023-12-06 01:35:12,235 - INFO - util.py:112 : 331248 b'2023-12-06 01:35:12,235 Xpra Session Disconnected: server shutdown\r\n'
2023-12-06 01:35:12,235 - INFO - util.py:112 : 331248 b'2023-12-06 01:35:12,235  server connection lost\r\n'
2023-12-06 01:35:12,235 - INFO - util.py:112 : 331248 b'2023-12-06 01:35:12,235 server requested disconnect:\r\n'
2023-12-06 01:35:12,235 - INFO - util.py:112 : 331248 b'2023-12-06 01:35:12,235  server shutdown\r\n'
2023-12-06 01:35:12,235 - INFO - util.py:112 : 331248 b'2023-12-06 01:35:12,235  server connection lost\r\n'

**Comment by totaam** [comment]
Please read the comment above.
Unless proven otherwise, you don't need to change the socket timeout.
And you certainly don't need to change the vsock timeout since you're using windows10, which is very unlikely to have vsock support.
And 3.1.5 is not a supported version for MS Windows 10.
Whatever you're trying to do, go back to the beginning.
