### ISSUE TITLE
Applications run under Xpra have altered PATH - can we run with unaltered PATH?

### ISSUE THREAD

**Issue by Rush-iam** [Xpra-org/xpra#4076]
Xpra adds `/usr/libexec/xpra` to the `PATH` environment variable for its needs. But it is also inherited by applications run under Xpra, though it may not be desired.

My use case is the [Bazel](https://bazel.build/) build system, which is set to be sensitive to changes in the `PATH` variable - it invalidates and clears the build cache on a change.

Is there a way to run an application under Xpra with the original `PATH`? Or I'd like to ask you for such a feature.

**Comment by totaam** [comment]
Use `--forward-xdg-open=no`.
We modify the `$PATH` to override the `xdg-open` binary so that we can intercept and potentially forward the requests to the client.
https://github.com/Xpra-org/xpra/blob/6e7fe1a361d1343b40bf48b9195bbe4ef317cd2b/xpra/scripts/server.py#L1424-L1434
