### ISSUE TITLE
Xpra client on Ubuntu derivative unable to connect to Xpra server

### ISSUE THREAD

**Issue by BRTPOB** [Xpra-org/xpra#4084]
**Describe the bug**
At this point I don't think it's a bug, it's more of a question of something missing. Attempting to connect to an Xpra server on Pop!_OS (Ubuntu derivative) I'm getting an error message about unable to bencode the received packet.

**To Reproduce**
1. Run server normally.
2. Attempt to connect with `xpra --desktop-scaling=off --speaker=disabled --microphone=disabled attach tcp://IP:3388/10`

**System Information (please complete the following information):**
 - Server OS: Ubuntu server (Docker)
 - Client OS: Pop!_OS 22.04 LTS
 - Xpra Server Version xpra v3.0.6-r25177
 - Xpra Client Version xpra v5.0.4-r0M

**Additional context**
As mentioned, I don't think this is a bug since I can easily connect via Windows, but the Linux version is throwing this error:
```
2023-12-25 14:04:14,931 Error: failed to connect
2023-12-25 14:04:14,931  received uninterpretable nonsense: invalid packet header byte: 0x646973636f6e6e65
2023-12-25 14:04:14,931  b'disconnect: failed to parse bencode packet\n' (43 bytes)
2023-12-25 14:04:14,931  data: 'disconnect: failed to parse bencode packet'
```
I'd love to figure out what the missing thing is so I can get this working again.

**Comment by totaam** [comment]
3.0.6 is not a supported version: https://github.com/Xpra-org/xpra/wiki/Versions
Use  a current version and it will just work.
