### ISSUE TITLE
TypeError: xid must be an int, not a <class 'gi.repository.GdkX11.X11Window'>

### ISSUE THREAD

**Issue by cpatulea** [Xpra-org/xpra#4087]
**Describe the bug**
When running start-desktop, at some point during server startup, there's this error:
```
2023-12-29 17:40:22,123 randr=True
2023-12-29 17:40:22,123 _XPRA_RANDR_EXACT_SIZE=None
2023-12-29 17:40:22,123 get_xrr_screen_sizes()=[(8192, 4096)]
2023-12-29 17:40:22,123 Error: <class 'TypeError'>, xid must be an int, not a <class 'gi.repository.GdkX11.X11Window'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 170, in x11_init
    self.init_randr()
  File "/usr/lib/python3/dist-packages/xpra/x11/x11_server_core.py", line 206, in init_randr
    prop_set(self.root_window, "_XPRA_RANDR_EXACT_SIZE", "u32", 1)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/prop.py", line 73, in prop_set
    raw_prop_set(xid, key, dtype, dformat, data)
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/prop.py", line 77, in raw_prop_set
    raise TypeError(f"xid must be an int, not a {type(xid)}")
TypeError: xid must be an int, not a <class 'gi.repository.GdkX11.X11Window'>
```

~The server seems in an incomplete start state - it can be connected (via html5 client on port :10000) but there's no windows, no window decoration (even if starting a command separately), and lacking the usual html5 client window management menus.~ The server seems mostly running. (No window decoration: seems normal, I am able to get the window decoration back using 'xpra start'; lacking menus: seems like #4005)

**To Reproduce**
1. xpra start-desktop --bind-tcp=:10000 --start=gnome-session --daemon=no -d all --systemd-run=no

**System Information (please complete the following information):**
 - Server OS: Debian 11
 - Client OS: N/A
 - Xpra Server Version 5.0.3-r1-1
 - Xpra Client Version N/A

**Additional context**
- I think this bug was introduced during xid refactoring in commit https://github.com/Xpra-org/xpra/commit/1994b3047f0921a6c2cc948e2db49ee1a6e2a8a6
- The bug appears to still be present at HEAD
- I plan to send a pull request, but filing this issue report anyway in case to provide details on the problem and in case anyone encounters the same issue in the future

**Comment by totaam** [comment]
Thanks for the PR.

This code path is only used on Debian and Ubuntu since those use are unable to use Xdummy and that explains why I never hit this during testing.

But I don't really understand why I didn't hit the issue with `do_clean_x11_properties` as this one is definitely used by all server variants, no matter what vfb backend is used. Oh well.

**Comment by cpatulea** [comment]
Nice, thanks for the context and merge.
