### ISSUE TITLE
Command line docu

### ISSUE THREAD

**Issue by adimetrius** [Xpra-org/xpra#4094]
I cannot find an .md or whatever under the Docu that would show the same info as xpra --help, so as to review it in a format more convenient than a terminal emulator. Please direct me.

**Comment by totaam** [comment]
There isn't one.

**Comment by adimetrius** [comment]
How come? Are you saying it's nailed in the source code? (I actually tried to search the repo for "show program's version number and exit", to no avail)

**Comment by totaam** [comment]
```shell
$ xpra -h | grep '\--version'
  --version             show program's version number and exit
```
Also present in the man page.
