### ISSUE TITLE
lightweigth win32 installations

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4100]
Rather than having regular and "client" builds, with very little difference between them in terms of disk space:
```shell
$ du -sm \
    dists/windows/Xpra-Client-x86_64_Setup_5.0.4-r0.exe \
    dists/windows/Xpra-x86_64_Setup_5.0.4-r0.exe
123	dists/windows/Xpra-Client-x86_64_Setup_5.0.4-r0.exe
138	dists/windows/Xpra-x86_64_Setup_5.0.4-r0.exe
```
(the disk space actually used when installed is closer to 2GB, which is just ridiculous)

Split them into regular and "lightweigth" builds and remove more than just the server components: putty, remove all cuda and nvidia modules, all the video encoders, numpy (as long as pyopengl still works), ffmpeg codecs used by gstreamer, etc..
Use this as an exercise to also remove libraries we don't really need: clang / llvm?, libicu?, openblas, opencv, etc

This will also help with #4050

**Comment by totaam** [comment]
With this initial commit, the size of the "Minimal" builds are now just:
* installation directory: 181MB
* EXE: 49MB
* ZIP: 71MB

Due to diminishing returns, I think the bulk of the savings are already implemented.

Still TODO:
* rename to "Light" builds?
* gstreamer: remove video encoder, add build toggle for it?
* remove `enc_rgb`?
* toolbox doesn't run - remove it from minimal builds?
* update the upload and release scripts, wiki, etc..

**Comment by totaam** [comment]
Comparing with v5.x at 1d716ad76ca779ec0e10514dfbd0e5b7f9c77313:
```shell
$ du -sm beta/windows/*5.0.8-r9.{exe,zip}
126	beta/windows/Xpra-Client-x86_64_Setup_5.0.8-r9.exe
141	beta/windows/Xpra-x86_64_Setup_5.0.8-r9.exe
177	beta/windows/Xpra-Client-x86_64_5.0.8-r9.zip
199	beta/windows/Xpra-x86_64_5.0.8-r9.zip
```

**Comment by totaam** [comment]
v5 is done and is almost as good as v6!
```
$ du -sm beta/windows/Xpra*5.0.8-r10*.{zip,exe}
78	beta/windows/Xpra-Light-x86_64_5.0.8-r10.zip
56	beta/windows/Xpra-Light-x86_64_Setup_5.0.8-r10.exe
```

However, v3.x is still absolutely massive:
```
$ du -sm Xpra*3.1.7-r77M*.{zip,exe}
349	/home/antoine/Shared/Xpra-Client-Python3-x86_64_3.1.7-r77M.zip
224	/home/antoine/Shared/Xpra-Client-Python3-x86_64_Setup_3.1.7-r77M.exe
```
And the installed size is ridiculous (almost 1TB!) - mostly because of opencv (#3336):
```
$ du -sm Xpra-Client-Python3-x86_64_3.1.7-r77M
973	Xpra-Client-Python3-x86_64_3.1.7-r77M
```

**Comment by totaam** [comment]
The big difficulty with 3.x is that we have to ship `ffmpeg` to be able to decode `h264` (the `dec_avcodec2` decoder), whereas v5.x has `openh264`.
And `ffmpeg` brings in tons of dependencies, big ones too, so the resulting installation was still over 800MB!
So much so that we used to build our own `ffmpeg` package with trimmed down dependencies (#3166), just like we still do on MacOS.
But this was just too much effort to manage properly.

So I've decided to also remove `ffmpeg` from the "light" builds in v3.x - `vp8` / `vp9` are decent alternatives anyway, and truly free too. One could consider backporting `openh264` to this branch, as it is self-contained.
Anyone really needing `h264` can use the fat builds, or even better: a newer version.

There are still a few more stray DLLs in this version than the newer branches, but the "Light" build size is now much more reasonable:
```shell
$ du -sm beta/windows/Xpra*r84*.{zip,exe}
107	beta/windows/Xpra-Light-Python3-x86_64_3.1.7-r84.zip
73	beta/windows/Xpra-Light-Python3-x86_64_Setup_3.1.7-r84.exe
```

**Comment by totaam** [comment]
And within 24 hours of closing this ticket, an MSYS2 update brings in GStreamer version 1.24.0, which causes some new breakage - with a dialog alter box shown for every missing DLL!:
```
(Xpra_Audio.exe:1052): GStreamer-WARNING **: 20:48:51.306: Failed to load plugin 'C:\Program Files\Xpra\lib\gstreamer-1.0\libgstd3d11.dll': The specified procedure could not be found.

(Xpra_Audio.exe:1052): GStreamer-WARNING **: 20:48:51.837: Failed to load plugin 'C:\Program Files\Xpra\lib\gstreamer-1.0\libgstisomp4.dll': The specified procedure could not be found.

(Xpra_Audio.exe:1052): GStreamer-WARNING **: 20:48:53.017: Failed to load plugin 'C:\Program Files\Xpra\lib\gstreamer-1.0\libgstd3d11.dll': The specified procedure could not be found.

(Xpra_Audio.exe:1052): GStreamer-WARNING **: 20:48:53.884: Failed to load plugin 'C:\Program Files\Xpra\lib\gstreamer-1.0\libgstisomp4.dll': The specified procedure could not be found.
```

**Comment by totaam** [comment]
Though not as dramatic as v6, the 3.1.7 release got some significant weight loss:
```shell
du -sm Xpra*3.1.7*
73	Xpra-Light-Python3-x86_64_3.1.7-r0.msi
107	Xpra-Light-Python3-x86_64_3.1.7-r0.zip
72	Xpra-Light-Python3-x86_64_Setup_3.1.7-r0.exe
209	Xpra-Python3-x86_64_3.1.7-r0.msi
307	Xpra-Python3-x86_64_3.1.7-r0.zip
208	Xpra-Python3-x86_64_Setup_3.1.7-r0.exe
```

**Comment by stdedos** [comment]
> @stdedos you may be interested in using these builds if you don't have any nvidia GPUs in your clients.

I do, but what's the benefit of "supporting" nvidia? CPU offload?

**Comment by totaam** [comment]
> I do, but what's the benefit of "supporting" nvidia? CPU offload?

Very fast GPU encoding and decoding.
For a client, that means accelerated `jpeg` decoding via `nvdec` or `nvjpeg`.
