### ISSUE TITLE
Connecting to an Xpra host using a Microsoft Surface Book detaches tablet from dock

### ISSUE THREAD

**Issue by BRTPOB** [Xpra-org/xpra#4101]
**Describe the bug**
For some reason, whenever connecting to an Xpra host, the Surface Book will begin the detaching process and will only complete once Xpra is disconnected and shut down on the machine.

**To Reproduce**
1. Get a Microsoft Surface Book
2. Install Xpra
3. Successfully connect to an Xpra host

**System Information (please complete the following information):**
 - Server OS: Ubuntu 23.10
 - Client OS: Windows 10
 - Xpra Server Version: v5.0.4
 - Xpra Client Version v5.0.4

**Additional context**
I'm not sure what is causing this, but I can repro it 100%. I've rebooted numerous times, both the host and the client and the behavior is still seen.

**Comment by totaam** [comment]
> Get a Microsoft Surface Book

Not going to happen unless someone sponsors one.

You can try running the latest beta client builds with  `--minimal` to see if turning everything off helps.
There are also a bunch of native API toggles you may want to try turning off:
https://github.com/Xpra-org/xpra/blob/2d586b41cd3d1d7503d48b66b15b397d8ff4dc58/xpra/platform/win32/gui.py#L62-L67

Good luck.

**Comment by totaam** [comment]
Not heard back.
