### ISSUE TITLE
NameError: name 'get_default_port' is not defined. Did you mean: 'get_defaults'?

### ISSUE THREAD

**Issue by al1ta** [Xpra-org/xpra#4104]
**Describe the bug**
starting a remote ssh session with xpra 5.0.4-10.r0.fc38.x86_64 fails with the following error logged at console
```
splash=True (<class 'bool'>) - not None (<class 'NoneType'>)
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/gtk_common/start_gui.py", line 591, in runattach_command
    self.do_run(True)
  File "/usr/lib64/python3.11/site-packages/xpra/gtk_common/start_gui.py", line 594, in do_run
    cmd = self.get_run_command(attach)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/gtk_common/start_gui.py", line 676, in get_run_command
    if port and port!=get_default_port(mode):
                      ^^^^^^^^^^^^^^^^
NameError: name 'get_default_port' is not defined. Did you mean: 'get_defaults'?
```

**To Reproduce**
from client terminal
1. run xpra
2. click on start button
3. choose seamless session, flag remote host, choose ssh protocol, fill user name , port 22, fill command with something like xcalc
4. click start or start+attach, error is shown at console. remote session never starts

**System Information (please complete the following information):**
 - Client OS: [fedora workstation 38]
 - Xpra Client Version [5.0.4-10.r0.fc38.x86_64]

**Additional context**
tested with fedora workstation 38
repo configured
```
cat /etc/yum.repos.d/xpra.repo 
[xpra]
name=Xpra $releasever - $basearch
enabled=1
metadata_expire=1d
gpgcheck=1
gpgkey=https://xpra.org/xpra.asc
baseurl=https://xpra.org/dists/Fedora/$releasever/$basearch/

rpm -qa | grep xpra
xorg-x11-drv-dummy-0.4.1-1.xpra1.fc38.x86_64
xpra-common-5.0.4-10.r0.fc38.x86_64
xpra-client-5.0.4-10.r0.fc38.x86_64
xpra-codecs-5.0.4-10.r0.fc38.x86_64
xpra-x11-5.0.4-10.r0.fc38.x86_64
xpra-audio-5.0.4-10.r0.fc38.x86_64
xpra-client-gtk3-5.0.4-10.r0.fc38.x86_64
xpra-server-5.0.4-10.r0.fc38.x86_64
xpra-html5-10-1.r9.fc38.noarch
xpra-5.0.4-10.r0.fc38.x86_64
```

**Comment by al1ta** [comment]
as workaround, commenting lines at  :676 /usr/lib64/python3.11/site-packages/xpra/gtk_common/start_gui.py

#if port and port!=get_default_port(mode):
#               uri += ":%s" % port


allow xpra to work

**Comment by totaam** [comment]
Thanks. Fixed in the commit above.

The whole point of that line is that you don't need to specify a default port.
So you don't need to specify `22` when using `ssh` mode.
