### ISSUE TITLE
Failure to build xpra without nvcc

### ISSUE THREAD

**Issue by gl-yziquel** [Xpra-org/xpra#4105]
Hi.

I recently got hold of a linux without any GPU. nvcc is not installed on that box.

This makes the python setup.py build instruction fail.

```console
'nvcc --version' failed with return code 127
```

Is there anyway to build xpra from source without nvcc installed ?

**Comment by gl-yziquel** [comment]
I tried --without-cuda, as gleaned from other issues. Didn't help. Not sure I really know what the good command line is, in fact...

Is there any way to provide a command line invocation that builds only the core xpra server (and nothing else) with the most minimal amount of options, ensure a safe build ?

I'd rather remove all bell and whistles in order to have just what I need: an xpra server, functional, no matter how slow.

**Comment by totaam** [comment]
> I tried --without-nvidia, as gleaned from other issues. Didn't help.

Please post the full error messages. `--without-nvidia` should work, it does here.

Assuming that you're building from the v5.x branch, try `--without-nvidia --without-nvenc --without-nvjpeg`
Related: c388d6930de7d49da768fca5f27ed39b262c7013

> most minimal amount of options, ensure a safe build

`./setup.py --minimal`

> I'd rather remove all bell and whistles in order to have just what I need

Please make sure to mention that at the very top when reporting issues as this will trigger unusual bugs.
