### ISSUE TITLE
Tray Icon > About dialog doesn't open

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4119]
**Describe the bug**

![image](https://github.com/Xpra-org/xpra/assets/133706/ca7cb8ac-ff87-4f6f-b9de-7444294f8959)

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

**System Information (please complete the following information):**
- Server OS: Ubuntu 20.04.6 LTS
- Client OS: Microsoft Windows [Version 10.0.18363.836]
- Xpra Server Version: 5.0.5-r27-1
- Xpra Client Version: (see above)

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Already queued for v5.0.5: 356dda7aa3fcba9a1ca23e2875dc6ee1c6f13009
(not sure if r27 has it or not, please include the full `xpra --version` to check)

**Comment by stdedos** [comment]
```
$ xpra --version
xpra v5.0.5-r27
```

I used to be able to get xpra-beta updates also on the deb server.
You don't do them anymore, it's a known pause - or the deb-betas are stopped?

**Comment by stdedos** [comment]
Duplicate of https://github.com/Xpra-org/xpra/issues/4061

**Comment by stdedos** [comment]
Totally random tidbit: You might be interested in https://github.com/tibdex/backport GitHub action
