### ISSUE TITLE
Try to avoid removing `xpra/<screen>/` on destroy

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4121]
**Is your feature request related to a problem? Please describe.**

It could be that the logs provide some _useful_ information - even when we are talking about disconnect.

**Describe the solution you'd like**

It might be better to garbage-collect them after-the-fact, instead of "at disconnect"?

Also, it might be nice to append them a date/time?

**Describe alternatives you've considered**

**Additional context**

... I think we've talked about this before 😅

But I cannot remember/grok how to modify

https://github.com/Xpra-org/xpra/blob/f12369ad493b0987cd62c1baca24b1067183e657/fs/etc/xpra/conf.d/60_server.conf.in#L4-L8

to make it work 😓

**Comment by totaam** [comment]
> It might be better to garbage-collect them after-the-fact, instead of "at disconnect"?

The session directory is cleaned up after the session is terminated, not "at disconnect" - though it ends up being "at disconnect" for remote shadow sessions since those normally enable `--exit-with-client` automatically, you can use `--exit-with-client=no` to override this behaviour.
Setting `log-dir = /tmp` should also work.

**Comment by stdedos** [comment]
> Setting `log-dir = /tmp` should also work.

Should work, because ... `rm -rf /1/`, but not `rm -rf %(log-dir)/%(log-file)`?

**Comment by totaam** [comment]
> Should work, because ... `rm -rf /1/`, but not `rm -rf %(log-dir)/%(log-file)`?

I don't understand what that means.
We don't `rm -rf`, but only carefully remove the files we know we have created and no longer need, then the session directory if that's all that's left.

**Comment by stdedos** [comment]
I'd say log file is definitely needed 😅 

But anyhow - if the log files are moved _somewhere_, and _somehow_ get date-stamped - xpra won't remove them "no matter what", right?

**Comment by totaam** [comment]
We have to remove session files at some point.

> if the log files are moved somewhere, and somehow get date-stamped - xpra won't remove them "no matter what", right?

I don't understand what you're saying.
Once you copy them anywhere, they become your responsibility to cleanup.
The date stamp is maintained by the filesystem. (creation date, last modified date)

**Comment by stdedos** [comment]
> We have to remove session files at some point.

`/run` is a tmpfs system, so ... it will be rotated on reboot 😅 

> I don't understand what you're saying.

If I move log files to `/tmp/xpra/<screen>-<datetime>.log`, xpra will not remove them as part of its cleanup, right?
