### ISSUE TITLE
(In)Release file out of date for the beta/jammy repo

### ISSUE THREAD

**Issue by jzyrobert** [Xpra-org/xpra#4123]
**Describe the bug**
The https://xpra.org/beta/jammy/Release and https://xpra.org/beta/jammy/InRelease files were last updated on 31/01 but the Packages.gz file at https://xpra.org/beta/jammy/main/binary-amd64/Packages.gz was updated on 01/02, meaning that the expected sha256 is wrong and apt will refuse to update the repo.

**To Reproduce**
1. Add the beta Xpra repo as an apt source
2. Try running `apt update`
3. See the error 
```
Failed to fetch https://xpra.org/beta/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (11993 != 10743). Mirror sync in progress?
   Hashes of expected file:
    - Filesize:10743 [weak]
    - SHA512:a2652092905506c88cf199e0433ca15677bc95778551a083635d304de6caac567e16ba4b006911cf6dc77c3f05f16051a1ff020670f1cc371806a96aa5698531
    - SHA256:0962abeef30f60803533ee74a89fafee7ba8e028fce94094177ab484420923e5
    - SHA1:7af05e80dcb5d6287401d7edc986a4bdbbbc032d [weak]
    - MD5Sum:9d51e55c80e58ebe095a1f1cbef37ae4 [weak]
   Release file created at: Wed, 31 Jan 2024 10:15:24 +0000
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS: Windows 10 (not relevant)
 - Xpra Server Version: 5.0.4 (not relevant)
 - Xpra Client Version: 5.0.4 (not relevant)

**Comment by totaam** [comment]
Sorry about that, no idea how it happened - again...

I've regenerated all the files.
