### ISSUE TITLE
systemd[39455]: xpra.socket: Failed to create listening socket ([::]:14500): Address already in use

### ISSUE THREAD

**Issue by narfa0215** [Xpra-org/xpra#4124]
When attempting to start the xpra-server.service, the system reports the error message: `systemd[39455]: xpra.socket: Failed to create listening socket ([::]:14500): Address already in use`.
Upon reviewing the installation logs from `apt install xpra`, it was found that the following entry exists: _Created symlink /etc/systemd/system/sockets.target.wants/xpra-server.socket → /lib/systemd/system/xpra-server.socket._ This entry causes a conflict with the service. The solution to this problem is to remove the `/etc/systemd/system/sockets.target.wants/xpra-server.socket` file and restart the computer. Please address this issue by avoiding the creation of this symlink to prevent future conflicts.

**Comment by narfa0215** [comment]
Additionally, it needs to be clarified: what are the differences between xpra-server.service and xpra.service? Can xpra-server.service be enabled by default, or are there other viable solutions?

**Comment by totaam** [comment]
> The solution to this problem is to remove the `/etc/systemd/system/sockets.target.wants/xpra-server.socket` file and restart the computer

No, this only stops xpra's proxy service from starting.

What you need to figure out is what else is claiming that port.
In any case, there's not enough information to act on, please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by narfa0215** [comment]
You can try these steps in a Docker container or a virtual machine. The version is Ubuntu 22.04. Run the following commands:
`DISTRO=jammy
#install https support for apt (which may be installed already):
apt update
apt install apt-transport-https software-properties-common
apt install ca-certificates
# add xpra GPG key:
wget -O "/usr/share/keyrings/xpra.asc" https://xpra.org/xpra.asc
# add the xpra repository:
wget -O "/etc/apt/sources.list.d/xpra.sources" https://xpra.org/repos/$DISTRO/xpra.sources
# add the optional beta channel:
# wget -O "/etc/apt/sources.list.d/xpra-beta.sources" https://xpra.org/repos/$DISTRO/xpra-beta.sources
# install the xpra package:
apt update
apt install xpra
`
To start the service using systemctl start xpra-server, you might encounter the error "systemd[39455]: xpra.socket: Failed to create listening socket ([::]:14500): Address already in use."

If you delete /etc/systemd/system/sockets.target.wants/xpra-server.socket, run systemctl enable xpra-server, and restart the computer, you should be able to access https://127.0.0.1:14500/ using a browser. Otherwise, you won't be able to access it.

I noticed that my issue has been marked as invalid, but I still believe it's a valid concern. If possible, please reconsider and consider reopening the issue for further discussion. Thank you!

**Comment by totaam** [comment]
The xpra proxy service is socket activated, that's what `xpra.socket` does.
You don't need to start the server, just connect to the socket and systemd will start the server.

**Comment by MortenVinding** [comment]
I have the same problem.
Clean install of Xpra from:
https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/jammy/xpra.sources

So systemd is listning on 14500 but as soon as I try to connect to it it fails because it can't spawn the server on port 14500...

Changing the proxy server to listen on port 8080 instead solves the problem:
systemctl edit --full xpra-server.socket

#ListenStream=14500
ListenStream=8080

**Comment by totaam** [comment]
My build logs show that Ubuntu 22.04 is using `sd_listen`:
```
$ grep '* sd_listen' logs/ubuntu-jammy.log 
* sd_listen            : Yes
* sd_listen            : Yes
* sd_listen            : Yes
* sd_listen            : Yes
* sd_listen            : Yes
```
And based on this, the build will include the socket activated version of the service file:
https://github.com/Xpra-org/xpra/blob/3e0cd938ce9d913237483ac9b44a30b990e0e997/setup.py#L1983-L1989
As well as the socket file:
https://github.com/Xpra-org/xpra/blob/3e0cd938ce9d913237483ac9b44a30b990e0e997/setup.py#L1992-L1993

---

After a clean install, I see that they're there.
**But** there are also some extra duplicate files...
Probably the result of split packaging and Debian's automagic packaging scripts.
The commits above should fix that.

**Comment by MortenVinding** [comment]
> Until this lands in a stable release near you, you can just nuke all the `xpra*.service` and `xpra*.socket` files and use the latest ones instead:
> 
>     * [xpra-server.service](https://github.com/Xpra-org/xpra/blob/8d091417d1e415bc1c8b60fcdd666a83c7c8c5b5/packaging/debian/xpra/xpra-server.service)
> 
>     * [xpra-server.socket](https://github.com/Xpra-org/xpra/blob/8d091417d1e415bc1c8b60fcdd666a83c7c8c5b5/packaging/debian/xpra/xpra-server.socket)

Thanks a lot @totaam that solved it :)

Now I have a new problem: we are using FreeIPA to manage user permissions.
So the users are not effectively created on the server until first login.

But I have created following FR to track that: https://github.com/Xpra-org/xpra/issues/4141
