### ISSUE TITLE
Debian repository broken

### ISSUE THREAD

**Issue by anotherthomas** [Xpra-org/xpra#4126]
**Describe the bug**
The debian repository is not set up correctly.
The error message is:
`Failed to fetch https://xpra.org/dists/focal/main/binary-amd64/Packages.gz  File has unexpected size (10511 != 9123). Mirror sync in progress?`

**To Reproduce**
Run the following in e.g. a ubuntu:20.04-image: 
```
apt update
apt install -y software-properties-common wget
wget -qO - https://xpra.org/gpg.asc | apt-key add -
add-apt-repository 'deb [arch=amd64] https://xpra.org/ focal main'
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu
 - Xpra Server Version any

**Comment by totaam** [comment]
Worked for me.

I guess that the repository sync was in progress when you tried.

I've re-generated the repo data just in case, can you try again?

**Comment by totaam** [comment]
Hopefully, finally fixed: https://github.com/Xpra-org/xpra/issues/4170#issuecomment-2014260048
