### ISSUE TITLE
Debian repository broken

### ISSUE THREAD

**Issue by darg-2036** [Xpra-org/xpra#4128]
**Describe the bug**

Receiving the following error message:

```
Err:14 https://xpra.org jammy/main amd64 Packages
  File has unexpected size (11520 != 10446). Mirror sync in progress?
```

**To Reproduce**

See #4126

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Xpra Server Version any

**Comment by totaam** [comment]
This keeps happening (#4126) and I don't know why.

Please just refresh.

**Comment by totaam** [comment]
I think this is now more permanently fixed: https://github.com/Xpra-org/xpra/issues/4170#issuecomment-2014260048
