### ISSUE TITLE
Assertion error: "exit-with-children was specified but start-child* is missing!" when used with --start-child-late

### ISSUE THREAD

**Issue by jeffmax** [Xpra-org/xpra#4137]
**To Reproduce**
1. Start server with `--start-child-late` and `--exit-with-children`. Server will fail to start with assertion error: assert has_child_arg, _exit-with-children was specified but start-child* is missing!_

**System Information (please complete the following information):**
 - Server OS: Ubuntu Jammy
 - Client OS: OS X
 - Xpra Server Version 5.0.5

I see that start-child-late flag is not included [here](https://github.com/Xpra-org/xpra/blob/master/xpra/scripts/server.py#L796), but the help language seems to indicate it should work: _program to spawn in server once initialization is complete taken into account by the exit-with-children option (may be repeated to run multiple commands). Default: none._

Thanks!

**Comment by totaam** [comment]
Well spotted!
Fixed in 5bc8471af30f94a839f3b995d0c1b9f187ea3689

Until this is available in a stable release, you should be able to workaround by adding `--start-child="sleep 10000000000"` to get past this check.
