### ISSUE TITLE
With "--tray=no", Xpra tray still renders in HTML5 client 

### ISSUE THREAD

**Issue by jeffmax** [Xpra-org/xpra#4138]
**Describe the bug**
The "--tray=no" server flag does not appear to be respected by the HTML5 client.

**To Reproduce**
1. Start server using "--tray=no"
2. Open HTML5 client.

**System Information (please complete the following information):**
 - Server OS: Ubuntu Jammy
 - Client OS: OS X Ventura
 - Xpra Server Version 5.0.5
 - Xpra Client Version: Server reports "HTML5 Mac OSX Chrome client version 9.0" but client UI says "Version 11 beta". It is the client bundled with 5.0.5. Web browser is Chrome version 121.0.6167.160. Behavior is the same in Safari.
 
**Additional context**
I may be misunderstanding what this flag does, but when I set it to "no" I still see a floating tray in the UI that allows me to see session info.

Thanks!

**Comment by jeffmax** [comment]
I just realized what this refers to and that it would not apply to a browser client, apologies.

**Comment by totaam** [comment]
No problem.

Thanks for pointing out the version string issue, fixed:
* v11.x: https://github.com/Xpra-org/xpra-html5/commit/8973774c5318aa2dc5223628826296a835aed43e
* git master: https://github.com/Xpra-org/xpra-html5/commit/b7a937d05ad98b3d0cb92d4f79f39d2150127fd6
