### ISSUE TITLE
`ResourceWarning` in OpenGL backing

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4139]
No idea where that's coming from. (not my report)
```
/usr/lib64/python3.12/site-packages/xpra/client/gl/backing.py:1197: ResourceWarning: unclosed file <_io.BufferedWriter name=12>
  glTexImage2D(target, 0, self.internal_format, width, height, 0, pformat, ptype, img_data)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
@karlkleinpaste can you run with `PYTHONTRACEMALLOC=1` ?
And add `-d opengl` to your command line. Or event `XPRA_OPENGL_DEBUG=1`.

We're uploading image data, so that data is not meant to be written to.
My guess is that it's pyopengl that's using a writer object to do the upload?

**Comment by karlkleinpaste** [comment]
first several attempts to reproduce have not been successful. i'll experiment more later today and see if i can get it to happen again. this was the first time i've ever seen that diagnostic, so it may be a rare thing, a timing or race condition problem.

**Comment by karlkleinpaste** [comment]
it seems i can get this to happen irregularly but not infrequently by running glxspheres64 (from virtualgl) over an ssh remote terminal. nothing else has yet tweaked it.
see line 118 in this file. the output volume is understandably huge, so i've sampled 250 lines bracketing the single occurrence.

`PYTHONTRACEMALLOC=1 XPRA_LOG_PREFIX=[minor:19] xpra attach ssh://minor/19 --border=turquoise,2 -d opengl`

[resource-warning.txt](https://github.com/Xpra-org/xpra/files/14334441/resource-warning.txt)

**Comment by totaam** [comment]
This looks like a different backtrace! It points to:
https://github.com/Xpra-org/xpra/blob/a3a51067e61d710d1f63b48e4bbffa66ff71ab83/xpra/net/bytestreams.py#L83-L93

Which is just a retry loop (which we may be able to remove now that we have Python 3.10+ as a requirement).
The real IO most probably comes from the ssh subprocess.
Looks to me like we're reading from a process' pipe as it is being closed.
Not a huge problem. I think the exception here needs to be narrower so we exit the loop:
https://github.com/Xpra-org/xpra/blob/a3a51067e61d710d1f63b48e4bbffa66ff71ab83/xpra/net/bytestreams.py#L87

**Comment by karlkleinpaste** [comment]
> Looks to me like we're reading from a process' pipe as it is being closed.

It's your call, of course, but that conclusion surprises me, because it's right in the middle of extensive GL I/O drawing, such that the pipe should be very active. Are pipes being opened and close during the session?

**Comment by totaam** [comment]
> because it's right in the middle of extensive GL I/O drawing

OpenGL I/O doesn't go through `xpra.net.*`
I can't think of anything GUI related that would trigger I/O. We try very hard to avoid I/O, especially in the UI!

The only subprocess we have, usually per-window, is the signal watcher.
You can run without it via: `XPRA_SIGNAL_WATCHER=0 xpra attach ...`
It is only used for catch unix signals sent to the window so we can forward it to the real, server-side process.

**Comment by totaam** [comment]
And another one, in a different location:
```
/usr/lib64/python3.12/site-packages/cryptography/hazmat/backends/openssl/ciphers.py:165: ResourceWarning: unclosed file <_io.BufferedWriter name=12>
  inlen = min(self._MAX_CHUNK_SIZE, total_data_len - data_processed)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

@karlkleinpaste what version of pyopengl do you have installed on the client?
Could be: 05d14949a7f5f900a39a7c95712859ede3989753 ?

**Comment by karlkleinpaste** [comment]
python3-pyopengl-3.1.7-3.fc39.x86_64.rpm

**Comment by totaam** [comment]
Damn, something else then..

**Comment by totaam** [comment]
I think (almost) all of these `ResourceWarning`'s source locations are bogus.
Something may be leaking, but the interpreter must be detecting it when garbage collection runs.

**Comment by totaam** [comment]
Seen again, these locations are most definitely bogus.

I am closing this ticket because I am fairly sure that the problem is purely cosmetic.
