### ISSUE TITLE
Auto create user dirs when logging in

### ISSUE THREAD

**Issue by MortenVinding** [Xpra-org/xpra#4141]
We have a new problem that we are using FreeIPA to manage user permissions.

So the users are not effectively created on the server until first login, which means there is no /home/<username> until first logon.
It looks like the home dir is needed to store session data.
(pulseaudio among others).

Is there anyway to have homedir's build while logging in?
Possibly a pre-x-start-up script of some kind.

**Comment by totaam** [comment]
Most of the session data should live in `$XDG_RUNTIME_DIR` if it exists.
How do you login?
How do you create the xpra session?
If your users authenticate and login via the proxy service, you should be able to use pam to create the directory structure.

**Comment by MortenVinding** [comment]
> If your users authenticate and login via the proxy service, you should be able to use pam to create the directory structure.

That did it, thanks!

I just changed /etc/pam.d/xpra like (added the last line):
```
.
.
session    required     pam_loginuid.so
#to require a local user account, uncomment this line:
#session    required     pam_localuser.so
**session    optional     pam_mkhomedir.so** 
.
.
```
