### ISSUE TITLE
Cannot start xpra server on Debian  12

### ISSUE THREAD

**Issue by jiang-qian** [Xpra-org/xpra#4155]
**Describe the bug**
I tried to star xpra using this command and it simply failed

**To Reproduce**
1. server command
`xpra start :100 --bind-tcp=0.0.0.0:10000`

**System Information (please complete the following information):**
 - Server OS: Debian 12
 - Client OS: Debian 12
 - Xpra Server Version v5.0.6-r3 from repository https://xpra.org
 - Xpra Client Version ditto.

Error in the log:
```
24-02-28 08:34:19,036 printer forwarding enabled using postscript and pdfESC[0m
2024-02-28 08:34:19,102 some GStreamer elements are missing or unavailable on this system:ESC[0m
2024-02-28 08:34:19,102  vaapih265enc, amfh264enc, amfh265encESC[0m
2024-02-28 08:34:19,276 CUDA initialization (this may take a few seconds)ESC[0m
terminate called after throwing an instance of 'pycuda::error'
  what():  cuInit failed: no CUDA-capable device is detected
```
Full log attached.q
[server.log](https://github.com/Xpra-org/xpra/files/14434766/server.log)

**Comment by totaam** [comment]
> no CUDA-capable device is detected

This should not be fatal.
You can bypass this problem by uninstalling `xpra-codecs-nvidia`.

This is a pycuda problem.
Which version of CUDA / pycuda do you have installed?
From which channel did you get it?

**Comment by jiang-qian** [comment]
Sorry for the late reply! Removing xpra-codecs-nivida indeed enabled the xpra server to start and the display applications works properly.
To answer your questions, all my cuda /pyCuda files were installed from default Debian 12 repository.

**Comment by totaam** [comment]
Sounds like Debian is shipping buggy versions again..
`cuInit` should never terminate the program that calls it.
