### ISSUE TITLE
Missing 5.0.7 debian package files from distro?

### ISSUE THREAD

**Issue by jzyrobert** [Xpra-org/xpra#4159]
**Describe the bug**
The 5.0.7 release debian files are missing from the jammy/mantic/noble dists in https://xpra.org/dists/

**To Reproduce**
1. Check for example https://xpra.org/dists/jammy/main/binary-amd64/
2. See that the 5.0.7 files are missing
3. Try apt installing Xpra and see that 5.0.6 is the latest available version

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Client OS: Windows 10
 - Xpra Server Version 5.0.6
 - Xpra Client Version 5.0.4

**Additional context**
N/a

**Comment by totaam** [comment]
Sorry about the delay. Fixed.

I was hoping to release 5.0.8 rather than doing a rebuild, but that has been delayed for now.
