### ISSUE TITLE
Windows SSH connections fail.

### ISSUE THREAD

**Issue by chen369** [Xpra-org/xpra#4162]
**Describe the bug**
In Windows, if you try to connect to a Xpra server using the GUI start button or cmdline, ssh connections fail only when you are prompted to enter a SSH password on the prompt that asks you to enter ssh password.

However, If you put your SSH password within the username box on the GUI or put the ssh password in cmd line 
`& 'C:\Program Files\Xpra\Xpra_cmd.exe' attach ssh://[SSH_USER]:[SSH_PASSWORD]@[SSH_HOST]`
connections to Xpra work and connect successfully.

**To Reproduce**
1. Server command: Not Appplicable 
2. Client command: `& 'C:\Program Files\Xpra\Xpra_cmd.exe' start ssh://[SSH_USER]@[SSH_HOST]/[X11_DISPLAY] --debug=ssh --start=xterm`
3. Specific action to trigger the bug: Connect to Xpra host using standard start commands or any SSH related client command without ssh password included in connection parameters in windows.

**System Information (please complete the following information):**
 - Server OS: RHEL 9/CentOS 9/Fedora 39.
 - Client OS: Windows 11
 - Xpra Server Version: 5.0.2-2
 - Xpra Client Version: 5.0.7

**Additional context**
I tried debugging this and on the logs for the client side, I see just timeouts to Xpra even though it was able to connect to the host just fine via ssh. On the server side, when I have Debugging enabled on the Host I see a bunch of socket timeouts to /run/user/{UID}/xpra/{x11_display_id}/socket

**Comment by totaam** [comment]
Thanks for the detailed description.
This is a regression caused by ddd954580ab98630788a130aa38691b6fa745fcd (as a result of the changes for #3822)
The commit above fix this problem.

There are "Light" MS Windows builds with this fix in the beta area: https://xpra.org/beta/windows/
v5.0.8-r45 and v6.0-r35331 or later.
I believe that the 3.1.x branch was not affected by this.
