### ISSUE TITLE
Python3 Installation on RHEL

### ISSUE THREAD

**Issue by gregory-barr** [Xpra-org/xpra#4166]
**Describe the bug**
When installing xpra using rpms on RHEL8 (using rhel/ubi8 as base in a container installation via podman), the installation changes the shebang from /usr/bin/python3 to /usr/libexec/platform-python, which then defaults to python3.6. The preference is to use the latest 3.11.

**To Reproduce**
1. Start with rhel8/ubi
2. Configure yum repos to use [almalinux](https://xpra.org/dists/almalinux/$releasever/$basearch/)
3. yum install xpra-5.0.7
4. Inspect /usr/bin/xpra and noticed changed shebang to /usr/libexec/platform-python

**System Information (please complete the following information):**
 - Server OS: RHEL8.9
 - Xpra version: 5.0.7
 
**Additional context**
Setting alternatives for python3 to python3.11 does not have any affect.

**Comment by gregory-barr** [comment]
More info:

Installed python3.11
>  alternatives --display python3
>  Current `best' version is /usr/bin/python3.11

Attached is yum install xpra output which shows python36 dependency
[Yum Install with dependencies.txt](https://github.com/Xpra-org/xpra/files/14630255/Yum.Install.with.dependencies.txt)

Attached also is "python3 version.py" output after installation.
[version.py output.txt](https://github.com/Xpra-org/xpra/files/14630271/version.py.output.txt)

**Comment by totaam** [comment]
> The preference is to use the latest 3.11.

You cannot simply switch python version.
The xpra package is tied to a specific python version.

In version 6 (available from the beta repository), `xpra` will install `python3.11-xpra` and can co-exist with other versions, as is done on Fedora where you also have the choice of installing `python3.12-xpra`, `python3.10-xpra`, etc..
