### ISSUE TITLE
invalid compressor(s) specified: lzo

### ISSUE THREAD

**Issue by thorstenwagner** [Xpra-org/xpra#4169]
When I attach via xpra (`xpra v5.0.7-r0M`), I always see this warning on my linux client:

```
Warning: invalid compressor(s) specified: lzo
2024-03-20 08:20:02,823 Warning: invalid compressor lzo specified
```

This is how I connect:

```
xpra attach tcp:gtxr1.srv-local.mpi-dortmund.mpg.de:2001 --encoding=webp --speaker=disabled --opengl=yes --min-speed=0 --min-quality=0
```

Any idea how to resolve  that?

**Comment by totaam** [comment]
Your configuration files are invalid and specify `lzo` as a compressor.
This compressor has been removed in v5.
IIRC, this warning is now suppressed in v5.0.8

> `xpra attach tcp:gtxr1.srv-local.mpi-dortmund.mpg.de:2001 --encoding=webp --speaker=disabled --opengl=yes --min-speed=0 --min-quality=0`

* this syntax has been deprecated for years, use `tcp://host:port/` instead
* `--encoding=webp` is a bad idea

**Comment by thorstenwagner** [comment]
The output is
```
Warning: invalid compressor(s) specified: lzo
* default config:
compressors         : 'all'                                    (<class 'list'>)
* '/etc/xpra':
compressors         : 'lz4, lzo, zlib, brotli'                 (<class 'str'>)
* '/etc/xpra/':
compressors         : 'lz4, lzo, zlib, brotli'                 (<class 'str'>)
* '/home/twagner/.config/xpra':
compressors         :                                          (<class 'NoneType'>)
* '/home/twagner/.xpra':
compressors         :                                          (<class 'NoneType'>)
```

However, I looked in the files `/etc/xpra/xpra.conf` etc but there are no compressors specified.

Thanks for syntax hint! I changed it :-)

Regarding encoding: Simply remove it?

**Comment by totaam** [comment]
> However, I looked in the files...

`grep -r compressors /etc/xpra`

> Regarding encoding: Simply remove it?

Yes, raise `--min-speed` or `--min-quality` as needed instead.

**Comment by thorstenwagner** [comment]
```
/etc/xpra/conf.d/10_network.conf:#compressors = all
/etc/xpra/conf.d/10_network.conf:#compressors = none
/etc/xpra/conf.d/10_network.conf:#compressors = zlib
/etc/xpra/conf.d/10_network.conf:compressors = lz4, lzo, zlib, brotli
```
It comes from here... simply delete the file?

**Comment by totaam** [comment]
Personally, I would figure out why you have an old configuration file installed rather than the one that comes with the package you have installed.
Perhaps you had made some changes to that file and the package manager decided not to overwrite them?

Installing the correct file from the package would be *my* preferred option, but deleting it would also work.

**Comment by thorstenwagner** [comment]
I thought that the reason is, that I installed an old xpra version first via the package manager. However, uninstalling it did not remove those old config files. I will simply try to delete them. Thank you a lot for the support! :-)
