### ISSUE TITLE
Missing dependencies on Ubuntu 22.04

### ISSUE THREAD

**Issue by iDmple** [Xpra-org/xpra#4177]
These two libraries don't exist on Ubuntu 22.04. I had to comment them out to be able to build the .deb packages.

https://github.com/Xpra-org/xpra/blob/f024726a64301a4343df28f9981ba008ef0833b5/packaging/debian/xpra/control#L262-L263

Existing lib:
https://packages.ubuntu.com/search?keywords=libopenh264&searchon=names&suite=jammy&section=all

I don't know by what the other one should be replaced, or how to make it also work with Debian? However, it used to work fine before these lines were changed.

**Comment by totaam** [comment]
I violently dislike Debian's library package naming.
This is going to require per-distro package names, similar to: 
https://github.com/Xpra-org/xpra/blob/f024726a64301a4343df28f9981ba008ef0833b5/packaging/debian/xpra/control#L279-L285
The buildbot then comments out the one matching the distro being built.

**Comment by iDmple** [comment]
Ok, gonna try to make a PR.
