### ISSUE TITLE
Complete screen turns white

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#4178]
**Describe the bug**
When successfully connecting to a server with xpra 6.0-r35337-1, the complete screen turns white.

The first time I could still ctrl-tab and see the windows (and it turned white again when I stopped pressing the keys), but now I do not get to see the xpra or other windows at all.

I tried the usual suspects like disabling compositing in kwin, using --opengl=no for xpra and using a fluxbox session instead of KDE, but I get the problem in all cases.

**To Reproduce**
1. server command: xpra attach ssh://user@server/10 --opengl=no
2. client command: xpra start :10
3. Successfully connect to a server

**System Information (please complete the following information):**
 - Server OS: Debian bookworm (stable)
 - Client OS: Debian trixie (testing)
 - Xpra Server Version: 5.0.7-r0-1
 - Xpra Client Version: 6.0-r35337-1

**Additional context**
- I have a nvidia card and use the proprietary driver.
- Killing xpra from the Linux console lets me use the desktop again. Using xpra again causes the same problem. I see no messages regarding the problem on the console running the xpra attach command.

**Comment by allo-** [comment]
Strange thing: When I connect to a local server (without ssh) I do not get the problem.
Without --opengl=no I get an opengl error, though: `probe error: PyOpenGL vs accelerate version mismatch: 3.1.7 vs` (the rest is not visible in the passive popup)

**Comment by allo-** [comment]
ssh to localhost doesn't cause the problem either. It really seems to be the combination of the two different xpra versions.

**Comment by allo-** [comment]
It was indeed a server-side issue and xpra upgrade solved it for now. As I don't have a server-side log after the upgrade, I close here for now until I can reproduce.

**Comment by totaam** [comment]
> `Xpra Client Version: 6.0-r35337-1`

That's old.

> `probe error: PyOpenGL vs accelerate version mismatch: 3.1.7 vs`

You've messed up your installation. They should **always** have the same version.
Not doing leads to crashes.

**Comment by allo-** [comment]
> That's old.

The latest from the xpra.org Debian testing repo. The server-side is even older, but again the xpra.org (Debian stable) repo.

> You've messed up your installation. They should always have the same version.
That's what I thought, but it isn't directly related to the problem in the way, that the server-side xpra upgrade solved it. On the other hand, it is at least partially a client problem, because even when the server messes up, it shouldn't result in a completely white screen (but possibly in white or black windows).

Still, the Debian testing client may be broken from time to time due to Debian testing, but the Debian stable side should be reliable. And I've had the OpenGL error in the past and with and without (manually) disabling OpenGL it wasn't an issue leading to noticeable problems.

But as said, I do not have an idea how to reproduce after reloading the server side xpra, so I don't have much to contribute here. Except, maybe, that the repo doesn't seem to contain the latest version.

**Comment by totaam** [comment]
> And I've had the OpenGL error in the past and with and without (manually) disabling OpenGL it wasn't an issue leading to noticeable problems.

Because we detect this dangerous combination safely, by running it in a subprocess, and then disable OpenGL.

> Except, maybe, that the repo doesn't seem to contain the latest version.

The beta repo is... not always stable or reliable.
