### ISSUE TITLE
some keys don't work

### ISSUE THREAD

**Issue by rogeriojlle** [Xpra-org/xpra#4183]
**Describe the bug**
My keyboard is the ABNT2 standard (Brazil), I noticed that the backtick (`) and caret (~) keys do not work, using both the client program for Windows and the html5 version.
I haven't tested it with a Linux client

**To Reproduce**

1. server command
`xpra start --start-new-commands=no --start-child=xfce4-terminal --audio=no --exit-with-children=yes --bind-tcp=127.0.0.1:14500 --html=on --webcam=no --daemon=no --notifications=no --minimal=MINIMAL --open-files=no`

3. client command
browsing with Google Chrome up to 127.0.0.1:14500 or using the windows client and using tcp type 127.0.0.1:14500

5. specific action to trigger the bug

backtick (`) and caret (~) keys do not work

**System Information (please complete the following information):**
 - Server OS: Fedora Core 41
 - Client OS: Windows 11
 - Xpra Server Version v6.0-r35418 (g08ce2221bf) beta
 - Xpra Client Version 5.0.4

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
> ` --minimal=MINIMAL`

This is not a valid option.

As per [Reporting-Bugs](https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs), please add more [keyboard information](https://github.com/Xpra-org/xpra/blob/master/docs/Features/Keyboard.md)
ie: attach a picture of the layout
Include the server log, client output when running with `xpra_cmd.exe attach ..`, etc.

**Comment by totaam** [comment]
Not heard back.
