### ISSUE TITLE
[v6.0] Latest Beta Builds missing from https://xpra.org/beta/stable/main/binary-amd64/

### ISSUE THREAD

**Issue by markmandel** [Xpra-org/xpra#4184]
Just noticed that my `testing` Debian instances have version `xpra v6.0-r35418 (g08ce2221bf) beta` while, my `stable` ones are on the older `v6.0-r35337 (gf32ad5254) beta`  - they are usually in sync.

Might be a good reason - just figured I'd flag it in case you didn't know.

**Comment by totaam** [comment]
Doing builds for **all** supported platforms takes many days - and a lot of disk space, so I often limit beta builds to the ones most likely to be needed.

**Comment by markmandel** [comment]
Totally fair enough 👍🏻
