### ISSUE TITLE
Sub menus do not open in Firefox

### ISSUE THREAD

**Issue by Chaz6** [Xpra-org/xpra#4188]
**Describe the bug**
When running Firefox through Xpra, clicking on a target which opens a menu works as expected. However, if that menu contains sub-menus, they do not open when hovered over.

**To Reproduce**
1. Connect to the host using `xpra start ssh://SERVER/ --start=firefox`
2. Click on a target which opens a menu
3. Hover over a submenu

**System Information (please complete the following information):**
 - Server OS: `AlmaLinux 9.3`
 - Client OS: `Fedora 38` (KDE Plasma on Wayland)
 - Xpra Server Version `v5.0-r0`
 - Xpra Client Version `v5.0.6`

**Additional context**

![Screenshot_20240408_165033](https://github.com/Xpra-org/xpra/assets/12680/e2288fe6-dac6-4060-a32a-cf8de7019ab5)

**Comment by totaam** [comment]
> Xpra Server Version v5.0-r0

Are you sure about that?
If so, that's quite old and missing lots of geometry fixes.

Works for me with an X11 client and a Fedora server - I will check again as this could well be to a Wayland misfeature.

**Comment by totaam** [comment]
Yeah, looks like it's a Wayland feature again.
I can crash Weston every single time by clicking the menu, then clicking the xterm I started xpra from!
100% reliable crash.
But eh, Wayland is better, safer, it's the future! Or something.

**Comment by totaam** [comment]
The warning comes from here and "explains" why the window is not shown:
https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/wayland/gdkwindow-wayland.c?ref_type=heads#L3019-L3026
Looks like providing the window parent (and ensuring it is mapped) would allow the popup to be shown?

**Comment by totaam** [comment]
And here's the popup window metadata that triggers the warning:
```
process_new_common: (67, 697, 477, 207, 97, { \
    'xid': 12583148, 'has-alpha': True, 'client-machine': 'fedora', 'pid': 665851, 'title': 'Firefox', 'role': 'Popup',
    'command': '/usr/lib64/firefox/firefox', 'class-instance': ('Firefox', 'firefox'), 'opaque-region': (), \
    'transient-for-xid': 12582955, 'transient-for': 2, 'bypass-compositor': 2, 'group-leader-xid': 12582913, \
    'window-type': ('POPUP_MENU',), 'content-type': '', 'override-redirect': True \
}) (..) OR=True
```
The problem is that its parent is not the other popup.
This works fine on X11, but GTK refuses to show the popup on Wayland.

The commit above implements an ugly workaround, second guessing what `WM_TRANSIENT_FOR` really should point to.

Works-for-me... Although I did notice some pointer offsets under Wayland with Firefox, but that's a different issue.

**Comment by totaam** [comment]
Works-for-me.
