### ISSUE TITLE
README has incorrect information about PGP key

### ISSUE THREAD

**Issue by CrazyKidJack** [Xpra-org/xpra#4190]
**Describe the bug**
The PGP key fingerprint mentioned on the README does not match the actual key downloaded from https://xpra.org/xpra.asc.

![image](https://github.com/Xpra-org/xpra/assets/43480837/69499a16-b810-4613-96a4-dbcafd346dc5)

![image](https://github.com/Xpra-org/xpra/assets/43480837/2a312d55-5b38-4fdd-8088-757e98a180fe)

So when verifying the Windows EXE full build download, I either have to assume that the key download link is not compromised and the github is just wrong or compromised, so it's ok to install (because the EXE does match the downloaded PGP key)... or the github is not compromised and the downloaded key is compromised or wrong, so it is no ok to install...

If I understand correctly (which I might not... I do not use kleopatra/gpg/pgp often)... PGP keys are like TLS certs, except they aren't tied to a CA that verifies the identify of the key owner... so they are only as good as my trust that the key I received actually belongs to who I think it belongs to. If both GitHub and the downloaded key agreed with each other, that gives me some level of confidence because for them to agree but be compromised, an attacker would need to compromise two independent systems. But here they don't agree, so if I go by what GitHub says, then I should assume the downloaded key and EXE are compromised (which I assume it is not... but still...)

**To Reproduce**
1. Download the Windows full build EXE
2. Downloaded the Windows full build EXE GPG signature
3. Download the PGP key from https://xpra.org/xpra.asc
4. Import the PGP key to kleopatra
5. Observe that the fingerprint does not match GitHub
6. Try to verify the gpg signature with kleopatra
7. Observe that the gpg signature matches the PGP key (but it doesn't match GitHub... so what should we trust?)
![image](https://github.com/Xpra-org/xpra/assets/43480837/b83308eb-eea8-4dd6-b4db-9700cd182775)

**System Information (please complete the following information):**
 - OS: Windows 11
 - Xpra version: https://xpra.org/dists/windows/Xpra-x86_64_Setup.exe

**Comment by totaam** [comment]
> The PGP key fingerprint mentioned on the README

Which one?
Must have forgotten to update somewhere.

**Comment by CrazyKidJack** [comment]
@totaam 
> > The PGP key fingerprint mentioned on the README
> 
> Which one? Must have forgotten to update somewhere.

Sorry not on the README. It's on the Download page:
![image](https://github.com/Xpra-org/xpra/assets/43480837/71e90303-ae6d-4ee0-870c-f2e1b89e3431)

**Comment by totaam** [comment]
The key had been updated in #4190, the wiki download page has now been updated: https://github.com/Xpra-org/xpra/wiki/Download/_compare/918cb9af07c28a9e026340bf894da7879d15914f
