### ISSUE TITLE
Mac M1, run jhbuild update,  got "No such file or directory: 'xpra-gtk3.modules'"

### ISSUE THREAD

**Issue by lpf6** [Xpra-org/xpra#4203]
**Describe the bug**
Run `jhbuild update` got error when I try to build from source on MacOS M1 Pro:
```
jhbuild update: failed to parse xpra-gtk3.modules: [Errno 2] No such file or directory: 'xpra-gtk3.modules'.
```
How can I aviod the error?

**To Reproduce**
I follow the doc [docs/Build/MacOS.md](https://github.com/Xpra-org/xpra/blob/master/docs/Build/MacOS.md) to install from source in Mac M1.
1. `Setup gtk-osx`  And set PATH
2. `Configure jhbuild to use our modules`
3.  when I run `jhbuild update`  got error: "No such file or directory: 'xpra-gtk3.modules'".

**System Information (please complete the following information):**
 - Mac OS 13.3.1 (a) 
 - Apple M1 Pro
 - aarch64 Terminal

**Additional context**
I has uninstall `brew` in my MAC to build source, their is all logs of `jhbuild update` when I run again:
```
/Users/lu/.new_local/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:778: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
/Users/lu/.new_local/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:778: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Loading .env environment variables...
Setting $PYTHON to module-built python3 because python3;.
Modules python3;meta-osx-xpra-deps
jhbuild update: failed to parse xpra-gtk3.modules: [Errno 2] No such file or directory: 'xpra-gtk3.modules'
```

**Comment by lpf6** [comment]
I found where 'xpra-gtk3.modules', its in another repo, I fix by:
```
git clone https://github.com/Xpra-org/gtk-osx-build.git
cd gtk-osx-build
jhbuild update
```

**Comment by cpatulea** [comment]
Sorry about that, https://github.com/Xpra-org/xpra/pull/4212
