### ISSUE TITLE
Ubuntu PPA: file conlfict of xpra-codecs-extra (6.0-r0-1) with xpra-codecs (5.0.8-r0-1)

### ISSUE THREAD

**Issue by alleehol** [Xpra-org/xpra#4204]
**Describe the bug**
Upgrade von 5.0.8-r0-1 to 6.0-r0-1 failed with:

```
Unpacking xpra-codecs-extras (6.0-r0-1) over (5.0.8-r0-1) ...             
dpkg: error processing archive /tmp/apt-dpkg-install-d7eiCY/1-xpra-codecs-extras_6.0-r0-1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/xpra/codecs/avif/__init__.py', which is also in package xpra-codecs 5.0.8-r0-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../2-xpra-codecs_6.0-r0-1_amd64.deb ...
Unpacking xpra-codecs (6.0-r0-1) over (5.0.8-r0-1) ...
```

Hack to fix it
```
apt -f install
apt full-upgrade
```

**To Reproduce**
1. server command: apt full-upgrade
2. client command: n/a
3. specific action to trigger the bug:  apt update; apt full-upgrade

**System Information (please complete the following information):**
 - Server OS: [Ubuntu 22.04]
 - Client OS: [n/a]
 - Xpra Server Version [5.0.8]
 - Xpra Client Version [n/a]

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Ah, the `avif` codec must have been moved to a different codec package and that causes problems during the upgrade.
I will need to figure out how to tell `dpkg` to remove `xpra-codecs` before installing the newer split packages.

**Comment by alleehol** [comment]
AFAIR https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts

**Comment by totaam** [comment]
Yes, that's what 90a26b79a96281b22440018c236c551fc8c2798f does, we'll see how it goes.

In the meantime, you can just remove `xpra` and re-install it, it should work.
