### ISSUE TITLE
task grouping not working for gtk based applications

### ISSUE THREAD

**Issue by d3matt** [Xpra-org/xpra#4208]
**Describe the bug**
Launching multiple seamless gtk based applications with the same binary isn't showing them as grouped

**To Reproduce**
1. xpra start :8
2. using a session to launch xpra with opengl off, connecting to the remote server over ssh on display 8
3. launch multiple gvim windows, note that they're not grouped together

**System Information (please complete the following information):**
 - Server OS: Rocky Linux 9.3
 - Client OS: Windows 10
 - Xpra Server Version 5.0.2
 - Xpra Client Version 5.0.8

**Additional context**
Some QT based applications (such on konsole) and xfce based applications (such as xfce4-terminal) seem to get grouped together but not others. The terminal I launch everything from (usually konsole) was started from the xpra client taskbar start menu.

**Comment by totaam** [comment]
My guess is that the grouped applications use the same `pid` for all of their windows and the others do not. 
If so, then I'm not sure that this is fixable in a sane way.

**Comment by d3matt** [comment]
Hmm, yea... Looks like if I force a new PID to get a new window, then QT apps don't group either... Could the client optionally group things based on the /proc/<pid>/exe symlink?

**Comment by totaam** [comment]
It should be doable here:
https://github.com/Xpra-org/xpra/blob/efa5e2cf6540e77d66113e3f5f2dcfab8c1e7328/xpra/client/gtk3/client_base.py#L1427-L1468
I was worried that the signal watcher was going to be tied to it, but I was wrong, it only uses the wid, pid:
https://github.com/Xpra-org/xpra/blob/efa5e2cf6540e77d66113e3f5f2dcfab8c1e7328/xpra/client/mixins/windows.py#L960

**Comment by totaam** [comment]
@d3matt please try 307242be6b1e2e1f85d8506fdcf342e91518bb81 or later.
The default grouping will be the first match from:
https://github.com/Xpra-org/xpra/blob/307242be6b1e2e1f85d8506fdcf342e91518bb81/xpra/client/gtk3/client_base.py#L79
So what you want should be achievable using:
```
XPRA_WINDOW_GROUPING=group-leader-xid,command,pid xpra attach ...
```
