### ISSUE TITLE
Hyperlinks in applications don't work anymore after upgrading to version 6 when using the HTML Client

### ISSUE THREAD

**Issue by zvooveDev** [Xpra-org/xpra#4215]
**Describe the bug**
After upgrading Xpra from version 4.4.6-r29-1 to 6.0-r0-1 hyperlinks in our application don't work anymore when using the HTML Client.

**To Reproduce**
1. Upgrade to Xpra version 6.0-r0-1
2. Click on a link inside an application
3. The link doesn't open inside a new tab anymore. The following error is displayed in the log:
New socket connection received
on '/run/user/1000/xpra/635951d33320-0'
**Warning: remote end does not accept URLs**
1 packets received (2.6K bytes)
1 packets sent (57 bytes)

**System Information (please complete the following information):**
 - Server OS: ubuntu:22.04
 - Client OS: Windows 11
 - Browser: Chrome 124.0.6347.93
 - Xpra Server Version 6.0-r0-1
 - Xpra Client Version 12
 - Application: Delphi Application running in Wine version 8.0.2

**Additional context**
- I can reproduce the error in 6.0-r0-1  and 5.0.8-r0-1
- Rolling back to Version 4.4.6-r29-1 (HTML Client Version 8.1) solves the issue

**Comment by totaam** [comment]
Sorry about that.
Fixed by the commit above.

Tested using `xdg-open http://google.com/` from within a basic session.
