### ISSUE TITLE
tip: clipboard usage via xclipboard

### ISSUE THREAD

**Issue by thorstenwagner** [Xpra-org/xpra#4217]
Hi,

while I'm struggling with the clipboard with both, the xpra and the html5 client, I found a good workaround:

You simply start `xclipboard &`. If you then copy something on your system, you paste it in `xclipboard` and then you can paste it by pressing the mouse wheel.

In the html5 client however, it also paste some formatting stuff, which is annoying. But better than having no copy&paste at all. Maybe its worth to add this to the documentation. 

Best,
Thorsten

EDIT: I noticed that this only works to copy FROM your system TO xpra, but not the other way around.

**Comment by totaam** [comment]
I believe this ticket belongs in the `xpra-html5` project, right?
There should not be any major problems with the python client.

You should probably look at existing tickets: https://github.com/Xpra-org/xpra-html5/issues/298, https://github.com/Xpra-org/xpra-html5/issues/301, https://github.com/Xpra-org/xpra-html5/issues/283, etc..

**Comment by totaam** [comment]
Not heard back.
