### ISSUE TITLE
probe-error:not painted on screen

### ISSUE THREAD

**Issue by intractabilis** [Xpra-org/xpra#4218]
**Describe the bug**
I see the cryptic message in the title of the issue, and the client's OpenGL doesn't work.

**To Reproduce**
I don't know how to reproduce it in general besides logging in to my system. The command was
```
xpra start-desktop --ssh="ssh" ssh:server --start-child='xfce4-session' --exit-with-children --resize-display="2560x1440"
```

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22
 - Client OS: ManjaroLinux 23.1.4 Vulcan
 - Xpra Server Version: 6.0
 - Xpra Client Version: 6.1-r35755

**Additional context**
 I ran with "-d opengl" and didn't see any errors besides glXMakeCurrent returning NULL. The full log is attached.
[xpra.log](https://github.com/Xpra-org/xpra/files/15244022/xpra.log)

**Comment by totaam** [comment]
> `ssh:server`

Is deprecated, use `ssh://username@host/`

> `glXMakeCurrent returning NULL`

This is fine, that's xpra closing the glx context.

That's an issue in git master - you can use a stable release instead.

**Comment by intractabilis** [comment]
> Is deprecated, use

Does it support SSH config?

> That's an issue in git master - you can use a stable release instead.

I don't think I can. The version in the Manjaro repository is 4.4.5, and it stopped working with the version in the Ubuntu repository. The AUR version is 6.1-r35755. Can you advise on how I can make 4.4.5 work with 6.0?

**Comment by intractabilis** [comment]
> No, as per

Therefore, this statement is false:

> you can use a stable release instead.

**Comment by totaam** [comment]
> this statement is false

It is only false because your distribution, which is not supported here, only provides outdated packages and not stable releases.
