### ISSUE TITLE
Use more native file picker/save dialogs

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#4222]
[Apparently](https://gitlab.gnome.org/GNOME/gtk/-/issues/6688#note_2102696), we're supposed to use [FileChooserNative](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/FileChooserNative.html) on win32 and macos: fec4bb7e410c490753c9433acae2870f639f6525

Please try `6.1-r35733` or later.

_Originally posted by @totaam in https://github.com/Xpra-org/xpra/issues/4210#issuecomment-2094722934_

**Comment by stdedos** [comment]
Also on Session Info / save png?

![image](https://github.com/Xpra-org/xpra/assets/133706/e5fa3c3e-85f2-4e80-b88a-a7836abbaaeb)

**Comment by totaam** [comment]
Can I close this?

**Comment by stdedos** [comment]
Ah, sorry - haven't seen it 😅 

If you want to clean up, feel free. I'll test again tonight probably 🙏

**Comment by stdedos** [comment]
Yes, seems to be working!

![image](https://github.com/Xpra-org/xpra/assets/133706/0177bdec-440e-4150-b591-99b72e372ceb)


... almost 😅 

```py
2024-05-23 22:21:36,311 server is OK again
2024-05-23 22:21:41,042 server is not responding, drawing spinners over the windows
Traceback (most recent call last):
  File "E:/xpra/xpra/gtk/dialogs/session_info.py", line 1308, in save_graph
AttributeError: 'FileChooserNative' object has no attribute 'close'
2024-05-23 22:21:53,086 server is OK again
```

**Comment by totaam** [comment]
> `AttributeError: 'FileChooserNative' object has no attribute 'close'`

Done: 3b9b18e4720a8ae9c30495c12c5f4a2fbb83ee99
