### ISSUE TITLE
run_scaled parsed is wrong making it impossible to use it as intended.

### ISSUE THREAD

**Issue by fcolecumberri** [Xpra-org/xpra#4223]
In

https://github.com/Xpra-org/xpra/blob/90f6ae49e0ba8003f3b807baff8332d4c951d2f0/fs/bin/run_scaled#L89-L90

The if is always false. You are checking that `extra_xpra_args` is not `None` which is impossible since that variable is initialized as `[]` which python considers it different than `None` and it never is assigned to `None`.

The problem with this is that the very next line is the only place where `command_argv` can be filled (unless you split the command with `--`) rendering impossible to fill.

Because of this, always at

https://github.com/Xpra-org/xpra/blob/90f6ae49e0ba8003f3b807baff8332d4c951d2f0/fs/bin/run_scaled#L93-L94

the message of missing command is printed and the program exits as failure.

This is clearly an error, and I would gladly make a pull request but I have no idea about the intention behind that `if` so I thought it would be better to report this as an issue.

Also some people might argue that since the cli can be ussed splitting the argument with `--` is not a problem, but the usage message mentions nothing about it.

https://github.com/Xpra-org/xpra/blob/90f6ae49e0ba8003f3b807baff8332d4c951d2f0/fs/bin/run_scaled#L11-L16

**Comment by totaam** [comment]
@fcolecumberri thanks, how about this updated version:
https://github.com/Xpra-org/xpra/blob/530a19421401a279270fb7fbbff1ee46da82211e/fs/bin/run_scaled

See 530a19421401a279270fb7fbbff1ee46da82211e for the list of changes.
I forgot one: it should now start much more quickly thanks to `--start-new-commands=no`, `--audio=no` and `--video=no`.

This does make me think about other options which may need to be added to the defaults:
* dbus and notifications: should we just leave the environment as it is and let them pass through - I don't see why not
* what about `--open-url` and `--open-files`..
Probably more options could be tweaked.

**Comment by fcolecumberri** [comment]
thanks
