### ISSUE TITLE
Server crash when using IntelliJ IDEA

### ISSUE THREAD

**Issue by SanjayVas** [Xpra-org/xpra#4230]
**Describe the bug**
Xpra server crashes. Client disconnects. Inspecting server gives 

```
server socket for display 100 is in UNKNOWN state
 waiting up to 20 seconds
Warning: failed to connect:
 cannot find live server for display 100
```

**To Reproduce**
1. server command - `XPRA_X11_DEBUG_EVENTS="*" xpra start :100`
2. client command - `xpra attach :100` (local)
3. Navigate/scroll through files in IntelliJ IDEA

**System Information (please complete the following information):**
 - Server OS: Debian Trixie
 - Client OS: Debian Trixie
 - Xpra Server Version xpra v6.1-r35687 (g929d991be7) beta
 - Xpra Client Version xpra v6.1-r35687 (g929d991be7) beta

**Additional context**
I was not having this issue until very recently. I suspect something else on my managed Debian installation got updated. I was running v6.0-r35337 and started seeing crashes this morning with BadWindow errors, so I updated to the latest beta version. Now I am not spotting any relevant error in the server logs, even with debug events on.

I'm running locally so that I can swap between local and remote (SSH) connections.

[xpra-server.log](https://github.com/Xpra-org/xpra/files/15325820/xpra-server.log)

**Comment by SanjayVas** [comment]
Captured another log with `--debug all`:

[xpra-server.log](https://github.com/Xpra-org/xpra/files/15326503/xpra-server.log)

**Comment by totaam** [comment]
Debian Trixie is not stable yet, so things do break.
When that happens, simply using a newer build can fix things.

Also from your log:
```
FileNotFoundError: [Errno 2] No such file or directory: 'dbus-launch'[0m
```
That's odd, could cause problems - probably not crashes though.

I can't reproduce any problems running it on Fedora.
The fact that there is not a single unusual X11 message in your log makes me think that this is likely to be a Debian only issue, perhaps related to the use of `Xvfb`.

**Comment by totaam** [comment]
Does the problem go away if you turn off mmap? `--mmap=no`
I've just remembered doing this change: https://github.com/Xpra-org/xpra/commit/8e51176885aea640db187ddbbaad9bdb523d8ef0
You could try undoing this commit.

**Comment by SanjayVas** [comment]
Interestingly, I actually can't reproduce this anymore after rebooting my machine. Prior to that it was happening so frequently that it was nearly impossible to get any work done.

> Debian Trixie is not stable yet, so things do break. When that happens, simply using a newer build can fix things.

Yes, if you noticed that was the first thing I did.

To clarify, do you mean that the Xpra codebase for Trixie is not stable or are you referring to the Debian release tracks? Debian stable is extremely conservative and mostly used for servers. Desktop Debian users tend to be on Debian testing, which is currently Trixie. I would expect that out of all the Debian users that would want to use Xpra, the majority of them would _not_ be on stable. This includes [all Linux workstations for engineers at Google](https://en.wikipedia.org/wiki/GLinux), for example.

> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'dbus-launch'�[0m
> ```
> 
> That's odd, could cause problems - probably not crashes though.

Just in case, I installed `dbus-x11` which was not installed. It made that log message go away, but did not prevent the crash.

**Comment by totaam** [comment]
> To clarify, do you mean that the Xpra codebase for Trixie is not stable or are you referring to the Debian release tracks?

I meant that until Trixie [is frozen](https://release.debian.org/testing/freeze_policy.html), then the ABI will break. This happens, a lot, sometimes it's obvious: https://github.com/Xpra-org/xpra/issues/3531#issuecomment-1406373850 and other times it will just crash instead.

The xpra beta channel does get builds fairly regularly, but Debian being a sub-optimal platform for xpra (mostly because of the butchered Xorg installation) means that we don't make builds whenever the ABI breaks - I'm not even sure there would be a way to tell when that happens.

> Just in case, I installed `dbus-x11` which was not installed.

It should have been installed automatically as a "recommends" dependency:
https://github.com/Xpra-org/xpra/blob/be310a793273e4a2445ceb09592ec3685db2aa5d/packaging/debian/xpra/control#L148-L149

**Comment by SanjayVas** [comment]
> It should have been installed automatically as a "recommends" dependency

This is fully up to whomever is installing this, right? e.g. `--no-install-recommends` or even installing from .deb files manually using `dpkg` or `gdebi`

**Comment by totaam** [comment]
> This is fully up to whomever is installing this, right?

Yes, but as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs, this should be stated from the onset, to save us all valuable time.

Please also be aware that a missing or broken `dbus-x11` should never be able to cause xpra or the Xorg server to crash, this is exactly why Debian is a Tier-3 platform: https://github.com/Xpra-org/xpra/wiki/Platforms
