### ISSUE TITLE
Failed to copy from linux to windows

### ISSUE THREAD

**Issue by cadem** [Xpra-org/xpra#4233]
I attach to a linux app from a windows.
I copy a Chinese charactor from linux app to a windows app, but I didn't get the correct chinese word, but got a strange charator.

**Comment by totaam** [comment]
Can you paste the original character in this github issue?
So that I can try copying it myself.
Please also specify which versions you are using at both ends.

**Comment by cadem** [comment]
any Chinese charactor, like 中文字符. 
linux server:
xpra --version
xpra v6.0-r0

windows client:
6.1
revision 35715
commit g1ec038bf9a from master branch

**Comment by totaam** [comment]
Could be related to #4225

**Comment by totaam** [comment]
Trivial fix in 4b8baa544b402c17030e483128cb3caf3659ca23, this had been broken for a long time!

This will be included in v6.0.1
