### ISSUE TITLE
"Server does not support speaker forwarding" when connected via SSH

### ISSUE THREAD

**Issue by b2jammer** [Xpra-org/xpra#4236]
**Describe the bug**
When connected via SSH, all "Sound" items in client's Xpra system tray menu are grayed out with "Server does not support speaker forwarding" tooltip, and no audio plays through client speakers.

**To Reproduce**
1. server command
`xpra start :100 --start="xterm" -d audio,gstreamer,av-sync`

Also tried adding option `--pulseaudio=yes`, to no effect.

2. client command
Windows: `"C:\Program Files\Xpra\xpra_cmd" attach ssh:[user]@[host] -d audio,gstreamer,av-sync`
Linux: `xpra attach ssh:[user]@[host] -d audio,gstreamer,av-sync`

Also tried adding option `--speaker=on`, to no effect.

3. specific action to trigger the bug
    1. In `xterm` window, enter: `aplay /dev/random`
    2. Command appears to run as normal, but no sound is output.

**System Information (please complete the following information):**
 - Server OS: Debian 12 Bookworm (Also tried Xubuntu 24.04 Noble Numbat)
 - Client OS: Windows 11 Home (Also tried Debian 12 Bookworm and Xubuntu 24.04 Noble Numbat)
 - Xpra Server Version 6.0-r0
 - Xpra Client Version 6.0-r0

**Additional context**
Neither the documentation nor the wiki specified any additional setup for audio beyond installing Xpra itself on server and client.

**Logs:**
(logs with the same number (e.g. log1) belong to the same session)
[log1_win11_client.txt](https://github.com/Xpra-org/xpra/files/15367101/log1_win11_client.txt)
[log1_debian_server.txt](https://github.com/Xpra-org/xpra/files/15367100/log1_debian_server.txt)

[log2_debian_client.txt](https://github.com/Xpra-org/xpra/files/15367102/log2_debian_client.txt)
[log2_xubuntu_server.txt](https://github.com/Xpra-org/xpra/files/15367103/log2_xubuntu_server.txt)

[log3_xubuntu_client.txt](https://github.com/Xpra-org/xpra/files/15367099/log3_xubuntu_client.txt)
[log3_debian_server.txt](https://github.com/Xpra-org/xpra/files/15367098/log3_debian_server.txt)

**Comment by totaam** [comment]
> When connected via SSH

This bug is not related to SSH, it is already fixed and will be included in v6.0.1: c16792368631f3c73ac98a0c7cd61062dc5befaf
