### ISSUE TITLE
Dithering artifacts with PNG encoding

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#4237]
**Describe the bug**
When using PNG encoding, it seems like colors are dithered and I think in older versions they were just clamped to the nearest color in the palette. Even though it may look better for photos, dithered areas look like having artifacts when UI elements and other larger areas with a constant color are rendered and it would probably look better to map them to the nearest color, or provide an option to choose if colors should be dithered.

**To Reproduce**
1. Switch to PNG as video encoding
2. Open a window with some large single color area of a color that is not in the palette.

**System Information (please complete the following information):**
 - Server OS: Debian stable
 - Client OS: Debian stable
 - Xpra Server Version: 6.0
 - Xpra Client Version: 6.0

**Additional Context**
I wonder if the PNG palette is fixed or optimized for the current image. Many patches would probably not contain more than 256 colors if the palette would be adapted to the image contents.

**Comment by totaam** [comment]
> When using PNG encoding, it seems like colors are dithered and I think in older versions they were just clamped to the nearest color in the palette

Please include a screenshot.

> Switch to PNG as video encoding

PNG is not a video encoding.
Even when switching to `png`, the xpra server may still use other encodings as needed.
You can run the server with `-d compress` or the client with `-d draw` to see what is actually being used.
Or even use `XPRA_PAINT_BOX=1 xpra attach` to see it visually using colour-coding.

> I wonder if the PNG palette is fixed or optimized for the current image. 

`png` does not use a palette.
`png/L` and `png/P` do.

It must be something else, perhaps an issue with pre-multiplied alpha instead.

**Comment by allo-** [comment]
I meant "PNG 8 bit colour" and `-d draw` tells that PNG/P is indeed used.

It then looks like this:
![image](https://github.com/Xpra-org/xpra/assets/1482341/26e9ebf2-5046-4c06-b308-981afc1aecb3)

**Comment by totaam** [comment]
OK, so not plain png then.
Don't use `PNG 8 bit colour`.
I very much doubt that it is any better than letting the xpra engine compress things.

**Comment by totaam** [comment]
I keep saying it again and again, documenting it, wikying it.
I even added a GUI in v6 to stop people messing with encodings: https://github.com/Xpra-org/xpra/issues/4064#issuecomment-2126907280

**Comment by totaam** [comment]
> If there are new warnings and new configuration UI, I have completely missed it so far.

Try `xpra configure`
fd3e265de4543ca70c2f89bdfc46547ceda9adbb also adds it to the GUI you get when running just `xpra`
