### ISSUE TITLE
When using HiDPI, in Ghidra, some window content is not scaled up but some are

### ISSUE THREAD

**Issue by pellaeon** [Xpra-org/xpra#4242]
**Describe the bug**
1. I have 2 screens, one is scaled at 150%, the other at 100%
2. When running Ghidra from xpra, and placing all windows on the 150% screen, one window of Ghidra has the correct frame size, but the content was small (seems to be 1/2 size). One other window has both correct window frame size and content size.

**To Reproduce**
1. `xpra start ssh://...`
2. Download and unpack [Ghidra](https://github.com/NationalSecurityAgency/ghidra/releases), I tested 11.0.3 and 10.2.2.
3. Run Ghidra by running `./ghidraRun` in the unpacked directory.
4. See the screenshot:
![Screenshot_20240530_154410](https://github.com/Xpra-org/xpra/assets/916913/e50e9225-5ce6-4697-a9cc-ca67543af2bc)

**System Information (please complete the following information):**
 - Server OS: Ubuntu 22.04.4 LTS
 - Client OS: Ubuntu 24.04 LTS
 - Xpra Server Version: 6.1-r35816-1
 - Xpra Client Version: Xpra GTK3 Wayland client version 6.1-r35816 (gefa5e2cf65) beta
 - KDE Plasma version: 5.27.11
 - Display server: Wayland

**Additional context**
* If I move the windows to the 100% screen, everything becomes normal again.
* I tested `konsole` running on the xpra server, with its window on the 150% screen, it is displayed as expected. (It's blurry but expected.)
* Regardless of the setting of [KDE's Xwayland Client Scale ](https://pointieststick.com/2022/06/17/this-week-in-kde-non-blurry-xwayland-apps/), the behavior of this bug is the same.

**Comment by totaam** [comment]
Sounds quite similar to #4167 for macos.
I believe that MS Windows also has the same problem, see also #3943 which may help there.

**Comment by totaam** [comment]
Could be related to #3994

**Comment by totaam** [comment]
This commit fixes things for v6.1 when running Wayland clients: 641847cf278aef4859497c7f0e55f6d3d67a162e
Wayland clients and MacOS / Windows use the `--opengl=gtk` backend - I will need to test some more before backporting this to older branches.
