### ISSUE TITLE
docs: Usage/Desktop.md not found

### ISSUE THREAD

**Issue by megies** [Xpra-org/xpra#4256]
**Describe the bug**

On the ["usage" section of the docs](https://github.com/Xpra-org/xpra/tree/master/docs/Usage), there is a link to `Desktop.md` under "Forwarding a full desktop" but that file does not seem to exist.

Edit: Same goes for `Usage/Shadow.md`

**Comment by totaam** [comment]
I have reverted the faulty commit in 6ba9ba81b53cda66d78ce0e8d84dac47c6f97663.

**Comment by megies** [comment]
@totaam maybe I'm missing something here, but those pages are still not there and looking back at the git history, I believe the problem was with this commit 6faf11a675ccf38e6034d82c06465eba56576448 in April when the two pages seem to inadvertently got `git rm`'d instead of `git mv`'d.

**Comment by totaam** [comment]
The files were sitting in my local tree.
I believe I had a commit that moved them, then I must have used `git reset` and forgot to re-add them afterwards.
