### ISSUE TITLE
Dead link / Redundant wiki page

### ISSUE THREAD

**Issue by Miladiir** [Xpra-org/xpra#4258]
On https://github.com/Xpra-org/xpra/wiki/Platforms#-macos

https://github.com/Xpra-org/issues/2441 should be changed to

https://github.com/Xpra-org/xpra/issues/2441

The whole page seems a bit redundant, since there is also a downloads page with a lot of the same information.

**Comment by totaam** [comment]
Done.

Platforms and Downloads are not the same thing.
