### ISSUE TITLE
Can not get Xpra working on python3.8.10

### ISSUE THREAD

**Issue by ujasindro** [Xpra-org/xpra#4267]
Can you please help me to solve this without updating my python version

![image](https://github.com/Xpra-org/xpra/assets/109538925/101f3355-3f0b-4a08-9c1e-9903ec7fe125)

**Comment by totaam** [comment]
Use xpra v5.x LTS branch which supports Python 3.6+

**Comment by ujasindro** [comment]
I tried this and it gave me an error 
![image](https://github.com/Xpra-org/xpra/assets/109538925/718cd799-37c2-4882-9967-736484fc3943)

**Comment by totaam** [comment]
Please do not use screenshots for text. Paste as text so that it remains searchable.

Building for supported distributions is documented here: https://github.com/Xpra-org/xpra/tree/master/docs/Build
For other distributions, steps may vary, please refer to your distribution package manager.

**Comment by ujasindro** [comment]
hello, i have tried all the possible methods to get the Xpra working. hwever, I ended up getting the same error all time.

xpra main error:
Traceback (most recent call last):
  File "/home/indro/.local/lib/python3.8/site-packages/xpra/scripts/main.py", line 111, in main
    options, args = do_parse_cmdline(cmdline, defaults)
  File "/home/indro/.local/lib/python3.8/site-packages/xpra/scripts/parsing.py", line 1783, in do_parse_cmdline
    fixup_options(options)
  File "/home/indro/.local/lib/python3.8/site-packages/xpra/scripts/config.py", line 1581, in fixup_options
    fixup_encodings(options)
  File "/home/indro/.local/lib/python3.8/site-packages/xpra/scripts/config.py", line 1432, in fixup_encodings
    from xpra.codecs.codec_constants import PREFERRED_ENCODING_ORDER
  File "/home/indro/.local/lib/python3.8/site-packages/xpra/codecs/codec_constants.py", line 29, in <module>
    PREFERRED_REFRESH_ENCODING_ORDER: tuple[str, ...] = (
TypeError: 'type' object is not subscriptable

**Comment by totaam** [comment]
Try the v5.x branch

**Comment by ujasindro** [comment]
I tried v5.x branch but still gives the same error

**Comment by totaam** [comment]
> I tried v5.x branch but still gives the same error

No, it does not.
The syntax in v5.x is different and is compatible with older Python versions:
https://github.com/Xpra-org/xpra/blob/0005b89738387e95e764608a5b2d9e5f11dfa208/xpra/codecs/codec_constants.py#L29

You must be doing something wrong, perhaps not removing the v6.x installation you attempted, or not installing v5.x properly.
