### ISSUE TITLE
Is Xpra 6.0.1 available within the Ubuntu Jammy repo?

### ISSUE THREAD

**Issue by jeffmax** [Xpra-org/xpra#4268]
**Describe the bug**
When I search for available versions of Xpra on Jammy (after adding the xpra.sources file), the most recent version I see is:  "6.0-r0-1"

Is there a  6.0.1-r0-1 version?

**Comment by totaam** [comment]
Sorry about that, I can't remember why this particular build had failed (probably a transient upstream repository failure) and the logs have since been overwritten.

I have re-spawned it and it succeeded this time.
