### ISSUE TITLE
xpra-6.1 source code compilation, missing dependency packages（libproc2） and unable to install

### ISSUE THREAD

**Issue by qingjh** [Xpra-org/xpra#4274]
In CentOS 8.4,when I executed the command：rpmbuild -ba xpra.spec, I got the following error:
```
ERROR: call to 'pkg-config --libs libproc2' failed (err=Package libproc2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libproc2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libproc2', required by 'virtual:world', not found
)
error: Bad exit status from /var/tmp/rpm-tmp.m0ktFk (%build)
```
How should I install the libproc2?

**Comment by totaam** [comment]
CentOS 8.4 is too old. 
Even the v5.x LTS branch probably won't build on it.

**Comment by totaam** [comment]
Installing the build dependencies is covered here: https://github.com/Xpra-org/xpra/blob/master/docs/Build/RPM.md

**Comment by qingjh** [comment]
> CentOS 8.4 is too old. Even the v5.x LTS branch probably won't build on it.

If I want to compile the latest version of xpra, what is the CentOS version at least?

**Comment by totaam** [comment]
CentOS is no longer supported. 
Please see
https://github.com/Xpra-org/xpra/wiki/Platforms

**Comment by qingjh** [comment]
> CentOS is no longer supported. Please see https://github.com/Xpra-org/xpra/wiki/Platforms

thank u,and if I compile xpra with CentOS 8.4, which version of xpra will be compile successfully

**Comment by totaam** [comment]
No idea, don't use an out of date distribution.
Your best bet is still 5.x LTS. v6.1.x may still work, for now.
Have you tried the build instructions or not?

**Comment by qingjh** [comment]
> No idea, don't use an out of date distribution. Your best bet is still 5.x LTS. v6.1.x may still work, for now. Have you tried the build instructions or not?

I've tried compiling both 5.x and 6.x versions, but both are missing dependencies and can't install them

**Comment by totaam** [comment]
> `but both are missing dependencies and can't install them`

Without details, it's impossible to help.
There's a whole section devoted to installing build dependencies:
https://github.com/Xpra-org/xpra/blob/master/docs/Build/RPM.md#install-build-requirements
What's the problem with it?
What's the error?

**Comment by qingjh** [comment]
> > `but both are missing dependencies and can't install them`
> 
> Without details, it's impossible to help. There's a whole section devoted to installing build dependencies: https://github.com/Xpra-org/xpra/blob/master/docs/Build/RPM.md#install-build-requirements What's the problem with it? What's the error?

The centos version is 8.4,and the xpra version is 6.1.
By linking:https://github.com/Xpra-org/xpra/blob/master/docs/Build/RPM.md, try to build an rpm package. 

Execute the command：dnf builddep xpra.spec,I got the error:No matching package to install：'xxx'
Some dependencies can be installed manually, and some dependencies need to be installed by changing the package name。
Finally, execute the command without error

And execute the command：rpmbuild -ba xpra.spec,I got the following error:
ERROR: call to 'pkg-config --libs libproc2' failed (err=Package libproc2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libproc2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libproc2', required by 'virtual:world', not found
)
error: Bad exit status from /var/tmp/rpm-tmp.m0ktFk (%build)
How to fix this error?

**Comment by totaam** [comment]
> dependencies need to be installed by changing the package name

Details missing. What have you tried to get `procps`?
Have you tried installing `procps-devel`?

**Comment by qingjh** [comment]
> > dependencies need to be installed by changing the package name
> 
> Details missing. What have you tried to get `procps`? Have you tried installing `procps-devel`?

the detail missing:
![img_v3_02cd_cc864870-2174-40d1-80ab-c652532badeg](https://github.com/Xpra-org/xpra/assets/120639672/5ac45282-3c1b-4987-b358-e019911e719c)
procps-devel is already installed.

**Comment by totaam** [comment]
Please do **NOT** use images for text, paste the text.
You may just need to change the RPM spec file to require `procps-devel` instead of `pkgconfig(libprocps)`. This should work.
Another option would be to create the missing pkgconfig file.
