### ISSUE TITLE
XPRA-Client  printing issue, PDFIUM_Print.exe crash

### ISSUE THREAD

**Issue by JuergenGleiss** [Xpra-org/xpra#4275]
When I print a document on the server, it is transferred to the client. The command PDFIUM_Print.EXE  is invoked, but crashes. The PDF document is correct and can be opened without any problems. The error can be repeated for me if I call the command manually: **PDFIUM_Print.exe test.pdf 'printer name 'TEST'**

**System Information (please complete the following information):**
 - Server OS: Debian 12 (bookworm)
 - Client OS:  MS Windows 11 Pro, latest patch level
 - Xpra Server Version:  6.1-r35816 
 - Xpra Client Version: 6.0.1-r0

**Additional context**
The program crashes in **/xpra/platform/win32/ctypes_printing.py:152**. After changing malloc.restype, free.argtypes and free.resttype the program crashes **/xpra/platform/win32/pdfium.py:113**.  Cause of my version is 64bit the size of the pointer changes.
 [ctypes_printing_patch.txt](https://github.com/user-attachments/files/16065798/ctypes_printing_patch.txt)

**Comment by totaam** [comment]
Does the patch really fix things for you?
Why would the bundled ctypes have the wrong return type for `malloc` and `free`??
Surely other components would crash?

**Comment by totaam** [comment]
Applied in a0c188bc1310781c133a04d627bc832d5d97f9ee.
Thanks!

This is the only place where we use the `msvcrt` version of `malloc` and `free` - and I'm not quite sure why that is.

**Comment by JuergenGleiss** [comment]
Thanks for quickly applying the patch but PDFIUM_Print.exe still crashes and no documents are printed.

**Additional context**
I did a little research (https://developers.foxit.com/resources/pdf-sdk/c_api_reference_pdfium/group___f_p_d_f_i_u_m.html#gad3c37d53910b1feec99a1961052bfb2f) and looked at pypdfium2. Thus I adapted the order of the fields and the type definitions of the **FPDF_LIBRARY_CONFIG** class. I think the return type of **FPDF_LoadPage** is also missing.

[pdfium_patch.txt](https://github.com/user-attachments/files/16070286/pdfium_patch.txt

**Comment by totaam** [comment]
@JuergenGleiss can you submit this as a PR please?
It's hard to read a patch in text form, and harder to apply.
You can just edit the file on github then click create PR when you're done:
https://github.com/Xpra-org/xpra/blob/a0c188bc1310781c133a04d627bc832d5d97f9ee/xpra/platform/win32/pdfium.py#L13
