### ISSUE TITLE
Debian installation

### ISSUE THREAD

**Issue by gtirth** [Xpra-org/xpra#4280]
**Describe the bug**
I am trying to download and install for ubuntu 22 following step by step guide of installing xpra on debian based system. but when I try to run this command ```wget -O "/etc/apt/sources.list.d/xpra.sources" https://xpra.org/repos/$DISTRO/xpra.sources``` it does not get anything and says no server found

**System Information (please complete the following information):**
 - Server OS: ubuntu 20
 - Client OS: ubuntu 22
 - Xpra Server Version (whatever comes from following these steps)

**Comment by totaam** [comment]
> it does not get anything and says no server found

Please include the exact error message.
My guess is that you didn't copy and paste properly or that something is wrong with your internet connection:
```shell
$ ping xpra.org
PING xpra.org (78.129.163.65) 56(84) bytes of data.
64 bytes from xpra.org (78.129.163.65): icmp_seq=1 ttl=51 time=213 ms
^C
```
