### ISSUE TITLE
RHEL 10 builds

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4282]
Based on CentOS "stream10-development" for now.

The repo build scripts needed some small updates: https://github.com/Xpra-org/repo-build-scripts/commit/854ea26fb15fd5c99ebd0f53d12b8644b7a22d17

The RPM packaging will also need updates.

**Comment by totaam** [comment]
Needs backporting to v5.x, v3.1.x

Then when the missing packages become available, remember to undo some of these changes...

**Comment by totaam** [comment]
I hope they haven't broken it on purpose, but I wouldn't put it past them.
dummy driver builds now fail with:
```
	No matching package to install: 'xorg-x11-server-devel >= 1.10.99.902'
```

**Comment by totaam** [comment]
It's not just the dummy driver, they're not even shipping `Xvfb` in RHEL10!
The specfile for `Xwayland` is the `xserver`, with: `%build`: `... -D{xorg,xnest,xvfb,udev}=false ...`

**Comment by totaam** [comment]
It looks like `CentOS:stream10-development` had the files we need for building the dummy driver at some point .. except now it doesn't any more. But I had already updated the buildbot:
https://github.com/Xpra-org/repo-build-scripts/commit/3f31467238d455aec088ac054e38e3632b11e593

Options:
* build our own `Xvfb`
* build our own `xserver` + `dummy` driver
Neither of these options is going to be fun.

**Comment by AswathySK** [comment]
Has there been any work around for the Xvfb issue in rhel10 so far?

**Comment by totaam** [comment]
@AswathySK you can run xpra on RHEL 10 by first starting a headless Wayland display, ie: `weston — backend=headless-backend.so` then using `Xwayland :10 -noreset` to obtain an X11 display on which you can start xpra almost as normal:
```shell
xpra start :10
```

Alternatively, you can build `Xorg` using the Fedora spec file, then build `xorg-x11-drv-dummy`.

**Comment by totaam** [comment]
Apart from the commits above and #4450, the buildbot also needed this change: https://github.com/Xpra-org/repo-build-scripts/commit/9524360c5e180d2fd766f6f00292f2ea8f1da396

There are working beta packages now, with just one minor issue: there is a conflict between `noopenh264` and our `openh264` package which prevents `xpra-codecs` from being installed.

**Comment by totaam** [comment]
The workaround for `openh264` is in dd8d77e872291a54243d21fe090865515bd514a7

Installing xpra from the beta repository should just work on `CentOS stream10`.

The only caveat is that it seems that `Xwayland` gets confused about which wayland display it should be running on, so it is best to specify the display by hand if you have graphical session active for your user:
```shell
xpra start :100
```

**Comment by totaam** [comment]
Some direct links to the beta repos:
https://xpra.org/beta/CentOS/stream10/
https://xpra.org/beta/almalinux/10-kitten/x86_64/
(there are no `xpra` builds for `AlmaLinux 10` because their repositories are missing `xxhash`)

**Comment by totaam** [comment]
The `AlmaLinux 10` builds are available now, thanks to this repo build script change to enable EPEL: https://github.com/Xpra-org/repo-build-scripts/commit/c62297cc9cb70482d79cb830dd5d4b946dbd0345

**Comment by totaam** [comment]
See also #4450 and #4456
