### ISSUE TITLE
ssh:// handler forces hostname lowercase

### ISSUE THREAD

**Issue by luke-jr** [Xpra-org/xpra#4289]
**Describe the bug**
ssh:// handler lowercases hostname before executing ssh command. This breaks if the hostname is case-sensitive.

**To Reproduce**
1. Configure ~/.ssh/config similarly:
```
Host MYHOST
    Hostname 127.0.0.1
```
2. xpra start ssh://MYHOST/100

Result: `ssh: Could not resolve hostname myhost: Name or service not known`

**System Information (please complete the following information):**
 - Xpra Client Version 6.0.1

**Comment by luke-jr** [comment]
This seems to have regressed in 18720c1f1d9fcade877c6174c7ef65d6580471ea. Python's `urllib.parse.urlparse` is documented to lowercase the `hostname` field. `netloc` is unaffected, but includes user/password/port.

**Comment by totaam** [comment]
The fact that OpenSSH decided to use case-sensitive configuration for case insensitive data is unfortunate,  but I will not change this back.

[rfc4343](https://datatracker.ietf.org/doc/html/rfc4343) : _While the above Request for Comments (RFC) from 1985 can be seen as archaic, it still holds true today in most environments, so DNS names and hostnames are case-insensitive by default_
