### ISSUE TITLE
XPRA Not Working when accessing remotely- encryption ERROR/SSL not working/Authentication and Encryption 

### ISSUE THREAD

**Issue by aaron26122** [Xpra-org/xpra#4291]
I am getting an ENCRYPTION error and it is not working. Kerberos-password is not working either and I get a no module "Kerberos" found.
I have tried tying Kerberos with SSL and it is not tying them together, instead allows for a "fake authentication challenge," please inform me how to get XPRA working remotely on UBUNTU server with either PAM/Kerberos Authentication and an SSL/SSH system. I have spent a long time trying to get things resolved with the documentation. Many Hours. I have tried 5.0.9 and the new 6.1 beta and I am still running into issues. My windows machine is getting an "ENCRYPTION" error on the client when I use the actual IP address on the internet and not an SSH tunnel. Is it not possible to have authentication with encryption? Otherwise, the system allows any random person to gain access. Thank you for assisting.

**Comment by totaam** [comment]
There are not enough details to act on this ticket. Please see https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
Not heard back.
