### ISSUE TITLE
screen corruption/green on vscode

### ISSUE THREAD

**Issue by cavedon** [Xpra-org/xpra#4305]
The screen appears corrupted, apparently only when using vscode.
This started happening with the upgrade to xpra 6.1

![image](https://github.com/user-attachments/assets/e8a0c3d5-cfde-43e6-938e-0e94aaaa3a5c)

**To Reproduce**
`GDK_BACKEND=x11 xpra start ssh://192.168.86.163  --start code`

**System Information (please complete the following information):**
 - Server OS: Ubuntu jammy
 - Client OS: Ubuntu jammy
 - Xpra Server Version: 6.1-r0-1
 - Xpra Client Version: 6.1-r0-1

The problem also happens without `GDK_BACKEND=x11`.
The problem does not happen with `--opengl=no`.

[xpra bugreport.zip](https://github.com/user-attachments/files/16329402/xpra.bugreport.zip)

**Comment by totaam** [comment]
Wow, that's weird!
The fact that this doesn't happen with `opengl=no` tells me that it's probably the colorspace conversion using the wrong range.
I suspect that the problem happens with `webp` encoding.
I had made a note of: d6d59a07116fdea90f75290133baded570533527 + d06a100dc36d26595bbf107aa46b6457700783f0 + 28bc4c6f60d6ae46eb187314364782146cad5605
We have unit tests for that, but somehow the colors looked wrong so I had reverted it.

I'll have to take another look.

---

Whilst we're here, this shouldn't occur at all if we had correctly mapped vscode to `text` content-type, but that needs work: #4248 (from #4343)

**Comment by totaam** [comment]
@cavedon can you try running your client with `XPRA_WEBP_YUV=0 xpra attach ..`
Does that make the green tint go away?

**Comment by totaam** [comment]
@cavedon that one is easier: I forgot to disable scroll encoding again in 6.1
You can fix this one with `--encodings=all,-scroll`

**Comment by totaam** [comment]
I think I may be onto something: the tests insist that the data is "studio" range whereas I can clearly see that it's not.
But the unit tests go through the one shot encode function:
https://github.com/Xpra-org/xpra/blob/13a130e52f22be3c5dd447443421cf58055c7d78/xpra/codecs/webp/encoder.pyx#L668
Whereas the "studio" range images that I see have a `frame` number, so they go through the pseudo video encoder at:
https://github.com/Xpra-org/xpra/blob/13a130e52f22be3c5dd447443421cf58055c7d78/xpra/codecs/webp/encoder.pyx#L526
The metadata has a `subsampling=YUV420P` value, so the image data has been processed by `WebPPictureARGBToYUVA` in
https://github.com/Xpra-org/xpra/blob/13a130e52f22be3c5dd447443421cf58055c7d78/xpra/codecs/webp/encoder.pyx#L795

Somehow, these two functions don't produce the same color range!

**Comment by cavedon** [comment]
Confirming that `--encodings=all,-scroll` solves the corruption form me, thanks!
Let me know if there is any test I can do to help.
