### ISSUE TITLE
invalid compression: zlib is not available

### ISSUE THREAD

**Issue by oie1** [Xpra-org/xpra#4313]
**Describe the bug**
cannot connect to xpra and I get this in systemd logs

**To Reproduce**
connecting to xpra

**System Information (please complete the following information):**
 - Server OS: bookworm
 - Client OS: mint wilma
 - Xpra Server Version: xpra v6.2.0-r36379 (g5244b9ebb9) beta (compiled from master)
 - Xpra Client Version: xpra v3.1.5 (installed from apt but shouldn't be the issue because its happening server-side)
 
 **Logs**
 ```
 Jul 30 19:25:14 denisland.ovh xpra[71057]: 2024-07-30 19:25:14,998 New tcp connection received
Jul 30 19:25:14 denisland.ovh xpra[71057]: 2024-07-30 19:25:14,998  from '::ffff:192.168.1.102, 55846, 0, 0'
Jul 30 19:25:14 denisland.ovh xpra[71057]: 2024-07-30 19:25:14,998  on '[::]:14500'
Jul 30 19:25:15 denisland.ovh xpra[71057]: 2024-07-30 19:25:15,000 Disconnecting client ::ffff:192.168.1.102, 55846, 0, 0:
Jul 30 19:25:15 denisland.ovh xpra[71057]: 2024-07-30 19:25:15,000  invalid compression: zlib is not available
Jul 30 19:25:15 denisland.ovh xpra[71057]: 2024-07-30 19:25:15,102 0 packets received (0.9K bytes)
Jul 30 19:25:15 denisland.ovh xpra[71057]: 2024-07-30 19:25:15,102 1 packets sent (54 bytes)
```

**Comment by totaam** [comment]
Don't use [broken distribution packages](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages) - these are dangerous.

**Comment by oie1** [comment]
> Don't use [broken distribution packages](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages) - these are dangerous.

kay, now I am on windows and I get different error in the systemd logs, ive tried both the stable - 6.1 and the beta 6.2, same thing
systemd logs:
```
Aug 01 07:37:44 denisland.ovh xpra[71057]: 2024-08-01 07:37:44,761 New tcp connection received
Aug 01 07:37:44 denisland.ovh xpra[71057]: 2024-08-01 07:37:44,761  from '::ffff:192.168.1.101, 54349, 0, 0'
Aug 01 07:37:44 denisland.ovh xpra[71057]: 2024-08-01 07:37:44,761  on '[::]:14500'
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,766 Authentication required by PAM authenticator module
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,766  sending challenge using 'xor' digest over tcp connection
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,780 client has requested disconnection: invalid digest
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,780 Disconnecting client ::ffff:192.168.1.101, 54354, 0, 0:
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,780  client request
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,881 2 packets received (1.9K bytes)
Aug 01 07:37:49 denisland.ovh xpra[71057]: 2024-08-01 07:37:49,881 2 packets sent (169 bytes)
```

**Comment by totaam** [comment]
This has nothing to do with zlib.
Xpra just refuses to send your password over unencrypted connections.

Either [encrypt the connection](https://github.com/Xpra-org/xpra/blob/master/docs/Network/Encryption.md) (ssl, aes, quic, etc) or use a different [authentication module](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md).

**Comment by oie1** [comment]
> This has nothing to do with zlib. Xpra just refuses to send your password over unencrypted connections.
> 
> Either [encrypt the connection](https://github.com/Xpra-org/xpra/blob/master/docs/Network/Encryption.md) (ssl, aes, quic, etc) or use a different [authentication module](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Authentication.md).

now I got this and xpra is "not responding" according to windows
![image](https://github.com/user-attachments/assets/8d7bde37-5fa4-4109-92b6-3b1251643406)

**Comment by totaam** [comment]
Which client version is this?
The "handle is invalid" error was meant to be fixed in 6.1 and it should only occur when connecting from a GUI. (either the launcher or the mdns gui)
In any case, the opengl failure should not be fatal.

**Comment by oie1** [comment]
> Which client version is this? The "handle is invalid" error was meant to be fixed in 6.1 and it should only occur when connecting from a GUI. (either the launcher or the mdns gui) In any case, the opengl failure should not be fatal.
its 6.2.0, yes im using gui, will try cli
![image](https://github.com/user-attachments/assets/dcacc03b-c229-4e3a-b2a6-2dcdcd396621)

**Comment by totaam** [comment]
ie: `xpra_cmd.exe attach tcp://host:port/`

**Comment by oie1** [comment]
> ie: `xpra_cmd.exe attach tcp://host:port/`

the same error happens

**Comment by oie1** [comment]
actually I ran it with xpra instead of xpra_cmd but it still gives a error (not sure if its the same) and crashes
![image](https://github.com/user-attachments/assets/f6d9cc1f-3bb4-4ad8-961c-a8d2fdd6268c)

**Comment by oie1** [comment]
its a different error but still crashes

**Comment by oie1** [comment]
![image](https://github.com/user-attachments/assets/e5ad44be-3f1c-43d2-980f-16b54fb35970)

**Comment by totaam** [comment]
This is not a fatal error. The client is still connecting.

**Comment by oie1** [comment]
> This is not a fatal error. The client is still connecting.
> 
> Please don't post images of text, use cut&paste.

it is fatal because it shows as not responding
here is error then
```
2024-08-01 06:37:34,740 Xpra GTK3 client version 6.2.0-r36327 (g20c167a95a) beta
2024-08-01 06:37:35,226  running on Microsoft Windows Microsoft Windows 11 Pro
2024-08-01 06:37:35,228  cpython 3.11
2024-08-01 06:37:40,141 GStreamer version 1.24.5
2024-08-01 06:37:40,161 created named pipe 'Xpra\11548'
2024-08-01 06:37:40,541 Error setting up the pipeline:
2024-08-01 06:37:40,541  gst_parse_error: could not link decoder to sink (3)
2024-08-01 06:37:40,541  GStreamer pipeline for:
2024-08-01 06:37:40,547   appsrc name=src emit-signals=1 block=0 is-live=1 do-timestamp=1 stream-type=0 format=2 caps=video/x-h264,width=128,height=128,profile=(string)main,stream-format=(string)byte-stream,alignment=(string)au ! \
2024-08-01 06:37:40,547   d3d11h264dec name=decoder ! \
2024-08-01 06:37:40,547   appsink name=sink emit-signals=1 max-buffers=10 drop=False sync=False async=True qos=False caps=video/x-raw,width=128,height=128,format=(string)I420
2024-08-01 06:37:40,547 Error creating context h264 128x128 YUV420P
2024-08-01 06:37:40,552 gstreamer: h264 decoding failed: failed to setup gstreamer pipeline
2024-08-01 06:37:40,567 keyboard layout 'United States - English' : 'us' (0x409)
2024-08-01 06:37:42,582 OpenGL enabled on 'Intel(R) Iris(R) Xe Graphics'
```

**Comment by totaam** [comment]
If it's frozen, perhaps it is having problem connecting - without your command line, I can't say for sure.

Maybe try a stable version?
6.2 is from the beta channel.

**Comment by oie1** [comment]
> If it's frozen, perhaps it is having problem connecting - without your command line, I can't say for sure.
> 
> Maybe try a stable version? 6.2 is from the beta channel.

still happens

**Comment by totaam** [comment]
Well, then, don't use quic for starters.
It's probably a network issue.

**Comment by oie1** [comment]
> Well, then, don't use quic for starters. It's probably a network issue.

tcp wont work for encryption and ssl requires some certificate? I have ssl certificates on the server, just dont know how to make xpra use them

**Comment by totaam** [comment]
> and ssl requires some certificate

so does quic..

**Comment by oie1** [comment]
> > and ssl requires some certificate
> 
> so does quic..

may I know how to set up the ssl?

**Comment by oie1** [comment]
I have found a conf.d file which has that I will fill it out

**Comment by totaam** [comment]
Don't modify system files, see https://github.com/Xpra-org/xpra/blob/master/docs/Network/SSL.md

**Comment by oie1** [comment]
okay so ssl is now ok but issue is that pipeline error

**Comment by totaam** [comment]
the pipeline error is unimportant, you can skip it with `--video-decoders=all,-gstreamer`

**Comment by oie1** [comment]
> the pipeline error is unimportant, you can skip it with `--video-decoders=all,-gstreamer`

now it isnt erroing but xterm isnt starting either - my cmdline - `xpra_cmd attach quic://root:pass@192.168.1.100:14500/ --ssl-ca-certs=C:\Users\denis\Documents\ssl-cert-snakeoil.pem --start-child=xterm --video-decoders=all,-gstreamer`
log is this no errors
```
2024-08-01 07:16:17,553 Xpra GTK3 client version 6.1-r0
2024-08-01 07:16:18,088  running on Microsoft Windows Microsoft Windows 11 Pro
2024-08-01 07:16:18,090  cpython 3.11
2024-08-01 07:16:23,142 GStreamer version 1.24.5
2024-08-01 07:16:23,158 created named pipe 'Xpra\7788'
2024-08-01 07:16:23,362 keyboard layout 'United States - English' : 'us' (0x409)
2024-08-01 07:16:25,041 OpenGL enabled on 'Intel(R) Iris(R) Xe Graphics'
```

**Comment by totaam** [comment]
> `xpra_cmd attach ...`

What about the server?
What command?
What does the log show?

**Comment by oie1** [comment]
> > `xpra_cmd attach ...`
> 
> What about the server? What command? What does the log show?
> 
> I would start with ssl, worry about using quic later.

ssl config not working
giving this
```
Aug 01 10:23:09 denisland.ovh xpra[673042]: 2024-08-01 10:23:09,121 Error: failed to create SSL socket
Aug 01 10:23:09 denisland.ovh xpra[673042]: 2024-08-01 10:23:09,122  from tcp socket: <socket.socket fd=10, family=10, type=1, proto=0, laddr=('::ffff:192.168.1.10>
Aug 01 10:23:09 denisland.ovh xpra[673042]: 2024-08-01 10:23:09,122  no certificate paths specified
Aug 01 10:23:09 denisland.ovh xpra[673042]: 2024-08-01 10:23:09,122  [Errno 2] No such file or directory
```
even though I've configured in /etc/xpra/conf.d/12_ssl.conf

**Comment by totaam** [comment]
> Don't modify system files, see https://github.com/Xpra-org/xpra/blob/master/docs/Network/SSL.md

**Comment by oie1** [comment]
> > Don't modify system files, see https://github.com/Xpra-org/xpra/blob/master/docs/Network/SSL.md

showing this even when I click yes in dialog to accept my self signed cert
```
2024-08-01 07:27:35,975 Warning: failed to save certificate data
Warning: failed to connect:
 self-signed certificate
E:/xpra/xpra/scripts/main.py:1557: ResourceWarning: unclosed <ssl.SSLSocket fd=1000, family=2, type=1, proto=0, laddr=('192.168.1.101', 55952), raddr=('192.168.1.100', 14500)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by oie1** [comment]
also it only allows me to use root, if i use other user it says invalid username
