### ISSUE TITLE
test pyqt6 client

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4314]
Just for testing, because it's actually fairly easy to implement now that the code is quite modular.

**Comment by totaam** [comment]
The commit above implements a tiny and not very useful client that is only capable of showing windows using rgb encoding..
It only supports tcp, no authentication, no keyboard, no nothing.
```shell
python3 xpra/client/qt6/main.py 127.0.0.1 10000
```

**Comment by totaam** [comment]
Now available as a package: `xpra-client-qt6` and also included in the win32 fat builds.
Can be tested using:
```sh
XPRA_GUI_BACKEND=qt xpra attach tcp://192.168.0.10:10000/
```
Still only works for TCP sockets.

---

Some useful documentation links:
* [Qt6 window geometry](https://doc.qt.io/qt-6/application-windows.html#window-geometry)
* [Qt6 event system](https://doc.qt.io/qt-6/eventsandfilters.html)

**Comment by totaam** [comment]
Important: new syntax for enabling the qt6 client:
```
xpra attach tcp://192.168.0.10:10000/ --backend=qt
```

**Comment by hadogenes** [comment]
@totaam could you update debian packaging, because I would like to use it, but now it is unavailable.

**Comment by totaam** [comment]
@hadogenes the packaging bits are in 0c0291c4dec5229ce928cb87e1e4d266d4b25a3c.
There is a long queue of stable / lts builds ahead of this.
In the meantime, you can easily build it: https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md


Be aware that this is not a complete client by any means.
