### ISSUE TITLE
Unable to set window title

### ISSUE THREAD

**Issue by snhirsch** [Xpra-org/xpra#4325]
**Describe the bug**

The "--title=.." parameter is supposed to set the window title.  It does not.  Regardless of what I pass, the window is always named 'Xpra,  Xpra<2> .. Xpra<n>'

**To Reproduce**
1. server command
2. client command
3. specific action to trigger the bug

I'm running the legacy 'run_scaled' script.  It doesn't matter what the child application is.

```
xpra start "$DISPLAYNUM" \
     --xvfb="Xvfb +extension Composite -screen 0 ${UNSCALED_RESOLUTION}x24+32 -nolisten tcp -noreset  -auth \$XAUTHORITY" \
     --env=GDK_SCALE=1 \
     --env=GDK_DPI_SCALE=1 \
     --start-child="$ESCAPED_PARAMS" \
     --title="Test" \
     --exit-with-children

sleep "$SLEEPTIME"

xpra attach "$DISPLAYNUM" \
     "--desktop-scaling=$SCALING_FACTOR" \
     "--opengl=$USE_OPENGL" \
     --title="Test" \
     $PERFORMANCE_OPTIONS \
     $PERSONAL_OPTIONS || xpra stop "$DISPLAYNUM"
```

**System Information (please complete the following information):**
 - Server OS: [e.g. RHEL 8.x]
 - Client OS: [e.g. Windows 10]

Kubuntu 18.04 LTS

 - Xpra Server Version [e.g. 4.2.3]
 - Xpra Client Version [e.g. 4.3]

3.1.8-r11-1

**Additional context**

Please see "reporting bugs" in the wiki section.

I may be misunderstanding what this flag is intended to do.  If so, my apologies.  Program behavior seems correct in all other aspects .

**Comment by totaam** [comment]
FYI: 3.1.x is EOL.
Please try 88556ec153ef15a2709f6726768a3ad56080d78d or later.

**Comment by snhirsch** [comment]
Thanks SO much for that quick patch to the EOL branch!  Problem is corrected :-)
