### ISSUE TITLE
start-desktop does not work with cinnamon X11 session (black screen)

### ISSUE THREAD

**Issue by Lanchon** [Xpra-org/xpra#4328]
**Describe the bug**
start-desktop does not work with a cinnamon X11 session. client shows black screen, but sounds of the desktop starting can be heard on the client. happens for HW accelerated and 2D session types. happens with or without `--opengl=off` in the client command.

**To Reproduce**
1. server command: none
2. client command:
   - `xpra start-desktop --start=cinnamon-session ssh:server:100`
   - `xpra start-desktop --opengl=off --start=cinnamon-session ssh:server:100`
   - `xpra start-desktop --start=cinnamon-session --resize-display=1600x900 ssh:server:100`
   - `xpra start-desktop --opengl=off --start=cinnamon-session --resize-display=1600x900 ssh:server:100`
   - `xpra start-desktop --opengl=off --start=cinnamon-session-cinnamon --resize-display=1600x900 ssh:server:100`
   - `xpra start-desktop --opengl=off --start=cinnamon-session-cinnamon2d --resize-display=1600x900 ssh:server:100`
4. specific action to trigger the bug: none

**System Information (please complete the following information):**
 - Server OS: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
 - Client OS: Linux Mint 22 Wilma base: Ubuntu 24.04 noble
 - Xpra Server Version: xpra v6.1.1-r0
 - Xpra Client Version: xpra v5.0.9-r0

**Additional context**
on both sides:
Desktop: Cinnamon v: 6.2.9 tk: GTK v: 3.24.41 wm: Muffin vt: 7 dm: LightDM v: 1.30.0
standard X11 session

note that although i'm reporting against mint 22 cinnamon, this already failed in mint 21 cinnamon. i didn't test on earlier versions.

**Comment by totaam** [comment]
> happens with or without --opengl=off in the client command

This doesn't do anything server side, it only probes the opengl backend.

> `--start=cinnamon-session`

Have you tried starting it from an `xterm`?
Is there anything in your server log?
Have you tried other desktops? Simple ones like fluxbox or openbox?

**Comment by totaam** [comment]
Works for me, as long as I am not logged in to X11 from the same user account.
This looks like a "limitation" of cinnamon.
I had it running simultaneously on two displays (main "physical" login on `:0` and `:10` I created via `xpra start-desktop :10 --start=xterm`) and when I clicked on some applications in the menu on `:10`, they showed up on `:0`!

**Comment by Lanchon** [comment]
> Works for me, as long as I am not logged in to X11 from the same user account.

i am not either. in fact, X is not running, this server boots to the console. i need to type `startx` if i want the local DE.

> when I clicked on some applications in the menu on :10, they showed up on :0!

interesting... i tried the above commands but changing :100 for :0 and there were no changes :(

> Have you tried starting it from an xterm?

yes, no luck.

> Is there anything in your server log?

i found nothing of value.

> Have you tried other desktops? Simple ones like fluxbox or openbox?

no, i want to use cinnamon. im using it via XRDP without issues.

**Comment by totaam** [comment]
> no, i want to use cinnamon

fluxbox is tiny to install and this gives you an important data point: is the problem with the window manager or with the xpra setup.

Also worth trying to install xpra from git master:
```shell
apt-get remove xpra
git clone https://github.com/Xpra-org/xpra
cd xpra
./setup.py dev-env
sudo ./setup.py install --prefix=/usr --install-layout=deb
```

---

> `ssh:server:100`

BTW, this syntax has been deprecated for over 10 years now - not sure where you got it from.
Use `ssh://HOST:PORT/DISPLAY`

**Comment by Lanchon** [comment]
sorry this server is not critical, but it still is in production. i don't want to mess with it too much. i will wait for your next package release and test it and report here.

- `--start=xterm` works (at a fixed xterm size).
- `--start=fluxbox` and `--start=fluxbox-remote` do not work; you end up with a black screen too.

maybe this is related to the gstreamer freezing bug?

> this syntax has been deprecated for almost 10 years now

lol am aware of the new syntax but i didn't know this one was deprecated. i just found it easier to type, as all my sshd are on port 22.

**Comment by Lanchon** [comment]
running `xpra start-desktop --start=cinnamon-session --video-encoders=x264,vpx :100` on the server and then attaching to it results in black screen too.

**Comment by totaam** [comment]
> do not work; you end up with a black screen too.

That's odd, in terms of behaviour, they're not so different from an `xterm`.
What if you run them from the xterm?

I don't remember seeing any fixes that could explain this.
I'll have to check with the proper 6.1.1 release, because there is something fundamentally wrong if `fluxbox` doesn't show up.

**Comment by Lanchon** [comment]
> What if you run them from the xterm?

i remember i ran cinnamon from xterm and it didn't work.

i'd suggest waiting for official 6.2 and then i'll re-test. if that doesn't fix it, you might want to install linux mint bare metal somewhere, preferably intel, to debug this. but keep in mind that i'm ok, i don't really need help because i'm using xrdp. my reason for posting issues is less that of my own convenience, but more me wanting to contribute to xpra, because i think it's a really cool project.

**Comment by Lanchon** [comment]
> You don't need to specify the port with the non-deprecated syntax either.

lol i know! but not needing to specify ports made me not need the newer syntax, which although is definitely more rooted on established standards, is a little bit more verbose. that's all.

**Comment by totaam** [comment]
FWIW: https://github.com/Xpra-org/xpra/issues/4330#issuecomment-2308760220

**Comment by Lanchon** [comment]
thanks! i'm still waiting for official 6.2 to do a new round of testing and report.

**Comment by totaam** [comment]
> but i'm think of switching away because of the lack of wayland

Some would see this as a positive thing, moving to wayland often means downgrading features, even for the x11 versions since they share the same codebase.
6.2 has been tagged but not yet released.

**Comment by Lanchon** [comment]
that's true. but there's a feature i want, and i can't get in X: security. i'm tired as hell of thinking for years now that any process can trivially steal my keystrokes; there is no way to sandbox an X application. the missing features of wayland i can endure, but not this anymore. in any case, wayland is catching up rapidly now.

**Comment by totaam** [comment]
> there is no way to sandbox an X application

Well, there is always xpra! :wink:
applications running in xpra can't see your keystrokes or pointer motion (unless enabled explicitly: #4318)

**Comment by Lanchon** [comment]
tested on v6.2.0-r0:

unfortunately, same issue: you can hear the login sounds but the screen is totally black.
