### ISSUE TITLE
make it possible to completely disable all of GStreamer at runtime

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4330]
Using #4307 to completely prevent `gi.repository.Gst` bindings from being loaded.

That's necessary because GStreamer can cause some serious problems.
Latest case in point: Linux Mint 22 in VirtualBox, loading GStreamer kills the X11 server!

**Comment by totaam** [comment]
Done in the commit above. ie:
```shell
xpra start --no-gstreamer
```
This is also activated with `--minimal=yes` (#3953)

**Comment by totaam** [comment]
Very useful since there are some monsters lurking - I'm not blaming GStreamer, hardware access is hard, and crashy.

Running Linux Mint 22 in VirtualBox, simply probing the gstreamer elements from xpra causes the whole desktop session to crash and go back to the login screen!

**Comment by janLo** [comment]
FYI: the death of the X-Server only happens if the gstreamer1.0-vaapi package is installed.

**Comment by totaam** [comment]
@janLo this should probably be reported as security issue somewhere, though I doubt that anyone cares. Hardware access is hard.

Meanwhile, I can't think of anything xpra can do here - `vaapi` is what we need for hardware acceleration on non-nvidia GPUs, so we're caught in a bind.

**Comment by janLo** [comment]
Oh, I don't really need a solution, I just wanted to note that it's not necessary to disable all of gstreamer if the Xorg crash happens.

We discovered this already a year ago. Our solution is to blacklist the package where we can and have it very prominently written in our internal documentation for everyone else coming across this.

**Comment by totaam** [comment]
And now also crashing on MS Windows:
```bat
Xpra_cmd.exe encoding enc_gstreamer
some GStreamer elements are missing or unavailable on this system:
 nvd3d11h264enc, nvd3d11h265enc
*** stack smashing detected ***: terminated
```
