### ISSUE TITLE
Causing Debian GUI first login failure

### ISSUE THREAD

**Issue by bit-lang** [Xpra-org/xpra#4334]
**Describe the bug**
Debian12 xfce desktop, after installing xpra and restart, first time login always fail. Successive login works though. 

**To Reproduce**
1. server command
N/A
2. client command
N/A

3. specific action to trigger the bug:
just login at the lightDM GUI

**System Information (please complete the following information):**
 - Server OS: Debian 12.6 , with xfce 
 - Client OS:N/A
 - Xpra Server Version 
6.1.1
 - Xpra Client Version N/A

**Additional context**

**Comment by totaam** [comment]
I am afraid that this is not an xpra bug, and not the first time that Debian causes things to break either: #2834
xpra should have no way of having any impact on session login.

Please use a better distro.
