### ISSUE TITLE
invalid encoding for tray: 'rgb'  - message repeating continuously

### ISSUE THREAD

**Issue by lionkmp** [Xpra-org/xpra#4336]
**Describe the bug**

This message is repeating very rapidly while I'm connected to Bitcoin Core Qt via Xpra:

```
2024-08-21 23:12:41,803 Warning: tray paint update failed: "invalid encoding for tray: 'rgb'"
2024-08-21 23:12:41,803  for 24x24 rgb32 update with options=typedict({'rgb_format': 'RGBA', 'lz4': 2, 'flush': 0, 'encoding': 'rgb32'})

```

But e.g. if I run "Transmissions" the Tray icon looks OK and no message is running. If I run "Bitcoin Core", the icon looks OK but this message is repeating. In both case the icons shows the app's own icon and a smaller Xpra icon in the icon's corner.

Please note that I'm on IceWM - but in general I had no problems with local tray icons.

And I didn't see any such repeating messages earlier, with previous Xpra versions I think. But recently I didn't try, because I use this software in daemon mode since some months So there may have been both Xpra **and** Bitcoin Core updates since I last tried.

**To Reproduce**
1. Server Command: xpra start :101 --start=/usr/local/bin/bitcoin-qt
2. Client command: xpra attach ssh://lion@egg/101

**System Information:**
 - Server OS: Debian 12
 - Client OS: antiX Linux 23.1, which is also a Debian 12, but without systemd. This is IceWM.
 - Xpra Server Version: xpra v6.1.1-r0
 - Xpra Client Version:  xpra v6.1.1-r0

Thank you in advance! (Not a big problem if you cannot find a reason, but I reported it, just in case...)

**Comment by totaam** [comment]
This is already fixed in 260efe0c91a871e246f5ffede85b28b15f1d64d6.
It was backported to the v6.1.x branch in 8926bd02029ad6f3d862534cedeae9e5b9feb73d and will be included in the v6.1.2 release.
