### ISSUE TITLE
On windows client, change Picture -> Quality will only take effect on GUI after the second clicking

### ISSUE THREAD

**Issue by Simba98** [Xpra-org/xpra#4346]
**Describe the bug**
On windows client, change Picture -> Quality will only take effect on GUI after the second clicking

**To Reproduce**
1. Run Xpra_cmd.exe attach ssh://server
2. TrayIcon -> Picture -> Quality, by default it should be Auto.  Now, click "Best"
3. Reopen TrayIcon -> Picture -> Quality, you will find it still Auto, now click best again.
4. Revisit TrayIcon -> Picture -> Quality, now it is "Best"

**System Information (please complete the following information):**
 - Windows Xpra Build
 - Xpra Client Version 6.1.2-r0, 5.0.9-r0 (But testing with 6.1.2-Server)

**Additional context**
Seems like Speed menu also has same issue.

**Comment by totaam** [comment]
Thanks, something must have changed in GTK which made the menu item callbacks trample on each other.
The commit above fixes that.
