### ISSUE TITLE
PgUp comes through as slash (/)

### ISSUE THREAD

**Issue by molecularentropy** [Xpra-org/xpra#4352]
Connecting to my xpra session (attach), pressing PgUp on the client, a '/' character gets written (I'm in a text editor)

**To Reproduce**
1. start the server: XPRA_USE_NATIVE_TRAY=0 xpra start ssh://user@192.168.0.3/ --tray=yes --dpi=96 --border=red,2 --opengl=no --start=/usr/bin/xfce4-terminal
2. attach to the server: XPRA_USE_NATIVE_TRAY=0 xpra attach ssh://user@192.168.0.3/ --tray=yes --dpi=96 --border=red,2 --opengl=no
3. Go to a text editor, press PgUp, a slash gets inserted.

**System Information:**
 - Server OS: Ubuntu 22.04.4
 - Client OS: Ubuntu 24.04.1
 - Xpra Server Version: 4.4.6-r29
 - Xpra Client Version 5.0.9-r0

**Comment by totaam** [comment]
> Xpra Server Version: 4.4.6-r29

This is not a supported version - there were quite a few keyboard fixes in 6.1.x, especially relevant for platforms that do not expose the full keymap (ie: Wayland).

Please see https://github.com/Xpra-org/xpra/blob/master/docs/Features/Keyboard.md#reporting-bugs

**Comment by molecularentropy** [comment]
Aye caramba! Okay, I shall upgrade to 6.x and report back here.

**Comment by molecularentropy** [comment]
That seems to fix it. Cheers!

**Comment by totaam** [comment]
Same as #4292
