### ISSUE TITLE
Don't use `pkg-config` to look up `py3cairo`

### ISSUE THREAD

**Issue by sebst** [Xpra-org/xpra#4358]
`pycairo` does not provide a `py3cairo.pc` by default. 

Some Linux distributions provide dedicated packages that provide the `.pc` file, like Debian in package [`python3-cairo-dev`](https://packages.debian.org/buster/all/python3-cairo-dev/filelist). This, however, is distribution specific. The original `pycairo` repo does not provide a `py3cairo.pc` file as part as their default installation routine. Related discussion here: [270](https://github.com/pygobject/pycairo/issues/270)

As a result, xpra's `setup.py` should not rely on `pkg-config` to retrieve `pycairo`.

**Comment by totaam** [comment]
That's a big NAK.
The standard way of finding header files is `.pc` files.

A PR that adds another fallback path may be accepted, but this will not be worked on.
