### ISSUE TITLE
Package xpra-audio uninstallable in Ubuntu noble

### ISSUE THREAD

**Issue by LaurentBonnaud** [Xpra-org/xpra#4359]
**Describe the bug**

The xpra-audio package cannot be installed in an Ubuntu 24.04/noble system because of package conflicts

**To Reproduce**
```
# apt install xpra-audio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pipewire-alsa : Conflicts: pulseaudio but 1:16.1+dfsg1-2ubuntu10 is to be installed
 pipewire-audio : Conflicts: pulseaudio but 1:16.1+dfsg1-2ubuntu10 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**System Information (please complete the following information):**
 - OS: Ubuntu 24.04

**Comment by totaam** [comment]
Like it says, audio support in xpra requires `pulseaudio`, this may require you to remove `pipewire`.

**Comment by bensteinberg** [comment]
For people finding this later, I have been able to install xpra successfully without xpra-audio, avoiding the dependency conflict, using

    sudo apt install --no-install-recommends xpra xpra-x11

**Comment by totaam** [comment]
@bensteinberg as of bac3baf87e8f619e60f02c795ffdb7b08220ccef, you should also be able to do:
```
apt install xpra-client
```
To get a client installed with working audio.

Only the server needs `--no-install-recommends` to deal with the pulseaudio conflict - in which case your server will not have working audio.
