### ISSUE TITLE
mac-mini (2010): Xpra-5 & 6.1 work for attach (displays remote desktop with working mouse) but NO KEYBOARD SUPPORT; fail for gui, launcher.

### ISSUE THREAD

**Issue by sto6** [Xpra-org/xpra#4360]
**Describe the bug**
mac-mini (2010): Xpra-5 & 6 work for attach (displays remote desktop with working mouse) but NO KEYBOARD SUPPORT; fail for gui, launcher.
Very similar stacktrace shown for gui, launcher, toolbox(Keyboard), attach (only survived for attach, only the attach stack shows it to be related to the keyboard). toolbox/text-entry field works.
When mini was on High Sierra (10.13), there was no xpra keyboard issue. (Upgraded to Monterey via OpenCoreLegacyPatcher! yeah: way to bury the lede.)

mini gui or launcher: fails with very similar (not survived) stacktrace.
mini toolbox: displays, typing into text-entry field works, Keyboard displays similar stacktrace:
```
...
ImportError: dlopen(/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/lib-dynload/Quartz/CoreGraphics/_callbacks.so, 0x0002): symbol not found in flat namespace (_C\
GDisplayRegisterReconfigurationCallback)
```

**To Reproduce**
remote server start (irrelevant to bug):
```
$ xpra --version
xpra v5.0.5-r1
$ xpra start-desktop :33 --exit-with-children=yes --start-child=startxfce4 --resize-display=yes --desktop-scaling=no --dpi=96
```
client command:
```
% ~/ap/Xpra-6.1.2-r0.app/Contents/MacOS/Xpra --version
xpra v6.1.2-r0
% ~/ap/Xpra-6.1.2-r0.app/Contents/MacOS/Xpra attach ssh://sto@cdsr0/33 --desktop-fullscreen=yes --desktop-scaling=no --speed=100 --quality=100 --dpi=96 --swap-keys=no --debug all --opengl=yes --ssh=ssh --ssh-upgrade=no
...
2024-09-14 17:33:38,574 progress(40, 'loading user interface')
2024-09-14 17:33:38,577 debug enabled for ['xpra.platform.keyboard_base', 'keyboard']
2024-09-14 17:33:38,611 error instantiating <class 'xpra.client.gtk3.keyboard_helper.GTKKeyboardHelper'>
Traceback (most recent call last):
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/client/gui/ui_client_base.py", line 224, in init_ui
    self.keyboard_helper = self.keyboard_helper_class(send_keyboard, opts.keyboard_sync,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/client/gtk3/keyboard_helper.py", line 22, in __init__
    KeyboardHelper.__init__(self, *args)
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/client/gui/keyboard_helper.py", line 47, in __init__
    from xpra.platform.keyboard import Keyboard  # pylint: disable=import-outside-toplevel
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/keyboard.py", line 13, in <module>
    platform_import(globals(), "keyboard", True,
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/__init__.py", line 201, in platform_import
    platform_module = __import__(module, {}, {}, imports)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/keyboard.py", line 13, in <module>
    from xpra.platform.darwin.menu import getOSXMenuHelper
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py", line 22, in <module>
    from xpra.platform.darwin.gui import get_OSXApplication
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/gui.py", line 16, in <module>
    import Quartz
  File "Quartz/__init__.pyc", line 47, in <module>
  File "Quartz/__init__.pyc", line 10, in _setup
  File "Quartz/CoreGraphics/__init__.pyc", line 80, in <module>
  File "Quartz/CoreGraphics/__init__.pyc", line 15, in _setup
  File "Quartz/CoreGraphics/_callbacks.pyc", line 13, in <module>
  File "Quartz/CoreGraphics/_callbacks.pyc", line 9, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/lib-dynload/Quartz/CoreGraphics/_callbacks.so, 0x0002): symbol not found in flat namespace (_CG
DisplayRegisterReconfigurationCallback)
2024-09-14 17:33:38,628 Warning: no keyboard support, dlopen(/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/lib-dynload/Quartz/CoreGraphics/_callbacks.so, 0x0002)
: symbol not found in flat namespace (_CGDisplayRegisterReconfigurationCallback)
```

**System Information (please complete the following information):**
 - Server OS: Rocky Linux 8.9 (Intel)
 - Client OS: macos Monterey 12.7.6 (Intel)
 - Xpra Server Version: xpra v5.0.5-r1
 - Xpra Client Version:  xpra v6.1.2-r0

**Additional context**
Tale of two macs. Both Intel-CPU on Monterey 12.7.6.
For comparison: macbook-pro (2015): Xpra-5 & 6 work (gui, launcher, attach) with keyboard support. Everything works; nice and boring.
xpra-5 refers to 5.0-r33686b. xpra-6 refers to 6.1.2-r0.

Comparing the debug logs (macbook-pro vs mini): The mini LACKS any 'debug enabled' outputs for osx, and very few (2) for darwin:

```
% grep -i -o 'debug enabled for.*\]' mpro-6.1.2-r0-all-attach.log > mpro-d-enabled2.txt
% grep -i -o 'debug enabled for.*\]' mini-6.1.2-r0-all-attach.log > mini-d-enabled2.txt
% grep -i -n darwin mini-d-enabled2.txt mpro-d-enabled2.txt
mini-d-enabled2.txt:143:debug enabled for ['xpra.platform.darwin.gl_context', 'bindings', 'gtk']
mini-d-enabled2.txt:144:debug enabled for ['xpra.platform.darwin.gl_context', 'opengl']
mpro-d-enabled2.txt:4:debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events']
mpro-d-enabled2.txt:5:debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events', 'workspace']
mpro-d-enabled2.txt:6:debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events', 'mouse']
mpro-d-enabled2.txt:7:debug enabled for ['xpra.platform.darwin.gui', 'osx', 'notify']
mpro-d-enabled2.txt:20:debug enabled for ['xpra.platform.darwin.menu', 'osx', 'tray', 'menu']
mpro-d-enabled2.txt:21:debug enabled for ['xpra.platform.darwin.menu', 'osx', 'menu', 'clipboard']
mpro-d-enabled2.txt:142:debug enabled for ['xpra.platform.darwin.gl_context', 'bindings', 'gtk']
mpro-d-enabled2.txt:143:debug enabled for ['xpra.platform.darwin.gl_context', 'opengl']
mpro-d-enabled2.txt:153:debug enabled for ['xpra.platform.darwin.tray', 'tray', 'osx']
mpro-d-enabled2.txt:164:debug enabled for ['xpra.platform.darwin.clipboard', 'clipboard', 'osx']
% grep -i -n osx mini-d-enabled2.txt
% 
%  nm --version
Apple LLVM version 14.0.0 (clang-1400.0.29.202)
  Optimized build.
  Default target: x86_64-apple-darwin21.6.0
  Host CPU: penryn

llvm-nm, compatible with GNU nm
% arch
i386
% machine
i486
```
Asides/FYI (unrelated to the above mini failures):

Cosmetic?: Both macbook & mini, for xpra-5, debug-logs state: "running on Mac OS X 10.16": but macos numbering went from 10.15 to 11.x, there was no 10.16. (An xpra-build artifact?)

Why do I keep Xpra 5.x around as a client?: Because it can connect to Xpra-3.x servers on centos-7.
My env has XPRA_COLOR_LOG=0, and the debug log briefly starts out no color, but quickly returns to colorized, why?

For Xpra-server on aarch64, with rocky-linux-8.10 (or 8.9): The distribution (repo epel) has: xpra-4.4.6-1.el8.aarch64 (it works).
The xpra repo does not support aarch64, but downloads https://xpra.org/dists/CentOS/8/aarch64/ has centos-8 packages: Can a repo-file be constructed to install from those centos-8 packages on aarch64? Anyone aware of a success story doing so?

[macmini-6.1.2-r0-keyboard-fail.zip](https://github.com/user-attachments/files/17032213/macmini-6.1.2-r0-keyboard-fail.zip)

**Comment by totaam** [comment]
This looks like a duplicate of #4347, please try `-r1` builds.

> The xpra repo does not support aarch64

There are fairly complete builds for `aarch64` in centos stream9: https://xpra.org/dists/CentOS/stream9/aarch64/
The default centos stream repo file should just work: https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/CentOS-Stream/xpra.repo
IIRC, stream8 was having some build issues, looking at the last build log, it barfed with:
```
- Curl error (6): Couldn't resolve host name for http://mirrorlist.centos.org/?release=8-stream&arch=x86_64&repo=AppStream&infra=container [Could not resolve host: mirrorlist.centos.org]
```
The `aarch64` builds take well over 24 hours to run, sometime more.. I don't have the patience.

**Comment by totaam** [comment]
I tagged the wrong ticket, the solution is in #4357: use newer builds.

**Comment by sto6** [comment]
6.1.2-r1: No help, same error. Same dlopen() error, referencing same symbol, consistent across 4.4.x, 5.0.x, 6.1.2.x. Only on one machine (of two).

Took a look at env-vars set by the PythonExecWrapper; to compare between the two machines: values are the same. (Because  "dlopen() ... symbol not found..." had the look of a DYLD_* problem).

Does the .pkg installer selectively install a subset (of files, libraries, dirs...), based on the what it observes about the target host?

Next on my list was: some part of xpra doesn't believe this machine is OSX. Here's a **working** gui:

```
/Applications/Xpra.app/Contents/Macos/Xpra gui --debug=all 2>&1 | head -10 | cat -n
     1  debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events']
     2  debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events', 'workspace']
     3  debug enabled for ['xpra.platform.darwin.gui', 'osx', 'events', 'mouse']
     4  debug enabled for ['xpra.platform.darwin.gui', 'osx', 'notify']
     5  kCGSSessionOnConsoleKey=True
     6  CGSSessionScreenIsLocked=0
     7  debug enabled for ['xpra.gtk.widget', 'gtk', 'util']
     8  debug enabled for ['xpra.gtk.pixbuf', 'gtk', 'util']
     9  debug enabled for ['xpra.scripts.pinentry', 'exec', 'auth']
    10  debug enabled for ['xpra.gtk.dialogs.base_gui_window', 'util']
```

The first lines 1-6 of modes "gui" and "about" (generated by: --debug=all) are **absent** on the failing machine.
Those same six are lines 4-9 of modes "launcher" and "attach", and **absent** on the failing machine.

So "very early" xpra "goes wrong" & (partially) doesn't think the host is OSX?: Any clues what can cause that?
How can I further explore what/why that is happening?

**Comment by totaam** [comment]
> Does the .pkg installer selectively install a subset

No, it just installs more so you get `.xpra` file associations working:
https://github.com/Xpra-org/xpra/blob/master/packaging/MacOS/make-PKG.sh
And the launch agent for shadowing from a non-interactive session, printer backend, etc

> How can I further explore what/why that is happening?

Something is installed on the failing machine which interferes with xpra's environment.
Maybe another python version, cffi, etc

**Comment by sto6** [comment]
Small progress: can make the keyboard almost fully-work, and believe I can explain the early void in OSX-specific debug messages. But the client Xpra menus are still all missing (I failed to mention this symptom earlier: another similarity to #4357), and `--swap-keys=no` does not take effect.

These two patches make the attach work with display,mouse & keyboard, BUT... the `--swap-keys=no` does not take effect; and the client Xpra still has no menus.

These changes I believe are appropriate full-time anyway: It's a waste to "import darwin.gui" when just darwin will do (to specifically provide: `get_OSXApplication`). These changes defer the import of platform.darwin.gui, but ultimately it is required for swap-keys config (part of ClientExtras).

```
% git diff --no-color ~/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py{-0,}
diff --git a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py-0 b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py
index a7acb67..6a58949 100644
--- a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py-0
+++ b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/menu.py
@@ -19,7 +19,8 @@ from xpra.client.gtk3.tray_menu import (
     SHOW_QR,
 )
 from xpra.platform.paths import get_icon
-from xpra.platform.darwin.gui import get_OSXApplication
+## WAS: from xpra.platform.darwin.gui import get_OSXApplication , but gui.py just does: from xpra.platform.darwin import get_OSXApplication
+from xpra.platform.darwin import get_OSXApplication
 from xpra.client.gui import features
 from xpra.log import Logger

% git diff --no-color ~/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/tray.py{-0,}
diff --git a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/tray.py-0 b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/tray.py
index fea31a3..646f421 100644
--- a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/tray.py-0
+++ b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/darwin/tray.py
@@ -26,7 +26,8 @@ class OSXTray(TrayBase):

     def __init__(self, *args):
         super().__init__(*args)
-        from xpra.platform.darwin.gui import get_OSXApplication
+        ## WAS: from xpra.platform.darwin.gui import get_OSXApplication , but gui.py just does: from xpra.platform.darwin import get_OSXApplication
+        from xpra.platform.darwin import get_OSXApplication
         self.macapp = get_OSXApplication()
         assert self.macapp, "cannot use OSX Tray without the native gtkosx_application bindings"
         self.last_attention_request_id = -1
```

Secondly, in `Contents/Resources/lib/python/xpra/platform/__init__.py` is:
```
def platform_import(where: dict, pm="", required=False, *imports)
```
which does an import, catches an exception, and conditionally re-raises it IFF required==True (else just silently returns).

I believe this is the source of the 'early void' in the debug-log of some 'debug enabled for' OSX-specific messages, when the dlopen() Quartz/CoreGraphics/_callbacks.so error occurs. i.e. No partial failure to recognize machine is darwin & OSX.

The platform/darwin/gui.py consistently will die there (in from Quartz.CoreGraphics import), which is before
getting to the: `debug enabled for ['xpra.platform.darwin.gui'`.
I think darwin.gui gets imported early, which on working-machine generates the early xpra.platform.darwin.gui debug enabled; but on the failing-machine the dlopen() exception happens, aborting the import, but exception is silently ignored. Then it's imported again later (for attach mode), without trap&hide of the exception.

The main event: the dlopen() Quartz/CoreGraphics/_callbacks.so error remains & is unexplained; but with no ancillary mysteries.

**Comment by totaam** [comment]
> It's a waste to "import darwin.gui"

Yes, good catch, applied in 04baa0522821c7f8d8474a352a27f98b4eda159b

> catches an exception

Which exception did you see here? This one?
`ImportError: dlopen(/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/lib-dynload/Quartz/CoreGraphics/_callbacks.so, 0x0002): symbol not found in flat namespace (_CGDisplayRegisterReconfigurationCallback)`
According to [`CGDisplayRegisterReconfigurationCallback`](https://developer.apple.com/documentation/coregraphics/1455336-cgdisplayregisterreconfiguration), this functions is available in macOS 10.3+

> `symbol not found in flat namespace`

Maybe pyobjc is not linking properly.
Running `otool` on `_callbacks.so` should give us more info.

> The platform/darwin/gui.py consistently will die there (in from Quartz.CoreGraphics import)

Still points to something being different on that system.

**Comment by sto6** [comment]
Sorry, I'll be greedy & ask: Outside of the clientExtras, is there a more fundamental (much earlier) place in the code where I can just hardwire behavior as swap-keys=no from the start? Isn't there sort-of "more work" (more code) being turned ON (enabled) in the keyboard for performing swap-keys=yes; so it should be kind of more basic/natural to flip the design so it "fails to Off": as-if swap-keys=no (instead of yes)? ;)

Yes, this main exception occurs twice (different processes), but both normally suppressed by the `platform_import(required=False)` which I tweaked to log also the survived exceptions:
```
ImportError: dlopen(/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/lib-dynload/Quartz/CoreGraphics/_callbacks.so, 0x0002): symbol not found in flat namespace (_CGDisplayRegisterReconfigurationCallback)
```
followed by a third exception (suspect this is Ok/minor?):
```
2024-09-24 00:42:32,010 maximum packet size set to 16777216
2024-09-24 00:42:32,011 debug enabled for ['xpra.platform.gui', 'screen']
2024-09-24 00:42:32,016 get_icc_info()
Traceback (most recent call last):
  File "/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/xpra/platform/gui.py", line 164, in get_pillow_icc_info
    from PIL import ImageCms
  File "PIL/ImageCms.pyc", line 395, in <module>
  File "PIL/_util.pyc", line 23, in __getattr__
  File "PIL/ImageCms.pyc", line 33, in <module>
ImportError: cannot import name '_imagingcms' from 'PIL' (/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/PIL/__init__.pyc)
2024-09-24 00:42:32,017 Warning: cannot query ICC profiles:
2024-09-24 00:42:32,018  cannot import name '_imagingcms' from 'PIL' (/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python/PIL/__init__.pyc)
```
RE: otool, I don't know what options are useful. I  believe most or all of this, including esp. `otool -L` is consistent on both machines (failing mini & working macbook-pro):
```
% nm /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so | g CGDisplayRegisterReconfigurationCallback
                 U _CGDisplayRegisterReconfigurationCallback
0000000000004b00 t _m_CGDisplayRegisterReconfigurationCallback
% otool -I -v /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so | g -C 4 CGDisplayRegisterReconfigurationCallback
0x00000000000071a4   330 _CGDataConsumerRelease
0x00000000000071aa   331 _CGDataProviderCreateSequential
0x00000000000071b0   332 _CGDataProviderCreateWithData
0x00000000000071b6   333 _CGDataProviderRelease
0x00000000000071bc   334 _CGDisplayRegisterReconfigurationCallback
0x00000000000071c2   335 _CGDisplayRemoveReconfigurationCallback
0x00000000000071c8   336 _CGEventTapCreate
0x00000000000071ce   337 _CGEventTapCreateForPSN
0x00000000000071d4   338 _CGFunctionCreate
--
0x0000000000008050   330 _CGDataConsumerRelease
0x0000000000008058   331 _CGDataProviderCreateSequential
0x0000000000008060   332 _CGDataProviderCreateWithData
0x0000000000008068   333 _CGDataProviderRelease
0x0000000000008070   334 _CGDisplayRegisterReconfigurationCallback
0x0000000000008078   335 _CGDisplayRemoveReconfigurationCallback
0x0000000000008080   336 _CGEventTapCreate
0x0000000000008088   337 _CGEventTapCreateForPSN
0x0000000000008090   338 _CGFunctionCreate
% otool -l /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so | g /
/Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so:
         name /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz (offset 24)
         name /usr/lib/libSystem.B.dylib (offset 24)
         name /usr/lib/libobjc.A.dylib (offset 24)
% otool -L /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so
/Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so:
        /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
% otool -dyld_info /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so
/Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so:
bind information:
segment section address value              type        addend   dylib          symbol
__DATA  __got   0x8008                     pointer     0x0      flat-namespace _OBJC_EHTYPE_$_NSException
__DATA  __got   0x8010                     pointer     0x0      flat-namespace _PyExc_RuntimeError
__DATA  __got   0x8018                     pointer     0x0      flat-namespace _PyExc_TypeError
__DATA  __got   0x8020                     pointer     0x0      flat-namespace _PyExc_ValueError
__DATA  __got   0x8028                     pointer     0x0      flat-namespace __Py_NoneStruct
__DATA  __got   0x8038                     pointer     0x0      libSystem      dyld_stub_binder
__DATA  __got   0x8030                     pointer     0x0      libobjc        ___objc_personality_v0
% otool -dyld_opcodes /Applications/Xpra.app/Contents/Resources//lib/python3.11/lib-dynload/Quartz/CoreGraphics/_callbacks.so | g -C 4 CGDisplayRegisterReconfigurationCallback
    29 0x0000c18f 0x90 BIND_OPCODE_DO_BIND
    30 0x0000c190 0x00 BIND_OPCODE_DONE
    31 0x0000c191 0x71 BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB(1, 0x70)
    32 0x0000c193 0x3e BIND_OPCODE_SET_DYLIB_SPECIAL_IMM(14)
    33 0x0000c194 0x40 BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM(0, _CGDisplayRegisterReconfigurationCallback)
    34 0x0000c1bf 0x90 BIND_OPCODE_DO_BIND
    35 0x0000c1c0 0x00 BIND_OPCODE_DONE
    36 0x0000c1c1 0x71 BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB(1, 0x78)
    37 0x0000c1c3 0x3e BIND_OPCODE_SET_DYLIB_SPECIAL_IMM(14)
```

**Comment by totaam** [comment]
> where I can just hardwire behavior as swap-keys=no from the start?

I don't understand what that means or why you would want to do that as opposed to using command line options.

> so it should be kind of more basic/natural to flip the design

`swap_keys` is just a boolean toggle

> followed by a third exception... `ImportError: cannot import name '_imagingcms' from 'PIL'`

I will reduce the log verbosity for this.

As per `otool -L`, I believe `_CGDisplayRegisterReconfigurationCallback` is meant to be provided by `/System/Library/Frameworks/Quartz.framework/Versions/A/Quartz`.

**Comment by sto6** [comment]
Yes, and I plaster swap-keys=no everywhere: `~/.xpra/xpra.conf`, attach command-line options, target-server-specific .xpra config-files. But while the dlopen() exception is there, clientExtras does not run, and swap-keys=no does not take effect, so I'm looking for an alternative way to hardwire/achieve it (editing the code: defeat whatever remains that is still doing the KeyCode filtering as-if swap-keys=yes).

Prob. I'm being silly, and/or don't understand why the default of swap-keys=yes was chosen, or may be considered the more minimalist state. Hypothetically if two versions were created, each hardwired for "yes" vs "no" swap respectively, and also aggressively stripped of any code needed to handle the opposite case, would the no-version now have "less code" (be smaller & more minimal than "yes"), because less "KeyCodes filtering" (or translating, whatever) is needed for no swap case?

**Comment by totaam** [comment]
The `Quartz` pyobjc bridge is essential for running xpra on macos, too many functions rely on it.
There's no way we're going to change fundamental pieces of code.
(this also explains why you're hitting the `ImageCms` missing warning - this is only used when the macos native calls can't be loaded)

The correct solution is to figure out what is different on this system and ensure that pyobc runs on it.

**Comment by sto6** [comment]
Yes, I expect I'll have to move that (proper RCCA) to an OCLP issue.

fyi: This gets me to swap-keys=no (i.e. hardwiring the default to off, so unreachable-clientExtras isn't needed to turn it off):

```
% git diff --no-color ~/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python3.11/xpra/platform/darwin/keyboard.py{-0,}
diff --git a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python3.11/xpra/platform/darwin/keyboard.py-0 b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python3.11/xpra/platform/darwin/keyboard.py
index 829c552..11b877b 100644
--- a/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python3.11/xpra/platform/darwin/keyboard.py-0
+++ b/Users/sto/ap/Xpra-6.1.2-r0.app/Contents/Resources/lib/python3.11/xpra/platform/darwin/keyboard.py
@@ -78,7 +78,8 @@ class Keyboard(KeyboardBase):

     def init_vars(self) -> None:
         super().init_vars()
-        self.swap_keys = True
+        ## was: self.swap_keys = True
+        self.swap_keys = False
         self.meta_modifier = ""
         self.control_modifier = "control"
         self.super_modifier = ""

```
Still no client menus. The initial-desktop size is often wrong (offset from top), but the window title-bar full-screen button (toggled twice) fixes that.

**Comment by totaam** [comment]
I've just realized that this is most definitely due to an unsupported OS issue: `mac-mini (2010)`
According to [What is the latest OS you can run on a Mac Mini from 2010?](https://discussions.apple.com/thread/252629401?sortBy=rank): _The Mid 2010 Mac Mini can run up to macOS 10.13 High Sierra_
But you said `Client OS: macos Monterey 12.7.6 (Intel)` - which can't be right.

MacOS 12 is required: https://github.com/Xpra-org/xpra/wiki/Platforms#-macos
