### ISSUE TITLE
Forgot a $ before the {QUIC_AUTH} variable.

### ISSUE THREAD

**Issue by MichaKersloot** [Xpra-org/xpra#4370]
https://github.com/Xpra-org/xpra/blame/d16915f39faa5012c848e5312de372a834fb9591/fs/lib/systemd/system/xpra.service#L14

**Comment by totaam** [comment]
Thanks, applied in 94dc7e93c529aaf6e16485fb058cb4dce2852e76

FYI: from github, you can just edit the file in place to create a PR.
