### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\.' during installation

### ISSUE THREAD

**Issue by GodAndEmperor** [Xpra-org/xpra#4379]
**Describe the bug**
During installation (> sudo apt install xpra) under kubuntu, there is a warning about an "invalid escape sequence". See 
[install_log.txt](https://github.com/user-attachments/files/17302518/install_log.txt) for complete warning and details (e.g. installed package versions)

**To Reproduce**
1. server command
n/a
2. client command
n/a
3. specific action to trigger the bug
sudo apt install xpra

**System Information (please complete the following information):**
 [xpra_bug-report.zip](https://github.com/user-attachments/files/17302486/xpra_bug-report.zip)

**Additional context**

**Comment by totaam** [comment]
TIL:
```
Setting up xpra (3.1.5+dfsg1-0.2ubuntu1) ...
(...)
-----
/usr/lib/python3/dist-packages/xpra/scripts/main.py:2758: SyntaxWarning: invalid escape sequence '\.'
  alphanum = lambda key: [convert(c) for c in re.split('([-+]?[0-9]*\.?[0-9]*)', key)]
```

This is not a supported version and is not provided by xpra.org

This version [is dangerous](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages) and should not be used.
