### ISSUE TITLE
Missing arm64 package

### ISSUE THREAD

**Issue by hampoelz** [Xpra-org/xpra#4388]
According to the [xpra.sources](https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/oracular/xpra.sources) file, there are also arm64 builds in the repository. (I've already used them several times in the past) But now `apt update` says something else: **Notice: Skip acquire of configured file 'main/binary-arm64/Packages' as repository 'https://xpra.org oracular InRelease' doesn't support architecture 'arm64'**.

**Comment by totaam** [comment]
Thanks for the report.

I don't think we have ever had oracular arm64 builds - not even beta builds.
Maybe you upgraded from a previous Ubuntu release?

The 6.2 packages are coming, it just takes time, a lot of time: building arm64 packages is running emulated via qemu, it takes days.

**Comment by hampoelz** [comment]
Oh my bad, I was using the arm build with Debian. But somehow I thought if it already worked on Debian in the past and the source.list for Ubuntu Oracular states that it supports arm64, why wouldn't it work now.

So are there arm64 builds planned for Ubuntu or should I build it myself for now / switch to Debian? _(I use it particularly for a container, so it shouldn't be too much work to switch to Debian)_

**Comment by totaam** [comment]
> So are there arm64 builds planned for Oracular

Like I said above: _The 6.2 packages are coming, it just takes time, a lot of time.._

**Comment by totaam** [comment]
And if you do switch to another distro, please make it not a Debian based one:
https://github.com/Xpra-org/xpra/issues/4389#issuecomment-2412698773

**Comment by totaam** [comment]
It looks like it's going to take longer than expected - maybe the oracular arm64 upstream repositories aren't fully populated yet?
```
dpkg-source: warning: xpra-6.2.0/debian/changelog(l25): found end of file where expected more change data or trailer
dpkg-source: info: using options from xpra-6.2.0/debian/source/options: --compression=xz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying pam.patch
dpkg-source: info: applying service-config.patch
dpkg-checkbuilddeps: error: Unmet build dependencies: xserver-xorg-video-dummy libxcomposite-dev libxdamage-dev libxtst-dev libxres-dev libavif-dev libyuv-dev libvpx-dev libx264-dev libopenh264-dev libwebp-dev libturbojpeg-dev libspng-dev libgtk-3-dev python3-cairo-dev python-gi-dev dh-python libsystemd-dev libpam0g-dev libproc2-dev | libprocps-dev liblz4-dev libxxhash-dev libqrencode-dev pandoc
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1184:
dpkg-buildpackage -us -uc -ui -b failed
```

In any case, I don't have the hardware or the time to look into this.

**Comment by totaam** [comment]
`v6.2.1` included `arm64` packages for oracular: https://xpra.org/dists/oracular/main/binary-arm64/

**Comment by totaam** [comment]
Just how much time does it take to build arm packages? Here are some samples for the 6.2.4 release builds:
* `python3.13-cython-3.0.12-1.fc40.aarch64.rpm` took 23 hours
* `python3.13-numpy-1.26.4-1.fc40.aarch64.rpm` took 15 hours
* `python3.13-xpra-6.2.4-10.r0.fc40.aarch64.rpm` took 6 hours
* etc

Which means that the Fedora 40 arm64 builds alone took over 2.5 days.
That's one architecture from one distribution variant, of which we have many.
