### ISSUE TITLE
Server cannot be stopped from command line if client is not installed

### ISSUE THREAD

**Issue by Oblomov** [Xpra-org/xpra#4391]
**Describe the bug**
```
user@server:~$ xpra stop :100
xpra main error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 141, in main
    return run_mode(script_file, cmdline, error_handler, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 515, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, full_mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 618, in do_run_mode
    return run_stopexit(mode, error_cb, options, args, cmdline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/scripts/main.py", line 3351, in run_stopexit
    from xpra.client.base.command import StopXpraClient
ModuleNotFoundError: No module named 'xpra.client
```

**To Reproduce**
1. start a server on a machine where `xpra-server` is installed, but `xpra-client` is not.
2. try to call `xpra stop :number` where `:number` is the X server number for XPRA

**System Information (please complete the following information):**
 - Server OS: Debian trixie
 - Client OS: n/a
 - Xpra Server Version: xpra v6.2.0-r36737 (g3562a26650) beta
 - Xpra Client Version: n/a

**Additional context**
I would expect the `stop` command to work without calling into the client code, but this might be a misconception of mine.

**Comment by totaam** [comment]
That's as expected.
`xpra stop` is a client.
If you don't want to install the (small) `xpra-client` package, you can use `kill`.
