### ISSUE TITLE
Click Picture -> Encoding -> Automatic will disable quality menu

### ISSUE THREAD

**Issue by GUAN-Xihao** [Xpra-org/xpra#4398]
**Describe the bug**
![Here](https://github.com/user-attachments/assets/981b7fc2-26f6-402b-a780-8af773a6a941)

**To Reproduce**
1. Star Xpra, you will find encoding is automatic and quality menu avaiable.
2. Now, click automatic encoding. Then quality menu disabled. As above screenshot shows.

**System Information (please complete the following information):**
 - Client OS: Windows 11
 - Xpra Client Version 6.2.0

**Comment by totaam** [comment]
Thanks for the bug report, this is fixed in 2c9301cb0c6afb87efafe68081f6fc2271a79194.

There are `6.3-r36803` beta MS Windows builds with this fix here: https://xpra.org/beta/windows/
