### ISSUE TITLE
Repo installation script doesn't recognize this distro -  KDE Neon - Ubuntu 24.04,Noble Numbat 

### ISSUE THREAD

**Issue by vonHabsi** [Xpra-org/xpra#4405]
**Describe the bug**
The script to configure the apt repo fails on KDE Neon - Ubuntu 24.04, Noble Numbat Linux distribution

**To Reproduce**

Download the xpra repo, switch to the xpra directory and run the command:

 `./setup.py install-repo`

The script fails with the error message:

`ValueError: unsupported distribution ('Neon', '24.04', 'noble')` 

**System Information (please complete the following information):**
 - Server OS: [KDE Neon, Noble Numbat Plasma 6.2]
 - Client OS: N/A
 - Xpra Server Version: N/A
 - Xpra Client Version: N/A

**Additional context**
The setup script probably hasn't been adapted to test for the distros identification strings.

**Comment by totaam** [comment]
Hmm. I'm not sure how we're supposed to identify this as `Ubuntu`.
Any ideas?

**Comment by vonHabsi** [comment]
TBH I'm not familiar with how the distros identify themselves in some kind of universally recognized manner.

I will report it one of their forums and get back to you.

Someone might read the script and offer some suggestions.

**Comment by totaam** [comment]
ad0433c0068a21c80cf5a9d7ac2f6f1980d302e6 should work for all supported DEB variants.

**Comment by vonHabsi** [comment]
The `./setup.py install-repo` command requires a number of Python packages to be installed to run properly and took me some time to discover them and them run on an older version of Ubuntu to create the `xpra.sources`  and the signing key  files.

I think asking users to insert their Debian  or Ubuntu variant in this file will make things easier.

```
Types: deb
URIs: https://xpra.org
Suites: {debian_variant}
Components: main
Signed-By: /usr/share/keyrings/xpra.asc
Architectures: amd64 arm64

```
In relation to https://github.com/orgs/Xpra-org/discussions/4406 I replaced with `{debian_variant}` with `bullseye` and now `apt-cache policy xpra` displays the version `5.0.x` packages from the xpra.org repository.

I will upgrade to it and hopefully that will fix the problem.

There used to be a form to generate the necessary `xpra.list` file by adding your distro version at the `xpra.org` or `winswitch.org` website but it isn't there now.

Bringing it back might help others a lot.

**Comment by totaam** [comment]
> The ./setup.py install-repo command requires a number of Python packages

Should be just `setuptools` - anything else is just noise or maybe needs to be moved around so it can be skipped.

> and the signing key files

What key files?

> I think asking users to insert their Debian or Ubuntu variant in this file will make things easier.

I much prefer one command that does it for them.
Experience tells me that users will type it wrong and / or think they can second guess the value.

**Comment by vonHabsi** [comment]
>> `./setup.py install-repo` command requires a number of Python packages

> Should be just `setuptools` - anything else is just noise or maybe needs to be moved around so it can be skipped.

Yes, the amount of output generated by its failure is a lot.

I will try it again on some new installs and offer a pull request to enhance the documentation around that if it will help.

> What key files?

Just one file actually 

`Signed-By: /usr/share/keyrings/xpra.asc`

in the `xpra.sources` file

**Comment by totaam** [comment]
> I will try it again on some new installs and offer a pull request to enhance the documentation around that if it will help.

That would be great!

> Just one file actually

Ah, yes!
It can be downloaded via https.
