### ISSUE TITLE
Start menu grayed out on Arch

### ISSUE THREAD

**Issue by nentibusarchitectura** [Xpra-org/xpra#4411]
**Describe the bug**
Start menu is grayed out

**To Reproduce**
Running XPRA on Arch renders the start menu gray (I suppose is empty)

**System Information (please complete the following information):**
 - Server OS: Arch (updated Nov 3)
 - Client OS: Arch (updated Nov 3)
 - Xpra Server Version 6.2
 - Xpra Client Version 5.0.10

How are the contents of the start menu generated? I've noticed they vary a lot from distro to distro.

While it would be nice the menu works on its own I'm not bothered to write entries manually for it, is this possible?

Can I create entries manually by editing files somewhere?

(I understand Arch is not supported, not too worried about it)

**Comment by totaam** [comment]
> How are the contents of the start menu generated?

They are loaded using `pyxdg`.

> Server OS: Arch

This is not a package from xpra.org, so my guess is that the metadata is missing the `pyxdg` dependency or that the menus are failing to load due to a system (mis)configuration.

You can run your server with `-d menu` to see more details.

> Can I create entries manually by editing files somewhere?

Yes, see: [Desktop Menu Specification](https://specifications.freedesktop.org/menu-spec/1.0/)

**Comment by nentibusarchitectura** [comment]
>my guess is that the metadata is missing the pyxdg dependency

Bingo! Thank you very much, the menu is working fine now, need to figure out why everything is in a single category, but that is a separate issue I'm not too concerned about.

Yes, I did build the packages myself, moved from Ubuntu to Arch and I have mixed and matched the server/client versions that work the best for my set-up.

> Yes, see: [Desktop Menu Specification](https://specifications.freedesktop.org/menu-spec/1.0/)

Ah excellent, thank you.

**Comment by totaam** [comment]
> Yes, I did build the packages myself

As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs, this key information should be included in all bug reports.

**Comment by nentibusarchitectura** [comment]
> As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs, this key information should be included in all bug reports.

Apologies for that, wasn't my intention to raise this as a bug, as I suspected it was related to my particular set-up.
