### ISSUE TITLE
xpra breaks with i3

### ISSUE THREAD

**Issue by CorbinWunderlich** [Xpra-org/xpra#4415]
**Describe the bug**
When trying to use the --use-display flag with xpra to take over a gpu-accelerated display, if that is running i3, the display will crash back to the display manager, and if I wrap i3 in say, xfce, it just becomes a seamless session with all the windows on that display. I tried this with plasma, and it worked flawlessly. I am using the html5 client.

**To Reproduce**
1. Run i3 on a GPU-acclerated display
2. run xpra --use-display [display]
3. connect via html5 client or otherwise

**System Information (please complete the following information):**
 - Server OS: NixOS unstable (24.11 Vicuna)
 - Client OS: Firefox
 - Xpra Server Version 6.1.3
 - Xpra Client Version 16.2 html5

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by CorbinWunderlich** [comment]
Sorry, I didn't realize that I wasn't using start-desktop.

**Comment by totaam** [comment]
In seamless mode, there can only be one display manager: `xpra` or `i3`.

If `i3` claims the `_NEW_WM_CM_S0`  selection, then xpra should have printed the message:
https://github.com/Xpra-org/xpra/blob/0dfe55ed50404565e53d4fab4a47ea4d5295c4ec/xpra/x11/gtk/wm_check.py#L111-L115

Did it?

> `xpra --use-display [display]`

This is not a valid command.

> Xpra Server Version 6.1.3

This is out of date.

**Comment by CorbinWunderlich** [comment]
> In seamless mode, there can only be one display manager: `xpra` or `i3`.
> 
> If `i3` claims the `_NEW_WM_CM_S0` selection, then xpra should have printed the message:
> 
> https://github.com/Xpra-org/xpra/blob/0dfe55ed50404565e53d4fab4a47ea4d5295c4ec/xpra/x11/gtk/wm_check.py#L111-L115
> 
> Did it?
> 
> > `xpra --use-display [display]`
> 
> This is not a valid command.
> 
> > Xpra Server Version 6.1.3
> 
> This is out of date.

Hm. It's working great for me now. Using start-desktop instead of start allows me to use my own wm.

**Comment by totaam** [comment]
> Using start-desktop ...

Yes, that's [desktop mode](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Desktop.md). `xpra start` is [seamless mode](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Seamless.md).

The more modern syntax is :`xpra desktop` or `xpra seamless` instead of `xpra start-whatever`

**Comment by CorbinWunderlich** [comment]
> > Using start-desktop ...
> 
> Yes, that's [desktop mode](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Desktop.md). `xpra start` is [seamless mode](https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Seamless.md).
> 
> The more modern syntax is :`xpra desktop` or `xpra seamless` instead of `xpra start-whatever`

Alright. No complains, so far the best remote desktop solution I've tried. html5 client has some audio latency but it seems to be a known issue and it isn't a necessity. Thanks for creating this great software!
