### ISSUE TITLE
`run_scaled` fails to start because of ambiguous xpra options

### ISSUE THREAD

**Issue by UrsMetz** [Xpra-org/xpra#4417]
**Describe the bug**

On Fedora 40 I see the following issue (with the version v5.0.10 from the Fedora repo):
```
xpra initialization error:
 ambiguous option: --video (--video-decorders, --video-encoders, --video-scaling?)
``` 

**To Reproduce**
I'm trying to a command (in my case `wine` but the error occurs with any command e.g. firefox) with xpra using
```
/usr/bin/run_scaled wine ...
```

**System Information (please complete the following information):**
 - Server OS: Fedora 40
 - Client OS: Fedora 40 (server and client are the same machine)
 - Xpra Server Version 5.0.10
 - Xpra Client Version 5.0.10

**Additional context**

With an older version of xpra/run_scaled it worked. I'm not 100% sure which one but I think it also was a 5.* version that worked.

When I modify the `run_scaled` python script by removing `--video=no` form the `DEFAULT_XPRA_ARGS` array it works again.

**Comment by totaam** [comment]
Sorry about that, d7643c8252bbe7d7d5053323d23d70f1cd5b1706 broke `run_scaled` in v5.0.9
(it isn't broken when used with newer v6 versions)

75d25ef615b8782f221eeacb3d424f6aabbb9b93 fixes that and will be included in the next release.
Meanwhile you can easily just replace `/usr/bin/run_scaled` with [this version](https://raw.githubusercontent.com/Xpra-org/xpra/refs/heads/v5.x/fs/bin/run_scaled)
