### ISSUE TITLE
xpra gui start&attach not working

### ISSUE THREAD

**Issue by jmakov** [Xpra-org/xpra#4426]
**Describe the bug**
Using xpra gui -> start -> remote (seamless session, SSH) -> start & attach, I'd expect a xpra process will be started on the remote server and I could start programs via the tray icon -> applications. Instead I'm returned to the same "start xpra session" window. I do see some new xpra processes on the remote server, but even clicking in the "xpra" gui window on "browse", I don't see any sessions. 
If I enter a command in "start xpra session" window e.g. `firefox`, then Firefox is started and I see the tray icon. But what I'd like is just to get to the point where the tray icon is available so I can launch new windows.

When using "firefox" in the command, the scaling is off and no audio.

Server OS: Ubuntu 24.10
Client OS: Manjaro 24.1.2
server xpra version: xpra v6.2.1-r0
client xpra version: xpra v6.0-r0
no changes to xpra:
xpra client:
<details>
add-printer-options            = '-u allow:$USER', '-E', '-o printer-is-shared=false'
attach                         = auto
audio                          = True
audio-source                   = ''
auth                           = 
auto-refresh-delay             = 0.15
av-sync                        = True
bandwidth-detection            = False
bandwidth-limit                = 'auto'
bell                           = True
bind                           = 'auto'
bind-quic                      = 
bind-rfb                       = 
bind-ssh                       = 
bind-ssl                       = 
bind-tcp                       = 
bind-vsock                     = 
bind-ws                        = 
bind-wss                       = 
border                         = 'auto,5:off'
challenge-handlers             = 'all'
chdir                          = ''
client-socket-dirs             = '$XDG_RUNTIME_DIR/xpra/clients'
clipboard                      = 'yes'
clipboard-direction            = 'both'
clipboard-filter-file           = ''
compression_level              = 1
compressors                    = 'none', 'lz4', 'brotli'
csc-modules                    = 'all'
cursors                        = True
daemon                         = True
dbus-control                   = True
dbus-launch                    = 'dbus-launch --sh-syntax --close-stderr'
debug                          = ''
delay-tray                     = False
desktop-fullscreen             = False
desktop-scaling                = 'on'
display                        = ''
displayfd                      = 0
download-path                  = '~/Downloads'
dpi                            = 0
encoding                       = 'auto'
encodings                      = 'h264', 'vp9', 'vp8', 'mpeg4', 'mpeg4+mp4', 'h264+mp4', 'vp8+webm', 'vp9+webm', 'png', 'png/P', 'png/L', 'webp', 'avif', 'rgb', 'rgb24', 'rgb32', 'jpeg', 'jpega', 'h265', 'av1', 'scroll', 'grayscale', 'stream'
encryption                     = ''
encryption-keyfile             = ''
env                   (used)   = '#silence some AT-SPI and atk-bridge warnings:', 'NO_AT_BRIDGE=1'  <class 'list'>
env                  (default) = '#avoid Ubuntu's global menu, which is a mess and cannot be forwarded:', 'UBUNTU_MENUPROXY=', 'QT_X11_NO_NATIVE_MENUBAR=1', '#fix for MainSoft's MainWin buggy window management:', 'MWNOCAPTURE=true', 'MWNO_RIT=true', 'MWWM=allwm', '#force GTK3 applications to use X11 so we can intercept them:', 'GDK_BACKEND=x11', '#force Qt applications to use X11 so we can intercept them:', 'QT_QPA_PLATFORM=xcb', '#disable Qt scaling:QT_AUTO_SCREEN_SET_FACTOR=0', 'QT_SCALE_FACTOR=1', '#overlay scrollbars complicate things:GTK_OVERLAY_SCROLLING=0', '#some versions of GTK3 honour this option, sadly not all:', 'GTK_CSD=0'  <class 'list'>
exec-wrapper                   = ''
exit-ssh                       = True
exit-with-children             = False
exit-with-client               = False
exit-with-windows              = False
file-size-limit                = '1G'
file-transfer                  = 'auto'
forward-xdg-open               = auto
gid                            = 1001
headerbar                      = 'auto'
html                           = 'auto'
http-scripts                   = 'all'
idle-timeout                   = 0
input-devices                  = 'auto'
input-method                   = 'auto'
key-shortcut                   = 'Control+Menu:toggle_keyboard_grab', 'Shift+Menu:toggle_pointer_grab', 'Shift+F11:toggle_fullscreen', '#+F1:show_menu', '#+F2:show_start_new_command', '#+F3:show_bug_report', '#+F4:quit', '#+F5:show_window_info', '#+F6:show_shortcuts', '#+F7:show_docs', '#+F8:toggle_keyboard_grab', '#+F9:toggle_pointer_grab', '#+F10:magic_key', '#+F11:show_session_info', '#+F12:toggle_debug', '#+plus:scaleup', '#+minus:scaledown', '#+underscore:scaledown', '#+KP_Add:scaleup', '#+KP_Subtract:scaledown', '#+KP_Multiply:scalereset', '#+bar:scalereset', '#+question:scalingoff'
keyboard-layout                = ''
keyboard-layouts               = '[]'
keyboard-options               = ''
keyboard-raw                   = False
keyboard-sync                  = True
keyboard-variant               = ''
keyboard-variants              = '[]'
local-clipboard                = 'CLIPBOARD'
lock                           = auto
log-dir                        = 'auto'
log-file                       = 'server.log'
lpadmin                        = '/usr/sbin/lpadmin'
lpinfo                         = '/usr/sbin/lpinfo'
max-size                       = ''
mdns                           = True
microphone                     = 'off'
microphone-codec               = 
min-port                       = 1024
min-quality                    = 1
min-size                       = ''
min-speed                      = 1
minimal                        = False
mmap                           = 'yes'
mmap-group                     = 'auto'
modal-windows                  = False
mousewheel                     = 'on'
notifications                  = True
open-command                   = '/usr/bin/xdg-open'
open-files                     = 'auto'
open-url                       = 'auto'
opengl                         = 'probe'
packet-encoders                = 'rencodeplus'
password                       = ''
password-file                  = 
pdf-printer           (used)   = ''                                <class 'str'>
pdf-printer          (default) = '/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd'  <class 'str'>
pidfile                        = '${XPRA_SESSION_DIR}/server.pid'
pings                          = 5
pixel-depth                    = 0
postscript-printer    (used)   = ''                                <class 'str'>
postscript-printer   (default) = 'drv:///sample.drv/generic.ppd'   <class 'str'>
printing                       = 'yes'
proxy-start-sessions           = True
proxy-video-encoders           = 'none'
pulseaudio                     = auto
pulseaudio-command             = 'pulseaudio --start -n --daemonize=false --system=false --exit-idle-time=-1 --load=module-suspend-on-idle '--load=module-null-sink sink_name=Xpra-Speaker sink_properties=device.description="Xpra\ Speaker"' '--load=module-null-sink sink_name=Xpra-Microphone sink_properties=device.description="Xpra\ Microphone"' '--load=module-remap-source source_name=Xpra-Mic-Source source_properties=device.description="Xpra\ Mic\ Source" master=Xpra-Microphone.monitor channels=1' '--load=module-native-protocol-unix socket=$XPRA_PULSE_SERVER' '--load=module-dbus-protocol' '--load=module-x11-publish' --log-level=2 --log-target=stderr --enable-memfd=no'
pulseaudio-configure-commands           = 'pactl set-default-sink Xpra-Speaker', 'pactl set-default-source Xpra-Mic-Source'
quality                        = 0
quic-auth                      = 
readonly                       = False
reconnect                      = True
refresh-rate                   = 'auto'
remote-clipboard               = 'CLIPBOARD'
remote-logging                 = 'both'
remote-xpra                    = 'xpra', '$XDG_RUNTIME_DIR/xpra/run-xpra', '/usr/local/bin/xpra', '~/.xpra/run-xpra', 'Xpra_cmd.exe'
resize-display                 = 'yes'
rfb-auth                       = 
rfb-upgrade                    = 5
server-idle-timeout            = 0
session-name                   = ''
sessions-dir                   = '$XDG_RUNTIME_DIR/xpra'
sharing                        = auto
shortcut-modifiers             = 'auto'
socket-dir                     = ''
socket-dirs           (used)   = '/run/user/$UID/xpra', '/run/xpra', '~/.xpra'  <class 'list'>
socket-dirs          (default) = '$XDG_RUNTIME_DIR/xpra', '/run/xpra', '~/.xpra'  <class 'list'>
socket-permissions             = '600'
source                         = '/etc/profile'
source-start                   = 
speaker                        = 'on'
speaker-codec                  = 
speed                          = 0
splash                         = auto
ssh                            = 'auto'
ssh-auth                       = 
ssh-upgrade                    = True
ssl                            = 'auto'
ssl-auth                       = 
ssl-ca-certs                   = 'default'
ssl-ca-data                    = ''
ssl-cert                       = ''
ssl-check-hostname             = True
ssl-ciphers                    = 'DEFAULT'
ssl-client-verify-mode           = 'optional'
ssl-key                        = ''
ssl-key-password               = ''
ssl-options                    = 'ALL,NO_COMPRESSION'
ssl-protocol                   = 'TLS'
ssl-server-hostname            = ''
ssl-server-verify-mode           = 'required'
ssl-upgrade                    = True
ssl-verify-flags               = 'X509_STRICT'
start                          = 
start-after-connect            = 
start-child                    = 
start-child-after-connect           = 
start-child-late               = 
start-child-on-connect           = 
start-child-on-last-client-exit           = 
start-env             (used)   = '#avoid Ubuntu's global menu, which is a mess and cannot be forwarded:', 'UBUNTU_MENUPROXY=', 'QT_X11_NO_NATIVE_MENUBAR=1', '#fix for MainSoft's MainWin buggy window management:', 'MWNOCAPTURE=true', 'MWNO_RIT=true', 'MWWM=allwm', '#force GTK3 applications to use X11 so we can intercept them:', 'GDK_BACKEND=x11', '#force Qt applications to use X11 so we can intercept them:', 'QT_QPA_PLATFORM=xcb', '#disable Qt scaling:QT_AUTO_SCREEN_SET_FACTOR=0', 'QT_SCALE_FACTOR=1', '#overlay scrollbars complicate things:GTK_OVERLAY_SCROLLING=0', '#some versions of GTK3 honour this option, sadly not all:', 'GTK_CSD=0'  <class 'list'>
start-env            (default) = '#silence some AT-SPI and atk-bridge warnings:', 'NO_AT_BRIDGE=1'  <class 'list'>
start-late                     = 
start-new-commands             = True
start-on-connect               = 
start-on-last-client-exit           = 
start-via-proxy                = False
sync-xvfb             (used)   = 0                                 <class 'int'>
sync-xvfb            (default) =                                   <class 'NoneType'>
system-proxy-socket            = '/run/xpra/system'
system-tray                    = True
systemd-run                    = 'auto'
systemd-run-args               = ''
tcp-auth                       = 
tcp-encryption                 = ''
tcp-encryption-keyfile           = ''
terminate-children             = False
title                          = '@title@ on @hostinfo@'
tray                           = True
tray-icon                      = ''
uid                            = 1000
use-display                    = 'auto'
username                       = ''
video                          = True
video-decoders                 = 'all'
video-encoders                 = 'all'
video-scaling                  = 'auto'
vsock-auth                     = 
webcam                         = 'auto'
websocket-upgrade              = True
window-close                   = 'auto'
window-icon                    = ''
windows                        = True
wm-name                        = 'Xpra'
ws-auth                        = 
wss-auth                       = 
xsettings                      = 'auto'
xvfb                  (used)   = 'xpra_Xdummy -noreset -novtswitch -nolisten tcp  +extension GLX +extension RANDR +extension RENDER  -auth $XAUTHORITY -logfile ${XPRA_SESSION_DIR}/Xorg.log  -configdir "${XPRA_SESSION_DIR}/xorg.conf.d/$PID"  -config "${XORG_CONFIG_PREFIX}/etc/xpra/xorg.conf"'  <class 'str'>
xvfb                 (default) = '/usr/lib/Xorg -noreset -novtswitch -nolisten tcp +extension GLX +extension RANDR +extension RENDER -auth $XAUTHORITY -logfile ${XPRA_SESSION_DIR}/Xorg.log -configdir "${XPRA_SESSION_DIR}/xorg.conf.d/$PID" -config "${XORG_CONFIG_PREFIX}/etc/xpra/xorg.conf"'  <class 'str'>
</details>

Server desktop: Gnome
Client desktop: KDE
both on LAN
Client 3 monitors with diff resolutions

**Comment by totaam** [comment]
Please provide more details as per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs

**Comment by totaam** [comment]
> client xpra version: xpra v6.0-r0

You should upgrade to a more recent version.

> Client 3 monitors with diff resolutions

FYI this may cause problems if the total resolution is higher than what `Xvfb` can handle.

> Client desktop: KDE
> I could start programs via the tray icon

So, the tray icon usually work in KDE? Good to know.
(I can't remember the last time I've tried it)

> clicking in the "xpra" gui window on "browse", I don't see any sessions

This requires mDNS support to be installed and working properly on both systems.

> If I enter a command in "start xpra session" window e.g. firefox, then Firefox is started and I see the tray icon

Sorry it's taken so long to figure it out!
The trivial fix is in d6d153f8e1082ed9d4342ec4801b56c5690b0458.

The problem was that the `exit with application` checkbox was always selected, causing the session to terminate when there were no applications to run..
