### ISSUE TITLE
Starting with Automatic Encoding will disable quality menu

### ISSUE THREAD

**Issue by GUAN-Xihao** [Xpra-org/xpra#4427]
**Describe the bug**
Following by #4398 
Now in v6.2.1, if you start without --encoding option, the encoding will be recorded as "auto"
<img width="151" alt="image" src="https://github.com/user-attachments/assets/f6f7c0f6-86d3-4134-a4a3-dd1ed4148277">
If you manually click the auto option like #4398 describes, then due to the following code:
https://github.com/Xpra-org/xpra/blob/master/xpra/client/mixins/encodings.py#L302
The encoding will be "".

**To Reproduce**
1. Star Xpra, encoding is automatic and the quality menu is NOT available.
2. Now, click automatic encoding. Then quality menu is enabled. As the above screenshot shows.

**System Information (please complete the following information):**
 - Client OS: Windows 11
 - Xpra Client Version 6.2.0

**Comment by totaam** [comment]
What is the problem with having `encoding = ""`?
What behaviour does this change fix?

IIRC, the empty value has different semantics.

**Comment by GUAN-Xihao** [comment]
>What is the problem with having encoding = ""?
What behaviour does this change fix?
IIRC, the empty value has different semantics.

From commit 2c9301c,
`GENERIC_ENCODINGS = ("", "stream", "grayscale")`
You may choose to mark automatic encoding to "" either "auto"
But v6.2.1 behavior is 1) if you start without --encoding, then it will mark as "auto".
2) if you manually select encoding as automatic from the menu, then it will be marked as "".
You may use "auto" or "" on the above two statuses.

And the commit is trying use "auto" in both cases.

**Comment by GUAN-Xihao** [comment]
From your IIRC info, maybe 
`GENERIC_ENCODINGS = ("", "auto", "stream", "grayscale")`

is what you prefer. If so let me know and I can update the PR.

**Comment by totaam** [comment]
I will have to test this myself to understand. 
Hopefully tomorrow.

**Comment by GUAN-Xihao** [comment]
> I will have to test this myself to understand. Hopefully tomorrow.

Hi totaam, what do you think about it?
