### ISSUE TITLE
Xpra screen size shrinks, second monitor unusable after attaching from laptop with smaller display resolution

### ISSUE THREAD

**Issue by c0xc** [Xpra-org/xpra#4430]
**Describe the bug**
if I connect to an Xpra session from different clients with different monitor configurations, the available screen area seems to get limited to the smallest monitor configuration and outside of that area, I cannot click anything anymore. One client has a second monitor which cannot be used because windows on that monitor are not responsive anymore.

**To Reproduce**
0. Have an Xpra session running on some vm (`xpra start ... :10`).
1. From client 1, which is a desktop with 2 monitors, both set to 2560x1440, attach (`xpra attach .../10`), open and use various program windows.
2. From client 2, which is a laptop with a resolution of 1920x1080 and an external monitor which is not yet connected, attach.
3. From client 1, attach again. Now, any window that's on the second monitor or anywhere outside of the screen size of client 1 is unusable.

**Screen size**
1. When client 1 first attaches, the virtual screen size as shown by `xrandr | grep current` or `xdpyinfo | grep 'dimensions'` is 11520x6318 (vs. actual screen size of 5120x1440).
2. When client 2 attaches, the virtual screen size seems to be shrunk to the actual resolution of client 2, `xrandr` shows 1920x1080.
3. When client 1 attaches again, the virtual screen size apparently remains at 1920x1080 instead of being adjusted to the larger screen of client 1, `xrandr` still shows 1920x1080.

Workaround: Manually revert the screen size to the previous value:
```
$ xrandr | grep current
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 320 x 175, current 1920 x 1080, maximum 11520 x 6318

$ xrandr --output default --mode 11520x6318
xrandr: Failed to get size of gamma for output default

$ xrandr | grep current
xrandr: Failed to get size of gamma for output default
Screen 0: minimum 320 x 175, current 11520 x 6318, maximum 11520 x 6318
```

It seems either the virtual screen size should not be reduced when client 2 attaches or it should be restored (increased) when client 1 attaches afterwards.

**System Information (please complete the following information):**
 - Server OS: Fedora 39
 - Client OS: Fedora 39
 - Xpra Server Version: 6.2.1
 - Xpra Client Version: 6.2.1

**Additional context**
Am I missing something or is my expectation wrong? I tried to go over the logs and the docs.

**Comment by totaam** [comment]
> Fedora 39

This OS has been EOLed.

> When client 1 attaches again, the virtual screen size apparently remains at 1920x1080 instead of being adjusted to the larger screen of client 1, xrandr still shows 1920x1080

That's definitely wrong.
Please include the server log which should be showing the display resizing that occurs whenever the client resolution changes.
The client output may also be useful, it should print the display size detected.
As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs, please include any details that may have an impact on the client resolution detected: window manager, desktop scaling, etc.

> Workaround: Manually revert the screen size to the previous value:

This can have major unintended side-effects.

**Comment by totaam** [comment]
From an email:
> Previously, I had Xpra installed from the Fedora repo but I read that's not recommended and so I set up the xpra repo and installed it from there. Besides, there's "xorg-x11-drv-dummy-0.3.7-19.fc39.x86_64".

That's most definitely wrong.
The one you want is from the xpra repo and is at version 0.4.1:
https://github.com/Xpra-org/xpra/blob/7aa0a0ef86d188270ada3b1c4f931f7bfd96cd9a/packaging/rpm/xorg-x11-drv-dummy.spec#L11

**Comment by c0xc** [comment]
> This OS has been EOLed.
I see, EOLed since last Tuesday, oh well. Upgrading soon.

>  The one you want is from the xpra repo and is at version 0.4.1:
Thanks, I missed that one when reinstalling (only) xpra. Now it's up to date:
```
$ sudo dnf info xorg-x11-drv-dummy | grep -e From -e Version
Version      : 0.4.1
From repo    : xpra
```

In fact, it seems like this may have been the missing piece. The resolution returned by xrandr is now reverted to the original value when connecting from client 1 again! I'll double-check but if that's all, then it was just this package.

I'm attaching some logs just in case but I overwrote the log file from the server that I pulled when opening the issue.
[xpra_log_client1_0.log](https://github.com/user-attachments/files/17994203/xpra_log_client1_0.log)
[xpra_log_client1_2reconnect.log](https://github.com/user-attachments/files/17994204/xpra_log_client1_2reconnect.log)
[xpra_log_client1_beforeupdate_reconnect.log](https://github.com/user-attachments/files/17994205/xpra_log_client1_beforeupdate_reconnect.log)
[xpra_log_client2.log](https://github.com/user-attachments/files/17994206/xpra_log_client2.log)
[xpra_log_client2_2reconnect.log](https://github.com/user-attachments/files/17994207/xpra_log_client2_2reconnect.log)
[xpra_log_server.log](https://github.com/user-attachments/files/17994208/xpra_log_server.log)
[xpra_info_10.log](https://github.com/user-attachments/files/17994414/xpra_info_10.log)


Going over the list from the guidelines page:
* OS: Fedora 39, one client upgraded to 40 in the meantime (other upgrades postpones because of several new KDE issues in F40)
* Changes made to Xpra config: None, at least none I made manually. According to xpra showconfig, these keys differ from the default: env mdns pdf-printer postscript-printer socket-dirs start-env sync-xvfb xvfb (where the last one seems to be identical except for a whitespace)
* DE: All systems mentioned above currently run KDE/Plasma (window manager: KWin; originally all in X11).
* Both clients have desktop scaling ("global scale") set to 125% in KDE.
* Unusual setup: client 1 has 2 monitors, client 2 none when attaching, external monitor connected later
* Network: In this particular test, local [multi]gigabit LAN.
* Command: As above, xpra start :10 on the server and xpra attach ssh://server/10 on the clients
* $PATH: `/usr/libexec/xpra:/usr/local/bin:/usr/bin:/bin:/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin`; $LD_LIBRARY_PATH blank
* XPRA used to be installed from the Fedora repo, so I initially configured the XPRA repo and installed XPRA from there to get the latest version. One of the dependencies remained too old, causing a Python error (it tried to import some module which had been moved, forgot which one), so I reinstalled all of XPRA.
* Is this a new problem? No.
* Are there other bugs? Not sure. Keyboard layout switching didn't work, I even set up an extra layout on both server and client to make it obvious. But I haven't gone through the debugging steps for keyboard issues yet. And it seems off-topic.
* Unusual issues? Not sure, see above.
* Reproducible? Yes.
* Does this happen with all picture encodings? Didn't check, probably not relevant.
* Does switching off certain features make a difference? No.
* include relevant parts of the log files. Most of the time I actually focused on the log lines which mentioned the resolution ("client root window size is 5120x1440"), I did not notice an incorrect value there (except for the most recent test where the second client accidentally ran KDE/Wayland after upgrading but the logged value was correct when switching back to KDE/X11).
* Does re-connecting help? No.
* Does it happen with other type of clients? Didn't check / irrelevant.

```
$ sudo rpm -qa | grep xpra:
xpra-html5-10-1.r9.fc39.noarch
xpra-filesystem-6.2.1-10.r0.fc39.noarch
xpra-common-6.2.1-10.r0.fc39.x86_64
xpra-client-6.2.1-10.r0.fc39.x86_64
xpra-codecs-6.2.1-10.r0.fc39.x86_64
xpra-audio-6.2.1-10.r0.fc39.x86_64
xpra-client-gtk3-6.2.1-10.r0.fc39.x86_64
xpra-server-6.2.1-10.r0.fc39.x86_64
xpra-6.2.1-10.r0.fc39.x86_64
xpra-x11-6.2.1-10.r0.fc39.x86_64
xorg-x11-drv-dummy-0.4.1-1.xpra2.fc39.x86_64
```

**Comment by totaam** [comment]
> Both clients have desktop scaling ("global scale") set to 125% in KDE.

Then things aren't going to look great.

> Does it happen with other type of clients? Didn't check / irrelevant.

This would not be irrelevant. The builtin html5 client simulates a virtual screen matching the browser's window dimensions.

**Comment by totaam** [comment]
> I would change that to 100% if it helps debugging

It would not.
This is just a warning that scaling by 125% on the client side will result in blurry text in most cases, as xpra will be sending text at 100% resolution and the upscaling will be done client side.
