### ISSUE TITLE
PAM authentication bypassed with no username or password

### ISSUE THREAD

**Issue by Dovencio** [Xpra-org/xpra#4433]
**Describe the bug**
I'm unsure if I'm doing something incorrect, I have tried using TCP, WSS, SSL, and all of them seem to accept an empty username and password. I am using the default Debian 12 PAM config.

**To Reproduce**
1. Run the command `xpra start --bind-wss=0.0.0.0:10000,auth=pam`
2. Open browser and enter `https://XXX.XXX.XXX.XXX:10000/`
3. Observe client has remote access without getting authenticated

**System Information (please complete the following information):**
 - Server OS: Debian 12
 - Client OS: Debian 12, Mozilla Firefox 128.5.0esr / Android 13 Mozilla Firefox 133.0
 - Xpra Server Version: v6.2.1-r0
 - Xpra Client Version: v6.2.1-r0

**Additional context**
I've also tried `XPRA_PAM_CHECK_ACCOUNT=1` environment variable and `service=system-auth` (using the new comma separated auth options) and both at the same time found in bug #2085.  Using default /etc/pam.d/xpra file.
 
Log file: [server.log](https://github.com/user-attachments/files/18015192/server.log)

**Comment by totaam** [comment]
> `xpra start --bind-wss=0.0.0.0:10000,auth=pam`

This is not a valid command, you cannot use `bind-wss` without ssl options.

You're right that there is a bug.
Until it is fixed, please use `--wss-auth=pam`.

**Comment by totaam** [comment]
The bug: `bind-wss` and `bind-ssl` did not inherit the socket options.

This was not spotted earlier because the usual way of enabling `ssl` is to use `--bind-tcp` and let the xpra server upgrade to `ssl` or `wss`, and in these cases the socket options were preserved.

**Comment by totaam** [comment]
@MakiseKurisu please see the documentation, you're using the wrong syntax.
Use `--bind-tcp=127.0.0.1:14500,auth=pam` (preferably) or `--bind-tcp=127.0.0.1:14500 --tcp-auth=pam`.
