### ISSUE TITLE
MSWindows Manifest is invalid

### ISSUE THREAD

**Issue by GUAN-Xihao** [Xpra-org/xpra#4442]
**Describe the bug**
MSWindows Manifest is invalid, the XML schema `assemblyIdentity` under the schema `assembly` is required.
DPI Awareness PerMonitorV2 will not be affected due to invalid XML.
See https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests

**To Reproduce**
We may use mt.exe in Windows SDK to verify it.
```
&"Path_to_WinSDK\Windows Kits\10\bin\10.0.22621.0\x64\mt.exe" -validate_manifest -manifest "Path_to_Xpra\Xpra-x86_64_6.2.2-r0\Xpra_cmd.exe.manifest"

Xpra_cmd.exe.manifest : general error 10100ba: The manifest is missing the definition identity.
```

Run an Xpra_cmd with the XML file shipped with the official ZIP package. Using GetProcessDpiAwareness will find it is System DPI Aware.

**System Information (please complete the following information):**
 - Xpra Client Version 6.2.2 MSWindows Full Build

**Comment by totaam** [comment]
That took some effort: 0aaa53d5b3d42fba0859054bd8efa453118b8580

**Comment by GUAN-Xihao** [comment]
Thank you for your continued dedication to the Xpra project!
