### ISSUE TITLE
Unmet dependencies for Ubuntu with xpra-codecs (libwebp7)

### ISSUE THREAD

**Issue by V-ctor** [Xpra-org/xpra#4447]
Unmet dependencies for Ubuntu with xpra-codecs. xpra-codecs needs libwebp7 >= 1.4.0 but there is only 1.3.2-0.4build3.

**To Reproduce**
`apt install xpra-codecs`
reports
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. Perhaps what you are asking for is
not feasible, or you are using an unstable version of the distribution where
the packages you requested have not yet been built or have been removed from Incoming.
The following information may help:

The following packages have unmet dependencies:
xpra-codecs : Depends: libwebp7 (>= 1.4.0) but 1.3.2-0.4build3 must be installed
```
AFAIU there is no libwebp7-1.4.0.x in official Ubuntu repositories.
There is such packages in third party launchpad distribution [https://code.launchpad.net/ubuntu/+source/libwebp/1.4.0-0.1](https://code.launchpad.net/ubuntu/+source/libwebp/1.4.0-0.1)
But 
1. It is marked as unstable
2. It leads to broken packages when I tried to force it

Is it possible to work around? 
- May be reduce requirements for packages/library version?
- Rebuild/Repack as standalone application (AppImage/Snap/flatpack/docker)?

**System Information (please complete the following information):**
- Server OS: Kubuntu 24.10 (X server arm64 Oracle Cloud VM)
- Client OS: Kubuntu 24.10 (Wayland)
- Xpra v6.2.1-r0 (There is no 6.2.2 for arm64)
- Xpra v6.2.2-r0 (amd64)

**Comment by totaam** [comment]
The correct version of libwebp for Ubuntu 24.10 - aka Oracular is definitely `libwebp7` / aka `1.4.0`:
https://packages.ubuntu.com/oracular/libwebp7

The actual package that the DEB archive depends on is automagically generated.

Is this on `arm64` or `amd64`? (not clear from your description)
Installing on a `amd64` VM with `apt-get install xpra` worked just fine for me.

So I guess you're talking about `arm64`, then the problem is likely to be due to the missing 6.2.2 release - 6.2.1 must have been built before the actual Oracular release, before they bumped the `libwebp` version.
6.2.2 builds will eventually land for `arm64`, be patient - these things take a lot of time and effort.

**Comment by V-ctor** [comment]
> Is this on `arm64` or `amd64`? (not clear from your description)

It affects both amd64 and arm64. Both complains the same.
> Installing on a amd64 VM with `apt-get install xpra` worked just fine for me.

Interesting.
> The correct version of libwebp for Ubuntu 24.10 - aka Oracular is definitely libwebp7 / aka 1.4.0:
> https://packages.ubuntu.com/oracular/libwebp7

Alright, thank you. I'll see it again how to add it to list of repositories to be able to obtain.
Or did you install it as a single package by `dpkg -i libwebp7_1.4.0-0.1_amd64.deb` ?

>  6.2.2 builds will eventually land for arm64, be patient - these things take a lot of time and effort.
Is it possible to build by myself from sources?

**Comment by totaam** [comment]
> It affects both amd64 and arm64. Both complains the same.

Then you have made a mistake configuring the repositories.

> Is it possible to build by myself from sources?

This is fully documented:
https://github.com/Xpra-org/xpra/blob/master/docs/Build/Debian.md

**Comment by totaam** [comment]
FWIW: the buildbot environment was rebuilt recently, and `Oracular:arm64` was missing from the default target list: https://github.com/Xpra-org/repo-build-scripts/commit/4e5ed7e6d2db4422c365343006cef4ddcd28b44d

The xpra 6.2.2 Ubuntu Oracular arm64 builds are available now.

**Comment by V-ctor** [comment]
> The xpra 6.2.2 Ubuntu Oracular arm64 builds are available now.

Cool, thank you. I'll try it.

> Then you have made a mistake configuring the repositories.

The thing is that I updated to 24.10 from 24.04 and it didn't get this repository by default. I added it manually, updated (a lot of packages were updated) and got broken system lol. (K)ubuntu updating could be a big pain. I've been fixing it for two days. Now I almost fixed it (thanks to BTRFS snapshots) but Wayland session still does not work. I tried X11 and I get XPRA segfault. Did not go deeper.

```
xpra start ssh://victor@X --start-child=konsole
2024-12-21 15:02:55,827 Warning: missing 'xpra.audio' module
2024-12-21 15:02:55,827  for Python 3.12.7 (main, Oct  3 2024, 15:15:22) [GCC 14.2.0]
2024-12-21 15:02:55,871 Error: cannot find directory '/usr/share/xpra/css'

2024-12-21 15:02:55,928 Xpra GTK3 X11 client version 6.2.2-r0
splash: Error: cannot find directory '/usr/share/xpra/css'
2024-12-21 15:02:56,144  running on Linux Ubuntu 24.10 oracular
2024-12-21 15:02:56,144  cpython 3.12
2024-12-21 15:02:56,146  window manager is 'KWin'
2024-12-21 15:02:57,022 created unix domain sockets:
2024-12-21 15:02:57,022  '/run/user/1000/xpra/clients/victor-HP-255-G8-34820'
Segmentation fault (core dumped)
```
Tried to reinstall xpra with no luck

**Comment by totaam** [comment]
Probably built against the wrong glibc / xorg / whatever.
I would remove xpra before the upgrade, disable the xpra repositories.
Then re-enable afterwards.

**Comment by V-ctor** [comment]
I got segfault on client  (amd64) not on server (arm64).

**Comment by V-ctor** [comment]
May be something is still broken on my desktop after update that is why I get segfault.
In journalctl I can see:
```
gstglcontext[40463]: segfault at 7db700000011 ip 00007db7b53e12f3 sp 00007db7b25ff000 error 4 in radeonsi_drv_video.so[1e12f3,7db7b5259000+8e0000] likely on CPU 3 (core 1, socket 0)
Code: c3 31 c0 48 83 3b 00 74 07 44 39 63 08 0f 94 c0 5b 41 5c 5d c3 66 90 f3 0f 1e fa 55 48 89 f2 48 89 e5 53 48 89 fb 48 83 ec 08 <8b> 77 10 48 8b 3f e8 12 ee ff ff 48 8b 53 08 48 8b 5d f8 89 c0 0f
```
Looks that this issue connected with my integrated GPU Radeon driver. Probably because of new kernel 6.11 before this upgrade it was 6.8.

**Comment by V-ctor** [comment]
I fixed all my issues with repos and now it was installed properly. Sorry for bothering you.
