### ISSUE TITLE
at least one valid packet encoder must be enabled

### ISSUE THREAD

**Issue by doctorcolossus** [Xpra-org/xpra#4448]
```
$ xpra start ssh:jetson:100 --start=gnome-terminal
Warning: invalid compressor(s) specified: lzo
Warning: invalid packet encoder(s) specified: rencode, bencode, yaml
2024-12-20 18:40:33,909 Warning: invalid compressor lzo specified
2024-12-20 18:40:33,909 Warning: invalid compressor zlib specified
2024-12-20 18:40:33,912 Warning: invalid encoder 'rencode'
2024-12-20 18:40:33,912 Warning: invalid encoder 'bencode'
2024-12-20 18:40:33,912 Warning: invalid encoder 'yaml'
xpra initialization error:
 at least one valid packet encoder must be enabled
```

Okay, but how do I "enable" it?

Is there an argument to do this? (no match for "packet encoder" in the manpage)
Is it something that needs to be configured before building?
Is it about missing dependencies?

This error message doesn't help me understand how to proceed.

**Comment by totaam** [comment]
Simply use a supported version at both ends.

**Comment by totaam** [comment]
> On my remote Ubuntu 22.04 laptop I installed v6.2.2 

As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs
This is important.

> on the host Jetson I installed v5.0.3

Why would you install a version that is years out of date?

> Maybe I should try downgrading on the laptop to v5.0.3 to match?

Why downgrade to a more broken version?
It might work, with extra bugs.

> I just tried to install the highest possible on each

No. v5.0.3 is not the latest from the v5.x branch

> higher subversions of v5 triggered some Cython build error quite similar to

This is a known issue with Ubuntu and Debian shipping completely out of date versions of Cython.
More here: https://github.com/Xpra-org/xpra/wiki/Distribution-Packages

> In any case, I still think that the error message could use improvement.

The error message, of which we have literally tens of thousands, should never come up with a proper installation.

**Comment by totaam** [comment]
That's on way to go about things, but whatever.
Why build from source? We have arm64 packages.
Even building from source, I would just upgrade Cython rather than downgrade something else.
