### ISSUE TITLE
xpra erroneously sends meta key from windows

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#759]
*Issue migrated from trac ticket # 759*

**component:** client | **priority:** critical | **resolution:** worksforme | **keywords:** keyboard win32

#### 2014-12-06 00:00:21: tyler created the issue

___
> alt-meta is being sent to intellij when using the alt key. On x11, the alt key works as expected.
> 
> 
> 
> In emacs, gnome-terminal, and I assume others the meta key is stuck on after pressing windows-left (or any direction). Pressing windows twice after that un-sticks the meta key. Also not a problem in x11.
> 
> 
> 
> 
> If I log the keys from xev, a single press of the left direction key yeilds a sequence of about 10 `KeyRelease` and `KeyPress` events for `Alt_L`, `Alt_R`, `Meta_L`, and finally a release for Left. The final events for the modifier keys are all presses.
> 
> 
> 
> The intellij break happens no matter what and cannot be fixed by pressing the windows key twice.

**Comment by totaam** [comment]
Key mapping, and Alt / Meta in particular is really difficult to get right.
10 key events is quite excessive!

**Comment by totaam** [comment]
Oh!

That's got to be the weirdest bug I've seen in a long time!
Could this be opengl related? Can you try turning it off to see if it helps?

**Comment by totaam** [comment]
Please provide the opengl information, from the bug report tool or from the gl_check.py utility.
Then we can make it disabled by default on this broken driver.

**Comment by totaam** [comment]
[r8233](../commit/184e085da63fb7d9f1cb980725e7d898520a169b) will disable opengl automatically when we detect the "Software Rasterizer" - I may backport this to v0.14.x
I just hope that we're not unnecessarily penalizing other users.. can you tell us which distro and version you are using?
The big *libGL error:...* warnings are ominous.

Until then, you can turn off opengl by default on those systems using:
```
echo "opengl=no" >> ~/.xpra/xpra.conf
```

Note: we have digressed somewhat, this ticket was originally about key presses. And I still need to look into that.

**Comment by totaam** [comment]
There have not been any fixes to the keyboard code since 0.14.9.

So the problem may not be fixed, just not triggered yet after you re-installed.

**Comment by totaam** [comment]
I believe many of the extra keys that were being pressed were because we had various bugs in the forwarding and parsing of the keyboard data structures - these should be fixed by [r8477](../commit/45ca606b472d23edd05d6e1c4cd543a4530a18c4) + [r8475](../commit/55bf2e1c13edbff0ebab3dbb408d5240fb9cf66b) + [r8474](../commit/531eb887dcea6607e3b9c3d5eb9c75fe7954ecf6) (which will be backported to the 0.14.x branch).

As for `AltGr`, this is a tricky one (see #62) and I am very reluctant to go anywhere near it unless it can be proven to be a real blocker for something.

tyler: can I close this ticket?

**Comment by totaam** [comment]
Unless someone can give me steps to reproduce with win7, I will have to close this ticket as "worksforme".

**Comment by totaam** [comment]
@stdedos did you have a ticket to do with aerosnap somewhere? I can't find it and this is the closest thing to it.

I found [GTK windows with CSD are not being fully integrated to the Windows window manager](https://gitlab.gnome.org/GNOME/gtk/-/issues/2785#note_2539790) and [GdkWin32: AeroSnap shortcuts broken under CSD](https://gitlab.gnome.org/GNOME/gtk/-/issues/7738) which may cause problems with #2539

**Comment by stdedos** [comment]
> @stdedos) did you have a ticket to do with aerosnap somewhere? I can't find it and this is the closest thing to it.

Aaah, I think I know which one you mean ... 

Sadly, _now I am home_ 😅 
I'll try to dig it in a couple of days, though 😓 

However - it goes without saying. "If somehow you need to remove something for stability", chop at will 🙏
